In [65]:
import pandas as pd
import numpy as np
import importlib
import gc
import sys
import warnings
sys.path.append('./scripts')  
import preprocesamiento
import feature_engineering
import model_lgb
import model_lgb_keepsimple
importlib.reload(preprocesamiento)
importlib.reload(model_lgb)
importlib.reload(model_lgb_keepsimple)
importlib.reload(feature_engineering)
warnings.filterwarnings("ignore")

# Experimento 7: 
- LGBM
- Usando funcion entrenamiento: model_lgb.semillerio_en_prediccion(train, test, version="v1")
- optuna = sqlite:///optuna_studies_v14.db
- Kaggle =

##### Levantamos el dataset con target ya calculado

In [37]:
df = pd.read_csv("./datasets/periodo_x_producto_con_target.csv", sep=',', encoding='utf-8')
df.shape

(31362, 19)

In [25]:
df[df['target'].isna()][['product_id', 'periodo', 'tn', 'target']]
# 20034 , 201905

       product_id  periodo          tn  target
34          20001   201911  1397.37231     NaN
35          20001   201912  1504.68856     NaN
70          20002   201911  1423.57739     NaN
71          20002   201912  1087.30855     NaN
106         20003   201911   948.29393     NaN
...           ...      ...         ...     ...
31344       21274   201708     0.00867     NaN
31353       21276   201911     0.03341     NaN
31354       21276   201912     0.00892     NaN
31360       21281   201707     0.00000     NaN
31361       21281   201708     0.03500     NaN

[2328 rows x 4 columns]

In [26]:
columnas_baseline = df.columns.tolist()
columnas_baseline

['product_id',
 'periodo',
 'nacimiento_producto',
 'muerte_producto',
 'mes_n',
 'total_meses',
 'producto_nuevo',
 'ciclo_de_vida_inicial',
 'cat1',
 'cat2',
 'cat3',
 'brand',
 'sku_size',
 'stock_final',
 'tn',
 'plan_precios_cuidados',
 'cust_request_qty',
 'cust_request_tn',
 'target']

##### Preprocesamiento a la minima expresión :)

In [38]:
df = feature_engineering.create_category_features_cat1(df)
df = feature_engineering.create_category_features_cat2(df)
df = feature_engineering.create_category_features_cat3(df)

##### aplicamos OHE
# df = preprocesamiento.aplicarOHE(df)
df.shape

(31362, 28)

### Feature Engineering

##### Neural Prophet

In [40]:
neural_prophet_fe = pd.read_csv("./datasets/features_neuralprophet_completo.csv", sep=',', encoding='utf-8')
neural_prophet_fe['ds'] = pd.to_datetime(neural_prophet_fe['ds'], errors='coerce')
# Versión alternativa más robusta:
neural_prophet_fe['periodo'] = neural_prophet_fe['ds'].apply(
    lambda x: x.year * 100 + x.month if pd.notnull(x) else None
)
neural_prophet_fe = neural_prophet_fe[['periodo', 'product_id', 'trend', "season_yearly", "season_monthly"]]
df = df.merge(neural_prophet_fe, on=['periodo', 'product_id'], how='left')
df.shape

(31362, 31)

##### Prophet

In [41]:
prophet_fe = pd.read_csv("./datasets/prophet_features_tn_zscore.csv", sep=',', encoding='utf-8')
prophet_fe['ds'] = pd.to_datetime(prophet_fe['ds'], errors='coerce')
prophet_fe['periodo'] = prophet_fe['ds'].apply(
    lambda x: x.year * 100 + x.month if pd.notnull(x) else None
)
prophet_fe = prophet_fe[['periodo', 'product_id', 'trend_add', "yearly_add", "additive_terms", 'trend_mult', 'yearly_mult', 'multiplicative_terms']]
df = df.merge(prophet_fe, on=['periodo', 'product_id'], how='left')
df.shape

(31362, 37)

##### FE Moviles

In [43]:
df = feature_engineering.get_lags(df, "tn", 201912)
df = feature_engineering.get_delta_lags(df, "tn", 24)
df = feature_engineering.get_rolling_means(df, "tn", 201912)
df = feature_engineering.get_rolling_stds(df, "tn", 201912)
df = feature_engineering.get_rolling_mins(df, "tn", 201912)
df = feature_engineering.get_rolling_maxs(df, "tn", 201912)
df = feature_engineering.get_rolling_medians(df, "tn", 201912)
df = feature_engineering.get_rolling_skewness(df, "tn", 201912)
df = feature_engineering.get_autocorrelaciones(df, "tn", 201912)
df.shape

(31362, 599)

In [8]:
df = feature_engineering.get_lags(df, "cust_request_qty", 201912)
df = feature_engineering.get_delta_lags(df, "cust_request_qty", 24)
df = feature_engineering.get_rolling_means(df, "cust_request_qty", 201912)
df = feature_engineering.get_rolling_stds(df, "cust_request_qty", 201912)
df = feature_engineering.get_rolling_mins(df, "cust_request_qty", 201912)
df = feature_engineering.get_rolling_maxs(df, "cust_request_qty", 201912)

In [ ]:
df = feature_engineering.get_lags(df, "cust_request_qty", 201912)
df = feature_engineering.get_delta_lags(df, "cust_request_qty", 24)
df = feature_engineering.get_rolling_means(df, "cust_request_qty", 201912)
df = feature_engineering.get_rolling_stds(df, "cust_request_qty", 201912)
df = feature_engineering.get_rolling_mins(df, "cust_request_qty", 201912)
df = feature_engineering.get_rolling_maxs(df, "cust_request_qty", 201912)
df.shape

(31362, 1500)

##### FE Diana

In [45]:
df = feature_engineering.calcular_diferencia_con_medias_moviles(df)
df = feature_engineering.calcular_ratios_con_medias_moviles(df)
df.shape

(31362, 635)

##### FE Moviles sobre otras variables

In [56]:
# #  stock final
# df = feature_engineering.get_lagsEspecificos(df, col='stock_final_zscore')
# df = feature_engineering.get_delta_lags_especificos(df, col='stock_final_zscore')
# df = feature_engineering.get_rolling_means_especificos(df, col='stock_final_zscore')
# df = feature_engineering.get_rolling_stds_especificos(df, col='stock_final_zscore')
# df = feature_engineering.get_rolling_medians_especificos(df, col='stock_final_zscore')
# df = feature_engineering.get_rolling_mins_especificos(df, col='stock_final_zscore')
# df = feature_engineering.get_rolling_maxs_especificos(df, col='stock_final_zscore')
# df = feature_engineering.get_rolling_skewness_especificos(df, col='stock_final_zscore')

#  cust_request_qty
# df = feature_engineering.get_lagsEspecificos(df, col='cust_request_qty')
# df = feature_engineering.get_delta_lags_especificos(df, col='cust_request_qty')
# df = feature_engineering.get_rolling_means_especificos(df, col='cust_request_qty')
# df = feature_engineering.get_rolling_stds_especificos(df, col='cust_request_qty')
# df = feature_engineering.get_rolling_mins_especificos(df, col='cust_request_qty')
# df = feature_engineering.get_rolling_maxs_especificos(df, col='cust_request_qty')
# df = feature_engineering.get_rolling_medians_especificos(df, col='cust_request_qty')
# df = feature_engineering.get_rolling_skewness_especificos(df, col='cust_request_qty')

##### FE Calendario

In [47]:
df = feature_engineering.generar_ids(df)
df = feature_engineering.get_componentesTemporales(df)
df = feature_engineering.get_anomaliasPoliticas(df)
# df = feature_engineering.descomposicion_serie_temporal(df, col='tn')
df.shape

(31362, 660)

##### FE sobre FE

In [33]:
df = feature_engineering.chatGPT_features_serie(df, "tn")
df = feature_engineering.mes_con_feriado(df)
df.shape

(31362, 689)

##### Variables Exogenas

In [49]:
df = feature_engineering.get_dolar(df)
df = feature_engineering.get_IPC(df)
df['ipc'] = df['ipc'].str.replace(',', '.').astype(float)
df['dolar'] = df['dolar'].str.replace(',', '.').astype(float)
# df.drop(columns=['ds'], inplace=True)
#df.fillna(0, inplace=True) ##### EXPERIMENTAR
df = feature_engineering.correlacion_exogenas(df)
df = feature_engineering.get_mes_receso_escolar(df)
df.shape

(31362, 666)

##### Nuevas FE

In [52]:
df = feature_engineering.create_ratio_features(df)
df = feature_engineering.enhance_lifecycle_features(df)
# df = feature_engineering.create_category_features(df)
df = feature_engineering.create_regime_features(df)
df = feature_engineering.create_nonlinear_trends(df)
df = feature_engineering.create_temporal_interactions(df)
df = feature_engineering.create_asymmetric_window_features(df)
# df = feature_engineering.recomendaciones_deepseek(df)
df = feature_engineering.get_nuevas_features(df)
df.shape

(31362, 702)

##### Ceros

In [ ]:
df = feature_engineering.agregar_ceros_consecutivos_atras(df, col_tn='tn_original')
df = feature_engineering.agregar_no_ceros_consecutivos_atras(df, col_tn='tn_original')
df = feature_engineering.agregar_ceros_ultimos_n_meses(df, ventanas=[1,2,3,4,5,6,12], col_tn='tn_original')
df = feature_engineering.agregar_min_max_ult_n(df, n_list=(1,2,3,4,5,6,12), col_tn='tn_original')
df.shape

##### Elimino aquellas que no sirven

In [13]:
importantes = pd.read_csv("./feature_importance/exp04_3.csv", sep=',', encoding='utf-8')
no_importantes = importantes[importantes['importance'] <= 100]
no_importantes = no_importantes[~no_importantes['feature'].isin(columnas_baseline)]
no_importantes

                  feature  importance
67        tn_vs_prev_year         100
68     tn_delta_lag5_lag8          99
69       tn_rolling_min_4          96
70               tn_lag_5          95
71       tn_rolling_std_6          95
..                    ...         ...
677          dia_del_year           0
678               cat2_TE           0
680            cat2_PIEL1           0
681            cat2_OTROS           0
682  tn_is_outlier_3sigma           0

[608 rows x 2 columns]

In [14]:
cols_a_eliminar = no_importantes.feature.unique()
print(f"Antes de eliminar: {df.shape[1]} columnas")
df = df.drop(columns=cols_a_eliminar, errors='ignore')
print(f"Después de eliminar: {df.shape[1]} columnas")

Antes de eliminar: 1144 columnas
Después de eliminar: 684 columnas

Eliminar object/categorical columnas

In [15]:
df = df.select_dtypes(exclude=['datetime', 'datetime64', 'object'])

Train Test Split

In [54]:
training = [
    201701, 201702, 201703, 201704, 201705, 201706, 201707, 201708, 201709,
    201710, 201711, 201712, 201801, 201802, 201803, 201804, 201805,
    201806, 201807, 201808, 201809, 201810, 201811, 201812,
    201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908
]

validation = [
    201909
]


testing = [
    201910
]

prediction = [
    201912  
]

In [55]:
df_train = df[df['periodo'].isin(training)].copy()
df_val = df[df['periodo'].isin(validation)].copy()
df_test = df[df['periodo'].isin(testing)].copy()
df_pred = df[df['periodo'].isin(prediction)].copy()

gc.collect()

327

Entrenamiento

In [59]:
# Hay casos como este donde el producto muere en 2019006, por lo tanto tienen los dos ultimos target vacios.
# df_train[df_train['product_id']==20034][['product_id', 'periodo', 'tn', 'target']]
# 20034 , 201905

In [60]:
df_train['target'].fillna(0, inplace=True)
df_val['target'].fillna(0, inplace=True)
df_test['target'].fillna(0, inplace=True)

In [61]:
model_lgb_keepsimple.optimizar_con_optuna_sin5FCV_con_semillerio_db(df_train=df_train, df_val=df_val, version="v24")

Para visualizar los resultados en tiempo real:
1. Abre otra terminal y ejecuta:
   optuna-dashboard sqlite:///optuna_studies_v24.db
2. Abre en tu navegador: http://127.0.0.1:8080/

[I 2025-07-15 20:59:12,223] Using an existing study with name 'lightgbm_optimization_v24' instead of creating a new one.
[I 2025-07-15 20:59:43,700] Trial 2 finished with value: 0.24713381488498531 and parameters: {'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}. Best is trial 2 with value: 0.24713381488498531.

Mejor trial hasta ahora: TFE=0.247134, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-15 21:00:56,806] Trial 3 finished with value: 0.27233624554335006 and parameters: {'num_leaves': 41, 'learning_rate': 0.05958389350068958, 'feature_fraction': 0.7727780074568463, 'bagging_fraction': 0.7873687420594125, 'bagging_freq': 7, 'lambda_l1': 1.8007140198129195e-07, 'lambda_l2': 4.258943089524393e-06, 'min_child_samples': 25, 'max_depth': 6, 'max_bin': 414, 'min_data_in_leaf': 36, 'extra_trees': False, 'early_stopping_rounds': 11, 'path_smooth': 0.6075448519014384, 'min_gain_to_split': 0.08526206184364576}. Best is trial 2 with value: 0.24713381488498531.

Mejor trial hasta ahora: TFE=0.247134, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-15 21:01:17,060] Trial 4 finished with value: 0.25583184448323804 and parameters: {'num_leaves': 20, 'learning_rate': 0.2521267904777921, 'feature_fraction': 0.9862528132298237, 'bagging_fraction': 0.9425192044349383, 'bagging_freq': 4, 'lambda_l1': 7.569183361880229e-08, 'lambda_l2': 0.014391207615728067, 'min_child_samples': 28, 'max_depth': 3, 'max_bin': 298, 'min_data_in_leaf': 22, 'extra_trees': True, 'early_stopping_rounds': 37, 'path_smooth': 0.31171107608941095, 'min_gain_to_split': 0.2600340105889054}. Best is trial 2 with value: 0.24713381488498531.

Mejor trial hasta ahora: TFE=0.247134, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-15 21:02:19,630] Trial 5 finished with value: 0.27258488285229876 and parameters: {'num_leaves': 62, 'learning_rate': 0.01875220945578641, 'feature_fraction': 0.9878338511058234, 'bagging_fraction': 0.9325398470083344, 'bagging_freq': 10, 'lambda_l1': 1.1309571585271483, 'lambda_l2': 0.002404915432737351, 'min_child_samples': 47, 'max_depth': 3, 'max_bin': 178, 'min_data_in_leaf': 23, 'extra_trees': False, 'early_stopping_rounds': 21, 'path_smooth': 0.8287375091519293, 'min_gain_to_split': 0.17837666334679464}. Best is trial 2 with value: 0.24713381488498531.

Mejor trial hasta ahora: TFE=0.247134, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-15 21:02:55,683] Trial 6 finished with value: 0.26206530814519396 and parameters: {'num_leaves': 39, 'learning_rate': 0.06333268775321843, 'feature_fraction': 0.6563696899899051, 'bagging_fraction': 0.9406590942262119, 'bagging_freq': 1, 'lambda_l1': 7.620481786158549, 'lambda_l2': 0.08916674715636537, 'min_child_samples': 18, 'max_depth': 3, 'max_bin': 427, 'min_data_in_leaf': 77, 'extra_trees': False, 'early_stopping_rounds': 13, 'path_smooth': 0.3584657285442726, 'min_gain_to_split': 0.05793452976256486}. Best is trial 2 with value: 0.24713381488498531.

Mejor trial hasta ahora: TFE=0.247134, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-15 21:04:25,758] Trial 7 finished with value: 0.2704125498124754 and parameters: {'num_leaves': 89, 'learning_rate': 0.08330803890301997, 'feature_fraction': 0.7323592099410596, 'bagging_fraction': 0.7190675050858071, 'bagging_freq': 4, 'lambda_l1': 8.445977074223802e-06, 'lambda_l2': 0.036851536911881845, 'min_child_samples': 36, 'max_depth': 10, 'max_bin': 289, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 33, 'path_smooth': 0.770967179954561, 'min_gain_to_split': 0.24689779818219537}. Best is trial 2 with value: 0.24713381488498531.

Mejor trial hasta ahora: TFE=0.247134, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-15 21:05:56,102] Trial 8 finished with value: 0.23877096673712206 and parameters: {'num_leaves': 59, 'learning_rate': 0.042808491617570936, 'feature_fraction': 0.610167650697638, 'bagging_fraction': 0.7323674280979913, 'bagging_freq': 1, 'lambda_l1': 0.005341874754868531, 'lambda_l2': 6.748446817464346e-06, 'min_child_samples': 30, 'max_depth': 10, 'max_bin': 199, 'min_data_in_leaf': 53, 'extra_trees': True, 'early_stopping_rounds': 13, 'path_smooth': 0.289751452913768, 'min_gain_to_split': 0.08061064362700221}. Best is trial 8 with value: 0.23877096673712206.

Mejor trial hasta ahora: TFE=0.238771, Parámetros={'num_leaves': 59, 'learning_rate': 0.042808491617570936, 'feature_fraction': 0.610167650697638, 'bagging_fraction': 0.7323674280979913, 'bagging_freq': 1, 'lambda_l1': 0.005341874754868531, 'lambda_l2': 6.748446817464346e-06, 'min_child_samples': 30, 'max_depth': 10, 'max_bin': 199, 'min_data_in_leaf': 53, 'extra_trees': True, 'early_stopping_rounds': 13, 'path_smooth': 0.289751452913768, 'min_gain_to_split': 0.08061064362700221}

[I 2025-07-15 21:07:33,345] Trial 9 finished with value: 0.2727851406054954 and parameters: {'num_leaves': 94, 'learning_rate': 0.156203869845265, 'feature_fraction': 0.8533615026041694, 'bagging_fraction': 0.9614381770563153, 'bagging_freq': 9, 'lambda_l1': 4.776728196949699e-07, 'lambda_l2': 1.0790237065789294, 'min_child_samples': 32, 'max_depth': 9, 'max_bin': 459, 'min_data_in_leaf': 45, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.8180147659224931, 'min_gain_to_split': 0.4303652916281717}. Best is trial 8 with value: 0.23877096673712206.

Mejor trial hasta ahora: TFE=0.238771, Parámetros={'num_leaves': 59, 'learning_rate': 0.042808491617570936, 'feature_fraction': 0.610167650697638, 'bagging_fraction': 0.7323674280979913, 'bagging_freq': 1, 'lambda_l1': 0.005341874754868531, 'lambda_l2': 6.748446817464346e-06, 'min_child_samples': 30, 'max_depth': 10, 'max_bin': 199, 'min_data_in_leaf': 53, 'extra_trees': True, 'early_stopping_rounds': 13, 'path_smooth': 0.289751452913768, 'min_gain_to_split': 0.08061064362700221}

[I 2025-07-15 21:08:47,372] Trial 10 finished with value: 0.24103846395065576 and parameters: {'num_leaves': 15, 'learning_rate': 0.05681142678077596, 'feature_fraction': 0.7669644012595116, 'bagging_fraction': 0.7666323431412191, 'bagging_freq': 2, 'lambda_l1': 1.0927895733904103e-05, 'lambda_l2': 3.0632845126552133, 'min_child_samples': 23, 'max_depth': 7, 'max_bin': 381, 'min_data_in_leaf': 49, 'extra_trees': True, 'early_stopping_rounds': 20, 'path_smooth': 0.49724850589238545, 'min_gain_to_split': 0.15043915490838483}. Best is trial 8 with value: 0.23877096673712206.

Mejor trial hasta ahora: TFE=0.238771, Parámetros={'num_leaves': 59, 'learning_rate': 0.042808491617570936, 'feature_fraction': 0.610167650697638, 'bagging_fraction': 0.7323674280979913, 'bagging_freq': 1, 'lambda_l1': 0.005341874754868531, 'lambda_l2': 6.748446817464346e-06, 'min_child_samples': 30, 'max_depth': 10, 'max_bin': 199, 'min_data_in_leaf': 53, 'extra_trees': True, 'early_stopping_rounds': 13, 'path_smooth': 0.289751452913768, 'min_gain_to_split': 0.08061064362700221}

[I 2025-07-15 21:12:14,652] Trial 11 finished with value: 0.26816441511712485 and parameters: {'num_leaves': 39, 'learning_rate': 0.011336695817840537, 'feature_fraction': 0.8438257335919588, 'bagging_fraction': 0.8508037069686585, 'bagging_freq': 1, 'lambda_l1': 3.21972053981427e-06, 'lambda_l2': 1.49414578394363, 'min_child_samples': 19, 'max_depth': 4, 'max_bin': 296, 'min_data_in_leaf': 99, 'extra_trees': False, 'early_stopping_rounds': 41, 'path_smooth': 0.23763754399239967, 'min_gain_to_split': 0.3641081743059298}. Best is trial 8 with value: 0.23877096673712206.

Mejor trial hasta ahora: TFE=0.238771, Parámetros={'num_leaves': 59, 'learning_rate': 0.042808491617570936, 'feature_fraction': 0.610167650697638, 'bagging_fraction': 0.7323674280979913, 'bagging_freq': 1, 'lambda_l1': 0.005341874754868531, 'lambda_l2': 6.748446817464346e-06, 'min_child_samples': 30, 'max_depth': 10, 'max_bin': 199, 'min_data_in_leaf': 53, 'extra_trees': True, 'early_stopping_rounds': 13, 'path_smooth': 0.289751452913768, 'min_gain_to_split': 0.08061064362700221}

[I 2025-07-15 21:13:21,059] Trial 12 finished with value: 0.2390565227449309 and parameters: {'num_leaves': 70, 'learning_rate': 0.029068799010326083, 'feature_fraction': 0.6030189277265172, 'bagging_fraction': 0.7053885626844458, 'bagging_freq': 6, 'lambda_l1': 0.016301353379407614, 'lambda_l2': 1.785697818123025e-05, 'min_child_samples': 11, 'max_depth': 9, 'max_bin': 104, 'min_data_in_leaf': 67, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.07644843397269116, 'min_gain_to_split': 0.016311559769174172}. Best is trial 8 with value: 0.23877096673712206.

Mejor trial hasta ahora: TFE=0.238771, Parámetros={'num_leaves': 59, 'learning_rate': 0.042808491617570936, 'feature_fraction': 0.610167650697638, 'bagging_fraction': 0.7323674280979913, 'bagging_freq': 1, 'lambda_l1': 0.005341874754868531, 'lambda_l2': 6.748446817464346e-06, 'min_child_samples': 30, 'max_depth': 10, 'max_bin': 199, 'min_data_in_leaf': 53, 'extra_trees': True, 'early_stopping_rounds': 13, 'path_smooth': 0.289751452913768, 'min_gain_to_split': 0.08061064362700221}

[I 2025-07-15 21:14:32,151] Trial 13 finished with value: 0.2423800016782658 and parameters: {'num_leaves': 70, 'learning_rate': 0.03277504540244485, 'feature_fraction': 0.6016809725144093, 'bagging_fraction': 0.7023704528366805, 'bagging_freq': 6, 'lambda_l1': 0.007816957762452724, 'lambda_l2': 2.0765916893298003e-05, 'min_child_samples': 11, 'max_depth': 9, 'max_bin': 105, 'min_data_in_leaf': 73, 'extra_trees': True, 'early_stopping_rounds': 50, 'path_smooth': 0.0519846601327208, 'min_gain_to_split': 0.00158505126253837}. Best is trial 8 with value: 0.23877096673712206.

Mejor trial hasta ahora: TFE=0.238771, Parámetros={'num_leaves': 59, 'learning_rate': 0.042808491617570936, 'feature_fraction': 0.610167650697638, 'bagging_fraction': 0.7323674280979913, 'bagging_freq': 1, 'lambda_l1': 0.005341874754868531, 'lambda_l2': 6.748446817464346e-06, 'min_child_samples': 30, 'max_depth': 10, 'max_bin': 199, 'min_data_in_leaf': 53, 'extra_trees': True, 'early_stopping_rounds': 13, 'path_smooth': 0.289751452913768, 'min_gain_to_split': 0.08061064362700221}

[I 2025-07-15 21:16:02,601] Trial 14 finished with value: 0.23936215237855932 and parameters: {'num_leaves': 76, 'learning_rate': 0.028280029125359214, 'feature_fraction': 0.6610851111345213, 'bagging_fraction': 0.772466479894102, 'bagging_freq': 7, 'lambda_l1': 0.0063396191326126295, 'lambda_l2': 1.1152289337655545e-06, 'min_child_samples': 10, 'max_depth': 10, 'max_bin': 184, 'min_data_in_leaf': 63, 'extra_trees': True, 'early_stopping_rounds': 49, 'path_smooth': 0.07966474866055566, 'min_gain_to_split': 0.024600987934401332}. Best is trial 8 with value: 0.23877096673712206.

Mejor trial hasta ahora: TFE=0.238771, Parámetros={'num_leaves': 59, 'learning_rate': 0.042808491617570936, 'feature_fraction': 0.610167650697638, 'bagging_fraction': 0.7323674280979913, 'bagging_freq': 1, 'lambda_l1': 0.005341874754868531, 'lambda_l2': 6.748446817464346e-06, 'min_child_samples': 30, 'max_depth': 10, 'max_bin': 199, 'min_data_in_leaf': 53, 'extra_trees': True, 'early_stopping_rounds': 13, 'path_smooth': 0.289751452913768, 'min_gain_to_split': 0.08061064362700221}

[I 2025-07-15 21:17:29,046] Trial 15 finished with value: 0.2385570417348099 and parameters: {'num_leaves': 80, 'learning_rate': 0.033771878346500646, 'feature_fraction': 0.6009839266623576, 'bagging_fraction': 0.738347297284792, 'bagging_freq': 4, 'lambda_l1': 0.002087014542499813, 'lambda_l2': 0.00015048681978212022, 'min_child_samples': 38, 'max_depth': 8, 'max_bin': 101, 'min_data_in_leaf': 60, 'extra_trees': True, 'early_stopping_rounds': 43, 'path_smooth': 0.003671708045375116, 'min_gain_to_split': 0.14750719687627886}. Best is trial 15 with value: 0.2385570417348099.

Mejor trial hasta ahora: TFE=0.238557, Parámetros={'num_leaves': 80, 'learning_rate': 0.033771878346500646, 'feature_fraction': 0.6009839266623576, 'bagging_fraction': 0.738347297284792, 'bagging_freq': 4, 'lambda_l1': 0.002087014542499813, 'lambda_l2': 0.00015048681978212022, 'min_child_samples': 38, 'max_depth': 8, 'max_bin': 101, 'min_data_in_leaf': 60, 'extra_trees': True, 'early_stopping_rounds': 43, 'path_smooth': 0.003671708045375116, 'min_gain_to_split': 0.14750719687627886}

[I 2025-07-15 21:19:02,456] Trial 16 finished with value: 0.24921786243466038 and parameters: {'num_leaves': 55, 'learning_rate': 0.11081843062045608, 'feature_fraction': 0.6986809916245451, 'bagging_fraction': 0.8125258125825939, 'bagging_freq': 4, 'lambda_l1': 0.0002648976777559709, 'lambda_l2': 0.000322744962439201, 'min_child_samples': 38, 'max_depth': 8, 'max_bin': 195, 'min_data_in_leaf': 57, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.38291340768503, 'min_gain_to_split': 0.1671876770805229}. Best is trial 15 with value: 0.2385570417348099.

Mejor trial hasta ahora: TFE=0.238557, Parámetros={'num_leaves': 80, 'learning_rate': 0.033771878346500646, 'feature_fraction': 0.6009839266623576, 'bagging_fraction': 0.738347297284792, 'bagging_freq': 4, 'lambda_l1': 0.002087014542499813, 'lambda_l2': 0.00015048681978212022, 'min_child_samples': 38, 'max_depth': 8, 'max_bin': 101, 'min_data_in_leaf': 60, 'extra_trees': True, 'early_stopping_rounds': 43, 'path_smooth': 0.003671708045375116, 'min_gain_to_split': 0.14750719687627886}

[I 2025-07-15 21:20:26,065] Trial 17 finished with value: 0.24483375611291094 and parameters: {'num_leaves': 81, 'learning_rate': 0.03561002028757219, 'feature_fraction': 0.6593942321100332, 'bagging_fraction': 0.7382843618519671, 'bagging_freq': 3, 'lambda_l1': 0.0005426067912868092, 'lambda_l2': 2.6502328992620956e-07, 'min_child_samples': 41, 'max_depth': 6, 'max_bin': 220, 'min_data_in_leaf': 86, 'extra_trees': True, 'early_stopping_rounds': 43, 'path_smooth': 0.9669020441022618, 'min_gain_to_split': 0.25602994180637456}. Best is trial 15 with value: 0.2385570417348099.

Mejor trial hasta ahora: TFE=0.238557, Parámetros={'num_leaves': 80, 'learning_rate': 0.033771878346500646, 'feature_fraction': 0.6009839266623576, 'bagging_fraction': 0.738347297284792, 'bagging_freq': 4, 'lambda_l1': 0.002087014542499813, 'lambda_l2': 0.00015048681978212022, 'min_child_samples': 38, 'max_depth': 8, 'max_bin': 101, 'min_data_in_leaf': 60, 'extra_trees': True, 'early_stopping_rounds': 43, 'path_smooth': 0.003671708045375116, 'min_gain_to_split': 0.14750719687627886}

[I 2025-07-15 21:22:47,226] Trial 18 finished with value: 0.23134505653663795 and parameters: {'num_leaves': 85, 'learning_rate': 0.01686868883631449, 'feature_fraction': 0.7038735369549389, 'bagging_fraction': 0.8102068001045296, 'bagging_freq': 3, 'lambda_l1': 0.12278690506092826, 'lambda_l2': 0.0001229859781469921, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 145, 'min_data_in_leaf': 49, 'extra_trees': True, 'early_stopping_rounds': 32, 'path_smooth': 0.00034158099459036815, 'min_gain_to_split': 0.13323950745284918}. Best is trial 18 with value: 0.23134505653663795.

Mejor trial hasta ahora: TFE=0.231345, Parámetros={'num_leaves': 85, 'learning_rate': 0.01686868883631449, 'feature_fraction': 0.7038735369549389, 'bagging_fraction': 0.8102068001045296, 'bagging_freq': 3, 'lambda_l1': 0.12278690506092826, 'lambda_l2': 0.0001229859781469921, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 145, 'min_data_in_leaf': 49, 'extra_trees': True, 'early_stopping_rounds': 32, 'path_smooth': 0.00034158099459036815, 'min_gain_to_split': 0.13323950745284918}

[I 2025-07-15 21:24:11,157] Trial 19 finished with value: 0.23200970877949043 and parameters: {'num_leaves': 99, 'learning_rate': 0.015999577212409074, 'feature_fraction': 0.7076083274519943, 'bagging_fraction': 0.8310604354926014, 'bagging_freq': 5, 'lambda_l1': 0.9271619949217428, 'lambda_l2': 0.00023081872758193387, 'min_child_samples': 35, 'max_depth': 5, 'max_bin': 127, 'min_data_in_leaf': 40, 'extra_trees': True, 'early_stopping_rounds': 33, 'path_smooth': 0.16434365252616934, 'min_gain_to_split': 0.33404193824642164}. Best is trial 18 with value: 0.23134505653663795.

Mejor trial hasta ahora: TFE=0.231345, Parámetros={'num_leaves': 85, 'learning_rate': 0.01686868883631449, 'feature_fraction': 0.7038735369549389, 'bagging_fraction': 0.8102068001045296, 'bagging_freq': 3, 'lambda_l1': 0.12278690506092826, 'lambda_l2': 0.0001229859781469921, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 145, 'min_data_in_leaf': 49, 'extra_trees': True, 'early_stopping_rounds': 32, 'path_smooth': 0.00034158099459036815, 'min_gain_to_split': 0.13323950745284918}

[I 2025-07-15 21:26:34,940] Trial 20 finished with value: 0.2265615761756715 and parameters: {'num_leaves': 100, 'learning_rate': 0.010295275433610978, 'feature_fraction': 0.7147606750227061, 'bagging_fraction': 0.836754044248871, 'bagging_freq': 5, 'lambda_l1': 0.28040224426271043, 'lambda_l2': 0.0004165950761243581, 'min_child_samples': 50, 'max_depth': 5, 'max_bin': 248, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 33, 'path_smooth': 0.16448804475298406, 'min_gain_to_split': 0.34455780466539554}. Best is trial 20 with value: 0.2265615761756715.

Mejor trial hasta ahora: TFE=0.226562, Parámetros={'num_leaves': 100, 'learning_rate': 0.010295275433610978, 'feature_fraction': 0.7147606750227061, 'bagging_fraction': 0.836754044248871, 'bagging_freq': 5, 'lambda_l1': 0.28040224426271043, 'lambda_l2': 0.0004165950761243581, 'min_child_samples': 50, 'max_depth': 5, 'max_bin': 248, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 33, 'path_smooth': 0.16448804475298406, 'min_gain_to_split': 0.34455780466539554}

[I 2025-07-15 21:29:55,646] Trial 21 finished with value: 0.226001919421211 and parameters: {'num_leaves': 90, 'learning_rate': 0.010064438320933452, 'feature_fraction': 0.8100100345176875, 'bagging_fraction': 0.8859545438390546, 'bagging_freq': 7, 'lambda_l1': 0.11578337849724761, 'lambda_l2': 0.009309260978012176, 'min_child_samples': 48, 'max_depth': 5, 'max_bin': 248, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.47910514938529053, 'min_gain_to_split': 0.4954888318934103}. Best is trial 21 with value: 0.226001919421211.

Mejor trial hasta ahora: TFE=0.226002, Parámetros={'num_leaves': 90, 'learning_rate': 0.010064438320933452, 'feature_fraction': 0.8100100345176875, 'bagging_fraction': 0.8859545438390546, 'bagging_freq': 7, 'lambda_l1': 0.11578337849724761, 'lambda_l2': 0.009309260978012176, 'min_child_samples': 48, 'max_depth': 5, 'max_bin': 248, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.47910514938529053, 'min_gain_to_split': 0.4954888318934103}

[I 2025-07-15 21:32:30,621] Trial 22 finished with value: 0.22521041474054398 and parameters: {'num_leaves': 100, 'learning_rate': 0.01087323713937833, 'feature_fraction': 0.8163210359254969, 'bagging_fraction': 0.8853113701739203, 'bagging_freq': 8, 'lambda_l1': 0.1253492231405072, 'lambda_l2': 0.0029877678779985017, 'min_child_samples': 49, 'max_depth': 5, 'max_bin': 256, 'min_data_in_leaf': 31, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.6224543798910074, 'min_gain_to_split': 0.49846951756757646}. Best is trial 22 with value: 0.22521041474054398.

Mejor trial hasta ahora: TFE=0.225210, Parámetros={'num_leaves': 100, 'learning_rate': 0.01087323713937833, 'feature_fraction': 0.8163210359254969, 'bagging_fraction': 0.8853113701739203, 'bagging_freq': 8, 'lambda_l1': 0.1253492231405072, 'lambda_l2': 0.0029877678779985017, 'min_child_samples': 49, 'max_depth': 5, 'max_bin': 256, 'min_data_in_leaf': 31, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.6224543798910074, 'min_gain_to_split': 0.49846951756757646}

[I 2025-07-15 21:35:04,190] Trial 23 finished with value: 0.22576917592678178 and parameters: {'num_leaves': 98, 'learning_rate': 0.010965992291897493, 'feature_fraction': 0.8155171538054089, 'bagging_fraction': 0.8885871311881973, 'bagging_freq': 8, 'lambda_l1': 0.1169474996045438, 'lambda_l2': 0.003618410064289044, 'min_child_samples': 50, 'max_depth': 5, 'max_bin': 249, 'min_data_in_leaf': 32, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.49806137165250897, 'min_gain_to_split': 0.49949413286816613}. Best is trial 22 with value: 0.22521041474054398.

Mejor trial hasta ahora: TFE=0.225210, Parámetros={'num_leaves': 100, 'learning_rate': 0.01087323713937833, 'feature_fraction': 0.8163210359254969, 'bagging_fraction': 0.8853113701739203, 'bagging_freq': 8, 'lambda_l1': 0.1253492231405072, 'lambda_l2': 0.0029877678779985017, 'min_child_samples': 49, 'max_depth': 5, 'max_bin': 256, 'min_data_in_leaf': 31, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.6224543798910074, 'min_gain_to_split': 0.49846951756757646}

[I 2025-07-15 21:37:14,272] Trial 24 finished with value: 0.22550783158142776 and parameters: {'num_leaves': 91, 'learning_rate': 0.014039752323094316, 'feature_fraction': 0.8207254242125847, 'bagging_fraction': 0.894573052955677, 'bagging_freq': 8, 'lambda_l1': 0.074837834711279, 'lambda_l2': 0.004691816860622596, 'min_child_samples': 43, 'max_depth': 5, 'max_bin': 259, 'min_data_in_leaf': 32, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.6020521677467197, 'min_gain_to_split': 0.49914179308300183}. Best is trial 22 with value: 0.22521041474054398.

Mejor trial hasta ahora: TFE=0.225210, Parámetros={'num_leaves': 100, 'learning_rate': 0.01087323713937833, 'feature_fraction': 0.8163210359254969, 'bagging_fraction': 0.8853113701739203, 'bagging_freq': 8, 'lambda_l1': 0.1253492231405072, 'lambda_l2': 0.0029877678779985017, 'min_child_samples': 49, 'max_depth': 5, 'max_bin': 256, 'min_data_in_leaf': 31, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.6224543798910074, 'min_gain_to_split': 0.49846951756757646}

[I 2025-07-15 21:38:44,265] Trial 25 finished with value: 0.22736111619460858 and parameters: {'num_leaves': 100, 'learning_rate': 0.021146993954024793, 'feature_fraction': 0.9181233215474569, 'bagging_fraction': 0.9031476217775648, 'bagging_freq': 9, 'lambda_l1': 0.02987718498914562, 'lambda_l2': 0.2032994126001902, 'min_child_samples': 43, 'max_depth': 4, 'max_bin': 349, 'min_data_in_leaf': 29, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.6226378581134477, 'min_gain_to_split': 0.497293623808962}. Best is trial 22 with value: 0.22521041474054398.

Mejor trial hasta ahora: TFE=0.225210, Parámetros={'num_leaves': 100, 'learning_rate': 0.01087323713937833, 'feature_fraction': 0.8163210359254969, 'bagging_fraction': 0.8853113701739203, 'bagging_freq': 8, 'lambda_l1': 0.1253492231405072, 'lambda_l2': 0.0029877678779985017, 'min_child_samples': 49, 'max_depth': 5, 'max_bin': 256, 'min_data_in_leaf': 31, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.6224543798910074, 'min_gain_to_split': 0.49846951756757646}

[I 2025-07-15 21:40:58,772] Trial 26 finished with value: 0.22592407348981455 and parameters: {'num_leaves': 91, 'learning_rate': 0.013916638682014138, 'feature_fraction': 0.823867406161426, 'bagging_fraction': 0.9880968780734987, 'bagging_freq': 8, 'lambda_l1': 5.371533970287109, 'lambda_l2': 0.0028416836798144953, 'min_child_samples': 50, 'max_depth': 4, 'max_bin': 249, 'min_data_in_leaf': 42, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.6282351043307308, 'min_gain_to_split': 0.43786364908182884}. Best is trial 22 with value: 0.22521041474054398.

Mejor trial hasta ahora: TFE=0.225210, Parámetros={'num_leaves': 100, 'learning_rate': 0.01087323713937833, 'feature_fraction': 0.8163210359254969, 'bagging_fraction': 0.8853113701739203, 'bagging_freq': 8, 'lambda_l1': 0.1253492231405072, 'lambda_l2': 0.0029877678779985017, 'min_child_samples': 49, 'max_depth': 5, 'max_bin': 256, 'min_data_in_leaf': 31, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.6224543798910074, 'min_gain_to_split': 0.49846951756757646}

[I 2025-07-15 21:42:51,271] Trial 27 finished with value: 0.22393785472188332 and parameters: {'num_leaves': 94, 'learning_rate': 0.02136514260078608, 'feature_fraction': 0.8747760464247547, 'bagging_fraction': 0.9072038738234789, 'bagging_freq': 8, 'lambda_l1': 8.415859017249229e-05, 'lambda_l2': 0.002034555608687068, 'min_child_samples': 44, 'max_depth': 6, 'max_bin': 340, 'min_data_in_leaf': 29, 'extra_trees': True, 'early_stopping_rounds': 17, 'path_smooth': 0.7118472703835844, 'min_gain_to_split': 0.4389541596294772}. Best is trial 27 with value: 0.22393785472188332.

Mejor trial hasta ahora: TFE=0.223938, Parámetros={'num_leaves': 94, 'learning_rate': 0.02136514260078608, 'feature_fraction': 0.8747760464247547, 'bagging_fraction': 0.9072038738234789, 'bagging_freq': 8, 'lambda_l1': 8.415859017249229e-05, 'lambda_l2': 0.002034555608687068, 'min_child_samples': 44, 'max_depth': 6, 'max_bin': 340, 'min_data_in_leaf': 29, 'extra_trees': True, 'early_stopping_rounds': 17, 'path_smooth': 0.7118472703835844, 'min_gain_to_split': 0.4389541596294772}

[I 2025-07-15 21:44:31,401] Trial 28 finished with value: 0.22741998561298069 and parameters: {'num_leaves': 74, 'learning_rate': 0.022069973333271535, 'feature_fraction': 0.8873929066082786, 'bagging_fraction': 0.9141531346075807, 'bagging_freq': 10, 'lambda_l1': 0.00039419112289280347, 'lambda_l2': 0.2570706753387252, 'min_child_samples': 42, 'max_depth': 6, 'max_bin': 334, 'min_data_in_leaf': 26, 'extra_trees': True, 'early_stopping_rounds': 17, 'path_smooth': 0.6876533777511453, 'min_gain_to_split': 0.4397414867873536}. Best is trial 27 with value: 0.22393785472188332.

Mejor trial hasta ahora: TFE=0.223938, Parámetros={'num_leaves': 94, 'learning_rate': 0.02136514260078608, 'feature_fraction': 0.8747760464247547, 'bagging_fraction': 0.9072038738234789, 'bagging_freq': 8, 'lambda_l1': 8.415859017249229e-05, 'lambda_l2': 0.002034555608687068, 'min_child_samples': 44, 'max_depth': 6, 'max_bin': 340, 'min_data_in_leaf': 29, 'extra_trees': True, 'early_stopping_rounds': 17, 'path_smooth': 0.7118472703835844, 'min_gain_to_split': 0.4389541596294772}

[I 2025-07-15 21:47:03,328] Trial 29 finished with value: 0.22626025891893656 and parameters: {'num_leaves': 85, 'learning_rate': 0.013973025918530477, 'feature_fraction': 0.9333081339475022, 'bagging_fraction': 0.8710748820451125, 'bagging_freq': 8, 'lambda_l1': 1.1366556210653464e-08, 'lambda_l2': 0.0008131893649470191, 'min_child_samples': 46, 'max_depth': 6, 'max_bin': 329, 'min_data_in_leaf': 41, 'extra_trees': True, 'early_stopping_rounds': 22, 'path_smooth': 0.7276707973828502, 'min_gain_to_split': 0.3977431234619697}. Best is trial 27 with value: 0.22393785472188332.

Mejor trial hasta ahora: TFE=0.223938, Parámetros={'num_leaves': 94, 'learning_rate': 0.02136514260078608, 'feature_fraction': 0.8747760464247547, 'bagging_fraction': 0.9072038738234789, 'bagging_freq': 8, 'lambda_l1': 8.415859017249229e-05, 'lambda_l2': 0.002034555608687068, 'min_child_samples': 44, 'max_depth': 6, 'max_bin': 340, 'min_data_in_leaf': 29, 'extra_trees': True, 'early_stopping_rounds': 17, 'path_smooth': 0.7118472703835844, 'min_gain_to_split': 0.4389541596294772}

[I 2025-07-15 21:49:19,587] Trial 30 finished with value: 0.22592874793751444 and parameters: {'num_leaves': 94, 'learning_rate': 0.02379096590027072, 'feature_fraction': 0.7723997824779677, 'bagging_fraction': 0.8546079341442157, 'bagging_freq': 9, 'lambda_l1': 8.225535726189818e-05, 'lambda_l2': 0.028695059404516873, 'min_child_samples': 40, 'max_depth': 7, 'max_bin': 483, 'min_data_in_leaf': 20, 'extra_trees': True, 'early_stopping_rounds': 15, 'path_smooth': 0.9952101309182552, 'min_gain_to_split': 0.45856064551373954}. Best is trial 27 with value: 0.22393785472188332.

Mejor trial hasta ahora: TFE=0.223938, Parámetros={'num_leaves': 94, 'learning_rate': 0.02136514260078608, 'feature_fraction': 0.8747760464247547, 'bagging_fraction': 0.9072038738234789, 'bagging_freq': 8, 'lambda_l1': 8.415859017249229e-05, 'lambda_l2': 0.002034555608687068, 'min_child_samples': 44, 'max_depth': 6, 'max_bin': 340, 'min_data_in_leaf': 29, 'extra_trees': True, 'early_stopping_rounds': 17, 'path_smooth': 0.7118472703835844, 'min_gain_to_split': 0.4389541596294772}

[I 2025-07-15 21:50:57,613] Trial 31 finished with value: 0.22798345505888223 and parameters: {'num_leaves': 28, 'learning_rate': 0.01504930766234438, 'feature_fraction': 0.8638864867287364, 'bagging_fraction': 0.9174377883182204, 'bagging_freq': 8, 'lambda_l1': 4.481950037169302e-05, 'lambda_l2': 4.2141176161540076e-05, 'min_child_samples': 44, 'max_depth': 4, 'max_bin': 370, 'min_data_in_leaf': 28, 'extra_trees': True, 'early_stopping_rounds': 19, 'path_smooth': 0.8997779343230531, 'min_gain_to_split': 0.3965898714903228}. Best is trial 27 with value: 0.22393785472188332.

Mejor trial hasta ahora: TFE=0.223938, Parámetros={'num_leaves': 94, 'learning_rate': 0.02136514260078608, 'feature_fraction': 0.8747760464247547, 'bagging_fraction': 0.9072038738234789, 'bagging_freq': 8, 'lambda_l1': 8.415859017249229e-05, 'lambda_l2': 0.002034555608687068, 'min_child_samples': 44, 'max_depth': 6, 'max_bin': 340, 'min_data_in_leaf': 29, 'extra_trees': True, 'early_stopping_rounds': 17, 'path_smooth': 0.7118472703835844, 'min_gain_to_split': 0.4389541596294772}

[I 2025-07-15 21:54:01,626] Trial 32 finished with value: 0.22166423284517464 and parameters: {'num_leaves': 85, 'learning_rate': 0.013024006566396011, 'feature_fraction': 0.8889418892219242, 'bagging_fraction': 0.9789235422316024, 'bagging_freq': 7, 'lambda_l1': 0.001589056528703464, 'lambda_l2': 0.0008636899560574178, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 269, 'min_data_in_leaf': 47, 'extra_trees': True, 'early_stopping_rounds': 17, 'path_smooth': 0.556586478883635, 'min_gain_to_split': 0.30963154862111025}. Best is trial 32 with value: 0.22166423284517464.

Mejor trial hasta ahora: TFE=0.221664, Parámetros={'num_leaves': 85, 'learning_rate': 0.013024006566396011, 'feature_fraction': 0.8889418892219242, 'bagging_fraction': 0.9789235422316024, 'bagging_freq': 7, 'lambda_l1': 0.001589056528703464, 'lambda_l2': 0.0008636899560574178, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 269, 'min_data_in_leaf': 47, 'extra_trees': True, 'early_stopping_rounds': 17, 'path_smooth': 0.556586478883635, 'min_gain_to_split': 0.30963154862111025}

[I 2025-07-15 21:57:19,711] Trial 33 finished with value: 0.22320270017764607 and parameters: {'num_leaves': 85, 'learning_rate': 0.012761525845691806, 'feature_fraction': 0.8955594494654867, 'bagging_fraction': 0.9992374577203372, 'bagging_freq': 7, 'lambda_l1': 0.0015946318610854935, 'lambda_l2': 0.0015135054501013972, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 278, 'min_data_in_leaf': 46, 'extra_trees': True, 'early_stopping_rounds': 17, 'path_smooth': 0.5738745942029191, 'min_gain_to_split': 0.2981865341836818}. Best is trial 32 with value: 0.22166423284517464.

Mejor trial hasta ahora: TFE=0.221664, Parámetros={'num_leaves': 85, 'learning_rate': 0.013024006566396011, 'feature_fraction': 0.8889418892219242, 'bagging_fraction': 0.9789235422316024, 'bagging_freq': 7, 'lambda_l1': 0.001589056528703464, 'lambda_l2': 0.0008636899560574178, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 269, 'min_data_in_leaf': 47, 'extra_trees': True, 'early_stopping_rounds': 17, 'path_smooth': 0.556586478883635, 'min_gain_to_split': 0.30963154862111025}

[I 2025-07-15 22:00:34,777] Trial 34 finished with value: 0.22272484199222853 and parameters: {'num_leaves': 84, 'learning_rate': 0.013004841978892819, 'feature_fraction': 0.9459688146357189, 'bagging_fraction': 0.9988382673790395, 'bagging_freq': 7, 'lambda_l1': 0.0015392613807410033, 'lambda_l2': 0.001084611157309458, 'min_child_samples': 46, 'max_depth': 7, 'max_bin': 279, 'min_data_in_leaf': 48, 'extra_trees': True, 'early_stopping_rounds': 10, 'path_smooth': 0.5750573481940419, 'min_gain_to_split': 0.2968588548724785}. Best is trial 32 with value: 0.22166423284517464.

Mejor trial hasta ahora: TFE=0.221664, Parámetros={'num_leaves': 85, 'learning_rate': 0.013024006566396011, 'feature_fraction': 0.8889418892219242, 'bagging_fraction': 0.9789235422316024, 'bagging_freq': 7, 'lambda_l1': 0.001589056528703464, 'lambda_l2': 0.0008636899560574178, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 269, 'min_data_in_leaf': 47, 'extra_trees': True, 'early_stopping_rounds': 17, 'path_smooth': 0.556586478883635, 'min_gain_to_split': 0.30963154862111025}

[I 2025-07-15 22:02:18,826] Trial 35 finished with value: 0.22478078682210817 and parameters: {'num_leaves': 84, 'learning_rate': 0.025316681563174157, 'feature_fraction': 0.9506027611123091, 'bagging_fraction': 0.9942242156211469, 'bagging_freq': 7, 'lambda_l1': 0.0017123095249279054, 'lambda_l2': 0.001038701305707928, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 281, 'min_data_in_leaf': 52, 'extra_trees': True, 'early_stopping_rounds': 10, 'path_smooth': 0.39702103701385144, 'min_gain_to_split': 0.30065946996278103}. Best is trial 32 with value: 0.22166423284517464.

Mejor trial hasta ahora: TFE=0.221664, Parámetros={'num_leaves': 85, 'learning_rate': 0.013024006566396011, 'feature_fraction': 0.8889418892219242, 'bagging_fraction': 0.9789235422316024, 'bagging_freq': 7, 'lambda_l1': 0.001589056528703464, 'lambda_l2': 0.0008636899560574178, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 269, 'min_data_in_leaf': 47, 'extra_trees': True, 'early_stopping_rounds': 17, 'path_smooth': 0.556586478883635, 'min_gain_to_split': 0.30963154862111025}

[I 2025-07-15 22:06:26,554] Trial 36 finished with value: 0.2711388522992749 and parameters: {'num_leaves': 66, 'learning_rate': 0.019307506105232648, 'feature_fraction': 0.8961739122617823, 'bagging_fraction': 0.9740995289665515, 'bagging_freq': 6, 'lambda_l1': 0.00015542943154704046, 'lambda_l2': 6.570579231592986e-05, 'min_child_samples': 46, 'max_depth': 7, 'max_bin': 347, 'min_data_in_leaf': 46, 'extra_trees': False, 'early_stopping_rounds': 16, 'path_smooth': 0.5724754048111403, 'min_gain_to_split': 0.22058147621191015}. Best is trial 32 with value: 0.22166423284517464.

Mejor trial hasta ahora: TFE=0.221664, Parámetros={'num_leaves': 85, 'learning_rate': 0.013024006566396011, 'feature_fraction': 0.8889418892219242, 'bagging_fraction': 0.9789235422316024, 'bagging_freq': 7, 'lambda_l1': 0.001589056528703464, 'lambda_l2': 0.0008636899560574178, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 269, 'min_data_in_leaf': 47, 'extra_trees': True, 'early_stopping_rounds': 17, 'path_smooth': 0.556586478883635, 'min_gain_to_split': 0.30963154862111025}

[I 2025-07-15 22:09:37,322] Trial 37 finished with value: 0.22690957507666046 and parameters: {'num_leaves': 80, 'learning_rate': 0.017823504164951733, 'feature_fraction': 0.9594730328437604, 'bagging_fraction': 0.9619411855706584, 'bagging_freq': 7, 'lambda_l1': 0.001257770858434342, 'lambda_l2': 0.0010759026827676195, 'min_child_samples': 39, 'max_depth': 8, 'max_bin': 326, 'min_data_in_leaf': 57, 'extra_trees': True, 'early_stopping_rounds': 13, 'path_smooth': 0.5385066567352834, 'min_gain_to_split': 0.3034723027047065}. Best is trial 32 with value: 0.22166423284517464.

Mejor trial hasta ahora: TFE=0.221664, Parámetros={'num_leaves': 85, 'learning_rate': 0.013024006566396011, 'feature_fraction': 0.8889418892219242, 'bagging_fraction': 0.9789235422316024, 'bagging_freq': 7, 'lambda_l1': 0.001589056528703464, 'lambda_l2': 0.0008636899560574178, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 269, 'min_data_in_leaf': 47, 'extra_trees': True, 'early_stopping_rounds': 17, 'path_smooth': 0.556586478883635, 'min_gain_to_split': 0.30963154862111025}

[I 2025-07-15 22:14:48,270] Trial 38 finished with value: 0.2733406898973869 and parameters: {'num_leaves': 52, 'learning_rate': 0.012804812774993289, 'feature_fraction': 0.8975944112825909, 'bagging_fraction': 0.9766382527881007, 'bagging_freq': 6, 'lambda_l1': 3.270228375597564e-05, 'lambda_l2': 0.012869282269761842, 'min_child_samples': 47, 'max_depth': 6, 'max_bin': 414, 'min_data_in_leaf': 40, 'extra_trees': False, 'early_stopping_rounds': 10, 'path_smooth': 0.6804426333354724, 'min_gain_to_split': 0.29481833848596395}. Best is trial 32 with value: 0.22166423284517464.

Mejor trial hasta ahora: TFE=0.221664, Parámetros={'num_leaves': 85, 'learning_rate': 0.013024006566396011, 'feature_fraction': 0.8889418892219242, 'bagging_fraction': 0.9789235422316024, 'bagging_freq': 7, 'lambda_l1': 0.001589056528703464, 'lambda_l2': 0.0008636899560574178, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 269, 'min_data_in_leaf': 47, 'extra_trees': True, 'early_stopping_rounds': 17, 'path_smooth': 0.556586478883635, 'min_gain_to_split': 0.30963154862111025}

[I 2025-07-15 22:16:13,724] Trial 39 finished with value: 0.23174090435563488 and parameters: {'num_leaves': 75, 'learning_rate': 0.04581653470765275, 'feature_fraction': 0.9618631139812724, 'bagging_fraction': 0.9547319237166755, 'bagging_freq': 7, 'lambda_l1': 1.2096113132553092e-06, 'lambda_l2': 1.728254826277213e-08, 'min_child_samples': 34, 'max_depth': 7, 'max_bin': 312, 'min_data_in_leaf': 54, 'extra_trees': True, 'early_stopping_rounds': 15, 'path_smooth': 0.42884805295744266, 'min_gain_to_split': 0.21117771201643087}. Best is trial 32 with value: 0.22166423284517464.

Mejor trial hasta ahora: TFE=0.221664, Parámetros={'num_leaves': 85, 'learning_rate': 0.013024006566396011, 'feature_fraction': 0.8889418892219242, 'bagging_fraction': 0.9789235422316024, 'bagging_freq': 7, 'lambda_l1': 0.001589056528703464, 'lambda_l2': 0.0008636899560574178, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 269, 'min_data_in_leaf': 47, 'extra_trees': True, 'early_stopping_rounds': 17, 'path_smooth': 0.556586478883635, 'min_gain_to_split': 0.30963154862111025}

[I 2025-07-15 22:19:10,546] Trial 40 finished with value: 0.2242564137466318 and parameters: {'num_leaves': 63, 'learning_rate': 0.018714710095456208, 'feature_fraction': 0.9243723738108888, 'bagging_fraction': 0.9988027883267357, 'bagging_freq': 9, 'lambda_l1': 1.582617921788372e-05, 'lambda_l2': 0.06259983477020821, 'min_child_samples': 41, 'max_depth': 6, 'max_bin': 278, 'min_data_in_leaf': 47, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.7557023980668945, 'min_gain_to_split': 0.28129046135015146}. Best is trial 32 with value: 0.22166423284517464.

Mejor trial hasta ahora: TFE=0.221664, Parámetros={'num_leaves': 85, 'learning_rate': 0.013024006566396011, 'feature_fraction': 0.8889418892219242, 'bagging_fraction': 0.9789235422316024, 'bagging_freq': 7, 'lambda_l1': 0.001589056528703464, 'lambda_l2': 0.0008636899560574178, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 269, 'min_data_in_leaf': 47, 'extra_trees': True, 'early_stopping_rounds': 17, 'path_smooth': 0.556586478883635, 'min_gain_to_split': 0.30963154862111025}

[I 2025-07-15 22:19:46,997] Trial 41 finished with value: 0.2677377544940502 and parameters: {'num_leaves': 87, 'learning_rate': 0.26591649681328244, 'feature_fraction': 0.8744246513381454, 'bagging_fraction': 0.9379974991069246, 'bagging_freq': 5, 'lambda_l1': 0.0008091098888139892, 'lambda_l2': 2.794758955975898e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 212, 'min_data_in_leaf': 64, 'extra_trees': False, 'early_stopping_rounds': 12, 'path_smooth': 0.8389093054419016, 'min_gain_to_split': 0.32489623900988823}. Best is trial 32 with value: 0.22166423284517464.

Mejor trial hasta ahora: TFE=0.221664, Parámetros={'num_leaves': 85, 'learning_rate': 0.013024006566396011, 'feature_fraction': 0.8889418892219242, 'bagging_fraction': 0.9789235422316024, 'bagging_freq': 7, 'lambda_l1': 0.001589056528703464, 'lambda_l2': 0.0008636899560574178, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 269, 'min_data_in_leaf': 47, 'extra_trees': True, 'early_stopping_rounds': 17, 'path_smooth': 0.556586478883635, 'min_gain_to_split': 0.30963154862111025}

[I 2025-07-15 22:27:36,884] Trial 42 finished with value: 0.22183572159934992 and parameters: {'num_leaves': 94, 'learning_rate': 0.012166706461774736, 'feature_fraction': 0.9937249031474614, 'bagging_fraction': 0.9810237060117248, 'bagging_freq': 7, 'lambda_l1': 0.00011330346415354003, 'lambda_l2': 0.0009226045859650878, 'min_child_samples': 45, 'max_depth': 8, 'max_bin': 410, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 22, 'path_smooth': 0.5465290087855941, 'min_gain_to_split': 0.3811983340535544}. Best is trial 32 with value: 0.22166423284517464.

Mejor trial hasta ahora: TFE=0.221664, Parámetros={'num_leaves': 85, 'learning_rate': 0.013024006566396011, 'feature_fraction': 0.8889418892219242, 'bagging_fraction': 0.9789235422316024, 'bagging_freq': 7, 'lambda_l1': 0.001589056528703464, 'lambda_l2': 0.0008636899560574178, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 269, 'min_data_in_leaf': 47, 'extra_trees': True, 'early_stopping_rounds': 17, 'path_smooth': 0.556586478883635, 'min_gain_to_split': 0.30963154862111025}

[I 2025-07-15 22:34:18,973] Trial 43 finished with value: 0.22276600132340155 and parameters: {'num_leaves': 95, 'learning_rate': 0.012417008570050549, 'feature_fraction': 0.9872554086372487, 'bagging_fraction': 0.9785291141299821, 'bagging_freq': 7, 'lambda_l1': 0.00016119353144569736, 'lambda_l2': 0.0010416442670912853, 'min_child_samples': 47, 'max_depth': 8, 'max_bin': 414, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 22, 'path_smooth': 0.44884635805444745, 'min_gain_to_split': 0.3660245116028939}. Best is trial 32 with value: 0.22166423284517464.

Mejor trial hasta ahora: TFE=0.221664, Parámetros={'num_leaves': 85, 'learning_rate': 0.013024006566396011, 'feature_fraction': 0.8889418892219242, 'bagging_fraction': 0.9789235422316024, 'bagging_freq': 7, 'lambda_l1': 0.001589056528703464, 'lambda_l2': 0.0008636899560574178, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 269, 'min_data_in_leaf': 47, 'extra_trees': True, 'early_stopping_rounds': 17, 'path_smooth': 0.556586478883635, 'min_gain_to_split': 0.30963154862111025}

[I 2025-07-15 22:42:14,212] Trial 44 finished with value: 0.223556861526992 and parameters: {'num_leaves': 80, 'learning_rate': 0.012383334715367853, 'feature_fraction': 0.9892242036267165, 'bagging_fraction': 0.979769483200674, 'bagging_freq': 7, 'lambda_l1': 0.00019637958072801518, 'lambda_l2': 0.0005819870194513865, 'min_child_samples': 47, 'max_depth': 8, 'max_bin': 410, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 22, 'path_smooth': 0.4460334816383588, 'min_gain_to_split': 0.3674875039875208}. Best is trial 32 with value: 0.22166423284517464.

Mejor trial hasta ahora: TFE=0.221664, Parámetros={'num_leaves': 85, 'learning_rate': 0.013024006566396011, 'feature_fraction': 0.8889418892219242, 'bagging_fraction': 0.9789235422316024, 'bagging_freq': 7, 'lambda_l1': 0.001589056528703464, 'lambda_l2': 0.0008636899560574178, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 269, 'min_data_in_leaf': 47, 'extra_trees': True, 'early_stopping_rounds': 17, 'path_smooth': 0.556586478883635, 'min_gain_to_split': 0.30963154862111025}

[I 2025-07-15 22:50:37,706] Trial 45 finished with value: 0.22382832741025052 and parameters: {'num_leaves': 93, 'learning_rate': 0.012859285611119408, 'feature_fraction': 0.9990649469134674, 'bagging_fraction': 0.9528508889371519, 'bagging_freq': 6, 'lambda_l1': 0.002009732289032719, 'lambda_l2': 0.007704094157079676, 'min_child_samples': 45, 'max_depth': 9, 'max_bin': 442, 'min_data_in_leaf': 44, 'extra_trees': True, 'early_stopping_rounds': 22, 'path_smooth': 0.5492785428320582, 'min_gain_to_split': 0.3909094805019556}. Best is trial 32 with value: 0.22166423284517464.

Mejor trial hasta ahora: TFE=0.221664, Parámetros={'num_leaves': 85, 'learning_rate': 0.013024006566396011, 'feature_fraction': 0.8889418892219242, 'bagging_fraction': 0.9789235422316024, 'bagging_freq': 7, 'lambda_l1': 0.001589056528703464, 'lambda_l2': 0.0008636899560574178, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 269, 'min_data_in_leaf': 47, 'extra_trees': True, 'early_stopping_rounds': 17, 'path_smooth': 0.556586478883635, 'min_gain_to_split': 0.30963154862111025}

[I 2025-07-15 22:51:48,248] Trial 46 finished with value: 0.2307957515036505 and parameters: {'num_leaves': 88, 'learning_rate': 0.07751013753574136, 'feature_fraction': 0.9693223794220993, 'bagging_fraction': 0.9284191079323215, 'bagging_freq': 7, 'lambda_l1': 3.886912476716248e-06, 'lambda_l2': 0.026547038638883518, 'min_child_samples': 37, 'max_depth': 8, 'max_bin': 393, 'min_data_in_leaf': 52, 'extra_trees': True, 'early_stopping_rounds': 20, 'path_smooth': 0.3237484892407403, 'min_gain_to_split': 0.36028953061316127}. Best is trial 32 with value: 0.22166423284517464.

Mejor trial hasta ahora: TFE=0.221664, Parámetros={'num_leaves': 85, 'learning_rate': 0.013024006566396011, 'feature_fraction': 0.8889418892219242, 'bagging_fraction': 0.9789235422316024, 'bagging_freq': 7, 'lambda_l1': 0.001589056528703464, 'lambda_l2': 0.0008636899560574178, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 269, 'min_data_in_leaf': 47, 'extra_trees': True, 'early_stopping_rounds': 17, 'path_smooth': 0.556586478883635, 'min_gain_to_split': 0.30963154862111025}

[I 2025-07-15 22:59:39,532] Trial 47 finished with value: 0.28362293588407217 and parameters: {'num_leaves': 70, 'learning_rate': 0.01600503210610256, 'feature_fraction': 0.9399179077165416, 'bagging_fraction': 0.9647014969714787, 'bagging_freq': 6, 'lambda_l1': 0.01648784546190454, 'lambda_l2': 6.1004851340097466e-05, 'min_child_samples': 48, 'max_depth': 9, 'max_bin': 491, 'min_data_in_leaf': 35, 'extra_trees': False, 'early_stopping_rounds': 14, 'path_smooth': 0.5335625906368576, 'min_gain_to_split': 0.27275493882793017}. Best is trial 32 with value: 0.22166423284517464.

Mejor trial hasta ahora: TFE=0.221664, Parámetros={'num_leaves': 85, 'learning_rate': 0.013024006566396011, 'feature_fraction': 0.8889418892219242, 'bagging_fraction': 0.9789235422316024, 'bagging_freq': 7, 'lambda_l1': 0.001589056528703464, 'lambda_l2': 0.0008636899560574178, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 269, 'min_data_in_leaf': 47, 'extra_trees': True, 'early_stopping_rounds': 17, 'path_smooth': 0.556586478883635, 'min_gain_to_split': 0.30963154862111025}

[I 2025-07-15 23:00:18,095] Trial 48 finished with value: 0.23753383914857182 and parameters: {'num_leaves': 44, 'learning_rate': 0.16500803763630065, 'feature_fraction': 0.9138352191180673, 'bagging_fraction': 0.9859934074721627, 'bagging_freq': 5, 'lambda_l1': 0.003867043060726992, 'lambda_l2': 1.4695797078451354e-05, 'min_child_samples': 42, 'max_depth': 7, 'max_bin': 309, 'min_data_in_leaf': 25, 'extra_trees': True, 'early_stopping_rounds': 19, 'path_smooth': 0.4532808754027921, 'min_gain_to_split': 0.23333880641063204}. Best is trial 32 with value: 0.22166423284517464.

Mejor trial hasta ahora: TFE=0.221664, Parámetros={'num_leaves': 85, 'learning_rate': 0.013024006566396011, 'feature_fraction': 0.8889418892219242, 'bagging_fraction': 0.9789235422316024, 'bagging_freq': 7, 'lambda_l1': 0.001589056528703464, 'lambda_l2': 0.0008636899560574178, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 269, 'min_data_in_leaf': 47, 'extra_trees': True, 'early_stopping_rounds': 17, 'path_smooth': 0.556586478883635, 'min_gain_to_split': 0.30963154862111025}

[I 2025-07-15 23:04:35,227] Trial 49 finished with value: 0.22143557236456388 and parameters: {'num_leaves': 96, 'learning_rate': 0.011923179332309958, 'feature_fraction': 0.9761506166324092, 'bagging_fraction': 0.999502286266864, 'bagging_freq': 7, 'lambda_l1': 0.0006699634831010268, 'lambda_l2': 0.0016924513888046412, 'min_child_samples': 22, 'max_depth': 8, 'max_bin': 365, 'min_data_in_leaf': 49, 'extra_trees': True, 'early_stopping_rounds': 12, 'path_smooth': 0.5820215573173859, 'min_gain_to_split': 0.31790057690827844}. Best is trial 49 with value: 0.22143557236456388.

Mejor trial hasta ahora: TFE=0.221436, Parámetros={'num_leaves': 96, 'learning_rate': 0.011923179332309958, 'feature_fraction': 0.9761506166324092, 'bagging_fraction': 0.999502286266864, 'bagging_freq': 7, 'lambda_l1': 0.0006699634831010268, 'lambda_l2': 0.0016924513888046412, 'min_child_samples': 22, 'max_depth': 8, 'max_bin': 365, 'min_data_in_leaf': 49, 'extra_trees': True, 'early_stopping_rounds': 12, 'path_smooth': 0.5820215573173859, 'min_gain_to_split': 0.31790057690827844}

[I 2025-07-15 23:09:20,569] Trial 50 finished with value: 0.22631589696493384 and parameters: {'num_leaves': 96, 'learning_rate': 0.011695904198923157, 'feature_fraction': 0.9803571489524401, 'bagging_fraction': 0.9493143055613851, 'bagging_freq': 6, 'lambda_l1': 2.3543637519470657e-05, 'lambda_l2': 0.00016916645278717462, 'min_child_samples': 18, 'max_depth': 8, 'max_bin': 463, 'min_data_in_leaf': 49, 'extra_trees': True, 'early_stopping_rounds': 12, 'path_smooth': 0.34979953054361945, 'min_gain_to_split': 0.3211580158472596}. Best is trial 49 with value: 0.22143557236456388.

Mejor trial hasta ahora: TFE=0.221436, Parámetros={'num_leaves': 96, 'learning_rate': 0.011923179332309958, 'feature_fraction': 0.9761506166324092, 'bagging_fraction': 0.999502286266864, 'bagging_freq': 7, 'lambda_l1': 0.0006699634831010268, 'lambda_l2': 0.0016924513888046412, 'min_child_samples': 22, 'max_depth': 8, 'max_bin': 365, 'min_data_in_leaf': 49, 'extra_trees': True, 'early_stopping_rounds': 12, 'path_smooth': 0.5820215573173859, 'min_gain_to_split': 0.31790057690827844}

[I 2025-07-15 23:12:59,479] Trial 51 finished with value: 0.22894168037992052 and parameters: {'num_leaves': 94, 'learning_rate': 0.016840844534830337, 'feature_fraction': 0.9988793700686548, 'bagging_fraction': 0.967782906203645, 'bagging_freq': 9, 'lambda_l1': 8.157054425521325e-05, 'lambda_l2': 0.0006213453894002998, 'min_child_samples': 23, 'max_depth': 9, 'max_bin': 371, 'min_data_in_leaf': 69, 'extra_trees': True, 'early_stopping_rounds': 11, 'path_smooth': 0.6438342016286457, 'min_gain_to_split': 0.37725413429696164}. Best is trial 49 with value: 0.22143557236456388.

Mejor trial hasta ahora: TFE=0.221436, Parámetros={'num_leaves': 96, 'learning_rate': 0.011923179332309958, 'feature_fraction': 0.9761506166324092, 'bagging_fraction': 0.999502286266864, 'bagging_freq': 7, 'lambda_l1': 0.0006699634831010268, 'lambda_l2': 0.0016924513888046412, 'min_child_samples': 22, 'max_depth': 8, 'max_bin': 365, 'min_data_in_leaf': 49, 'extra_trees': True, 'early_stopping_rounds': 12, 'path_smooth': 0.5820215573173859, 'min_gain_to_split': 0.31790057690827844}

[I 2025-07-15 23:16:36,134] Trial 52 finished with value: 0.2692937395068585 and parameters: {'num_leaves': 77, 'learning_rate': 0.027439593969766772, 'feature_fraction': 0.9779292706540119, 'bagging_fraction': 0.9281235997368418, 'bagging_freq': 6, 'lambda_l1': 0.0005137133845096197, 'lambda_l2': 0.13408682053632348, 'min_child_samples': 13, 'max_depth': 8, 'max_bin': 403, 'min_data_in_leaf': 55, 'extra_trees': False, 'early_stopping_rounds': 14, 'path_smooth': 0.5172028255103206, 'min_gain_to_split': 0.34837515725022766}. Best is trial 49 with value: 0.22143557236456388.

Mejor trial hasta ahora: TFE=0.221436, Parámetros={'num_leaves': 96, 'learning_rate': 0.011923179332309958, 'feature_fraction': 0.9761506166324092, 'bagging_fraction': 0.999502286266864, 'bagging_freq': 7, 'lambda_l1': 0.0006699634831010268, 'lambda_l2': 0.0016924513888046412, 'min_child_samples': 22, 'max_depth': 8, 'max_bin': 365, 'min_data_in_leaf': 49, 'extra_trees': True, 'early_stopping_rounds': 12, 'path_smooth': 0.5820215573173859, 'min_gain_to_split': 0.31790057690827844}

[I 2025-07-15 23:20:07,609] Trial 53 finished with value: 0.2229998918589357 and parameters: {'num_leaves': 84, 'learning_rate': 0.012682534547761226, 'feature_fraction': 0.9530967691317747, 'bagging_fraction': 0.9995939123011328, 'bagging_freq': 7, 'lambda_l1': 0.003969571841532302, 'lambda_l2': 0.001469110541357527, 'min_child_samples': 20, 'max_depth': 7, 'max_bin': 427, 'min_data_in_leaf': 44, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.5702212769640949, 'min_gain_to_split': 0.3240271295892658}. Best is trial 49 with value: 0.22143557236456388.

Mejor trial hasta ahora: TFE=0.221436, Parámetros={'num_leaves': 96, 'learning_rate': 0.011923179332309958, 'feature_fraction': 0.9761506166324092, 'bagging_fraction': 0.999502286266864, 'bagging_freq': 7, 'lambda_l1': 0.0006699634831010268, 'lambda_l2': 0.0016924513888046412, 'min_child_samples': 22, 'max_depth': 8, 'max_bin': 365, 'min_data_in_leaf': 49, 'extra_trees': True, 'early_stopping_rounds': 12, 'path_smooth': 0.5820215573173859, 'min_gain_to_split': 0.31790057690827844}

[I 2025-07-15 23:25:27,854] Trial 54 finished with value: 0.22298171937834127 and parameters: {'num_leaves': 89, 'learning_rate': 0.01005987062032337, 'feature_fraction': 0.9497206655310974, 'bagging_fraction': 0.9852705933942054, 'bagging_freq': 7, 'lambda_l1': 0.01048763400193741, 'lambda_l2': 0.006610355495386135, 'min_child_samples': 20, 'max_depth': 8, 'max_bin': 437, 'min_data_in_leaf': 43, 'extra_trees': True, 'early_stopping_rounds': 12, 'path_smooth': 0.5809826302043315, 'min_gain_to_split': 0.3267076723739905}. Best is trial 49 with value: 0.22143557236456388.

Mejor trial hasta ahora: TFE=0.221436, Parámetros={'num_leaves': 96, 'learning_rate': 0.011923179332309958, 'feature_fraction': 0.9761506166324092, 'bagging_fraction': 0.999502286266864, 'bagging_freq': 7, 'lambda_l1': 0.0006699634831010268, 'lambda_l2': 0.0016924513888046412, 'min_child_samples': 22, 'max_depth': 8, 'max_bin': 365, 'min_data_in_leaf': 49, 'extra_trees': True, 'early_stopping_rounds': 12, 'path_smooth': 0.5820215573173859, 'min_gain_to_split': 0.31790057690827844}

[I 2025-07-15 23:29:13,150] Trial 55 finished with value: 0.2236135166537593 and parameters: {'num_leaves': 88, 'learning_rate': 0.015046987742909893, 'feature_fraction': 0.9418816970702625, 'bagging_fraction': 0.9832924284376748, 'bagging_freq': 7, 'lambda_l1': 0.00895577179512863, 'lambda_l2': 0.0065317573319604956, 'min_child_samples': 17, 'max_depth': 8, 'max_bin': 448, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 12, 'path_smooth': 0.4103331140543906, 'min_gain_to_split': 0.26028964497070894}. Best is trial 49 with value: 0.22143557236456388.

Mejor trial hasta ahora: TFE=0.221436, Parámetros={'num_leaves': 96, 'learning_rate': 0.011923179332309958, 'feature_fraction': 0.9761506166324092, 'bagging_fraction': 0.999502286266864, 'bagging_freq': 7, 'lambda_l1': 0.0006699634831010268, 'lambda_l2': 0.0016924513888046412, 'min_child_samples': 22, 'max_depth': 8, 'max_bin': 365, 'min_data_in_leaf': 49, 'extra_trees': True, 'early_stopping_rounds': 12, 'path_smooth': 0.5820215573173859, 'min_gain_to_split': 0.31790057690827844}

[I 2025-07-15 23:35:08,453] Trial 56 finished with value: 0.22542303959055704 and parameters: {'num_leaves': 95, 'learning_rate': 0.010087726334067739, 'feature_fraction': 0.9724319284809791, 'bagging_fraction': 0.9731503961602452, 'bagging_freq': 8, 'lambda_l1': 0.00023633014887874273, 'lambda_l2': 0.0003653659380311696, 'min_child_samples': 27, 'max_depth': 9, 'max_bin': 430, 'min_data_in_leaf': 51, 'extra_trees': True, 'early_stopping_rounds': 10, 'path_smooth': 0.6751685316192693, 'min_gain_to_split': 0.408837149764263}. Best is trial 49 with value: 0.22143557236456388.

Mejor trial hasta ahora: TFE=0.221436, Parámetros={'num_leaves': 96, 'learning_rate': 0.011923179332309958, 'feature_fraction': 0.9761506166324092, 'bagging_fraction': 0.999502286266864, 'bagging_freq': 7, 'lambda_l1': 0.0006699634831010268, 'lambda_l2': 0.0016924513888046412, 'min_child_samples': 22, 'max_depth': 8, 'max_bin': 365, 'min_data_in_leaf': 49, 'extra_trees': True, 'early_stopping_rounds': 12, 'path_smooth': 0.5820215573173859, 'min_gain_to_split': 0.31790057690827844}

[I 2025-07-15 23:39:18,852] Trial 57 finished with value: 0.22228161403909966 and parameters: {'num_leaves': 97, 'learning_rate': 0.011409804163826674, 'feature_fraction': 0.929970388054152, 'bagging_fraction': 0.9407613343832096, 'bagging_freq': 6, 'lambda_l1': 0.0006682137087832046, 'lambda_l2': 0.01537150160547832, 'min_child_samples': 29, 'max_depth': 8, 'max_bin': 377, 'min_data_in_leaf': 43, 'extra_trees': True, 'early_stopping_rounds': 14, 'path_smooth': 0.4765229802176373, 'min_gain_to_split': 0.19656660563494874}. Best is trial 49 with value: 0.22143557236456388.

Mejor trial hasta ahora: TFE=0.221436, Parámetros={'num_leaves': 96, 'learning_rate': 0.011923179332309958, 'feature_fraction': 0.9761506166324092, 'bagging_fraction': 0.999502286266864, 'bagging_freq': 7, 'lambda_l1': 0.0006699634831010268, 'lambda_l2': 0.0016924513888046412, 'min_child_samples': 22, 'max_depth': 8, 'max_bin': 365, 'min_data_in_leaf': 49, 'extra_trees': True, 'early_stopping_rounds': 12, 'path_smooth': 0.5820215573173859, 'min_gain_to_split': 0.31790057690827844}

[I 2025-07-15 23:43:46,090] Trial 58 finished with value: 0.22682382340392468 and parameters: {'num_leaves': 97, 'learning_rate': 0.011554074961570186, 'feature_fraction': 0.9128732908093272, 'bagging_fraction': 0.946737633775158, 'bagging_freq': 5, 'lambda_l1': 0.0007475443094544157, 'lambda_l2': 0.4816451877868358, 'min_child_samples': 29, 'max_depth': 9, 'max_bin': 363, 'min_data_in_leaf': 60, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.4773387532166522, 'min_gain_to_split': 0.202921570443417}. Best is trial 49 with value: 0.22143557236456388.

Mejor trial hasta ahora: TFE=0.221436, Parámetros={'num_leaves': 96, 'learning_rate': 0.011923179332309958, 'feature_fraction': 0.9761506166324092, 'bagging_fraction': 0.999502286266864, 'bagging_freq': 7, 'lambda_l1': 0.0006699634831010268, 'lambda_l2': 0.0016924513888046412, 'min_child_samples': 22, 'max_depth': 8, 'max_bin': 365, 'min_data_in_leaf': 49, 'extra_trees': True, 'early_stopping_rounds': 12, 'path_smooth': 0.5820215573173859, 'min_gain_to_split': 0.31790057690827844}

[I 2025-07-15 23:46:56,403] Trial 59 finished with value: 0.23530351234540653 and parameters: {'num_leaves': 92, 'learning_rate': 0.018495726659871224, 'feature_fraction': 0.9296809972430038, 'bagging_fraction': 0.957280690949855, 'bagging_freq': 6, 'lambda_l1': 4.749181936150477e-06, 'lambda_l2': 0.020613203861830878, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 388, 'min_data_in_leaf': 84, 'extra_trees': True, 'early_stopping_rounds': 37, 'path_smooth': 0.48247615025082113, 'min_gain_to_split': 0.23779305691122107}. Best is trial 49 with value: 0.22143557236456388.

Mejor trial hasta ahora: TFE=0.221436, Parámetros={'num_leaves': 96, 'learning_rate': 0.011923179332309958, 'feature_fraction': 0.9761506166324092, 'bagging_fraction': 0.999502286266864, 'bagging_freq': 7, 'lambda_l1': 0.0006699634831010268, 'lambda_l2': 0.0016924513888046412, 'min_child_samples': 22, 'max_depth': 8, 'max_bin': 365, 'min_data_in_leaf': 49, 'extra_trees': True, 'early_stopping_rounds': 12, 'path_smooth': 0.5820215573173859, 'min_gain_to_split': 0.31790057690827844}

[I 2025-07-15 23:50:23,014] Trial 60 finished with value: 0.22217201431387074 and parameters: {'num_leaves': 98, 'learning_rate': 0.014445513366922468, 'feature_fraction': 0.9869583664846052, 'bagging_fraction': 0.9696159027669378, 'bagging_freq': 8, 'lambda_l1': 0.02531900976493105, 'lambda_l2': 0.06056277306373205, 'min_child_samples': 24, 'max_depth': 10, 'max_bin': 229, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 20, 'path_smooth': 0.36633280566723536, 'min_gain_to_split': 0.1743375326567767}. Best is trial 49 with value: 0.22143557236456388.

Mejor trial hasta ahora: TFE=0.221436, Parámetros={'num_leaves': 96, 'learning_rate': 0.011923179332309958, 'feature_fraction': 0.9761506166324092, 'bagging_fraction': 0.999502286266864, 'bagging_freq': 7, 'lambda_l1': 0.0006699634831010268, 'lambda_l2': 0.0016924513888046412, 'min_child_samples': 22, 'max_depth': 8, 'max_bin': 365, 'min_data_in_leaf': 49, 'extra_trees': True, 'early_stopping_rounds': 12, 'path_smooth': 0.5820215573173859, 'min_gain_to_split': 0.31790057690827844}

[I 2025-07-15 23:52:48,940] Trial 61 finished with value: 0.22986265148100876 and parameters: {'num_leaves': 34, 'learning_rate': 0.0146945155840516, 'feature_fraction': 0.9693710053423494, 'bagging_fraction': 0.9412551623187843, 'bagging_freq': 8, 'lambda_l1': 0.029252450461013695, 'lambda_l2': 0.06347767449866663, 'min_child_samples': 24, 'max_depth': 10, 'max_bin': 225, 'min_data_in_leaf': 49, 'extra_trees': True, 'early_stopping_rounds': 20, 'path_smooth': 0.26246425769523296, 'min_gain_to_split': 0.12408842977255358}. Best is trial 49 with value: 0.22143557236456388.

Mejor trial hasta ahora: TFE=0.221436, Parámetros={'num_leaves': 96, 'learning_rate': 0.011923179332309958, 'feature_fraction': 0.9761506166324092, 'bagging_fraction': 0.999502286266864, 'bagging_freq': 7, 'lambda_l1': 0.0006699634831010268, 'lambda_l2': 0.0016924513888046412, 'min_child_samples': 22, 'max_depth': 8, 'max_bin': 365, 'min_data_in_leaf': 49, 'extra_trees': True, 'early_stopping_rounds': 12, 'path_smooth': 0.5820215573173859, 'min_gain_to_split': 0.31790057690827844}

[I 2025-07-15 23:53:52,348] Trial 62 finished with value: 0.2235457321558989 and parameters: {'num_leaves': 98, 'learning_rate': 0.041951647518939914, 'feature_fraction': 0.8470303145429523, 'bagging_fraction': 0.9664389661921291, 'bagging_freq': 8, 'lambda_l1': 0.49984227507443063, 'lambda_l2': 3.940996262226868, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 234, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 14, 'path_smooth': 0.204389268409991, 'min_gain_to_split': 0.18917526119261222}. Best is trial 49 with value: 0.22143557236456388.

Mejor trial hasta ahora: TFE=0.221436, Parámetros={'num_leaves': 96, 'learning_rate': 0.011923179332309958, 'feature_fraction': 0.9761506166324092, 'bagging_fraction': 0.999502286266864, 'bagging_freq': 7, 'lambda_l1': 0.0006699634831010268, 'lambda_l2': 0.0016924513888046412, 'min_child_samples': 22, 'max_depth': 8, 'max_bin': 365, 'min_data_in_leaf': 49, 'extra_trees': True, 'early_stopping_rounds': 12, 'path_smooth': 0.5820215573173859, 'min_gain_to_split': 0.31790057690827844}

[I 2025-07-15 23:57:41,980] Trial 63 finished with value: 0.22341626812474855 and parameters: {'num_leaves': 97, 'learning_rate': 0.01126327992037228, 'feature_fraction': 0.9919098424396314, 'bagging_fraction': 0.9863880220934735, 'bagging_freq': 7, 'lambda_l1': 0.003176416112218364, 'lambda_l2': 0.015113427027845808, 'min_child_samples': 30, 'max_depth': 9, 'max_bin': 172, 'min_data_in_leaf': 32, 'extra_trees': True, 'early_stopping_rounds': 23, 'path_smooth': 0.3457782094157409, 'min_gain_to_split': 0.1759656496659383}. Best is trial 49 with value: 0.22143557236456388.

Mejor trial hasta ahora: TFE=0.221436, Parámetros={'num_leaves': 96, 'learning_rate': 0.011923179332309958, 'feature_fraction': 0.9761506166324092, 'bagging_fraction': 0.999502286266864, 'bagging_freq': 7, 'lambda_l1': 0.0006699634831010268, 'lambda_l2': 0.0016924513888046412, 'min_child_samples': 22, 'max_depth': 8, 'max_bin': 365, 'min_data_in_leaf': 49, 'extra_trees': True, 'early_stopping_rounds': 12, 'path_smooth': 0.5820215573173859, 'min_gain_to_split': 0.31790057690827844}

[I 2025-07-16 00:00:12,038] Trial 64 finished with value: 0.2224112297341292 and parameters: {'num_leaves': 91, 'learning_rate': 0.01598587586155327, 'feature_fraction': 0.9824316465201166, 'bagging_fraction': 0.9755991319799147, 'bagging_freq': 7, 'lambda_l1': 0.00010189183511481636, 'lambda_l2': 0.00011328590181000957, 'min_child_samples': 25, 'max_depth': 7, 'max_bin': 298, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 19, 'path_smooth': 0.29905613293367656, 'min_gain_to_split': 0.10411978955989185}. Best is trial 49 with value: 0.22143557236456388.

Mejor trial hasta ahora: TFE=0.221436, Parámetros={'num_leaves': 96, 'learning_rate': 0.011923179332309958, 'feature_fraction': 0.9761506166324092, 'bagging_fraction': 0.999502286266864, 'bagging_freq': 7, 'lambda_l1': 0.0006699634831010268, 'lambda_l2': 0.0016924513888046412, 'min_child_samples': 22, 'max_depth': 8, 'max_bin': 365, 'min_data_in_leaf': 49, 'extra_trees': True, 'early_stopping_rounds': 12, 'path_smooth': 0.5820215573173859, 'min_gain_to_split': 0.31790057690827844}

[I 2025-07-16 00:02:46,629] Trial 65 finished with value: 0.22268900638620556 and parameters: {'num_leaves': 82, 'learning_rate': 0.016042973539701782, 'feature_fraction': 0.9653521200660051, 'bagging_fraction': 0.991368021978967, 'bagging_freq': 6, 'lambda_l1': 6.927547715576786e-05, 'lambda_l2': 0.0001248912679203045, 'min_child_samples': 25, 'max_depth': 7, 'max_bin': 295, 'min_data_in_leaf': 41, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.2667438448947229, 'min_gain_to_split': 0.09199085724502597}. Best is trial 49 with value: 0.22143557236456388.

Mejor trial hasta ahora: TFE=0.221436, Parámetros={'num_leaves': 96, 'learning_rate': 0.011923179332309958, 'feature_fraction': 0.9761506166324092, 'bagging_fraction': 0.999502286266864, 'bagging_freq': 7, 'lambda_l1': 0.0006699634831010268, 'lambda_l2': 0.0016924513888046412, 'min_child_samples': 22, 'max_depth': 8, 'max_bin': 365, 'min_data_in_leaf': 49, 'extra_trees': True, 'early_stopping_rounds': 12, 'path_smooth': 0.5820215573173859, 'min_gain_to_split': 0.31790057690827844}

[I 2025-07-16 00:04:54,250] Trial 66 finished with value: 0.22347405259545336 and parameters: {'num_leaves': 90, 'learning_rate': 0.015826716038751538, 'feature_fraction': 0.7932524552544538, 'bagging_fraction': 0.9681930824690429, 'bagging_freq': 6, 'lambda_l1': 4.969204567391124e-05, 'lambda_l2': 9.891374262730334e-05, 'min_child_samples': 25, 'max_depth': 7, 'max_bin': 293, 'min_data_in_leaf': 41, 'extra_trees': True, 'early_stopping_rounds': 19, 'path_smooth': 0.2857464870584549, 'min_gain_to_split': 0.12003920847162408}. Best is trial 49 with value: 0.22143557236456388.

Mejor trial hasta ahora: TFE=0.221436, Parámetros={'num_leaves': 96, 'learning_rate': 0.011923179332309958, 'feature_fraction': 0.9761506166324092, 'bagging_fraction': 0.999502286266864, 'bagging_freq': 7, 'lambda_l1': 0.0006699634831010268, 'lambda_l2': 0.0016924513888046412, 'min_child_samples': 22, 'max_depth': 8, 'max_bin': 365, 'min_data_in_leaf': 49, 'extra_trees': True, 'early_stopping_rounds': 12, 'path_smooth': 0.5820215573173859, 'min_gain_to_split': 0.31790057690827844}

[I 2025-07-16 00:07:35,059] Trial 67 finished with value: 0.2202200412080683 and parameters: {'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 00:11:07,347] Trial 68 finished with value: 0.23661349119302733 and parameters: {'num_leaves': 100, 'learning_rate': 0.020525333269332258, 'feature_fraction': 0.9802596684258852, 'bagging_fraction': 0.9328164160341444, 'bagging_freq': 3, 'lambda_l1': 1.1506412110465986e-06, 'lambda_l2': 1.9200510379492825e-05, 'min_child_samples': 28, 'max_depth': 10, 'max_bin': 266, 'min_data_in_leaf': 100, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.1335691439495491, 'min_gain_to_split': 0.05223743491888566}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 00:15:07,602] Trial 69 finished with value: 0.22545941325408667 and parameters: {'num_leaves': 90, 'learning_rate': 0.01409374690304687, 'feature_fraction': 0.9997874013038092, 'bagging_fraction': 0.9201244183294132, 'bagging_freq': 4, 'lambda_l1': 7.390986794476312e-06, 'lambda_l2': 6.363213365454907e-06, 'min_child_samples': 16, 'max_depth': 10, 'max_bin': 310, 'min_data_in_leaf': 23, 'extra_trees': True, 'early_stopping_rounds': 21, 'path_smooth': 0.38137086155426503, 'min_gain_to_split': 0.09184830679729775}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 00:17:22,824] Trial 70 finished with value: 0.22542276403672284 and parameters: {'num_leaves': 78, 'learning_rate': 0.024317692266591327, 'feature_fraction': 0.7567083175381641, 'bagging_fraction': 0.9447193111564377, 'bagging_freq': 5, 'lambda_l1': 1.9806385689105675e-06, 'lambda_l2': 8.912500070110333e-07, 'min_child_samples': 21, 'max_depth': 10, 'max_bin': 359, 'min_data_in_leaf': 31, 'extra_trees': True, 'early_stopping_rounds': 17, 'path_smooth': 0.22674466800128237, 'min_gain_to_split': 0.06332254736715327}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 00:19:51,687] Trial 71 finished with value: 0.2206602780647946 and parameters: {'num_leaves': 92, 'learning_rate': 0.0170808853777602, 'feature_fraction': 0.9323272990730822, 'bagging_fraction': 0.957739752345759, 'bagging_freq': 8, 'lambda_l1': 0.0438622983894436, 'lambda_l2': 3.787551246956779e-05, 'min_child_samples': 23, 'max_depth': 9, 'max_bin': 204, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 15, 'path_smooth': 0.31467944642060197, 'min_gain_to_split': 0.14295489269513184}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 00:22:06,846] Trial 72 finished with value: 0.27178413477460894 and parameters: {'num_leaves': 97, 'learning_rate': 0.03132742299658136, 'feature_fraction': 0.9121164275714465, 'bagging_fraction': 0.9595544849875708, 'bagging_freq': 8, 'lambda_l1': 1.814555002795123e-07, 'lambda_l2': 2.840123032297214e-05, 'min_child_samples': 22, 'max_depth': 9, 'max_bin': 193, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 15, 'path_smooth': 0.3272455372655949, 'min_gain_to_split': 0.15283555570467314}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 00:24:34,432] Trial 73 finished with value: 0.22698560883530572 and parameters: {'num_leaves': 93, 'learning_rate': 0.01770056469580752, 'feature_fraction': 0.9333680925932651, 'bagging_fraction': 0.9731789702037963, 'bagging_freq': 8, 'lambda_l1': 0.04027854066406481, 'lambda_l2': 0.0002519052919268756, 'min_child_samples': 27, 'max_depth': 10, 'max_bin': 165, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 20, 'path_smooth': 0.284888594836136, 'min_gain_to_split': 0.1426162655518488}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 00:26:47,986] Trial 74 finished with value: 0.2239737572627029 and parameters: {'num_leaves': 92, 'learning_rate': 0.019917644587181333, 'feature_fraction': 0.9542674787472755, 'bagging_fraction': 0.9351654445479775, 'bagging_freq': 9, 'lambda_l1': 2.3484051499970398, 'lambda_l2': 8.616232760661338e-06, 'min_child_samples': 23, 'max_depth': 9, 'max_bin': 210, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 13, 'path_smooth': 0.14352118375019135, 'min_gain_to_split': 0.10830045265200822}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 00:30:46,977] Trial 75 finished with value: 0.22442160274890482 and parameters: {'num_leaves': 86, 'learning_rate': 0.011132177320422161, 'feature_fraction': 0.9620901042191107, 'bagging_fraction': 0.949977126988865, 'bagging_freq': 4, 'lambda_l1': 0.0003634666162782795, 'lambda_l2': 4.1685092125678944e-05, 'min_child_samples': 26, 'max_depth': 10, 'max_bin': 231, 'min_data_in_leaf': 27, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.3752268283451514, 'min_gain_to_split': 0.03854023916346366}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 00:34:23,413] Trial 76 finished with value: 0.22066355115836522 and parameters: {'num_leaves': 100, 'learning_rate': 0.013838946879911386, 'feature_fraction': 0.9774792315326528, 'bagging_fraction': 0.956938584916132, 'bagging_freq': 10, 'lambda_l1': 0.058324251670695396, 'lambda_l2': 0.0026229173903720695, 'min_child_samples': 31, 'max_depth': 9, 'max_bin': 266, 'min_data_in_leaf': 30, 'extra_trees': True, 'early_stopping_rounds': 14, 'path_smooth': 0.2392729720803301, 'min_gain_to_split': 0.16593292179165028}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 00:37:41,504] Trial 77 finished with value: 0.22404820652325846 and parameters: {'num_leaves': 99, 'learning_rate': 0.013348116550611664, 'feature_fraction': 0.9044197870866334, 'bagging_fraction': 0.7602204621343139, 'bagging_freq': 10, 'lambda_l1': 0.05207669446881501, 'lambda_l2': 0.003269513701061777, 'min_child_samples': 15, 'max_depth': 9, 'max_bin': 265, 'min_data_in_leaf': 22, 'extra_trees': True, 'early_stopping_rounds': 14, 'path_smooth': 0.20427579757558367, 'min_gain_to_split': 0.17734811471858536}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 00:40:57,937] Trial 78 finished with value: 0.22605166946450228 and parameters: {'num_leaves': 100, 'learning_rate': 0.014238779892102664, 'feature_fraction': 0.8812055990821744, 'bagging_fraction': 0.9028337864724831, 'bagging_freq': 9, 'lambda_l1': 0.21357268538377303, 'lambda_l2': 0.03782983784086936, 'min_child_samples': 34, 'max_depth': 10, 'max_bin': 240, 'min_data_in_leaf': 45, 'extra_trees': True, 'early_stopping_rounds': 15, 'path_smooth': 0.1177842825492623, 'min_gain_to_split': 0.15708694511904453}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 00:44:23,002] Trial 79 finished with value: 0.2225787394666125 and parameters: {'num_leaves': 82, 'learning_rate': 0.011678716003434621, 'feature_fraction': 0.9265443581412607, 'bagging_fraction': 0.9221170462172616, 'bagging_freq': 10, 'lambda_l1': 0.01822058789828189, 'lambda_l2': 0.0020745204097806194, 'min_child_samples': 31, 'max_depth': 9, 'max_bin': 211, 'min_data_in_leaf': 29, 'extra_trees': True, 'early_stopping_rounds': 17, 'path_smooth': 0.5020574038521184, 'min_gain_to_split': 0.1968147071326974}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 00:45:12,022] Trial 80 finished with value: 0.22630432265664185 and parameters: {'num_leaves': 87, 'learning_rate': 0.06496312766213477, 'feature_fraction': 0.9737372727821438, 'bagging_fraction': 0.862952805128098, 'bagging_freq': 10, 'lambda_l1': 0.20172292784739507, 'lambda_l2': 0.00042561209106437703, 'min_child_samples': 19, 'max_depth': 8, 'max_bin': 268, 'min_data_in_leaf': 30, 'extra_trees': True, 'early_stopping_rounds': 11, 'path_smooth': 0.24772289123198357, 'min_gain_to_split': 0.1632624975040799}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 00:46:55,349] Trial 81 finished with value: 0.228597025147609 and parameters: {'num_leaves': 96, 'learning_rate': 0.02212675160163456, 'feature_fraction': 0.9417308541608401, 'bagging_fraction': 0.9579744263812272, 'bagging_freq': 9, 'lambda_l1': 4.2298194719697765e-08, 'lambda_l2': 0.004435790326322383, 'min_child_samples': 21, 'max_depth': 9, 'max_bin': 153, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 13, 'path_smooth': 0.6048545746187733, 'min_gain_to_split': 0.2195019028314874}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 00:50:06,250] Trial 82 finished with value: 0.2260275518446016 and parameters: {'num_leaves': 73, 'learning_rate': 0.01699033076907193, 'feature_fraction': 0.9584847597236943, 'bagging_fraction': 0.8131729639478187, 'bagging_freq': 6, 'lambda_l1': 0.0008620660017925884, 'lambda_l2': 0.013980308437578724, 'min_child_samples': 24, 'max_depth': 10, 'max_bin': 398, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 15, 'path_smooth': 0.6572533485226911, 'min_gain_to_split': 0.13437014941557704}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 00:53:18,002] Trial 83 finished with value: 0.22243781176227673 and parameters: {'num_leaves': 91, 'learning_rate': 0.015474643376531913, 'feature_fraction': 0.9858925545953842, 'bagging_fraction': 0.9783723681161846, 'bagging_freq': 7, 'lambda_l1': 0.00012990924180384235, 'lambda_l2': 0.00024933014023326616, 'min_child_samples': 28, 'max_depth': 8, 'max_bin': 325, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.30279893794592677, 'min_gain_to_split': 0.1827588039570411}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 00:58:38,755] Trial 84 finished with value: 0.22148826749349207 and parameters: {'num_leaves': 94, 'learning_rate': 0.01076686406719337, 'feature_fraction': 0.9911288626347572, 'bagging_fraction': 0.9906055027725513, 'bagging_freq': 8, 'lambda_l1': 0.07527848056815857, 'lambda_l2': 9.979638261904198e-05, 'min_child_samples': 24, 'max_depth': 8, 'max_bin': 379, 'min_data_in_leaf': 26, 'extra_trees': True, 'early_stopping_rounds': 19, 'path_smooth': 0.22391177524640127, 'min_gain_to_split': 0.07970939212583845}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 01:03:41,013] Trial 85 finished with value: 0.2228249930573059 and parameters: {'num_leaves': 95, 'learning_rate': 0.010817751109416435, 'feature_fraction': 0.991512135636537, 'bagging_fraction': 0.9889551804148263, 'bagging_freq': 8, 'lambda_l1': 0.07739991943919702, 'lambda_l2': 6.171467011994795e-05, 'min_child_samples': 22, 'max_depth': 8, 'max_bin': 379, 'min_data_in_leaf': 25, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.17232802097187566, 'min_gain_to_split': 0.07575818944488805}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 01:07:16,633] Trial 86 finished with value: 0.22211978007446337 and parameters: {'num_leaves': 98, 'learning_rate': 0.011930650683584614, 'feature_fraction': 0.9708529278560553, 'bagging_fraction': 0.9693033068334962, 'bagging_freq': 8, 'lambda_l1': 0.027232263042450938, 'lambda_l2': 1.2744147018289534e-05, 'min_child_samples': 24, 'max_depth': 8, 'max_bin': 243, 'min_data_in_leaf': 26, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.220914983328936, 'min_gain_to_split': 0.030532177334846644}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 01:10:49,207] Trial 87 finished with value: 0.22142397029353575 and parameters: {'num_leaves': 93, 'learning_rate': 0.013565527754655192, 'feature_fraction': 0.9697049898430198, 'bagging_fraction': 0.9909841443630985, 'bagging_freq': 9, 'lambda_l1': 0.3260820911629121, 'lambda_l2': 2.4845083962771683e-06, 'min_child_samples': 24, 'max_depth': 9, 'max_bin': 242, 'min_data_in_leaf': 20, 'extra_trees': True, 'early_stopping_rounds': 21, 'path_smooth': 0.21766258834644767, 'min_gain_to_split': 0.012466993614054789}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 01:17:09,259] Trial 88 finished with value: 0.29239897293115114 and parameters: {'num_leaves': 93, 'learning_rate': 0.013289296096963506, 'feature_fraction': 0.9719560200073661, 'bagging_fraction': 0.9931244218250534, 'bagging_freq': 9, 'lambda_l1': 0.3864082278011639, 'lambda_l2': 1.267717906061769e-06, 'min_child_samples': 19, 'max_depth': 9, 'max_bin': 242, 'min_data_in_leaf': 21, 'extra_trees': False, 'early_stopping_rounds': 21, 'path_smooth': 0.22784393605356856, 'min_gain_to_split': 0.039327634651145}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 01:20:37,898] Trial 89 finished with value: 0.22239566259027682 and parameters: {'num_leaves': 89, 'learning_rate': 0.011954219047901081, 'feature_fraction': 0.949210949003556, 'bagging_fraction': 0.981862414858356, 'bagging_freq': 9, 'lambda_l1': 0.7653352777857373, 'lambda_l2': 1.7886528614727937e-07, 'min_child_samples': 21, 'max_depth': 8, 'max_bin': 256, 'min_data_in_leaf': 24, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.19381508085952714, 'min_gain_to_split': 0.0073969017290943725}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 01:25:12,581] Trial 90 finished with value: 0.22263264488677872 and parameters: {'num_leaves': 86, 'learning_rate': 0.010815015764420711, 'feature_fraction': 0.9638649256172583, 'bagging_fraction': 0.9924730356073059, 'bagging_freq': 10, 'lambda_l1': 2.031614590096864, 'lambda_l2': 3.1487433980104517e-06, 'min_child_samples': 23, 'max_depth': 9, 'max_bin': 283, 'min_data_in_leaf': 20, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.06810007810280783, 'min_gain_to_split': 0.030901319208819084}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 01:29:07,904] Trial 91 finished with value: 0.22210443928411744 and parameters: {'num_leaves': 94, 'learning_rate': 0.010008056254351878, 'feature_fraction': 0.9766145503807133, 'bagging_fraction': 0.9644491198462497, 'bagging_freq': 9, 'lambda_l1': 0.07320585194626902, 'lambda_l2': 1.1406191743041531e-05, 'min_child_samples': 20, 'max_depth': 8, 'max_bin': 200, 'min_data_in_leaf': 27, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.10584247497006058, 'min_gain_to_split': 0.016584001539484656}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 01:30:33,736] Trial 92 finished with value: 0.23389923738229798 and parameters: {'num_leaves': 52, 'learning_rate': 0.010410194090374993, 'feature_fraction': 0.9382664372635267, 'bagging_fraction': 0.9529410719405024, 'bagging_freq': 9, 'lambda_l1': 0.07309608067192672, 'lambda_l2': 2.8938983572011648e-05, 'min_child_samples': 18, 'max_depth': 3, 'max_bin': 197, 'min_data_in_leaf': 27, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.09049175984407874, 'min_gain_to_split': 0.013146344616}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 01:33:46,089] Trial 93 finished with value: 0.2213273876578592 and parameters: {'num_leaves': 94, 'learning_rate': 0.012250527612367144, 'feature_fraction': 0.8336105376718923, 'bagging_fraction': 0.9820650865347249, 'bagging_freq': 9, 'lambda_l1': 0.18622248248183632, 'lambda_l2': 1.3322419680335721e-05, 'min_child_samples': 20, 'max_depth': 8, 'max_bin': 255, 'min_data_in_leaf': 27, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.10477690898524095, 'min_gain_to_split': 0.025150495302308618}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 01:36:33,159] Trial 94 finished with value: 0.22274706485160892 and parameters: {'num_leaves': 95, 'learning_rate': 0.013424251003623777, 'feature_fraction': 0.8591175131076806, 'bagging_fraction': 0.9610128479863199, 'bagging_freq': 10, 'lambda_l1': 0.1491160222606083, 'lambda_l2': 1.7306628411047985e-06, 'min_child_samples': 20, 'max_depth': 8, 'max_bin': 219, 'min_data_in_leaf': 23, 'extra_trees': True, 'early_stopping_rounds': 31, 'path_smooth': 0.1066597705694443, 'min_gain_to_split': 0.06060393618636381}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 01:37:09,697] Trial 95 finished with value: 0.23788764215370856 and parameters: {'num_leaves': 93, 'learning_rate': 0.1317938141134358, 'feature_fraction': 0.8336257009678179, 'bagging_fraction': 0.9840997736374877, 'bagging_freq': 9, 'lambda_l1': 0.2713370390212135, 'lambda_l2': 7.195417430625156e-06, 'min_child_samples': 17, 'max_depth': 9, 'max_bin': 255, 'min_data_in_leaf': 28, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.033575881879828795, 'min_gain_to_split': 0.0014330911940953484}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 01:38:40,388] Trial 96 finished with value: 0.23231287621926655 and parameters: {'num_leaves': 15, 'learning_rate': 0.012424719205369155, 'feature_fraction': 0.7976129975510812, 'bagging_fraction': 0.9991118683902185, 'bagging_freq': 9, 'lambda_l1': 0.07647088610963489, 'lambda_l2': 1.006843132188027e-05, 'min_child_samples': 20, 'max_depth': 8, 'max_bin': 187, 'min_data_in_leaf': 30, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.15505371992538292, 'min_gain_to_split': 0.019596387332499035}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 01:40:56,658] Trial 97 finished with value: 0.22187924619442984 and parameters: {'num_leaves': 88, 'learning_rate': 0.017354454095001765, 'feature_fraction': 0.998361641272174, 'bagging_fraction': 0.9925920379910367, 'bagging_freq': 10, 'lambda_l1': 1.5353757281536002, 'lambda_l2': 6.255256830848383e-07, 'min_child_samples': 14, 'max_depth': 8, 'max_bin': 203, 'min_data_in_leaf': 32, 'extra_trees': True, 'early_stopping_rounds': 30, 'path_smooth': 0.023164775948786548, 'min_gain_to_split': 0.05008374965646256}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 01:43:07,029] Trial 98 finished with value: 0.2238354681686275 and parameters: {'num_leaves': 88, 'learning_rate': 0.01775726744040602, 'feature_fraction': 0.6318743319619913, 'bagging_fraction': 0.9930694313016736, 'bagging_freq': 10, 'lambda_l1': 1.2955140456677403, 'lambda_l2': 3.0055707687201176e-07, 'min_child_samples': 10, 'max_depth': 9, 'max_bin': 271, 'min_data_in_leaf': 33, 'extra_trees': True, 'early_stopping_rounds': 34, 'path_smooth': 0.02739300041859052, 'min_gain_to_split': 0.04458997100865325}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 01:44:59,583] Trial 99 finished with value: 0.22398724000843973 and parameters: {'num_leaves': 83, 'learning_rate': 0.019122370847951778, 'feature_fraction': 0.99981936335872, 'bagging_fraction': 0.9783221254835123, 'bagging_freq': 10, 'lambda_l1': 0.5683299081725123, 'lambda_l2': 8.415196731199012, 'min_child_samples': 14, 'max_depth': 8, 'max_bin': 206, 'min_data_in_leaf': 31, 'extra_trees': True, 'early_stopping_rounds': 35, 'path_smooth': 0.01806995186449889, 'min_gain_to_split': 0.0760991192044866}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 01:47:18,066] Trial 100 finished with value: 0.22396966787828482 and parameters: {'num_leaves': 90, 'learning_rate': 0.022842820728031375, 'feature_fraction': 0.9927200292963593, 'bagging_fraction': 0.9882249325523427, 'bagging_freq': 10, 'lambda_l1': 2.904850805059619, 'lambda_l2': 5.545725627475182e-07, 'min_child_samples': 12, 'max_depth': 9, 'max_bin': 285, 'min_data_in_leaf': 24, 'extra_trees': True, 'early_stopping_rounds': 30, 'path_smooth': 0.1790998998799681, 'min_gain_to_split': 0.06428670328448664}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 01:51:09,840] Trial 101 finished with value: 0.2712949569124924 and parameters: {'num_leaves': 80, 'learning_rate': 0.014783605179499691, 'feature_fraction': 0.9809991919871257, 'bagging_fraction': 0.981395258921492, 'bagging_freq': 8, 'lambda_l1': 1.5182903572358084, 'lambda_l2': 6.432139291444626e-08, 'min_child_samples': 17, 'max_depth': 7, 'max_bin': 252, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.25129307612855295, 'min_gain_to_split': 0.05047612855975571}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 01:53:43,876] Trial 102 finished with value: 0.22362215735546073 and parameters: {'num_leaves': 86, 'learning_rate': 0.0168893171024761, 'feature_fraction': 0.8684010463129703, 'bagging_fraction': 0.9730092457088754, 'bagging_freq': 10, 'lambda_l1': 0.8614952103707435, 'lambda_l2': 4.927162417911959e-06, 'min_child_samples': 22, 'max_depth': 8, 'max_bin': 274, 'min_data_in_leaf': 29, 'extra_trees': True, 'early_stopping_rounds': 32, 'path_smooth': 0.07410152227825312, 'min_gain_to_split': 0.3099753411679842}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 01:56:09,597] Trial 103 finished with value: 0.22602606763518587 and parameters: {'num_leaves': 92, 'learning_rate': 0.013657572163030793, 'feature_fraction': 0.9758635590897942, 'bagging_fraction': 0.9666470856514225, 'bagging_freq': 9, 'lambda_l1': 6.500659336105212, 'lambda_l2': 2.964682427707131e-06, 'min_child_samples': 26, 'max_depth': 8, 'max_bin': 187, 'min_data_in_leaf': 26, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.12247703588108017, 'min_gain_to_split': 0.024578355661531825}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 01:59:58,200] Trial 104 finished with value: 0.22369814127009965 and parameters: {'num_leaves': 95, 'learning_rate': 0.010515907466060974, 'feature_fraction': 0.9545696823840496, 'bagging_fraction': 0.9931717502803344, 'bagging_freq': 9, 'lambda_l1': 3.6998928519714256, 'lambda_l2': 0.0006789249088123158, 'min_child_samples': 21, 'max_depth': 8, 'max_bin': 220, 'min_data_in_leaf': 22, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.06033262329875483, 'min_gain_to_split': 0.07242655583686662}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 02:02:47,256] Trial 105 finished with value: 0.22517615410189135 and parameters: {'num_leaves': 89, 'learning_rate': 0.010006328437491545, 'feature_fraction': 0.7868103046207906, 'bagging_fraction': 0.9622613315047525, 'bagging_freq': 9, 'lambda_l1': 0.011302666409712624, 'lambda_l2': 3.962322099158207e-05, 'min_child_samples': 19, 'max_depth': 8, 'max_bin': 163, 'min_data_in_leaf': 27, 'extra_trees': True, 'early_stopping_rounds': 30, 'path_smooth': 0.09583872632578427, 'min_gain_to_split': 0.08618653634876552}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 02:05:36,150] Trial 106 finished with value: 0.22777195268172182 and parameters: {'num_leaves': 94, 'learning_rate': 0.012054377568947896, 'feature_fraction': 0.9643255538759552, 'bagging_fraction': 0.975024406739967, 'bagging_freq': 8, 'lambda_l1': 0.3344191439977526, 'lambda_l2': 8.429330337941751e-05, 'min_child_samples': 16, 'max_depth': 7, 'max_bin': 236, 'min_data_in_leaf': 62, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.048582979181873306, 'min_gain_to_split': 0.2793119607391814}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 02:09:02,536] Trial 107 finished with value: 0.23893817086225494 and parameters: {'num_leaves': 96, 'learning_rate': 0.013030180749470566, 'feature_fraction': 0.988487919071978, 'bagging_fraction': 0.9996746893718222, 'bagging_freq': 10, 'lambda_l1': 0.0052869705361030805, 'lambda_l2': 0.00019826573995544077, 'min_child_samples': 43, 'max_depth': 8, 'max_bin': 178, 'min_data_in_leaf': 95, 'extra_trees': True, 'early_stopping_rounds': 21, 'path_smooth': 0.5511100493354469, 'min_gain_to_split': 0.10243105457591574}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 02:12:29,928] Trial 108 finished with value: 0.22145587678737583 and parameters: {'num_leaves': 99, 'learning_rate': 0.014994447445710291, 'feature_fraction': 0.979651510669196, 'bagging_fraction': 0.955769546021156, 'bagging_freq': 8, 'lambda_l1': 0.14546319711368844, 'lambda_l2': 2.1685395551069782e-06, 'min_child_samples': 23, 'max_depth': 9, 'max_bin': 262, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.15653170431738456, 'min_gain_to_split': 0.032761517756796366}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 02:14:44,995] Trial 109 finished with value: 0.22336084701942532 and parameters: {'num_leaves': 98, 'learning_rate': 0.02626936975383148, 'feature_fraction': 0.9947525578787547, 'bagging_fraction': 0.9464463546859746, 'bagging_freq': 8, 'lambda_l1': 0.11200684906385305, 'lambda_l2': 5.809146711137086e-07, 'min_child_samples': 25, 'max_depth': 9, 'max_bin': 263, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.15087721868441475, 'min_gain_to_split': 0.45599770806817175}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 02:17:20,283] Trial 110 finished with value: 0.22829239547277685 and parameters: {'num_leaves': 100, 'learning_rate': 0.015155854202106349, 'feature_fraction': 0.9825735494528294, 'bagging_fraction': 0.9858381736223474, 'bagging_freq': 7, 'lambda_l1': 0.1901730917741834, 'lambda_l2': 1.6123026751897736e-06, 'min_child_samples': 27, 'max_depth': 9, 'max_bin': 134, 'min_data_in_leaf': 58, 'extra_trees': True, 'early_stopping_rounds': 31, 'path_smooth': 0.1925530038288629, 'min_gain_to_split': 0.34249111498331725}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 02:20:25,601] Trial 111 finished with value: 0.22291103112255936 and parameters: {'num_leaves': 91, 'learning_rate': 0.016497087884472215, 'feature_fraction': 0.9585405332261614, 'bagging_fraction': 0.9716079683133563, 'bagging_freq': 8, 'lambda_l1': 0.6100704550718183, 'lambda_l2': 4.107673712468958e-06, 'min_child_samples': 23, 'max_depth': 9, 'max_bin': 318, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 11, 'path_smooth': 0.27313446514960354, 'min_gain_to_split': 0.033283983815901905}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 02:20:54,529] Trial 112 finished with value: 0.242559190566715 and parameters: {'num_leaves': 88, 'learning_rate': 0.1935903313467057, 'feature_fraction': 0.7580812917289561, 'bagging_fraction': 0.9807667648092566, 'bagging_freq': 7, 'lambda_l1': 0.041333365515190304, 'lambda_l2': 1.1704187046983155e-07, 'min_child_samples': 49, 'max_depth': 9, 'max_bin': 301, 'min_data_in_leaf': 32, 'extra_trees': True, 'early_stopping_rounds': 23, 'path_smooth': 0.16678204376017267, 'min_gain_to_split': 0.05543411309709182}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 02:24:21,635] Trial 113 finished with value: 0.22143858344455608 and parameters: {'num_leaves': 93, 'learning_rate': 0.011143945096344473, 'feature_fraction': 0.9752296057676534, 'bagging_fraction': 0.9548995422922055, 'bagging_freq': 9, 'lambda_l1': 0.10650008004379494, 'lambda_l2': 2.5371076135985206e-05, 'min_child_samples': 22, 'max_depth': 8, 'max_bin': 201, 'min_data_in_leaf': 30, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.0015737543847606644, 'min_gain_to_split': 0.015418741827656235}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 02:27:10,426] Trial 114 finished with value: 0.22257781673914218 and parameters: {'num_leaves': 92, 'learning_rate': 0.014068220772060224, 'feature_fraction': 0.9206725315246891, 'bagging_fraction': 0.9410612999458333, 'bagging_freq': 5, 'lambda_l1': 0.11992806370147101, 'lambda_l2': 2.3803253331290592e-05, 'min_child_samples': 22, 'max_depth': 8, 'max_bin': 222, 'min_data_in_leaf': 30, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.043229633439516205, 'min_gain_to_split': 0.023501959650184458}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 02:31:07,494] Trial 115 finished with value: 0.22188726766565328 and parameters: {'num_leaves': 96, 'learning_rate': 0.011084357259560692, 'feature_fraction': 0.9427517633243285, 'bagging_fraction': 0.9514213347441223, 'bagging_freq': 9, 'lambda_l1': 0.3537152440654676, 'lambda_l2': 0.001632367515908555, 'min_child_samples': 23, 'max_depth': 9, 'max_bin': 246, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.01645863730643824, 'min_gain_to_split': 0.01094966086615956}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 02:33:52,566] Trial 116 finished with value: 0.2206580556947178 and parameters: {'num_leaves': 99, 'learning_rate': 0.012886157577440067, 'feature_fraction': 0.6848490987589426, 'bagging_fraction': 0.9574337868931257, 'bagging_freq': 8, 'lambda_l1': 0.04643362672547468, 'lambda_l2': 2.135120414008035e-06, 'min_child_samples': 24, 'max_depth': 7, 'max_bin': 422, 'min_data_in_leaf': 40, 'extra_trees': True, 'early_stopping_rounds': 19, 'path_smooth': 0.21206345238320984, 'min_gain_to_split': 0.05195575092600297}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 02:36:57,500] Trial 117 finished with value: 0.22384395474912128 and parameters: {'num_leaves': 99, 'learning_rate': 0.012333409695413373, 'feature_fraction': 0.718380835951003, 'bagging_fraction': 0.9579495126125229, 'bagging_freq': 8, 'lambda_l1': 0.04880819876263693, 'lambda_l2': 2.427131318016689e-06, 'min_child_samples': 24, 'max_depth': 7, 'max_bin': 451, 'min_data_in_leaf': 43, 'extra_trees': True, 'early_stopping_rounds': 19, 'path_smooth': 0.2225836755690772, 'min_gain_to_split': 0.0686019539941176}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 02:39:18,648] Trial 118 finished with value: 0.22476752504887135 and parameters: {'num_leaves': 97, 'learning_rate': 0.014945445523988576, 'feature_fraction': 0.9045507413924484, 'bagging_fraction': 0.9551708215226022, 'bagging_freq': 8, 'lambda_l1': 0.01893654094609182, 'lambda_l2': 0.0004435616155646073, 'min_child_samples': 26, 'max_depth': 6, 'max_bin': 408, 'min_data_in_leaf': 47, 'extra_trees': True, 'early_stopping_rounds': 23, 'path_smooth': 0.5221651445366455, 'min_gain_to_split': 0.24828164932416083}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 02:41:49,575] Trial 119 finished with value: 0.22600108858781875 and parameters: {'num_leaves': 98, 'learning_rate': 0.013309432352877893, 'feature_fraction': 0.6196928789319116, 'bagging_fraction': 0.9318984305020537, 'bagging_freq': 8, 'lambda_l1': 3.7156261126111646e-07, 'lambda_l2': 1.4776094147517606e-05, 'min_child_samples': 21, 'max_depth': 7, 'max_bin': 390, 'min_data_in_leaf': 51, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.247021004455254, 'min_gain_to_split': 0.03966466884897964}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 02:42:43,271] Trial 120 finished with value: 0.2688080538969301 and parameters: {'num_leaves': 100, 'learning_rate': 0.09499149664189852, 'feature_fraction': 0.6882447781551563, 'bagging_fraction': 0.9650632945368195, 'bagging_freq': 7, 'lambda_l1': 0.0028519681760668806, 'lambda_l2': 6.25746092387616e-05, 'min_child_samples': 25, 'max_depth': 7, 'max_bin': 425, 'min_data_in_leaf': 41, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.19923123429731673, 'min_gain_to_split': 0.003413241679139466}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 02:46:50,793] Trial 121 finished with value: 0.2239245479271605 and parameters: {'num_leaves': 93, 'learning_rate': 0.011753450700781747, 'feature_fraction': 0.668083354988757, 'bagging_fraction': 0.9450226354138216, 'bagging_freq': 8, 'lambda_l1': 1.319979338749727e-05, 'lambda_l2': 3.8133913529773294e-05, 'min_child_samples': 39, 'max_depth': 9, 'max_bin': 419, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 20, 'path_smooth': 0.5847648351963128, 'min_gain_to_split': 0.4129906775881537}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 02:50:17,427] Trial 122 finished with value: 0.22367234691230015 and parameters: {'num_leaves': 96, 'learning_rate': 0.012616832501059114, 'feature_fraction': 0.8891190072896921, 'bagging_fraction': 0.9763107599121547, 'bagging_freq': 7, 'lambda_l1': 0.00728603783152683, 'lambda_l2': 4.645887133468355e-06, 'min_child_samples': 22, 'max_depth': 7, 'max_bin': 476, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 17, 'path_smooth': 0.3175458421009008, 'min_gain_to_split': 0.3773929145552709}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 02:52:28,760] Trial 123 finished with value: 0.22322463981091162 and parameters: {'num_leaves': 90, 'learning_rate': 0.018053731188279933, 'feature_fraction': 0.809131792657348, 'bagging_fraction': 0.9932703199881349, 'bagging_freq': 9, 'lambda_l1': 0.14079109582142724, 'lambda_l2': 8.814600539213176e-07, 'min_child_samples': 24, 'max_depth': 8, 'max_bin': 262, 'min_data_in_leaf': 33, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.1340124578227663, 'min_gain_to_split': 0.04879067203687659}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 02:54:37,596] Trial 124 finished with value: 0.2248719116408468 and parameters: {'num_leaves': 84, 'learning_rate': 0.02057314970684888, 'feature_fraction': 0.7387309413632699, 'bagging_fraction': 0.9869947060065934, 'bagging_freq': 10, 'lambda_l1': 0.013053518377271435, 'lambda_l2': 6.263841067875304e-07, 'min_child_samples': 23, 'max_depth': 8, 'max_bin': 355, 'min_data_in_leaf': 40, 'extra_trees': True, 'early_stopping_rounds': 13, 'path_smooth': 0.21393664983787897, 'min_gain_to_split': 0.26394221623515784}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 02:57:44,571] Trial 125 finished with value: 0.22313693531715764 and parameters: {'num_leaves': 94, 'learning_rate': 0.013845377451621352, 'feature_fraction': 0.9679058757295477, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 9, 'lambda_l1': 0.23938778717122866, 'lambda_l2': 0.0010929531936531513, 'min_child_samples': 44, 'max_depth': 8, 'max_bin': 291, 'min_data_in_leaf': 29, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.17867003497175896, 'min_gain_to_split': 0.0864822310485748}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 03:00:56,303] Trial 126 finished with value: 0.22145700508970104 and parameters: {'num_leaves': 91, 'learning_rate': 0.015598146375055234, 'feature_fraction': 0.8330919473203547, 'bagging_fraction': 0.9683538908800672, 'bagging_freq': 8, 'lambda_l1': 0.04786070596218446, 'lambda_l2': 2.047952379006158e-06, 'min_child_samples': 21, 'max_depth': 8, 'max_bin': 401, 'min_data_in_leaf': 31, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.6297752719688532, 'min_gain_to_split': 0.02825289574445911}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 03:04:40,925] Trial 127 finished with value: 0.22460235602171497 and parameters: {'num_leaves': 92, 'learning_rate': 0.015609193765171139, 'feature_fraction': 0.8417373436895812, 'bagging_fraction': 0.9699006838652496, 'bagging_freq': 8, 'lambda_l1': 0.03419970507824784, 'lambda_l2': 0.0024158500663775, 'min_child_samples': 36, 'max_depth': 9, 'max_bin': 403, 'min_data_in_leaf': 25, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.6242199653846148, 'min_gain_to_split': 0.029809785695304177}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 03:08:16,251] Trial 128 finished with value: 0.2248811635800636 and parameters: {'num_leaves': 98, 'learning_rate': 0.011084853898955103, 'feature_fraction': 0.7828613797978149, 'bagging_fraction': 0.9597842452667495, 'bagging_freq': 8, 'lambda_l1': 0.09186556136083568, 'lambda_l2': 7.256181135495243e-06, 'min_child_samples': 18, 'max_depth': 7, 'max_bin': 438, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 41, 'path_smooth': 0.6478285888718123, 'min_gain_to_split': 0.016182878476110312}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 03:10:36,646] Trial 129 finished with value: 0.22272323803946956 and parameters: {'num_leaves': 95, 'learning_rate': 0.014480095165518292, 'feature_fraction': 0.950678123217745, 'bagging_fraction': 0.9271897486874748, 'bagging_freq': 7, 'lambda_l1': 0.02334929341119808, 'lambda_l2': 2.165936395758076e-06, 'min_child_samples': 21, 'max_depth': 6, 'max_bin': 384, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.5577598602957455, 'min_gain_to_split': 0.11818498113412391}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 03:14:13,409] Trial 130 finished with value: 0.22482766248899302 and parameters: {'num_leaves': 59, 'learning_rate': 0.012547832895653161, 'feature_fraction': 0.8508485746561678, 'bagging_fraction': 0.9521939230202636, 'bagging_freq': 8, 'lambda_l1': 0.054404173238363746, 'lambda_l2': 2.0723107142593823e-05, 'min_child_samples': 22, 'max_depth': 8, 'max_bin': 399, 'min_data_in_leaf': 20, 'extra_trees': True, 'early_stopping_rounds': 21, 'path_smooth': 0.24029008692467724, 'min_gain_to_split': 0.04032283844117353}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 03:17:37,321] Trial 131 finished with value: 0.22368933695028598 and parameters: {'num_leaves': 63, 'learning_rate': 0.011355066371515067, 'feature_fraction': 0.8270059934135946, 'bagging_fraction': 0.9362839211148738, 'bagging_freq': 5, 'lambda_l1': 0.17858630595035802, 'lambda_l2': 0.00012702066319955516, 'min_child_samples': 20, 'max_depth': 10, 'max_bin': 279, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 14, 'path_smooth': 0.7167169107471685, 'min_gain_to_split': 0.3535969296493655}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 03:21:37,213] Trial 132 finished with value: 0.22227334521862074 and parameters: {'num_leaves': 100, 'learning_rate': 0.015971479877282497, 'feature_fraction': 0.9848363174601381, 'bagging_fraction': 0.8411403996820318, 'bagging_freq': 8, 'lambda_l1': 0.000264557299150134, 'lambda_l2': 3.294983350200083e-07, 'min_child_samples': 23, 'max_depth': 9, 'max_bin': 417, 'min_data_in_leaf': 31, 'extra_trees': True, 'early_stopping_rounds': 15, 'path_smooth': 0.5960979075410964, 'min_gain_to_split': 0.05838046806018178}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 03:24:39,259] Trial 133 finished with value: 0.22187126162055462 and parameters: {'num_leaves': 86, 'learning_rate': 0.01738256136683519, 'feature_fraction': 0.9763518774788265, 'bagging_fraction': 0.9806038193082507, 'bagging_freq': 9, 'lambda_l1': 0.47131936845577704, 'lambda_l2': 1.5551803136460058e-06, 'min_child_samples': 24, 'max_depth': 8, 'max_bin': 366, 'min_data_in_leaf': 31, 'extra_trees': True, 'early_stopping_rounds': 31, 'path_smooth': 0.5340240867739182, 'min_gain_to_split': 0.04990862140675521}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 03:27:16,902] Trial 134 finished with value: 0.22348912590774575 and parameters: {'num_leaves': 87, 'learning_rate': 0.019390396751716825, 'feature_fraction': 0.8076609812420771, 'bagging_fraction': 0.9805782918883343, 'bagging_freq': 9, 'lambda_l1': 0.05219918403068911, 'lambda_l2': 1.273999451507283e-06, 'min_child_samples': 25, 'max_depth': 8, 'max_bin': 370, 'min_data_in_leaf': 30, 'extra_trees': True, 'early_stopping_rounds': 32, 'path_smooth': 0.5319329626095273, 'min_gain_to_split': 0.0236095778575988}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 03:30:59,184] Trial 135 finished with value: 0.22304184050480674 and parameters: {'num_leaves': 91, 'learning_rate': 0.01352056232006345, 'feature_fraction': 0.9736760720317916, 'bagging_fraction': 0.9636343020582956, 'bagging_freq': 1, 'lambda_l1': 0.3943508173859414, 'lambda_l2': 0.004948949222090516, 'min_child_samples': 24, 'max_depth': 8, 'max_bin': 344, 'min_data_in_leaf': 28, 'extra_trees': True, 'early_stopping_rounds': 31, 'path_smooth': 0.5023762108618096, 'min_gain_to_split': 0.0005857495798180581}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 03:34:00,491] Trial 136 finished with value: 0.2237166372749304 and parameters: {'num_leaves': 85, 'learning_rate': 0.015035067772592413, 'feature_fraction': 0.8378598795061736, 'bagging_fraction': 0.9722990460318787, 'bagging_freq': 9, 'lambda_l1': 0.11752904154532978, 'lambda_l2': 5.225966592403776e-06, 'min_child_samples': 26, 'max_depth': 8, 'max_bin': 367, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 17, 'path_smooth': 0.6099755446546413, 'min_gain_to_split': 0.09644483529393054}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 03:35:32,397] Trial 137 finished with value: 0.22417879509734745 and parameters: {'num_leaves': 93, 'learning_rate': 0.0375021079408983, 'feature_fraction': 0.9614206685349403, 'bagging_fraction': 0.9850046078531548, 'bagging_freq': 8, 'lambda_l1': 0.0004591705360257752, 'lambda_l2': 1.7806762850434028e-06, 'min_child_samples': 21, 'max_depth': 8, 'max_bin': 335, 'min_data_in_leaf': 24, 'extra_trees': True, 'early_stopping_rounds': 19, 'path_smooth': 0.5565009512006923, 'min_gain_to_split': 0.03423887333428244}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 03:39:53,717] Trial 138 finished with value: 0.22276222517856642 and parameters: {'num_leaves': 97, 'learning_rate': 0.012158697493961684, 'feature_fraction': 0.9782934395479025, 'bagging_fraction': 0.9564431557030111, 'bagging_freq': 9, 'lambda_l1': 2.3572214523138244e-05, 'lambda_l2': 3.5109304435023402e-06, 'min_child_samples': 23, 'max_depth': 8, 'max_bin': 380, 'min_data_in_leaf': 31, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.6659248647526466, 'min_gain_to_split': 0.07740220370679306}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 03:42:13,227] Trial 139 finished with value: 0.2247540976716867 and parameters: {'num_leaves': 90, 'learning_rate': 0.016841080211476768, 'feature_fraction': 0.9893797044236596, 'bagging_fraction': 0.9772118867175464, 'bagging_freq': 7, 'lambda_l1': 0.0012606574142635923, 'lambda_l2': 0.0007095154000897319, 'min_child_samples': 19, 'max_depth': 7, 'max_bin': 250, 'min_data_in_leaf': 28, 'extra_trees': True, 'early_stopping_rounds': 33, 'path_smooth': 0.2652879846264329, 'min_gain_to_split': 0.06394650891898412}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 03:46:02,399] Trial 140 finished with value: 0.22365920347962387 and parameters: {'num_leaves': 82, 'learning_rate': 0.014128334131088703, 'feature_fraction': 0.9688564084094404, 'bagging_fraction': 0.9684009389929408, 'bagging_freq': 9, 'lambda_l1': 0.25310505882293627, 'lambda_l2': 0.00034148453277361014, 'min_child_samples': 20, 'max_depth': 9, 'max_bin': 351, 'min_data_in_leaf': 45, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.1619214259083321, 'min_gain_to_split': 0.04575465808729086}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 03:49:44,483] Trial 141 finished with value: 0.2782191883275833 and parameters: {'num_leaves': 35, 'learning_rate': 0.01861061214272421, 'feature_fraction': 0.9487454593119916, 'bagging_fraction': 0.7898625490458896, 'bagging_freq': 8, 'lambda_l1': 0.4898427879745628, 'lambda_l2': 0.00016915283963805098, 'min_child_samples': 28, 'max_depth': 10, 'max_bin': 394, 'min_data_in_leaf': 55, 'extra_trees': False, 'early_stopping_rounds': 17, 'path_smooth': 0.5134549462223492, 'min_gain_to_split': 0.23649065773996814}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 03:53:59,358] Trial 142 finished with value: 0.22241450064327623 and parameters: {'num_leaves': 78, 'learning_rate': 0.01071491766409469, 'feature_fraction': 0.9837285864143874, 'bagging_fraction': 0.9974875631610198, 'bagging_freq': 4, 'lambda_l1': 0.08218204291659433, 'lambda_l2': 9.293434228276019e-07, 'min_child_samples': 22, 'max_depth': 8, 'max_bin': 270, 'min_data_in_leaf': 26, 'extra_trees': True, 'early_stopping_rounds': 22, 'path_smooth': 0.7001656932386523, 'min_gain_to_split': 0.015151199540169531}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 03:57:05,551] Trial 143 finished with value: 0.22268455563343656 and parameters: {'num_leaves': 88, 'learning_rate': 0.013046019638202164, 'feature_fraction': 0.9893557404103522, 'bagging_fraction': 0.9893729310597245, 'bagging_freq': 10, 'lambda_l1': 1.5797778570914478, 'lambda_l2': 5.233080809783434e-07, 'min_child_samples': 33, 'max_depth': 8, 'max_bin': 202, 'min_data_in_leaf': 32, 'extra_trees': True, 'early_stopping_rounds': 30, 'path_smooth': 0.4630207041403994, 'min_gain_to_split': 0.050221051700092556}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 03:59:24,761] Trial 144 finished with value: 0.2230396037962814 and parameters: {'num_leaves': 86, 'learning_rate': 0.01742414364462768, 'feature_fraction': 0.9973067814418832, 'bagging_fraction': 0.9909079388893759, 'bagging_freq': 10, 'lambda_l1': 0.852999652393098, 'lambda_l2': 3.704193464481387e-07, 'min_child_samples': 24, 'max_depth': 8, 'max_bin': 217, 'min_data_in_leaf': 33, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.004292428102309915, 'min_gain_to_split': 0.31083397155044806}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 04:01:53,359] Trial 145 finished with value: 0.22309957454888285 and parameters: {'num_leaves': 67, 'learning_rate': 0.015966275174300215, 'feature_fraction': 0.9754622674994864, 'bagging_fraction': 0.9826107741476982, 'bagging_freq': 9, 'lambda_l1': 0.05721304467821835, 'lambda_l2': 8.315365501470668e-05, 'min_child_samples': 27, 'max_depth': 8, 'max_bin': 231, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 31, 'path_smooth': 0.0012901220231894628, 'min_gain_to_split': 0.024168293157456847}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 04:04:51,306] Trial 146 finished with value: 0.22061137522334234 and parameters: {'num_leaves': 94, 'learning_rate': 0.01454391699751878, 'feature_fraction': 0.9999255660973104, 'bagging_fraction': 0.9782700961831664, 'bagging_freq': 9, 'lambda_l1': 1.0859839585644013, 'lambda_l2': 1.9780547270667266e-07, 'min_child_samples': 14, 'max_depth': 8, 'max_bin': 259, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 32, 'path_smooth': 0.6312662731536925, 'min_gain_to_split': 0.335480847430404}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 04:06:02,699] Trial 147 finished with value: 0.22603706427850198 and parameters: {'num_leaves': 95, 'learning_rate': 0.05424326259825308, 'feature_fraction': 0.9701918951287313, 'bagging_fraction': 0.9623215086841912, 'bagging_freq': 9, 'lambda_l1': 0.15490083244287808, 'lambda_l2': 3.220444734096949e-05, 'min_child_samples': 24, 'max_depth': 9, 'max_bin': 272, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 33, 'path_smooth': 0.632363235103209, 'min_gain_to_split': 0.2878770398799273}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 04:09:28,034] Trial 148 finished with value: 0.2212842402733605 and parameters: {'num_leaves': 94, 'learning_rate': 0.011852983236055997, 'feature_fraction': 0.934922477759045, 'bagging_fraction': 0.9471059242631001, 'bagging_freq': 8, 'lambda_l1': 6.6286815168597325e-06, 'lambda_l2': 5.3595000651487276e-08, 'min_child_samples': 22, 'max_depth': 8, 'max_bin': 258, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 12, 'path_smooth': 0.5854100964259206, 'min_gain_to_split': 0.3308019413028116}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 04:12:52,328] Trial 149 finished with value: 0.22093061347727633 and parameters: {'num_leaves': 94, 'learning_rate': 0.011597336304679887, 'feature_fraction': 0.9327579790963255, 'bagging_fraction': 0.948570504883091, 'bagging_freq': 8, 'lambda_l1': 2.1052672614495794e-06, 'lambda_l2': 1.2420032054474385e-08, 'min_child_samples': 46, 'max_depth': 8, 'max_bin': 257, 'min_data_in_leaf': 41, 'extra_trees': True, 'early_stopping_rounds': 13, 'path_smooth': 0.5885085665762273, 'min_gain_to_split': 0.34188905604333064}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 04:15:39,063] Trial 150 finished with value: 0.2234926152763273 and parameters: {'num_leaves': 96, 'learning_rate': 0.011675297074933966, 'feature_fraction': 0.9365523292231118, 'bagging_fraction': 0.948513467130016, 'bagging_freq': 8, 'lambda_l1': 1.2579022243393446e-06, 'lambda_l2': 5.112156793025803e-08, 'min_child_samples': 46, 'max_depth': 7, 'max_bin': 255, 'min_data_in_leaf': 42, 'extra_trees': True, 'early_stopping_rounds': 12, 'path_smooth': 0.5906061034221533, 'min_gain_to_split': 0.33304827430742945}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 04:19:38,761] Trial 151 finished with value: 0.22314745110137552 and parameters: {'num_leaves': 98, 'learning_rate': 0.01068601833129333, 'feature_fraction': 0.9074207170390041, 'bagging_fraction': 0.9399390249395742, 'bagging_freq': 8, 'lambda_l1': 8.816963483683998e-07, 'lambda_l2': 2.4153453816010313e-08, 'min_child_samples': 22, 'max_depth': 9, 'max_bin': 259, 'min_data_in_leaf': 40, 'extra_trees': True, 'early_stopping_rounds': 12, 'path_smooth': 0.6119594888050982, 'min_gain_to_split': 0.3217524922819435}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 04:22:30,134] Trial 152 finished with value: 0.22473135045536932 and parameters: {'num_leaves': 94, 'learning_rate': 0.01307763977152734, 'feature_fraction': 0.9235064351008838, 'bagging_fraction': 0.9092795295391558, 'bagging_freq': 8, 'lambda_l1': 6.1574397958202686e-06, 'lambda_l2': 1.443183267238724e-08, 'min_child_samples': 21, 'max_depth': 8, 'max_bin': 238, 'min_data_in_leaf': 44, 'extra_trees': True, 'early_stopping_rounds': 11, 'path_smooth': 0.6442731988439239, 'min_gain_to_split': 0.33749330106291386}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 04:25:44,773] Trial 153 finished with value: 0.22050566220324402 and parameters: {'num_leaves': 93, 'learning_rate': 0.01181279235903027, 'feature_fraction': 0.880296474543411, 'bagging_fraction': 0.9456680160607636, 'bagging_freq': 8, 'lambda_l1': 2.239040570959782e-06, 'lambda_l2': 1.1278801570654965e-07, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 247, 'min_data_in_leaf': 40, 'extra_trees': True, 'early_stopping_rounds': 13, 'path_smooth': 0.5669911096769286, 'min_gain_to_split': 0.3589057262809192}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 04:29:04,110] Trial 154 finished with value: 0.2206626975836068 and parameters: {'num_leaves': 92, 'learning_rate': 0.011543388959187004, 'feature_fraction': 0.8842463361566214, 'bagging_fraction': 0.9456942779151087, 'bagging_freq': 8, 'lambda_l1': 3.0212416350400315e-06, 'lambda_l2': 1.0193305922758563e-08, 'min_child_samples': 47, 'max_depth': 8, 'max_bin': 244, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 14, 'path_smooth': 0.5680599283255643, 'min_gain_to_split': 0.3621203285545993}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 04:32:12,660] Trial 155 finished with value: 0.22088067570471343 and parameters: {'num_leaves': 92, 'learning_rate': 0.011402114462230157, 'feature_fraction': 0.880541619318049, 'bagging_fraction': 0.9453390265630152, 'bagging_freq': 8, 'lambda_l1': 4.527911129633506e-06, 'lambda_l2': 1.0066963931329104e-08, 'min_child_samples': 49, 'max_depth': 8, 'max_bin': 244, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 13, 'path_smooth': 0.5694258443306288, 'min_gain_to_split': 0.36402359864522554}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 04:35:23,070] Trial 156 finished with value: 0.22070638478902982 and parameters: {'num_leaves': 92, 'learning_rate': 0.011566137141868792, 'feature_fraction': 0.8793552955782741, 'bagging_fraction': 0.9427708863765492, 'bagging_freq': 8, 'lambda_l1': 1.957206774374332e-06, 'lambda_l2': 2.263391358815767e-08, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 245, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 13, 'path_smooth': 0.5675235186367779, 'min_gain_to_split': 0.35170049690135163}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 04:38:34,096] Trial 157 finished with value: 0.22350307872726433 and parameters: {'num_leaves': 93, 'learning_rate': 0.011419534060419494, 'feature_fraction': 0.8852339971022999, 'bagging_fraction': 0.9294859712477481, 'bagging_freq': 8, 'lambda_l1': 2.1309202331857707e-06, 'lambda_l2': 1.0370344589574365e-08, 'min_child_samples': 49, 'max_depth': 8, 'max_bin': 248, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 13, 'path_smooth': 0.5774977116898815, 'min_gain_to_split': 0.3578405442365918}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 04:41:35,585] Trial 158 finished with value: 0.22306444132550238 and parameters: {'num_leaves': 96, 'learning_rate': 0.012285176350694477, 'feature_fraction': 0.8680360480389753, 'bagging_fraction': 0.9420900994653201, 'bagging_freq': 8, 'lambda_l1': 3.2967315693909914e-06, 'lambda_l2': 4.5756819088952504e-08, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 239, 'min_data_in_leaf': 43, 'extra_trees': True, 'early_stopping_rounds': 14, 'path_smooth': 0.5731085883772394, 'min_gain_to_split': 0.3510615673773754}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 04:44:50,490] Trial 159 finished with value: 0.22268597056815875 and parameters: {'num_leaves': 99, 'learning_rate': 0.011891000866353349, 'feature_fraction': 0.8789838866117944, 'bagging_fraction': 0.9471061177080324, 'bagging_freq': 8, 'lambda_l1': 8.79532827890817e-06, 'lambda_l2': 2.5664795617378538e-08, 'min_child_samples': 50, 'max_depth': 8, 'max_bin': 262, 'min_data_in_leaf': 41, 'extra_trees': True, 'early_stopping_rounds': 13, 'path_smooth': 0.6033621218744171, 'min_gain_to_split': 0.36730145356439564}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 04:48:53,073] Trial 160 finished with value: 0.22195405130485701 and parameters: {'num_leaves': 92, 'learning_rate': 0.01015876298792419, 'feature_fraction': 0.8615120436649917, 'bagging_fraction': 0.9363383906286545, 'bagging_freq': 8, 'lambda_l1': 2.3939177229781153e-06, 'lambda_l2': 1.0001431681974864e-08, 'min_child_samples': 49, 'max_depth': 9, 'max_bin': 245, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 10, 'path_smooth': 0.5594962024687828, 'min_gain_to_split': 0.3872150178785755}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 04:51:46,569] Trial 161 finished with value: 0.22490902119014572 and parameters: {'num_leaves': 97, 'learning_rate': 0.013976680427363046, 'feature_fraction': 0.8914395058249328, 'bagging_fraction': 0.944304651158556, 'bagging_freq': 8, 'lambda_l1': 7.705123062044442e-07, 'lambda_l2': 1.096975602501989e-07, 'min_child_samples': 47, 'max_depth': 8, 'max_bin': 228, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 12, 'path_smooth': 0.586216716944995, 'min_gain_to_split': 0.3446693927630663}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 04:52:10,483] Trial 162 finished with value: 0.25047490661789257 and parameters: {'num_leaves': 90, 'learning_rate': 0.29248714936586845, 'feature_fraction': 0.9168075194171791, 'bagging_fraction': 0.9262078177479112, 'bagging_freq': 9, 'lambda_l1': 4.650245525517579e-06, 'lambda_l2': 3.365078152123915e-08, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 257, 'min_data_in_leaf': 41, 'extra_trees': True, 'early_stopping_rounds': 15, 'path_smooth': 0.6803729992442158, 'min_gain_to_split': 0.3692212344180033}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 04:55:08,441] Trial 163 finished with value: 0.22441781001623604 and parameters: {'num_leaves': 92, 'learning_rate': 0.012670135204043914, 'feature_fraction': 0.8748238955426945, 'bagging_fraction': 0.9556853894900158, 'bagging_freq': 8, 'lambda_l1': 1.4510654643027152e-06, 'lambda_l2': 1.951803026801165e-08, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 235, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 13, 'path_smooth': 0.6090612079779608, 'min_gain_to_split': 0.3319040929664448}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 04:58:39,961] Trial 164 finished with value: 0.22056100942626963 and parameters: {'num_leaves': 91, 'learning_rate': 0.01136635150049403, 'feature_fraction': 0.8992553456176108, 'bagging_fraction': 0.9491048026764815, 'bagging_freq': 8, 'lambda_l1': 2.5103718601935535e-06, 'lambda_l2': 1.1572973895351115e-07, 'min_child_samples': 47, 'max_depth': 8, 'max_bin': 252, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 14, 'path_smooth': 0.6242302072518481, 'min_gain_to_split': 0.36044436272431213}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 05:01:58,443] Trial 165 finished with value: 0.22232888725538733 and parameters: {'num_leaves': 95, 'learning_rate': 0.011384076739819431, 'feature_fraction': 0.896916830914631, 'bagging_fraction': 0.9496391418927522, 'bagging_freq': 8, 'lambda_l1': 2.756706042106158e-06, 'lambda_l2': 8.414148601522376e-08, 'min_child_samples': 46, 'max_depth': 8, 'max_bin': 253, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 14, 'path_smooth': 0.5456564329619858, 'min_gain_to_split': 0.35730317957450164}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 05:05:22,240] Trial 166 finished with value: 0.22081090760816208 and parameters: {'num_leaves': 89, 'learning_rate': 0.010870249527133372, 'feature_fraction': 0.883175553415672, 'bagging_fraction': 0.9369411244855993, 'bagging_freq': 8, 'lambda_l1': 6.2146224229077466e-06, 'lambda_l2': 1.9758817541266625e-07, 'min_child_samples': 47, 'max_depth': 8, 'max_bin': 245, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 14, 'path_smooth': 0.6374219890707312, 'min_gain_to_split': 0.40394569557442545}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 05:08:42,161] Trial 167 finished with value: 0.22232895705759362 and parameters: {'num_leaves': 90, 'learning_rate': 0.010805095494099777, 'feature_fraction': 0.8704121074936544, 'bagging_fraction': 0.9226632261667769, 'bagging_freq': 8, 'lambda_l1': 5.993963404894426e-07, 'lambda_l2': 1.7404042608943768e-07, 'min_child_samples': 47, 'max_depth': 8, 'max_bin': 246, 'min_data_in_leaf': 42, 'extra_trees': True, 'early_stopping_rounds': 14, 'path_smooth': 0.6332308385864901, 'min_gain_to_split': 0.4150369937356212}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 05:11:40,632] Trial 168 finished with value: 0.22562729649459595 and parameters: {'num_leaves': 89, 'learning_rate': 0.011707358305210264, 'feature_fraction': 0.9031063481273173, 'bagging_fraction': 0.933683961138495, 'bagging_freq': 9, 'lambda_l1': 5.6840611969884745e-06, 'lambda_l2': 3.699968960517005e-08, 'min_child_samples': 50, 'max_depth': 8, 'max_bin': 226, 'min_data_in_leaf': 40, 'extra_trees': True, 'early_stopping_rounds': 12, 'path_smooth': 0.7381069457430723, 'min_gain_to_split': 0.3953631617070847}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 05:15:27,995] Trial 169 finished with value: 0.22230275879230427 and parameters: {'num_leaves': 93, 'learning_rate': 0.010528142756913376, 'feature_fraction': 0.8814850331392273, 'bagging_fraction': 0.9390081356535224, 'bagging_freq': 8, 'lambda_l1': 1.0363112936648107e-05, 'lambda_l2': 1.6141353294041805e-07, 'min_child_samples': 47, 'max_depth': 8, 'max_bin': 276, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 15, 'path_smooth': 0.6638048428928965, 'min_gain_to_split': 0.3780012378457761}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 05:18:51,731] Trial 170 finished with value: 0.22404700491902013 and parameters: {'num_leaves': 94, 'learning_rate': 0.010066314312391375, 'feature_fraction': 0.8530587132487649, 'bagging_fraction': 0.9516359388242274, 'bagging_freq': 8, 'lambda_l1': 1.8063726954233864e-06, 'lambda_l2': 1.3698020300701257e-08, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 237, 'min_data_in_leaf': 46, 'extra_trees': True, 'early_stopping_rounds': 11, 'path_smooth': 0.5934506427266525, 'min_gain_to_split': 0.34522190795812746}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 05:23:20,409] Trial 171 finished with value: 0.2601810787732347 and parameters: {'num_leaves': 91, 'learning_rate': 0.01288065360162163, 'feature_fraction': 0.8978200978508017, 'bagging_fraction': 0.9445989623203307, 'bagging_freq': 9, 'lambda_l1': 3.5908181113566696e-06, 'lambda_l2': 6.341181552717491e-08, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 216, 'min_data_in_leaf': 42, 'extra_trees': False, 'early_stopping_rounds': 16, 'path_smooth': 0.6180341565878771, 'min_gain_to_split': 0.3140048884461338}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 05:27:01,504] Trial 172 finished with value: 0.22186474019312805 and parameters: {'num_leaves': 95, 'learning_rate': 0.011129593303727507, 'feature_fraction': 0.9286763885556715, 'bagging_fraction': 0.9146491353480735, 'bagging_freq': 8, 'lambda_l1': 2.2238890155536236e-05, 'lambda_l2': 2.361861920739435e-08, 'min_child_samples': 45, 'max_depth': 8, 'max_bin': 267, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 13, 'path_smooth': 0.5706360367736074, 'min_gain_to_split': 0.36307231223696323}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 05:30:25,086] Trial 173 finished with value: 0.22306219722517437 and parameters: {'num_leaves': 100, 'learning_rate': 0.013637790513725828, 'feature_fraction': 0.8613571210006529, 'bagging_fraction': 0.9535025467842525, 'bagging_freq': 8, 'lambda_l1': 4.135740718679055e-06, 'lambda_l2': 9.230719204877253e-08, 'min_child_samples': 49, 'max_depth': 9, 'max_bin': 259, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 15, 'path_smooth': 0.6474479686544934, 'min_gain_to_split': 0.37396893812603743}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 05:33:34,462] Trial 174 finished with value: 0.2210732116760302 and parameters: {'num_leaves': 97, 'learning_rate': 0.012154966696495358, 'feature_fraction': 0.8850851749517104, 'bagging_fraction': 0.9412522327162499, 'bagging_freq': 8, 'lambda_l1': 6.889149545892373e-06, 'lambda_l2': 1.7207781659128863e-08, 'min_child_samples': 46, 'max_depth': 8, 'max_bin': 245, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.19719131472267842, 'min_gain_to_split': 0.338959205744165}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 05:36:47,882] Trial 175 finished with value: 0.22070422119804514 and parameters: {'num_leaves': 97, 'learning_rate': 0.012112143069725566, 'feature_fraction': 0.8821795640289298, 'bagging_fraction': 0.935006110283804, 'bagging_freq': 8, 'lambda_l1': 6.886785608657618e-06, 'lambda_l2': 1.537115496942452e-08, 'min_child_samples': 46, 'max_depth': 8, 'max_bin': 243, 'min_data_in_leaf': 40, 'extra_trees': True, 'early_stopping_rounds': 50, 'path_smooth': 0.5970246405797733, 'min_gain_to_split': 0.34387687489197094}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 05:40:02,739] Trial 176 finished with value: 0.22066330897081504 and parameters: {'num_leaves': 97, 'learning_rate': 0.01220243407816374, 'feature_fraction': 0.8808467104669424, 'bagging_fraction': 0.9332483525567853, 'bagging_freq': 8, 'lambda_l1': 1.071392239923201e-05, 'lambda_l2': 3.205237156239689e-08, 'min_child_samples': 46, 'max_depth': 8, 'max_bin': 243, 'min_data_in_leaf': 40, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.593017618677163, 'min_gain_to_split': 0.3428458603119009}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 08:13:53,908] Trial 177 finished with value: 0.22186330393413112 and parameters: {'num_leaves': 97, 'learning_rate': 0.01223021860813695, 'feature_fraction': 0.888775375070983, 'bagging_fraction': 0.9334140076162057, 'bagging_freq': 8, 'lambda_l1': 1.4655650691766662e-05, 'lambda_l2': 3.261573837438211e-08, 'min_child_samples': 46, 'max_depth': 8, 'max_bin': 251, 'min_data_in_leaf': 40, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.6176732449799432, 'min_gain_to_split': 0.33635929381023405}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 08:16:52,431] Trial 178 finished with value: 0.22172403425203258 and parameters: {'num_leaves': 98, 'learning_rate': 0.01308841294391056, 'feature_fraction': 0.874110822375796, 'bagging_fraction': 0.9250373058186236, 'bagging_freq': 8, 'lambda_l1': 5.837763423952286e-06, 'lambda_l2': 1.6668927804535433e-08, 'min_child_samples': 45, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 41, 'path_smooth': 0.5909646092273446, 'min_gain_to_split': 0.35047431346350694}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 08:20:57,256] Trial 179 finished with value: 0.23540928103182987 and parameters: {'num_leaves': 96, 'learning_rate': 0.01200434104887508, 'feature_fraction': 0.9116154853991054, 'bagging_fraction': 0.9383353396890941, 'bagging_freq': 8, 'lambda_l1': 8.306233870265906e-06, 'lambda_l2': 1.5536478162434656e-08, 'min_child_samples': 46, 'max_depth': 8, 'max_bin': 232, 'min_data_in_leaf': 78, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.5356725448940981, 'min_gain_to_split': 0.38425122270153633}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 08:23:52,343] Trial 180 finished with value: 0.22245055948851467 and parameters: {'num_leaves': 92, 'learning_rate': 0.014178217696481381, 'feature_fraction': 0.8825300272616196, 'bagging_fraction': 0.9427084400403544, 'bagging_freq': 8, 'lambda_l1': 2.5339248744146644e-06, 'lambda_l2': 6.132406654456095e-08, 'min_child_samples': 47, 'max_depth': 8, 'max_bin': 245, 'min_data_in_leaf': 43, 'extra_trees': True, 'early_stopping_rounds': 45, 'path_smooth': 0.5632377663563964, 'min_gain_to_split': 0.4250900757416762}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 08:27:21,547] Trial 181 finished with value: 0.22312971718783844 and parameters: {'num_leaves': 89, 'learning_rate': 0.011518439660865406, 'feature_fraction': 0.899137146332029, 'bagging_fraction': 0.9321014165609439, 'bagging_freq': 8, 'lambda_l1': 9.840569935722862e-06, 'lambda_l2': 1.022141719458863e-08, 'min_child_samples': 44, 'max_depth': 8, 'max_bin': 253, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 50, 'path_smooth': 0.6947605331812295, 'min_gain_to_split': 0.4033184113406663}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 08:30:50,566] Trial 182 finished with value: 0.22122266498805718 and parameters: {'num_leaves': 95, 'learning_rate': 0.012596347388924057, 'feature_fraction': 0.889140647953996, 'bagging_fraction': 0.9456252744073916, 'bagging_freq': 8, 'lambda_l1': 1.7089983270853276e-06, 'lambda_l2': 2.1815735498020296e-07, 'min_child_samples': 49, 'max_depth': 8, 'max_bin': 286, 'min_data_in_leaf': 40, 'extra_trees': True, 'early_stopping_rounds': 49, 'path_smooth': 0.19222644349553442, 'min_gain_to_split': 0.3268144853101894}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 08:34:03,952] Trial 183 finished with value: 0.22117034200947913 and parameters: {'num_leaves': 94, 'learning_rate': 0.012731545453335638, 'feature_fraction': 0.8914440070907839, 'bagging_fraction': 0.9404422272375492, 'bagging_freq': 8, 'lambda_l1': 1.6669349099133738e-06, 'lambda_l2': 2.2273448744214856e-07, 'min_child_samples': 47, 'max_depth': 8, 'max_bin': 280, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 49, 'path_smooth': 0.22164289113319696, 'min_gain_to_split': 0.3225550284943341}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 08:37:29,590] Trial 184 finished with value: 0.22164080270728506 and parameters: {'num_leaves': 95, 'learning_rate': 0.012550774635113908, 'feature_fraction': 0.8903169662344088, 'bagging_fraction': 0.9455129079263975, 'bagging_freq': 8, 'lambda_l1': 3.3420522295130133e-07, 'lambda_l2': 1.7229817791145923e-07, 'min_child_samples': 49, 'max_depth': 8, 'max_bin': 287, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 49, 'path_smooth': 0.19823306968722593, 'min_gain_to_split': 0.32764011757712524}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 08:40:48,913] Trial 185 finished with value: 0.22173979256454124 and parameters: {'num_leaves': 97, 'learning_rate': 0.010770803739556672, 'feature_fraction': 0.8751635646268426, 'bagging_fraction': 0.9364529417715164, 'bagging_freq': 8, 'lambda_l1': 9.734526922673917, 'lambda_l2': 2.605468417542591e-07, 'min_child_samples': 47, 'max_depth': 8, 'max_bin': 281, 'min_data_in_leaf': 40, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.23494202396750574, 'min_gain_to_split': 0.3410361804441892}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 08:44:23,495] Trial 186 finished with value: 0.22518368408363573 and parameters: {'num_leaves': 99, 'learning_rate': 0.012740533933490592, 'feature_fraction': 0.8827253574269416, 'bagging_fraction': 0.916281918964413, 'bagging_freq': 8, 'lambda_l1': 1.617959575428442e-06, 'lambda_l2': 3.681196984175862e-08, 'min_child_samples': 46, 'max_depth': 8, 'max_bin': 272, 'min_data_in_leaf': 42, 'extra_trees': True, 'early_stopping_rounds': 49, 'path_smooth': 0.2890289961362186, 'min_gain_to_split': 0.3595330183461603}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 08:51:35,038] Trial 187 finished with value: 0.2220814491045248 and parameters: {'num_leaves': 94, 'learning_rate': 0.011848192578524085, 'feature_fraction': 0.8936257022484979, 'bagging_fraction': 0.9425513181253802, 'bagging_freq': 5, 'lambda_l1': 1.0612869045757116e-06, 'lambda_l2': 1.3082300787376235e-07, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 305, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 46, 'path_smooth': 0.2510611849871198, 'min_gain_to_split': 0.3011991705445293}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 08:58:23,552] Trial 188 finished with value: 0.22159564027093456 and parameters: {'num_leaves': 96, 'learning_rate': 0.014471116893991989, 'feature_fraction': 0.8654758115410858, 'bagging_fraction': 0.930498975394089, 'bagging_freq': 8, 'lambda_l1': 3.4356912765748276e-06, 'lambda_l2': 1.9185323110661182e-08, 'min_child_samples': 50, 'max_depth': 8, 'max_bin': 266, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 50, 'path_smooth': 0.6363316957910629, 'min_gain_to_split': 0.32176981064612453}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 09:07:34,761] Trial 189 finished with value: 0.22206396629660255 and parameters: {'num_leaves': 92, 'learning_rate': 0.010985776332671867, 'feature_fraction': 0.88584038610166, 'bagging_fraction': 0.9491554631805468, 'bagging_freq': 8, 'lambda_l1': 6.518063021217066e-06, 'lambda_l2': 2.5138117467861113e-07, 'min_child_samples': 45, 'max_depth': 8, 'max_bin': 290, 'min_data_in_leaf': 41, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.19528403972615704, 'min_gain_to_split': 0.33111010767258076}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 09:11:16,246] Trial 190 finished with value: 0.2226064498747769 and parameters: {'num_leaves': 94, 'learning_rate': 0.013497258492540312, 'feature_fraction': 0.9074484859447416, 'bagging_fraction': 0.9354086893632434, 'bagging_freq': 8, 'lambda_l1': 1.753517931596756e-06, 'lambda_l2': 7.221781807896182e-08, 'min_child_samples': 46, 'max_depth': 8, 'max_bin': 259, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 38, 'path_smooth': 0.6001784090275016, 'min_gain_to_split': 0.34811092425980894}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 09:16:13,864] Trial 191 finished with value: 0.2239790788762948 and parameters: {'num_leaves': 98, 'learning_rate': 0.010070193796399991, 'feature_fraction': 0.8778180413911147, 'bagging_fraction': 0.9199822494525287, 'bagging_freq': 7, 'lambda_l1': 2.76990185869027e-06, 'lambda_l2': 2.4173471926587184e-08, 'min_child_samples': 44, 'max_depth': 8, 'max_bin': 278, 'min_data_in_leaf': 44, 'extra_trees': True, 'early_stopping_rounds': 49, 'path_smooth': 0.2139013337839859, 'min_gain_to_split': 0.3616223416471966}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 09:19:22,081] Trial 192 finished with value: 0.22300772652885983 and parameters: {'num_leaves': 48, 'learning_rate': 0.011790414448987555, 'feature_fraction': 0.8550087994686868, 'bagging_fraction': 0.9494632149079666, 'bagging_freq': 8, 'lambda_l1': 4.279824955597527e-06, 'lambda_l2': 4.5303593284492254e-08, 'min_child_samples': 49, 'max_depth': 8, 'max_bin': 250, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.18169963406427667, 'min_gain_to_split': 0.33705918258286494}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 09:22:26,775] Trial 193 finished with value: 0.22218324013352103 and parameters: {'num_leaves': 91, 'learning_rate': 0.013447579913515337, 'feature_fraction': 0.8955845163967455, 'bagging_fraction': 0.8776137621221102, 'bagging_freq': 8, 'lambda_l1': 1.2798638497384466e-05, 'lambda_l2': 1.4373242181440514e-08, 'min_child_samples': 47, 'max_depth': 8, 'max_bin': 241, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 50, 'path_smooth': 0.21231225309120805, 'min_gain_to_split': 0.3173738124894015}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 09:26:07,859] Trial 194 finished with value: 0.22182505187399357 and parameters: {'num_leaves': 93, 'learning_rate': 0.012369890463309184, 'feature_fraction': 0.9006709159118867, 'bagging_fraction': 0.9385416080863858, 'bagging_freq': 8, 'lambda_l1': 1.9391496339038284e-05, 'lambda_l2': 1.0419452733430901e-07, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 266, 'min_data_in_leaf': 40, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.23697633053563294, 'min_gain_to_split': 0.3712094215924563}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 09:28:59,850] Trial 195 finished with value: 0.22210980027488478 and parameters: {'num_leaves': 95, 'learning_rate': 0.014376507171655182, 'feature_fraction': 0.868188225859588, 'bagging_fraction': 0.9471751610239332, 'bagging_freq': 8, 'lambda_l1': 5.271184184042826e-07, 'lambda_l2': 2.3072186419978393e-08, 'min_child_samples': 46, 'max_depth': 8, 'max_bin': 234, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 14, 'path_smooth': 0.2643447770569853, 'min_gain_to_split': 0.3551980147404992}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 09:33:17,774] Trial 196 finished with value: 0.22329622071112962 and parameters: {'num_leaves': 93, 'learning_rate': 0.012954832277960827, 'feature_fraction': 0.8870853639656424, 'bagging_fraction': 0.9584482724210281, 'bagging_freq': 8, 'lambda_l1': 8.814827629212734e-07, 'lambda_l2': 3.827198329133397e-08, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 252, 'min_data_in_leaf': 41, 'extra_trees': True, 'early_stopping_rounds': 45, 'path_smooth': 0.6540914337504948, 'min_gain_to_split': 0.3440250204167848}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 09:37:09,624] Trial 197 finished with value: 0.22271593396611195 and parameters: {'num_leaves': 100, 'learning_rate': 0.011721928735339076, 'feature_fraction': 0.9161160023652872, 'bagging_fraction': 0.9395643842967262, 'bagging_freq': 8, 'lambda_l1': 6.881610556728552e-06, 'lambda_l2': 2.4560774049155635e-07, 'min_child_samples': 49, 'max_depth': 8, 'max_bin': 228, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 15, 'path_smooth': 0.5768478890389771, 'min_gain_to_split': 0.3310756850476133}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 09:41:37,463] Trial 198 finished with value: 0.22350274418282673 and parameters: {'num_leaves': 97, 'learning_rate': 0.01112828022636872, 'feature_fraction': 0.8759070533389045, 'bagging_fraction': 0.9299658337548276, 'bagging_freq': 8, 'lambda_l1': 2.477041741331703e-06, 'lambda_l2': 4.2349379575469507e-07, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 261, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 49, 'path_smooth': 0.6206525337545241, 'min_gain_to_split': 0.35108937600335827}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 09:45:03,328] Trial 199 finished with value: 0.22252545033578403 and parameters: {'num_leaves': 89, 'learning_rate': 0.013655003852109169, 'feature_fraction': 0.8928280688499889, 'bagging_fraction': 0.9525098710133789, 'bagging_freq': 7, 'lambda_l1': 4.7187134540213166e-06, 'lambda_l2': 1.1417184750604365e-08, 'min_child_samples': 47, 'max_depth': 8, 'max_bin': 243, 'min_data_in_leaf': 43, 'extra_trees': True, 'early_stopping_rounds': 38, 'path_smooth': 0.5451861838297085, 'min_gain_to_split': 0.3240922110249224}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 09:47:13,475] Trial 200 finished with value: 0.224851999047288 and parameters: {'num_leaves': 92, 'learning_rate': 0.012322914919260772, 'feature_fraction': 0.9335915296021805, 'bagging_fraction': 0.959902519510982, 'bagging_freq': 8, 'lambda_l1': 3.8590861774822355e-05, 'lambda_l2': 8.009500312762055e-08, 'min_child_samples': 47, 'max_depth': 5, 'max_bin': 270, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 13, 'path_smooth': 0.17984978636913895, 'min_gain_to_split': 0.30586798101486506}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 09:50:43,946] Trial 201 finished with value: 0.22482084730712715 and parameters: {'num_leaves': 95, 'learning_rate': 0.01066051605209514, 'feature_fraction': 0.9060631408724319, 'bagging_fraction': 0.9441111671475234, 'bagging_freq': 8, 'lambda_l1': 1.3969933280538434e-06, 'lambda_l2': 3.2154105604695016e-08, 'min_child_samples': 44, 'max_depth': 7, 'max_bin': 254, 'min_data_in_leaf': 45, 'extra_trees': True, 'early_stopping_rounds': 14, 'path_smooth': 0.5692353505977925, 'min_gain_to_split': 0.3434468649903352}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 10:00:19,188] Trial 202 finished with value: 0.26571201956387447 and parameters: {'num_leaves': 90, 'learning_rate': 0.014982438050888934, 'feature_fraction': 0.922251511507969, 'bagging_fraction': 0.925673025031285, 'bagging_freq': 9, 'lambda_l1': 3.4072866182645046e-06, 'lambda_l2': 1.3435368071383484e-07, 'min_child_samples': 50, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 16, 'path_smooth': 0.5135993673755829, 'min_gain_to_split': 0.36639706657824844}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 10:04:07,423] Trial 203 finished with value: 0.2241631367562837 and parameters: {'num_leaves': 96, 'learning_rate': 0.011451395197210466, 'feature_fraction': 0.8819575419781781, 'bagging_fraction': 0.9485794988693125, 'bagging_freq': 7, 'lambda_l1': 1.9041933750491962e-06, 'lambda_l2': 1.6781374282916727e-08, 'min_child_samples': 12, 'max_depth': 8, 'max_bin': 246, 'min_data_in_leaf': 42, 'extra_trees': True, 'early_stopping_rounds': 12, 'path_smooth': 0.6085994753154432, 'min_gain_to_split': 0.3127238433989507}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 10:07:44,602] Trial 204 finished with value: 0.2229131324978219 and parameters: {'num_leaves': 98, 'learning_rate': 0.012570461867976038, 'feature_fraction': 0.870293906372704, 'bagging_fraction': 0.9400534278608572, 'bagging_freq': 8, 'lambda_l1': 8.93331826195029e-06, 'lambda_l2': 2.0153293578272974e-07, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 237, 'min_data_in_leaf': 40, 'extra_trees': True, 'early_stopping_rounds': 13, 'path_smooth': 0.5842389852245562, 'min_gain_to_split': 0.33340174430137526}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 10:11:47,189] Trial 205 finished with value: 0.22091535589332129 and parameters: {'num_leaves': 94, 'learning_rate': 0.013265763680567406, 'feature_fraction': 0.8871400678674696, 'bagging_fraction': 0.9552534224462774, 'bagging_freq': 8, 'lambda_l1': 6.078385995227359e-08, 'lambda_l2': 5.2864473461154394e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 259, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 35, 'path_smooth': 0.5959313172326167, 'min_gain_to_split': 0.32183756448352246}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 10:15:41,408] Trial 206 finished with value: 0.22356596117505037 and parameters: {'num_leaves': 94, 'learning_rate': 0.013306226918570198, 'feature_fraction': 0.886006048368595, 'bagging_fraction': 0.9610023425802062, 'bagging_freq': 8, 'lambda_l1': 6.1058877805148965e-06, 'lambda_l2': 5.1313376384809495e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 257, 'min_data_in_leaf': 33, 'extra_trees': True, 'early_stopping_rounds': 36, 'path_smooth': 0.9210469490623553, 'min_gain_to_split': 0.3241930106946879}. Best is trial 67 with value: 0.2202200412080683.

Mejor trial hasta ahora: TFE=0.220220, Parámetros={'num_leaves': 82, 'learning_rate': 0.020230497513888536, 'feature_fraction': 0.9655912818100384, 'bagging_fraction': 0.9360519451006626, 'bagging_freq': 5, 'lambda_l1': 7.2345842547741475e-06, 'lambda_l2': 3.644357089214262e-05, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 264, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.22932102950614247, 'min_gain_to_split': 0.0690262722574783}

[I 2025-07-16 10:19:10,903] Trial 207 finished with value: 0.2196942896096191 and parameters: {'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 10:22:31,185] Trial 208 finished with value: 0.22229464909938113 and parameters: {'num_leaves': 91, 'learning_rate': 0.014313826295722415, 'feature_fraction': 0.9018262221326666, 'bagging_fraction': 0.9525098284554253, 'bagging_freq': 8, 'lambda_l1': 7.135410214856872e-07, 'lambda_l2': 5.305459067148189e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 299, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 46, 'path_smooth': 0.6624928144996309, 'min_gain_to_split': 0.2902878863987623}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 10:26:24,358] Trial 209 finished with value: 0.2199201940340354 and parameters: {'num_leaves': 88, 'learning_rate': 0.012190026103739248, 'feature_fraction': 0.8625451252258617, 'bagging_fraction': 0.9576697321446064, 'bagging_freq': 8, 'lambda_l1': 4.304992529565611e-06, 'lambda_l2': 2.6336440292734365e-08, 'min_child_samples': 30, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 49, 'path_smooth': 0.636997835061957, 'min_gain_to_split': 0.3593745603786819}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 10:30:27,621] Trial 210 finished with value: 0.22180171787509823 and parameters: {'num_leaves': 87, 'learning_rate': 0.01147859735112923, 'feature_fraction': 0.8920472203236405, 'bagging_fraction': 0.956640319009665, 'bagging_freq': 8, 'lambda_l1': 1.4022837080185121e-05, 'lambda_l2': 2.7205711033037937e-08, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 286, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.6294792338956468, 'min_gain_to_split': 0.38433056722131703}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 10:34:02,346] Trial 211 finished with value: 0.22175996013257465 and parameters: {'num_leaves': 88, 'learning_rate': 0.012754746283035039, 'feature_fraction': 0.8771542576516885, 'bagging_fraction': 0.9484639263231783, 'bagging_freq': 8, 'lambda_l1': 1.563690332509908e-07, 'lambda_l2': 1.7276257307822614e-08, 'min_child_samples': 29, 'max_depth': 8, 'max_bin': 287, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 49, 'path_smooth': 0.6008352519565808, 'min_gain_to_split': 0.35486132625187644}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 10:38:06,225] Trial 212 finished with value: 0.2215946353804752 and parameters: {'num_leaves': 91, 'learning_rate': 0.010588709596470753, 'feature_fraction': 0.8612057659258887, 'bagging_fraction': 0.942835804503797, 'bagging_freq': 8, 'lambda_l1': 3.473106748394121e-08, 'lambda_l2': 8.690529726887793e-08, 'min_child_samples': 30, 'max_depth': 8, 'max_bin': 277, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6800351821499334, 'min_gain_to_split': 0.37284267679670496}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 10:41:51,912] Trial 213 finished with value: 0.2239689532086276 and parameters: {'num_leaves': 94, 'learning_rate': 0.01215718428491891, 'feature_fraction': 0.8702500270316764, 'bagging_fraction': 0.9639022982044139, 'bagging_freq': 8, 'lambda_l1': 5.717029634720759e-08, 'lambda_l2': 3.193603251147506e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 271, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 49, 'path_smooth': 0.6434279120468853, 'min_gain_to_split': 0.34037315922432776}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 10:45:52,430] Trial 214 finished with value: 0.22501115937815622 and parameters: {'num_leaves': 92, 'learning_rate': 0.011275548650500454, 'feature_fraction': 0.8809843381422873, 'bagging_fraction': 0.9538471214648678, 'bagging_freq': 8, 'lambda_l1': 1.3720044761657135e-08, 'lambda_l2': 2.153195546814159e-08, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 296, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 50, 'path_smooth': 0.6209155689978693, 'min_gain_to_split': 0.35293898725444134}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 10:49:03,412] Trial 215 finished with value: 0.2209421325760088 and parameters: {'num_leaves': 96, 'learning_rate': 0.013441959184566758, 'feature_fraction': 0.8952715128704505, 'bagging_fraction': 0.9352822685908421, 'bagging_freq': 8, 'lambda_l1': 2.7303448134843834e-08, 'lambda_l2': 1.228742916650181e-08, 'min_child_samples': 34, 'max_depth': 8, 'max_bin': 279, 'min_data_in_leaf': 33, 'extra_trees': True, 'early_stopping_rounds': 14, 'path_smooth': 0.5979595380007818, 'min_gain_to_split': 0.35844504969467506}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 10:52:24,580] Trial 216 finished with value: 0.2209337925848054 and parameters: {'num_leaves': 98, 'learning_rate': 0.013577079683237634, 'feature_fraction': 0.8943736247086106, 'bagging_fraction': 0.9344156109299262, 'bagging_freq': 8, 'lambda_l1': 1.389242232582549e-08, 'lambda_l2': 1.1790550401939562e-08, 'min_child_samples': 45, 'max_depth': 8, 'max_bin': 282, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 14, 'path_smooth': 0.5943491004006194, 'min_gain_to_split': 0.36222457672374697}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 10:55:25,239] Trial 217 finished with value: 0.22145300554528308 and parameters: {'num_leaves': 97, 'learning_rate': 0.015282796610652504, 'feature_fraction': 0.8985759004026255, 'bagging_fraction': 0.9329959304500641, 'bagging_freq': 8, 'lambda_l1': 2.5671516472811387e-08, 'lambda_l2': 1.1827995477685655e-08, 'min_child_samples': 30, 'max_depth': 8, 'max_bin': 282, 'min_data_in_leaf': 33, 'extra_trees': True, 'early_stopping_rounds': 15, 'path_smooth': 0.5564124965285817, 'min_gain_to_split': 0.36384582341238547}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 10:58:43,073] Trial 218 finished with value: 0.22141380742224195 and parameters: {'num_leaves': 99, 'learning_rate': 0.014241901904749018, 'feature_fraction': 0.8901781107598011, 'bagging_fraction': 0.9342650283775749, 'bagging_freq': 8, 'lambda_l1': 1.5850488232067377e-08, 'lambda_l2': 1.3769264378876116e-08, 'min_child_samples': 29, 'max_depth': 8, 'max_bin': 291, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 46, 'path_smooth': 0.6067054697442199, 'min_gain_to_split': 0.36519494717858775}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 11:02:02,221] Trial 219 finished with value: 0.22271564104849634 and parameters: {'num_leaves': 97, 'learning_rate': 0.013647987190296848, 'feature_fraction': 0.9117070420390055, 'bagging_fraction': 0.9400039414469761, 'bagging_freq': 5, 'lambda_l1': 1.8480177529230067e-08, 'lambda_l2': 1.0683774923801296e-08, 'min_child_samples': 35, 'max_depth': 8, 'max_bin': 275, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 14, 'path_smooth': 0.6393225758500419, 'min_gain_to_split': 0.39526772635060514}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 11:05:13,225] Trial 220 finished with value: 0.22349182422656466 and parameters: {'num_leaves': 100, 'learning_rate': 0.013092423674232223, 'feature_fraction': 0.8872292071351717, 'bagging_fraction': 0.9306122760325339, 'bagging_freq': 8, 'lambda_l1': 1.824278834426917e-07, 'lambda_l2': 2.121094428766954e-08, 'min_child_samples': 34, 'max_depth': 8, 'max_bin': 264, 'min_data_in_leaf': 32, 'extra_trees': True, 'early_stopping_rounds': 13, 'path_smooth': 0.5938245260408718, 'min_gain_to_split': 0.34574454289910017}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 11:08:11,120] Trial 221 finished with value: 0.22365730750042276 and parameters: {'num_leaves': 96, 'learning_rate': 0.016094750611509463, 'feature_fraction': 0.8980306002881502, 'bagging_fraction': 0.9239079804087299, 'bagging_freq': 8, 'lambda_l1': 1.0816241881790534e-07, 'lambda_l2': 1.7166269217533244e-08, 'min_child_samples': 33, 'max_depth': 8, 'max_bin': 309, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.5657874693722226, 'min_gain_to_split': 0.4548840568475892}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 11:11:24,298] Trial 222 finished with value: 0.22257380737690582 and parameters: {'num_leaves': 89, 'learning_rate': 0.014903304352785387, 'feature_fraction': 0.8805618579995729, 'bagging_fraction': 0.9440195183891692, 'bagging_freq': 8, 'lambda_l1': 2.653892790687222e-08, 'lambda_l2': 2.4972783515682643e-08, 'min_child_samples': 33, 'max_depth': 8, 'max_bin': 279, 'min_data_in_leaf': 33, 'extra_trees': True, 'early_stopping_rounds': 43, 'path_smooth': 0.6219279344866342, 'min_gain_to_split': 0.3787166393980709}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 11:15:04,348] Trial 223 finished with value: 0.22186732523203506 and parameters: {'num_leaves': 93, 'learning_rate': 0.012190692495736928, 'feature_fraction': 0.9068148734069185, 'bagging_fraction': 0.9478814057636353, 'bagging_freq': 8, 'lambda_l1': 1.1882347075658836e-08, 'lambda_l2': 4.2609991819116134e-08, 'min_child_samples': 30, 'max_depth': 8, 'max_bin': 266, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 13, 'path_smooth': 0.5847408631676495, 'min_gain_to_split': 0.35925581030964326}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 11:18:12,929] Trial 224 finished with value: 0.2217152483853888 and parameters: {'num_leaves': 95, 'learning_rate': 0.012976764166200186, 'feature_fraction': 0.8927608998509865, 'bagging_fraction': 0.9393741373267257, 'bagging_freq': 8, 'lambda_l1': 3.351232657492833e-06, 'lambda_l2': 6.49449437406626e-08, 'min_child_samples': 47, 'max_depth': 8, 'max_bin': 248, 'min_data_in_leaf': 41, 'extra_trees': True, 'early_stopping_rounds': 14, 'path_smooth': 0.5917751327307545, 'min_gain_to_split': 0.3391660764995314}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 11:22:00,087] Trial 225 finished with value: 0.22119316140202966 and parameters: {'num_leaves': 98, 'learning_rate': 0.011826324637750917, 'feature_fraction': 0.875798896785675, 'bagging_fraction': 0.9563317709464441, 'bagging_freq': 8, 'lambda_l1': 5.031962876825178e-06, 'lambda_l2': 3.2561213593160445e-08, 'min_child_samples': 45, 'max_depth': 8, 'max_bin': 295, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 12, 'path_smooth': 0.5472589042499014, 'min_gain_to_split': 0.3508386651570833}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 11:25:39,082] Trial 226 finished with value: 0.22516093570929302 and parameters: {'num_leaves': 72, 'learning_rate': 0.011154397051564732, 'feature_fraction': 0.873773049086594, 'bagging_fraction': 0.9571189825902144, 'bagging_freq': 8, 'lambda_l1': 4.214921712294661e-06, 'lambda_l2': 1.020112785637257e-08, 'min_child_samples': 45, 'max_depth': 8, 'max_bin': 300, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 13, 'path_smooth': 0.5360342407034648, 'min_gain_to_split': 0.35144371459584}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 11:29:10,420] Trial 227 finished with value: 0.22168790411530495 and parameters: {'num_leaves': 98, 'learning_rate': 0.012674124083111912, 'feature_fraction': 0.8840215434967966, 'bagging_fraction': 0.9524152111355386, 'bagging_freq': 8, 'lambda_l1': 1.0997386478479506e-07, 'lambda_l2': 3.28313091776679e-08, 'min_child_samples': 46, 'max_depth': 8, 'max_bin': 292, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 15, 'path_smooth': 0.5550017396209882, 'min_gain_to_split': 0.3671973432944041}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 11:32:37,153] Trial 228 finished with value: 0.22845144361115946 and parameters: {'num_leaves': 100, 'learning_rate': 0.01400488033936969, 'feature_fraction': 0.8674938879489692, 'bagging_fraction': 0.9596731765368743, 'bagging_freq': 8, 'lambda_l1': 2.7215470114867442e-08, 'lambda_l2': 1.669421815581352e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 284, 'min_data_in_leaf': 67, 'extra_trees': True, 'early_stopping_rounds': 50, 'path_smooth': 0.5663014079647108, 'min_gain_to_split': 0.35760089251504473}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 11:36:26,551] Trial 229 finished with value: 0.22236971797777078 and parameters: {'num_leaves': 96, 'learning_rate': 0.011933084236424831, 'feature_fraction': 0.8769307027730728, 'bagging_fraction': 0.936339260387555, 'bagging_freq': 8, 'lambda_l1': 2.3102339302205127e-06, 'lambda_l2': 1.3122794327929275e-07, 'min_child_samples': 46, 'max_depth': 8, 'max_bin': 276, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.6065682238643161, 'min_gain_to_split': 0.4847797118995809}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 11:40:36,670] Trial 230 finished with value: 0.22226697103489568 and parameters: {'num_leaves': 98, 'learning_rate': 0.010721236903292403, 'feature_fraction': 0.892896980179716, 'bagging_fraction': 0.9642540686675805, 'bagging_freq': 8, 'lambda_l1': 5.125607673828852e-08, 'lambda_l2': 2.6443998061738168e-08, 'min_child_samples': 45, 'max_depth': 8, 'max_bin': 270, 'min_data_in_leaf': 40, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.6546192721707027, 'min_gain_to_split': 0.34557831943158446}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 11:44:10,382] Trial 231 finished with value: 0.22233235617183436 and parameters: {'num_leaves': 91, 'learning_rate': 0.013108957541163762, 'feature_fraction': 0.886471444494396, 'bagging_fraction': 0.9455249766885327, 'bagging_freq': 8, 'lambda_l1': 1.4600001943231838e-06, 'lambda_l2': 1.680609411535921e-08, 'min_child_samples': 49, 'max_depth': 8, 'max_bin': 317, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 11, 'path_smooth': 0.525661665386532, 'min_gain_to_split': 0.3743677488504799}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 11:47:11,717] Trial 232 finished with value: 0.22273588246081108 and parameters: {'num_leaves': 96, 'learning_rate': 0.011586674606637261, 'feature_fraction': 0.9007782777469329, 'bagging_fraction': 0.8931368500864556, 'bagging_freq': 8, 'lambda_l1': 4.649449731726975e-06, 'lambda_l2': 3.37718334893083e-08, 'min_child_samples': 47, 'max_depth': 7, 'max_bin': 294, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 14, 'path_smooth': 0.6239657212019382, 'min_gain_to_split': 0.34140400562499346}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 11:49:52,746] Trial 233 finished with value: 0.2237224083844042 and parameters: {'num_leaves': 94, 'learning_rate': 0.012141839013397807, 'feature_fraction': 0.6448160244448882, 'bagging_fraction': 0.9507202873605218, 'bagging_freq': 8, 'lambda_l1': 9.610251299412848e-06, 'lambda_l2': 5.4551925585184845e-08, 'min_child_samples': 46, 'max_depth': 8, 'max_bin': 260, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 12, 'path_smooth': 0.575528462301298, 'min_gain_to_split': 0.331357418116563}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 11:53:15,508] Trial 234 finished with value: 0.22475997311409848 and parameters: {'num_leaves': 93, 'learning_rate': 0.01138291935810692, 'feature_fraction': 0.8790827509848373, 'bagging_fraction': 0.9447467852860456, 'bagging_freq': 8, 'lambda_l1': 5.265493820968664e-06, 'lambda_l2': 9.398003596940136e-08, 'min_child_samples': 40, 'max_depth': 8, 'max_bin': 249, 'min_data_in_leaf': 41, 'extra_trees': True, 'early_stopping_rounds': 15, 'path_smooth': 0.5820314828558952, 'min_gain_to_split': 0.3188899227476009}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 11:55:33,161] Trial 235 finished with value: 0.22644684465810308 and parameters: {'num_leaves': 28, 'learning_rate': 0.013300336107193483, 'feature_fraction': 0.9416685065419992, 'bagging_fraction': 0.9555693550032089, 'bagging_freq': 8, 'lambda_l1': 8.038214528837147e-06, 'lambda_l2': 1.011375175512226e-08, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 259, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 12, 'path_smooth': 0.5996865320430163, 'min_gain_to_split': 0.3519086337560328}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 11:59:05,386] Trial 236 finished with value: 0.2216581776176061 and parameters: {'num_leaves': 95, 'learning_rate': 0.012284470647090892, 'feature_fraction': 0.8626746703621505, 'bagging_fraction': 0.9369078431721177, 'bagging_freq': 8, 'lambda_l1': 2.6811368874118136e-06, 'lambda_l2': 2.2625227822348914e-08, 'min_child_samples': 45, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 13, 'path_smooth': 0.54323899571282, 'min_gain_to_split': 0.33152194535293245}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 12:02:48,088] Trial 237 finished with value: 0.22227343817079262 and parameters: {'num_leaves': 98, 'learning_rate': 0.010489414593988873, 'feature_fraction': 0.8945612803191092, 'bagging_fraction': 0.9488698997840795, 'bagging_freq': 8, 'lambda_l1': 1.089503930691029e-06, 'lambda_l2': 2.0475145909429698e-07, 'min_child_samples': 43, 'max_depth': 8, 'max_bin': 239, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 10, 'path_smooth': 0.634202259289411, 'min_gain_to_split': 0.3574610261161485}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 12:05:24,557] Trial 238 finished with value: 0.2253848524373085 and parameters: {'num_leaves': 92, 'learning_rate': 0.011913963066418242, 'feature_fraction': 0.9183264948860244, 'bagging_fraction': 0.9281528019944341, 'bagging_freq': 8, 'lambda_l1': 7.793393767137996e-08, 'lambda_l2': 4.2039032447792346e-08, 'min_child_samples': 47, 'max_depth': 8, 'max_bin': 115, 'min_data_in_leaf': 32, 'extra_trees': True, 'early_stopping_rounds': 49, 'path_smooth': 0.6097582009075793, 'min_gain_to_split': 0.2148041158574161}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 12:08:22,507] Trial 239 finished with value: 0.2246212569238643 and parameters: {'num_leaves': 90, 'learning_rate': 0.013870462881050594, 'feature_fraction': 0.8850553287159034, 'bagging_fraction': 0.9421048510813366, 'bagging_freq': 8, 'lambda_l1': 6.471469579432165e-06, 'lambda_l2': 1.5294479654614268e-08, 'min_child_samples': 37, 'max_depth': 8, 'max_bin': 266, 'min_data_in_leaf': 42, 'extra_trees': True, 'early_stopping_rounds': 14, 'path_smooth': 0.4196423339954524, 'min_gain_to_split': 0.33732407412042337}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 12:11:31,636] Trial 240 finished with value: 0.2229050318710685 and parameters: {'num_leaves': 94, 'learning_rate': 0.012641657540150212, 'feature_fraction': 0.8751364271508427, 'bagging_fraction': 0.9536561008261801, 'bagging_freq': 7, 'lambda_l1': 3.4526579126187074e-06, 'lambda_l2': 6.283188249713117e-08, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 251, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 11, 'path_smooth': 0.2263737963040892, 'min_gain_to_split': 0.14061779166002697}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 12:14:41,258] Trial 241 finished with value: 0.22516296176674241 and parameters: {'num_leaves': 97, 'learning_rate': 0.011154038630227162, 'feature_fraction': 0.6904570761078205, 'bagging_fraction': 0.9349467319553554, 'bagging_freq': 8, 'lambda_l1': 1.0489166768755544e-08, 'lambda_l2': 3.234732233383776e-07, 'min_child_samples': 49, 'max_depth': 8, 'max_bin': 226, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 13, 'path_smooth': 0.81172368472306, 'min_gain_to_split': 0.3879563559338892}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 12:20:13,975] Trial 242 finished with value: 0.2706267873107375 and parameters: {'num_leaves': 99, 'learning_rate': 0.014850621728802565, 'feature_fraction': 0.9042948648955799, 'bagging_fraction': 0.9424550296267071, 'bagging_freq': 8, 'lambda_l1': 2.3512018599032256e-06, 'lambda_l2': 1.4064487649296833e-07, 'min_child_samples': 44, 'max_depth': 8, 'max_bin': 303, 'min_data_in_leaf': 39, 'extra_trees': False, 'early_stopping_rounds': 14, 'path_smooth': 0.5793768367829281, 'min_gain_to_split': 0.36686430308929674}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 12:23:20,538] Trial 243 finished with value: 0.22201777789093616 and parameters: {'num_leaves': 93, 'learning_rate': 0.012227978537286018, 'feature_fraction': 0.8881438744496382, 'bagging_fraction': 0.9620071017549605, 'bagging_freq': 3, 'lambda_l1': 4.32517217630299, 'lambda_l2': 1.812301219641567e-08, 'min_child_samples': 15, 'max_depth': 8, 'max_bin': 257, 'min_data_in_leaf': 40, 'extra_trees': True, 'early_stopping_rounds': 12, 'path_smooth': 0.592217776556859, 'min_gain_to_split': 0.35004735842251267}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 12:26:19,066] Trial 244 finished with value: 0.22227038026010865 and parameters: {'num_leaves': 95, 'learning_rate': 0.013302103492865784, 'feature_fraction': 0.8551861427419633, 'bagging_fraction': 0.945637385252825, 'bagging_freq': 8, 'lambda_l1': 1.134061684335724e-05, 'lambda_l2': 2.469380527029412e-08, 'min_child_samples': 46, 'max_depth': 8, 'max_bin': 244, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 14, 'path_smooth': 0.2061505193695947, 'min_gain_to_split': 0.32669314419921036}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 12:30:01,334] Trial 245 finished with value: 0.22293409220161484 and parameters: {'num_leaves': 92, 'learning_rate': 0.011694474322516352, 'feature_fraction': 0.8694433829692934, 'bagging_fraction': 0.9509671830750653, 'bagging_freq': 8, 'lambda_l1': 1.8702436182613005e-06, 'lambda_l2': 4.350411989421461e-08, 'min_child_samples': 30, 'max_depth': 8, 'max_bin': 274, 'min_data_in_leaf': 41, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.5601454557415652, 'min_gain_to_split': 0.3397572757855871}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 12:33:20,426] Trial 246 finished with value: 0.2223981454144695 and parameters: {'num_leaves': 96, 'learning_rate': 0.01262377078625893, 'feature_fraction': 0.8811628841397036, 'bagging_fraction': 0.9576032288929268, 'bagging_freq': 8, 'lambda_l1': 4.982398193375903e-06, 'lambda_l2': 1.3562584730837732e-08, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 253, 'min_data_in_leaf': 32, 'extra_trees': True, 'early_stopping_rounds': 35, 'path_smooth': 0.6235111709476564, 'min_gain_to_split': 0.3591763980644538}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 12:37:36,733] Trial 247 finished with value: 0.21979460222616526 and parameters: {'num_leaves': 94, 'learning_rate': 0.010025578944993842, 'feature_fraction': 0.895482042176894, 'bagging_fraction': 0.9377527439908162, 'bagging_freq': 8, 'lambda_l1': 3.7967573956977924e-07, 'lambda_l2': 7.76982854254365e-08, 'min_child_samples': 29, 'max_depth': 8, 'max_bin': 262, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 50, 'path_smooth': 0.3375893166044388, 'min_gain_to_split': 0.3448370501968947}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 12:41:51,308] Trial 248 finished with value: 0.21997357872579903 and parameters: {'num_leaves': 90, 'learning_rate': 0.010347070403041116, 'feature_fraction': 0.8987319378344499, 'bagging_fraction': 0.9308408994278906, 'bagging_freq': 8, 'lambda_l1': 2.9202678323437966e-07, 'lambda_l2': 8.664128187353284e-08, 'min_child_samples': 47, 'max_depth': 8, 'max_bin': 265, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 49, 'path_smooth': 0.3937384955291653, 'min_gain_to_split': 0.34645388548311795}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 12:46:09,972] Trial 249 finished with value: 0.2219107159440596 and parameters: {'num_leaves': 89, 'learning_rate': 0.010088002871734773, 'feature_fraction': 0.9002217208859378, 'bagging_fraction': 0.928955669754216, 'bagging_freq': 8, 'lambda_l1': 5.594566368161584e-07, 'lambda_l2': 9.896944844133127e-08, 'min_child_samples': 28, 'max_depth': 8, 'max_bin': 266, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 50, 'path_smooth': 0.3967472602211422, 'min_gain_to_split': 0.3487174320772849}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 12:51:26,616] Trial 250 finished with value: 0.22210844148690784 and parameters: {'num_leaves': 91, 'learning_rate': 0.010147223485707301, 'feature_fraction': 0.9083132198129215, 'bagging_fraction': 0.9224052655664855, 'bagging_freq': 8, 'lambda_l1': 2.526059623793505e-07, 'lambda_l2': 1.76922424902847e-07, 'min_child_samples': 47, 'max_depth': 10, 'max_bin': 282, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 49, 'path_smooth': 0.3453185460370587, 'min_gain_to_split': 0.3712351758121955}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 12:55:23,021] Trial 251 finished with value: 0.22296273535214067 and parameters: {'num_leaves': 89, 'learning_rate': 0.010875617097203968, 'feature_fraction': 0.891743283571887, 'bagging_fraction': 0.9332644726196432, 'bagging_freq': 8, 'lambda_l1': 4.0680942942622224e-07, 'lambda_l2': 6.710475727527872e-08, 'min_child_samples': 47, 'max_depth': 8, 'max_bin': 275, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 50, 'path_smooth': 0.3303753759063485, 'min_gain_to_split': 0.36197139302970044}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 12:59:12,628] Trial 252 finished with value: 0.2243294426986146 and parameters: {'num_leaves': 91, 'learning_rate': 0.010044547154411559, 'feature_fraction': 0.8940463360318424, 'bagging_fraction': 0.9400550281112445, 'bagging_freq': 8, 'lambda_l1': 1.8680926813233562e-07, 'lambda_l2': 1.3342141815877034e-07, 'min_child_samples': 29, 'max_depth': 8, 'max_bin': 235, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.35467044278330356, 'min_gain_to_split': 0.34218534861855576}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 13:03:08,546] Trial 253 finished with value: 0.2225421648307621 and parameters: {'num_leaves': 87, 'learning_rate': 0.010763203183670366, 'feature_fraction': 0.8857415598123548, 'bagging_fraction': 0.9377806561915919, 'bagging_freq': 8, 'lambda_l1': 2.740647150738409e-07, 'lambda_l2': 3.1707155334519834e-08, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 263, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 49, 'path_smooth': 0.3114661357913484, 'min_gain_to_split': 0.35360619707796076}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 13:04:06,322] Trial 254 finished with value: 0.2293758592537057 and parameters: {'num_leaves': 100, 'learning_rate': 0.06801686448443012, 'feature_fraction': 0.8979574969339456, 'bagging_fraction': 0.9293061986153112, 'bagging_freq': 8, 'lambda_l1': 8.729490718800974e-08, 'lambda_l2': 8.509112252344727e-08, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 292, 'min_data_in_leaf': 40, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.2857059109548123, 'min_gain_to_split': 0.3784258492270774}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 13:07:43,409] Trial 255 finished with value: 0.2203221248910005 and parameters: {'num_leaves': 93, 'learning_rate': 0.011170046643448018, 'feature_fraction': 0.8765900821245837, 'bagging_fraction': 0.9361191881698866, 'bagging_freq': 8, 'lambda_l1': 9.030389388153589e-07, 'lambda_l2': 1.0282029884728946e-08, 'min_child_samples': 46, 'max_depth': 8, 'max_bin': 241, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 50, 'path_smooth': 0.2544093038165144, 'min_gain_to_split': 0.31422954067902215}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 13:11:22,087] Trial 256 finished with value: 0.2224882684836816 and parameters: {'num_leaves': 93, 'learning_rate': 0.011030188580326063, 'feature_fraction': 0.870781917197432, 'bagging_fraction': 0.9343071863924821, 'bagging_freq': 7, 'lambda_l1': 7.488706872146035e-07, 'lambda_l2': 1.0310273365016393e-08, 'min_child_samples': 46, 'max_depth': 8, 'max_bin': 246, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 49, 'path_smooth': 0.25764013708108907, 'min_gain_to_split': 0.34737085609056695}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 13:12:28,834] Trial 257 finished with value: 0.225926963964845 and parameters: {'num_leaves': 90, 'learning_rate': 0.048166409878516774, 'feature_fraction': 0.8805577126698519, 'bagging_fraction': 0.9404589291979681, 'bagging_freq': 8, 'lambda_l1': 1.1970985589198858e-06, 'lambda_l2': 1.6694403108611554e-08, 'min_child_samples': 45, 'max_depth': 8, 'max_bin': 241, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 50, 'path_smooth': 0.27605840331653747, 'min_gain_to_split': 0.3094551153278588}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 13:16:18,550] Trial 258 finished with value: 0.2213241508735794 and parameters: {'num_leaves': 97, 'learning_rate': 0.010713174451850932, 'feature_fraction': 0.8753850194032284, 'bagging_fraction': 0.9274203156397491, 'bagging_freq': 5, 'lambda_l1': 3.972042235856621e-07, 'lambda_l2': 2.168457082950046e-08, 'min_child_samples': 46, 'max_depth': 8, 'max_bin': 234, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 50, 'path_smooth': 0.24524653858614062, 'min_gain_to_split': 0.3192640857726668}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 13:19:18,602] Trial 259 finished with value: 0.22354686184688477 and parameters: {'num_leaves': 92, 'learning_rate': 0.011274378208199955, 'feature_fraction': 0.8639179015409084, 'bagging_fraction': 0.9673944278343958, 'bagging_freq': 8, 'lambda_l1': 2.347913546705566e-07, 'lambda_l2': 1.4426119429144648e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 249, 'min_data_in_leaf': 43, 'extra_trees': True, 'early_stopping_rounds': 39, 'path_smooth': 0.49359665543579284, 'min_gain_to_split': 0.36116889096978844}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 13:22:56,099] Trial 260 finished with value: 0.22204278548803572 and parameters: {'num_leaves': 94, 'learning_rate': 0.011370790475435724, 'feature_fraction': 0.909751400612956, 'bagging_fraction': 0.9325690264430246, 'bagging_freq': 8, 'lambda_l1': 1.0544716810710624e-06, 'lambda_l2': 3.3382638959639915e-08, 'min_child_samples': 46, 'max_depth': 8, 'max_bin': 258, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 14, 'path_smooth': 0.30104423625594035, 'min_gain_to_split': 0.337869317205081}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 13:26:04,358] Trial 261 finished with value: 0.22212950977921503 and parameters: {'num_leaves': 98, 'learning_rate': 0.013690039544633423, 'feature_fraction': 0.8823585980334094, 'bagging_fraction': 0.9173999295179134, 'bagging_freq': 8, 'lambda_l1': 3.485966079977904e-06, 'lambda_l2': 1.0109160757119931e-08, 'min_child_samples': 47, 'max_depth': 8, 'max_bin': 269, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.23247226372834862, 'min_gain_to_split': 0.36913005129222526}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 13:29:52,973] Trial 262 finished with value: 0.22270462396639368 and parameters: {'num_leaves': 88, 'learning_rate': 0.010001525436327789, 'feature_fraction': 0.9005785906159782, 'bagging_fraction': 0.9491425427568259, 'bagging_freq': 8, 'lambda_l1': 5.80796263376908e-07, 'lambda_l2': 2.470770693366067e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 223, 'min_data_in_leaf': 32, 'extra_trees': True, 'early_stopping_rounds': 15, 'path_smooth': 0.6445786863325739, 'min_gain_to_split': 0.3488045668128773}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 13:33:18,685] Trial 263 finished with value: 0.2208007692098616 and parameters: {'num_leaves': 96, 'learning_rate': 0.011581630192706747, 'feature_fraction': 0.8926838575552127, 'bagging_fraction': 0.9397045255256679, 'bagging_freq': 8, 'lambda_l1': 2.1101254171734947e-08, 'lambda_l2': 4.318717792992386e-08, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 252, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 13, 'path_smooth': 0.3738255059109634, 'min_gain_to_split': 0.1125096293606674}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 13:38:00,294] Trial 264 finished with value: 0.22199319082883648 and parameters: {'num_leaves': 91, 'learning_rate': 0.01082665357421529, 'feature_fraction': 0.914232700968189, 'bagging_fraction': 0.937111042953677, 'bagging_freq': 8, 'lambda_l1': 1.7341148921213992e-08, 'lambda_l2': 5.2433876159049976e-08, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 252, 'min_data_in_leaf': 30, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.3761230657023822, 'min_gain_to_split': 0.13441042966219652}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 13:43:45,584] Trial 265 finished with value: 0.26842068120016827 and parameters: {'num_leaves': 93, 'learning_rate': 0.01145401728983953, 'feature_fraction': 0.8924318741754392, 'bagging_fraction': 0.9082373283383333, 'bagging_freq': 2, 'lambda_l1': 3.073462116110781e-08, 'lambda_l2': 1.0063219417044756e-08, 'min_child_samples': 47, 'max_depth': 8, 'max_bin': 238, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 14, 'path_smooth': 0.3219204478888512, 'min_gain_to_split': 0.3337515907346183}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 13:45:36,963] Trial 266 finished with value: 0.22514741932660404 and parameters: {'num_leaves': 54, 'learning_rate': 0.014289139976174486, 'feature_fraction': 0.9016824399958858, 'bagging_fraction': 0.9240960407302292, 'bagging_freq': 8, 'lambda_l1': 2.1014602125303336e-08, 'lambda_l2': 1.7525089305355786e-08, 'min_child_samples': 30, 'max_depth': 6, 'max_bin': 245, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 13, 'path_smooth': 0.3935263052349705, 'min_gain_to_split': 0.15362248965109174}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 13:48:59,362] Trial 267 finished with value: 0.23727930336780262 and parameters: {'num_leaves': 95, 'learning_rate': 0.012558877138893318, 'feature_fraction': 0.7348303822596776, 'bagging_fraction': 0.9428743149376102, 'bagging_freq': 8, 'lambda_l1': 4.674623711851487e-08, 'lambda_l2': 8.624376901971113e-08, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 262, 'min_data_in_leaf': 94, 'extra_trees': True, 'early_stopping_rounds': 50, 'path_smooth': 0.3706285081946818, 'min_gain_to_split': 0.12218387676593571}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 13:52:47,469] Trial 268 finished with value: 0.22194864606318276 and parameters: {'num_leaves': 96, 'learning_rate': 0.010600946773951968, 'feature_fraction': 0.8891221401933941, 'bagging_fraction': 0.9367484283113208, 'bagging_freq': 8, 'lambda_l1': 2.329180750414055e-06, 'lambda_l2': 2.2853205635747496e-08, 'min_child_samples': 29, 'max_depth': 8, 'max_bin': 255, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 15, 'path_smooth': 0.35617071403524886, 'min_gain_to_split': 0.17155792399321204}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 13:56:38,399] Trial 269 finished with value: 0.22453176327130508 and parameters: {'num_leaves': 90, 'learning_rate': 0.011783504166148076, 'feature_fraction': 0.8849450810064518, 'bagging_fraction': 0.8603123358411909, 'bagging_freq': 8, 'lambda_l1': 4.247900386495339e-08, 'lambda_l2': 4.5598263982196566e-08, 'min_child_samples': 48, 'max_depth': 9, 'max_bin': 231, 'min_data_in_leaf': 40, 'extra_trees': True, 'early_stopping_rounds': 44, 'path_smooth': 0.34444306530337665, 'min_gain_to_split': 0.10139754314350244}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 13:59:39,437] Trial 270 finished with value: 0.22073693208563502 and parameters: {'num_leaves': 92, 'learning_rate': 0.015429038713732138, 'feature_fraction': 0.8972257535113841, 'bagging_fraction': 0.9309917615823187, 'bagging_freq': 8, 'lambda_l1': 1.322010151433609e-07, 'lambda_l2': 1.526456962684535e-08, 'min_child_samples': 47, 'max_depth': 8, 'max_bin': 269, 'min_data_in_leaf': 33, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.6064968305956684, 'min_gain_to_split': 0.2990663791298938}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 14:02:53,665] Trial 271 finished with value: 0.22203078990209263 and parameters: {'num_leaves': 92, 'learning_rate': 0.016773614700783368, 'feature_fraction': 0.9058779253223946, 'bagging_fraction': 0.9209619646203868, 'bagging_freq': 8, 'lambda_l1': 6.930668736093371e-08, 'lambda_l2': 1.5725593933987454e-08, 'min_child_samples': 10, 'max_depth': 8, 'max_bin': 268, 'min_data_in_leaf': 33, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6646110219470709, 'min_gain_to_split': 0.30203788782108426}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 14:05:42,227] Trial 272 finished with value: 0.2223509838617513 and parameters: {'num_leaves': 87, 'learning_rate': 0.015621195148209277, 'feature_fraction': 0.8966641941284387, 'bagging_fraction': 0.9307023180234749, 'bagging_freq': 7, 'lambda_l1': 1.2530500353951357e-07, 'lambda_l2': 1.4558472365763597e-08, 'min_child_samples': 33, 'max_depth': 8, 'max_bin': 243, 'min_data_in_leaf': 30, 'extra_trees': True, 'early_stopping_rounds': 46, 'path_smooth': 0.4386521387319485, 'min_gain_to_split': 0.3861845025438189}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 14:08:36,640] Trial 273 finished with value: 0.22304875169131394 and parameters: {'num_leaves': 90, 'learning_rate': 0.015086124506163949, 'feature_fraction': 0.9148747666728747, 'bagging_fraction': 0.9472227295280995, 'bagging_freq': 8, 'lambda_l1': 1.4330803715843678e-07, 'lambda_l2': 2.8388688726234594e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 254, 'min_data_in_leaf': 31, 'extra_trees': True, 'early_stopping_rounds': 13, 'path_smooth': 0.6280919984312874, 'min_gain_to_split': 0.3762867729297186}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 14:10:02,305] Trial 274 finished with value: 0.224568194883458 and parameters: {'num_leaves': 93, 'learning_rate': 0.028861235136571222, 'feature_fraction': 0.8800476221781453, 'bagging_fraction': 0.9265591771768328, 'bagging_freq': 9, 'lambda_l1': 2.4761616447161e-07, 'lambda_l2': 1.898839667819889e-08, 'min_child_samples': 35, 'max_depth': 7, 'max_bin': 262, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 34, 'path_smooth': 0.6043792947937826, 'min_gain_to_split': 0.35956258233282157}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 14:13:10,227] Trial 275 finished with value: 0.22225354307652218 and parameters: {'num_leaves': 96, 'learning_rate': 0.014290217443142777, 'feature_fraction': 0.9249054993139219, 'bagging_fraction': 0.9335054988606536, 'bagging_freq': 4, 'lambda_l1': 3.14984578491243e-07, 'lambda_l2': 4.0965228620837924e-08, 'min_child_samples': 50, 'max_depth': 8, 'max_bin': 247, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.6467612561460307, 'min_gain_to_split': 0.1889997534316516}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 14:16:58,002] Trial 276 finished with value: 0.2239644035804198 and parameters: {'num_leaves': 88, 'learning_rate': 0.013636552921240398, 'feature_fraction': 0.8956726163019902, 'bagging_fraction': 0.9513631860571041, 'bagging_freq': 8, 'lambda_l1': 1.6071501211742466e-07, 'lambda_l2': 1.3253052446875306e-08, 'min_child_samples': 47, 'max_depth': 9, 'max_bin': 274, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 15, 'path_smooth': 0.6151938993696452, 'min_gain_to_split': 0.4238534152707238}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 14:18:02,395] Trial 277 finished with value: 0.23466162553135303 and parameters: {'num_leaves': 92, 'learning_rate': 0.016142587857933523, 'feature_fraction': 0.8710522771368507, 'bagging_fraction': 0.9441700445959831, 'bagging_freq': 8, 'lambda_l1': 3.186908797842119e-08, 'lambda_l2': 1.0371540057113517e-08, 'min_child_samples': 49, 'max_depth': 3, 'max_bin': 257, 'min_data_in_leaf': 33, 'extra_trees': True, 'early_stopping_rounds': 14, 'path_smooth': 0.5982954033533249, 'min_gain_to_split': 0.12928564356484745}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 14:21:23,327] Trial 278 finished with value: 0.22275967662169557 and parameters: {'num_leaves': 85, 'learning_rate': 0.010425039322405079, 'feature_fraction': 0.7449687270065413, 'bagging_fraction': 0.9378995505153802, 'bagging_freq': 8, 'lambda_l1': 7.324357021655758e-08, 'lambda_l2': 2.1081856916265923e-08, 'min_child_samples': 46, 'max_depth': 8, 'max_bin': 238, 'min_data_in_leaf': 32, 'extra_trees': True, 'early_stopping_rounds': 13, 'path_smooth': 0.6652758784723568, 'min_gain_to_split': 0.28090931816878534}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 14:24:44,474] Trial 279 finished with value: 0.2216024431673121 and parameters: {'num_leaves': 94, 'learning_rate': 0.0131023194506426, 'feature_fraction': 0.9061820278069505, 'bagging_fraction': 0.9615867046289117, 'bagging_freq': 8, 'lambda_l1': 1.801911602929126e-05, 'lambda_l2': 7.015413667456409e-08, 'min_child_samples': 30, 'max_depth': 8, 'max_bin': 265, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.5697676954671629, 'min_gain_to_split': 0.3162003573223864}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 14:28:12,088] Trial 280 finished with value: 0.2228764917024256 and parameters: {'num_leaves': 100, 'learning_rate': 0.01147643079021126, 'feature_fraction': 0.9565130430875262, 'bagging_fraction': 0.9137159176746835, 'bagging_freq': 7, 'lambda_l1': 1.6509466055978504e-08, 'lambda_l2': 2.5746641392045487e-08, 'min_child_samples': 47, 'max_depth': 8, 'max_bin': 212, 'min_data_in_leaf': 41, 'extra_trees': True, 'early_stopping_rounds': 49, 'path_smooth': 0.6181347826109936, 'min_gain_to_split': 0.15846472616904822}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 14:29:37,620] Trial 281 finished with value: 0.234582518469696 and parameters: {'num_leaves': 97, 'learning_rate': 0.03346238649586863, 'feature_fraction': 0.886484336921362, 'bagging_fraction': 0.8295857755642695, 'bagging_freq': 9, 'lambda_l1': 2.9067993639795836e-06, 'lambda_l2': 4.286461960753126e-08, 'min_child_samples': 38, 'max_depth': 8, 'max_bin': 230, 'min_data_in_leaf': 71, 'extra_trees': True, 'early_stopping_rounds': 14, 'path_smooth': 0.5788681332393139, 'min_gain_to_split': 0.14605136053139736}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 14:32:56,918] Trial 282 finished with value: 0.22188157729764582 and parameters: {'num_leaves': 95, 'learning_rate': 0.012325871291774789, 'feature_fraction': 0.8645056250373666, 'bagging_fraction': 0.9544615667517662, 'bagging_freq': 8, 'lambda_l1': 4.610699679281143e-08, 'lambda_l2': 1.4641904788148681e-08, 'min_child_samples': 45, 'max_depth': 8, 'max_bin': 250, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.33558732293883753, 'min_gain_to_split': 0.11102220500216273}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 14:35:51,669] Trial 283 finished with value: 0.22192617970195308 and parameters: {'num_leaves': 90, 'learning_rate': 0.014627095651905127, 'feature_fraction': 0.8488745665573341, 'bagging_fraction': 0.9302434658776013, 'bagging_freq': 8, 'lambda_l1': 8.719432623748185e-06, 'lambda_l2': 2.8854902794351817e-08, 'min_child_samples': 28, 'max_depth': 8, 'max_bin': 271, 'min_data_in_leaf': 42, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.681912873362608, 'min_gain_to_split': 0.33975357857129473}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 14:36:25,670] Trial 284 finished with value: 0.2262816551365158 and parameters: {'num_leaves': 92, 'learning_rate': 0.11371940398059356, 'feature_fraction': 0.7123765494300528, 'bagging_fraction': 0.9440468760070455, 'bagging_freq': 8, 'lambda_l1': 4.647938497634893e-07, 'lambda_l2': 6.342581785794408e-08, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 259, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 50, 'path_smooth': 0.6409374082048955, 'min_gain_to_split': 0.36609617607620726}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 14:38:51,825] Trial 285 finished with value: 0.2853050497022341 and parameters: {'num_leaves': 19, 'learning_rate': 0.011116520382055607, 'feature_fraction': 0.8770596474049457, 'bagging_fraction': 0.9383894065862387, 'bagging_freq': 9, 'lambda_l1': 9.61092701486189e-08, 'lambda_l2': 1.0041844127319234e-08, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 241, 'min_data_in_leaf': 31, 'extra_trees': False, 'early_stopping_rounds': 15, 'path_smooth': 0.4161994652537094, 'min_gain_to_split': 0.32781579781414005}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 14:42:55,214] Trial 286 finished with value: 0.223193914511553 and parameters: {'num_leaves': 94, 'learning_rate': 0.013468087440051317, 'feature_fraction': 0.8971681858747705, 'bagging_fraction': 0.9497850484943542, 'bagging_freq': 5, 'lambda_l1': 4.092070762410083e-06, 'lambda_l2': 1.1808043008559933e-07, 'min_child_samples': 46, 'max_depth': 10, 'max_bin': 249, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 42, 'path_smooth': 0.6026917006108736, 'min_gain_to_split': 0.2985068835795989}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 14:45:25,214] Trial 287 finished with value: 0.22615445016599214 and parameters: {'num_leaves': 97, 'learning_rate': 0.010052134992584377, 'feature_fraction': 0.6675684794814081, 'bagging_fraction': 0.9215130470340613, 'bagging_freq': 8, 'lambda_l1': 6.6605448598235636e-06, 'lambda_l2': 2.0456886970043816e-08, 'min_child_samples': 49, 'max_depth': 7, 'max_bin': 223, 'min_data_in_leaf': 33, 'extra_trees': True, 'early_stopping_rounds': 13, 'path_smooth': 0.6306858726360163, 'min_gain_to_split': 0.3556218219906901}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 14:48:29,755] Trial 288 finished with value: 0.22597210874053925 and parameters: {'num_leaves': 43, 'learning_rate': 0.011876750270649054, 'feature_fraction': 0.8863526303558463, 'bagging_fraction': 0.9324956497862298, 'bagging_freq': 7, 'lambda_l1': 7.571575738964187e-07, 'lambda_l2': 3.3513920669511305e-08, 'min_child_samples': 41, 'max_depth': 9, 'max_bin': 278, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 12, 'path_smooth': 0.591513036491051, 'min_gain_to_split': 0.33968434930130714}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 14:51:31,455] Trial 289 finished with value: 0.22134979240286712 and parameters: {'num_leaves': 91, 'learning_rate': 0.015347681620312087, 'feature_fraction': 0.9040456644418245, 'bagging_fraction': 0.9585416359796178, 'bagging_freq': 8, 'lambda_l1': 2.47035068231596e-08, 'lambda_l2': 1.518921976487161e-08, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 263, 'min_data_in_leaf': 29, 'extra_trees': True, 'early_stopping_rounds': 49, 'path_smooth': 0.5570548677541967, 'min_gain_to_split': 0.3448766355717089}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 14:51:56,172] Trial 290 finished with value: 0.2507562567928644 and parameters: {'num_leaves': 89, 'learning_rate': 0.22563271244548724, 'feature_fraction': 0.7710258796628445, 'bagging_fraction': 0.9416502358479953, 'bagging_freq': 8, 'lambda_l1': 1.6780202104782372e-06, 'lambda_l2': 4.9970836908200146e-08, 'min_child_samples': 46, 'max_depth': 8, 'max_bin': 255, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 15, 'path_smooth': 0.6053546119994999, 'min_gain_to_split': 0.3730180432913952}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 14:55:53,259] Trial 291 finished with value: 0.22290948614243225 and parameters: {'num_leaves': 99, 'learning_rate': 0.010813124174040284, 'feature_fraction': 0.8929000417560352, 'bagging_fraction': 0.9672124790104747, 'bagging_freq': 8, 'lambda_l1': 1.0198784660980117e-08, 'lambda_l2': 1.0037337062469575e-07, 'min_child_samples': 47, 'max_depth': 8, 'max_bin': 270, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 14, 'path_smooth': 0.2613208982901348, 'min_gain_to_split': 0.35957685570229253}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 14:59:08,088] Trial 292 finished with value: 0.22144864009218357 and parameters: {'num_leaves': 96, 'learning_rate': 0.012819940573352964, 'feature_fraction': 0.8747410671332331, 'bagging_fraction': 0.9483812075406405, 'bagging_freq': 8, 'lambda_l1': 1.2154547571751575e-05, 'lambda_l2': 1.9999232180890835e-08, 'min_child_samples': 47, 'max_depth': 8, 'max_bin': 245, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.5732313160872311, 'min_gain_to_split': 0.3317652735606931}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 15:02:16,985] Trial 293 finished with value: 0.2222338522767883 and parameters: {'num_leaves': 67, 'learning_rate': 0.011816536962425286, 'feature_fraction': 0.8832653177536939, 'bagging_fraction': 0.9267256387568953, 'bagging_freq': 8, 'lambda_l1': 3.749648672164985e-06, 'lambda_l2': 1.3941956005202669e-08, 'min_child_samples': 46, 'max_depth': 8, 'max_bin': 235, 'min_data_in_leaf': 44, 'extra_trees': True, 'early_stopping_rounds': 50, 'path_smooth': 0.6213347849010173, 'min_gain_to_split': 0.4074760496513991}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 15:05:34,240] Trial 294 finished with value: 0.22234301394545533 and parameters: {'num_leaves': 92, 'learning_rate': 0.013773960943486556, 'feature_fraction': 0.9121123773037336, 'bagging_fraction': 0.9536524271964302, 'bagging_freq': 10, 'lambda_l1': 3.0637455686526997e-05, 'lambda_l2': 3.1183855089151965e-08, 'min_child_samples': 27, 'max_depth': 8, 'max_bin': 258, 'min_data_in_leaf': 40, 'extra_trees': True, 'early_stopping_rounds': 13, 'path_smooth': 0.36457525358804765, 'min_gain_to_split': 0.3124001514470496}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 15:07:58,370] Trial 295 finished with value: 0.22249190072587793 and parameters: {'num_leaves': 94, 'learning_rate': 0.01254165953856154, 'feature_fraction': 0.8608728237957233, 'bagging_fraction': 0.9360883366660602, 'bagging_freq': 8, 'lambda_l1': 2.5789095317213717e-06, 'lambda_l2': 1.0158360212914656e-08, 'min_child_samples': 31, 'max_depth': 6, 'max_bin': 280, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 40, 'path_smooth': 0.3114962359147996, 'min_gain_to_split': 0.3449684066767205}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 15:11:02,244] Trial 296 finished with value: 0.22453980000056678 and parameters: {'num_leaves': 95, 'learning_rate': 0.010786113939979396, 'feature_fraction': 0.7253790496259922, 'bagging_fraction': 0.7941362862901561, 'bagging_freq': 8, 'lambda_l1': 3.949920207699561e-07, 'lambda_l2': 7.393750420827615e-08, 'min_child_samples': 50, 'max_depth': 8, 'max_bin': 251, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6523327277539595, 'min_gain_to_split': 0.35235196047132755}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 15:15:54,648] Trial 297 finished with value: 0.23082835329188992 and parameters: {'num_leaves': 99, 'learning_rate': 0.012008906948579647, 'feature_fraction': 0.8917093365023047, 'bagging_fraction': 0.9443542733087461, 'bagging_freq': 8, 'lambda_l1': 1.2461920711817048e-06, 'lambda_l2': 2.025179503495859e-08, 'min_child_samples': 44, 'max_depth': 9, 'max_bin': 267, 'min_data_in_leaf': 77, 'extra_trees': True, 'early_stopping_rounds': 45, 'path_smooth': 0.5247206793339287, 'min_gain_to_split': 0.23060656033264992}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 15:18:50,674] Trial 298 finished with value: 0.2216107966460678 and parameters: {'num_leaves': 93, 'learning_rate': 0.014434673307666589, 'feature_fraction': 0.8711186444194697, 'bagging_fraction': 0.9406547073631097, 'bagging_freq': 9, 'lambda_l1': 2.4567285181302957e-07, 'lambda_l2': 3.949778009451243e-08, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 241, 'min_data_in_leaf': 41, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.3844405017773712, 'min_gain_to_split': 0.27190725605194505}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 15:20:23,351] Trial 299 finished with value: 0.2289575834678807 and parameters: {'num_leaves': 97, 'learning_rate': 0.011263508592280574, 'feature_fraction': 0.9202507182517126, 'bagging_fraction': 0.9624168346919107, 'bagging_freq': 7, 'lambda_l1': 2.070743587834684e-06, 'lambda_l2': 2.3908517941648123e-08, 'min_child_samples': 12, 'max_depth': 4, 'max_bin': 230, 'min_data_in_leaf': 33, 'extra_trees': True, 'early_stopping_rounds': 11, 'path_smooth': 0.5811349356843456, 'min_gain_to_split': 0.3836881717515501}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 15:23:49,082] Trial 300 finished with value: 0.22150269063109018 and parameters: {'num_leaves': 90, 'learning_rate': 0.013231719827017256, 'feature_fraction': 0.9483403903336513, 'bagging_fraction': 0.9323636723144886, 'bagging_freq': 8, 'lambda_l1': 6.84951158641761e-06, 'lambda_l2': 1.5271503008946177e-07, 'min_child_samples': 47, 'max_depth': 8, 'max_bin': 271, 'min_data_in_leaf': 42, 'extra_trees': True, 'early_stopping_rounds': 14, 'path_smooth': 0.6118139110016542, 'min_gain_to_split': 0.3248332300671971}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 15:27:28,127] Trial 301 finished with value: 0.2236550882109459 and parameters: {'num_leaves': 98, 'learning_rate': 0.010087438761646587, 'feature_fraction': 0.8815661861658323, 'bagging_fraction': 0.9521999294335878, 'bagging_freq': 8, 'lambda_l1': 0.03424837349447869, 'lambda_l2': 5.174182685792807e-08, 'min_child_samples': 33, 'max_depth': 10, 'max_bin': 146, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 13, 'path_smooth': 0.2082031768847659, 'min_gain_to_split': 0.36852863884217507}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 15:28:41,431] Trial 302 finished with value: 0.22957868035921383 and parameters: {'num_leaves': 93, 'learning_rate': 0.038331366390651204, 'feature_fraction': 0.8993881514166238, 'bagging_fraction': 0.7539910899656626, 'bagging_freq': 8, 'lambda_l1': 6.810365813171577e-08, 'lambda_l2': 1.4549986754464692e-08, 'min_child_samples': 46, 'max_depth': 8, 'max_bin': 252, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 49, 'path_smooth': 0.24331033140647484, 'min_gain_to_split': 0.3366350804408301}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 15:31:07,210] Trial 303 finished with value: 0.22316643429247432 and parameters: {'num_leaves': 87, 'learning_rate': 0.018024975437579388, 'feature_fraction': 0.8890248355004724, 'bagging_fraction': 0.9460843918054055, 'bagging_freq': 8, 'lambda_l1': 4.9785106641839014e-06, 'lambda_l2': 0.2956332639194823, 'min_child_samples': 49, 'max_depth': 8, 'max_bin': 262, 'min_data_in_leaf': 31, 'extra_trees': True, 'early_stopping_rounds': 50, 'path_smooth': 0.2916396479028877, 'min_gain_to_split': 0.3541800540251429}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 15:35:21,811] Trial 304 finished with value: 0.2618615199539233 and parameters: {'num_leaves': 96, 'learning_rate': 0.016133768076538366, 'feature_fraction': 0.9047270222131412, 'bagging_fraction': 0.9712696043323034, 'bagging_freq': 8, 'lambda_l1': 1.4540138045730787e-07, 'lambda_l2': 4.728678897452147e-07, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 243, 'min_data_in_leaf': 39, 'extra_trees': False, 'early_stopping_rounds': 12, 'path_smooth': 0.5450312023494606, 'min_gain_to_split': 0.43736045239283194}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 15:38:55,511] Trial 305 finished with value: 0.22248703873898873 and parameters: {'num_leaves': 91, 'learning_rate': 0.012161396408774658, 'feature_fraction': 0.8764839488162686, 'bagging_fraction': 0.9262377648783836, 'bagging_freq': 7, 'lambda_l1': 2.1854487113884008e-08, 'lambda_l2': 1.0015494073317305e-07, 'min_child_samples': 29, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.6348027263941562, 'min_gain_to_split': 0.11509249157551013}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 15:42:20,362] Trial 306 finished with value: 0.2215173115543882 and parameters: {'num_leaves': 84, 'learning_rate': 0.011080055708855806, 'feature_fraction': 0.8976301103921783, 'bagging_fraction': 0.9588356220544851, 'bagging_freq': 8, 'lambda_l1': 5.631735526350513e-05, 'lambda_l2': 2.94691137058434e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 275, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 15, 'path_smooth': 0.5918449971235, 'min_gain_to_split': 0.0870584202100432}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 15:44:56,012] Trial 307 finished with value: 0.22565277882454868 and parameters: {'num_leaves': 89, 'learning_rate': 0.013129194280954187, 'feature_fraction': 0.8680333253748851, 'bagging_fraction': 0.9371962102899826, 'bagging_freq': 9, 'lambda_l1': 3.249183726386477e-06, 'lambda_l2': 1.0284089396311269e-08, 'min_child_samples': 47, 'max_depth': 8, 'max_bin': 167, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 14, 'path_smooth': 0.6608331260030907, 'min_gain_to_split': 0.06589876849883466}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 15:48:24,871] Trial 308 finished with value: 0.22354824457121647 and parameters: {'num_leaves': 95, 'learning_rate': 0.014331772320358734, 'feature_fraction': 0.8864946023468445, 'bagging_fraction': 0.9495771632107896, 'bagging_freq': 5, 'lambda_l1': 9.705225273624507e-06, 'lambda_l2': 1.8204360193599175e-08, 'min_child_samples': 17, 'max_depth': 9, 'max_bin': 257, 'min_data_in_leaf': 40, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.5607947577401079, 'min_gain_to_split': 0.36601020503598497}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 15:51:47,502] Trial 309 finished with value: 0.2230652693808024 and parameters: {'num_leaves': 93, 'learning_rate': 0.011332854138839391, 'feature_fraction': 0.9111366657649823, 'bagging_fraction': 0.9412296787672622, 'bagging_freq': 8, 'lambda_l1': 0.015898253712469765, 'lambda_l2': 3.2493992648832645e-07, 'min_child_samples': 30, 'max_depth': 8, 'max_bin': 220, 'min_data_in_leaf': 43, 'extra_trees': True, 'early_stopping_rounds': 13, 'path_smooth': 0.6112477157831112, 'min_gain_to_split': 0.39235449018799845}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 15:55:00,558] Trial 310 finished with value: 0.22297626271117305 and parameters: {'num_leaves': 100, 'learning_rate': 0.012394494330238011, 'feature_fraction': 0.857127457546209, 'bagging_fraction': 0.9177219493387724, 'bagging_freq': 9, 'lambda_l1': 1.5353181599736642e-05, 'lambda_l2': 4.171208589984387e-08, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 237, 'min_data_in_leaf': 29, 'extra_trees': True, 'early_stopping_rounds': 46, 'path_smooth': 0.18041076727365557, 'min_gain_to_split': 0.34273334413492906}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 15:58:48,552] Trial 311 finished with value: 0.22318375682236025 and parameters: {'num_leaves': 98, 'learning_rate': 0.010698161582785312, 'feature_fraction': 0.8830999847030532, 'bagging_fraction': 0.9324590661205908, 'bagging_freq': 8, 'lambda_l1': 8.150103574137216e-07, 'lambda_l2': 5.110738551731333e-05, 'min_child_samples': 26, 'max_depth': 8, 'max_bin': 250, 'min_data_in_leaf': 32, 'extra_trees': True, 'early_stopping_rounds': 12, 'path_smooth': 0.5899377445225653, 'min_gain_to_split': 0.16592548303265117}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 16:01:28,424] Trial 312 finished with value: 0.22675479437851376 and parameters: {'num_leaves': 95, 'learning_rate': 0.013677222599276093, 'feature_fraction': 0.895951209797557, 'bagging_fraction': 0.9557980188762601, 'bagging_freq': 8, 'lambda_l1': 4.1690056586375203e-08, 'lambda_l2': 7.291356254836527e-08, 'min_child_samples': 35, 'max_depth': 8, 'max_bin': 182, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 15, 'path_smooth': 0.6317502115728835, 'min_gain_to_split': 0.32191052141841947}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 16:05:23,166] Trial 313 finished with value: 0.22279449618912048 and parameters: {'num_leaves': 91, 'learning_rate': 0.01541709645269031, 'feature_fraction': 0.8223575893517417, 'bagging_fraction': 0.9451925547498693, 'bagging_freq': 8, 'lambda_l1': 1.3098906228532356e-06, 'lambda_l2': 1.5172039101357062e-08, 'min_child_samples': 14, 'max_depth': 8, 'max_bin': 473, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 49, 'path_smooth': 0.2286324968823624, 'min_gain_to_split': 0.35885376109576556}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 16:08:32,434] Trial 314 finished with value: 0.22171127950108133 and parameters: {'num_leaves': 94, 'learning_rate': 0.01173374393944349, 'feature_fraction': 0.9316536431115153, 'bagging_fraction': 0.938138539296022, 'bagging_freq': 8, 'lambda_l1': 5.023571992151925e-06, 'lambda_l2': 1.0145561307698798e-08, 'min_child_samples': 34, 'max_depth': 7, 'max_bin': 264, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 37, 'path_smooth': 0.3311733536157269, 'min_gain_to_split': 0.37979586259754416}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 16:09:07,648] Trial 315 finished with value: 0.23246764667671732 and parameters: {'num_leaves': 89, 'learning_rate': 0.08569689518387066, 'feature_fraction': 0.6159027867554016, 'bagging_fraction': 0.9270513822427389, 'bagging_freq': 10, 'lambda_l1': 2.550534644343135e-06, 'lambda_l2': 2.6693438065072873e-08, 'min_child_samples': 45, 'max_depth': 8, 'max_bin': 245, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 14, 'path_smooth': 0.7033465592884185, 'min_gain_to_split': 0.3471966762345867}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 16:12:26,597] Trial 316 finished with value: 0.22276376089235717 and parameters: {'num_leaves': 97, 'learning_rate': 0.012893862287556701, 'feature_fraction': 0.8898279113541913, 'bagging_fraction': 0.9653242480911888, 'bagging_freq': 8, 'lambda_l1': 2.043195933883207e-07, 'lambda_l2': 1.4255582436416722e-07, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 231, 'min_data_in_leaf': 41, 'extra_trees': True, 'early_stopping_rounds': 33, 'path_smooth': 0.2691592944619634, 'min_gain_to_split': 0.32970837238611267}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 16:17:00,617] Trial 317 finished with value: 0.2236511475211322 and parameters: {'num_leaves': 93, 'learning_rate': 0.010600801005262223, 'feature_fraction': 0.8754093180956567, 'bagging_fraction': 0.9534656132203441, 'bagging_freq': 8, 'lambda_l1': 1.4646423852197352e-08, 'lambda_l2': 8.611242977385199e-07, 'min_child_samples': 46, 'max_depth': 9, 'max_bin': 275, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 13, 'path_smooth': 0.5813592949670588, 'min_gain_to_split': 0.35387351258694544}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 16:19:45,601] Trial 318 finished with value: 0.2239497950131387 and parameters: {'num_leaves': 96, 'learning_rate': 0.016671156652889218, 'feature_fraction': 0.9033773288886613, 'bagging_fraction': 0.9341335087846343, 'bagging_freq': 7, 'lambda_l1': 9.871536011682082e-08, 'lambda_l2': 2.2426764268392534e-08, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 255, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 50, 'path_smooth': 0.4739820262134108, 'min_gain_to_split': 0.2931266415780736}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 16:23:03,454] Trial 319 finished with value: 0.22273535648621254 and parameters: {'num_leaves': 59, 'learning_rate': 0.011680857692183962, 'feature_fraction': 0.8794887347910648, 'bagging_fraction': 0.8997085187189054, 'bagging_freq': 8, 'lambda_l1': 5.310921453390646e-07, 'lambda_l2': 5.3022372038535244e-08, 'min_child_samples': 49, 'max_depth': 8, 'max_bin': 286, 'min_data_in_leaf': 32, 'extra_trees': True, 'early_stopping_rounds': 17, 'path_smooth': 0.4050823999160024, 'min_gain_to_split': 0.20132526799066858}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 16:24:39,703] Trial 320 finished with value: 0.22497688733870266 and parameters: {'num_leaves': 92, 'learning_rate': 0.031046280809955792, 'feature_fraction': 0.8925813764920745, 'bagging_fraction': 0.9471567337893473, 'bagging_freq': 8, 'lambda_l1': 3.4425771289781575e-07, 'lambda_l2': 1.48256889870825e-08, 'min_child_samples': 44, 'max_depth': 8, 'max_bin': 266, 'min_data_in_leaf': 42, 'extra_trees': True, 'early_stopping_rounds': 49, 'path_smooth': 0.5654335883175173, 'min_gain_to_split': 0.3377545022692014}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 16:26:36,164] Trial 321 finished with value: 0.222220337729179 and parameters: {'num_leaves': 88, 'learning_rate': 0.023412736307485, 'feature_fraction': 0.865209659291927, 'bagging_fraction': 0.9402979516098743, 'bagging_freq': 9, 'lambda_l1': 6.4663894708919144e-06, 'lambda_l2': 3.583517987145674e-08, 'min_child_samples': 47, 'max_depth': 8, 'max_bin': 248, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 14, 'path_smooth': 0.67630265190137, 'min_gain_to_split': 0.3644909867411923}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 16:29:42,130] Trial 322 finished with value: 0.22235529048562244 and parameters: {'num_leaves': 100, 'learning_rate': 0.01400260007533811, 'feature_fraction': 0.9598152788437413, 'bagging_fraction': 0.9587105156530601, 'bagging_freq': 8, 'lambda_l1': 1.4248718811005952e-06, 'lambda_l2': 1.9371160842712255e-08, 'min_child_samples': 42, 'max_depth': 8, 'max_bin': 260, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 12, 'path_smooth': 0.6130258371579062, 'min_gain_to_split': 0.37229751535313255}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 16:34:47,767] Trial 323 finished with value: 0.2650725596793772 and parameters: {'num_leaves': 91, 'learning_rate': 0.012636962581832032, 'feature_fraction': 0.882674505559898, 'bagging_fraction': 0.9208905204994311, 'bagging_freq': 8, 'lambda_l1': 3.6884917696707976e-06, 'lambda_l2': 8.081781929880688e-08, 'min_child_samples': 47, 'max_depth': 9, 'max_bin': 192, 'min_data_in_leaf': 39, 'extra_trees': False, 'early_stopping_rounds': 47, 'path_smooth': 0.6447179045562172, 'min_gain_to_split': 0.30894459047095446}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 16:38:25,790] Trial 324 finished with value: 0.2231726220514359 and parameters: {'num_leaves': 86, 'learning_rate': 0.011312069516618785, 'feature_fraction': 0.9982942049325068, 'bagging_fraction': 0.930603050913289, 'bagging_freq': 6, 'lambda_l1': 0.004054925679106699, 'lambda_l2': 3.5187460730128064e-08, 'min_child_samples': 49, 'max_depth': 8, 'max_bin': 239, 'min_data_in_leaf': 33, 'extra_trees': True, 'early_stopping_rounds': 15, 'path_smooth': 0.5443923087827071, 'min_gain_to_split': 0.3160530138044702}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 16:40:56,610] Trial 325 finished with value: 0.22127335028864908 and parameters: {'num_leaves': 98, 'learning_rate': 0.020191631428155544, 'feature_fraction': 0.9184895888378157, 'bagging_fraction': 0.9501819122300872, 'bagging_freq': 8, 'lambda_l1': 3.446418947238607e-08, 'lambda_l2': 1.904097639256974e-07, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 281, 'min_data_in_leaf': 40, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.5960362412043798, 'min_gain_to_split': 0.34693417759107015}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 16:46:13,226] Trial 326 finished with value: 0.2241192854578405 and parameters: {'num_leaves': 95, 'learning_rate': 0.010069850719028415, 'feature_fraction': 0.899971299470795, 'bagging_fraction': 0.9411239395006065, 'bagging_freq': 8, 'lambda_l1': 8.713723223372147e-06, 'lambda_l2': 1.4169046930101198e-08, 'min_child_samples': 46, 'max_depth': 10, 'max_bin': 270, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 32, 'path_smooth': 0.6249573237559065, 'min_gain_to_split': 0.35816693568555574}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 16:48:27,679] Trial 327 finished with value: 0.22391299408166407 and parameters: {'num_leaves': 93, 'learning_rate': 0.014891036917631334, 'feature_fraction': 0.8899830987932583, 'bagging_fraction': 0.9359521856470899, 'bagging_freq': 8, 'lambda_l1': 2.811144559084124, 'lambda_l2': 2.5300017415272607e-08, 'min_child_samples': 48, 'max_depth': 7, 'max_bin': 254, 'min_data_in_leaf': 30, 'extra_trees': True, 'early_stopping_rounds': 13, 'path_smooth': 0.5107896696423306, 'min_gain_to_split': 0.3313415417834655}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 16:51:57,504] Trial 328 finished with value: 0.22219933907379624 and parameters: {'num_leaves': 90, 'learning_rate': 0.011965741548965157, 'feature_fraction': 0.9107013908200613, 'bagging_fraction': 0.9456298940606722, 'bagging_freq': 9, 'lambda_l1': 0.007533115836861635, 'lambda_l2': 5.942216918026932e-08, 'min_child_samples': 28, 'max_depth': 8, 'max_bin': 247, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 50, 'path_smooth': 0.5680016303161037, 'min_gain_to_split': 0.346661056271908}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 16:52:29,966] Trial 329 finished with value: 0.23781826344982587 and parameters: {'num_leaves': 95, 'learning_rate': 0.14979481683498957, 'feature_fraction': 0.8696001026653334, 'bagging_fraction': 0.9631867790354139, 'bagging_freq': 8, 'lambda_l1': 2.5184044277842233e-06, 'lambda_l2': 1.019849920686521e-05, 'min_child_samples': 45, 'max_depth': 8, 'max_bin': 227, 'min_data_in_leaf': 44, 'extra_trees': True, 'early_stopping_rounds': 14, 'path_smooth': 0.20226896349778714, 'min_gain_to_split': 0.07348379783964282}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 16:55:33,230] Trial 330 finished with value: 0.22173255260789934 and parameters: {'num_leaves': 97, 'learning_rate': 0.013560876412281566, 'feature_fraction': 0.8783585659698872, 'bagging_fraction': 0.9545114291320178, 'bagging_freq': 8, 'lambda_l1': 9.687252016924526e-07, 'lambda_l2': 1.0104280717004503e-08, 'min_child_samples': 50, 'max_depth': 8, 'max_bin': 259, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 11, 'path_smooth': 0.600235155105212, 'min_gain_to_split': 0.3356160794300884}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 16:59:27,553] Trial 331 finished with value: 0.22005204051073837 and parameters: {'num_leaves': 92, 'learning_rate': 0.010742962451769191, 'feature_fraction': 0.9435374239644163, 'bagging_fraction': 0.9731594312812865, 'bagging_freq': 7, 'lambda_l1': 1.7881566323349862e-06, 'lambda_l2': 1.9506780582193233e-08, 'min_child_samples': 39, 'max_depth': 8, 'max_bin': 237, 'min_data_in_leaf': 41, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.35054934369416707, 'min_gain_to_split': 0.3782284577335775}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 17:01:47,288] Trial 332 finished with value: 0.22358186497170665 and parameters: {'num_leaves': 91, 'learning_rate': 0.010038687206639493, 'feature_fraction': 0.9464224813620845, 'bagging_fraction': 0.9747859747863337, 'bagging_freq': 7, 'lambda_l1': 1.7992204304915917e-06, 'lambda_l2': 9.804894838936173e-08, 'min_child_samples': 37, 'max_depth': 5, 'max_bin': 215, 'min_data_in_leaf': 47, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.3447909760185621, 'min_gain_to_split': 0.3796351727034251}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 17:05:30,461] Trial 333 finished with value: 0.22085494012637047 and parameters: {'num_leaves': 92, 'learning_rate': 0.010771769237560291, 'feature_fraction': 0.9333405441446624, 'bagging_fraction': 0.9631883614594796, 'bagging_freq': 7, 'lambda_l1': 9.425751553228184e-07, 'lambda_l2': 0.0002850480937831828, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 233, 'min_data_in_leaf': 43, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.3639361039061229, 'min_gain_to_split': 0.39954307704909225}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 17:09:48,675] Trial 334 finished with value: 0.2228944183828001 and parameters: {'num_leaves': 89, 'learning_rate': 0.010578632844291934, 'feature_fraction': 0.9282312797243435, 'bagging_fraction': 0.9713234200077234, 'bagging_freq': 7, 'lambda_l1': 6.706347076638719e-07, 'lambda_l2': 0.00040293420254556417, 'min_child_samples': 32, 'max_depth': 9, 'max_bin': 234, 'min_data_in_leaf': 45, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.37556128531383737, 'min_gain_to_split': 0.40368189713030406}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 17:13:33,814] Trial 335 finished with value: 0.22438287699375614 and parameters: {'num_leaves': 92, 'learning_rate': 0.010979718700660163, 'feature_fraction': 0.9313591108539793, 'bagging_fraction': 0.9677040971343648, 'bagging_freq': 6, 'lambda_l1': 9.799826190083224e-07, 'lambda_l2': 0.0002460490203742125, 'min_child_samples': 40, 'max_depth': 8, 'max_bin': 227, 'min_data_in_leaf': 42, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.35833646309223566, 'min_gain_to_split': 0.39790045557631804}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 17:17:58,010] Trial 336 finished with value: 0.22320664550989386 and parameters: {'num_leaves': 90, 'learning_rate': 0.010003607705039915, 'feature_fraction': 0.9404534881159315, 'bagging_fraction': 0.9713930897107557, 'bagging_freq': 6, 'lambda_l1': 1.7122603762854227e-06, 'lambda_l2': 1.7269909515923313e-05, 'min_child_samples': 30, 'max_depth': 8, 'max_bin': 236, 'min_data_in_leaf': 42, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.3028394887751318, 'min_gain_to_split': 0.3978987312167451}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 17:21:28,862] Trial 337 finished with value: 0.22176146445394757 and parameters: {'num_leaves': 87, 'learning_rate': 0.010935638131996172, 'feature_fraction': 0.9427206044639332, 'bagging_fraction': 0.9666038306926971, 'bagging_freq': 7, 'lambda_l1': 1.3327267187499436e-06, 'lambda_l2': 0.008690516274738413, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 209, 'min_data_in_leaf': 41, 'extra_trees': True, 'early_stopping_rounds': 17, 'path_smooth': 0.37418498853821514, 'min_gain_to_split': 0.41908783082301676}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 17:24:34,738] Trial 338 finished with value: 0.2230465511240471 and parameters: {'num_leaves': 92, 'learning_rate': 0.01139649976132083, 'feature_fraction': 0.9535608340204824, 'bagging_fraction': 0.9578174482602752, 'bagging_freq': 6, 'lambda_l1': 3.0241682641595613e-07, 'lambda_l2': 0.00013150345393635621, 'min_child_samples': 31, 'max_depth': 7, 'max_bin': 241, 'min_data_in_leaf': 40, 'extra_trees': True, 'early_stopping_rounds': 17, 'path_smooth': 0.3895657693431685, 'min_gain_to_split': 0.39034624255328654}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 17:28:25,569] Trial 339 finished with value: 0.2226155548049909 and parameters: {'num_leaves': 93, 'learning_rate': 0.010784287006119563, 'feature_fraction': 0.92313978593876, 'bagging_fraction': 0.9772589157004599, 'bagging_freq': 7, 'lambda_l1': 2.2209186685577154e-06, 'lambda_l2': 0.0053343197932633705, 'min_child_samples': 29, 'max_depth': 8, 'max_bin': 250, 'min_data_in_leaf': 43, 'extra_trees': True, 'early_stopping_rounds': 15, 'path_smooth': 0.34392999297509524, 'min_gain_to_split': 0.40550664663798497}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 17:32:06,315] Trial 340 finished with value: 0.22130188815067403 and parameters: {'num_leaves': 89, 'learning_rate': 0.011972184851737797, 'feature_fraction': 0.9641626622775813, 'bagging_fraction': 0.9598517968843057, 'bagging_freq': 5, 'lambda_l1': 7.001860017177438e-07, 'lambda_l2': 1.300387182414053e-07, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 40, 'extra_trees': True, 'early_stopping_rounds': 35, 'path_smooth': 0.36213829991436247, 'min_gain_to_split': 0.25438166719579597}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 17:35:30,991] Trial 341 finished with value: 0.22344850448902637 and parameters: {'num_leaves': 91, 'learning_rate': 0.010647032292326296, 'feature_fraction': 0.7835819459340164, 'bagging_fraction': 0.9658646908514769, 'bagging_freq': 7, 'lambda_l1': 4.4142767866213836e-07, 'lambda_l2': 4.818564828664649e-08, 'min_child_samples': 42, 'max_depth': 8, 'max_bin': 225, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 17, 'path_smooth': 0.2817326793345213, 'min_gain_to_split': 0.3807855447447026}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 17:39:04,208] Trial 342 finished with value: 0.22236123016680706 and parameters: {'num_leaves': 80, 'learning_rate': 0.01146396269400813, 'feature_fraction': 0.9294963681937499, 'bagging_fraction': 0.9621769419301524, 'bagging_freq': 9, 'lambda_l1': 1.8902164738552247e-07, 'lambda_l2': 0.028043064450654874, 'min_child_samples': 47, 'max_depth': 8, 'max_bin': 235, 'min_data_in_leaf': 41, 'extra_trees': True, 'early_stopping_rounds': 15, 'path_smooth': 0.3383691619957693, 'min_gain_to_split': 0.3718331727618625}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 17:45:29,240] Trial 343 finished with value: 0.25837488746236187 and parameters: {'num_leaves': 94, 'learning_rate': 0.011797853993448173, 'feature_fraction': 0.9353228362950932, 'bagging_fraction': 0.9498083415744151, 'bagging_freq': 10, 'lambda_l1': 3.469226025897284e-06, 'lambda_l2': 7.851336235905392e-05, 'min_child_samples': 25, 'max_depth': 8, 'max_bin': 262, 'min_data_in_leaf': 83, 'extra_trees': False, 'early_stopping_rounds': 18, 'path_smooth': 0.39431432880161743, 'min_gain_to_split': 0.13850893068591905}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 17:50:00,032] Trial 344 finished with value: 0.22249588429826855 and parameters: {'num_leaves': 62, 'learning_rate': 0.010543734225396437, 'feature_fraction': 0.9509764281767552, 'bagging_fraction': 0.9729851057071353, 'bagging_freq': 4, 'lambda_l1': 1.1579643520128449e-06, 'lambda_l2': 0.0011865185153156763, 'min_child_samples': 18, 'max_depth': 8, 'max_bin': 252, 'min_data_in_leaf': 44, 'extra_trees': True, 'early_stopping_rounds': 49, 'path_smooth': 0.35726089652400955, 'min_gain_to_split': 0.41430590663868966}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 17:54:16,146] Trial 345 finished with value: 0.22117991917986402 and parameters: {'num_leaves': 92, 'learning_rate': 0.01267548033046359, 'feature_fraction': 0.9356251064594215, 'bagging_fraction': 0.9549114314955469, 'bagging_freq': 8, 'lambda_l1': 1.7103745149306472e-06, 'lambda_l2': 0.0018582634990061831, 'min_child_samples': 30, 'max_depth': 10, 'max_bin': 243, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 50, 'path_smooth': 0.32153782366752626, 'min_gain_to_split': 0.36622162301193195}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 17:59:10,040] Trial 346 finished with value: 0.22726475923575623 and parameters: {'num_leaves': 90, 'learning_rate': 0.010010733726993251, 'feature_fraction': 0.936723757489822, 'bagging_fraction': 0.952512084470435, 'bagging_freq': 9, 'lambda_l1': 3.335536774131937e-06, 'lambda_l2': 2.6236925861136593e-07, 'min_child_samples': 48, 'max_depth': 9, 'max_bin': 268, 'min_data_in_leaf': 64, 'extra_trees': True, 'early_stopping_rounds': 12, 'path_smooth': 0.31003821567773765, 'min_gain_to_split': 0.3769066494132624}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 18:05:14,741] Trial 347 finished with value: 0.22141099200844744 and parameters: {'num_leaves': 93, 'learning_rate': 0.011297430242764368, 'feature_fraction': 0.9851305430890671, 'bagging_fraction': 0.9607543750609445, 'bagging_freq': 8, 'lambda_l1': 1.210527656166412e-07, 'lambda_l2': 2.9674745523940194e-08, 'min_child_samples': 38, 'max_depth': 9, 'max_bin': 253, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 15, 'path_smooth': 0.6523899960566156, 'min_gain_to_split': 0.0593882110851379}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 18:09:44,108] Trial 348 finished with value: 0.22400293550238048 and parameters: {'num_leaves': 94, 'learning_rate': 0.012289413364003058, 'feature_fraction': 0.8421007319265804, 'bagging_fraction': 0.9459079840549453, 'bagging_freq': 8, 'lambda_l1': 0.03056344869402096, 'lambda_l2': 4.778313732460367e-08, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 221, 'min_data_in_leaf': 40, 'extra_trees': True, 'early_stopping_rounds': 34, 'path_smooth': 0.4325077569475678, 'min_gain_to_split': 0.3833223795572628}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 18:15:47,443] Trial 349 finished with value: 0.22074038842244156 and parameters: {'num_leaves': 88, 'learning_rate': 0.012966140815557333, 'feature_fraction': 0.9441008537595734, 'bagging_fraction': 0.9567876846349338, 'bagging_freq': 7, 'lambda_l1': 7.86414417331349e-07, 'lambda_l2': 0.0036213394883520033, 'min_child_samples': 49, 'max_depth': 8, 'max_bin': 233, 'min_data_in_leaf': 43, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.6308413736984894, 'min_gain_to_split': 0.39395770012390835}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 18:21:47,427] Trial 350 finished with value: 0.2248639393005591 and parameters: {'num_leaves': 85, 'learning_rate': 0.012737583596063721, 'feature_fraction': 0.9423429493930913, 'bagging_fraction': 0.9628759812053845, 'bagging_freq': 7, 'lambda_l1': 5.402039706609936e-07, 'lambda_l2': 0.004351357515627808, 'min_child_samples': 50, 'max_depth': 8, 'max_bin': 232, 'min_data_in_leaf': 44, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.666347740428551, 'min_gain_to_split': 0.4061576680822132}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 18:29:30,383] Trial 351 finished with value: 0.22840834170469143 and parameters: {'num_leaves': 87, 'learning_rate': 0.011279982264773865, 'feature_fraction': 0.9573203331559355, 'bagging_fraction': 0.882264928740529, 'bagging_freq': 7, 'lambda_l1': 8.880673259257523e-07, 'lambda_l2': 0.0005676841987225242, 'min_child_samples': 49, 'max_depth': 8, 'max_bin': 229, 'min_data_in_leaf': 45, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.6381166671124416, 'min_gain_to_split': 0.3967367334768903}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 18:36:21,823] Trial 352 finished with value: 0.2212696263410064 and parameters: {'num_leaves': 88, 'learning_rate': 0.011963014349216887, 'feature_fraction': 0.9503918026021289, 'bagging_fraction': 0.956904273402976, 'bagging_freq': 7, 'lambda_l1': 5.363639669415142e-07, 'lambda_l2': 0.0032406571691475415, 'min_child_samples': 49, 'max_depth': 7, 'max_bin': 242, 'min_data_in_leaf': 42, 'extra_trees': True, 'early_stopping_rounds': 17, 'path_smooth': 0.6877702972432284, 'min_gain_to_split': 0.09629829927711563}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 18:42:58,944] Trial 353 finished with value: 0.2268190868913722 and parameters: {'num_leaves': 48, 'learning_rate': 0.010662523628027342, 'feature_fraction': 0.9266635340179498, 'bagging_fraction': 0.8728613128201456, 'bagging_freq': 7, 'lambda_l1': 3.1860254727749364e-07, 'lambda_l2': 5.992030988250573e-06, 'min_child_samples': 49, 'max_depth': 8, 'max_bin': 218, 'min_data_in_leaf': 47, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.40962026811854335, 'min_gain_to_split': 0.39779367052621467}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 18:50:02,870] Trial 354 finished with value: 0.22413060507463775 and parameters: {'num_leaves': 90, 'learning_rate': 0.012853481106445536, 'feature_fraction': 0.9391078646332071, 'bagging_fraction': 0.9684008558617949, 'bagging_freq': 7, 'lambda_l1': 0.002411748476456066, 'lambda_l2': 0.006569702404590269, 'min_child_samples': 39, 'max_depth': 8, 'max_bin': 235, 'min_data_in_leaf': 42, 'extra_trees': True, 'early_stopping_rounds': 49, 'path_smooth': 0.6284259597401815, 'min_gain_to_split': 0.386263354003831}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 18:56:04,984] Trial 355 finished with value: 0.22229417945273505 and parameters: {'num_leaves': 88, 'learning_rate': 0.015562924002473564, 'feature_fraction': 0.9179283094711789, 'bagging_fraction': 0.9761389707231162, 'bagging_freq': 5, 'lambda_l1': 9.292569980655812e-07, 'lambda_l2': 0.0024979317987617344, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 247, 'min_data_in_leaf': 43, 'extra_trees': True, 'early_stopping_rounds': 17, 'path_smooth': 0.2442049652569766, 'min_gain_to_split': 0.39351721718286886}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 19:03:41,768] Trial 356 finished with value: 0.22309179986457645 and parameters: {'num_leaves': 82, 'learning_rate': 0.011737608407727744, 'feature_fraction': 0.9646857728702435, 'bagging_fraction': 0.9520146987605754, 'bagging_freq': 7, 'lambda_l1': 1.6402080789815196e-06, 'lambda_l2': 0.9212872409833921, 'min_child_samples': 11, 'max_depth': 8, 'max_bin': 258, 'min_data_in_leaf': 41, 'extra_trees': True, 'early_stopping_rounds': 50, 'path_smooth': 0.33071862306580974, 'min_gain_to_split': 0.15004576794470653}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 19:08:16,240] Trial 357 finished with value: 0.22233057845905427 and parameters: {'num_leaves': 91, 'learning_rate': 0.01853914143949572, 'feature_fraction': 0.9448765262941685, 'bagging_fraction': 0.9578584670234466, 'bagging_freq': 8, 'lambda_l1': 2.696869102721043e-06, 'lambda_l2': 0.002721640467084559, 'min_child_samples': 50, 'max_depth': 8, 'max_bin': 238, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.6170850517101552, 'min_gain_to_split': 0.1289192692644302}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 19:14:56,226] Trial 358 finished with value: 0.22341460161430451 and parameters: {'num_leaves': 87, 'learning_rate': 0.014513361839013538, 'feature_fraction': 0.9547464977879796, 'bagging_fraction': 0.9646154215798021, 'bagging_freq': 6, 'lambda_l1': 0.9727233661807647, 'lambda_l2': 0.010623080552942287, 'min_child_samples': 13, 'max_depth': 8, 'max_bin': 250, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.5233541987670954, 'min_gain_to_split': 0.4093004030293364}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 19:21:02,944] Trial 359 finished with value: 0.22461087817036868 and parameters: {'num_leaves': 85, 'learning_rate': 0.0109556573186118, 'feature_fraction': 0.7601864520937046, 'bagging_fraction': 0.9488023087057851, 'bagging_freq': 9, 'lambda_l1': 4.592291537751922e-06, 'lambda_l2': 7.501372195784898e-08, 'min_child_samples': 29, 'max_depth': 8, 'max_bin': 224, 'min_data_in_leaf': 40, 'extra_trees': True, 'early_stopping_rounds': 13, 'path_smooth': 0.6510354616571972, 'min_gain_to_split': 0.1065846829239952}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 19:28:33,382] Trial 360 finished with value: 0.22389901626185932 and parameters: {'num_leaves': 89, 'learning_rate': 0.012285190101476605, 'feature_fraction': 0.6480239725116569, 'bagging_fraction': 0.9529006252750554, 'bagging_freq': 7, 'lambda_l1': 1.1332912696163941e-06, 'lambda_l2': 0.0008983569061383549, 'min_child_samples': 16, 'max_depth': 9, 'max_bin': 260, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 11, 'path_smooth': 0.5817774630920908, 'min_gain_to_split': 0.351824402511449}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 19:34:52,212] Trial 361 finished with value: 0.2212621860181289 and parameters: {'num_leaves': 92, 'learning_rate': 0.013185606711202238, 'feature_fraction': 0.8706668609232936, 'bagging_fraction': 0.9446579345379057, 'bagging_freq': 8, 'lambda_l1': 7.072523883407669e-07, 'lambda_l2': 1.0797161137125867e-07, 'min_child_samples': 47, 'max_depth': 8, 'max_bin': 244, 'min_data_in_leaf': 41, 'extra_trees': True, 'early_stopping_rounds': 36, 'path_smooth': 0.5520181820155607, 'min_gain_to_split': 0.320517550883226}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 19:39:53,948] Trial 362 finished with value: 0.2594581143688298 and parameters: {'num_leaves': 91, 'learning_rate': 0.017133412502208414, 'feature_fraction': 0.9686591896919144, 'bagging_fraction': 0.9566500822042323, 'bagging_freq': 8, 'lambda_l1': 4.109194899790549e-07, 'lambda_l2': 3.7576327503410175e-07, 'min_child_samples': 49, 'max_depth': 6, 'max_bin': 256, 'min_data_in_leaf': 50, 'extra_trees': False, 'early_stopping_rounds': 15, 'path_smooth': 0.6164725217240258, 'min_gain_to_split': 0.38697341636157884}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 19:47:39,614] Trial 363 finished with value: 0.22467667491685533 and parameters: {'num_leaves': 93, 'learning_rate': 0.010600038124418081, 'feature_fraction': 0.9264328651086028, 'bagging_fraction': 0.9466574867781515, 'bagging_freq': 1, 'lambda_l1': 0.0011096629021909664, 'lambda_l2': 1.8237531048352056e-07, 'min_child_samples': 47, 'max_depth': 8, 'max_bin': 266, 'min_data_in_leaf': 59, 'extra_trees': True, 'early_stopping_rounds': 13, 'path_smooth': 0.3705545467706795, 'min_gain_to_split': 0.3042202862378875}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 19:52:25,277] Trial 364 finished with value: 0.22408800620061808 and parameters: {'num_leaves': 75, 'learning_rate': 0.01168667894489555, 'feature_fraction': 0.8029858372107098, 'bagging_fraction': 0.9615398662191377, 'bagging_freq': 8, 'lambda_l1': 2.632878558380043e-07, 'lambda_l2': 3.713188467151035e-08, 'min_child_samples': 48, 'max_depth': 7, 'max_bin': 205, 'min_data_in_leaf': 43, 'extra_trees': True, 'early_stopping_rounds': 14, 'path_smooth': 0.27502359556042105, 'min_gain_to_split': 0.3706530560938088}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 19:55:18,718] Trial 365 finished with value: 0.22271381955737754 and parameters: {'num_leaves': 94, 'learning_rate': 0.02592836682907284, 'feature_fraction': 0.9789572766250033, 'bagging_fraction': 0.9418344097572162, 'bagging_freq': 8, 'lambda_l1': 6.726140002977068, 'lambda_l2': 6.343554398503898e-08, 'min_child_samples': 33, 'max_depth': 8, 'max_bin': 233, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 49, 'path_smooth': 0.2987286694448629, 'min_gain_to_split': 0.3583096185243151}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 19:59:46,907] Trial 366 finished with value: 0.223764842412028 and parameters: {'num_leaves': 39, 'learning_rate': 0.013804232868920756, 'feature_fraction': 0.8620646654148423, 'bagging_fraction': 0.972141768332623, 'bagging_freq': 8, 'lambda_l1': 2.1192443997605087e-06, 'lambda_l2': 2.5380057343669998e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 248, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 15, 'path_smooth': 0.6460870778366473, 'min_gain_to_split': 0.08275680163424073}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 20:12:42,194] Trial 367 finished with value: 0.22375664401428166 and parameters: {'num_leaves': 90, 'learning_rate': 0.011208547837890251, 'feature_fraction': 0.9137375920249886, 'bagging_fraction': 0.951806722647762, 'bagging_freq': 7, 'lambda_l1': 4.970204999636011e-06, 'lambda_l2': 2.3658140906978406e-08, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 454, 'min_data_in_leaf': 40, 'extra_trees': True, 'early_stopping_rounds': 50, 'path_smooth': 0.25268772628421293, 'min_gain_to_split': 0.34636170497521873}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 20:20:37,198] Trial 368 finished with value: 0.22257733271136898 and parameters: {'num_leaves': 94, 'learning_rate': 0.012227296247241976, 'feature_fraction': 0.9908783136652889, 'bagging_fraction': 0.9683203279112805, 'bagging_freq': 8, 'lambda_l1': 1.73166506064834e-07, 'lambda_l2': 4.5436026210743127e-05, 'min_child_samples': 23, 'max_depth': 8, 'max_bin': 240, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 13, 'path_smooth': 0.6730404706588424, 'min_gain_to_split': 0.33008538297192785}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 20:30:08,100] Trial 369 finished with value: 0.22286268011942725 and parameters: {'num_leaves': 88, 'learning_rate': 0.010005976563341571, 'feature_fraction': 0.8786322499699296, 'bagging_fraction': 0.9800281397343025, 'bagging_freq': 10, 'lambda_l1': 0.020627818910602346, 'lambda_l2': 1.2285183637786943e-07, 'min_child_samples': 27, 'max_depth': 8, 'max_bin': 262, 'min_data_in_leaf': 46, 'extra_trees': True, 'early_stopping_rounds': 15, 'path_smooth': 0.32562628222271917, 'min_gain_to_split': 0.17828372000498716}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 20:35:51,420] Trial 370 finished with value: 0.22242889424849305 and parameters: {'num_leaves': 92, 'learning_rate': 0.01292616696786395, 'feature_fraction': 0.8571362767661577, 'bagging_fraction': 0.7768328085327274, 'bagging_freq': 8, 'lambda_l1': 2.7372554094374997e-06, 'lambda_l2': 0.00030177563105053957, 'min_child_samples': 30, 'max_depth': 8, 'max_bin': 215, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.5682091400566549, 'min_gain_to_split': 0.3650031703457962}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 20:42:55,452] Trial 371 finished with value: 0.22172424638821356 and parameters: {'num_leaves': 96, 'learning_rate': 0.014537153965870308, 'feature_fraction': 0.9057026384447178, 'bagging_fraction': 0.927290436216208, 'bagging_freq': 8, 'lambda_l1': 1.6204819989706548e-06, 'lambda_l2': 3.8323376464901206e-08, 'min_child_samples': 46, 'max_depth': 8, 'max_bin': 254, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 49, 'path_smooth': 0.6097150566442273, 'min_gain_to_split': 0.2684416983387711}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 20:52:17,478] Trial 372 finished with value: 0.22448326497297613 and parameters: {'num_leaves': 90, 'learning_rate': 0.011217381056702141, 'feature_fraction': 0.945345318298135, 'bagging_fraction': 0.8250004042723741, 'bagging_freq': 8, 'lambda_l1': 7.571686808977782e-07, 'lambda_l2': 0.0037044130258616814, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 273, 'min_data_in_leaf': 42, 'extra_trees': True, 'early_stopping_rounds': 12, 'path_smooth': 0.5397443776893825, 'min_gain_to_split': 0.041442675429579245}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 20:58:13,875] Trial 373 finished with value: 0.22607460799050574 and parameters: {'num_leaves': 86, 'learning_rate': 0.010625244594431312, 'feature_fraction': 0.6020009306486527, 'bagging_fraction': 0.9413476629131872, 'bagging_freq': 9, 'lambda_l1': 3.825501165565887e-06, 'lambda_l2': 7.158014361426563e-08, 'min_child_samples': 28, 'max_depth': 8, 'max_bin': 231, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 14, 'path_smooth': 0.5840283032228435, 'min_gain_to_split': 0.374717420946513}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 21:04:10,426] Trial 374 finished with value: 0.22279788496313824 and parameters: {'num_leaves': 95, 'learning_rate': 0.01578539491866892, 'feature_fraction': 0.9204709047003156, 'bagging_fraction': 0.9487333092733701, 'bagging_freq': 8, 'lambda_l1': 2.4724780033125723e-05, 'lambda_l2': 2.1670140589443604e-08, 'min_child_samples': 47, 'max_depth': 8, 'max_bin': 246, 'min_data_in_leaf': 45, 'extra_trees': True, 'early_stopping_rounds': 32, 'path_smooth': 0.21913040153992241, 'min_gain_to_split': 0.4171393521838858}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 21:11:16,389] Trial 375 finished with value: 0.2227748701690872 and parameters: {'num_leaves': 83, 'learning_rate': 0.012419756828963232, 'feature_fraction': 0.8872997524750889, 'bagging_fraction': 0.959449916469185, 'bagging_freq': 7, 'lambda_l1': 1.1556303453761358e-05, 'lambda_l2': 0.11639848941415032, 'min_child_samples': 49, 'max_depth': 9, 'max_bin': 254, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.6280346049115738, 'min_gain_to_split': 0.3401695314448565}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 21:16:44,466] Trial 376 finished with value: 0.22931856908077242 and parameters: {'num_leaves': 92, 'learning_rate': 0.013460705518043393, 'feature_fraction': 0.871894218440478, 'bagging_fraction': 0.7211368684474116, 'bagging_freq': 8, 'lambda_l1': 1.0912486225296866e-06, 'lambda_l2': 2.1811459519427924e-07, 'min_child_samples': 50, 'max_depth': 8, 'max_bin': 265, 'min_data_in_leaf': 41, 'extra_trees': True, 'early_stopping_rounds': 13, 'path_smooth': 0.3846614129655027, 'min_gain_to_split': 0.42750055576813506}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 21:23:25,073] Trial 377 finished with value: 0.22189805061470244 and parameters: {'num_leaves': 94, 'learning_rate': 0.011497590264225345, 'feature_fraction': 0.8798971847142816, 'bagging_fraction': 0.9372792929016259, 'bagging_freq': 8, 'lambda_l1': 4.602433269679256e-07, 'lambda_l2': 1.8822699036958264e-08, 'min_child_samples': 46, 'max_depth': 8, 'max_bin': 237, 'min_data_in_leaf': 43, 'extra_trees': True, 'early_stopping_rounds': 14, 'path_smooth': 0.5991833481541786, 'min_gain_to_split': 0.3529078402425737}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 21:29:49,316] Trial 378 finished with value: 0.22205146074659274 and parameters: {'num_leaves': 89, 'learning_rate': 0.010740756697986738, 'feature_fraction': 0.675763197383871, 'bagging_fraction': 0.9531203169411204, 'bagging_freq': 9, 'lambda_l1': 0.00017739449997618094, 'lambda_l2': 2.833379430439115e-08, 'min_child_samples': 47, 'max_depth': 7, 'max_bin': 271, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 50, 'path_smooth': 0.3581452941979062, 'min_gain_to_split': 0.3271309449002449}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 21:32:24,040] Trial 379 finished with value: 0.22407340859545294 and parameters: {'num_leaves': 92, 'learning_rate': 0.0214601393428104, 'feature_fraction': 0.9589764986033195, 'bagging_fraction': 0.9310061376821835, 'bagging_freq': 8, 'lambda_l1': 0.05391004847235187, 'lambda_l2': 0.00014910480829894145, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 225, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 17, 'path_smooth': 0.6334939059941211, 'min_gain_to_split': 0.35603970050464717}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 21:36:31,433] Trial 380 finished with value: 0.22393408764546446 and parameters: {'num_leaves': 95, 'learning_rate': 0.012228738290874789, 'feature_fraction': 0.9336492900840755, 'bagging_fraction': 0.911695282899065, 'bagging_freq': 5, 'lambda_l1': 7.0861268628729895e-06, 'lambda_l2': 5.394529436193169e-08, 'min_child_samples': 31, 'max_depth': 9, 'max_bin': 245, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.49296248333554615, 'min_gain_to_split': 0.3889027400197115}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 21:39:37,928] Trial 381 finished with value: 0.2221902187672858 and parameters: {'num_leaves': 90, 'learning_rate': 0.014749062417194505, 'feature_fraction': 0.8958611068307398, 'bagging_fraction': 0.9644981875529219, 'bagging_freq': 8, 'lambda_l1': 2.0410778811208436e-06, 'lambda_l2': 1.522724403998473e-08, 'min_child_samples': 25, 'max_depth': 8, 'max_bin': 249, 'min_data_in_leaf': 32, 'extra_trees': True, 'early_stopping_rounds': 15, 'path_smooth': 0.5766342320333022, 'min_gain_to_split': 0.3378947849813262}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 21:43:51,476] Trial 382 finished with value: 0.2252058823766998 and parameters: {'num_leaves': 93, 'learning_rate': 0.010011953799359659, 'feature_fraction': 0.9013290719850342, 'bagging_fraction': 0.9443043196935507, 'bagging_freq': 8, 'lambda_l1': 1.1545256822240783e-07, 'lambda_l2': 9.513575323605063e-08, 'min_child_samples': 44, 'max_depth': 8, 'max_bin': 261, 'min_data_in_leaf': 55, 'extra_trees': True, 'early_stopping_rounds': 42, 'path_smooth': 0.6111192605249881, 'min_gain_to_split': 0.3150135435493882}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 21:47:42,661] Trial 383 finished with value: 0.2677271576352699 and parameters: {'num_leaves': 88, 'learning_rate': 0.013073751869748518, 'feature_fraction': 0.8855615525573074, 'bagging_fraction': 0.7003908769914788, 'bagging_freq': 7, 'lambda_l1': 2.1176766719775853e-07, 'lambda_l2': 3.537440232049676e-08, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 193, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 12, 'path_smooth': 0.3440190759478383, 'min_gain_to_split': 0.3671830121039977}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 21:51:00,664] Trial 384 finished with value: 0.22476878842040376 and parameters: {'num_leaves': 96, 'learning_rate': 0.011598711888069489, 'feature_fraction': 0.8736454865182076, 'bagging_fraction': 0.9574674834344084, 'bagging_freq': 8, 'lambda_l1': 4.984332048446487e-06, 'lambda_l2': 1.9568214315619897e-08, 'min_child_samples': 46, 'max_depth': 8, 'max_bin': 237, 'min_data_in_leaf': 40, 'extra_trees': True, 'early_stopping_rounds': 19, 'path_smooth': 0.9905134093907, 'min_gain_to_split': 0.34680082726280176}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 21:54:46,783] Trial 385 finished with value: 0.2219436409047626 and parameters: {'num_leaves': 91, 'learning_rate': 0.013960348643035483, 'feature_fraction': 0.9097461568023782, 'bagging_fraction': 0.9250432255218344, 'bagging_freq': 8, 'lambda_l1': 3.252369033429364e-06, 'lambda_l2': 1.520100296499249e-07, 'min_child_samples': 41, 'max_depth': 10, 'max_bin': 257, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 49, 'path_smooth': 0.6691344481554181, 'min_gain_to_split': 0.12213751235108142}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 21:55:58,542] Trial 386 finished with value: 0.22875025123807693 and parameters: {'num_leaves': 94, 'learning_rate': 0.048621232001909126, 'feature_fraction': 0.9689387957944923, 'bagging_fraction': 0.9383406019015207, 'bagging_freq': 6, 'lambda_l1': 5.982809050272393e-07, 'lambda_l2': 5.03482495968739e-08, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 274, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.5582715810354031, 'min_gain_to_split': 0.2851457363138881}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 21:59:07,492] Trial 387 finished with value: 0.22236774859444056 and parameters: {'num_leaves': 99, 'learning_rate': 0.011161661947987345, 'feature_fraction': 0.9455738241113373, 'bagging_fraction': 0.9485725352546627, 'bagging_freq': 8, 'lambda_l1': 0.00034403678263450336, 'lambda_l2': 0.0018314934931083257, 'min_child_samples': 47, 'max_depth': 7, 'max_bin': 253, 'min_data_in_leaf': 41, 'extra_trees': True, 'early_stopping_rounds': 30, 'path_smooth': 0.23644156794477927, 'min_gain_to_split': 0.37261171950022803}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 22:02:11,145] Trial 388 finished with value: 0.22297780871714173 and parameters: {'num_leaves': 92, 'learning_rate': 0.012192266185987103, 'feature_fraction': 0.8480489971450206, 'bagging_fraction': 0.9712677334747751, 'bagging_freq': 9, 'lambda_l1': 1.192366175093559e-06, 'lambda_l2': 0.04006867145951322, 'min_child_samples': 49, 'max_depth': 8, 'max_bin': 241, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 14, 'path_smooth': 0.6430245191028139, 'min_gain_to_split': 0.35940424711888896}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 22:04:51,451] Trial 389 finished with value: 0.22340650704485063 and parameters: {'num_leaves': 97, 'learning_rate': 0.010749823606655695, 'feature_fraction': 0.8889945124144913, 'bagging_fraction': 0.9441682608095634, 'bagging_freq': 7, 'lambda_l1': 0.010297162078708465, 'lambda_l2': 7.038811599737608e-07, 'min_child_samples': 30, 'max_depth': 6, 'max_bin': 265, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 50, 'path_smooth': 0.4438511040661979, 'min_gain_to_split': 0.32705168292173015}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 22:06:38,413] Trial 390 finished with value: 0.22942214377160647 and parameters: {'num_leaves': 27, 'learning_rate': 0.01645606054730679, 'feature_fraction': 0.8674568719354465, 'bagging_fraction': 0.9526169464029773, 'bagging_freq': 8, 'lambda_l1': 1.280460098560757e-05, 'lambda_l2': 2.7771236445310942e-08, 'min_child_samples': 46, 'max_depth': 8, 'max_bin': 248, 'min_data_in_leaf': 43, 'extra_trees': True, 'early_stopping_rounds': 10, 'path_smooth': 0.4035193914945613, 'min_gain_to_split': 0.3840495598061466}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 22:09:08,935] Trial 391 finished with value: 0.22374693666748668 and parameters: {'num_leaves': 95, 'learning_rate': 0.012981844948009073, 'feature_fraction': 0.7038304289116994, 'bagging_fraction': 0.9346359548431293, 'bagging_freq': 8, 'lambda_l1': 7.636007526355112e-06, 'lambda_l2': 0.0013946878579502752, 'min_child_samples': 33, 'max_depth': 8, 'max_bin': 228, 'min_data_in_leaf': 31, 'extra_trees': True, 'early_stopping_rounds': 12, 'path_smooth': 0.3135582388111633, 'min_gain_to_split': 0.16264120177063865}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 22:12:19,494] Trial 392 finished with value: 0.22242883194333068 and parameters: {'num_leaves': 91, 'learning_rate': 0.011505503096620849, 'feature_fraction': 0.9234300590736471, 'bagging_fraction': 0.846642397415152, 'bagging_freq': 8, 'lambda_l1': 7.359165673208333e-08, 'lambda_l2': 1.4545854508107511e-08, 'min_child_samples': 45, 'max_depth': 8, 'max_bin': 217, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 46, 'path_smooth': 0.5927501004778883, 'min_gain_to_split': 0.4028108914568533}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 22:15:21,606] Trial 393 finished with value: 0.2239809726876178 and parameters: {'num_leaves': 86, 'learning_rate': 0.015214729654439466, 'feature_fraction': 0.9820604250222288, 'bagging_fraction': 0.9213959899503079, 'bagging_freq': 10, 'lambda_l1': 2.03390119188697e-06, 'lambda_l2': 2.921831687050667e-07, 'min_child_samples': 29, 'max_depth': 8, 'max_bin': 257, 'min_data_in_leaf': 41, 'extra_trees': True, 'early_stopping_rounds': 13, 'path_smooth': 0.5351877912269816, 'min_gain_to_split': 0.3461322900912302}. Best is trial 207 with value: 0.2196942896096191.

Mejor trial hasta ahora: TFE=0.219694, Parámetros={'num_leaves': 92, 'learning_rate': 0.01386963089377729, 'feature_fraction': 0.8940947144735888, 'bagging_fraction': 0.9523569272327731, 'bagging_freq': 8, 'lambda_l1': 2.1344360901466714e-07, 'lambda_l2': 2.8012033091033457e-08, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 285, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6283689452411402, 'min_gain_to_split': 0.35434113705079}

[I 2025-07-16 22:19:50,803] Trial 394 finished with value: 0.2196119759319271 and parameters: {'num_leaves': 89, 'learning_rate': 0.01056655024145398, 'feature_fraction': 0.9998858161624768, 'bagging_fraction': 0.9642216648647404, 'bagging_freq': 9, 'lambda_l1': 3.646128475098312e-07, 'lambda_l2': 7.529660029948819e-08, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.6196653716445973, 'min_gain_to_split': 0.054318368500530116}. Best is trial 394 with value: 0.2196119759319271.

Mejor trial hasta ahora: TFE=0.219612, Parámetros={'num_leaves': 89, 'learning_rate': 0.01056655024145398, 'feature_fraction': 0.9998858161624768, 'bagging_fraction': 0.9642216648647404, 'bagging_freq': 9, 'lambda_l1': 3.646128475098312e-07, 'lambda_l2': 7.529660029948819e-08, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.6196653716445973, 'min_gain_to_split': 0.054318368500530116}

[I 2025-07-16 22:23:43,067] Trial 395 finished with value: 0.22364177133581148 and parameters: {'num_leaves': 65, 'learning_rate': 0.010334978107867128, 'feature_fraction': 0.9901485059233182, 'bagging_fraction': 0.9821636188174471, 'bagging_freq': 10, 'lambda_l1': 2.7370856447919053e-07, 'lambda_l2': 9.730250430588813e-08, 'min_child_samples': 50, 'max_depth': 8, 'max_bin': 232, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.624731893302211, 'min_gain_to_split': 0.07343271394219664}. Best is trial 394 with value: 0.2196119759319271.

Mejor trial hasta ahora: TFE=0.219612, Parámetros={'num_leaves': 89, 'learning_rate': 0.01056655024145398, 'feature_fraction': 0.9998858161624768, 'bagging_fraction': 0.9642216648647404, 'bagging_freq': 9, 'lambda_l1': 3.646128475098312e-07, 'lambda_l2': 7.529660029948819e-08, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.6196653716445973, 'min_gain_to_split': 0.054318368500530116}

[I 2025-07-16 22:28:14,756] Trial 396 finished with value: 0.22138751000909762 and parameters: {'num_leaves': 88, 'learning_rate': 0.01051427970509412, 'feature_fraction': 0.9845610443301518, 'bagging_fraction': 0.9661205914195727, 'bagging_freq': 9, 'lambda_l1': 4.4674582983663843e-07, 'lambda_l2': 5.891057725977334e-08, 'min_child_samples': 49, 'max_depth': 9, 'max_bin': 239, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.6557963936271498, 'min_gain_to_split': 0.06276284974408365}. Best is trial 394 with value: 0.2196119759319271.

Mejor trial hasta ahora: TFE=0.219612, Parámetros={'num_leaves': 89, 'learning_rate': 0.01056655024145398, 'feature_fraction': 0.9998858161624768, 'bagging_fraction': 0.9642216648647404, 'bagging_freq': 9, 'lambda_l1': 3.646128475098312e-07, 'lambda_l2': 7.529660029948819e-08, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.6196653716445973, 'min_gain_to_split': 0.054318368500530116}

[I 2025-07-16 22:29:06,524] Trial 397 finished with value: 0.22680731711147736 and parameters: {'num_leaves': 84, 'learning_rate': 0.05975572130715802, 'feature_fraction': 0.9946768184810498, 'bagging_fraction': 0.9775512535008805, 'bagging_freq': 9, 'lambda_l1': 1.5272557032937952e-07, 'lambda_l2': 8.135532341312203e-08, 'min_child_samples': 15, 'max_depth': 8, 'max_bin': 175, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 49, 'path_smooth': 0.6397133138717533, 'min_gain_to_split': 0.03909267067009364}. Best is trial 394 with value: 0.2196119759319271.

Mejor trial hasta ahora: TFE=0.219612, Parámetros={'num_leaves': 89, 'learning_rate': 0.01056655024145398, 'feature_fraction': 0.9998858161624768, 'bagging_fraction': 0.9642216648647404, 'bagging_freq': 9, 'lambda_l1': 3.646128475098312e-07, 'lambda_l2': 7.529660029948819e-08, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.6196653716445973, 'min_gain_to_split': 0.054318368500530116}

[I 2025-07-16 22:32:56,619] Trial 398 finished with value: 0.2210416699564682 and parameters: {'num_leaves': 88, 'learning_rate': 0.011096908878036497, 'feature_fraction': 0.9937399736640247, 'bagging_fraction': 0.9586595419387175, 'bagging_freq': 10, 'lambda_l1': 3.4140448831738753e-07, 'lambda_l2': 1.4991125216861058e-07, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.61310024327707, 'min_gain_to_split': 0.0496380486602025}. Best is trial 394 with value: 0.2196119759319271.

Mejor trial hasta ahora: TFE=0.219612, Parámetros={'num_leaves': 89, 'learning_rate': 0.01056655024145398, 'feature_fraction': 0.9998858161624768, 'bagging_fraction': 0.9642216648647404, 'bagging_freq': 9, 'lambda_l1': 3.646128475098312e-07, 'lambda_l2': 7.529660029948819e-08, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.6196653716445973, 'min_gain_to_split': 0.054318368500530116}

[I 2025-07-16 22:36:57,333] Trial 399 finished with value: 0.2221228751187981 and parameters: {'num_leaves': 90, 'learning_rate': 0.010032974116371258, 'feature_fraction': 0.9976795553044326, 'bagging_fraction': 0.9695300107002881, 'bagging_freq': 9, 'lambda_l1': 2.2684964345640742e-07, 'lambda_l2': 4.334797970199665e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 289, 'min_data_in_leaf': 33, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.7146286500629567, 'min_gain_to_split': 0.059429168543322905}. Best is trial 394 with value: 0.2196119759319271.

Mejor trial hasta ahora: TFE=0.219612, Parámetros={'num_leaves': 89, 'learning_rate': 0.01056655024145398, 'feature_fraction': 0.9998858161624768, 'bagging_fraction': 0.9642216648647404, 'bagging_freq': 9, 'lambda_l1': 3.646128475098312e-07, 'lambda_l2': 7.529660029948819e-08, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.6196653716445973, 'min_gain_to_split': 0.054318368500530116}

[I 2025-07-16 22:39:09,324] Trial 400 finished with value: 0.22526729529929543 and parameters: {'num_leaves': 34, 'learning_rate': 0.012265221125589237, 'feature_fraction': 0.6286388575359907, 'bagging_fraction': 0.964390813056832, 'bagging_freq': 9, 'lambda_l1': 6.471403049359547e-07, 'lambda_l2': 0.00019559249401279418, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 221, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 39, 'path_smooth': 0.2600427377987683, 'min_gain_to_split': 0.04977119122628859}. Best is trial 394 with value: 0.2196119759319271.

Mejor trial hasta ahora: TFE=0.219612, Parámetros={'num_leaves': 89, 'learning_rate': 0.01056655024145398, 'feature_fraction': 0.9998858161624768, 'bagging_fraction': 0.9642216648647404, 'bagging_freq': 9, 'lambda_l1': 3.646128475098312e-07, 'lambda_l2': 7.529660029948819e-08, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.6196653716445973, 'min_gain_to_split': 0.054318368500530116}

[I 2025-07-16 22:44:32,033] Trial 401 finished with value: 0.2704968742801223 and parameters: {'num_leaves': 86, 'learning_rate': 0.013831206349053693, 'feature_fraction': 0.9995430470131175, 'bagging_fraction': 0.9741468869182577, 'bagging_freq': 7, 'lambda_l1': 4.2309066609886266e-07, 'lambda_l2': 4.302874354868528e-08, 'min_child_samples': 23, 'max_depth': 8, 'max_bin': 248, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 50, 'path_smooth': 0.69124406844264, 'min_gain_to_split': 0.07292973943554794}. Best is trial 394 with value: 0.2196119759319271.

Mejor trial hasta ahora: TFE=0.219612, Parámetros={'num_leaves': 89, 'learning_rate': 0.01056655024145398, 'feature_fraction': 0.9998858161624768, 'bagging_fraction': 0.9642216648647404, 'bagging_freq': 9, 'lambda_l1': 3.646128475098312e-07, 'lambda_l2': 7.529660029948819e-08, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.6196653716445973, 'min_gain_to_split': 0.054318368500530116}

[I 2025-07-16 22:47:37,495] Trial 402 finished with value: 0.22262096578803864 and parameters: {'num_leaves': 89, 'learning_rate': 0.011743021230857376, 'feature_fraction': 0.882373046912414, 'bagging_fraction': 0.9606588453241335, 'bagging_freq': 3, 'lambda_l1': 1.9784054284520989, 'lambda_l2': 1.0550485790946591e-07, 'min_child_samples': 49, 'max_depth': 8, 'max_bin': 234, 'min_data_in_leaf': 32, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.3669089664310563, 'min_gain_to_split': 0.09000044146543737}. Best is trial 394 with value: 0.2196119759319271.

Mejor trial hasta ahora: TFE=0.219612, Parámetros={'num_leaves': 89, 'learning_rate': 0.01056655024145398, 'feature_fraction': 0.9998858161624768, 'bagging_fraction': 0.9642216648647404, 'bagging_freq': 9, 'lambda_l1': 3.646128475098312e-07, 'lambda_l2': 7.529660029948819e-08, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.6196653716445973, 'min_gain_to_split': 0.054318368500530116}

[I 2025-07-16 22:50:47,451] Trial 403 finished with value: 0.22333663042947527 and parameters: {'num_leaves': 78, 'learning_rate': 0.012714133089715522, 'feature_fraction': 0.9878542594096918, 'bagging_fraction': 0.9309493691404681, 'bagging_freq': 8, 'lambda_l1': 1.3033597476521705e-07, 'lambda_l2': 0.013224093787342383, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 210, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 49, 'path_smooth': 0.6503300221375179, 'min_gain_to_split': 0.2943648982454834}. Best is trial 394 with value: 0.2196119759319271.

Mejor trial hasta ahora: TFE=0.219612, Parámetros={'num_leaves': 89, 'learning_rate': 0.01056655024145398, 'feature_fraction': 0.9998858161624768, 'bagging_fraction': 0.9642216648647404, 'bagging_freq': 9, 'lambda_l1': 3.646128475098312e-07, 'lambda_l2': 7.529660029948819e-08, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.6196653716445973, 'min_gain_to_split': 0.054318368500530116}

[I 2025-07-16 22:55:08,482] Trial 404 finished with value: 0.22391855381313483 and parameters: {'num_leaves': 91, 'learning_rate': 0.01076064299582464, 'feature_fraction': 0.9737387144465761, 'bagging_fraction': 0.9552125054884693, 'bagging_freq': 8, 'lambda_l1': 0.08586922201048618, 'lambda_l2': 6.866780258605467e-08, 'min_child_samples': 47, 'max_depth': 9, 'max_bin': 227, 'min_data_in_leaf': 30, 'extra_trees': True, 'early_stopping_rounds': 46, 'path_smooth': 0.286511688649038, 'min_gain_to_split': 0.2225782095708323}. Best is trial 394 with value: 0.2196119759319271.

Mejor trial hasta ahora: TFE=0.219612, Parámetros={'num_leaves': 89, 'learning_rate': 0.01056655024145398, 'feature_fraction': 0.9998858161624768, 'bagging_fraction': 0.9642216648647404, 'bagging_freq': 9, 'lambda_l1': 3.646128475098312e-07, 'lambda_l2': 7.529660029948819e-08, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.6196653716445973, 'min_gain_to_split': 0.054318368500530116}

[I 2025-07-16 22:58:27,568] Trial 405 finished with value: 0.22287214219909163 and parameters: {'num_leaves': 100, 'learning_rate': 0.014344161019088404, 'feature_fraction': 0.8943269679804199, 'bagging_fraction': 0.9399192966834237, 'bagging_freq': 9, 'lambda_l1': 8.595149307896591e-05, 'lambda_l2': 1.3377951967175403e-06, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 304, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.6072565944401956, 'min_gain_to_split': 0.3928049410109095}. Best is trial 394 with value: 0.2196119759319271.

Mejor trial hasta ahora: TFE=0.219612, Parámetros={'num_leaves': 89, 'learning_rate': 0.01056655024145398, 'feature_fraction': 0.9998858161624768, 'bagging_fraction': 0.9642216648647404, 'bagging_freq': 9, 'lambda_l1': 3.646128475098312e-07, 'lambda_l2': 7.529660029948819e-08, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.6196653716445973, 'min_gain_to_split': 0.054318368500530116}

[I 2025-07-16 23:02:14,300] Trial 406 finished with value: 0.2223884984074263 and parameters: {'num_leaves': 93, 'learning_rate': 0.011295982679467555, 'feature_fraction': 0.8763872612829271, 'bagging_fraction': 0.9487534784454345, 'bagging_freq': 6, 'lambda_l1': 8.027220586359162e-07, 'lambda_l2': 1.3025722330942223e-05, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 277, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 17, 'path_smooth': 0.21630785991774917, 'min_gain_to_split': 0.3751416468226821}. Best is trial 394 with value: 0.2196119759319271.

Mejor trial hasta ahora: TFE=0.219612, Parámetros={'num_leaves': 89, 'learning_rate': 0.01056655024145398, 'feature_fraction': 0.9998858161624768, 'bagging_fraction': 0.9642216648647404, 'bagging_freq': 9, 'lambda_l1': 3.646128475098312e-07, 'lambda_l2': 7.529660029948819e-08, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.6196653716445973, 'min_gain_to_split': 0.054318368500530116}

[I 2025-07-16 23:04:44,474] Trial 407 finished with value: 0.2228167985858212 and parameters: {'num_leaves': 71, 'learning_rate': 0.01737385371066924, 'feature_fraction': 0.9006644428388499, 'bagging_fraction': 0.9626896102183946, 'bagging_freq': 7, 'lambda_l1': 2.7979817881713185e-07, 'lambda_l2': 0.0005659519899087363, 'min_child_samples': 30, 'max_depth': 8, 'max_bin': 267, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.6289195120339737, 'min_gain_to_split': 0.24695343758383803}. Best is trial 394 with value: 0.2196119759319271.

Mejor trial hasta ahora: TFE=0.219612, Parámetros={'num_leaves': 89, 'learning_rate': 0.01056655024145398, 'feature_fraction': 0.9998858161624768, 'bagging_fraction': 0.9642216648647404, 'bagging_freq': 9, 'lambda_l1': 3.646128475098312e-07, 'lambda_l2': 7.529660029948819e-08, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.6196653716445973, 'min_gain_to_split': 0.054318368500530116}

[I 2025-07-16 23:07:36,406] Trial 408 finished with value: 0.2239160276752597 and parameters: {'num_leaves': 89, 'learning_rate': 0.013256556488315634, 'feature_fraction': 0.8880534640473184, 'bagging_fraction': 0.8065268065547925, 'bagging_freq': 10, 'lambda_l1': 1.6584983388857876e-05, 'lambda_l2': 4.5775168065374123e-07, 'min_child_samples': 50, 'max_depth': 8, 'max_bin': 245, 'min_data_in_leaf': 40, 'extra_trees': True, 'early_stopping_rounds': 33, 'path_smooth': 0.16210269199735788, 'min_gain_to_split': 0.41377506281908505}. Best is trial 394 with value: 0.2196119759319271.

Mejor trial hasta ahora: TFE=0.219612, Parámetros={'num_leaves': 89, 'learning_rate': 0.01056655024145398, 'feature_fraction': 0.9998858161624768, 'bagging_fraction': 0.9642216648647404, 'bagging_freq': 9, 'lambda_l1': 3.646128475098312e-07, 'lambda_l2': 7.529660029948819e-08, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.6196653716445973, 'min_gain_to_split': 0.054318368500530116}

[I 2025-07-16 23:10:53,054] Trial 409 finished with value: 0.22422282877067526 and parameters: {'num_leaves': 92, 'learning_rate': 0.012127735506418354, 'feature_fraction': 0.8638943369193165, 'bagging_fraction': 0.9373372456486292, 'bagging_freq': 8, 'lambda_l1': 9.95101887503158e-07, 'lambda_l2': 3.82454752592639e-08, 'min_child_samples': 47, 'max_depth': 8, 'max_bin': 253, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.3289628061835747, 'min_gain_to_split': 0.36486720928448024}. Best is trial 394 with value: 0.2196119759319271.

Mejor trial hasta ahora: TFE=0.219612, Parámetros={'num_leaves': 89, 'learning_rate': 0.01056655024145398, 'feature_fraction': 0.9998858161624768, 'bagging_fraction': 0.9642216648647404, 'bagging_freq': 9, 'lambda_l1': 3.646128475098312e-07, 'lambda_l2': 7.529660029948819e-08, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.6196653716445973, 'min_gain_to_split': 0.054318368500530116}

[I 2025-07-16 23:14:01,064] Trial 410 finished with value: 0.2271663597371228 and parameters: {'num_leaves': 96, 'learning_rate': 0.010547947311656578, 'feature_fraction': 0.8815251735800175, 'bagging_fraction': 0.9286719195959464, 'bagging_freq': 8, 'lambda_l1': 4.957649040850367e-06, 'lambda_l2': 2.2491399952664959e-07, 'min_child_samples': 24, 'max_depth': 8, 'max_bin': 156, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 44, 'path_smooth': 0.5685161771816888, 'min_gain_to_split': 0.19117514680368836}. Best is trial 394 with value: 0.2196119759319271.

Mejor trial hasta ahora: TFE=0.219612, Parámetros={'num_leaves': 89, 'learning_rate': 0.01056655024145398, 'feature_fraction': 0.9998858161624768, 'bagging_fraction': 0.9642216648647404, 'bagging_freq': 9, 'lambda_l1': 3.646128475098312e-07, 'lambda_l2': 7.529660029948819e-08, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.6196653716445973, 'min_gain_to_split': 0.054318368500530116}

[I 2025-07-16 23:18:24,180] Trial 411 finished with value: 0.22103214848356 and parameters: {'num_leaves': 98, 'learning_rate': 0.011308768699671668, 'feature_fraction': 0.977906685584795, 'bagging_fraction': 0.9544499397931173, 'bagging_freq': 8, 'lambda_l1': 8.628308928990487e-06, 'lambda_l2': 1.3384098082985413e-07, 'min_child_samples': 49, 'max_depth': 9, 'max_bin': 236, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 49, 'path_smooth': 0.5942938818072143, 'min_gain_to_split': 0.31167380335080846}. Best is trial 394 with value: 0.2196119759319271.

Mejor trial hasta ahora: TFE=0.219612, Parámetros={'num_leaves': 89, 'learning_rate': 0.01056655024145398, 'feature_fraction': 0.9998858161624768, 'bagging_fraction': 0.9642216648647404, 'bagging_freq': 9, 'lambda_l1': 3.646128475098312e-07, 'lambda_l2': 7.529660029948819e-08, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.6196653716445973, 'min_gain_to_split': 0.054318368500530116}

[I 2025-07-16 23:20:46,355] Trial 412 finished with value: 0.22215737049622714 and parameters: {'num_leaves': 87, 'learning_rate': 0.019602258978927797, 'feature_fraction': 0.9995483209442354, 'bagging_fraction': 0.9432713380879413, 'bagging_freq': 7, 'lambda_l1': 0.034289909913906326, 'lambda_l2': 6.672505209187633e-08, 'min_child_samples': 19, 'max_depth': 8, 'max_bin': 263, 'min_data_in_leaf': 32, 'extra_trees': True, 'early_stopping_rounds': 15, 'path_smooth': 0.4247960690250785, 'min_gain_to_split': 0.05460817207532546}. Best is trial 394 with value: 0.2196119759319271.

Mejor trial hasta ahora: TFE=0.219612, Parámetros={'num_leaves': 89, 'learning_rate': 0.01056655024145398, 'feature_fraction': 0.9998858161624768, 'bagging_fraction': 0.9642216648647404, 'bagging_freq': 9, 'lambda_l1': 3.646128475098312e-07, 'lambda_l2': 7.529660029948819e-08, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.6196653716445973, 'min_gain_to_split': 0.054318368500530116}

[I 2025-07-16 23:23:44,139] Trial 413 finished with value: 0.22379920483638438 and parameters: {'num_leaves': 93, 'learning_rate': 0.015306621152207598, 'feature_fraction': 0.8926118137946651, 'bagging_fraction': 0.9711624186451362, 'bagging_freq': 5, 'lambda_l1': 3.0181890225445235e-06, 'lambda_l2': 2.7238705277925494e-08, 'min_child_samples': 48, 'max_depth': 7, 'max_bin': 432, 'min_data_in_leaf': 41, 'extra_trees': True, 'early_stopping_rounds': 50, 'path_smooth': 0.6214541906200239, 'min_gain_to_split': 0.3511542426192699}. Best is trial 394 with value: 0.2196119759319271.

Mejor trial hasta ahora: TFE=0.219612, Parámetros={'num_leaves': 89, 'learning_rate': 0.01056655024145398, 'feature_fraction': 0.9998858161624768, 'bagging_fraction': 0.9642216648647404, 'bagging_freq': 9, 'lambda_l1': 3.646128475098312e-07, 'lambda_l2': 7.529660029948819e-08, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.6196653716445973, 'min_gain_to_split': 0.054318368500530116}

[I 2025-07-16 23:27:30,818] Trial 414 finished with value: 0.22341933407850717 and parameters: {'num_leaves': 90, 'learning_rate': 0.012736466661228388, 'feature_fraction': 0.9067843683441922, 'bagging_fraction': 0.9168473722191215, 'bagging_freq': 8, 'lambda_l1': 1.4409276802725507e-06, 'lambda_l2': 8.16132497022667e-06, 'min_child_samples': 47, 'max_depth': 8, 'max_bin': 327, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.4592495622861007, 'min_gain_to_split': 0.38150734621846955}. Best is trial 394 with value: 0.2196119759319271.

Mejor trial hasta ahora: TFE=0.219612, Parámetros={'num_leaves': 89, 'learning_rate': 0.01056655024145398, 'feature_fraction': 0.9998858161624768, 'bagging_fraction': 0.9642216648647404, 'bagging_freq': 9, 'lambda_l1': 3.646128475098312e-07, 'lambda_l2': 7.529660029948819e-08, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.6196653716445973, 'min_gain_to_split': 0.054318368500530116}

[I 2025-07-16 23:30:57,994] Trial 415 finished with value: 0.21891901764809552 and parameters: {'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-16 23:34:21,810] Trial 416 finished with value: 0.22272202225831542 and parameters: {'num_leaves': 91, 'learning_rate': 0.01179688465822316, 'feature_fraction': 0.8543544197152485, 'bagging_fraction': 0.9769206018670124, 'bagging_freq': 8, 'lambda_l1': 1.997325956613093e-07, 'lambda_l2': 5.874570597516589e-05, 'min_child_samples': 49, 'max_depth': 8, 'max_bin': 240, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.3847928302589374, 'min_gain_to_split': 0.3585821750950735}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-16 23:38:17,051] Trial 417 finished with value: 0.22474651148890695 and parameters: {'num_leaves': 94, 'learning_rate': 0.010597667467497355, 'feature_fraction': 0.8738919911906307, 'bagging_fraction': 0.9658246291780628, 'bagging_freq': 9, 'lambda_l1': 3.8732709213872113e-07, 'lambda_l2': 3.0206907607086585e-05, 'min_child_samples': 40, 'max_depth': 8, 'max_bin': 229, 'min_data_in_leaf': 44, 'extra_trees': True, 'early_stopping_rounds': 49, 'path_smooth': 0.40952507739516, 'min_gain_to_split': 0.3349346286747382}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-16 23:42:17,783] Trial 418 finished with value: 0.22590410935306915 and parameters: {'num_leaves': 98, 'learning_rate': 0.010983365983627483, 'feature_fraction': 0.8138452651187349, 'bagging_fraction': 0.9847604302547026, 'bagging_freq': 7, 'lambda_l1': 8.745227267900465e-07, 'lambda_l2': 0.0001024491996617086, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 222, 'min_data_in_leaf': 53, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.3804741145620821, 'min_gain_to_split': 0.11488312388507776}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-16 23:46:33,169] Trial 419 finished with value: 0.23732117146685247 and parameters: {'num_leaves': 96, 'learning_rate': 0.0101204460457747, 'feature_fraction': 0.8669484703036617, 'bagging_fraction': 0.9352464471263786, 'bagging_freq': 8, 'lambda_l1': 4.079499850519631e-06, 'lambda_l2': 7.692158241682731e-05, 'min_child_samples': 34, 'max_depth': 8, 'max_bin': 243, 'min_data_in_leaf': 92, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.3673268666331321, 'min_gain_to_split': 0.36336698289772584}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-16 23:51:09,865] Trial 420 finished with value: 0.22374099320251548 and parameters: {'num_leaves': 89, 'learning_rate': 0.012050086790841115, 'feature_fraction': 0.8598415565691009, 'bagging_fraction': 0.9609438220153184, 'bagging_freq': 8, 'lambda_l1': 6.133344990651888e-07, 'lambda_l2': 1.046869398186548e-08, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 485, 'min_data_in_leaf': 40, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.6615273306587245, 'min_gain_to_split': 0.14617670911185046}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-16 23:54:56,501] Trial 421 finished with value: 0.22214582197036847 and parameters: {'num_leaves': 92, 'learning_rate': 0.011304077526869698, 'feature_fraction': 0.8750226776121266, 'bagging_fraction': 0.9489841348790723, 'bagging_freq': 8, 'lambda_l1': 1.0580862581245986e-07, 'lambda_l2': 5.791741545496253e-05, 'min_child_samples': 29, 'max_depth': 9, 'max_bin': 233, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 50, 'path_smooth': 0.3431477430918891, 'min_gain_to_split': 0.34987728209430097}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-16 23:59:55,239] Trial 422 finished with value: 0.2857177137189768 and parameters: {'num_leaves': 56, 'learning_rate': 0.0123247071791545, 'feature_fraction': 0.9629902011068975, 'bagging_fraction': 0.9233051553337623, 'bagging_freq': 8, 'lambda_l1': 6.045058819736301e-06, 'lambda_l2': 2.2033549845215132e-05, 'min_child_samples': 27, 'max_depth': 8, 'max_bin': 250, 'min_data_in_leaf': 30, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.39054470441017936, 'min_gain_to_split': 0.3755355837686254}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 00:03:35,469] Trial 423 finished with value: 0.2224174011716976 and parameters: {'num_leaves': 93, 'learning_rate': 0.010576259554139737, 'feature_fraction': 0.8800668488492357, 'bagging_fraction': 0.9446891097356022, 'bagging_freq': 9, 'lambda_l1': 3.4640575836715004e-07, 'lambda_l2': 0.00011589556817777127, 'min_child_samples': 46, 'max_depth': 8, 'max_bin': 239, 'min_data_in_leaf': 33, 'extra_trees': True, 'early_stopping_rounds': 14, 'path_smooth': 0.34609930963363494, 'min_gain_to_split': 0.3392455271247036}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 00:06:53,308] Trial 424 finished with value: 0.2226589462715316 and parameters: {'num_leaves': 96, 'learning_rate': 0.011464597069558836, 'feature_fraction': 0.9518011428490284, 'bagging_fraction': 0.968681216741848, 'bagging_freq': 8, 'lambda_l1': 0.5767096442773072, 'lambda_l2': 4.4747217584767556e-05, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 200, 'min_data_in_leaf': 42, 'extra_trees': True, 'early_stopping_rounds': 49, 'path_smooth': 0.4098639351653076, 'min_gain_to_split': 0.4045412821486498}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 00:09:24,401] Trial 425 finished with value: 0.22374809825652608 and parameters: {'num_leaves': 100, 'learning_rate': 0.013630294111715834, 'feature_fraction': 0.8990562400971105, 'bagging_fraction': 0.9573921159213258, 'bagging_freq': 5, 'lambda_l1': 2.314498182002102e-06, 'lambda_l2': 0.00022946909987368196, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 251, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.30285684295739473, 'min_gain_to_split': 0.03526435458153725}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 00:10:34,525] Trial 426 finished with value: 0.22751358254405254 and parameters: {'num_leaves': 90, 'learning_rate': 0.04274954462006632, 'feature_fraction': 0.7488732556553049, 'bagging_fraction': 0.9310105593428677, 'bagging_freq': 8, 'lambda_l1': 1.3163541102957276e-06, 'lambda_l2': 3.376828471331147e-05, 'min_child_samples': 47, 'max_depth': 10, 'max_bin': 229, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 15, 'path_smooth': 0.24351710704652316, 'min_gain_to_split': 0.3536662987571526}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 00:13:34,026] Trial 427 finished with value: 0.22292185755334235 and parameters: {'num_leaves': 87, 'learning_rate': 0.012621318358461852, 'feature_fraction': 0.8689801046921847, 'bagging_fraction': 0.7471050247630815, 'bagging_freq': 8, 'lambda_l1': 1.673127563584547e-07, 'lambda_l2': 1.6979193124406923e-08, 'min_child_samples': 22, 'max_depth': 8, 'max_bin': 245, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 49, 'path_smooth': 0.2684207740149043, 'min_gain_to_split': 0.36742890362701763}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 00:17:46,918] Trial 428 finished with value: 0.2235902517945124 and parameters: {'num_leaves': 51, 'learning_rate': 0.010022885701376294, 'feature_fraction': 0.9870796101532949, 'bagging_fraction': 0.9391380607735536, 'bagging_freq': 4, 'lambda_l1': 5.262652708003046e-07, 'lambda_l2': 2.51440607821512e-08, 'min_child_samples': 47, 'max_depth': 8, 'max_bin': 292, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 45, 'path_smooth': 0.3559871070192121, 'min_gain_to_split': 0.387899615956706}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 00:21:08,647] Trial 429 finished with value: 0.2212878671250101 and parameters: {'num_leaves': 85, 'learning_rate': 0.011778719648718504, 'feature_fraction': 0.8852806410918385, 'bagging_fraction': 0.9527298581700895, 'bagging_freq': 8, 'lambda_l1': 1.0666256572974066e-05, 'lambda_l2': 1.679503990480786e-05, 'min_child_samples': 50, 'max_depth': 8, 'max_bin': 257, 'min_data_in_leaf': 41, 'extra_trees': True, 'early_stopping_rounds': 17, 'path_smooth': 0.22881501603043314, 'min_gain_to_split': 0.3427426722622566}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 00:23:17,119] Trial 430 finished with value: 0.22491952047165514 and parameters: {'num_leaves': 95, 'learning_rate': 0.010945916302322244, 'feature_fraction': 0.892101910909549, 'bagging_fraction': 0.9617850420676831, 'bagging_freq': 7, 'lambda_l1': 0.000661798909410104, 'lambda_l2': 1.8452834622837348e-07, 'min_child_samples': 32, 'max_depth': 5, 'max_bin': 272, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 14, 'path_smooth': 0.1921909075915752, 'min_gain_to_split': 0.06440760026547081}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 00:26:49,679] Trial 431 finished with value: 0.22323659766119563 and parameters: {'num_leaves': 91, 'learning_rate': 0.014151425288360569, 'feature_fraction': 0.9122940051159716, 'bagging_fraction': 0.943816847510168, 'bagging_freq': 8, 'lambda_l1': 2.86008785370087e-06, 'lambda_l2': 1.984841208504914e-08, 'min_child_samples': 37, 'max_depth': 8, 'max_bin': 315, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.6785451538488279, 'min_gain_to_split': 0.09991544499844696}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 00:31:57,922] Trial 432 finished with value: 0.22411234253999837 and parameters: {'num_leaves': 93, 'learning_rate': 0.012998503300585548, 'feature_fraction': 0.9738897321293115, 'bagging_fraction': 0.9501189181797633, 'bagging_freq': 7, 'lambda_l1': 1.7881138152808457e-06, 'lambda_l2': 0.004493319539835752, 'min_child_samples': 30, 'max_depth': 9, 'max_bin': 466, 'min_data_in_leaf': 43, 'extra_trees': True, 'early_stopping_rounds': 46, 'path_smooth': 0.3267385975200175, 'min_gain_to_split': 0.39728189730391}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 00:32:43,876] Trial 433 finished with value: 0.2325690937556837 and parameters: {'num_leaves': 98, 'learning_rate': 0.07589652273463632, 'feature_fraction': 0.8757968755968115, 'bagging_fraction': 0.9342352434535576, 'bagging_freq': 8, 'lambda_l1': 5.104465013815426e-06, 'lambda_l2': 3.5563770121745175e-05, 'min_child_samples': 49, 'max_depth': 8, 'max_bin': 239, 'min_data_in_leaf': 31, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.8568437011920061, 'min_gain_to_split': 0.35827343580818205}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 00:36:33,529] Trial 434 finished with value: 0.22170952183519624 and parameters: {'num_leaves': 88, 'learning_rate': 0.011131484513005973, 'feature_fraction': 0.860326726758238, 'bagging_fraction': 0.9746405540760338, 'bagging_freq': 10, 'lambda_l1': 2.72396613053408e-07, 'lambda_l2': 0.0003916944090328326, 'min_child_samples': 46, 'max_depth': 8, 'max_bin': 281, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 50, 'path_smooth': 0.42241046982417096, 'min_gain_to_split': 0.32950595399892524}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 00:38:09,596] Trial 435 finished with value: 0.23364344572807078 and parameters: {'num_leaves': 92, 'learning_rate': 0.010047409373198767, 'feature_fraction': 0.8843544502432614, 'bagging_fraction': 0.9667895522184101, 'bagging_freq': 9, 'lambda_l1': 1.0938522088115673e-06, 'lambda_l2': 1.0016345240762863e-08, 'min_child_samples': 42, 'max_depth': 3, 'max_bin': 249, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 15, 'path_smooth': 0.6323352313580184, 'min_gain_to_split': 0.377133360380959}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 00:41:25,261] Trial 436 finished with value: 0.2306114490017716 and parameters: {'num_leaves': 94, 'learning_rate': 0.0122272635121405, 'feature_fraction': 0.896350481189984, 'bagging_fraction': 0.9257048630366307, 'bagging_freq': 8, 'lambda_l1': 5.599405870213503e-07, 'lambda_l2': 3.738438464409631e-08, 'min_child_samples': 39, 'max_depth': 8, 'max_bin': 222, 'min_data_in_leaf': 62, 'extra_trees': True, 'early_stopping_rounds': 14, 'path_smooth': 0.5162245034880868, 'min_gain_to_split': 0.13285449714931075}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 00:45:00,828] Trial 437 finished with value: 0.22059096234452102 and parameters: {'num_leaves': 89, 'learning_rate': 0.011536994425941005, 'feature_fraction': 0.8694449986407896, 'bagging_fraction': 0.9570151354285957, 'bagging_freq': 8, 'lambda_l1': 3.0258855119647334e-06, 'lambda_l2': 7.893357628407779e-08, 'min_child_samples': 45, 'max_depth': 8, 'max_bin': 260, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.38801973585603655, 'min_gain_to_split': 0.04776121727931634}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 00:47:45,593] Trial 438 finished with value: 0.2207970808027465 and parameters: {'num_leaves': 87, 'learning_rate': 0.015840227982775092, 'feature_fraction': 0.8466392466596958, 'bagging_fraction': 0.9566067780007277, 'bagging_freq': 8, 'lambda_l1': 0.023814984694828106, 'lambda_l2': 1.0186409720875085e-07, 'min_child_samples': 45, 'max_depth': 8, 'max_bin': 268, 'min_data_in_leaf': 33, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.39118029522610226, 'min_gain_to_split': 0.0826944218045621}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 00:49:59,163] Trial 439 finished with value: 0.22098493306988254 and parameters: {'num_leaves': 84, 'learning_rate': 0.01642129275463733, 'feature_fraction': 0.8527846151584393, 'bagging_fraction': 0.9565413084429443, 'bagging_freq': 8, 'lambda_l1': 0.05049283554994147, 'lambda_l2': 1.2775235589428702e-07, 'min_child_samples': 46, 'max_depth': 7, 'max_bin': 270, 'min_data_in_leaf': 33, 'extra_trees': True, 'early_stopping_rounds': 46, 'path_smooth': 0.39440670269994393, 'min_gain_to_split': 0.06853636699604332}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 00:52:32,531] Trial 440 finished with value: 0.22124174118001183 and parameters: {'num_leaves': 86, 'learning_rate': 0.016640260629124326, 'feature_fraction': 0.848361081330238, 'bagging_fraction': 0.9570503167014105, 'bagging_freq': 8, 'lambda_l1': 0.03760057063140647, 'lambda_l2': 8.185247769665893e-08, 'min_child_samples': 45, 'max_depth': 8, 'max_bin': 279, 'min_data_in_leaf': 29, 'extra_trees': True, 'early_stopping_rounds': 45, 'path_smooth': 0.4356244243465671, 'min_gain_to_split': 0.05502292511897988}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 00:57:01,445] Trial 441 finished with value: 0.2705541354636907 and parameters: {'num_leaves': 87, 'learning_rate': 0.015035837184013716, 'feature_fraction': 0.8358205037080726, 'bagging_fraction': 0.9509409391328809, 'bagging_freq': 8, 'lambda_l1': 0.1227439128732519, 'lambda_l2': 2.159801122486342e-07, 'min_child_samples': 44, 'max_depth': 8, 'max_bin': 264, 'min_data_in_leaf': 31, 'extra_trees': False, 'early_stopping_rounds': 47, 'path_smooth': 0.4049531130000418, 'min_gain_to_split': 0.07793383785489669}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 00:59:28,203] Trial 442 finished with value: 0.2207540185659302 and parameters: {'num_leaves': 88, 'learning_rate': 0.018147473390643626, 'feature_fraction': 0.8631009556759854, 'bagging_fraction': 0.9598904939216185, 'bagging_freq': 8, 'lambda_l1': 0.0233554067480339, 'lambda_l2': 1.1965391118292925e-07, 'min_child_samples': 45, 'max_depth': 8, 'max_bin': 272, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.3951051573274791, 'min_gain_to_split': 0.05378577232747703}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 01:02:15,725] Trial 443 finished with value: 0.22167543281187346 and parameters: {'num_leaves': 85, 'learning_rate': 0.016632731774082806, 'feature_fraction': 0.8596190042537872, 'bagging_fraction': 0.9620702704942435, 'bagging_freq': 8, 'lambda_l1': 0.026269025059697127, 'lambda_l2': 1.0561550263194245e-07, 'min_child_samples': 44, 'max_depth': 8, 'max_bin': 277, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 46, 'path_smooth': 0.4478589293449814, 'min_gain_to_split': 0.05495355132288323}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 01:04:42,295] Trial 444 finished with value: 0.22110848136847663 and parameters: {'num_leaves': 87, 'learning_rate': 0.018340030724315365, 'feature_fraction': 0.8444746048851036, 'bagging_fraction': 0.9692650958021695, 'bagging_freq': 8, 'lambda_l1': 0.07101375394055623, 'lambda_l2': 6.370079831831295e-08, 'min_child_samples': 43, 'max_depth': 8, 'max_bin': 286, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.4181964291542035, 'min_gain_to_split': 0.040185938378075846}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 01:06:58,674] Trial 445 finished with value: 0.2215029276288948 and parameters: {'num_leaves': 86, 'learning_rate': 0.019528397589675384, 'feature_fraction': 0.8638165440710119, 'bagging_fraction': 0.9612349578000501, 'bagging_freq': 8, 'lambda_l1': 0.04422685045580982, 'lambda_l2': 9.091973963029319e-08, 'min_child_samples': 45, 'max_depth': 8, 'max_bin': 269, 'min_data_in_leaf': 32, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.383920247780912, 'min_gain_to_split': 0.08256804997112147}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 01:09:49,388] Trial 446 finished with value: 0.22359468552356182 and parameters: {'num_leaves': 82, 'learning_rate': 0.01722528228554976, 'feature_fraction': 0.8686516727579644, 'bagging_fraction': 0.9537941745947125, 'bagging_freq': 9, 'lambda_l1': 0.015273488011874429, 'lambda_l2': 5.002401916561617e-08, 'min_child_samples': 45, 'max_depth': 9, 'max_bin': 274, 'min_data_in_leaf': 33, 'extra_trees': True, 'early_stopping_rounds': 44, 'path_smooth': 0.39286472655649, 'min_gain_to_split': 0.0467129194224154}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 01:12:21,419] Trial 447 finished with value: 0.22467471928315513 and parameters: {'num_leaves': 88, 'learning_rate': 0.018466207629660836, 'feature_fraction': 0.8741286250069014, 'bagging_fraction': 0.9560857600324708, 'bagging_freq': 8, 'lambda_l1': 0.07430646149944022, 'lambda_l2': 1.3801134832552556e-07, 'min_child_samples': 45, 'max_depth': 8, 'max_bin': 294, 'min_data_in_leaf': 28, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.37951569074597813, 'min_gain_to_split': 0.0519780921076552}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 01:14:56,474] Trial 448 finished with value: 0.22460405566709155 and parameters: {'num_leaves': 89, 'learning_rate': 0.016759826418816254, 'feature_fraction': 0.8549432962523503, 'bagging_fraction': 0.9655823599521168, 'bagging_freq': 8, 'lambda_l1': 0.02270793375335393, 'lambda_l2': 7.437094264234177e-08, 'min_child_samples': 43, 'max_depth': 8, 'max_bin': 263, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.3983186583213914, 'min_gain_to_split': 0.06599585396898688}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 01:17:14,870] Trial 449 finished with value: 0.22333698792495515 and parameters: {'num_leaves': 89, 'learning_rate': 0.02150093716339922, 'feature_fraction': 0.8516565489046122, 'bagging_fraction': 0.9792749122529353, 'bagging_freq': 8, 'lambda_l1': 0.030745588249863367, 'lambda_l2': 4.8119409968780404e-08, 'min_child_samples': 45, 'max_depth': 8, 'max_bin': 283, 'min_data_in_leaf': 31, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.42798319236165083, 'min_gain_to_split': 0.09247628989523837}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 01:19:59,717] Trial 450 finished with value: 0.22442171114859716 and parameters: {'num_leaves': 83, 'learning_rate': 0.018863585926648108, 'feature_fraction': 0.8668570639490187, 'bagging_fraction': 0.9707860381759562, 'bagging_freq': 9, 'lambda_l1': 0.047821730299999934, 'lambda_l2': 1.0932556321689292e-07, 'min_child_samples': 44, 'max_depth': 10, 'max_bin': 267, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 46, 'path_smooth': 0.3676252324573438, 'min_gain_to_split': 0.07003733090890055}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 01:22:39,980] Trial 451 finished with value: 0.22210073927434631 and parameters: {'num_leaves': 90, 'learning_rate': 0.01788692505032573, 'feature_fraction': 0.8441727187894537, 'bagging_fraction': 0.9485978161362213, 'bagging_freq': 8, 'lambda_l1': 9.418711854149151e-08, 'lambda_l2': 6.341998111816336e-08, 'min_child_samples': 44, 'max_depth': 9, 'max_bin': 259, 'min_data_in_leaf': 33, 'extra_trees': True, 'early_stopping_rounds': 45, 'path_smooth': 0.4049983235977648, 'min_gain_to_split': 0.0417219501227896}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 01:25:02,784] Trial 452 finished with value: 0.2221726555422255 and parameters: {'num_leaves': 98, 'learning_rate': 0.01572987249556695, 'feature_fraction': 0.8582712497428763, 'bagging_fraction': 0.958070042011224, 'bagging_freq': 8, 'lambda_l1': 0.02795403404267323, 'lambda_l2': 3.004299940708295e-07, 'min_child_samples': 46, 'max_depth': 7, 'max_bin': 273, 'min_data_in_leaf': 32, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.35484755919609723, 'min_gain_to_split': 0.05837163839854606}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 01:27:43,504] Trial 453 finished with value: 0.22272642275723942 and parameters: {'num_leaves': 90, 'learning_rate': 0.01563634033321128, 'feature_fraction': 0.8650541247033086, 'bagging_fraction': 0.949110898743771, 'bagging_freq': 8, 'lambda_l1': 0.010963149853708432, 'lambda_l2': 3.9083980609560975e-08, 'min_child_samples': 46, 'max_depth': 8, 'max_bin': 259, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 49, 'path_smooth': 0.3792013616531379, 'min_gain_to_split': 0.028844780582309198}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 01:31:03,726] Trial 454 finished with value: 0.22143450625596078 and parameters: {'num_leaves': 100, 'learning_rate': 0.01425871773553928, 'feature_fraction': 0.981858680943409, 'bagging_fraction': 0.9638614861787047, 'bagging_freq': 2, 'lambda_l1': 0.2077272044704402, 'lambda_l2': 1.5203095057499534e-07, 'min_child_samples': 21, 'max_depth': 8, 'max_bin': 286, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 46, 'path_smooth': 0.4189058449722468, 'min_gain_to_split': 0.043292657802951016}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 01:34:02,136] Trial 455 finished with value: 0.22138836103835313 and parameters: {'num_leaves': 85, 'learning_rate': 0.015070551392698028, 'feature_fraction': 0.8715331940208146, 'bagging_fraction': 0.957209190840984, 'bagging_freq': 8, 'lambda_l1': 0.05336437643220475, 'lambda_l2': 9.198978453291964e-08, 'min_child_samples': 46, 'max_depth': 8, 'max_bin': 269, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.3735249521026178, 'min_gain_to_split': 0.060770187425923}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 01:36:39,439] Trial 456 finished with value: 0.22265258308729102 and parameters: {'num_leaves': 88, 'learning_rate': 0.017451068412289914, 'feature_fraction': 0.8599048271838499, 'bagging_fraction': 0.9459574950956378, 'bagging_freq': 8, 'lambda_l1': 0.026636672675322125, 'lambda_l2': 3.381102625844539e-08, 'min_child_samples': 13, 'max_depth': 8, 'max_bin': 279, 'min_data_in_leaf': 30, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.3143668779001391, 'min_gain_to_split': 0.08552854962552278}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 01:38:45,447] Trial 457 finished with value: 0.2218602769080431 and parameters: {'num_leaves': 95, 'learning_rate': 0.01377097597969198, 'feature_fraction': 0.8742670769581579, 'bagging_fraction': 0.9754353541386185, 'bagging_freq': 9, 'lambda_l1': 1.2468129018391283, 'lambda_l2': 5.59227426444709e-08, 'min_child_samples': 47, 'max_depth': 6, 'max_bin': 260, 'min_data_in_leaf': 33, 'extra_trees': True, 'early_stopping_rounds': 49, 'path_smooth': 0.4603291601344188, 'min_gain_to_split': 0.11119715059116217}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 01:39:15,351] Trial 458 finished with value: 0.2440118391321171 and parameters: {'num_leaves': 96, 'learning_rate': 0.18610167039559306, 'feature_fraction': 0.82550768390287, 'bagging_fraction': 0.9521403845088553, 'bagging_freq': 6, 'lambda_l1': 0.013817303104177866, 'lambda_l2': 1.568161403260653e-07, 'min_child_samples': 44, 'max_depth': 8, 'max_bin': 301, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.4789092965884756, 'min_gain_to_split': 0.04563758907150549}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 01:41:42,452] Trial 459 finished with value: 0.2247913533363946 and parameters: {'num_leaves': 90, 'learning_rate': 0.014864139540104406, 'feature_fraction': 0.6922242983789131, 'bagging_fraction': 0.9404708385468635, 'bagging_freq': 8, 'lambda_l1': 0.004273521328731324, 'lambda_l2': 0.008025137711100262, 'min_child_samples': 45, 'max_depth': 8, 'max_bin': 257, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 50, 'path_smooth': 0.35187712704249785, 'min_gain_to_split': 0.07120793410093754}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 01:45:39,642] Trial 460 finished with value: 0.26184695491666526 and parameters: {'num_leaves': 91, 'learning_rate': 0.01996442760157203, 'feature_fraction': 0.7779169489824985, 'bagging_fraction': 0.961675875814612, 'bagging_freq': 8, 'lambda_l1': 0.018422671601494356, 'lambda_l2': 4.5376865985713515, 'min_child_samples': 47, 'max_depth': 10, 'max_bin': 267, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 48, 'path_smooth': 0.21369806772850197, 'min_gain_to_split': 0.03242503850585375}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 01:46:24,409] Trial 461 finished with value: 0.23691766396529026 and parameters: {'num_leaves': 88, 'learning_rate': 0.10761968999079681, 'feature_fraction': 0.9906607670315873, 'bagging_fraction': 0.9857807568944125, 'bagging_freq': 8, 'lambda_l1': 0.08938866191185195, 'lambda_l2': 2.8196061564469955e-08, 'min_child_samples': 23, 'max_depth': 8, 'max_bin': 276, 'min_data_in_leaf': 57, 'extra_trees': True, 'early_stopping_rounds': 46, 'path_smooth': 0.40214612522528564, 'min_gain_to_split': 0.06219549584877219}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 01:49:52,734] Trial 462 finished with value: 0.22255966602783617 and parameters: {'num_leaves': 97, 'learning_rate': 0.01570801463848517, 'feature_fraction': 0.9593827809585055, 'bagging_fraction': 0.968759111814753, 'bagging_freq': 8, 'lambda_l1': 0.0017160517288369154, 'lambda_l2': 8.614149648529582e-08, 'min_child_samples': 18, 'max_depth': 9, 'max_bin': 256, 'min_data_in_leaf': 32, 'extra_trees': True, 'early_stopping_rounds': 49, 'path_smooth': 0.25417498009589456, 'min_gain_to_split': 0.07373247163482857}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 01:53:05,167] Trial 463 finished with value: 0.22008065657066656 and parameters: {'num_leaves': 94, 'learning_rate': 0.01327441660974176, 'feature_fraction': 0.8808123593958072, 'bagging_fraction': 0.941789698376417, 'bagging_freq': 9, 'lambda_l1': 5.8106709880956976e-08, 'lambda_l2': 4.5543859905550224e-08, 'min_child_samples': 45, 'max_depth': 8, 'max_bin': 252, 'min_data_in_leaf': 27, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.28495692088843433, 'min_gain_to_split': 0.05793411783262265}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 01:55:30,187] Trial 464 finished with value: 0.2259303222193419 and parameters: {'num_leaves': 37, 'learning_rate': 0.0136222541625074, 'feature_fraction': 0.8648637922812797, 'bagging_fraction': 0.9523651409579301, 'bagging_freq': 9, 'lambda_l1': 4.644510375321243e-08, 'lambda_l2': 6.486774380239404e-08, 'min_child_samples': 45, 'max_depth': 8, 'max_bin': 263, 'min_data_in_leaf': 26, 'extra_trees': True, 'early_stopping_rounds': 20, 'path_smooth': 0.2815334162487883, 'min_gain_to_split': 0.05489829525271046}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 01:59:01,108] Trial 465 finished with value: 0.2234491351006993 and parameters: {'num_leaves': 93, 'learning_rate': 0.013185365814456517, 'feature_fraction': 0.8802215299794264, 'bagging_fraction': 0.9465192879005424, 'bagging_freq': 9, 'lambda_l1': 7.53176967316528e-08, 'lambda_l2': 2.515112343843134e-08, 'min_child_samples': 43, 'max_depth': 8, 'max_bin': 291, 'min_data_in_leaf': 24, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.2613667474213262, 'min_gain_to_split': 0.024014404980152823}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 02:02:01,144] Trial 466 finished with value: 0.22266439691960893 and parameters: {'num_leaves': 91, 'learning_rate': 0.014022004298528049, 'feature_fraction': 0.8534100532154367, 'bagging_fraction': 0.9578490904766536, 'bagging_freq': 9, 'lambda_l1': 1.6360236248097048e-07, 'lambda_l2': 1.213889008467361e-07, 'min_child_samples': 45, 'max_depth': 8, 'max_bin': 251, 'min_data_in_leaf': 27, 'extra_trees': True, 'early_stopping_rounds': 46, 'path_smooth': 0.3092014446943501, 'min_gain_to_split': 0.048602895605553406}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 02:04:45,091] Trial 467 finished with value: 0.22235666549348432 and parameters: {'num_leaves': 87, 'learning_rate': 0.01605048474802592, 'feature_fraction': 0.8728616755695859, 'bagging_fraction': 0.9440263181210251, 'bagging_freq': 9, 'lambda_l1': 0.00695402459647086, 'lambda_l2': 2.3466885713444115e-07, 'min_child_samples': 16, 'max_depth': 8, 'max_bin': 270, 'min_data_in_leaf': 28, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.24004425890446485, 'min_gain_to_split': 0.038304262245991864}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 02:08:08,657] Trial 468 finished with value: 0.23127745234208458 and parameters: {'num_leaves': 94, 'learning_rate': 0.014707652294542673, 'feature_fraction': 0.999395862804411, 'bagging_fraction': 0.8613060322769477, 'bagging_freq': 9, 'lambda_l1': 5.940040873361645e-08, 'lambda_l2': 3.3564605151767776e-08, 'min_child_samples': 25, 'max_depth': 8, 'max_bin': 281, 'min_data_in_leaf': 66, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.2614282505250262, 'min_gain_to_split': 0.05670189346033946}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 02:10:52,761] Trial 469 finished with value: 0.22188151420250435 and parameters: {'num_leaves': 89, 'learning_rate': 0.013089687288468163, 'feature_fraction': 0.7960077915791975, 'bagging_fraction': 0.9669920888227007, 'bagging_freq': 9, 'lambda_l1': 4.474007167331731, 'lambda_l2': 2.834053379476266e-06, 'min_child_samples': 46, 'max_depth': 8, 'max_bin': 254, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 45, 'path_smooth': 0.29512896315534454, 'min_gain_to_split': 0.0660637137730711}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 02:14:41,828] Trial 470 finished with value: 0.22325155807551558 and parameters: {'num_leaves': 91, 'learning_rate': 0.012638323851147994, 'feature_fraction': 0.8347020962652557, 'bagging_fraction': 0.9599245253879448, 'bagging_freq': 10, 'lambda_l1': 1.0790493743009915e-07, 'lambda_l2': 1.852927226183638e-08, 'min_child_samples': 44, 'max_depth': 9, 'max_bin': 265, 'min_data_in_leaf': 28, 'extra_trees': True, 'early_stopping_rounds': 49, 'path_smooth': 0.2852026433399697, 'min_gain_to_split': 0.07729699635253932}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 02:18:15,130] Trial 471 finished with value: 0.22350724568488362 and parameters: {'num_leaves': 93, 'learning_rate': 0.014635383199811954, 'feature_fraction': 0.8679872999760386, 'bagging_fraction': 0.9532970173176027, 'bagging_freq': 9, 'lambda_l1': 1.3433147168820098e-07, 'lambda_l2': 5.1793073622164314e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 500, 'min_data_in_leaf': 29, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.3313746077301553, 'min_gain_to_split': 0.04570547611095723}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 02:21:29,340] Trial 472 finished with value: 0.22260912223815393 and parameters: {'num_leaves': 86, 'learning_rate': 0.0131992286719001, 'feature_fraction': 0.9682334522966619, 'bagging_fraction': 0.8903497524320473, 'bagging_freq': 10, 'lambda_l1': 2.4153725433747706e-07, 'lambda_l2': 9.2951889853895e-08, 'min_child_samples': 46, 'max_depth': 8, 'max_bin': 247, 'min_data_in_leaf': 24, 'extra_trees': True, 'early_stopping_rounds': 50, 'path_smooth': 0.28626950513919086, 'min_gain_to_split': 0.341301523632593}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 02:25:12,612] Trial 473 finished with value: 0.22198532023009734 and parameters: {'num_leaves': 95, 'learning_rate': 0.012235809455120124, 'feature_fraction': 0.8832414460279567, 'bagging_fraction': 0.9329410366347494, 'bagging_freq': 9, 'lambda_l1': 2.780284736874027e-06, 'lambda_l2': 1.6344473170912828e-07, 'min_child_samples': 44, 'max_depth': 8, 'max_bin': 274, 'min_data_in_leaf': 27, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.23662331230406738, 'min_gain_to_split': 0.34742665463185485}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 02:27:40,255] Trial 474 finished with value: 0.22126494347736406 and parameters: {'num_leaves': 92, 'learning_rate': 0.017939022553883587, 'feature_fraction': 0.8801084519493911, 'bagging_fraction': 0.9032175788310881, 'bagging_freq': 5, 'lambda_l1': 0.016692494511001594, 'lambda_l2': 3.73060099228309e-07, 'min_child_samples': 20, 'max_depth': 8, 'max_bin': 259, 'min_data_in_leaf': 30, 'extra_trees': True, 'early_stopping_rounds': 46, 'path_smooth': 0.2714690528873451, 'min_gain_to_split': 0.32349378214366653}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 02:30:36,192] Trial 475 finished with value: 0.22320462350144288 and parameters: {'num_leaves': 89, 'learning_rate': 0.014008859322598988, 'feature_fraction': 0.8723663970527519, 'bagging_fraction': 0.9406139688007259, 'bagging_freq': 8, 'lambda_l1': 7.858545019622478e-08, 'lambda_l2': 3.947848961981856e-08, 'min_child_samples': 46, 'max_depth': 8, 'max_bin': 251, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 49, 'path_smooth': 0.654830982870023, 'min_gain_to_split': 0.03321590101554808}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 02:34:07,489] Trial 476 finished with value: 0.22119171460262033 and parameters: {'num_leaves': 91, 'learning_rate': 0.012412882704860037, 'feature_fraction': 0.8616253633730229, 'bagging_fraction': 0.9482928554292305, 'bagging_freq': 9, 'lambda_l1': 1.5052446396845814e-06, 'lambda_l2': 1.84507235483347e-08, 'min_child_samples': 45, 'max_depth': 8, 'max_bin': 286, 'min_data_in_leaf': 40, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.31337734550106106, 'min_gain_to_split': 0.06053248501968438}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 02:36:54,289] Trial 477 finished with value: 0.2217388956711631 and parameters: {'num_leaves': 83, 'learning_rate': 0.016417259617734076, 'feature_fraction': 0.8865600240354341, 'bagging_fraction': 0.9715224715327861, 'bagging_freq': 9, 'lambda_l1': 2.01393389205178e-07, 'lambda_l2': 0.020567469860586052, 'min_child_samples': 26, 'max_depth': 9, 'max_bin': 241, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.6142141717910278, 'min_gain_to_split': 0.33442702846211303}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 02:39:41,223] Trial 478 finished with value: 0.22024628945196906 and parameters: {'num_leaves': 94, 'learning_rate': 0.015384372645889825, 'feature_fraction': 0.9021154072519847, 'bagging_fraction': 0.9558282319721094, 'bagging_freq': 4, 'lambda_l1': 0.3281693878241367, 'lambda_l2': 6.255588822260305e-08, 'min_child_samples': 47, 'max_depth': 8, 'max_bin': 264, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 50, 'path_smooth': 0.22137775036656243, 'min_gain_to_split': 0.20269432721386776}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 02:41:21,122] Trial 479 finished with value: 0.22610155822014777 and parameters: {'num_leaves': 94, 'learning_rate': 0.013462307973469303, 'feature_fraction': 0.9053009493277205, 'bagging_fraction': 0.9278047466476131, 'bagging_freq': 3, 'lambda_l1': 0.2706313662150931, 'lambda_l2': 2.7244934622130277e-08, 'min_child_samples': 47, 'max_depth': 4, 'max_bin': 259, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 50, 'path_smooth': 0.19373432789032705, 'min_gain_to_split': 0.21438332807473603}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 02:45:00,513] Trial 480 finished with value: 0.26516931327217047 and parameters: {'num_leaves': 96, 'learning_rate': 0.01194453226608342, 'feature_fraction': 0.901946765546336, 'bagging_fraction': 0.9419749616127167, 'bagging_freq': 3, 'lambda_l1': 0.797989430931322, 'lambda_l2': 0.002600352530888439, 'min_child_samples': 47, 'max_depth': 7, 'max_bin': 185, 'min_data_in_leaf': 40, 'extra_trees': False, 'early_stopping_rounds': 50, 'path_smooth': 0.21914070107412653, 'min_gain_to_split': 0.20272118434057124}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 02:47:45,741] Trial 481 finished with value: 0.2232924983382354 and parameters: {'num_leaves': 98, 'learning_rate': 0.014696981097191409, 'feature_fraction': 0.8969828976787685, 'bagging_fraction': 0.9644875254475477, 'bagging_freq': 4, 'lambda_l1': 0.36777361716759815, 'lambda_l2': 5.104715147142442e-08, 'min_child_samples': 10, 'max_depth': 8, 'max_bin': 248, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 49, 'path_smooth': 0.1712283742909671, 'min_gain_to_split': 0.2337471070440961}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 02:51:02,901] Trial 482 finished with value: 0.22225609673247287 and parameters: {'num_leaves': 94, 'learning_rate': 0.012691675854597946, 'feature_fraction': 0.8912539480223228, 'bagging_fraction': 0.952204129018479, 'bagging_freq': 3, 'lambda_l1': 0.12501386886488763, 'lambda_l2': 2.3666947480651284e-08, 'min_child_samples': 47, 'max_depth': 8, 'max_bin': 254, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 50, 'path_smooth': 0.20223966896568146, 'min_gain_to_split': 0.18775511207190101}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 02:52:00,634] Trial 483 finished with value: 0.2302806310693674 and parameters: {'num_leaves': 30, 'learning_rate': 0.03734681744054428, 'feature_fraction': 0.9160248733314006, 'bagging_fraction': 0.977939146407526, 'bagging_freq': 8, 'lambda_l1': 2.2888503695695617, 'lambda_l2': 6.88144347646604e-08, 'min_child_samples': 46, 'max_depth': 8, 'max_bin': 240, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 49, 'path_smooth': 0.2316643118078637, 'min_gain_to_split': 0.16207837492505126}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 02:55:29,655] Trial 484 finished with value: 0.22017411543452142 and parameters: {'num_leaves': 99, 'learning_rate': 0.011512172326527714, 'feature_fraction': 0.9004759892952879, 'bagging_fraction': 0.9356606598593307, 'bagging_freq': 4, 'lambda_l1': 1.0407669159083408, 'lambda_l2': 3.761746727541774e-08, 'min_child_samples': 24, 'max_depth': 8, 'max_bin': 263, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 50, 'path_smooth': 0.26355176620996335, 'min_gain_to_split': 0.3520852259683815}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 02:58:57,880] Trial 485 finished with value: 0.22376351642735007 and parameters: {'num_leaves': 100, 'learning_rate': 0.011751040921924187, 'feature_fraction': 0.9105212254022033, 'bagging_fraction': 0.9325481734890975, 'bagging_freq': 4, 'lambda_l1': 0.618930234040314, 'lambda_l2': 4.018035608769162e-08, 'min_child_samples': 24, 'max_depth': 8, 'max_bin': 246, 'min_data_in_leaf': 40, 'extra_trees': True, 'early_stopping_rounds': 50, 'path_smooth': 0.2458549930584622, 'min_gain_to_split': 0.2265716119812368}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 03:02:42,430] Trial 486 finished with value: 0.222746506052356 and parameters: {'num_leaves': 98, 'learning_rate': 0.011414345042539038, 'feature_fraction': 0.9054224936686034, 'bagging_fraction': 0.9360054341293149, 'bagging_freq': 4, 'lambda_l1': 0.6638945031176565, 'lambda_l2': 1.4797054771064927e-08, 'min_child_samples': 25, 'max_depth': 8, 'max_bin': 262, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 50, 'path_smooth': 0.2670418458805933, 'min_gain_to_split': 0.17845708302257313}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 03:05:41,870] Trial 487 finished with value: 0.22309932335525268 and parameters: {'num_leaves': 98, 'learning_rate': 0.012884080067495283, 'feature_fraction': 0.8983303215587356, 'bagging_fraction': 0.926829371352161, 'bagging_freq': 4, 'lambda_l1': 0.6068252273293799, 'lambda_l2': 2.3900372118306027e-08, 'min_child_samples': 22, 'max_depth': 8, 'max_bin': 252, 'min_data_in_leaf': 40, 'extra_trees': True, 'early_stopping_rounds': 50, 'path_smooth': 0.2974873723937806, 'min_gain_to_split': 0.26005117064464234}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 03:08:52,297] Trial 488 finished with value: 0.22306370598668918 and parameters: {'num_leaves': 99, 'learning_rate': 0.011951191693487651, 'feature_fraction': 0.9184877555990691, 'bagging_fraction': 0.9400026536698484, 'bagging_freq': 4, 'lambda_l1': 2.1137749272121413e-06, 'lambda_l2': 3.2641262440620615e-08, 'min_child_samples': 24, 'max_depth': 8, 'max_bin': 211, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 49, 'path_smooth': 0.22690429734853082, 'min_gain_to_split': 0.352484585129914}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 03:12:20,334] Trial 489 finished with value: 0.22166733876059 and parameters: {'num_leaves': 100, 'learning_rate': 0.01089238838054044, 'feature_fraction': 0.90401844654911, 'bagging_fraction': 0.916027422617597, 'bagging_freq': 4, 'lambda_l1': 1.3957962928868262, 'lambda_l2': 1.683036608244665e-08, 'min_child_samples': 22, 'max_depth': 8, 'max_bin': 235, 'min_data_in_leaf': 41, 'extra_trees': True, 'early_stopping_rounds': 50, 'path_smooth': 0.27353751618298083, 'min_gain_to_split': 0.2076068345814793}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 03:15:16,475] Trial 490 finished with value: 0.22284064642495743 and parameters: {'num_leaves': 97, 'learning_rate': 0.01371734437416928, 'feature_fraction': 0.8888988151345559, 'bagging_fraction': 0.922594741584807, 'bagging_freq': 4, 'lambda_l1': 1.776120344222925, 'lambda_l2': 3.304005036405644e-08, 'min_child_samples': 23, 'max_depth': 8, 'max_bin': 263, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 49, 'path_smooth': 0.25667753575084945, 'min_gain_to_split': 0.3400344347748294}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 03:19:03,408] Trial 491 finished with value: 0.22140146051702878 and parameters: {'num_leaves': 96, 'learning_rate': 0.012577607066910489, 'feature_fraction': 0.8910378289166714, 'bagging_fraction': 0.9341631636513924, 'bagging_freq': 4, 'lambda_l1': 0.42258043908193876, 'lambda_l2': 5.573373586590913e-08, 'min_child_samples': 17, 'max_depth': 9, 'max_bin': 244, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 49, 'path_smooth': 0.21182489849964595, 'min_gain_to_split': 0.35772301771185727}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 03:21:56,505] Trial 492 finished with value: 0.22289558022740702 and parameters: {'num_leaves': 80, 'learning_rate': 0.011723229348773245, 'feature_fraction': 0.9002363383757573, 'bagging_fraction': 0.9447465173380201, 'bagging_freq': 6, 'lambda_l1': 0.8943281821812267, 'lambda_l2': 2.1600323729078195e-08, 'min_child_samples': 25, 'max_depth': 7, 'max_bin': 255, 'min_data_in_leaf': 25, 'extra_trees': True, 'early_stopping_rounds': 50, 'path_smooth': 0.25364531764823617, 'min_gain_to_split': 0.34984184496702153}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 03:26:04,885] Trial 493 finished with value: 0.2235109716837766 and parameters: {'num_leaves': 95, 'learning_rate': 0.01002475524879618, 'feature_fraction': 0.7274981878519067, 'bagging_fraction': 0.9383913696210741, 'bagging_freq': 4, 'lambda_l1': 1.4134066368783298, 'lambda_l2': 4.26702849903252e-08, 'min_child_samples': 24, 'max_depth': 10, 'max_bin': 232, 'min_data_in_leaf': 42, 'extra_trees': True, 'early_stopping_rounds': 49, 'path_smooth': 0.280995671217385, 'min_gain_to_split': 0.1702126339459177}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 03:28:13,575] Trial 494 finished with value: 0.22281616809554955 and parameters: {'num_leaves': 97, 'learning_rate': 0.010976294596347632, 'feature_fraction': 0.9103052488190271, 'bagging_fraction': 0.9312281739239283, 'bagging_freq': 4, 'lambda_l1': 0.19005520675689974, 'lambda_l2': 2.4695976189320032e-05, 'min_child_samples': 36, 'max_depth': 5, 'max_bin': 254, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.2348807397436386, 'min_gain_to_split': 0.33080311061609896}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 03:31:35,154] Trial 495 finished with value: 0.22153195094372147 and parameters: {'num_leaves': 93, 'learning_rate': 0.013757538365556075, 'feature_fraction': 0.8881132203824724, 'bagging_fraction': 0.9461800271447297, 'bagging_freq': 4, 'lambda_l1': 3.951088405571509e-07, 'lambda_l2': 1.7554312336219405e-08, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 264, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 50, 'path_smooth': 0.29878657901341266, 'min_gain_to_split': 0.36464861067999865}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 03:35:06,216] Trial 496 finished with value: 0.22178173933238318 and parameters: {'num_leaves': 100, 'learning_rate': 0.012151501536488711, 'feature_fraction': 0.980355757983492, 'bagging_fraction': 0.9382461781160268, 'bagging_freq': 4, 'lambda_l1': 1.0899119025521284, 'lambda_l2': 0.0062935241864905235, 'min_child_samples': 23, 'max_depth': 8, 'max_bin': 243, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 49, 'path_smooth': 0.5940282819581955, 'min_gain_to_split': 0.3389514222970365}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 03:38:20,443] Trial 497 finished with value: 0.221698154049852 and parameters: {'num_leaves': 95, 'learning_rate': 0.012961830203644976, 'feature_fraction': 0.9570912256165081, 'bagging_fraction': 0.9219361835084616, 'bagging_freq': 5, 'lambda_l1': 3.5334087224140944, 'lambda_l2': 1.2600851588622e-05, 'min_child_samples': 48, 'max_depth': 8, 'max_bin': 277, 'min_data_in_leaf': 41, 'extra_trees': True, 'early_stopping_rounds': 19, 'path_smooth': 0.1912190229074055, 'min_gain_to_split': 0.34912382750587195}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 03:43:21,014] Trial 498 finished with value: 0.22214483314329692 and parameters: {'num_leaves': 93, 'learning_rate': 0.011261034585313743, 'feature_fraction': 0.9896957160851799, 'bagging_fraction': 0.9472926777974023, 'bagging_freq': 10, 'lambda_l1': 2.5537528319917975, 'lambda_l2': 1.3262159178371068e-08, 'min_child_samples': 38, 'max_depth': 9, 'max_bin': 335, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.2527235142987508, 'min_gain_to_split': 0.30228570501997515}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 03:44:22,733] Trial 499 finished with value: 0.2272017965656768 and parameters: {'num_leaves': 97, 'learning_rate': 0.05381784768415072, 'feature_fraction': 0.8803349634420072, 'bagging_fraction': 0.952109568288421, 'bagging_freq': 9, 'lambda_l1': 3.1818254322142423e-06, 'lambda_l2': 5.7523198809748637e-08, 'min_child_samples': 26, 'max_depth': 8, 'max_bin': 249, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.2172579993050793, 'min_gain_to_split': 0.2431471035801689}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 03:49:47,676] Trial 500 finished with value: 0.2623521055976997 and parameters: {'num_leaves': 95, 'learning_rate': 0.011736645915993285, 'feature_fraction': 0.8933902586971586, 'bagging_fraction': 0.9418487145981, 'bagging_freq': 9, 'lambda_l1': 1.5146949269264286e-06, 'lambda_l2': 3.324055340104984e-08, 'min_child_samples': 33, 'max_depth': 8, 'max_bin': 225, 'min_data_in_leaf': 40, 'extra_trees': False, 'early_stopping_rounds': 49, 'path_smooth': 0.579297289099909, 'min_gain_to_split': 0.31470465847822776}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}

[I 2025-07-17 03:52:48,131] Trial 501 finished with value: 0.23731584208495055 and parameters: {'num_leaves': 99, 'learning_rate': 0.0105802080224289, 'feature_fraction': 0.9085462386027983, 'bagging_fraction': 0.9307935360875796, 'bagging_freq': 4, 'lambda_l1': 0.3519615272484014, 'lambda_l2': 8.650957654167965e-05, 'min_child_samples': 29, 'max_depth': 8, 'max_bin': 122, 'min_data_in_leaf': 81, 'extra_trees': True, 'early_stopping_rounds': 50, 'path_smooth': 0.6329891840655055, 'min_gain_to_split': 0.36172206631018705}. Best is trial 415 with value: 0.21891901764809552.

Mejor trial hasta ahora: TFE=0.218919, Parámetros={'num_leaves': 94, 'learning_rate': 0.011828769582017987, 'feature_fraction': 0.8730198358476882, 'bagging_fraction': 0.959933825640181, 'bagging_freq': 8, 'lambda_l1': 8.833494682319988e-08, 'lambda_l2': 7.062421979561123e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 242, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.39251848468006784, 'min_gain_to_split': 0.3363925701702316}
Estudio guardado en: sqlite:///optuna_studies_v24.db

Mejores hiperparámetros encontrados:
num_leaves: 94
learning_rate: 0.011828769582017987
feature_fraction: 0.8730198358476882
bagging_fraction: 0.959933825640181
bagging_freq: 8
lambda_l1: 8.833494682319988e-08
lambda_l2: 7.062421979561123e-05
min_child_samples: 32
max_depth: 8
max_bin: 242
min_data_in_leaf: 34
extra_trees: True
early_stopping_rounds: 48
path_smooth: 0.39251848468006784
min_gain_to_split: 0.3363925701702316

(<optuna.study.study.Study at 0x21780e0d510>,
 {'num_leaves': 94,
  'learning_rate': 0.011828769582017987,
  'feature_fraction': 0.8730198358476882,
  'bagging_fraction': 0.959933825640181,
  'bagging_freq': 8,
  'lambda_l1': 8.833494682319988e-08,
  'lambda_l2': 7.062421979561123e-05,
  'min_child_samples': 32,
  'max_depth': 8,
  'max_bin': 242,
  'min_data_in_leaf': 34,
  'extra_trees': True,
  'early_stopping_rounds': 48,
  'path_smooth': 0.39251848468006784,
  'min_gain_to_split': 0.3363925701702316,
  'objective': 'regression',
  'metric': 'rmse',
  'boosting_type': 'gbdt',
  'verbosity': -1})

Prediccion Test

In [66]:
df_prediccion_test = model_lgb_keepsimple.semillerio_en_prediccion_con_pesos(df_train, df_val, df_test, version="v24")

In [67]:
df_prediccion_test

       periodo  product_id      target         pred
28656   201910       20001  1504.68856  1334.000601
28657   201910       20002  1087.30855  1376.701029
28658   201910       20003   892.50129   837.634090
28659   201910       20004   637.90002   568.996552
28660   201910       20005   593.24443   596.094511
...        ...         ...         ...          ...
29567   201910       21266     0.05121     0.212243
29568   201910       21267     0.01569     0.110493
29569   201910       21269     0.00000    -0.609200
29570   201910       21271     0.00298    -0.326782
29571   201910       21276     0.00892     0.437645

[916 rows x 4 columns]

Productos

In [69]:
productos_ok = pd.read_csv("../../data/raw/product_id_apredecir201912.csv", sep="\t")

In [71]:
df_promedios = model_lgb.promedio_12_meses_780p()
df_promedios

     product_id           tn
0         20001  1454.732720
1         20002  1175.437142
2         20003   784.976407
3         20004   627.215328
4         20005   668.270104
..          ...          ...
775       21263     0.029993
776       21265     0.089541
777       21266     0.094659
778       21267     0.092835
779       21276     0.045447

[780 rows x 2 columns]

Filtramos

In [72]:
df_prediccion_test = df_prediccion_test[df_prediccion_test['product_id'].isin(productos_ok['product_id'].unique())]

In [73]:
df_prediccion_test = df_prediccion_test.merge(df_promedios, on=['product_id'], how='left', suffixes=('', '_promedio'))
df_prediccion_test

     periodo  product_id      target         pred           tn
0     201910       20001  1504.68856  1334.000601  1454.732720
1     201910       20002  1087.30855  1376.701029  1175.437142
2     201910       20003   892.50129   837.634090   784.976407
3     201910       20004   637.90002   568.996552   627.215328
4     201910       20005   593.24443   596.094511   668.270104
..       ...         ...         ...          ...          ...
775   201910       21263     0.01270     0.247541     0.029993
776   201910       21265     0.05007     0.456357     0.089541
777   201910       21266     0.05121     0.212243     0.094659
778   201910       21267     0.01569     0.110493     0.092835
779   201910       21276     0.00892     0.437645     0.045447

[780 rows x 5 columns]

Reemplazamos negativos por el promedio

In [75]:
df_prediccion_test.loc[df_prediccion_test["pred"] < 0, "pred"] = df_prediccion_test["tn"]

TFE

In [77]:
df_prediccion_test['tfe'] = (np.sum(np.abs(df_prediccion_test['target'] - df_prediccion_test['pred']))) / np.sum(df_prediccion_test['target'])
df_prediccion_test['tfe']

0      0.239665
1      0.239665
2      0.239665
3      0.239665
4      0.239665
         ...
775    0.239665
776    0.239665
777    0.239665
778    0.239665
779    0.239665
Name: tfe, Length: 780, dtype: float64

Predicción kaggle

In [ ]:
df_prediccion_test = model_lgb_keepsimple.semillerio_en_prediccion_con_pesos(df_train, df_val, df_pred, version="v24")

In [80]:
df_prediccion_kaggle = df_prediccion_test.copy()
df_prediccion_kaggle = df_prediccion_kaggle[df_prediccion_kaggle['product_id'].isin(productos_ok['product_id'].unique())]
df_prediccion_kaggle

       periodo  product_id  target         pred
30476   201912       20001     NaN  1365.027653
30477   201912       20002     NaN  1114.254525
30478   201912       20003     NaN   656.971716
30479   201912       20004     NaN   487.696267
30480   201912       20005     NaN   566.637911
...        ...         ...     ...          ...
31355   201912       21263     NaN    -0.987871
31357   201912       21265     NaN    -0.207048
31358   201912       21266     NaN    -0.991461
31359   201912       21267     NaN    -1.202688
31361   201912       21276     NaN    -0.350916

[780 rows x 4 columns]

In [81]:
df_prediccion_kaggle = df_prediccion_kaggle.merge(df_promedios, on=['product_id'], how='left', suffixes=('', '_promedio'))
df_prediccion_kaggle

     periodo  product_id  target         pred           tn
0     201912       20001     NaN  1365.027653  1454.732720
1     201912       20002     NaN  1114.254525  1175.437142
2     201912       20003     NaN   656.971716   784.976407
3     201912       20004     NaN   487.696267   627.215328
4     201912       20005     NaN   566.637911   668.270104
..       ...         ...     ...          ...          ...
775   201912       21263     NaN    -0.987871     0.029993
776   201912       21265     NaN    -0.207048     0.089541
777   201912       21266     NaN    -0.991461     0.094659
778   201912       21267     NaN    -1.202688     0.092835
779   201912       21276     NaN    -0.350916     0.045447

[780 rows x 5 columns]

In [82]:
df_prediccion_kaggle.loc[df_prediccion_kaggle["pred"] < 0, "pred"] = df_prediccion_kaggle["tn"]

In [83]:
df_prediccion_kaggle = df_prediccion_kaggle[['product_id', 'pred']]
df_prediccion_kaggle.rename(columns={'pred': 'tn'}, inplace=True)
df_prediccion_kaggle.to_csv("./datasets/prediccion_exp09_lgb_v3.csv", index=False, sep=",", encoding='utf-8')