In [35]:
import pandas as pd
import numpy as np
import importlib
import gc
import sys
import warnings
sys.path.append('./scripts')  
import preprocesamiento
import target
import feature_engineering
import model_lgb
import model_lgb_simple
importlib.reload(preprocesamiento)
importlib.reload(target)
importlib.reload(model_lgb)
importlib.reload(model_lgb_simple)
importlib.reload(feature_engineering)
warnings.filterwarnings("ignore")

# Experimento 9: 
- LGBM
- Igual al main_v9_lgb_v2 pero con 5FCV
- Estandarización hasta 201906
- Estandarizacion del target
- Semillerio en train y test
- Agrego variables: agrego los ceros que dijo el profesor.
- Pesos: logaritmo
- sqlite:///optuna_studies_v22.db
- Kaggle =

**Training:**
```python
training = [
    201701, 201702, 201703, 201704, 201705, 201706, 201707, 201708, 201709,
    201710, 201711, 201712, 201801, 201802, 201803, 201804, 201805,
    201806, 201807, 201808, 201809, 201810, 201811, 201812,
    201901, 201902, 201903, 201904, 201905, 201906
]

validation = [
    # 201907, 201908
    201907, 201909
]

testing = [
    201910
]

Levantamos

In [2]:
df = pd.read_csv('./datasets/periodo_x_producto.csv', sep=',', encoding='utf-8')

Estandarizacion zscore

In [3]:
df = preprocesamiento.normalizar_con_zscore(df, "tn", fecha=201806)
df

,product_id,periodo,nacimiento_producto,muerte_producto,mes_n,total_meses,producto_nuevo,ciclo_de_vida_inicial,cat1,cat2,...,brand,sku_size,stock_final,tn,plan_precios_cuidados,cust_request_qty,cust_request_tn,tn_mean,tn_std,tn_zscore
0,20001,201701,201701,201912,1,36,0,0,HC,ROPA LAVADO,...,ARIEL,3000.0,NaN,934.77222,0.0,479.0,937.72717,1254.369806,251.944810,-1.268522
1,20001,201702,201701,201912,2,36,0,0,HC,ROPA LAVADO,...,ARIEL,3000.0,NaN,798.01620,0.0,432.0,833.72187,1254.369806,251.944810,-1.811324
2,20001,201703,201701,201912,3,36,0,0,HC,ROPA LAVADO,...,ARIEL,3000.0,NaN,1303.35771,0.0,509.0,1330.74697,1254.369806,251.944810,0.194439
3,20001,201704,201701,201912,4,36,0,0,HC,ROPA LAVADO,...,ARIEL,3000.0,NaN,1069.96130,0.0,279.0,1132.94430,1254.369806,251.944810,-0.731940
4,20001,201705,201701,201912,5,36,0,0,HC,ROPA LAVADO,...,ARIEL,3000.0,NaN,1502.20132,0.0,701.0,1550.68936,1254.369806,251.944810,0.983674
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31357,21281,201704,201702,201708,3,7,1,1,NaN,NaN,...,NaN,NaN,NaN,0.00000,NaN,NaN,NaN,0.021060,0.031414,-0.670410
31358,21281,201705,201702,201708,4,7,1,0,NaN,NaN,...,NaN,NaN,NaN,0.00000,NaN,NaN,NaN,0.021060,0.031414,-0.670410
31359,21281,201706,201702,201708,5,7,1,0,NaN,NaN,...,NaN,NaN,NaN,0.09134,0.0,8.0,0.10539,0.021060,0.031414,2.237248
31360,21281,201707,201702,201708,6,7,1,0,NaN,NaN,...,NaN,NaN,NaN,0.00000,NaN,NaN,NaN,0.021060,0.031414,-0.670410
31361,21281,201708,201702,201708,7,7,1,0,NaN,NaN,...,NaN,NaN,NaN,0.03500,0.0,1.0,0.03500,0.021060,0.031414,0.443757

In [4]:
df.rename(columns={'tn':'tn_original'}, inplace=True)
df.rename(columns={'tn_zscore':'tn'}, inplace=True)

Guardamos

In [12]:
df.to_csv("../../data/preprocessed/periodo_x_producto_con_target_zscore_201906.csv", index=False, sep=',', encoding='utf-8')

##### Procesamiento del Target

In [5]:
df = pd.read_csv("../../data/preprocessed/periodo_x_producto_con_target_zscore_201906.csv", sep=',', encoding='utf-8')

print(df.shape)

df = target.target_tn_mas_dos(df)

print(df.shape)

(31362, 21)
(31362, 22)

##### Feature Engineering

In [18]:
columnas_baseline = df.columns.tolist()
columnas_baseline

['product_id',
 'periodo',
 'nacimiento_producto',
 'muerte_producto',
 'mes_n',
 'total_meses',
 'producto_nuevo',
 'ciclo_de_vida_inicial',
 'cat1',
 'cat2',
 'cat3',
 'brand',
 'sku_size',
 'stock_final',
 'tn_original',
 'plan_precios_cuidados',
 'cust_request_qty',
 'cust_request_tn',
 'tn_mean',
 'tn_std',
 'tn',
 'target']

##### Preprocesamiento a la minima expresión :)

In [6]:
df = feature_engineering.create_category_features_cat1(df)
df = feature_engineering.create_category_features_cat2(df)
df = feature_engineering.create_category_features_cat3(df)

In [7]:
# ##### aplicamos OHE
df = preprocesamiento.aplicarOHE(df)
df.shape

(31362, 174)

### Feature Engineering

##### Neural Prophet

In [8]:
neural_prophet_fe = pd.read_csv("./datasets/features_neuralprophet_completo.csv", sep=',', encoding='utf-8')
neural_prophet_fe['ds'] = pd.to_datetime(neural_prophet_fe['ds'], errors='coerce')
# Versión alternativa más robusta:
neural_prophet_fe['periodo'] = neural_prophet_fe['ds'].apply(
    lambda x: x.year * 100 + x.month if pd.notnull(x) else None
)
neural_prophet_fe = neural_prophet_fe[['periodo', 'product_id', 'trend', "season_yearly", "season_monthly"]]
df = df.merge(neural_prophet_fe, on=['periodo', 'product_id'], how='left')
df.shape

(31362, 177)

##### Prophet

In [9]:
prophet_fe = pd.read_csv("./datasets/prophet_features_tn_zscore.csv", sep=',', encoding='utf-8')
prophet_fe['ds'] = pd.to_datetime(prophet_fe['ds'], errors='coerce')
prophet_fe['periodo'] = prophet_fe['ds'].apply(
    lambda x: x.year * 100 + x.month if pd.notnull(x) else None
)
prophet_fe = prophet_fe[['periodo', 'product_id', 'trend_add', "yearly_add", "additive_terms", 'trend_mult', 'yearly_mult', 'multiplicative_terms']]
df = df.merge(prophet_fe, on=['periodo', 'product_id'], how='left')
df.shape

(31362, 183)

##### FE Moviles

In [10]:
df = feature_engineering.get_lags(df, "tn", 201912)
df = feature_engineering.get_delta_lags(df, "tn", 24)
df = feature_engineering.get_rolling_means(df, "tn", 201912)
df = feature_engineering.get_rolling_stds(df, "tn", 201912)
df = feature_engineering.get_rolling_mins(df, "tn", 201912)
df = feature_engineering.get_rolling_maxs(df, "tn", 201912)
df = feature_engineering.get_rolling_medians(df, "tn", 201912)
df = feature_engineering.get_rolling_skewness(df, "tn", 201912)
df = feature_engineering.get_autocorrelaciones(df, "tn", 201912)
df.shape

(31362, 745)

In [11]:
df = feature_engineering.get_lags(df, "cust_request_qty", 201912)
df = feature_engineering.get_delta_lags(df, "cust_request_qty", 24)
df = feature_engineering.get_rolling_means(df, "cust_request_qty", 201912)
df = feature_engineering.get_rolling_stds(df, "cust_request_qty", 201912)
df = feature_engineering.get_rolling_mins(df, "cust_request_qty", 201912)
df = feature_engineering.get_rolling_maxs(df, "cust_request_qty", 201912)
df.shape

(31362, 1200)

In [12]:
df = feature_engineering.get_lags(df, "stock_final", 201912)
df = feature_engineering.get_delta_lags(df, "stock_final", 24)
df = feature_engineering.get_rolling_means(df, "stock_final", 201912)
df = feature_engineering.get_rolling_stds(df, "stock_final", 201912)
df = feature_engineering.get_rolling_mins(df, "stock_final", 201912)
df = feature_engineering.get_rolling_maxs(df, "stock_final", 201912)
df.shape

(31362, 1655)

Features Diana

In [13]:
df = feature_engineering.calcular_diferencia_con_medias_moviles(df)
df = feature_engineering.calcular_ratios_con_medias_moviles(df)
df.shape

(31362, 1691)

##### FE Moviles sobre otras variables

In [56]:
# #  stock final
# df = feature_engineering.get_lagsEspecificos(df, col='stock_final_zscore')
# df = feature_engineering.get_delta_lags_especificos(df, col='stock_final_zscore')
# df = feature_engineering.get_rolling_means_especificos(df, col='stock_final_zscore')
# df = feature_engineering.get_rolling_stds_especificos(df, col='stock_final_zscore')
# df = feature_engineering.get_rolling_medians_especificos(df, col='stock_final_zscore')
# df = feature_engineering.get_rolling_mins_especificos(df, col='stock_final_zscore')
# df = feature_engineering.get_rolling_maxs_especificos(df, col='stock_final_zscore')
# df = feature_engineering.get_rolling_skewness_especificos(df, col='stock_final_zscore')

#  cust_request_qty
# df = feature_engineering.get_lagsEspecificos(df, col='cust_request_qty')
# df = feature_engineering.get_delta_lags_especificos(df, col='cust_request_qty')
# df = feature_engineering.get_rolling_means_especificos(df, col='cust_request_qty')
# df = feature_engineering.get_rolling_stds_especificos(df, col='cust_request_qty')
# df = feature_engineering.get_rolling_mins_especificos(df, col='cust_request_qty')
# df = feature_engineering.get_rolling_maxs_especificos(df, col='cust_request_qty')
# df = feature_engineering.get_rolling_medians_especificos(df, col='cust_request_qty')
# df = feature_engineering.get_rolling_skewness_especificos(df, col='cust_request_qty')

##### FE Calendario

In [14]:
df = feature_engineering.generar_ids(df)
df = feature_engineering.get_componentesTemporales(df)
df = feature_engineering.get_anomaliasPoliticas(df)
# df = feature_engineering.descomposicion_serie_temporal(df, col='tn')
df.shape

(31362, 1716)

##### FE sobre FE

In [15]:
df = feature_engineering.chatGPT_features_serie(df, "tn")
df = feature_engineering.mes_con_feriado(df)
df.shape

(31362, 1745)

##### Variables Exogenas

In [16]:
df = feature_engineering.get_dolar(df)
df = feature_engineering.get_IPC(df)
df['ipc'] = df['ipc'].str.replace(',', '.').astype(float)
df['dolar'] = df['dolar'].str.replace(',', '.').astype(float)
# df.drop(columns=['ds'], inplace=True)
df.fillna(0, inplace=True) ##### EXPERIMENTAR
df = feature_engineering.correlacion_exogenas(df)
df = feature_engineering.get_mes_receso_escolar(df)
df.shape

(31362, 1748)

##### Nuevas FE

In [17]:
df = feature_engineering.create_ratio_features(df)
df = feature_engineering.enhance_lifecycle_features(df)
# df = feature_engineering.create_category_features(df)
df = feature_engineering.create_regime_features(df)
df = feature_engineering.create_nonlinear_trends(df)
df = feature_engineering.create_temporal_interactions(df)
df = feature_engineering.create_asymmetric_window_features(df)
df = feature_engineering.recomendaciones_deepseek(df)
df = feature_engineering.get_nuevas_features(df)
df.shape

(31362, 1787)

##### Ceros

In [18]:
df = feature_engineering.agregar_ceros_consecutivos_atras(df, col_tn='tn_original')
df = feature_engineering.agregar_no_ceros_consecutivos_atras(df, col_tn='tn_original')
df = feature_engineering.agregar_ceros_ultimos_n_meses(df, ventanas=[1,2,3,4,5,6,12], col_tn='tn_original')
df = feature_engineering.agregar_min_max_ult_n(df, n_list=(1,2,3,4,5,6,12), col_tn='tn_original')
df.shape

(31362, 1810)

##### Elimino aquellas que no sirven

In [ ]:
import json
import pandas as pd
import csv

with open("./feature_importance/v19.json") as f:
    data = json.load(f)

# Crear una lista de tuplas (feature, value)
features_values = [(feature, value) for feature, value in data.items()]

# Guardar en un archivo CSV
with open('./feature_importance/v19.csv', 'w', newline='') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow(['feature', 'importance'])  # Escribir el encabezado
    writer.writerows(features_values)      # Escribir los datos

print("Archivo CSV generado exitosamente: features_values.csv")

Archivo CSV generado exitosamente: features_values.csv

In [17]:
importantes = pd.read_csv("./feature_importance/v19.csv", sep=',', encoding='utf-8')
no_importantes = importantes[importantes['importance'] == 0]
no_importantes = no_importantes[~no_importantes['feature'].isin(columnas_baseline)]
no_importantes

                         feature  importance
1103           tn_rolling_std_20         0.0
1104           tn_rolling_std_22         0.0
1105           tn_rolling_std_25         0.0
1106           tn_rolling_std_26         0.0
1107           tn_rolling_std_27         0.0
...                          ...         ...
1781             cat3_Acond Bebe         0.0
1782        tn_rolling_median_25         0.0
1783        tn_rolling_median_24         0.0
1786            tn_rolling_std_1         0.0
1787  stock_final_rolling_min_23         0.0

[682 rows x 2 columns]

In [18]:
cols_a_eliminar = no_importantes.feature.unique()
print(f"Antes de eliminar: {df.shape[1]} columnas")
df = df.drop(columns=cols_a_eliminar, errors='ignore')
print(f"Después de eliminar: {df.shape[1]} columnas")

Antes de eliminar: 1821 columnas
Después de eliminar: 1139 columnas

Eliminar object/categorical columnas

In [25]:
df = df.select_dtypes(exclude=['datetime', 'datetime64', 'object', 'category'])
df.shape

(31362, 1809)

Train Test Split

In [20]:
train = df[df['periodo'] <= 201912]
test = df[df['periodo'] == 201912]

In [26]:
# 1. Limpieza de datos ANTES de la división
def clean_data(df):
    # Reemplazar infinitos y valores extremos
    df = df.replace([np.inf, -np.inf], np.nan)
    
    # Rellenar NA (elige una estrategia)
    df = df.fillna(df.median())  # Opción 1: con medianas
    # df = df.dropna()  # Opción 2: eliminar filas con NA
    
    # Normalizar valores extremos
    for col in df.select_dtypes(include=[np.number]).columns:
        df[col] = np.clip(df[col], -1e10, 1e10)
    
    return df

df = clean_data(df)

Entrenamiento

In [ ]:
model_lgb_simple.optimizar_con_optuna_con5FCV_con_semillerio_db(train, version="v23", n_trials=500)

Para visualizar los resultados en tiempo real:
1. Abre otra terminal y ejecuta:
   optuna-dashboard sqlite:///optuna_studies_v23.db
2. Abre en tu navegador: http://127.0.0.1:8080/

[I 2025-07-13 11:54:59,579] Using an existing study with name 'lightgbm_optimization_v23' instead of creating a new one.
[I 2025-07-13 11:57:31,694] Trial 2 finished with value: 177.62549487263504 and parameters: {'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}. Best is trial 2 with value: 177.62549487263504.

Mejor trial hasta ahora: RMSE=177.625495, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-13 11:59:53,208] Trial 3 finished with value: 177.4771143702057 and parameters: {'num_leaves': 41, 'learning_rate': 0.05958389350068958, 'feature_fraction': 0.7727780074568463, 'bagging_fraction': 0.7873687420594125, 'bagging_freq': 7, 'lambda_l1': 1.8007140198129195e-07, 'lambda_l2': 4.258943089524393e-06, 'min_child_samples': 25, 'max_depth': 6, 'max_bin': 414, 'min_data_in_leaf': 36, 'extra_trees': False, 'early_stopping_rounds': 11, 'path_smooth': 0.6075448519014384, 'min_gain_to_split': 0.08526206184364576}. Best is trial 3 with value: 177.4771143702057.

Mejor trial hasta ahora: RMSE=177.477114, Parámetros={'num_leaves': 41, 'learning_rate': 0.05958389350068958, 'feature_fraction': 0.7727780074568463, 'bagging_fraction': 0.7873687420594125, 'bagging_freq': 7, 'lambda_l1': 1.8007140198129195e-07, 'lambda_l2': 4.258943089524393e-06, 'min_child_samples': 25, 'max_depth': 6, 'max_bin': 414, 'min_data_in_leaf': 36, 'extra_trees': False, 'early_stopping_rounds': 11, 'path_smooth': 0.6075448519014384, 'min_gain_to_split': 0.08526206184364576}

[I 2025-07-13 12:01:42,333] Trial 4 finished with value: 177.58778808913604 and parameters: {'num_leaves': 20, 'learning_rate': 0.2521267904777921, 'feature_fraction': 0.9862528132298237, 'bagging_fraction': 0.9425192044349383, 'bagging_freq': 4, 'lambda_l1': 7.569183361880229e-08, 'lambda_l2': 0.014391207615728067, 'min_child_samples': 28, 'max_depth': 3, 'max_bin': 298, 'min_data_in_leaf': 22, 'extra_trees': True, 'early_stopping_rounds': 37, 'path_smooth': 0.31171107608941095, 'min_gain_to_split': 0.2600340105889054}. Best is trial 3 with value: 177.4771143702057.

Mejor trial hasta ahora: RMSE=177.477114, Parámetros={'num_leaves': 41, 'learning_rate': 0.05958389350068958, 'feature_fraction': 0.7727780074568463, 'bagging_fraction': 0.7873687420594125, 'bagging_freq': 7, 'lambda_l1': 1.8007140198129195e-07, 'lambda_l2': 4.258943089524393e-06, 'min_child_samples': 25, 'max_depth': 6, 'max_bin': 414, 'min_data_in_leaf': 36, 'extra_trees': False, 'early_stopping_rounds': 11, 'path_smooth': 0.6075448519014384, 'min_gain_to_split': 0.08526206184364576}

[I 2025-07-13 12:03:37,302] Trial 5 finished with value: 177.45662999448214 and parameters: {'num_leaves': 62, 'learning_rate': 0.01875220945578641, 'feature_fraction': 0.9878338511058234, 'bagging_fraction': 0.9325398470083344, 'bagging_freq': 10, 'lambda_l1': 1.1309571585271483, 'lambda_l2': 0.002404915432737351, 'min_child_samples': 47, 'max_depth': 3, 'max_bin': 178, 'min_data_in_leaf': 23, 'extra_trees': False, 'early_stopping_rounds': 21, 'path_smooth': 0.8287375091519293, 'min_gain_to_split': 0.17837666334679464}. Best is trial 5 with value: 177.45662999448214.

Mejor trial hasta ahora: RMSE=177.456630, Parámetros={'num_leaves': 62, 'learning_rate': 0.01875220945578641, 'feature_fraction': 0.9878338511058234, 'bagging_fraction': 0.9325398470083344, 'bagging_freq': 10, 'lambda_l1': 1.1309571585271483, 'lambda_l2': 0.002404915432737351, 'min_child_samples': 47, 'max_depth': 3, 'max_bin': 178, 'min_data_in_leaf': 23, 'extra_trees': False, 'early_stopping_rounds': 21, 'path_smooth': 0.8287375091519293, 'min_gain_to_split': 0.17837666334679464}

[I 2025-07-13 12:06:00,382] Trial 6 finished with value: 177.50025631691352 and parameters: {'num_leaves': 39, 'learning_rate': 0.06333268775321843, 'feature_fraction': 0.6563696899899051, 'bagging_fraction': 0.9406590942262119, 'bagging_freq': 1, 'lambda_l1': 7.620481786158549, 'lambda_l2': 0.08916674715636537, 'min_child_samples': 18, 'max_depth': 3, 'max_bin': 427, 'min_data_in_leaf': 77, 'extra_trees': False, 'early_stopping_rounds': 13, 'path_smooth': 0.3584657285442726, 'min_gain_to_split': 0.05793452976256486}. Best is trial 5 with value: 177.45662999448214.

Mejor trial hasta ahora: RMSE=177.456630, Parámetros={'num_leaves': 62, 'learning_rate': 0.01875220945578641, 'feature_fraction': 0.9878338511058234, 'bagging_fraction': 0.9325398470083344, 'bagging_freq': 10, 'lambda_l1': 1.1309571585271483, 'lambda_l2': 0.002404915432737351, 'min_child_samples': 47, 'max_depth': 3, 'max_bin': 178, 'min_data_in_leaf': 23, 'extra_trees': False, 'early_stopping_rounds': 21, 'path_smooth': 0.8287375091519293, 'min_gain_to_split': 0.17837666334679464}

[I 2025-07-13 12:11:06,403] Trial 7 finished with value: 177.47946005308373 and parameters: {'num_leaves': 89, 'learning_rate': 0.08330803890301997, 'feature_fraction': 0.7323592099410596, 'bagging_fraction': 0.7190675050858071, 'bagging_freq': 4, 'lambda_l1': 8.445977074223802e-06, 'lambda_l2': 0.036851536911881845, 'min_child_samples': 36, 'max_depth': 10, 'max_bin': 289, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 33, 'path_smooth': 0.770967179954561, 'min_gain_to_split': 0.24689779818219537}. Best is trial 5 with value: 177.45662999448214.

Mejor trial hasta ahora: RMSE=177.456630, Parámetros={'num_leaves': 62, 'learning_rate': 0.01875220945578641, 'feature_fraction': 0.9878338511058234, 'bagging_fraction': 0.9325398470083344, 'bagging_freq': 10, 'lambda_l1': 1.1309571585271483, 'lambda_l2': 0.002404915432737351, 'min_child_samples': 47, 'max_depth': 3, 'max_bin': 178, 'min_data_in_leaf': 23, 'extra_trees': False, 'early_stopping_rounds': 21, 'path_smooth': 0.8287375091519293, 'min_gain_to_split': 0.17837666334679464}

[I 2025-07-13 12:13:25,545] Trial 8 finished with value: 177.47097186731443 and parameters: {'num_leaves': 59, 'learning_rate': 0.042808491617570936, 'feature_fraction': 0.610167650697638, 'bagging_fraction': 0.7323674280979913, 'bagging_freq': 1, 'lambda_l1': 0.005341874754868531, 'lambda_l2': 6.748446817464346e-06, 'min_child_samples': 30, 'max_depth': 10, 'max_bin': 199, 'min_data_in_leaf': 53, 'extra_trees': True, 'early_stopping_rounds': 13, 'path_smooth': 0.289751452913768, 'min_gain_to_split': 0.08061064362700221}. Best is trial 5 with value: 177.45662999448214.

Mejor trial hasta ahora: RMSE=177.456630, Parámetros={'num_leaves': 62, 'learning_rate': 0.01875220945578641, 'feature_fraction': 0.9878338511058234, 'bagging_fraction': 0.9325398470083344, 'bagging_freq': 10, 'lambda_l1': 1.1309571585271483, 'lambda_l2': 0.002404915432737351, 'min_child_samples': 47, 'max_depth': 3, 'max_bin': 178, 'min_data_in_leaf': 23, 'extra_trees': False, 'early_stopping_rounds': 21, 'path_smooth': 0.8287375091519293, 'min_gain_to_split': 0.17837666334679464}

[I 2025-07-13 12:18:01,362] Trial 9 finished with value: 177.59843525933942 and parameters: {'num_leaves': 94, 'learning_rate': 0.156203869845265, 'feature_fraction': 0.8533615026041694, 'bagging_fraction': 0.9614381770563153, 'bagging_freq': 9, 'lambda_l1': 4.776728196949699e-07, 'lambda_l2': 1.0790237065789294, 'min_child_samples': 32, 'max_depth': 9, 'max_bin': 459, 'min_data_in_leaf': 45, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.8180147659224931, 'min_gain_to_split': 0.4303652916281717}. Best is trial 5 with value: 177.45662999448214.

Mejor trial hasta ahora: RMSE=177.456630, Parámetros={'num_leaves': 62, 'learning_rate': 0.01875220945578641, 'feature_fraction': 0.9878338511058234, 'bagging_fraction': 0.9325398470083344, 'bagging_freq': 10, 'lambda_l1': 1.1309571585271483, 'lambda_l2': 0.002404915432737351, 'min_child_samples': 47, 'max_depth': 3, 'max_bin': 178, 'min_data_in_leaf': 23, 'extra_trees': False, 'early_stopping_rounds': 21, 'path_smooth': 0.8287375091519293, 'min_gain_to_split': 0.17837666334679464}

[I 2025-07-13 12:20:14,077] Trial 10 finished with value: 177.46909000599072 and parameters: {'num_leaves': 15, 'learning_rate': 0.05681142678077596, 'feature_fraction': 0.7669644012595116, 'bagging_fraction': 0.7666323431412191, 'bagging_freq': 2, 'lambda_l1': 1.0927895733904103e-05, 'lambda_l2': 3.0632845126552133, 'min_child_samples': 23, 'max_depth': 7, 'max_bin': 381, 'min_data_in_leaf': 49, 'extra_trees': True, 'early_stopping_rounds': 20, 'path_smooth': 0.49724850589238545, 'min_gain_to_split': 0.15043915490838483}. Best is trial 5 with value: 177.45662999448214.

Mejor trial hasta ahora: RMSE=177.456630, Parámetros={'num_leaves': 62, 'learning_rate': 0.01875220945578641, 'feature_fraction': 0.9878338511058234, 'bagging_fraction': 0.9325398470083344, 'bagging_freq': 10, 'lambda_l1': 1.1309571585271483, 'lambda_l2': 0.002404915432737351, 'min_child_samples': 47, 'max_depth': 3, 'max_bin': 178, 'min_data_in_leaf': 23, 'extra_trees': False, 'early_stopping_rounds': 21, 'path_smooth': 0.8287375091519293, 'min_gain_to_split': 0.17837666334679464}

[I 2025-07-13 12:22:29,212] Trial 11 finished with value: 177.45190627601065 and parameters: {'num_leaves': 39, 'learning_rate': 0.011336695817840537, 'feature_fraction': 0.8438257335919588, 'bagging_fraction': 0.8508037069686585, 'bagging_freq': 1, 'lambda_l1': 3.21972053981427e-06, 'lambda_l2': 1.49414578394363, 'min_child_samples': 19, 'max_depth': 4, 'max_bin': 296, 'min_data_in_leaf': 99, 'extra_trees': False, 'early_stopping_rounds': 41, 'path_smooth': 0.23763754399239967, 'min_gain_to_split': 0.3641081743059298}. Best is trial 11 with value: 177.45190627601065.

Mejor trial hasta ahora: RMSE=177.451906, Parámetros={'num_leaves': 39, 'learning_rate': 0.011336695817840537, 'feature_fraction': 0.8438257335919588, 'bagging_fraction': 0.8508037069686585, 'bagging_freq': 1, 'lambda_l1': 3.21972053981427e-06, 'lambda_l2': 1.49414578394363, 'min_child_samples': 19, 'max_depth': 4, 'max_bin': 296, 'min_data_in_leaf': 99, 'extra_trees': False, 'early_stopping_rounds': 41, 'path_smooth': 0.23763754399239967, 'min_gain_to_split': 0.3641081743059298}

[I 2025-07-13 12:24:44,334] Trial 12 finished with value: 177.4518402196238 and parameters: {'num_leaves': 78, 'learning_rate': 0.010206070557576998, 'feature_fraction': 0.8784471213433285, 'bagging_fraction': 0.853169218052769, 'bagging_freq': 6, 'lambda_l1': 0.002727735266709211, 'lambda_l2': 6.3791369398325e-05, 'min_child_samples': 10, 'max_depth': 5, 'max_bin': 104, 'min_data_in_leaf': 100, 'extra_trees': False, 'early_stopping_rounds': 47, 'path_smooth': 0.06591993228324083, 'min_gain_to_split': 0.47016884607215803}. Best is trial 12 with value: 177.4518402196238.

Mejor trial hasta ahora: RMSE=177.451840, Parámetros={'num_leaves': 78, 'learning_rate': 0.010206070557576998, 'feature_fraction': 0.8784471213433285, 'bagging_fraction': 0.853169218052769, 'bagging_freq': 6, 'lambda_l1': 0.002727735266709211, 'lambda_l2': 6.3791369398325e-05, 'min_child_samples': 10, 'max_depth': 5, 'max_bin': 104, 'min_data_in_leaf': 100, 'extra_trees': False, 'early_stopping_rounds': 47, 'path_smooth': 0.06591993228324083, 'min_gain_to_split': 0.47016884607215803}

[I 2025-07-13 12:27:04,352] Trial 13 finished with value: 177.45175446506929 and parameters: {'num_leaves': 76, 'learning_rate': 0.010374489038263175, 'feature_fraction': 0.8791236726666275, 'bagging_fraction': 0.8365092100994954, 'bagging_freq': 6, 'lambda_l1': 0.0018811879800026158, 'lambda_l2': 0.0001970044973812117, 'min_child_samples': 10, 'max_depth': 5, 'max_bin': 110, 'min_data_in_leaf': 100, 'extra_trees': False, 'early_stopping_rounds': 50, 'path_smooth': 0.05027279999990281, 'min_gain_to_split': 0.49367144995508916}. Best is trial 13 with value: 177.45175446506929.

Mejor trial hasta ahora: RMSE=177.451754, Parámetros={'num_leaves': 76, 'learning_rate': 0.010374489038263175, 'feature_fraction': 0.8791236726666275, 'bagging_fraction': 0.8365092100994954, 'bagging_freq': 6, 'lambda_l1': 0.0018811879800026158, 'lambda_l2': 0.0001970044973812117, 'min_child_samples': 10, 'max_depth': 5, 'max_bin': 110, 'min_data_in_leaf': 100, 'extra_trees': False, 'early_stopping_rounds': 50, 'path_smooth': 0.05027279999990281, 'min_gain_to_split': 0.49367144995508916}

[I 2025-07-13 12:29:38,623] Trial 14 finished with value: 177.45105470703513 and parameters: {'num_leaves': 77, 'learning_rate': 0.010154893009675833, 'feature_fraction': 0.9183295509129431, 'bagging_fraction': 0.8059496586274636, 'bagging_freq': 7, 'lambda_l1': 0.002228713371400192, 'lambda_l2': 5.965006744280542e-05, 'min_child_samples': 10, 'max_depth': 5, 'max_bin': 101, 'min_data_in_leaf': 100, 'extra_trees': False, 'early_stopping_rounds': 50, 'path_smooth': 0.0737471564880055, 'min_gain_to_split': 0.4715202094872239}. Best is trial 14 with value: 177.45105470703513.

Mejor trial hasta ahora: RMSE=177.451055, Parámetros={'num_leaves': 77, 'learning_rate': 0.010154893009675833, 'feature_fraction': 0.9183295509129431, 'bagging_fraction': 0.8059496586274636, 'bagging_freq': 7, 'lambda_l1': 0.002228713371400192, 'lambda_l2': 5.965006744280542e-05, 'min_child_samples': 10, 'max_depth': 5, 'max_bin': 101, 'min_data_in_leaf': 100, 'extra_trees': False, 'early_stopping_rounds': 50, 'path_smooth': 0.0737471564880055, 'min_gain_to_split': 0.4715202094872239}

[I 2025-07-13 12:32:09,023] Trial 15 finished with value: 177.4589362605023 and parameters: {'num_leaves': 75, 'learning_rate': 0.019293369292093035, 'feature_fraction': 0.9178581456448356, 'bagging_fraction': 0.8053707842057332, 'bagging_freq': 8, 'lambda_l1': 0.042897139990903915, 'lambda_l2': 0.00022756846991822064, 'min_child_samples': 10, 'max_depth': 5, 'max_bin': 101, 'min_data_in_leaf': 82, 'extra_trees': False, 'early_stopping_rounds': 50, 'path_smooth': 0.004478036080319735, 'min_gain_to_split': 0.37549861800626294}. Best is trial 14 with value: 177.45105470703513.

Mejor trial hasta ahora: RMSE=177.451055, Parámetros={'num_leaves': 77, 'learning_rate': 0.010154893009675833, 'feature_fraction': 0.9183295509129431, 'bagging_fraction': 0.8059496586274636, 'bagging_freq': 7, 'lambda_l1': 0.002228713371400192, 'lambda_l2': 5.965006744280542e-05, 'min_child_samples': 10, 'max_depth': 5, 'max_bin': 101, 'min_data_in_leaf': 100, 'extra_trees': False, 'early_stopping_rounds': 50, 'path_smooth': 0.0737471564880055, 'min_gain_to_split': 0.4715202094872239}

[I 2025-07-13 12:34:34,244] Trial 16 finished with value: 177.46189455585036 and parameters: {'num_leaves': 74, 'learning_rate': 0.024081743426268926, 'feature_fraction': 0.9388232439653788, 'bagging_fraction': 0.8199249519372853, 'bagging_freq': 5, 'lambda_l1': 0.0002648976777559709, 'lambda_l2': 1.3129174195141697e-07, 'min_child_samples': 15, 'max_depth': 5, 'max_bin': 189, 'min_data_in_leaf': 78, 'extra_trees': False, 'early_stopping_rounds': 45, 'path_smooth': 0.12593120375921885, 'min_gain_to_split': 0.4855201949985405}. Best is trial 14 with value: 177.45105470703513.

Mejor trial hasta ahora: RMSE=177.451055, Parámetros={'num_leaves': 77, 'learning_rate': 0.010154893009675833, 'feature_fraction': 0.9183295509129431, 'bagging_fraction': 0.8059496586274636, 'bagging_freq': 7, 'lambda_l1': 0.002228713371400192, 'lambda_l2': 5.965006744280542e-05, 'min_child_samples': 10, 'max_depth': 5, 'max_bin': 101, 'min_data_in_leaf': 100, 'extra_trees': False, 'early_stopping_rounds': 50, 'path_smooth': 0.0737471564880055, 'min_gain_to_split': 0.4715202094872239}

[I 2025-07-13 12:37:30,398] Trial 17 finished with value: 177.46913814999206 and parameters: {'num_leaves': 87, 'learning_rate': 0.031348511591493496, 'feature_fraction': 0.8366070683982902, 'bagging_fraction': 0.8958654007917661, 'bagging_freq': 7, 'lambda_l1': 0.0002339202948337775, 'lambda_l2': 5.115505282581392e-06, 'min_child_samples': 14, 'max_depth': 8, 'max_bin': 154, 'min_data_in_leaf': 87, 'extra_trees': False, 'early_stopping_rounds': 41, 'path_smooth': 0.9863647855153872, 'min_gain_to_split': 0.3771431546866458}. Best is trial 14 with value: 177.45105470703513.

Mejor trial hasta ahora: RMSE=177.451055, Parámetros={'num_leaves': 77, 'learning_rate': 0.010154893009675833, 'feature_fraction': 0.9183295509129431, 'bagging_fraction': 0.8059496586274636, 'bagging_freq': 7, 'lambda_l1': 0.002228713371400192, 'lambda_l2': 5.965006744280542e-05, 'min_child_samples': 10, 'max_depth': 5, 'max_bin': 101, 'min_data_in_leaf': 100, 'extra_trees': False, 'early_stopping_rounds': 50, 'path_smooth': 0.0737471564880055, 'min_gain_to_split': 0.4715202094872239}

[I 2025-07-13 12:40:07,178] Trial 18 finished with value: 177.45604877639715 and parameters: {'num_leaves': 68, 'learning_rate': 0.01491609761708737, 'feature_fraction': 0.9437177608251541, 'bagging_fraction': 0.7734499525100793, 'bagging_freq': 6, 'lambda_l1': 0.05915440918906229, 'lambda_l2': 0.0012874773694215435, 'min_child_samples': 21, 'max_depth': 6, 'max_bin': 234, 'min_data_in_leaf': 67, 'extra_trees': False, 'early_stopping_rounds': 49, 'path_smooth': 0.4299745589163554, 'min_gain_to_split': 0.30254918430923333}. Best is trial 14 with value: 177.45105470703513.

Mejor trial hasta ahora: RMSE=177.451055, Parámetros={'num_leaves': 77, 'learning_rate': 0.010154893009675833, 'feature_fraction': 0.9183295509129431, 'bagging_fraction': 0.8059496586274636, 'bagging_freq': 7, 'lambda_l1': 0.002228713371400192, 'lambda_l2': 5.965006744280542e-05, 'min_child_samples': 10, 'max_depth': 5, 'max_bin': 101, 'min_data_in_leaf': 100, 'extra_trees': False, 'early_stopping_rounds': 50, 'path_smooth': 0.0737471564880055, 'min_gain_to_split': 0.4715202094872239}

[I 2025-07-13 12:41:56,304] Trial 19 finished with value: 177.46764681659076 and parameters: {'num_leaves': 98, 'learning_rate': 0.03056840535816228, 'feature_fraction': 0.8147324663134726, 'bagging_fraction': 0.8275550329909136, 'bagging_freq': 8, 'lambda_l1': 0.0025909693251191376, 'lambda_l2': 4.153753480865991e-05, 'min_child_samples': 39, 'max_depth': 4, 'max_bin': 143, 'min_data_in_leaf': 67, 'extra_trees': False, 'early_stopping_rounds': 42, 'path_smooth': 0.13046990419595822, 'min_gain_to_split': 0.49863355389930464}. Best is trial 14 with value: 177.45105470703513.

Mejor trial hasta ahora: RMSE=177.451055, Parámetros={'num_leaves': 77, 'learning_rate': 0.010154893009675833, 'feature_fraction': 0.9183295509129431, 'bagging_fraction': 0.8059496586274636, 'bagging_freq': 7, 'lambda_l1': 0.002228713371400192, 'lambda_l2': 5.965006744280542e-05, 'min_child_samples': 10, 'max_depth': 5, 'max_bin': 101, 'min_data_in_leaf': 100, 'extra_trees': False, 'early_stopping_rounds': 50, 'path_smooth': 0.0737471564880055, 'min_gain_to_split': 0.4715202094872239}

[I 2025-07-13 12:43:34,038] Trial 20 finished with value: 177.45047526292933 and parameters: {'num_leaves': 82, 'learning_rate': 0.014023347876983932, 'feature_fraction': 0.8933888670293704, 'bagging_fraction': 0.8958428157396495, 'bagging_freq': 4, 'lambda_l1': 6.385957313624097e-05, 'lambda_l2': 3.885463992469711e-07, 'min_child_samples': 14, 'max_depth': 4, 'max_bin': 248, 'min_data_in_leaf': 91, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.028554005793492022, 'min_gain_to_split': 0.4303403804814074}. Best is trial 20 with value: 177.45047526292933.

Mejor trial hasta ahora: RMSE=177.450475, Parámetros={'num_leaves': 82, 'learning_rate': 0.014023347876983932, 'feature_fraction': 0.8933888670293704, 'bagging_fraction': 0.8958428157396495, 'bagging_freq': 4, 'lambda_l1': 6.385957313624097e-05, 'lambda_l2': 3.885463992469711e-07, 'min_child_samples': 14, 'max_depth': 4, 'max_bin': 248, 'min_data_in_leaf': 91, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.028554005793492022, 'min_gain_to_split': 0.4303403804814074}

[I 2025-07-13 12:45:47,349] Trial 21 finished with value: 177.44848604584234 and parameters: {'num_leaves': 84, 'learning_rate': 0.014493737202071621, 'feature_fraction': 0.9593513916296669, 'bagging_fraction': 0.9037633466282822, 'bagging_freq': 4, 'lambda_l1': 1.0750086398103041e-08, 'lambda_l2': 4.263678238900164e-07, 'min_child_samples': 15, 'max_depth': 4, 'max_bin': 244, 'min_data_in_leaf': 92, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.6651746294259466, 'min_gain_to_split': 0.4257402086067284}. Best is trial 21 with value: 177.44848604584234.

Mejor trial hasta ahora: RMSE=177.448486, Parámetros={'num_leaves': 84, 'learning_rate': 0.014493737202071621, 'feature_fraction': 0.9593513916296669, 'bagging_fraction': 0.9037633466282822, 'bagging_freq': 4, 'lambda_l1': 1.0750086398103041e-08, 'lambda_l2': 4.263678238900164e-07, 'min_child_samples': 15, 'max_depth': 4, 'max_bin': 244, 'min_data_in_leaf': 92, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.6651746294259466, 'min_gain_to_split': 0.4257402086067284}

[I 2025-07-13 12:47:22,647] Trial 22 finished with value: 177.4529864180542 and parameters: {'num_leaves': 83, 'learning_rate': 0.015362546899000754, 'feature_fraction': 0.9572565339004568, 'bagging_fraction': 0.994478688364546, 'bagging_freq': 4, 'lambda_l1': 1.147424251344576e-08, 'lambda_l2': 3.468643656700826e-07, 'min_child_samples': 16, 'max_depth': 4, 'max_bin': 239, 'min_data_in_leaf': 88, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.6224543798910074, 'min_gain_to_split': 0.32256350791284083}. Best is trial 21 with value: 177.44848604584234.

Mejor trial hasta ahora: RMSE=177.448486, Parámetros={'num_leaves': 84, 'learning_rate': 0.014493737202071621, 'feature_fraction': 0.9593513916296669, 'bagging_fraction': 0.9037633466282822, 'bagging_freq': 4, 'lambda_l1': 1.0750086398103041e-08, 'lambda_l2': 4.263678238900164e-07, 'min_child_samples': 15, 'max_depth': 4, 'max_bin': 244, 'min_data_in_leaf': 92, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.6651746294259466, 'min_gain_to_split': 0.4257402086067284}

[I 2025-07-13 12:49:20,408] Trial 23 finished with value: 177.45005625675734 and parameters: {'num_leaves': 66, 'learning_rate': 0.013993500972232169, 'feature_fraction': 0.9117150942392832, 'bagging_fraction': 0.8974348798250595, 'bagging_freq': 3, 'lambda_l1': 5.719755646849269e-05, 'lambda_l2': 1.145017678714142e-08, 'min_child_samples': 14, 'max_depth': 4, 'max_bin': 251, 'min_data_in_leaf': 91, 'extra_trees': True, 'early_stopping_rounds': 32, 'path_smooth': 0.5376260405862204, 'min_gain_to_split': 0.4353200109189678}. Best is trial 21 with value: 177.44848604584234.

Mejor trial hasta ahora: RMSE=177.448486, Parámetros={'num_leaves': 84, 'learning_rate': 0.014493737202071621, 'feature_fraction': 0.9593513916296669, 'bagging_fraction': 0.9037633466282822, 'bagging_freq': 4, 'lambda_l1': 1.0750086398103041e-08, 'lambda_l2': 4.263678238900164e-07, 'min_child_samples': 15, 'max_depth': 4, 'max_bin': 244, 'min_data_in_leaf': 92, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.6651746294259466, 'min_gain_to_split': 0.4257402086067284}

[I 2025-07-13 12:51:20,610] Trial 24 finished with value: 177.45796594276624 and parameters: {'num_leaves': 66, 'learning_rate': 0.026291859712901867, 'feature_fraction': 0.9958848666433324, 'bagging_fraction': 0.8946886893685754, 'bagging_freq': 3, 'lambda_l1': 3.8947087482184615e-05, 'lambda_l2': 1.0680309909164713e-08, 'min_child_samples': 14, 'max_depth': 4, 'max_bin': 246, 'min_data_in_leaf': 90, 'extra_trees': True, 'early_stopping_rounds': 32, 'path_smooth': 0.6406332172472392, 'min_gain_to_split': 0.42446684635733206}. Best is trial 21 with value: 177.44848604584234.

Mejor trial hasta ahora: RMSE=177.448486, Parámetros={'num_leaves': 84, 'learning_rate': 0.014493737202071621, 'feature_fraction': 0.9593513916296669, 'bagging_fraction': 0.9037633466282822, 'bagging_freq': 4, 'lambda_l1': 1.0750086398103041e-08, 'lambda_l2': 4.263678238900164e-07, 'min_child_samples': 15, 'max_depth': 4, 'max_bin': 244, 'min_data_in_leaf': 92, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.6651746294259466, 'min_gain_to_split': 0.4257402086067284}

[I 2025-07-13 12:53:05,245] Trial 25 finished with value: 177.4468450370319 and parameters: {'num_leaves': 53, 'learning_rate': 0.01438580796972246, 'feature_fraction': 0.9039381085177218, 'bagging_fraction': 0.9123298003082174, 'bagging_freq': 3, 'lambda_l1': 5.662573734224287e-05, 'lambda_l2': 6.176564586281621e-07, 'min_child_samples': 24, 'max_depth': 3, 'max_bin': 344, 'min_data_in_leaf': 72, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.7279990099279795, 'min_gain_to_split': 0.4182475021804156}. Best is trial 25 with value: 177.4468450370319.

Mejor trial hasta ahora: RMSE=177.446845, Parámetros={'num_leaves': 53, 'learning_rate': 0.01438580796972246, 'feature_fraction': 0.9039381085177218, 'bagging_fraction': 0.9123298003082174, 'bagging_freq': 3, 'lambda_l1': 5.662573734224287e-05, 'lambda_l2': 6.176564586281621e-07, 'min_child_samples': 24, 'max_depth': 3, 'max_bin': 344, 'min_data_in_leaf': 72, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.7279990099279795, 'min_gain_to_split': 0.4182475021804156}

[I 2025-07-13 12:54:54,793] Trial 26 finished with value: 177.4513002705898 and parameters: {'num_leaves': 57, 'learning_rate': 0.019227528215071225, 'feature_fraction': 0.9496223026919981, 'bagging_fraction': 0.9206444997033564, 'bagging_freq': 3, 'lambda_l1': 1.0230435314455833e-08, 'lambda_l2': 7.52549044775317e-08, 'min_child_samples': 25, 'max_depth': 3, 'max_bin': 341, 'min_data_in_leaf': 66, 'extra_trees': True, 'early_stopping_rounds': 23, 'path_smooth': 0.7065558676400303, 'min_gain_to_split': 0.41279651308113013}. Best is trial 25 with value: 177.4468450370319.

Mejor trial hasta ahora: RMSE=177.446845, Parámetros={'num_leaves': 53, 'learning_rate': 0.01438580796972246, 'feature_fraction': 0.9039381085177218, 'bagging_fraction': 0.9123298003082174, 'bagging_freq': 3, 'lambda_l1': 5.662573734224287e-05, 'lambda_l2': 6.176564586281621e-07, 'min_child_samples': 24, 'max_depth': 3, 'max_bin': 344, 'min_data_in_leaf': 72, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.7279990099279795, 'min_gain_to_split': 0.4182475021804156}

[I 2025-07-13 12:56:41,818] Trial 27 finished with value: 177.46389361950588 and parameters: {'num_leaves': 52, 'learning_rate': 0.040696532423978575, 'feature_fraction': 0.9175590348432299, 'bagging_fraction': 0.9762758288070235, 'bagging_freq': 3, 'lambda_l1': 3.393919865398472e-06, 'lambda_l2': 9.811138861151772e-07, 'min_child_samples': 21, 'max_depth': 3, 'max_bin': 340, 'min_data_in_leaf': 75, 'extra_trees': True, 'early_stopping_rounds': 34, 'path_smooth': 0.8991762748145777, 'min_gain_to_split': 0.28612876649132113}. Best is trial 25 with value: 177.4468450370319.

Mejor trial hasta ahora: RMSE=177.446845, Parámetros={'num_leaves': 53, 'learning_rate': 0.01438580796972246, 'feature_fraction': 0.9039381085177218, 'bagging_fraction': 0.9123298003082174, 'bagging_freq': 3, 'lambda_l1': 5.662573734224287e-05, 'lambda_l2': 6.176564586281621e-07, 'min_child_samples': 24, 'max_depth': 3, 'max_bin': 344, 'min_data_in_leaf': 72, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.7279990099279795, 'min_gain_to_split': 0.4182475021804156}

[I 2025-07-13 12:59:23,671] Trial 28 finished with value: 177.45942559506685 and parameters: {'num_leaves': 50, 'learning_rate': 0.02145851485673571, 'feature_fraction': 0.9725903702700844, 'bagging_fraction': 0.8703867034602377, 'bagging_freq': 5, 'lambda_l1': 2.0296863035660935e-06, 'lambda_l2': 1.1921364968803625e-08, 'min_child_samples': 27, 'max_depth': 6, 'max_bin': 334, 'min_data_in_leaf': 84, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.5396730735374388, 'min_gain_to_split': 0.34338478641727493}. Best is trial 25 with value: 177.4468450370319.

Mejor trial hasta ahora: RMSE=177.446845, Parámetros={'num_leaves': 53, 'learning_rate': 0.01438580796972246, 'feature_fraction': 0.9039381085177218, 'bagging_fraction': 0.9123298003082174, 'bagging_freq': 3, 'lambda_l1': 5.662573734224287e-05, 'lambda_l2': 6.176564586281621e-07, 'min_child_samples': 24, 'max_depth': 3, 'max_bin': 344, 'min_data_in_leaf': 72, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.7279990099279795, 'min_gain_to_split': 0.4182475021804156}

[I 2025-07-13 13:01:30,767] Trial 29 finished with value: 177.50024093378047 and parameters: {'num_leaves': 65, 'learning_rate': 0.09242432718042025, 'feature_fraction': 0.8142106426538911, 'bagging_fraction': 0.920666952916808, 'bagging_freq': 2, 'lambda_l1': 4.673976619408477e-05, 'lambda_l2': 1.7181207488904815e-06, 'min_child_samples': 18, 'max_depth': 4, 'max_bin': 264, 'min_data_in_leaf': 72, 'extra_trees': True, 'early_stopping_rounds': 37, 'path_smooth': 0.7097972791402332, 'min_gain_to_split': 0.4032146785722902}. Best is trial 25 with value: 177.4468450370319.

Mejor trial hasta ahora: RMSE=177.446845, Parámetros={'num_leaves': 53, 'learning_rate': 0.01438580796972246, 'feature_fraction': 0.9039381085177218, 'bagging_fraction': 0.9123298003082174, 'bagging_freq': 3, 'lambda_l1': 5.662573734224287e-05, 'lambda_l2': 6.176564586281621e-07, 'min_child_samples': 24, 'max_depth': 3, 'max_bin': 344, 'min_data_in_leaf': 72, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.7279990099279795, 'min_gain_to_split': 0.4182475021804156}

[I 2025-07-13 13:03:14,834] Trial 30 finished with value: 177.45084806338917 and parameters: {'num_leaves': 30, 'learning_rate': 0.016976685592824524, 'feature_fraction': 0.696695433310658, 'bagging_fraction': 0.8740398647496626, 'bagging_freq': 3, 'lambda_l1': 0.030642008782327798, 'lambda_l2': 5.631487157083441e-08, 'min_child_samples': 34, 'max_depth': 3, 'max_bin': 215, 'min_data_in_leaf': 58, 'extra_trees': True, 'early_stopping_rounds': 30, 'path_smooth': 0.5345598738634232, 'min_gain_to_split': 0.2188769006468256}. Best is trial 25 with value: 177.4468450370319.

Mejor trial hasta ahora: RMSE=177.446845, Parámetros={'num_leaves': 53, 'learning_rate': 0.01438580796972246, 'feature_fraction': 0.9039381085177218, 'bagging_fraction': 0.9123298003082174, 'bagging_freq': 3, 'lambda_l1': 5.662573734224287e-05, 'lambda_l2': 6.176564586281621e-07, 'min_child_samples': 24, 'max_depth': 3, 'max_bin': 344, 'min_data_in_leaf': 72, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.7279990099279795, 'min_gain_to_split': 0.4182475021804156}

[I 2025-07-13 13:05:32,813] Trial 31 finished with value: 177.44980706064104 and parameters: {'num_leaves': 45, 'learning_rate': 0.012705038191136423, 'feature_fraction': 0.8792764848147284, 'bagging_fraction': 0.9112776729505613, 'bagging_freq': 2, 'lambda_l1': 4.703747450787464e-07, 'lambda_l2': 3.3794071640943383e-07, 'min_child_samples': 50, 'max_depth': 7, 'max_bin': 369, 'min_data_in_leaf': 93, 'extra_trees': True, 'early_stopping_rounds': 37, 'path_smooth': 0.4417457398879847, 'min_gain_to_split': 0.004641588896625026}. Best is trial 25 with value: 177.4468450370319.

Mejor trial hasta ahora: RMSE=177.446845, Parámetros={'num_leaves': 53, 'learning_rate': 0.01438580796972246, 'feature_fraction': 0.9039381085177218, 'bagging_fraction': 0.9123298003082174, 'bagging_freq': 3, 'lambda_l1': 5.662573734224287e-05, 'lambda_l2': 6.176564586281621e-07, 'min_child_samples': 24, 'max_depth': 3, 'max_bin': 344, 'min_data_in_leaf': 72, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.7279990099279795, 'min_gain_to_split': 0.4182475021804156}

[I 2025-07-13 13:08:27,553] Trial 32 finished with value: 177.47687947706663 and parameters: {'num_leaves': 45, 'learning_rate': 0.03828646458397878, 'feature_fraction': 0.8599698503014036, 'bagging_fraction': 0.960301729148108, 'bagging_freq': 2, 'lambda_l1': 4.932926208370626e-08, 'lambda_l2': 3.2009545895838893e-07, 'min_child_samples': 43, 'max_depth': 7, 'max_bin': 378, 'min_data_in_leaf': 94, 'extra_trees': True, 'early_stopping_rounds': 17, 'path_smooth': 0.43056586408001396, 'min_gain_to_split': 0.007975682286966428}. Best is trial 25 with value: 177.4468450370319.

Mejor trial hasta ahora: RMSE=177.446845, Parámetros={'num_leaves': 53, 'learning_rate': 0.01438580796972246, 'feature_fraction': 0.9039381085177218, 'bagging_fraction': 0.9123298003082174, 'bagging_freq': 3, 'lambda_l1': 5.662573734224287e-05, 'lambda_l2': 6.176564586281621e-07, 'min_child_samples': 24, 'max_depth': 3, 'max_bin': 344, 'min_data_in_leaf': 72, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.7279990099279795, 'min_gain_to_split': 0.4182475021804156}

[I 2025-07-13 13:11:16,395] Trial 33 finished with value: 177.45065838828978 and parameters: {'num_leaves': 55, 'learning_rate': 0.013125613525205563, 'feature_fraction': 0.8999098102444413, 'bagging_fraction': 0.911782724199604, 'bagging_freq': 3, 'lambda_l1': 6.932355455761777e-07, 'lambda_l2': 2.3064393118349684e-08, 'min_child_samples': 50, 'max_depth': 8, 'max_bin': 320, 'min_data_in_leaf': 82, 'extra_trees': True, 'early_stopping_rounds': 37, 'path_smooth': 0.4463161343811588, 'min_gain_to_split': 0.15296789889425189}. Best is trial 25 with value: 177.4468450370319.

Mejor trial hasta ahora: RMSE=177.446845, Parámetros={'num_leaves': 53, 'learning_rate': 0.01438580796972246, 'feature_fraction': 0.9039381085177218, 'bagging_fraction': 0.9123298003082174, 'bagging_freq': 3, 'lambda_l1': 5.662573734224287e-05, 'lambda_l2': 6.176564586281621e-07, 'min_child_samples': 24, 'max_depth': 3, 'max_bin': 344, 'min_data_in_leaf': 72, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.7279990099279795, 'min_gain_to_split': 0.4182475021804156}

[I 2025-07-13 13:13:56,188] Trial 34 finished with value: 177.45499015948448 and parameters: {'num_leaves': 33, 'learning_rate': 0.014588694337634989, 'feature_fraction': 0.923886277805564, 'bagging_fraction': 0.8811512767671358, 'bagging_freq': 2, 'lambda_l1': 6.675706252375174e-08, 'lambda_l2': 1.704630526628915e-05, 'min_child_samples': 38, 'max_depth': 8, 'max_bin': 365, 'min_data_in_leaf': 94, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.6880370712518162, 'min_gain_to_split': 0.44410772920697145}. Best is trial 25 with value: 177.4468450370319.

Mejor trial hasta ahora: RMSE=177.446845, Parámetros={'num_leaves': 53, 'learning_rate': 0.01438580796972246, 'feature_fraction': 0.9039381085177218, 'bagging_fraction': 0.9123298003082174, 'bagging_freq': 3, 'lambda_l1': 5.662573734224287e-05, 'lambda_l2': 6.176564586281621e-07, 'min_child_samples': 24, 'max_depth': 3, 'max_bin': 344, 'min_data_in_leaf': 72, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.7279990099279795, 'min_gain_to_split': 0.4182475021804156}

[I 2025-07-13 13:16:26,018] Trial 35 finished with value: 177.44726715918597 and parameters: {'num_leaves': 46, 'learning_rate': 0.01182131242434692, 'feature_fraction': 0.8770231704861932, 'bagging_fraction': 0.9060986669810392, 'bagging_freq': 5, 'lambda_l1': 3.8782668825968125e-07, 'lambda_l2': 1.6214364054956158e-06, 'min_child_samples': 42, 'max_depth': 6, 'max_bin': 413, 'min_data_in_leaf': 94, 'extra_trees': True, 'early_stopping_rounds': 34, 'path_smooth': 0.5007853030628996, 'min_gain_to_split': 0.006887950563660901}. Best is trial 25 with value: 177.4468450370319.

Mejor trial hasta ahora: RMSE=177.446845, Parámetros={'num_leaves': 53, 'learning_rate': 0.01438580796972246, 'feature_fraction': 0.9039381085177218, 'bagging_fraction': 0.9123298003082174, 'bagging_freq': 3, 'lambda_l1': 5.662573734224287e-05, 'lambda_l2': 6.176564586281621e-07, 'min_child_samples': 24, 'max_depth': 3, 'max_bin': 344, 'min_data_in_leaf': 72, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.7279990099279795, 'min_gain_to_split': 0.4182475021804156}

[I 2025-07-13 13:18:42,623] Trial 36 finished with value: 177.45388777097523 and parameters: {'num_leaves': 45, 'learning_rate': 0.012202887161150481, 'feature_fraction': 0.8746803636077449, 'bagging_fraction': 0.9400260715492473, 'bagging_freq': 5, 'lambda_l1': 2.0544495033795498e-07, 'lambda_l2': 1.1555673388037435e-06, 'min_child_samples': 43, 'max_depth': 7, 'max_bin': 461, 'min_data_in_leaf': 95, 'extra_trees': True, 'early_stopping_rounds': 35, 'path_smooth': 0.3766359379233113, 'min_gain_to_split': 0.00200101281667946}. Best is trial 25 with value: 177.4468450370319.

Mejor trial hasta ahora: RMSE=177.446845, Parámetros={'num_leaves': 53, 'learning_rate': 0.01438580796972246, 'feature_fraction': 0.9039381085177218, 'bagging_fraction': 0.9123298003082174, 'bagging_freq': 3, 'lambda_l1': 5.662573734224287e-05, 'lambda_l2': 6.176564586281621e-07, 'min_child_samples': 24, 'max_depth': 3, 'max_bin': 344, 'min_data_in_leaf': 72, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.7279990099279795, 'min_gain_to_split': 0.4182475021804156}

[I 2025-07-13 13:20:44,963] Trial 37 finished with value: 177.4620889103682 and parameters: {'num_leaves': 27, 'learning_rate': 0.02321101017018576, 'feature_fraction': 0.9670286350810702, 'bagging_fraction': 0.9580665277069111, 'bagging_freq': 4, 'lambda_l1': 2.6789259269107545e-08, 'lambda_l2': 1.8283504862520145e-07, 'min_child_samples': 50, 'max_depth': 6, 'max_bin': 415, 'min_data_in_leaf': 85, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.5911471938994011, 'min_gain_to_split': 0.02770729146172382}. Best is trial 25 with value: 177.4468450370319.

Mejor trial hasta ahora: RMSE=177.446845, Parámetros={'num_leaves': 53, 'learning_rate': 0.01438580796972246, 'feature_fraction': 0.9039381085177218, 'bagging_fraction': 0.9123298003082174, 'bagging_freq': 3, 'lambda_l1': 5.662573734224287e-05, 'lambda_l2': 6.176564586281621e-07, 'min_child_samples': 24, 'max_depth': 3, 'max_bin': 344, 'min_data_in_leaf': 72, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.7279990099279795, 'min_gain_to_split': 0.4182475021804156}

[I 2025-07-13 13:22:30,485] Trial 38 finished with value: 177.58957083786302 and parameters: {'num_leaves': 36, 'learning_rate': 0.2665668332899408, 'feature_fraction': 0.7726897526679395, 'bagging_fraction': 0.9139862261024176, 'bagging_freq': 5, 'lambda_l1': 8.586415755053742e-07, 'lambda_l2': 1.6279979897209145e-06, 'min_child_samples': 46, 'max_depth': 6, 'max_bin': 497, 'min_data_in_leaf': 74, 'extra_trees': True, 'early_stopping_rounds': 37, 'path_smooth': 0.7810265653172, 'min_gain_to_split': 0.11352557379391257}. Best is trial 25 with value: 177.4468450370319.

Mejor trial hasta ahora: RMSE=177.446845, Parámetros={'num_leaves': 53, 'learning_rate': 0.01438580796972246, 'feature_fraction': 0.9039381085177218, 'bagging_fraction': 0.9123298003082174, 'bagging_freq': 3, 'lambda_l1': 5.662573734224287e-05, 'lambda_l2': 6.176564586281621e-07, 'min_child_samples': 24, 'max_depth': 3, 'max_bin': 344, 'min_data_in_leaf': 72, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.7279990099279795, 'min_gain_to_split': 0.4182475021804156}

[I 2025-07-13 13:24:47,026] Trial 39 finished with value: 177.45490834511753 and parameters: {'num_leaves': 49, 'learning_rate': 0.017575439653880347, 'feature_fraction': 0.8273339850314295, 'bagging_fraction': 0.8649286617966756, 'bagging_freq': 4, 'lambda_l1': 1.41161373756042e-07, 'lambda_l2': 1.2133638612744819e-05, 'min_child_samples': 41, 'max_depth': 9, 'max_bin': 403, 'min_data_in_leaf': 79, 'extra_trees': True, 'early_stopping_rounds': 39, 'path_smooth': 0.8917328949332809, 'min_gain_to_split': 0.05344396445932268}. Best is trial 25 with value: 177.4468450370319.

Mejor trial hasta ahora: RMSE=177.446845, Parámetros={'num_leaves': 53, 'learning_rate': 0.01438580796972246, 'feature_fraction': 0.9039381085177218, 'bagging_fraction': 0.9123298003082174, 'bagging_freq': 3, 'lambda_l1': 5.662573734224287e-05, 'lambda_l2': 6.176564586281621e-07, 'min_child_samples': 24, 'max_depth': 3, 'max_bin': 344, 'min_data_in_leaf': 72, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.7279990099279795, 'min_gain_to_split': 0.4182475021804156}

[I 2025-07-13 13:26:38,865] Trial 40 finished with value: 177.5728157837676 and parameters: {'num_leaves': 24, 'learning_rate': 0.16763411359387845, 'feature_fraction': 0.8633572343914035, 'bagging_fraction': 0.9282983751896652, 'bagging_freq': 1, 'lambda_l1': 1.633842412745322e-07, 'lambda_l2': 5.855599485424454e-07, 'min_child_samples': 48, 'max_depth': 7, 'max_bin': 442, 'min_data_in_leaf': 61, 'extra_trees': True, 'early_stopping_rounds': 17, 'path_smooth': 0.366608926755878, 'min_gain_to_split': 0.09922304660770975}. Best is trial 25 with value: 177.4468450370319.

Mejor trial hasta ahora: RMSE=177.446845, Parámetros={'num_leaves': 53, 'learning_rate': 0.01438580796972246, 'feature_fraction': 0.9039381085177218, 'bagging_fraction': 0.9123298003082174, 'bagging_freq': 3, 'lambda_l1': 5.662573734224287e-05, 'lambda_l2': 6.176564586281621e-07, 'min_child_samples': 24, 'max_depth': 3, 'max_bin': 344, 'min_data_in_leaf': 72, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.7279990099279795, 'min_gain_to_split': 0.4182475021804156}

[I 2025-07-13 13:28:10,412] Trial 41 finished with value: 177.44634805061435 and parameters: {'num_leaves': 42, 'learning_rate': 0.029060225434901842, 'feature_fraction': 0.7927601669278636, 'bagging_fraction': 0.9062630187635413, 'bagging_freq': 2, 'lambda_l1': 8.874585531798186e-06, 'lambda_l2': 3.986027947089727e-06, 'min_child_samples': 29, 'max_depth': 3, 'max_bin': 276, 'min_data_in_leaf': 32, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.4859562586494468, 'min_gain_to_split': 0.19825301847130325}. Best is trial 41 with value: 177.44634805061435.

Mejor trial hasta ahora: RMSE=177.446348, Parámetros={'num_leaves': 42, 'learning_rate': 0.029060225434901842, 'feature_fraction': 0.7927601669278636, 'bagging_fraction': 0.9062630187635413, 'bagging_freq': 2, 'lambda_l1': 8.874585531798186e-06, 'lambda_l2': 3.986027947089727e-06, 'min_child_samples': 29, 'max_depth': 3, 'max_bin': 276, 'min_data_in_leaf': 32, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.4859562586494468, 'min_gain_to_split': 0.19825301847130325}

[I 2025-07-13 13:29:45,781] Trial 42 finished with value: 177.4493410999796 and parameters: {'num_leaves': 61, 'learning_rate': 0.028109704299848985, 'feature_fraction': 0.7437408091078109, 'bagging_fraction': 0.9786885928437279, 'bagging_freq': 4, 'lambda_l1': 1.75415788513656e-05, 'lambda_l2': 3.552646502767598e-06, 'min_child_samples': 31, 'max_depth': 3, 'max_bin': 279, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 20, 'path_smooth': 0.583976269452466, 'min_gain_to_split': 0.21214469671260236}. Best is trial 41 with value: 177.44634805061435.

Mejor trial hasta ahora: RMSE=177.446348, Parámetros={'num_leaves': 42, 'learning_rate': 0.029060225434901842, 'feature_fraction': 0.7927601669278636, 'bagging_fraction': 0.9062630187635413, 'bagging_freq': 2, 'lambda_l1': 8.874585531798186e-06, 'lambda_l2': 3.986027947089727e-06, 'min_child_samples': 29, 'max_depth': 3, 'max_bin': 276, 'min_data_in_leaf': 32, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.4859562586494468, 'min_gain_to_split': 0.19825301847130325}

[I 2025-07-13 13:31:25,598] Trial 43 finished with value: 177.46239696359325 and parameters: {'num_leaves': 40, 'learning_rate': 0.04805871248973948, 'feature_fraction': 0.7395037152400381, 'bagging_fraction': 0.9948361974277262, 'bagging_freq': 4, 'lambda_l1': 1.0078843606755728e-05, 'lambda_l2': 3.30473040706196e-06, 'min_child_samples': 30, 'max_depth': 3, 'max_bin': 279, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 20, 'path_smooth': 0.5827490063411817, 'min_gain_to_split': 0.2069048735850237}. Best is trial 41 with value: 177.44634805061435.

Mejor trial hasta ahora: RMSE=177.446348, Parámetros={'num_leaves': 42, 'learning_rate': 0.029060225434901842, 'feature_fraction': 0.7927601669278636, 'bagging_fraction': 0.9062630187635413, 'bagging_freq': 2, 'lambda_l1': 8.874585531798186e-06, 'lambda_l2': 3.986027947089727e-06, 'min_child_samples': 29, 'max_depth': 3, 'max_bin': 276, 'min_data_in_leaf': 32, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.4859562586494468, 'min_gain_to_split': 0.19825301847130325}

[I 2025-07-13 13:32:59,489] Trial 44 finished with value: 177.47077894810374 and parameters: {'num_leaves': 60, 'learning_rate': 0.06529561877650288, 'feature_fraction': 0.7857811085662407, 'bagging_fraction': 0.9463085314123529, 'bagging_freq': 5, 'lambda_l1': 2.438191016739354e-05, 'lambda_l2': 1.2576884101711683e-05, 'min_child_samples': 33, 'max_depth': 3, 'max_bin': 320, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 23, 'path_smooth': 0.6624187331064075, 'min_gain_to_split': 0.2542560713716025}. Best is trial 41 with value: 177.44634805061435.

Mejor trial hasta ahora: RMSE=177.446348, Parámetros={'num_leaves': 42, 'learning_rate': 0.029060225434901842, 'feature_fraction': 0.7927601669278636, 'bagging_fraction': 0.9062630187635413, 'bagging_freq': 2, 'lambda_l1': 8.874585531798186e-06, 'lambda_l2': 3.986027947089727e-06, 'min_child_samples': 29, 'max_depth': 3, 'max_bin': 276, 'min_data_in_leaf': 32, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.4859562586494468, 'min_gain_to_split': 0.19825301847130325}

[I 2025-07-13 13:34:32,623] Trial 45 finished with value: 177.45614698679327 and parameters: {'num_leaves': 53, 'learning_rate': 0.028879475436553167, 'feature_fraction': 0.7047285120192321, 'bagging_fraction': 0.9768776884467332, 'bagging_freq': 4, 'lambda_l1': 2.5211611106008753e-06, 'lambda_l2': 2.8507402118071774e-06, 'min_child_samples': 28, 'max_depth': 3, 'max_bin': 277, 'min_data_in_leaf': 27, 'extra_trees': True, 'early_stopping_rounds': 15, 'path_smooth': 0.750106251401357, 'min_gain_to_split': 0.22249029000664888}. Best is trial 41 with value: 177.44634805061435.

Mejor trial hasta ahora: RMSE=177.446348, Parámetros={'num_leaves': 42, 'learning_rate': 0.029060225434901842, 'feature_fraction': 0.7927601669278636, 'bagging_fraction': 0.9062630187635413, 'bagging_freq': 2, 'lambda_l1': 8.874585531798186e-06, 'lambda_l2': 3.986027947089727e-06, 'min_child_samples': 29, 'max_depth': 3, 'max_bin': 276, 'min_data_in_leaf': 32, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.4859562586494468, 'min_gain_to_split': 0.19825301847130325}

[I 2025-07-13 13:36:04,389] Trial 46 finished with value: 177.4490147004796 and parameters: {'num_leaves': 70, 'learning_rate': 0.02101582249384935, 'feature_fraction': 0.7337965775146885, 'bagging_fraction': 0.8554958701946274, 'bagging_freq': 3, 'lambda_l1': 0.00013000989365439942, 'lambda_l2': 0.0010523102726997943, 'min_child_samples': 25, 'max_depth': 3, 'max_bin': 308, 'min_data_in_leaf': 44, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.4880508996349786, 'min_gain_to_split': 0.18609783078165346}. Best is trial 41 with value: 177.44634805061435.

Mejor trial hasta ahora: RMSE=177.446348, Parámetros={'num_leaves': 42, 'learning_rate': 0.029060225434901842, 'feature_fraction': 0.7927601669278636, 'bagging_fraction': 0.9062630187635413, 'bagging_freq': 2, 'lambda_l1': 8.874585531798186e-06, 'lambda_l2': 3.986027947089727e-06, 'min_child_samples': 29, 'max_depth': 3, 'max_bin': 276, 'min_data_in_leaf': 32, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.4859562586494468, 'min_gain_to_split': 0.19825301847130325}

[I 2025-07-13 13:37:37,582] Trial 47 finished with value: 177.45980381558206 and parameters: {'num_leaves': 71, 'learning_rate': 0.035510975007134085, 'feature_fraction': 0.6511557269304139, 'bagging_fraction': 0.8845571630962936, 'bagging_freq': 1, 'lambda_l1': 0.0005949991487341373, 'lambda_l2': 0.0050221379545576745, 'min_child_samples': 25, 'max_depth': 4, 'max_bin': 314, 'min_data_in_leaf': 32, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.48294374208475155, 'min_gain_to_split': 0.16143700282155266}. Best is trial 41 with value: 177.44634805061435.

Mejor trial hasta ahora: RMSE=177.446348, Parámetros={'num_leaves': 42, 'learning_rate': 0.029060225434901842, 'feature_fraction': 0.7927601669278636, 'bagging_fraction': 0.9062630187635413, 'bagging_freq': 2, 'lambda_l1': 8.874585531798186e-06, 'lambda_l2': 3.986027947089727e-06, 'min_child_samples': 29, 'max_depth': 3, 'max_bin': 276, 'min_data_in_leaf': 32, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.4859562586494468, 'min_gain_to_split': 0.19825301847130325}

[I 2025-07-13 13:39:09,679] Trial 48 finished with value: 177.448639122069 and parameters: {'num_leaves': 90, 'learning_rate': 0.02051386282421321, 'feature_fraction': 0.7893870638429386, 'bagging_fraction': 0.8552021925934924, 'bagging_freq': 2, 'lambda_l1': 0.0001390554877632113, 'lambda_l2': 0.16511977094378072, 'min_child_samples': 22, 'max_depth': 3, 'max_bin': 351, 'min_data_in_leaf': 47, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.3050750658269262, 'min_gain_to_split': 0.29102953599150316}. Best is trial 41 with value: 177.44634805061435.

Mejor trial hasta ahora: RMSE=177.446348, Parámetros={'num_leaves': 42, 'learning_rate': 0.029060225434901842, 'feature_fraction': 0.7927601669278636, 'bagging_fraction': 0.9062630187635413, 'bagging_freq': 2, 'lambda_l1': 8.874585531798186e-06, 'lambda_l2': 3.986027947089727e-06, 'min_child_samples': 29, 'max_depth': 3, 'max_bin': 276, 'min_data_in_leaf': 32, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.4859562586494468, 'min_gain_to_split': 0.19825301847130325}

[I 2025-07-13 13:40:34,120] Trial 49 finished with value: 177.44968846471232 and parameters: {'num_leaves': 91, 'learning_rate': 0.016930601828816845, 'feature_fraction': 0.7929106063397158, 'bagging_fraction': 0.8393221708698364, 'bagging_freq': 2, 'lambda_l1': 0.0009325016129723699, 'lambda_l2': 0.25122923653504564, 'min_child_samples': 22, 'max_depth': 3, 'max_bin': 399, 'min_data_in_leaf': 53, 'extra_trees': True, 'early_stopping_rounds': 10, 'path_smooth': 0.8580049980993284, 'min_gain_to_split': 0.2789339021589261}. Best is trial 41 with value: 177.44634805061435.

Mejor trial hasta ahora: RMSE=177.446348, Parámetros={'num_leaves': 42, 'learning_rate': 0.029060225434901842, 'feature_fraction': 0.7927601669278636, 'bagging_fraction': 0.9062630187635413, 'bagging_freq': 2, 'lambda_l1': 8.874585531798186e-06, 'lambda_l2': 3.986027947089727e-06, 'min_child_samples': 29, 'max_depth': 3, 'max_bin': 276, 'min_data_in_leaf': 32, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.4859562586494468, 'min_gain_to_split': 0.19825301847130325}

[I 2025-07-13 13:42:35,136] Trial 50 finished with value: 177.44869685611715 and parameters: {'num_leaves': 99, 'learning_rate': 0.011685543774470956, 'feature_fraction': 0.7640882057336038, 'bagging_fraction': 0.9352484547242345, 'bagging_freq': 1, 'lambda_l1': 0.009782540568264808, 'lambda_l2': 0.12415430982860913, 'min_child_samples': 35, 'max_depth': 5, 'max_bin': 433, 'min_data_in_leaf': 22, 'extra_trees': True, 'early_stopping_rounds': 30, 'path_smooth': 0.29140602691035, 'min_gain_to_split': 0.1276493072268962}. Best is trial 41 with value: 177.44634805061435.

Mejor trial hasta ahora: RMSE=177.446348, Parámetros={'num_leaves': 42, 'learning_rate': 0.029060225434901842, 'feature_fraction': 0.7927601669278636, 'bagging_fraction': 0.9062630187635413, 'bagging_freq': 2, 'lambda_l1': 8.874585531798186e-06, 'lambda_l2': 3.986027947089727e-06, 'min_child_samples': 29, 'max_depth': 3, 'max_bin': 276, 'min_data_in_leaf': 32, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.4859562586494468, 'min_gain_to_split': 0.19825301847130325}

[I 2025-07-13 13:44:13,700] Trial 51 finished with value: 177.45490805775688 and parameters: {'num_leaves': 95, 'learning_rate': 0.023683191017153642, 'feature_fraction': 0.8069386203375313, 'bagging_fraction': 0.8622389845371501, 'bagging_freq': 6, 'lambda_l1': 4.361964178880369e-06, 'lambda_l2': 0.00010172970798042101, 'min_child_samples': 27, 'max_depth': 4, 'max_bin': 356, 'min_data_in_leaf': 45, 'extra_trees': True, 'early_stopping_rounds': 22, 'path_smooth': 0.2504372765106299, 'min_gain_to_split': 0.34904722089145257}. Best is trial 41 with value: 177.44634805061435.

Mejor trial hasta ahora: RMSE=177.446348, Parámetros={'num_leaves': 42, 'learning_rate': 0.029060225434901842, 'feature_fraction': 0.7927601669278636, 'bagging_fraction': 0.9062630187635413, 'bagging_freq': 2, 'lambda_l1': 8.874585531798186e-06, 'lambda_l2': 3.986027947089727e-06, 'min_child_samples': 29, 'max_depth': 3, 'max_bin': 276, 'min_data_in_leaf': 32, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.4859562586494468, 'min_gain_to_split': 0.19825301847130325}

[I 2025-07-13 13:45:35,615] Trial 52 finished with value: 177.45146335404965 and parameters: {'num_leaves': 42, 'learning_rate': 0.016312183460906644, 'feature_fraction': 0.8372445523595855, 'bagging_fraction': 0.8845928925613719, 'bagging_freq': 2, 'lambda_l1': 0.00013366186097827585, 'lambda_l2': 7.512526563255573, 'min_child_samples': 19, 'max_depth': 3, 'max_bin': 208, 'min_data_in_leaf': 32, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.3314880487066767, 'min_gain_to_split': 0.3947706257257025}. Best is trial 41 with value: 177.44634805061435.

Mejor trial hasta ahora: RMSE=177.446348, Parámetros={'num_leaves': 42, 'learning_rate': 0.029060225434901842, 'feature_fraction': 0.7927601669278636, 'bagging_fraction': 0.9062630187635413, 'bagging_freq': 2, 'lambda_l1': 8.874585531798186e-06, 'lambda_l2': 3.986027947089727e-06, 'min_child_samples': 29, 'max_depth': 3, 'max_bin': 276, 'min_data_in_leaf': 32, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.4859562586494468, 'min_gain_to_split': 0.19825301847130325}

[I 2025-07-13 13:47:33,516] Trial 53 finished with value: 177.44917172127734 and parameters: {'num_leaves': 100, 'learning_rate': 0.012588050142750752, 'feature_fraction': 0.7568831533493989, 'bagging_fraction': 0.9332856741182981, 'bagging_freq': 1, 'lambda_l1': 0.009215724200240223, 'lambda_l2': 0.04648644120256559, 'min_child_samples': 36, 'max_depth': 5, 'max_bin': 448, 'min_data_in_leaf': 20, 'extra_trees': True, 'early_stopping_rounds': 31, 'path_smooth': 0.19496290136603248, 'min_gain_to_split': 0.1306409916703345}. Best is trial 41 with value: 177.44634805061435.

Mejor trial hasta ahora: RMSE=177.446348, Parámetros={'num_leaves': 42, 'learning_rate': 0.029060225434901842, 'feature_fraction': 0.7927601669278636, 'bagging_fraction': 0.9062630187635413, 'bagging_freq': 2, 'lambda_l1': 8.874585531798186e-06, 'lambda_l2': 3.986027947089727e-06, 'min_child_samples': 29, 'max_depth': 3, 'max_bin': 276, 'min_data_in_leaf': 32, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.4859562586494468, 'min_gain_to_split': 0.19825301847130325}

[I 2025-07-13 13:49:44,451] Trial 54 finished with value: 177.44781561316404 and parameters: {'num_leaves': 91, 'learning_rate': 0.011164956853952189, 'feature_fraction': 0.7838767224607208, 'bagging_fraction': 0.903535884130846, 'bagging_freq': 1, 'lambda_l1': 0.10875068629651359, 'lambda_l2': 0.17513289433108575, 'min_child_samples': 23, 'max_depth': 5, 'max_bin': 489, 'min_data_in_leaf': 24, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.39744891116076886, 'min_gain_to_split': 0.07510656994923048}. Best is trial 41 with value: 177.44634805061435.

Mejor trial hasta ahora: RMSE=177.446348, Parámetros={'num_leaves': 42, 'learning_rate': 0.029060225434901842, 'feature_fraction': 0.7927601669278636, 'bagging_fraction': 0.9062630187635413, 'bagging_freq': 2, 'lambda_l1': 8.874585531798186e-06, 'lambda_l2': 3.986027947089727e-06, 'min_child_samples': 29, 'max_depth': 3, 'max_bin': 276, 'min_data_in_leaf': 32, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.4859562586494468, 'min_gain_to_split': 0.19825301847130325}

[I 2025-07-13 13:53:01,324] Trial 55 finished with value: 177.45007119753214 and parameters: {'num_leaves': 88, 'learning_rate': 0.011188870344433128, 'feature_fraction': 0.7810259405450228, 'bagging_fraction': 0.9077809599455066, 'bagging_freq': 1, 'lambda_l1': 0.0004824932450951876, 'lambda_l2': 0.37667980137702217, 'min_child_samples': 23, 'max_depth': 5, 'max_bin': 494, 'min_data_in_leaf': 28, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.3884275080590237, 'min_gain_to_split': 0.06284001355701319}. Best is trial 41 with value: 177.44634805061435.

Mejor trial hasta ahora: RMSE=177.446348, Parámetros={'num_leaves': 42, 'learning_rate': 0.029060225434901842, 'feature_fraction': 0.7927601669278636, 'bagging_fraction': 0.9062630187635413, 'bagging_freq': 2, 'lambda_l1': 8.874585531798186e-06, 'lambda_l2': 3.986027947089727e-06, 'min_child_samples': 29, 'max_depth': 3, 'max_bin': 276, 'min_data_in_leaf': 32, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.4859562586494468, 'min_gain_to_split': 0.19825301847130325}

[I 2025-07-13 13:55:46,361] Trial 56 finished with value: 177.44602708660653 and parameters: {'num_leaves': 83, 'learning_rate': 0.019574286102926417, 'feature_fraction': 0.8261758278772241, 'bagging_fraction': 0.8994268817543155, 'bagging_freq': 2, 'lambda_l1': 1.557215086558011, 'lambda_l2': 0.026605769114614094, 'min_child_samples': 12, 'max_depth': 4, 'max_bin': 483, 'min_data_in_leaf': 42, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.25128871984966317, 'min_gain_to_split': 0.4632183453373665}. Best is trial 56 with value: 177.44602708660653.

Mejor trial hasta ahora: RMSE=177.446027, Parámetros={'num_leaves': 83, 'learning_rate': 0.019574286102926417, 'feature_fraction': 0.8261758278772241, 'bagging_fraction': 0.8994268817543155, 'bagging_freq': 2, 'lambda_l1': 1.557215086558011, 'lambda_l2': 0.026605769114614094, 'min_child_samples': 12, 'max_depth': 4, 'max_bin': 483, 'min_data_in_leaf': 42, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.25128871984966317, 'min_gain_to_split': 0.4632183453373665}

[I 2025-07-13 13:58:39,764] Trial 57 finished with value: 177.44596572720064 and parameters: {'num_leaves': 84, 'learning_rate': 0.010246501601424514, 'feature_fraction': 0.8223958282290293, 'bagging_fraction': 0.8995770559517772, 'bagging_freq': 10, 'lambda_l1': 1.5202136661922863, 'lambda_l2': 0.005714508893211084, 'min_child_samples': 17, 'max_depth': 4, 'max_bin': 469, 'min_data_in_leaf': 25, 'extra_trees': True, 'early_stopping_rounds': 22, 'path_smooth': 0.24409092395652088, 'min_gain_to_split': 0.4662355232732897}. Best is trial 57 with value: 177.44596572720064.

Mejor trial hasta ahora: RMSE=177.445966, Parámetros={'num_leaves': 84, 'learning_rate': 0.010246501601424514, 'feature_fraction': 0.8223958282290293, 'bagging_fraction': 0.8995770559517772, 'bagging_freq': 10, 'lambda_l1': 1.5202136661922863, 'lambda_l2': 0.005714508893211084, 'min_child_samples': 17, 'max_depth': 4, 'max_bin': 469, 'min_data_in_leaf': 25, 'extra_trees': True, 'early_stopping_rounds': 22, 'path_smooth': 0.24409092395652088, 'min_gain_to_split': 0.4662355232732897}

[I 2025-07-13 14:01:09,667] Trial 58 finished with value: 177.44760666328733 and parameters: {'num_leaves': 85, 'learning_rate': 0.010018802301669402, 'feature_fraction': 0.8229768489570395, 'bagging_fraction': 0.9481333942518132, 'bagging_freq': 7, 'lambda_l1': 1.2660384602132155, 'lambda_l2': 0.01209746931238406, 'min_child_samples': 12, 'max_depth': 5, 'max_bin': 467, 'min_data_in_leaf': 24, 'extra_trees': True, 'early_stopping_rounds': 20, 'path_smooth': 0.16345194277960307, 'min_gain_to_split': 0.45151773615539453}. Best is trial 57 with value: 177.44596572720064.

Mejor trial hasta ahora: RMSE=177.445966, Parámetros={'num_leaves': 84, 'learning_rate': 0.010246501601424514, 'feature_fraction': 0.8223958282290293, 'bagging_fraction': 0.8995770559517772, 'bagging_freq': 10, 'lambda_l1': 1.5202136661922863, 'lambda_l2': 0.005714508893211084, 'min_child_samples': 17, 'max_depth': 4, 'max_bin': 469, 'min_data_in_leaf': 25, 'extra_trees': True, 'early_stopping_rounds': 22, 'path_smooth': 0.24409092395652088, 'min_gain_to_split': 0.4662355232732897}

[I 2025-07-13 14:03:53,891] Trial 59 finished with value: 177.44799845427 and parameters: {'num_leaves': 80, 'learning_rate': 0.010312120484243405, 'feature_fraction': 0.8475889911231651, 'bagging_fraction': 0.950769218154186, 'bagging_freq': 10, 'lambda_l1': 7.310199299116948, 'lambda_l2': 0.008035895195124971, 'min_child_samples': 12, 'max_depth': 4, 'max_bin': 469, 'min_data_in_leaf': 33, 'extra_trees': True, 'early_stopping_rounds': 21, 'path_smooth': 0.17181297817588836, 'min_gain_to_split': 0.45774175809866596}. Best is trial 57 with value: 177.44596572720064.

Mejor trial hasta ahora: RMSE=177.445966, Parámetros={'num_leaves': 84, 'learning_rate': 0.010246501601424514, 'feature_fraction': 0.8223958282290293, 'bagging_fraction': 0.8995770559517772, 'bagging_freq': 10, 'lambda_l1': 1.5202136661922863, 'lambda_l2': 0.005714508893211084, 'min_child_samples': 17, 'max_depth': 4, 'max_bin': 469, 'min_data_in_leaf': 25, 'extra_trees': True, 'early_stopping_rounds': 22, 'path_smooth': 0.24409092395652088, 'min_gain_to_split': 0.4662355232732897}

[I 2025-07-13 14:07:03,500] Trial 60 finished with value: 177.46299331585004 and parameters: {'num_leaves': 86, 'learning_rate': 0.018299331332188275, 'feature_fraction': 0.8240065500455601, 'bagging_fraction': 0.88980933219636, 'bagging_freq': 9, 'lambda_l1': 0.5093399958185332, 'lambda_l2': 0.01269299848181572, 'min_child_samples': 12, 'max_depth': 6, 'max_bin': 474, 'min_data_in_leaf': 41, 'extra_trees': False, 'early_stopping_rounds': 20, 'path_smooth': 0.2439315578182396, 'min_gain_to_split': 0.4732733605603642}. Best is trial 57 with value: 177.44596572720064.

Mejor trial hasta ahora: RMSE=177.445966, Parámetros={'num_leaves': 84, 'learning_rate': 0.010246501601424514, 'feature_fraction': 0.8223958282290293, 'bagging_fraction': 0.8995770559517772, 'bagging_freq': 10, 'lambda_l1': 1.5202136661922863, 'lambda_l2': 0.005714508893211084, 'min_child_samples': 17, 'max_depth': 4, 'max_bin': 469, 'min_data_in_leaf': 25, 'extra_trees': True, 'early_stopping_rounds': 22, 'path_smooth': 0.24409092395652088, 'min_gain_to_split': 0.4662355232732897}

[I 2025-07-13 14:09:20,799] Trial 61 finished with value: 177.44973601553565 and parameters: {'num_leaves': 36, 'learning_rate': 0.015377927209161988, 'feature_fraction': 0.799133640530184, 'bagging_fraction': 0.9267229834230511, 'bagging_freq': 8, 'lambda_l1': 0.904748227350086, 'lambda_l2': 0.000729288503824768, 'min_child_samples': 12, 'max_depth': 4, 'max_bin': 480, 'min_data_in_leaf': 25, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.11377522444861086, 'min_gain_to_split': 0.4534556352352489}. Best is trial 57 with value: 177.44596572720064.

Mejor trial hasta ahora: RMSE=177.445966, Parámetros={'num_leaves': 84, 'learning_rate': 0.010246501601424514, 'feature_fraction': 0.8223958282290293, 'bagging_fraction': 0.8995770559517772, 'bagging_freq': 10, 'lambda_l1': 1.5202136661922863, 'lambda_l2': 0.005714508893211084, 'min_child_samples': 17, 'max_depth': 4, 'max_bin': 469, 'min_data_in_leaf': 25, 'extra_trees': True, 'early_stopping_rounds': 22, 'path_smooth': 0.24409092395652088, 'min_gain_to_split': 0.4662355232732897}

[I 2025-07-13 14:11:14,550] Trial 62 finished with value: 177.44781656930914 and parameters: {'num_leaves': 79, 'learning_rate': 0.010001004838999886, 'feature_fraction': 0.8242024552398497, 'bagging_fraction': 0.9237509109053809, 'bagging_freq': 7, 'lambda_l1': 2.9782252234277635, 'lambda_l2': 0.0003591100492754026, 'min_child_samples': 16, 'max_depth': 5, 'max_bin': 448, 'min_data_in_leaf': 31, 'extra_trees': True, 'early_stopping_rounds': 14, 'path_smooth': 0.19855242169233117, 'min_gain_to_split': 0.4805824354127914}. Best is trial 57 with value: 177.44596572720064.

Mejor trial hasta ahora: RMSE=177.445966, Parámetros={'num_leaves': 84, 'learning_rate': 0.010246501601424514, 'feature_fraction': 0.8223958282290293, 'bagging_fraction': 0.8995770559517772, 'bagging_freq': 10, 'lambda_l1': 1.5202136661922863, 'lambda_l2': 0.005714508893211084, 'min_child_samples': 17, 'max_depth': 4, 'max_bin': 469, 'min_data_in_leaf': 25, 'extra_trees': True, 'early_stopping_rounds': 22, 'path_smooth': 0.24409092395652088, 'min_gain_to_split': 0.4662355232732897}

[I 2025-07-13 14:14:14,819] Trial 63 finished with value: 177.4496051583923 and parameters: {'num_leaves': 94, 'learning_rate': 0.011013574354555506, 'feature_fraction': 0.843162290047493, 'bagging_fraction': 0.9009079597758277, 'bagging_freq': 9, 'lambda_l1': 0.22761875657129163, 'lambda_l2': 0.03251099452797202, 'min_child_samples': 19, 'max_depth': 5, 'max_bin': 479, 'min_data_in_leaf': 24, 'extra_trees': True, 'early_stopping_rounds': 22, 'path_smooth': 0.15421107837348777, 'min_gain_to_split': 0.048704432257375925}. Best is trial 57 with value: 177.44596572720064.

Mejor trial hasta ahora: RMSE=177.445966, Parámetros={'num_leaves': 84, 'learning_rate': 0.010246501601424514, 'feature_fraction': 0.8223958282290293, 'bagging_fraction': 0.8995770559517772, 'bagging_freq': 10, 'lambda_l1': 1.5202136661922863, 'lambda_l2': 0.005714508893211084, 'min_child_samples': 17, 'max_depth': 4, 'max_bin': 469, 'min_data_in_leaf': 25, 'extra_trees': True, 'early_stopping_rounds': 22, 'path_smooth': 0.24409092395652088, 'min_gain_to_split': 0.4662355232732897}

[I 2025-07-13 14:16:56,933] Trial 64 finished with value: 177.45063119527353 and parameters: {'num_leaves': 85, 'learning_rate': 0.012670583053318975, 'feature_fraction': 0.8085933940591044, 'bagging_fraction': 0.9049958800323645, 'bagging_freq': 7, 'lambda_l1': 3.0917316042241993, 'lambda_l2': 0.002812985524931766, 'min_child_samples': 29, 'max_depth': 5, 'max_bin': 427, 'min_data_in_leaf': 27, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.26736670959143205, 'min_gain_to_split': 0.07851151969214827}. Best is trial 57 with value: 177.44596572720064.

Mejor trial hasta ahora: RMSE=177.445966, Parámetros={'num_leaves': 84, 'learning_rate': 0.010246501601424514, 'feature_fraction': 0.8223958282290293, 'bagging_fraction': 0.8995770559517772, 'bagging_freq': 10, 'lambda_l1': 1.5202136661922863, 'lambda_l2': 0.005714508893211084, 'min_child_samples': 17, 'max_depth': 4, 'max_bin': 469, 'min_data_in_leaf': 25, 'extra_trees': True, 'early_stopping_rounds': 22, 'path_smooth': 0.24409092395652088, 'min_gain_to_split': 0.4662355232732897}

[I 2025-07-13 14:19:37,380] Trial 65 finished with value: 177.4531483359943 and parameters: {'num_leaves': 48, 'learning_rate': 0.013858410806727107, 'feature_fraction': 0.8682044222432665, 'bagging_fraction': 0.9185226756578718, 'bagging_freq': 10, 'lambda_l1': 0.17440622154316984, 'lambda_l2': 0.6612440785149182, 'min_child_samples': 17, 'max_depth': 6, 'max_bin': 461, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 19, 'path_smooth': 0.32720775593579665, 'min_gain_to_split': 0.3892914992180772}. Best is trial 57 with value: 177.44596572720064.

Mejor trial hasta ahora: RMSE=177.445966, Parámetros={'num_leaves': 84, 'learning_rate': 0.010246501601424514, 'feature_fraction': 0.8223958282290293, 'bagging_fraction': 0.8995770559517772, 'bagging_freq': 10, 'lambda_l1': 1.5202136661922863, 'lambda_l2': 0.005714508893211084, 'min_child_samples': 17, 'max_depth': 4, 'max_bin': 469, 'min_data_in_leaf': 25, 'extra_trees': True, 'early_stopping_rounds': 22, 'path_smooth': 0.24409092395652088, 'min_gain_to_split': 0.4662355232732897}

[I 2025-07-13 14:22:06,882] Trial 66 finished with value: 177.44871955353125 and parameters: {'num_leaves': 93, 'learning_rate': 0.011315991478659476, 'feature_fraction': 0.8893153727555972, 'bagging_fraction': 0.9522384084051909, 'bagging_freq': 9, 'lambda_l1': 2.004148323878145, 'lambda_l2': 0.05295799672418728, 'min_child_samples': 23, 'max_depth': 4, 'max_bin': 487, 'min_data_in_leaf': 20, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.21714321819250954, 'min_gain_to_split': 0.4990267058985409}. Best is trial 57 with value: 177.44596572720064.

Mejor trial hasta ahora: RMSE=177.445966, Parámetros={'num_leaves': 84, 'learning_rate': 0.010246501601424514, 'feature_fraction': 0.8223958282290293, 'bagging_fraction': 0.8995770559517772, 'bagging_freq': 10, 'lambda_l1': 1.5202136661922863, 'lambda_l2': 0.005714508893211084, 'min_child_samples': 17, 'max_depth': 4, 'max_bin': 469, 'min_data_in_leaf': 25, 'extra_trees': True, 'early_stopping_rounds': 22, 'path_smooth': 0.24409092395652088, 'min_gain_to_split': 0.4662355232732897}

[I 2025-07-13 14:24:53,812] Trial 67 finished with value: 177.4509616743308 and parameters: {'num_leaves': 82, 'learning_rate': 0.01519761867114076, 'feature_fraction': 0.7526217280468923, 'bagging_fraction': 0.8754382696281275, 'bagging_freq': 8, 'lambda_l1': 0.3141583762791648, 'lambda_l2': 0.022135505099280244, 'min_child_samples': 11, 'max_depth': 5, 'max_bin': 409, 'min_data_in_leaf': 25, 'extra_trees': True, 'early_stopping_rounds': 22, 'path_smooth': 0.39324127785152097, 'min_gain_to_split': 0.4148772657948916}. Best is trial 57 with value: 177.44596572720064.

Mejor trial hasta ahora: RMSE=177.445966, Parámetros={'num_leaves': 84, 'learning_rate': 0.010246501601424514, 'feature_fraction': 0.8223958282290293, 'bagging_fraction': 0.8995770559517772, 'bagging_freq': 10, 'lambda_l1': 1.5202136661922863, 'lambda_l2': 0.005714508893211084, 'min_child_samples': 17, 'max_depth': 4, 'max_bin': 469, 'min_data_in_leaf': 25, 'extra_trees': True, 'early_stopping_rounds': 22, 'path_smooth': 0.24409092395652088, 'min_gain_to_split': 0.4662355232732897}

[I 2025-07-13 14:27:06,548] Trial 68 finished with value: 177.45072342100084 and parameters: {'num_leaves': 57, 'learning_rate': 0.01188688514780975, 'feature_fraction': 0.7189127543275153, 'bagging_fraction': 0.9676475598395641, 'bagging_freq': 2, 'lambda_l1': 0.09604717772504703, 'lambda_l2': 0.00634304553241959, 'min_child_samples': 13, 'max_depth': 4, 'max_bin': 390, 'min_data_in_leaf': 30, 'extra_trees': False, 'early_stopping_rounds': 34, 'path_smooth': 0.3434573585919582, 'min_gain_to_split': 0.45638174377140306}. Best is trial 57 with value: 177.44596572720064.

Mejor trial hasta ahora: RMSE=177.445966, Parámetros={'num_leaves': 84, 'learning_rate': 0.010246501601424514, 'feature_fraction': 0.8223958282290293, 'bagging_fraction': 0.8995770559517772, 'bagging_freq': 10, 'lambda_l1': 1.5202136661922863, 'lambda_l2': 0.005714508893211084, 'min_child_samples': 17, 'max_depth': 4, 'max_bin': 469, 'min_data_in_leaf': 25, 'extra_trees': True, 'early_stopping_rounds': 22, 'path_smooth': 0.24409092395652088, 'min_gain_to_split': 0.4662355232732897}

[I 2025-07-13 14:29:37,635] Trial 69 finished with value: 177.4521360965442 and parameters: {'num_leaves': 64, 'learning_rate': 0.01326233715301176, 'feature_fraction': 0.8324377980909253, 'bagging_fraction': 0.8909625987282386, 'bagging_freq': 6, 'lambda_l1': 8.191775076027273, 'lambda_l2': 0.07757290396413793, 'min_child_samples': 19, 'max_depth': 6, 'max_bin': 437, 'min_data_in_leaf': 51, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.10780832179377231, 'min_gain_to_split': 0.030339136232346055}. Best is trial 57 with value: 177.44596572720064.

Mejor trial hasta ahora: RMSE=177.445966, Parámetros={'num_leaves': 84, 'learning_rate': 0.010246501601424514, 'feature_fraction': 0.8223958282290293, 'bagging_fraction': 0.8995770559517772, 'bagging_freq': 10, 'lambda_l1': 1.5202136661922863, 'lambda_l2': 0.005714508893211084, 'min_child_samples': 17, 'max_depth': 4, 'max_bin': 469, 'min_data_in_leaf': 25, 'extra_trees': True, 'early_stopping_rounds': 22, 'path_smooth': 0.24409092395652088, 'min_gain_to_split': 0.4662355232732897}

[I 2025-07-13 14:32:07,939] Trial 70 finished with value: 177.45496870225543 and parameters: {'num_leaves': 73, 'learning_rate': 0.01838916765971868, 'feature_fraction': 0.9321847497292801, 'bagging_fraction': 0.7199985016247983, 'bagging_freq': 1, 'lambda_l1': 1.0588633336357298, 'lambda_l2': 0.018604717228463977, 'min_child_samples': 26, 'max_depth': 4, 'max_bin': 499, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.40352432739024396, 'min_gain_to_split': 0.435511358622889}. Best is trial 57 with value: 177.44596572720064.

Mejor trial hasta ahora: RMSE=177.445966, Parámetros={'num_leaves': 84, 'learning_rate': 0.010246501601424514, 'feature_fraction': 0.8223958282290293, 'bagging_fraction': 0.8995770559517772, 'bagging_freq': 10, 'lambda_l1': 1.5202136661922863, 'lambda_l2': 0.005714508893211084, 'min_child_samples': 17, 'max_depth': 4, 'max_bin': 469, 'min_data_in_leaf': 25, 'extra_trees': True, 'early_stopping_rounds': 22, 'path_smooth': 0.24409092395652088, 'min_gain_to_split': 0.4662355232732897}

[I 2025-07-13 14:34:33,028] Trial 71 finished with value: 177.45762632803297 and parameters: {'num_leaves': 42, 'learning_rate': 0.02525378656671335, 'feature_fraction': 0.8900214048509658, 'bagging_fraction': 0.7438253236605776, 'bagging_freq': 3, 'lambda_l1': 1.5756407779533799, 'lambda_l2': 0.002907379090698236, 'min_child_samples': 16, 'max_depth': 5, 'max_bin': 421, 'min_data_in_leaf': 42, 'extra_trees': True, 'early_stopping_rounds': 32, 'path_smooth': 0.08201229727449809, 'min_gain_to_split': 0.36401638284716337}. Best is trial 57 with value: 177.44596572720064.

Mejor trial hasta ahora: RMSE=177.445966, Parámetros={'num_leaves': 84, 'learning_rate': 0.010246501601424514, 'feature_fraction': 0.8223958282290293, 'bagging_fraction': 0.8995770559517772, 'bagging_freq': 10, 'lambda_l1': 1.5202136661922863, 'lambda_l2': 0.005714508893211084, 'min_child_samples': 17, 'max_depth': 4, 'max_bin': 469, 'min_data_in_leaf': 25, 'extra_trees': True, 'early_stopping_rounds': 22, 'path_smooth': 0.24409092395652088, 'min_gain_to_split': 0.4662355232732897}

[I 2025-07-13 14:36:55,744] Trial 72 finished with value: 177.4504088499688 and parameters: {'num_leaves': 96, 'learning_rate': 0.010170086516133627, 'feature_fraction': 0.8524969803622063, 'bagging_fraction': 0.940564300007632, 'bagging_freq': 2, 'lambda_l1': 0.5303286508863172, 'lambda_l2': 1.824896724244896, 'min_child_samples': 21, 'max_depth': 6, 'max_bin': 464, 'min_data_in_leaf': 70, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.9856315759374152, 'min_gain_to_split': 0.23533379582496908}. Best is trial 57 with value: 177.44596572720064.

Mejor trial hasta ahora: RMSE=177.445966, Parámetros={'num_leaves': 84, 'learning_rate': 0.010246501601424514, 'feature_fraction': 0.8223958282290293, 'bagging_fraction': 0.8995770559517772, 'bagging_freq': 10, 'lambda_l1': 1.5202136661922863, 'lambda_l2': 0.005714508893211084, 'min_child_samples': 17, 'max_depth': 4, 'max_bin': 469, 'min_data_in_leaf': 25, 'extra_trees': True, 'early_stopping_rounds': 22, 'path_smooth': 0.24409092395652088, 'min_gain_to_split': 0.4662355232732897}

[I 2025-07-13 14:38:55,224] Trial 73 finished with value: 177.447896145745 and parameters: {'num_leaves': 82, 'learning_rate': 0.010257878749807374, 'feature_fraction': 0.8220306881091803, 'bagging_fraction': 0.9254880169750219, 'bagging_freq': 7, 'lambda_l1': 4.431411688424175, 'lambda_l2': 0.0004344626780900526, 'min_child_samples': 16, 'max_depth': 5, 'max_bin': 457, 'min_data_in_leaf': 30, 'extra_trees': True, 'early_stopping_rounds': 14, 'path_smooth': 0.19611699150739498, 'min_gain_to_split': 0.4805893859465475}. Best is trial 57 with value: 177.44596572720064.

Mejor trial hasta ahora: RMSE=177.445966, Parámetros={'num_leaves': 84, 'learning_rate': 0.010246501601424514, 'feature_fraction': 0.8223958282290293, 'bagging_fraction': 0.8995770559517772, 'bagging_freq': 10, 'lambda_l1': 1.5202136661922863, 'lambda_l2': 0.005714508893211084, 'min_child_samples': 17, 'max_depth': 4, 'max_bin': 469, 'min_data_in_leaf': 25, 'extra_trees': True, 'early_stopping_rounds': 22, 'path_smooth': 0.24409092395652088, 'min_gain_to_split': 0.4662355232732897}

[I 2025-07-13 14:41:11,587] Trial 74 finished with value: 177.44774390424195 and parameters: {'num_leaves': 79, 'learning_rate': 0.011334101905187485, 'feature_fraction': 0.776767560842112, 'bagging_fraction': 0.9157554519942318, 'bagging_freq': 6, 'lambda_l1': 3.4994472888416666, 'lambda_l2': 0.0017646559788637398, 'min_child_samples': 17, 'max_depth': 5, 'max_bin': 448, 'min_data_in_leaf': 23, 'extra_trees': True, 'early_stopping_rounds': 12, 'path_smooth': 0.2087561087201279, 'min_gain_to_split': 0.46820853918876354}. Best is trial 57 with value: 177.44596572720064.

Mejor trial hasta ahora: RMSE=177.445966, Parámetros={'num_leaves': 84, 'learning_rate': 0.010246501601424514, 'feature_fraction': 0.8223958282290293, 'bagging_fraction': 0.8995770559517772, 'bagging_freq': 10, 'lambda_l1': 1.5202136661922863, 'lambda_l2': 0.005714508893211084, 'min_child_samples': 17, 'max_depth': 4, 'max_bin': 469, 'min_data_in_leaf': 25, 'extra_trees': True, 'early_stopping_rounds': 22, 'path_smooth': 0.24409092395652088, 'min_gain_to_split': 0.4662355232732897}

[I 2025-07-13 14:43:08,284] Trial 75 finished with value: 177.44887531456146 and parameters: {'num_leaves': 89, 'learning_rate': 0.013821921472555803, 'feature_fraction': 0.9058380874125257, 'bagging_fraction': 0.9143408707936928, 'bagging_freq': 6, 'lambda_l1': 0.8047260848302228, 'lambda_l2': 0.0018828953116908362, 'min_child_samples': 18, 'max_depth': 4, 'max_bin': 486, 'min_data_in_leaf': 23, 'extra_trees': True, 'early_stopping_rounds': 11, 'path_smooth': 0.14705345575367054, 'min_gain_to_split': 0.4579012362498476}. Best is trial 57 with value: 177.44596572720064.

Mejor trial hasta ahora: RMSE=177.445966, Parámetros={'num_leaves': 84, 'learning_rate': 0.010246501601424514, 'feature_fraction': 0.8223958282290293, 'bagging_fraction': 0.8995770559517772, 'bagging_freq': 10, 'lambda_l1': 1.5202136661922863, 'lambda_l2': 0.005714508893211084, 'min_child_samples': 17, 'max_depth': 4, 'max_bin': 469, 'min_data_in_leaf': 25, 'extra_trees': True, 'early_stopping_rounds': 22, 'path_smooth': 0.24409092395652088, 'min_gain_to_split': 0.4662355232732897}

[I 2025-07-13 14:45:11,694] Trial 76 finished with value: 177.4510640304672 and parameters: {'num_leaves': 78, 'learning_rate': 0.016130674798740755, 'feature_fraction': 0.7786007266529805, 'bagging_fraction': 0.8962885619053318, 'bagging_freq': 7, 'lambda_l1': 0.10495377602569896, 'lambda_l2': 0.012347231466549147, 'min_child_samples': 20, 'max_depth': 4, 'max_bin': 453, 'min_data_in_leaf': 27, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.2820410038697574, 'min_gain_to_split': 0.4678023232378749}. Best is trial 57 with value: 177.44596572720064.

Mejor trial hasta ahora: RMSE=177.445966, Parámetros={'num_leaves': 84, 'learning_rate': 0.010246501601424514, 'feature_fraction': 0.8223958282290293, 'bagging_fraction': 0.8995770559517772, 'bagging_freq': 10, 'lambda_l1': 1.5202136661922863, 'lambda_l2': 0.005714508893211084, 'min_child_samples': 17, 'max_depth': 4, 'max_bin': 469, 'min_data_in_leaf': 25, 'extra_trees': True, 'early_stopping_rounds': 22, 'path_smooth': 0.24409092395652088, 'min_gain_to_split': 0.4662355232732897}

[I 2025-07-13 14:47:03,010] Trial 77 finished with value: 177.44862545746813 and parameters: {'num_leaves': 76, 'learning_rate': 0.011825806582895214, 'feature_fraction': 0.8047575661853897, 'bagging_fraction': 0.9054326531597684, 'bagging_freq': 5, 'lambda_l1': 5.248786749611673, 'lambda_l2': 2.322630101826422e-05, 'min_child_samples': 32, 'max_depth': 5, 'max_bin': 474, 'min_data_in_leaf': 22, 'extra_trees': True, 'early_stopping_rounds': 12, 'path_smooth': 0.5190834702887324, 'min_gain_to_split': 0.41279258162654436}. Best is trial 57 with value: 177.44596572720064.

Mejor trial hasta ahora: RMSE=177.445966, Parámetros={'num_leaves': 84, 'learning_rate': 0.010246501601424514, 'feature_fraction': 0.8223958282290293, 'bagging_fraction': 0.8995770559517772, 'bagging_freq': 10, 'lambda_l1': 1.5202136661922863, 'lambda_l2': 0.005714508893211084, 'min_child_samples': 17, 'max_depth': 4, 'max_bin': 469, 'min_data_in_leaf': 25, 'extra_trees': True, 'early_stopping_rounds': 22, 'path_smooth': 0.24409092395652088, 'min_gain_to_split': 0.4662355232732897}

[I 2025-07-13 14:49:25,062] Trial 78 finished with value: 177.47717286985124 and parameters: {'num_leaves': 51, 'learning_rate': 0.0334841109828602, 'feature_fraction': 0.7683763106722545, 'bagging_fraction': 0.8795743933586072, 'bagging_freq': 6, 'lambda_l1': 0.03297521205796722, 'lambda_l2': 0.0037131786862854895, 'min_child_samples': 10, 'max_depth': 6, 'max_bin': 294, 'min_data_in_leaf': 59, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.4615772603418432, 'min_gain_to_split': 0.4442120045031538}. Best is trial 57 with value: 177.44596572720064.

Mejor trial hasta ahora: RMSE=177.445966, Parámetros={'num_leaves': 84, 'learning_rate': 0.010246501601424514, 'feature_fraction': 0.8223958282290293, 'bagging_fraction': 0.8995770559517772, 'bagging_freq': 10, 'lambda_l1': 1.5202136661922863, 'lambda_l2': 0.005714508893211084, 'min_child_samples': 17, 'max_depth': 4, 'max_bin': 469, 'min_data_in_leaf': 25, 'extra_trees': True, 'early_stopping_rounds': 22, 'path_smooth': 0.24409092395652088, 'min_gain_to_split': 0.4662355232732897}

[I 2025-07-13 14:51:14,663] Trial 79 finished with value: 177.44492326122926 and parameters: {'num_leaves': 92, 'learning_rate': 0.013257063567660836, 'feature_fraction': 0.795826108132908, 'bagging_fraction': 0.9160286581963031, 'bagging_freq': 2, 'lambda_l1': 1.7458175327741818, 'lambda_l2': 7.1670967250222865e-06, 'min_child_samples': 14, 'max_depth': 3, 'max_bin': 443, 'min_data_in_leaf': 25, 'extra_trees': True, 'early_stopping_rounds': 23, 'path_smooth': 0.042784422457300825, 'min_gain_to_split': 0.02239260599379561}. Best is trial 79 with value: 177.44492326122926.

Mejor trial hasta ahora: RMSE=177.444923, Parámetros={'num_leaves': 92, 'learning_rate': 0.013257063567660836, 'feature_fraction': 0.795826108132908, 'bagging_fraction': 0.9160286581963031, 'bagging_freq': 2, 'lambda_l1': 1.7458175327741818, 'lambda_l2': 7.1670967250222865e-06, 'min_child_samples': 14, 'max_depth': 3, 'max_bin': 443, 'min_data_in_leaf': 25, 'extra_trees': True, 'early_stopping_rounds': 23, 'path_smooth': 0.042784422457300825, 'min_gain_to_split': 0.02239260599379561}

[I 2025-07-13 14:52:57,223] Trial 80 finished with value: 177.4494630967809 and parameters: {'num_leaves': 87, 'learning_rate': 0.019600020823635746, 'feature_fraction': 0.7961694626543261, 'bagging_fraction': 0.9358956828294202, 'bagging_freq': 3, 'lambda_l1': 5.311825348594448e-06, 'lambda_l2': 0.00014983833740604913, 'min_child_samples': 14, 'max_depth': 3, 'max_bin': 421, 'min_data_in_leaf': 55, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.05493356011923839, 'min_gain_to_split': 0.03406429381803162}. Best is trial 79 with value: 177.44492326122926.

Mejor trial hasta ahora: RMSE=177.444923, Parámetros={'num_leaves': 92, 'learning_rate': 0.013257063567660836, 'feature_fraction': 0.795826108132908, 'bagging_fraction': 0.9160286581963031, 'bagging_freq': 2, 'lambda_l1': 1.7458175327741818, 'lambda_l2': 7.1670967250222865e-06, 'min_child_samples': 14, 'max_depth': 3, 'max_bin': 443, 'min_data_in_leaf': 25, 'extra_trees': True, 'early_stopping_rounds': 23, 'path_smooth': 0.042784422457300825, 'min_gain_to_split': 0.02239260599379561}

[I 2025-07-13 14:54:40,732] Trial 81 finished with value: 177.4889607800331 and parameters: {'num_leaves': 54, 'learning_rate': 0.09778433830413415, 'feature_fraction': 0.8137857208683281, 'bagging_fraction': 0.9159614296004197, 'bagging_freq': 8, 'lambda_l1': 2.3309382363221767, 'lambda_l2': 2.9824014511949108e-05, 'min_child_samples': 13, 'max_depth': 3, 'max_bin': 437, 'min_data_in_leaf': 28, 'extra_trees': True, 'early_stopping_rounds': 21, 'path_smooth': 0.007737752493116527, 'min_gain_to_split': 0.4886475320498209}. Best is trial 79 with value: 177.44492326122926.

Mejor trial hasta ahora: RMSE=177.444923, Parámetros={'num_leaves': 92, 'learning_rate': 0.013257063567660836, 'feature_fraction': 0.795826108132908, 'bagging_fraction': 0.9160286581963031, 'bagging_freq': 2, 'lambda_l1': 1.7458175327741818, 'lambda_l2': 7.1670967250222865e-06, 'min_child_samples': 14, 'max_depth': 3, 'max_bin': 443, 'min_data_in_leaf': 25, 'extra_trees': True, 'early_stopping_rounds': 23, 'path_smooth': 0.042784422457300825, 'min_gain_to_split': 0.02239260599379561}

[I 2025-07-13 14:56:29,836] Trial 82 finished with value: 177.4483662169061 and parameters: {'num_leaves': 84, 'learning_rate': 0.01438615652224961, 'feature_fraction': 0.8567656084887104, 'bagging_fraction': 0.9457673165824696, 'bagging_freq': 3, 'lambda_l1': 1.168834999702591e-06, 'lambda_l2': 7.950453322969493e-06, 'min_child_samples': 15, 'max_depth': 3, 'max_bin': 446, 'min_data_in_leaf': 98, 'extra_trees': True, 'early_stopping_rounds': 23, 'path_smooth': 0.1038446416054142, 'min_gain_to_split': 0.012396973699829512}. Best is trial 79 with value: 177.44492326122926.

Mejor trial hasta ahora: RMSE=177.444923, Parámetros={'num_leaves': 92, 'learning_rate': 0.013257063567660836, 'feature_fraction': 0.795826108132908, 'bagging_fraction': 0.9160286581963031, 'bagging_freq': 2, 'lambda_l1': 1.7458175327741818, 'lambda_l2': 7.1670967250222865e-06, 'min_child_samples': 14, 'max_depth': 3, 'max_bin': 443, 'min_data_in_leaf': 25, 'extra_trees': True, 'early_stopping_rounds': 23, 'path_smooth': 0.042784422457300825, 'min_gain_to_split': 0.02239260599379561}

[I 2025-07-13 14:58:39,544] Trial 83 finished with value: 177.446679386707 and parameters: {'num_leaves': 81, 'learning_rate': 0.01283830792970654, 'feature_fraction': 0.77875983633965, 'bagging_fraction': 0.8877157143257597, 'bagging_freq': 2, 'lambda_l1': 0.47209142235091883, 'lambda_l2': 6.17395830447647e-07, 'min_child_samples': 17, 'max_depth': 3, 'max_bin': 488, 'min_data_in_leaf': 62, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.2264002785336556, 'min_gain_to_split': 0.07269856594979093}. Best is trial 79 with value: 177.44492326122926.

Mejor trial hasta ahora: RMSE=177.444923, Parámetros={'num_leaves': 92, 'learning_rate': 0.013257063567660836, 'feature_fraction': 0.795826108132908, 'bagging_fraction': 0.9160286581963031, 'bagging_freq': 2, 'lambda_l1': 1.7458175327741818, 'lambda_l2': 7.1670967250222865e-06, 'min_child_samples': 14, 'max_depth': 3, 'max_bin': 443, 'min_data_in_leaf': 25, 'extra_trees': True, 'early_stopping_rounds': 23, 'path_smooth': 0.042784422457300825, 'min_gain_to_split': 0.02239260599379561}

[I 2025-07-13 15:00:57,028] Trial 84 finished with value: 177.444171525826 and parameters: {'num_leaves': 80, 'learning_rate': 0.013009577250100757, 'feature_fraction': 0.7492556003203467, 'bagging_fraction': 0.8720679282697087, 'bagging_freq': 2, 'lambda_l1': 0.5274605854157965, 'lambda_l2': 9.24063199397594e-07, 'min_child_samples': 17, 'max_depth': 3, 'max_bin': 470, 'min_data_in_leaf': 70, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.22744662070224936, 'min_gain_to_split': 0.26901333326805343}. Best is trial 84 with value: 177.444171525826.

Mejor trial hasta ahora: RMSE=177.444172, Parámetros={'num_leaves': 80, 'learning_rate': 0.013009577250100757, 'feature_fraction': 0.7492556003203467, 'bagging_fraction': 0.8720679282697087, 'bagging_freq': 2, 'lambda_l1': 0.5274605854157965, 'lambda_l2': 9.24063199397594e-07, 'min_child_samples': 17, 'max_depth': 3, 'max_bin': 470, 'min_data_in_leaf': 70, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.22744662070224936, 'min_gain_to_split': 0.26901333326805343}

[I 2025-07-13 15:03:10,595] Trial 85 finished with value: 177.44639591883075 and parameters: {'num_leaves': 47, 'learning_rate': 0.012962857797315075, 'feature_fraction': 0.7499873923659118, 'bagging_fraction': 0.8667867250048573, 'bagging_freq': 2, 'lambda_l1': 0.3970607732826118, 'lambda_l2': 1.924867703032525e-07, 'min_child_samples': 13, 'max_depth': 3, 'max_bin': 258, 'min_data_in_leaf': 64, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.22752413454513462, 'min_gain_to_split': 0.02234869392138361}. Best is trial 84 with value: 177.444171525826.

Mejor trial hasta ahora: RMSE=177.444172, Parámetros={'num_leaves': 80, 'learning_rate': 0.013009577250100757, 'feature_fraction': 0.7492556003203467, 'bagging_fraction': 0.8720679282697087, 'bagging_freq': 2, 'lambda_l1': 0.5274605854157965, 'lambda_l2': 9.24063199397594e-07, 'min_child_samples': 17, 'max_depth': 3, 'max_bin': 470, 'min_data_in_leaf': 70, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.22744662070224936, 'min_gain_to_split': 0.26901333326805343}

[I 2025-07-13 15:05:11,243] Trial 86 finished with value: 177.4434870320175 and parameters: {'num_leaves': 45, 'learning_rate': 0.01311209217492973, 'feature_fraction': 0.7211788010574011, 'bagging_fraction': 0.8699423614124506, 'bagging_freq': 2, 'lambda_l1': 0.6064372125146411, 'lambda_l2': 1.7701456616316702e-07, 'min_child_samples': 17, 'max_depth': 3, 'max_bin': 262, 'min_data_in_leaf': 69, 'extra_trees': True, 'early_stopping_rounds': 30, 'path_smooth': 0.2244416859102201, 'min_gain_to_split': 0.024200075244305806}. Best is trial 86 with value: 177.4434870320175.

Mejor trial hasta ahora: RMSE=177.443487, Parámetros={'num_leaves': 45, 'learning_rate': 0.01311209217492973, 'feature_fraction': 0.7211788010574011, 'bagging_fraction': 0.8699423614124506, 'bagging_freq': 2, 'lambda_l1': 0.6064372125146411, 'lambda_l2': 1.7701456616316702e-07, 'min_child_samples': 17, 'max_depth': 3, 'max_bin': 262, 'min_data_in_leaf': 69, 'extra_trees': True, 'early_stopping_rounds': 30, 'path_smooth': 0.2244416859102201, 'min_gain_to_split': 0.024200075244305806}

[I 2025-07-13 15:07:21,361] Trial 87 finished with value: 177.44720908346878 and parameters: {'num_leaves': 38, 'learning_rate': 0.016564317818855603, 'feature_fraction': 0.7165048713733666, 'bagging_fraction': 0.8449234545245253, 'bagging_freq': 2, 'lambda_l1': 0.36696995011261735, 'lambda_l2': 1.4552327182551643e-07, 'min_child_samples': 17, 'max_depth': 3, 'max_bin': 257, 'min_data_in_leaf': 64, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.2316860522734448, 'min_gain_to_split': 0.042795258451999954}. Best is trial 86 with value: 177.4434870320175.

Mejor trial hasta ahora: RMSE=177.443487, Parámetros={'num_leaves': 45, 'learning_rate': 0.01311209217492973, 'feature_fraction': 0.7211788010574011, 'bagging_fraction': 0.8699423614124506, 'bagging_freq': 2, 'lambda_l1': 0.6064372125146411, 'lambda_l2': 1.7701456616316702e-07, 'min_child_samples': 17, 'max_depth': 3, 'max_bin': 262, 'min_data_in_leaf': 69, 'extra_trees': True, 'early_stopping_rounds': 30, 'path_smooth': 0.2244416859102201, 'min_gain_to_split': 0.024200075244305806}

[I 2025-07-13 15:09:14,729] Trial 88 finished with value: 177.44910720415814 and parameters: {'num_leaves': 44, 'learning_rate': 0.02185886441819603, 'feature_fraction': 0.681575306337031, 'bagging_fraction': 0.8674978255788864, 'bagging_freq': 2, 'lambda_l1': 0.6376061202880541, 'lambda_l2': 6.918539884195289e-07, 'min_child_samples': 14, 'max_depth': 3, 'max_bin': 224, 'min_data_in_leaf': 70, 'extra_trees': True, 'early_stopping_rounds': 31, 'path_smooth': 0.25808567738359983, 'min_gain_to_split': 0.06789801291949113}. Best is trial 86 with value: 177.4434870320175.

Mejor trial hasta ahora: RMSE=177.443487, Parámetros={'num_leaves': 45, 'learning_rate': 0.01311209217492973, 'feature_fraction': 0.7211788010574011, 'bagging_fraction': 0.8699423614124506, 'bagging_freq': 2, 'lambda_l1': 0.6064372125146411, 'lambda_l2': 1.7701456616316702e-07, 'min_child_samples': 17, 'max_depth': 3, 'max_bin': 262, 'min_data_in_leaf': 69, 'extra_trees': True, 'early_stopping_rounds': 30, 'path_smooth': 0.2244416859102201, 'min_gain_to_split': 0.024200075244305806}

[I 2025-07-13 15:11:12,919] Trial 89 finished with value: 177.4469725576674 and parameters: {'num_leaves': 49, 'learning_rate': 0.013142089555937032, 'feature_fraction': 0.7493265557940386, 'bagging_fraction': 0.8885353965077868, 'bagging_freq': 2, 'lambda_l1': 0.16515378630278943, 'lambda_l2': 3.253529144487274e-08, 'min_child_samples': 15, 'max_depth': 3, 'max_bin': 285, 'min_data_in_leaf': 63, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.30018822957050384, 'min_gain_to_split': 0.09569709709114746}. Best is trial 86 with value: 177.4434870320175.

Mejor trial hasta ahora: RMSE=177.443487, Parámetros={'num_leaves': 45, 'learning_rate': 0.01311209217492973, 'feature_fraction': 0.7211788010574011, 'bagging_fraction': 0.8699423614124506, 'bagging_freq': 2, 'lambda_l1': 0.6064372125146411, 'lambda_l2': 1.7701456616316702e-07, 'min_child_samples': 17, 'max_depth': 3, 'max_bin': 262, 'min_data_in_leaf': 69, 'extra_trees': True, 'early_stopping_rounds': 30, 'path_smooth': 0.2244416859102201, 'min_gain_to_split': 0.024200075244305806}

Prediccion

In [23]:
df_future = model_lgb.semillerio_en_prediccion_con_pesos(train, test, version="v21")

In [24]:
df_future

       periodo  product_id  target      pred
30476   201912       20001     0.0  0.983107
30477   201912       20002     0.0  1.174595
30478   201912       20003     0.0  0.429366
30479   201912       20004     0.0  0.579315
30480   201912       20005     0.0  0.679257
...        ...         ...     ...       ...
31357   201912       21265     0.0  0.802648
31358   201912       21266     0.0  0.451392
31359   201912       21267     0.0  0.029572
31360   201912       21271     0.0  0.308942
31361   201912       21276     0.0  0.744200

[886 rows x 4 columns]

Filtramos los 180 productos

In [25]:
productos_ok = pd.read_csv("https://storage.googleapis.com/open-courses/austral2025-af91/labo3v/product_id_apredecir201912.txt", sep="\t")
df_future = df_future[df_future['periodo'] == 201912]
df_future = df_future[df_future['product_id'].isin(productos_ok['product_id'].unique())]

In [26]:
df_future

       periodo  product_id  target      pred
30476   201912       20001     0.0  0.983107
30477   201912       20002     0.0  1.174595
30478   201912       20003     0.0  0.429366
30479   201912       20004     0.0  0.579315
30480   201912       20005     0.0  0.679257
...        ...         ...     ...       ...
31355   201912       21263     0.0  0.314934
31357   201912       21265     0.0  0.802648
31358   201912       21266     0.0  0.451392
31359   201912       21267     0.0  0.029572
31361   201912       21276     0.0  0.744200

[780 rows x 4 columns]

In [27]:
df_future_copy = df_future.copy()

In [28]:
import os
ruta_archivo = f'./datasets/tn_stats_201912.csv'
    
df_stats = pd.DataFrame()

if os.path.exists(ruta_archivo) and ruta_archivo.endswith('.csv'):
    df_stats = pd.read_csv(ruta_archivo, sep=',')

df_stats

      product_id      tn_mean      tn_std
0          20001  1398.344322  293.975388
1          20002  1009.368178  299.585187
2          20003   889.004243  287.951952
3          20004   671.615383  221.310769
4          20005   644.200514  215.220300
...          ...          ...         ...
1159       21271     0.024268    0.019484
1160       21273     0.057242    0.124272
1161       21274     0.067028    0.096980
1162       21276     0.045447    0.041380
1163       21281     0.021060    0.031414

[1164 rows x 3 columns]

In [29]:
df_future_copy = df_future_copy.merge(df_stats, on=['product_id'], how='left')
df_future_copy

     periodo  product_id  target      pred      tn_mean      tn_std
0     201912       20001     0.0  0.983107  1398.344322  293.975388
1     201912       20002     0.0  1.174595  1009.368178  299.585187
2     201912       20003     0.0  0.429366   889.004243  287.951952
3     201912       20004     0.0  0.579315   671.615383  221.310769
4     201912       20005     0.0  0.679257   644.200514  215.220300
..       ...         ...     ...       ...          ...         ...
775   201912       21263     0.0  0.314934     0.089233    0.148180
776   201912       21265     0.0  0.802648     0.089541    0.103219
777   201912       21266     0.0  0.451392     0.094659    0.100530
778   201912       21267     0.0  0.029572     0.092835    0.075836
779   201912       21276     0.0  0.744200     0.045447    0.041380

[780 rows x 6 columns]

In [30]:

df_future_copy['tn'] = df_future_copy['pred'] * df_future_copy['tn_std'] + df_future_copy['tn_mean']
df_future_copy

,periodo,product_id,target,pred,tn_mean,tn_std,tn
0,201912,20001,0.0,0.983107,1398.344322,293.975388,1687.353551
1,201912,20002,0.0,1.174595,1009.368178,299.585187,1361.259501
2,201912,20003,0.0,0.429366,889.004243,287.951952,1012.641029
3,201912,20004,0.0,0.579315,671.615383,221.310769,799.823966
4,201912,20005,0.0,0.679257,644.200514,215.220300,790.390495
...,...,...,...,...,...,...,...
775,201912,21263,0.0,0.314934,0.089233,0.148180,0.135900
776,201912,21265,0.0,0.802648,0.089541,0.103219,0.172390
777,201912,21266,0.0,0.451392,0.094659,0.100530,0.140038
778,201912,21267,0.0,0.029572,0.092835,0.075836,0.095078
779,201912,21276,0.0,0.744200,0.045447,0.041380,0.076242

Vemos cuantos negativos hay

In [31]:
df_future_copy[df_future_copy['tn'] < 0]

Empty DataFrame
Columns: [periodo, product_id, target, pred, tn_mean, tn_std, tn]
Index: []

Reemplazamos los negativos por el promedio de ultimos 12 meses

In [ ]:
# promedio780 = model_lgb.promedio_12_meses_780p()
# df_future = df_future.merge(promedio780, on='product_id', how='left')
# df_future.drop(columns=['target','periodo'], inplace=True)
# df_future.loc[df_future['pred'] < 0, 'pred'] = df_future['tn']
# df_future

     product_id         pred           tn
0         20001  1397.305481  1454.732720
1         20002  1086.538942  1175.437142
2         20003   747.163659   784.976407
3         20004   565.799872   627.215328
4         20005   638.965713   668.270104
..          ...          ...          ...
775       21263     0.029993     0.029993
776       21265     0.791975     0.089541
777       21266     0.094659     0.094659
778       21267     0.092835     0.092835
779       21276     0.045447     0.045447

[780 rows x 3 columns]

Guardamos el archivo

In [32]:
# df_future_copy.drop(columns=['tn'], inplace=True)
# df_future_copy.rename(columns={'pred': 'tn'}, inplace=True)
df_future_copy[['product_id', 'tn']].to_csv("./outputs/predicciones_exp_07_lgb_v9.csv", index=False, sep=',')

Ensemble

In [31]:
df_lgb = df_future_copy[['product_id', 'tn']].rename(columns={'tn': 'tn_lgb'})
df_rl = pd.read_csv("./outputs/predicciones_regresion_lineal_v1.csv", sep=',', encoding='utf-8').rename(columns={'tn': 'tn_rl'})
df_ensemble = df_lgb.merge(df_rl, on='product_id', how='left')
df_ensemble['tn'] = (df_ensemble['tn_lgb'] + df_ensemble['tn_rl']) / 2
df_ensemble[['product_id', 'tn']].to_csv("./outputs/predicciones_exp_07_lgb_v6_ensemble.csv", index=False, sep=',')

In [32]:
df_lgb = df_future_copy[['product_id', 'tn']].rename(columns={'tn': 'tn_lgb'})
df_rl = pd.read_csv("./outputs/predicciones_regresion_lineal_v1.csv", sep=',', encoding='utf-8').rename(columns={'tn': 'tn_rl'})
df_ag = pd.read_csv("./outputs/prediccion_autogluon_2ventanas.csv", sep=',', encoding='utf-8').rename(columns={'tn': 'tn_ag'})
df_ensemble = df_lgb.merge(df_rl, on='product_id', how='left')
df_ensemble = df_ensemble.merge(df_ag, on='product_id', how='left')
df_ensemble['tn'] = (df_ensemble['tn_lgb'] + df_ensemble['tn_rl'] + df_ensemble['tn_ag']) / 3
df_ensemble[['product_id', 'tn']].to_csv("./outputs/predicciones_exp_07_lgb_v6_ensemble_3models.csv", index=False, sep=',')