In [86]:
import pandas as pd
import numpy as np
import importlib
import gc
import sys
import warnings
sys.path.append('./scripts')  
import preprocesamiento
import target
import feature_engineering
import model_lgb
import model_lgb_simple
importlib.reload(preprocesamiento)
importlib.reload(target)
importlib.reload(model_lgb)
importlib.reload(model_lgb_simple)
importlib.reload(feature_engineering)
warnings.filterwarnings("ignore")

# Experimento 9: 
- LGBM
- Estandarización hasta 201906
- Estandarizacion del target
- Semillerio en train y test
- Agrego variables: agrego los ceros que dijo el profesor.
- Pesos: logaritmo
- sqlite:///optuna_studies_v22.db
- Kaggle =

**Training:**
```python
training = [
    201701, 201702, 201703, 201704, 201705, 201706, 201707, 201708, 201709,
    201710, 201711, 201712, 201801, 201802, 201803, 201804, 201805,
    201806, 201807, 201808, 201809, 201810, 201811, 201812,
    201901, 201902, 201903, 201904, 201905, 201906
]

validation = [
    # 201907, 201908
    201907, 201909
]

testing = [
    201910
]

Levantamos

In [ ]:
df = pd.read_csv('./datasets/periodo_x_producto.csv', sep=',', encoding='utf-8')

Estandarizacion zscore

In [48]:
df = preprocesamiento.normalizar_con_zscore(df, "tn", fecha=201806)
df

,product_id,periodo,nacimiento_producto,muerte_producto,mes_n,total_meses,producto_nuevo,ciclo_de_vida_inicial,cat1,cat2,...,brand,sku_size,stock_final,tn,plan_precios_cuidados,cust_request_qty,cust_request_tn,tn_mean,tn_std,tn_zscore
0,20001,201701,201701,201912,1,36,0,0,HC,ROPA LAVADO,...,ARIEL,3000.0,NaN,934.77222,0.0,479.0,937.72717,1254.369806,251.944810,-1.268522
1,20001,201702,201701,201912,2,36,0,0,HC,ROPA LAVADO,...,ARIEL,3000.0,NaN,798.01620,0.0,432.0,833.72187,1254.369806,251.944810,-1.811324
2,20001,201703,201701,201912,3,36,0,0,HC,ROPA LAVADO,...,ARIEL,3000.0,NaN,1303.35771,0.0,509.0,1330.74697,1254.369806,251.944810,0.194439
3,20001,201704,201701,201912,4,36,0,0,HC,ROPA LAVADO,...,ARIEL,3000.0,NaN,1069.96130,0.0,279.0,1132.94430,1254.369806,251.944810,-0.731940
4,20001,201705,201701,201912,5,36,0,0,HC,ROPA LAVADO,...,ARIEL,3000.0,NaN,1502.20132,0.0,701.0,1550.68936,1254.369806,251.944810,0.983674
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31357,21281,201704,201702,201708,3,7,1,1,NaN,NaN,...,NaN,NaN,NaN,0.00000,NaN,NaN,NaN,0.021060,0.031414,-0.670410
31358,21281,201705,201702,201708,4,7,1,0,NaN,NaN,...,NaN,NaN,NaN,0.00000,NaN,NaN,NaN,0.021060,0.031414,-0.670410
31359,21281,201706,201702,201708,5,7,1,0,NaN,NaN,...,NaN,NaN,NaN,0.09134,0.0,8.0,0.10539,0.021060,0.031414,2.237248
31360,21281,201707,201702,201708,6,7,1,0,NaN,NaN,...,NaN,NaN,NaN,0.00000,NaN,NaN,NaN,0.021060,0.031414,-0.670410
31361,21281,201708,201702,201708,7,7,1,0,NaN,NaN,...,NaN,NaN,NaN,0.03500,0.0,1.0,0.03500,0.021060,0.031414,0.443757

In [49]:
df.rename(columns={'tn':'tn_original'}, inplace=True)
df.rename(columns={'tn_zscore':'tn'}, inplace=True)

Guardamos

In [12]:
df.to_csv("../../data/preprocessed/periodo_x_producto_con_target_zscore_201906.csv", index=False, sep=',', encoding='utf-8')

##### Procesamiento del Target

In [50]:
df = pd.read_csv("../../data/preprocessed/periodo_x_producto_con_target_zscore_201906.csv", sep=',', encoding='utf-8')

print(df.shape)

df = target.target_tn_mas_dos(df)

print(df.shape)

(31362, 21)
(31362, 22)

##### Feature Engineering

In [51]:
columnas_baseline = df.columns.tolist()
columnas_baseline

['product_id',
 'periodo',
 'nacimiento_producto',
 'muerte_producto',
 'mes_n',
 'total_meses',
 'producto_nuevo',
 'ciclo_de_vida_inicial',
 'cat1',
 'cat2',
 'cat3',
 'brand',
 'sku_size',
 'stock_final',
 'tn_original',
 'plan_precios_cuidados',
 'cust_request_qty',
 'cust_request_tn',
 'tn_mean',
 'tn_std',
 'tn',
 'target']

##### Preprocesamiento a la minima expresión :)

In [52]:
df = feature_engineering.create_category_features_cat1(df)
df = feature_engineering.create_category_features_cat2(df)
df = feature_engineering.create_category_features_cat3(df)

In [53]:
# ##### aplicamos OHE
df = preprocesamiento.aplicarOHE(df)
df.shape

(31362, 174)

### Feature Engineering

##### Neural Prophet

In [54]:
neural_prophet_fe = pd.read_csv("./datasets/features_neuralprophet_completo.csv", sep=',', encoding='utf-8')
neural_prophet_fe['ds'] = pd.to_datetime(neural_prophet_fe['ds'], errors='coerce')
# Versión alternativa más robusta:
neural_prophet_fe['periodo'] = neural_prophet_fe['ds'].apply(
    lambda x: x.year * 100 + x.month if pd.notnull(x) else None
)
neural_prophet_fe = neural_prophet_fe[['periodo', 'product_id', 'trend', "season_yearly", "season_monthly"]]
df = df.merge(neural_prophet_fe, on=['periodo', 'product_id'], how='left')
df.shape

(31362, 177)

##### Prophet

In [55]:
prophet_fe = pd.read_csv("./datasets/prophet_features_tn_zscore.csv", sep=',', encoding='utf-8')
prophet_fe['ds'] = pd.to_datetime(prophet_fe['ds'], errors='coerce')
prophet_fe['periodo'] = prophet_fe['ds'].apply(
    lambda x: x.year * 100 + x.month if pd.notnull(x) else None
)
prophet_fe = prophet_fe[['periodo', 'product_id', 'trend_add', "yearly_add", "additive_terms", 'trend_mult', 'yearly_mult', 'multiplicative_terms']]
df = df.merge(prophet_fe, on=['periodo', 'product_id'], how='left')
df.shape

(31362, 183)

##### FE Moviles

In [56]:
df = feature_engineering.get_lags(df, "tn", 201912)
df = feature_engineering.get_delta_lags(df, "tn", 24)
df = feature_engineering.get_rolling_means(df, "tn", 201912)
df = feature_engineering.get_rolling_stds(df, "tn", 201912)
df = feature_engineering.get_rolling_mins(df, "tn", 201912)
df = feature_engineering.get_rolling_maxs(df, "tn", 201912)
df = feature_engineering.get_rolling_medians(df, "tn", 201912)
df = feature_engineering.get_rolling_skewness(df, "tn", 201912)
df = feature_engineering.get_autocorrelaciones(df, "tn", 201912)
df.shape

(31362, 745)

In [57]:
df = feature_engineering.get_lags(df, "cust_request_qty", 201912)
df = feature_engineering.get_delta_lags(df, "cust_request_qty", 24)
df = feature_engineering.get_rolling_means(df, "cust_request_qty", 201912)
df = feature_engineering.get_rolling_stds(df, "cust_request_qty", 201912)
df = feature_engineering.get_rolling_mins(df, "cust_request_qty", 201912)
df = feature_engineering.get_rolling_maxs(df, "cust_request_qty", 201912)
df.shape

(31362, 1200)

In [58]:
df = feature_engineering.get_lags(df, "stock_final", 201912)
df = feature_engineering.get_delta_lags(df, "stock_final", 24)
df = feature_engineering.get_rolling_means(df, "stock_final", 201912)
df = feature_engineering.get_rolling_stds(df, "stock_final", 201912)
df = feature_engineering.get_rolling_mins(df, "stock_final", 201912)
df = feature_engineering.get_rolling_maxs(df, "stock_final", 201912)
df.shape

(31362, 1655)

Features Diana

In [59]:
df = feature_engineering.calcular_diferencia_con_medias_moviles(df)
df = feature_engineering.calcular_ratios_con_medias_moviles(df)
df.shape

(31362, 1691)

##### FE Moviles sobre otras variables

In [56]:
# #  stock final
# df = feature_engineering.get_lagsEspecificos(df, col='stock_final_zscore')
# df = feature_engineering.get_delta_lags_especificos(df, col='stock_final_zscore')
# df = feature_engineering.get_rolling_means_especificos(df, col='stock_final_zscore')
# df = feature_engineering.get_rolling_stds_especificos(df, col='stock_final_zscore')
# df = feature_engineering.get_rolling_medians_especificos(df, col='stock_final_zscore')
# df = feature_engineering.get_rolling_mins_especificos(df, col='stock_final_zscore')
# df = feature_engineering.get_rolling_maxs_especificos(df, col='stock_final_zscore')
# df = feature_engineering.get_rolling_skewness_especificos(df, col='stock_final_zscore')

#  cust_request_qty
# df = feature_engineering.get_lagsEspecificos(df, col='cust_request_qty')
# df = feature_engineering.get_delta_lags_especificos(df, col='cust_request_qty')
# df = feature_engineering.get_rolling_means_especificos(df, col='cust_request_qty')
# df = feature_engineering.get_rolling_stds_especificos(df, col='cust_request_qty')
# df = feature_engineering.get_rolling_mins_especificos(df, col='cust_request_qty')
# df = feature_engineering.get_rolling_maxs_especificos(df, col='cust_request_qty')
# df = feature_engineering.get_rolling_medians_especificos(df, col='cust_request_qty')
# df = feature_engineering.get_rolling_skewness_especificos(df, col='cust_request_qty')

##### FE Calendario

In [60]:
df = feature_engineering.generar_ids(df)
df = feature_engineering.get_componentesTemporales(df)
df = feature_engineering.get_anomaliasPoliticas(df)
# df = feature_engineering.descomposicion_serie_temporal(df, col='tn')
df.shape

(31362, 1716)

##### FE sobre FE

In [61]:
df = feature_engineering.chatGPT_features_serie(df, "tn")
df = feature_engineering.mes_con_feriado(df)
df.shape

(31362, 1745)

##### Variables Exogenas

In [62]:
df = feature_engineering.get_dolar(df)
df = feature_engineering.get_IPC(df)
df['ipc'] = df['ipc'].str.replace(',', '.').astype(float)
df['dolar'] = df['dolar'].str.replace(',', '.').astype(float)
# df.drop(columns=['ds'], inplace=True)
df.fillna(0, inplace=True) ##### EXPERIMENTAR
df = feature_engineering.correlacion_exogenas(df)
df = feature_engineering.get_mes_receso_escolar(df)
df.shape

(31362, 1748)

##### Nuevas FE

In [63]:
df = feature_engineering.create_ratio_features(df)
df = feature_engineering.enhance_lifecycle_features(df)
# df = feature_engineering.create_category_features(df)
df = feature_engineering.create_regime_features(df)
df = feature_engineering.create_nonlinear_trends(df)
df = feature_engineering.create_temporal_interactions(df)
df = feature_engineering.create_asymmetric_window_features(df)
df = feature_engineering.recomendaciones_deepseek(df)
df = feature_engineering.get_nuevas_features(df)
df.shape

(31362, 1787)

##### Ceros

In [17]:
df = feature_engineering.agregar_ceros_consecutivos_atras(df, col_tn='tn_original')
df = feature_engineering.agregar_no_ceros_consecutivos_atras(df, col_tn='tn_original')
df = feature_engineering.agregar_ceros_ultimos_n_meses(df, ventanas=[1,2,3,4,5,6,12], col_tn='tn_original')
df = feature_engineering.agregar_min_max_ult_n(df, n_list=(1,2,3,4,5,6,12), col_tn='tn_original')
df.shape

(31362, 1810)

##### Elimino aquellas que no sirven

In [ ]:
import json
import pandas as pd
import csv

with open("./feature_importance/v19.json") as f:
    data = json.load(f)

# Crear una lista de tuplas (feature, value)
features_values = [(feature, value) for feature, value in data.items()]

# Guardar en un archivo CSV
with open('./feature_importance/v19.csv', 'w', newline='') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow(['feature', 'importance'])  # Escribir el encabezado
    writer.writerows(features_values)      # Escribir los datos

print("Archivo CSV generado exitosamente: features_values.csv")

Archivo CSV generado exitosamente: features_values.csv

In [40]:
importantes = pd.read_csv("./feature_importance/v19.csv", sep=',', encoding='utf-8')
no_importantes = importantes[importantes['importance'] == 0]
no_importantes = no_importantes[~no_importantes['feature'].isin(columnas_baseline)]
no_importantes

                         feature  importance
1103           tn_rolling_std_20         0.0
1104           tn_rolling_std_22         0.0
1105           tn_rolling_std_25         0.0
1106           tn_rolling_std_26         0.0
1107           tn_rolling_std_27         0.0
...                          ...         ...
1781             cat3_Acond Bebe         0.0
1782        tn_rolling_median_25         0.0
1783        tn_rolling_median_24         0.0
1786            tn_rolling_std_1         0.0
1787  stock_final_rolling_min_23         0.0

[683 rows x 2 columns]

In [41]:
cols_a_eliminar = no_importantes.feature.unique()
print(f"Antes de eliminar: {df.shape[1]} columnas")
df = df.drop(columns=cols_a_eliminar, errors='ignore')
print(f"Después de eliminar: {df.shape[1]} columnas")

Antes de eliminar: 1787 columnas
Después de eliminar: 1104 columnas

Eliminar object/categorical columnas

In [64]:
df = df.select_dtypes(exclude=['datetime', 'datetime64', 'object', 'category'])

In [45]:
df['target'].isna().sum()

np.int64(0)

Train Test Split

In [65]:
train = df[df['periodo'] <= 201912]
test = df[df['periodo'] == 201912]

Entrenamiento

In [68]:

model_lgb_simple.optimizar_con_optuna_sin5FCV_con_semillerio_db(train, version="v22", n_trials=500)

Para visualizar los resultados en tiempo real:
1. Abre otra terminal y ejecuta:
   optuna-dashboard sqlite:///optuna_studies_v22.db
2. Abre en tu navegador: http://127.0.0.1:8080/

[I 2025-07-13 19:55:28,378] Using an existing study with name 'lightgbm_optimization_v22' instead of creating a new one.
[I 2025-07-13 19:56:36,412] Trial 289 finished with value: 124.27045080936986 and parameters: {'num_leaves': 83, 'learning_rate': 0.10809366764261591, 'feature_fraction': 0.6668086637168998, 'bagging_fraction': 0.9697017443698029, 'bagging_freq': 8, 'lambda_l1': 5.5313912737064595e-06, 'lambda_l2': 0.030070928012921057, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 322, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 23, 'path_smooth': 0.4478078172035074, 'min_gain_to_split': 0.047899714155294044}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 19:58:41,638] Trial 290 finished with value: 123.51206184111388 and parameters: {'num_leaves': 16, 'learning_rate': 0.09846709011591549, 'feature_fraction': 0.6342974086889194, 'bagging_fraction': 0.9931336989753181, 'bagging_freq': 10, 'lambda_l1': 9.030211108439333e-07, 'lambda_l2': 1.7270812116459777e-08, 'min_child_samples': 47, 'max_depth': 10, 'max_bin': 486, 'min_data_in_leaf': 67, 'extra_trees': False, 'early_stopping_rounds': 33, 'path_smooth': 0.8469961233886656, 'min_gain_to_split': 0.06064486906058383}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 19:59:49,360] Trial 291 finished with value: 119.29032137829977 and parameters: {'num_leaves': 22, 'learning_rate': 0.11614613980375857, 'feature_fraction': 0.65253742780935, 'bagging_fraction': 0.9577919910264876, 'bagging_freq': 10, 'lambda_l1': 1.7187287791950328e-06, 'lambda_l2': 0.11549577749073062, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 500, 'min_data_in_leaf': 42, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.8041725794331964, 'min_gain_to_split': 0.02980863157131907}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:00:41,888] Trial 292 finished with value: 131.88365762987075 and parameters: {'num_leaves': 27, 'learning_rate': 0.12927020357840524, 'feature_fraction': 0.6435079118255939, 'bagging_fraction': 0.977929712021997, 'bagging_freq': 10, 'lambda_l1': 2.852196860818722e-07, 'lambda_l2': 0.0107579475569039, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 345, 'min_data_in_leaf': 63, 'extra_trees': True, 'early_stopping_rounds': 35, 'path_smooth': 0.03148274766361214, 'min_gain_to_split': 0.015864385820130493}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:01:50,915] Trial 293 finished with value: 135.48318947877777 and parameters: {'num_leaves': 19, 'learning_rate': 0.09241426750196442, 'feature_fraction': 0.6605816151876237, 'bagging_fraction': 0.9656807959455549, 'bagging_freq': 8, 'lambda_l1': 1.2995293409900031e-05, 'lambda_l2': 0.06667575441075367, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 477, 'min_data_in_leaf': 65, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.8918882220091406, 'min_gain_to_split': 0.037319017245078676}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:02:35,415] Trial 294 finished with value: 113.83313579150938 and parameters: {'num_leaves': 17, 'learning_rate': 0.14476468751924662, 'feature_fraction': 0.8984553239225072, 'bagging_fraction': 0.9842590346225456, 'bagging_freq': 9, 'lambda_l1': 3.426090030005731e-06, 'lambda_l2': 0.018594998503014534, 'min_child_samples': 44, 'max_depth': 10, 'max_bin': 334, 'min_data_in_leaf': 33, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.986584842985717, 'min_gain_to_split': 0.025164543116400227}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:03:36,390] Trial 295 finished with value: 134.40362233778154 and parameters: {'num_leaves': 21, 'learning_rate': 0.10190873605818385, 'feature_fraction': 0.6755187466681152, 'bagging_fraction': 0.9447240440871612, 'bagging_freq': 10, 'lambda_l1': 1.3538798263084943, 'lambda_l2': 0.006652314899706267, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 375, 'min_data_in_leaf': 55, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.9121828963834467, 'min_gain_to_split': 0.32102429802590615}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:04:43,204] Trial 296 finished with value: 128.5662379524054 and parameters: {'num_leaves': 25, 'learning_rate': 0.11025164562504772, 'feature_fraction': 0.6261948094282564, 'bagging_fraction': 0.9348572083471756, 'bagging_freq': 10, 'lambda_l1': 5.641859505848189e-07, 'lambda_l2': 0.03315605151906261, 'min_child_samples': 47, 'max_depth': 10, 'max_bin': 286, 'min_data_in_leaf': 52, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.4091401994096536, 'min_gain_to_split': 0.11297409656911771}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:05:50,000] Trial 297 finished with value: 125.96749961395619 and parameters: {'num_leaves': 76, 'learning_rate': 0.12039299284129808, 'feature_fraction': 0.6507477123313307, 'bagging_fraction': 0.9732218908338467, 'bagging_freq': 10, 'lambda_l1': 9.431965155987949e-06, 'lambda_l2': 0.003432226550094423, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 458, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 46, 'path_smooth': 0.9483730380233435, 'min_gain_to_split': 0.04867561757421633}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:06:55,079] Trial 298 finished with value: 137.40743310497078 and parameters: {'num_leaves': 15, 'learning_rate': 0.16319405935160144, 'feature_fraction': 0.6844824212645619, 'bagging_fraction': 0.9540860955885433, 'bagging_freq': 9, 'lambda_l1': 1.9207098578842644e-05, 'lambda_l2': 0.046205571190669995, 'min_child_samples': 42, 'max_depth': 10, 'max_bin': 489, 'min_data_in_leaf': 67, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.437949043497286, 'min_gain_to_split': 0.037495836550326955}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:07:50,728] Trial 299 finished with value: 112.24835243049738 and parameters: {'num_leaves': 23, 'learning_rate': 0.10594596415781471, 'feature_fraction': 0.6680243353248817, 'bagging_fraction': 0.960285840538111, 'bagging_freq': 10, 'lambda_l1': 1.1691858753765081e-06, 'lambda_l2': 0.014383688278114298, 'min_child_samples': 46, 'max_depth': 10, 'max_bin': 358, 'min_data_in_leaf': 30, 'extra_trees': True, 'early_stopping_rounds': 33, 'path_smooth': 0.41763305627725456, 'min_gain_to_split': 0.011075985669136557}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:08:54,563] Trial 300 finished with value: 138.30058999123105 and parameters: {'num_leaves': 19, 'learning_rate': 0.13394577787302334, 'feature_fraction': 0.6584929051632015, 'bagging_fraction': 0.9491255386770785, 'bagging_freq': 10, 'lambda_l1': 5.293187156855785e-06, 'lambda_l2': 0.09793049193665827, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 369, 'min_data_in_leaf': 70, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.48955409656364895, 'min_gain_to_split': 0.0005401025094334527}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:09:48,599] Trial 301 finished with value: 127.1606743630391 and parameters: {'num_leaves': 20, 'learning_rate': 0.09660088701042596, 'feature_fraction': 0.637852540231738, 'bagging_fraction': 0.9683311115204215, 'bagging_freq': 10, 'lambda_l1': 1.1826221941654133e-07, 'lambda_l2': 0.022623100891119772, 'min_child_samples': 45, 'max_depth': 10, 'max_bin': 469, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 30, 'path_smooth': 0.9754359655338606, 'min_gain_to_split': 0.08975595619341217}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:10:39,561] Trial 302 finished with value: 110.3546681348729 and parameters: {'num_leaves': 17, 'learning_rate': 0.11542641902695996, 'feature_fraction': 0.6447036928754206, 'bagging_fraction': 0.9217448734979578, 'bagging_freq': 9, 'lambda_l1': 2.6969524781083733e-05, 'lambda_l2': 0.007768204393424543, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 349, 'min_data_in_leaf': 40, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.9312140510898756, 'min_gain_to_split': 0.021009983309590922}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:11:46,424] Trial 303 finished with value: 133.93212512759715 and parameters: {'num_leaves': 22, 'learning_rate': 0.08975937111721813, 'feature_fraction': 0.6743450197747751, 'bagging_fraction': 0.942986602558942, 'bagging_freq': 8, 'lambda_l1': 7.4027855252219e-07, 'lambda_l2': 0.010523433527635425, 'min_child_samples': 44, 'max_depth': 10, 'max_bin': 482, 'min_data_in_leaf': 61, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.46081890939636677, 'min_gain_to_split': 0.06714809889249941}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:13:51,436] Trial 304 finished with value: 146.84015820267194 and parameters: {'num_leaves': 28, 'learning_rate': 0.013359706377499819, 'feature_fraction': 0.6578728807989701, 'bagging_fraction': 0.8651064126296075, 'bagging_freq': 10, 'lambda_l1': 8.075460722880704e-06, 'lambda_l2': 0.025548679531200245, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 389, 'min_data_in_leaf': 65, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.1634775391630267, 'min_gain_to_split': 0.029928171531519467}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:14:46,284] Trial 305 finished with value: 120.49217741401216 and parameters: {'num_leaves': 66, 'learning_rate': 0.12517753822585226, 'feature_fraction': 0.6973222422870333, 'bagging_fraction': 0.9757381732530812, 'bagging_freq': 10, 'lambda_l1': 1.5533769658889886e-06, 'lambda_l2': 0.0019437785484588046, 'min_child_samples': 47, 'max_depth': 10, 'max_bin': 493, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.3847053966331111, 'min_gain_to_split': 0.4460284080752745}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:15:38,882] Trial 306 finished with value: 120.67607205554468 and parameters: {'num_leaves': 24, 'learning_rate': 0.08235577467911104, 'feature_fraction': 0.6311337830975664, 'bagging_fraction': 0.9566825571714224, 'bagging_freq': 10, 'lambda_l1': 1.3031176750963527e-08, 'lambda_l2': 0.0454997797969867, 'min_child_samples': 33, 'max_depth': 10, 'max_bin': 484, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 31, 'path_smooth': 0.7268431177164179, 'min_gain_to_split': 0.04927461787161244}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:16:32,405] Trial 307 finished with value: 135.23524570539965 and parameters: {'num_leaves': 46, 'learning_rate': 0.1511865748055878, 'feature_fraction': 0.6668585379218358, 'bagging_fraction': 0.9648279220980726, 'bagging_freq': 10, 'lambda_l1': 1.561925289717124e-05, 'lambda_l2': 0.016604016117712523, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 276, 'min_data_in_leaf': 67, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.9568240586014595, 'min_gain_to_split': 0.3064695816035018}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:17:21,224] Trial 308 finished with value: 121.86046912560603 and parameters: {'num_leaves': 20, 'learning_rate': 0.14038010372652857, 'feature_fraction': 0.6500751471780274, 'bagging_fraction': 0.9365350935395689, 'bagging_freq': 9, 'lambda_l1': 3.3900774240997564e-08, 'lambda_l2': 0.0758353773930245, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 338, 'min_data_in_leaf': 49, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.22136470498652955, 'min_gain_to_split': 0.09741400606274757}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:18:24,701] Trial 309 finished with value: 116.58650468832938 and parameters: {'num_leaves': 18, 'learning_rate': 0.10875518923764564, 'feature_fraction': 0.6173020597530718, 'bagging_fraction': 0.9858389197898344, 'bagging_freq': 4, 'lambda_l1': 2.3436174302353733e-06, 'lambda_l2': 0.1473942739407976, 'min_child_samples': 42, 'max_depth': 9, 'max_bin': 296, 'min_data_in_leaf': 20, 'extra_trees': False, 'early_stopping_rounds': 34, 'path_smooth': 0.9841617146173456, 'min_gain_to_split': 0.3189190312391307}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:19:16,537] Trial 310 finished with value: 142.28901516871377 and parameters: {'num_leaves': 26, 'learning_rate': 0.1771257872262494, 'feature_fraction': 0.9200368152550209, 'bagging_fraction': 0.9498469899734391, 'bagging_freq': 10, 'lambda_l1': 3.820730527743754e-07, 'lambda_l2': 0.00523747084926612, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 474, 'min_data_in_leaf': 63, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.9995698858484745, 'min_gain_to_split': 0.0202011210236512}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:20:11,008] Trial 311 finished with value: 123.84404736920753 and parameters: {'num_leaves': 15, 'learning_rate': 0.10077684891862045, 'feature_fraction': 0.7247659416766243, 'bagging_fraction': 0.928872894825056, 'bagging_freq': 7, 'lambda_l1': 6.895626053067727e-08, 'lambda_l2': 0.03184632331393783, 'min_child_samples': 46, 'max_depth': 10, 'max_bin': 378, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.4270061967123772, 'min_gain_to_split': 0.03612749268956789}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:21:04,659] Trial 312 finished with value: 108.81779670533953 and parameters: {'num_leaves': 21, 'learning_rate': 0.12898313994691812, 'feature_fraction': 0.6410909877057033, 'bagging_fraction': 0.9700396961059219, 'bagging_freq': 10, 'lambda_l1': 3.6369432894431344e-05, 'lambda_l2': 2.2737823322081033e-06, 'min_child_samples': 45, 'max_depth': 10, 'max_bin': 359, 'min_data_in_leaf': 26, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.9188299559986302, 'min_gain_to_split': 0.010394289033699869}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:21:50,676] Trial 313 finished with value: 115.08139225736572 and parameters: {'num_leaves': 18, 'learning_rate': 0.11764572647236118, 'feature_fraction': 0.6820382448982748, 'bagging_fraction': 0.913074505096795, 'bagging_freq': 10, 'lambda_l1': 3.95105505856118e-06, 'lambda_l2': 0.011987040097912243, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 352, 'min_data_in_leaf': 43, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.8865799549088259, 'min_gain_to_split': 0.3284512069049638}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:22:46,961] Trial 314 finished with value: 112.19504893694837 and parameters: {'num_leaves': 24, 'learning_rate': 0.09326207134335598, 'feature_fraction': 0.6617794801447698, 'bagging_fraction': 0.961774400532442, 'bagging_freq': 8, 'lambda_l1': 9.385317375083705e-06, 'lambda_l2': 0.017576077552713273, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 368, 'min_data_in_leaf': 22, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.4427839019642307, 'min_gain_to_split': 0.3390307808001666}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:23:33,348] Trial 315 finished with value: 142.00811737209602 and parameters: {'num_leaves': 22, 'learning_rate': 0.10471012557911348, 'feature_fraction': 0.8288573102420498, 'bagging_fraction': 0.8474194495821016, 'bagging_freq': 10, 'lambda_l1': 5.766894175242783e-06, 'lambda_l2': 0.007501574903656854, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 321, 'min_data_in_leaf': 71, 'extra_trees': True, 'early_stopping_rounds': 10, 'path_smooth': 0.9428608909656313, 'min_gain_to_split': 0.027198639070842037}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:24:28,150] Trial 316 finished with value: 125.40244668225293 and parameters: {'num_leaves': 17, 'learning_rate': 0.1134327105991779, 'feature_fraction': 0.6546606928504707, 'bagging_fraction': 0.9823290666353628, 'bagging_freq': 9, 'lambda_l1': 2.5127311331453427e-07, 'lambda_l2': 0.000542954506514457, 'min_child_samples': 44, 'max_depth': 10, 'max_bin': 492, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.4086538327522107, 'min_gain_to_split': 0.1901441732474288}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:25:36,730] Trial 317 finished with value: 139.21435403305966 and parameters: {'num_leaves': 60, 'learning_rate': 0.12456455188626273, 'feature_fraction': 0.6733563515928588, 'bagging_fraction': 0.9990602398306923, 'bagging_freq': 10, 'lambda_l1': 1.0379915035252058e-06, 'lambda_l2': 0.05662526124874695, 'min_child_samples': 47, 'max_depth': 10, 'max_bin': 500, 'min_data_in_leaf': 69, 'extra_trees': True, 'early_stopping_rounds': 23, 'path_smooth': 0.7729162086974937, 'min_gain_to_split': 0.2617969666294106}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:26:34,894] Trial 318 finished with value: 139.13059811703476 and parameters: {'num_leaves': 54, 'learning_rate': 0.15856843881414287, 'feature_fraction': 0.6916316532382507, 'bagging_fraction': 0.8071853115135906, 'bagging_freq': 10, 'lambda_l1': 2.4441216558860676e-05, 'lambda_l2': 0.025158321928685452, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 480, 'min_data_in_leaf': 65, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.46586621504859993, 'min_gain_to_split': 0.3117711795439219}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:27:29,412] Trial 319 finished with value: 138.978008814769 and parameters: {'num_leaves': 19, 'learning_rate': 0.14042324708779885, 'feature_fraction': 0.633582230890882, 'bagging_fraction': 0.8266154703313175, 'bagging_freq': 10, 'lambda_l1': 1.1675121784770363e-05, 'lambda_l2': 0.0407020503246215, 'min_child_samples': 50, 'max_depth': 9, 'max_bin': 466, 'min_data_in_leaf': 60, 'extra_trees': True, 'early_stopping_rounds': 19, 'path_smooth': 0.9642062420199158, 'min_gain_to_split': 0.05380136161000755}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:28:18,775] Trial 320 finished with value: 123.83414907341493 and parameters: {'num_leaves': 21, 'learning_rate': 0.10029204517901522, 'feature_fraction': 0.6467204535261751, 'bagging_fraction': 0.9772067540891995, 'bagging_freq': 9, 'lambda_l1': 2.956861687086033e-06, 'lambda_l2': 0.011151676055788746, 'min_child_samples': 41, 'max_depth': 10, 'max_bin': 343, 'min_data_in_leaf': 40, 'extra_trees': True, 'early_stopping_rounds': 21, 'path_smooth': 0.3865696674741631, 'min_gain_to_split': 0.042766323902255085}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:29:09,591] Trial 321 finished with value: 142.89779034357042 and parameters: {'num_leaves': 23, 'learning_rate': 0.10987951484135121, 'feature_fraction': 0.6647042958980831, 'bagging_fraction': 0.921566745345594, 'bagging_freq': 10, 'lambda_l1': 4.3092280986475936e-07, 'lambda_l2': 0.10221925970798186, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 363, 'min_data_in_leaf': 66, 'extra_trees': True, 'early_stopping_rounds': 30, 'path_smooth': 0.909113829516457, 'min_gain_to_split': 0.2979754599907641}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:29:52,936] Trial 322 finished with value: 121.05829666651425 and parameters: {'num_leaves': 16, 'learning_rate': 0.12139192965271185, 'feature_fraction': 0.6513951947134243, 'bagging_fraction': 0.955339442606089, 'bagging_freq': 10, 'lambda_l1': 0.0001523729227594988, 'lambda_l2': 0.004377505410288135, 'min_child_samples': 45, 'max_depth': 10, 'max_bin': 332, 'min_data_in_leaf': 46, 'extra_trees': True, 'early_stopping_rounds': 38, 'path_smooth': 0.43469505637911715, 'min_gain_to_split': 0.014599782444011689}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:30:46,666] Trial 323 finished with value: 118.0863404496974 and parameters: {'num_leaves': 25, 'learning_rate': 0.08512264750263886, 'feature_fraction': 0.6785713003875911, 'bagging_fraction': 0.9409759891054724, 'bagging_freq': 9, 'lambda_l1': 2.0955960586693155e-06, 'lambda_l2': 0.015817651385728368, 'min_child_samples': 34, 'max_depth': 10, 'max_bin': 384, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.41468169065209304, 'min_gain_to_split': 0.13261646137894154}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:31:46,297] Trial 324 finished with value: 119.26794265555097 and parameters: {'num_leaves': 20, 'learning_rate': 0.0980238044775969, 'feature_fraction': 0.641504296597328, 'bagging_fraction': 0.9714554824260757, 'bagging_freq': 10, 'lambda_l1': 1.6706918703361614e-05, 'lambda_l2': 0.022988724810256846, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 474, 'min_data_in_leaf': 33, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.9336520627305172, 'min_gain_to_split': 0.0349031814375218}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:32:32,552] Trial 325 finished with value: 115.46727233815008 and parameters: {'num_leaves': 18, 'learning_rate': 0.13310867737095425, 'feature_fraction': 0.6274467179652483, 'bagging_fraction': 0.947162003880054, 'bagging_freq': 8, 'lambda_l1': 4.46381314995203e-06, 'lambda_l2': 3.849329308109193e-05, 'min_child_samples': 46, 'max_depth': 10, 'max_bin': 486, 'min_data_in_leaf': 31, 'extra_trees': True, 'early_stopping_rounds': 31, 'path_smooth': 0.47879590848635756, 'min_gain_to_split': 0.2499615448308711}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:33:25,048] Trial 326 finished with value: 140.60404756339022 and parameters: {'num_leaves': 29, 'learning_rate': 0.19939646398538674, 'feature_fraction': 0.660119382438841, 'bagging_fraction': 0.9336220657311682, 'bagging_freq': 10, 'lambda_l1': 6.299108955971954e-07, 'lambda_l2': 0.22434525578886658, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 377, 'min_data_in_leaf': 68, 'extra_trees': True, 'early_stopping_rounds': 49, 'path_smooth': 0.981248608020037, 'min_gain_to_split': 0.07700199819488304}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:34:08,594] Trial 327 finished with value: 127.72646608537734 and parameters: {'num_leaves': 23, 'learning_rate': 0.15032492639425638, 'feature_fraction': 0.6666087162668437, 'bagging_fraction': 0.962172423489719, 'bagging_freq': 10, 'lambda_l1': 5.507118424476615e-05, 'lambda_l2': 0.06298531715083217, 'min_child_samples': 47, 'max_depth': 10, 'max_bin': 312, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 32, 'path_smooth': 0.9999448929746778, 'min_gain_to_split': 0.1568286824413658}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:35:07,616] Trial 328 finished with value: 136.81028215850964 and parameters: {'num_leaves': 15, 'learning_rate': 0.07017599632374691, 'feature_fraction': 0.6361607052289975, 'bagging_fraction': 0.951095113800503, 'bagging_freq': 10, 'lambda_l1': 1.1188562122790687e-06, 'lambda_l2': 0.007206798240414265, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 352, 'min_data_in_leaf': 62, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.9654768866455544, 'min_gain_to_split': 0.005979065089237354}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:36:08,547] Trial 329 finished with value: 142.44990056659944 and parameters: {'num_leaves': 39, 'learning_rate': 0.11220008674680505, 'feature_fraction': 0.7168353033755446, 'bagging_fraction': 0.9905933504250948, 'bagging_freq': 9, 'lambda_l1': 7.651423622921659e-06, 'lambda_l2': 0.03454783281750848, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 450, 'min_data_in_leaf': 64, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.4496911171798596, 'min_gain_to_split': 0.05957585534245795}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:40:21,543] Trial 330 finished with value: 122.87320720267807 and parameters: {'num_leaves': 26, 'learning_rate': 0.033360979339509586, 'feature_fraction': 0.6535975934259342, 'bagging_fraction': 0.9660917664472085, 'bagging_freq': 10, 'lambda_l1': 0.00043400582237665603, 'lambda_l2': 0.010471317857581037, 'min_child_samples': 44, 'max_depth': 10, 'max_bin': 459, 'min_data_in_leaf': 73, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.8763478724359772, 'min_gain_to_split': 0.021375316316440136}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:41:26,560] Trial 331 finished with value: 132.03157072707444 and parameters: {'num_leaves': 21, 'learning_rate': 0.10512335861091907, 'feature_fraction': 0.6705384769370768, 'bagging_fraction': 0.9816712795618617, 'bagging_freq': 10, 'lambda_l1': 1.8513450332088363e-07, 'lambda_l2': 3.0964428272188566e-07, 'min_child_samples': 47, 'max_depth': 10, 'max_bin': 369, 'min_data_in_leaf': 53, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.3693896623627819, 'min_gain_to_split': 0.17685313624698334}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:42:18,254] Trial 332 finished with value: 119.33113529981026 and parameters: {'num_leaves': 19, 'learning_rate': 0.09300814076597361, 'feature_fraction': 0.6210852730236678, 'bagging_fraction': 0.9151006186287105, 'bagging_freq': 10, 'lambda_l1': 1.2890238262811108e-05, 'lambda_l2': 0.017739167175481504, 'min_child_samples': 31, 'max_depth': 6, 'max_bin': 487, 'min_data_in_leaf': 40, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.9465081522717034, 'min_gain_to_split': 0.11807512315810839}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:43:10,144] Trial 333 finished with value: 140.79910365081327 and parameters: {'num_leaves': 17, 'learning_rate': 0.11793261263862735, 'feature_fraction': 0.6433224983687339, 'bagging_fraction': 0.9737517081040861, 'bagging_freq': 6, 'lambda_l1': 0.0070665783362444555, 'lambda_l2': 0.041760355754359275, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 341, 'min_data_in_leaf': 68, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.5002439268891541, 'min_gain_to_split': 0.3071300724446305}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:43:56,650] Trial 334 finished with value: 131.36036156469018 and parameters: {'num_leaves': 22, 'learning_rate': 0.16922934305161916, 'feature_fraction': 0.6574814690628316, 'bagging_fraction': 0.9263065757362717, 'bagging_freq': 10, 'lambda_l1': 1.7639661333055011e-06, 'lambda_l2': 5.837883437145101e-08, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 480, 'min_data_in_leaf': 56, 'extra_trees': True, 'early_stopping_rounds': 34, 'path_smooth': 0.39600170993344364, 'min_gain_to_split': 0.2683249193588856}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:44:34,110] Trial 335 finished with value: 111.54955625015093 and parameters: {'num_leaves': 24, 'learning_rate': 0.12952587677602215, 'feature_fraction': 0.6803053566706599, 'bagging_fraction': 0.9575041740319881, 'bagging_freq': 9, 'lambda_l1': 4.038430872766024e-05, 'lambda_l2': 0.09288001903594441, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 238, 'min_data_in_leaf': 24, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.9226637347492819, 'min_gain_to_split': 0.3197181666268303}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:45:29,823] Trial 336 finished with value: 134.9616687695879 and parameters: {'num_leaves': 20, 'learning_rate': 0.14027572163910415, 'feature_fraction': 0.68842605338087, 'bagging_fraction': 0.9657039065712013, 'bagging_freq': 10, 'lambda_l1': 2.041463597919708e-05, 'lambda_l2': 0.024452816450332083, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 329, 'min_data_in_leaf': 66, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.4327336318406255, 'min_gain_to_split': 0.02584144332506762}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:46:17,080] Trial 337 finished with value: 121.16175168844431 and parameters: {'num_leaves': 17, 'learning_rate': 0.10311679061485576, 'feature_fraction': 0.6473800707019358, 'bagging_fraction': 0.9435654625748509, 'bagging_freq': 10, 'lambda_l1': 5.918059434478591e-06, 'lambda_l2': 0.012125862498439107, 'min_child_samples': 46, 'max_depth': 10, 'max_bin': 360, 'min_data_in_leaf': 42, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.9585160591724377, 'min_gain_to_split': 0.04267654236861428}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:47:09,308] Trial 338 finished with value: 146.0172038067896 and parameters: {'num_leaves': 27, 'learning_rate': 0.12164504400111155, 'feature_fraction': 0.6125616105835449, 'bagging_fraction': 0.9088529184890273, 'bagging_freq': 9, 'lambda_l1': 3.139106022916136e-06, 'lambda_l2': 0.006780413308698067, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 471, 'min_data_in_leaf': 71, 'extra_trees': True, 'early_stopping_rounds': 33, 'path_smooth': 0.46725774921709873, 'min_gain_to_split': 0.030246969811293007}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:48:03,480] Trial 339 finished with value: 118.12330406357614 and parameters: {'num_leaves': 19, 'learning_rate': 0.0895357873625265, 'feature_fraction': 0.6319422911627616, 'bagging_fraction': 0.954143198804293, 'bagging_freq': 10, 'lambda_l1': 4.835290558409798e-08, 'lambda_l2': 0.0027476542849503697, 'min_child_samples': 45, 'max_depth': 10, 'max_bin': 493, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 35, 'path_smooth': 0.4087685497907419, 'min_gain_to_split': 0.28514208243649125}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:48:55,733] Trial 340 finished with value: 123.98397981589142 and parameters: {'num_leaves': 23, 'learning_rate': 0.07831948197222409, 'feature_fraction': 0.6616001619884267, 'bagging_fraction': 0.7806437861377494, 'bagging_freq': 10, 'lambda_l1': 1.7094394559004827e-08, 'lambda_l2': 0.16401904603642606, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 349, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9016408647475044, 'min_gain_to_split': 0.012104432656352476}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:49:42,588] Trial 341 finished with value: 143.3066235138944 and parameters: {'num_leaves': 16, 'learning_rate': 0.10978997306282161, 'feature_fraction': 0.6753632206813698, 'bagging_fraction': 0.8613521702102962, 'bagging_freq': 10, 'lambda_l1': 8.372466327726322e-07, 'lambda_l2': 0.0535467645946501, 'min_child_samples': 42, 'max_depth': 10, 'max_bin': 393, 'min_data_in_leaf': 64, 'extra_trees': True, 'early_stopping_rounds': 30, 'path_smooth': 0.5372297855662089, 'min_gain_to_split': 0.33185572797980306}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:50:25,238] Trial 342 finished with value: 111.22239120954399 and parameters: {'num_leaves': 21, 'learning_rate': 0.15384510267527063, 'feature_fraction': 0.8829965170841408, 'bagging_fraction': 0.9785509627915732, 'bagging_freq': 8, 'lambda_l1': 9.527282180732803e-08, 'lambda_l2': 0.017265620534228966, 'min_child_samples': 47, 'max_depth': 10, 'max_bin': 372, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.9408555017231077, 'min_gain_to_split': 0.29823609047199656}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:51:26,313] Trial 343 finished with value: 142.32512088413836 and parameters: {'num_leaves': 25, 'learning_rate': 0.11563449182826009, 'feature_fraction': 0.6521544631321787, 'bagging_fraction': 0.9605829568979208, 'bagging_freq': 10, 'lambda_l1': 3.8472217224709763e-07, 'lambda_l2': 0.030305212447431024, 'min_child_samples': 44, 'max_depth': 10, 'max_bin': 478, 'min_data_in_leaf': 69, 'extra_trees': True, 'early_stopping_rounds': 22, 'path_smooth': 0.9811610965562535, 'min_gain_to_split': 0.05073006200225761}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:52:13,309] Trial 344 finished with value: 123.5224035390219 and parameters: {'num_leaves': 18, 'learning_rate': 0.09561607116188643, 'feature_fraction': 0.6400008624711435, 'bagging_fraction': 0.9704662450261271, 'bagging_freq': 7, 'lambda_l1': 1.021121334814375e-08, 'lambda_l2': 0.00942176840563957, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 500, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.45208917220807154, 'min_gain_to_split': 0.040838305481441024}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:53:00,940] Trial 345 finished with value: 136.7266031847406 and parameters: {'num_leaves': 100, 'learning_rate': 0.1845846245492111, 'feature_fraction': 0.6678881782966745, 'bagging_fraction': 0.8391265811554568, 'bagging_freq': 9, 'lambda_l1': 1.4849989769944409e-06, 'lambda_l2': 0.07180128711367002, 'min_child_samples': 49, 'max_depth': 9, 'max_bin': 463, 'min_data_in_leaf': 67, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.41939209537847066, 'min_gain_to_split': 0.31221817767873683}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:53:46,740] Trial 346 finished with value: 114.91239256072508 and parameters: {'num_leaves': 22, 'learning_rate': 0.13493034167506407, 'feature_fraction': 0.6268540667841626, 'bagging_fraction': 0.9194357621529409, 'bagging_freq': 10, 'lambda_l1': 9.496490250104678e-06, 'lambda_l2': 0.00472999293566344, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 489, 'min_data_in_leaf': 32, 'extra_trees': True, 'early_stopping_rounds': 23, 'path_smooth': 0.37707487179288446, 'min_gain_to_split': 0.02114892468038554}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:54:38,692] Trial 347 finished with value: 138.4319948762646 and parameters: {'num_leaves': 20, 'learning_rate': 0.12511648786650778, 'feature_fraction': 0.6466968765416946, 'bagging_fraction': 0.8731159837477847, 'bagging_freq': 10, 'lambda_l1': 2.49714451041974e-05, 'lambda_l2': 0.3150956252842495, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 365, 'min_data_in_leaf': 59, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.9581157563151659, 'min_gain_to_split': 0.0036053146385183338}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:55:26,289] Trial 348 finished with value: 129.16405134326115 and parameters: {'num_leaves': 18, 'learning_rate': 0.1048958611050809, 'feature_fraction': 0.6586328239215724, 'bagging_fraction': 0.9391233227726918, 'bagging_freq': 10, 'lambda_l1': 4.347341804175069e-06, 'lambda_l2': 0.014439126876914642, 'min_child_samples': 44, 'max_depth': 10, 'max_bin': 379, 'min_data_in_leaf': 50, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.9237948325601387, 'min_gain_to_split': 0.06482328826443098}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:56:37,169] Trial 349 finished with value: 104.34740126879908 and parameters: {'num_leaves': 15, 'learning_rate': 0.14260167562529713, 'feature_fraction': 0.9537699068820227, 'bagging_fraction': 0.9456413489490647, 'bagging_freq': 9, 'lambda_l1': 2.082932780076922e-07, 'lambda_l2': 0.03744332301390541, 'min_child_samples': 45, 'max_depth': 10, 'max_bin': 355, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.9761206271442902, 'min_gain_to_split': 0.02845673680655529}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:57:29,223] Trial 350 finished with value: 115.21644839580217 and parameters: {'num_leaves': 24, 'learning_rate': 0.11311233333013244, 'feature_fraction': 0.6713243704784349, 'bagging_fraction': 0.9509397690207091, 'bagging_freq': 10, 'lambda_l1': 7.068241117229371e-07, 'lambda_l2': 0.12309303000718243, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 481, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.4369902530327881, 'min_gain_to_split': 0.327137269902901}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:58:16,910] Trial 351 finished with value: 119.81892311216136 and parameters: {'num_leaves': 20, 'learning_rate': 0.0997866132691844, 'feature_fraction': 0.6360954836516858, 'bagging_fraction': 0.984951904358865, 'bagging_freq': 8, 'lambda_l1': 2.758170541790049e-06, 'lambda_l2': 0.021325729400585587, 'min_child_samples': 46, 'max_depth': 10, 'max_bin': 405, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.33491486974059864, 'min_gain_to_split': 0.036508628140908446}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 20:59:06,279] Trial 352 finished with value: 133.22966485184125 and parameters: {'num_leaves': 22, 'learning_rate': 0.16135231179061993, 'feature_fraction': 0.8571560746802904, 'bagging_fraction': 0.9323224625235813, 'bagging_freq': 10, 'lambda_l1': 7.090247065522995e-05, 'lambda_l2': 0.00875717367546943, 'min_child_samples': 47, 'max_depth': 10, 'max_bin': 337, 'min_data_in_leaf': 66, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.7021022799603432, 'min_gain_to_split': 0.014142042099637988}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:00:08,266] Trial 353 finished with value: 136.22358565096619 and parameters: {'num_leaves': 17, 'learning_rate': 0.08644716669594882, 'feature_fraction': 0.6866396298529768, 'bagging_fraction': 0.9590110142391568, 'bagging_freq': 10, 'lambda_l1': 1.3295759245328995e-05, 'lambda_l2': 6.240008247378618e-07, 'min_child_samples': 28, 'max_depth': 10, 'max_bin': 471, 'min_data_in_leaf': 70, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.47703415025556445, 'min_gain_to_split': 0.2785310660707449}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:00:52,172] Trial 354 finished with value: 115.93808654678648 and parameters: {'num_leaves': 26, 'learning_rate': 0.1208863935767639, 'feature_fraction': 0.7044044769496733, 'bagging_fraction': 0.8520401798499427, 'bagging_freq': 9, 'lambda_l1': 7.658347030644376e-06, 'lambda_l2': 0.01387531918679912, 'min_child_samples': 49, 'max_depth': 7, 'max_bin': 318, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 30, 'path_smooth': 0.3949460216011003, 'min_gain_to_split': 0.34689189055260744}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:01:57,407] Trial 355 finished with value: 131.36145772164514 and parameters: {'num_leaves': 28, 'learning_rate': 0.1043152324759878, 'feature_fraction': 0.6520604178550933, 'bagging_fraction': 0.9714059709601555, 'bagging_freq': 10, 'lambda_l1': 3.1540276146260364e-07, 'lambda_l2': 0.027411666272085838, 'min_child_samples': 41, 'max_depth': 10, 'max_bin': 493, 'min_data_in_leaf': 62, 'extra_trees': True, 'early_stopping_rounds': 32, 'path_smooth': 0.9351954238114201, 'min_gain_to_split': 0.3174410030733931}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:02:50,880] Trial 356 finished with value: 118.10337953830052 and parameters: {'num_leaves': 19, 'learning_rate': 0.12948758433858568, 'feature_fraction': 0.7560594643418946, 'bagging_fraction': 0.9940111118448784, 'bagging_freq': 10, 'lambda_l1': 3.186085242880684e-05, 'lambda_l2': 4.5464155449563615, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 383, 'min_data_in_leaf': 41, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.891016349327664, 'min_gain_to_split': 0.08631982890035911}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:03:49,813] Trial 357 finished with value: 137.6224750477276 and parameters: {'num_leaves': 24, 'learning_rate': 0.11073658941510847, 'feature_fraction': 0.6640029362651251, 'bagging_fraction': 0.9779493071524608, 'bagging_freq': 10, 'lambda_l1': 4.370564012954023e-06, 'lambda_l2': 0.04503463951631297, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 347, 'min_data_in_leaf': 57, 'extra_trees': True, 'early_stopping_rounds': 36, 'path_smooth': 0.41796229817647734, 'min_gain_to_split': 0.29232555027813545}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:04:58,789] Trial 358 finished with value: 138.3655156270084 and parameters: {'num_leaves': 21, 'learning_rate': 0.09460706468865386, 'feature_fraction': 0.8191426190665431, 'bagging_fraction': 0.9653291096180613, 'bagging_freq': 9, 'lambda_l1': 4.996486508432443e-07, 'lambda_l2': 0.006365505193302215, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 487, 'min_data_in_leaf': 64, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.3594688274167544, 'min_gain_to_split': 0.12379106980236827}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:05:52,916] Trial 359 finished with value: 140.0991508026438 and parameters: {'num_leaves': 16, 'learning_rate': 0.14246638721282018, 'feature_fraction': 0.6421668787060915, 'bagging_fraction': 0.954117253058345, 'bagging_freq': 10, 'lambda_l1': 0.00020216197937607914, 'lambda_l2': 0.08398539900760608, 'min_child_samples': 40, 'max_depth': 9, 'max_bin': 327, 'min_data_in_leaf': 67, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.9984955156281241, 'min_gain_to_split': 0.14426936280255376}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:07:12,737] Trial 360 finished with value: 128.3808636694019 and parameters: {'num_leaves': 19, 'learning_rate': 0.02586704229658569, 'feature_fraction': 0.6736184690899002, 'bagging_fraction': 0.9464737449448996, 'bagging_freq': 10, 'lambda_l1': 0.00011506977999827039, 'lambda_l2': 0.0035114444959867337, 'min_child_samples': 47, 'max_depth': 10, 'max_bin': 361, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 33, 'path_smooth': 0.9569684957117052, 'min_gain_to_split': 0.020234491921842304}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:08:02,344] Trial 361 finished with value: 115.38804305451254 and parameters: {'num_leaves': 23, 'learning_rate': 0.11733642248007708, 'feature_fraction': 0.6559375940307384, 'bagging_fraction': 0.9062316130672585, 'bagging_freq': 9, 'lambda_l1': 1.2487044577276212e-06, 'lambda_l2': 0.021241394950401542, 'min_child_samples': 42, 'max_depth': 10, 'max_bin': 371, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.912097428050103, 'min_gain_to_split': 0.04458307792879629}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:08:53,509] Trial 362 finished with value: 141.31636702782384 and parameters: {'num_leaves': 18, 'learning_rate': 0.15039489406705003, 'feature_fraction': 0.6229865631458985, 'bagging_fraction': 0.9253682033345817, 'bagging_freq': 8, 'lambda_l1': 1.6784728283088544e-05, 'lambda_l2': 0.011606464037216057, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 476, 'min_data_in_leaf': 69, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.4509154233108544, 'min_gain_to_split': 0.256407910281976}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:09:46,369] Trial 363 finished with value: 136.96390556193637 and parameters: {'num_leaves': 21, 'learning_rate': 0.1721377094905191, 'feature_fraction': 0.6491468166865358, 'bagging_fraction': 0.9381230894748588, 'bagging_freq': 10, 'lambda_l1': 2.1570410024065154e-06, 'lambda_l2': 0.06104726729382409, 'min_child_samples': 46, 'max_depth': 10, 'max_bin': 304, 'min_data_in_leaf': 63, 'extra_trees': True, 'early_stopping_rounds': 31, 'path_smooth': 0.8188456042814795, 'min_gain_to_split': 0.0009020341290885761}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:11:01,965] Trial 364 finished with value: 138.67236406026834 and parameters: {'num_leaves': 25, 'learning_rate': 0.0471171497102757, 'feature_fraction': 0.6806659301176629, 'bagging_fraction': 0.9748026197412668, 'bagging_freq': 10, 'lambda_l1': 7.28449668715181e-06, 'lambda_l2': 0.03252112373815478, 'min_child_samples': 45, 'max_depth': 10, 'max_bin': 467, 'min_data_in_leaf': 65, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.9425951936133075, 'min_gain_to_split': 0.056584549541876805}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:11:50,520] Trial 365 finished with value: 132.31504776959258 and parameters: {'num_leaves': 17, 'learning_rate': 0.09757208717062854, 'feature_fraction': 0.6347056651068793, 'bagging_fraction': 0.9171356308796001, 'bagging_freq': 10, 'lambda_l1': 1.2713315909332797e-07, 'lambda_l2': 0.018091425812868704, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 342, 'min_data_in_leaf': 54, 'extra_trees': True, 'early_stopping_rounds': 34, 'path_smooth': 0.9752155832915106, 'min_gain_to_split': 0.3063287165233474}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:12:38,043] Trial 366 finished with value: 110.2724310873618 and parameters: {'num_leaves': 15, 'learning_rate': 0.12972444052012827, 'feature_fraction': 0.6953470108423949, 'bagging_fraction': 0.9654452929157683, 'bagging_freq': 10, 'lambda_l1': 1.1350291769460471e-05, 'lambda_l2': 0.008816404785571148, 'min_child_samples': 50, 'max_depth': 9, 'max_bin': 500, 'min_data_in_leaf': 30, 'extra_trees': True, 'early_stopping_rounds': 41, 'path_smooth': 0.39653881507604766, 'min_gain_to_split': 0.02850541730032486}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:13:40,502] Trial 367 finished with value: 111.86649598013582 and parameters: {'num_leaves': 30, 'learning_rate': 0.10792553829886904, 'feature_fraction': 0.6613930276431434, 'bagging_fraction': 0.9875254475871429, 'bagging_freq': 1, 'lambda_l1': 4.098511902688393e-05, 'lambda_l2': 0.042457198528047434, 'min_child_samples': 49, 'max_depth': 5, 'max_bin': 391, 'min_data_in_leaf': 26, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.4305780114060786, 'min_gain_to_split': 0.03535294655270717}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:14:29,815] Trial 368 finished with value: 125.73140888952037 and parameters: {'num_leaves': 22, 'learning_rate': 0.12081767519536848, 'feature_fraction': 0.6689128102603304, 'bagging_fraction': 0.703715772413345, 'bagging_freq': 10, 'lambda_l1': 8.992428957247304e-07, 'lambda_l2': 0.005415280939916971, 'min_child_samples': 44, 'max_depth': 10, 'max_bin': 484, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 20, 'path_smooth': 0.4676185728147044, 'min_gain_to_split': 0.2705037415487871}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:15:27,621] Trial 369 finished with value: 143.12275946876403 and parameters: {'num_leaves': 20, 'learning_rate': 0.0889068253173527, 'feature_fraction': 0.6431026998862969, 'bagging_fraction': 0.9586385520279771, 'bagging_freq': 7, 'lambda_l1': 4.810469595821533e-06, 'lambda_l2': 0.15443578424017887, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 355, 'min_data_in_leaf': 68, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.4909391135757924, 'min_gain_to_split': 0.011700664178827742}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:16:30,253] Trial 370 finished with value: 133.53422295702396 and parameters: {'num_leaves': 27, 'learning_rate': 0.10189141270523597, 'feature_fraction': 0.654195980730607, 'bagging_fraction': 0.9487111185457937, 'bagging_freq': 9, 'lambda_l1': 2.494379605590902e-06, 'lambda_l2': 0.013285461034798638, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 453, 'min_data_in_leaf': 72, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.5134089098266675, 'min_gain_to_split': 0.3386818427547167}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:17:04,073] Trial 371 finished with value: 116.55252992162609 and parameters: {'num_leaves': 23, 'learning_rate': 0.13780322991012087, 'feature_fraction': 0.6294368132873215, 'bagging_fraction': 0.9812275845237214, 'bagging_freq': 10, 'lambda_l1': 2.1657102722655166e-05, 'lambda_l2': 0.0001992957530890777, 'min_child_samples': 47, 'max_depth': 3, 'max_bin': 265, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9193224387368644, 'min_gain_to_split': 0.045857245252821005}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:17:43,844] Trial 372 finished with value: 110.46341789339215 and parameters: {'num_leaves': 19, 'learning_rate': 0.1601988979790175, 'feature_fraction': 0.6639550516799659, 'bagging_fraction': 0.9715019694412852, 'bagging_freq': 10, 'lambda_l1': 6.193079933893284e-06, 'lambda_l2': 0.02533988160818767, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 374, 'min_data_in_leaf': 40, 'extra_trees': True, 'early_stopping_rounds': 23, 'path_smooth': 0.8616618246019998, 'min_gain_to_split': 0.298565977564519}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:18:32,252] Trial 373 finished with value: 125.09701656744679 and parameters: {'num_leaves': 17, 'learning_rate': 0.11378557102042634, 'feature_fraction': 0.6183622601916007, 'bagging_fraction': 0.8682686232891063, 'bagging_freq': 10, 'lambda_l1': 0.0006513328766135587, 'lambda_l2': 0.10090712686444911, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 476, 'min_data_in_leaf': 43, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.9502567407865457, 'min_gain_to_split': 0.022374583137422115}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:19:21,734] Trial 374 finished with value: 124.22794310466205 and parameters: {'num_leaves': 25, 'learning_rate': 0.10643044536931234, 'feature_fraction': 0.7352062060358323, 'bagging_fraction': 0.930756460416803, 'bagging_freq': 9, 'lambda_l1': 1.5441416389761403e-06, 'lambda_l2': 0.06391258889859162, 'min_child_samples': 45, 'max_depth': 10, 'max_bin': 363, 'min_data_in_leaf': 47, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.44214776918492654, 'min_gain_to_split': 0.32486135667637284}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:20:06,174] Trial 375 finished with value: 109.29494454312108 and parameters: {'num_leaves': 37, 'learning_rate': 0.21537237522640293, 'feature_fraction': 0.6451903289148601, 'bagging_fraction': 0.95399662900969, 'bagging_freq': 5, 'lambda_l1': 0.02988044667392599, 'lambda_l2': 0.01823784476068232, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 490, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.31202585860627663, 'min_gain_to_split': 0.313560812167665}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:20:53,524] Trial 376 finished with value: 136.07299032507328 and parameters: {'num_leaves': 21, 'learning_rate': 0.12581096854462498, 'feature_fraction': 0.6836128241239173, 'bagging_fraction': 0.9622134214829815, 'bagging_freq': 10, 'lambda_l1': 2.4111081167502988e-08, 'lambda_l2': 0.011730607867478194, 'min_child_samples': 46, 'max_depth': 10, 'max_bin': 295, 'min_data_in_leaf': 66, 'extra_trees': True, 'early_stopping_rounds': 22, 'path_smooth': 0.41179493822919805, 'min_gain_to_split': 0.09990708846895426}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:21:44,364] Trial 377 finished with value: 123.1852982506449 and parameters: {'num_leaves': 19, 'learning_rate': 0.0955996746762831, 'feature_fraction': 0.6572164515295058, 'bagging_fraction': 0.9130689293679283, 'bagging_freq': 10, 'lambda_l1': 0.00028469213306925187, 'lambda_l2': 0.03371903331610684, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 480, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 32, 'path_smooth': 0.37889555752054616, 'min_gain_to_split': 0.0335137156422035}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:22:31,516] Trial 378 finished with value: 113.1026570887866 and parameters: {'num_leaves': 23, 'learning_rate': 0.11613919577367063, 'feature_fraction': 0.67309922771493, 'bagging_fraction': 0.9421345469010726, 'bagging_freq': 8, 'lambda_l1': 5.860520097461905e-07, 'lambda_l2': 0.008053855640029865, 'min_child_samples': 44, 'max_depth': 10, 'max_bin': 494, 'min_data_in_leaf': 32, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.9084032869659555, 'min_gain_to_split': 0.2451587114145281}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:23:13,451] Trial 379 finished with value: 139.4572666796772 and parameters: {'num_leaves': 15, 'learning_rate': 0.146216948954168, 'feature_fraction': 0.636883925185305, 'bagging_fraction': 0.9681936665628957, 'bagging_freq': 10, 'lambda_l1': 3.2904252600639315e-06, 'lambda_l2': 0.05010596447180552, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 331, 'min_data_in_leaf': 61, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9780844844193112, 'min_gain_to_split': 0.012112111983105828}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:24:11,093] Trial 380 finished with value: 138.82761802361296 and parameters: {'num_leaves': 17, 'learning_rate': 0.0819067609828097, 'feature_fraction': 0.6504433839781963, 'bagging_fraction': 0.9576172496605135, 'bagging_freq': 10, 'lambda_l1': 4.183056389209669e-08, 'lambda_l2': 0.02191259253119399, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 460, 'min_data_in_leaf': 66, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.9655260419468812, 'min_gain_to_split': 0.07405858507551616}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:24:57,109] Trial 381 finished with value: 125.01186240178372 and parameters: {'num_leaves': 21, 'learning_rate': 0.1010091102479253, 'feature_fraction': 0.6648742274429467, 'bagging_fraction': 0.9751097199527775, 'bagging_freq': 9, 'lambda_l1': 2.7363012589666037e-07, 'lambda_l2': 0.004628337861435223, 'min_child_samples': 47, 'max_depth': 10, 'max_bin': 382, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.8807687425018346, 'min_gain_to_split': 0.28588288917814964}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:25:39,413] Trial 382 finished with value: 147.5319990100695 and parameters: {'num_leaves': 18, 'learning_rate': 0.1346049816492004, 'feature_fraction': 0.676666307256219, 'bagging_fraction': 0.8568391488281846, 'bagging_freq': 10, 'lambda_l1': 1.1227750259091904e-05, 'lambda_l2': 0.014147548983195155, 'min_child_samples': 46, 'max_depth': 10, 'max_bin': 346, 'min_data_in_leaf': 69, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.9280205127224905, 'min_gain_to_split': 0.050521684473912476}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:26:37,283] Trial 383 finished with value: 131.45588221099496 and parameters: {'num_leaves': 26, 'learning_rate': 0.09084674867318024, 'feature_fraction': 0.6107267053164754, 'bagging_fraction': 0.9232840299663303, 'bagging_freq': 10, 'lambda_l1': 5.815638107854904e-05, 'lambda_l2': 0.02839724531140771, 'min_child_samples': 42, 'max_depth': 10, 'max_bin': 368, 'min_data_in_leaf': 51, 'extra_trees': True, 'early_stopping_rounds': 30, 'path_smooth': 0.4595012729389991, 'min_gain_to_split': 0.061947734698450274}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:27:35,871] Trial 384 finished with value: 147.07527419371246 and parameters: {'num_leaves': 23, 'learning_rate': 0.11019938345894056, 'feature_fraction': 0.6285623938598166, 'bagging_fraction': 0.8936747025880247, 'bagging_freq': 9, 'lambda_l1': 2.7640760615999485e-05, 'lambda_l2': 0.007252249073115059, 'min_child_samples': 49, 'max_depth': 8, 'max_bin': 485, 'min_data_in_leaf': 67, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.4188293323655347, 'min_gain_to_split': 0.021360997710396075}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:28:23,917] Trial 385 finished with value: 138.64089840113303 and parameters: {'num_leaves': 20, 'learning_rate': 0.12410688744127243, 'feature_fraction': 0.640862997545865, 'bagging_fraction': 0.8471086963091823, 'bagging_freq': 10, 'lambda_l1': 1.414088710355811e-05, 'lambda_l2': 0.09069121383407623, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 355, 'min_data_in_leaf': 64, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.9851772952599573, 'min_gain_to_split': 0.2617859246412967}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:29:03,665] Trial 386 finished with value: 125.12419248065962 and parameters: {'num_leaves': 19, 'learning_rate': 0.1084730824698038, 'feature_fraction': 0.6891745547514878, 'bagging_fraction': 0.949048775515784, 'bagging_freq': 10, 'lambda_l1': 1.7015196554279873e-06, 'lambda_l2': 0.26584214339337503, 'min_child_samples': 36, 'max_depth': 10, 'max_bin': 226, 'min_data_in_leaf': 41, 'extra_trees': True, 'early_stopping_rounds': 33, 'path_smooth': 0.39849390040931026, 'min_gain_to_split': 0.04057242644387944}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:30:08,784] Trial 387 finished with value: 112.46782808822582 and parameters: {'num_leaves': 22, 'learning_rate': 0.17882622630853973, 'feature_fraction': 0.6600176590617726, 'bagging_fraction': 0.984119339887007, 'bagging_freq': 10, 'lambda_l1': 8.274019120946497e-06, 'lambda_l2': 0.018638376934672476, 'min_child_samples': 45, 'max_depth': 10, 'max_bin': 440, 'min_data_in_leaf': 23, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.7496094897216667, 'min_gain_to_split': 0.031002674070025583}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:30:53,820] Trial 388 finished with value: 131.66047489586902 and parameters: {'num_leaves': 16, 'learning_rate': 0.1525893489656338, 'feature_fraction': 0.6482498481034096, 'bagging_fraction': 0.966563733230021, 'bagging_freq': 10, 'lambda_l1': 9.105162082375996e-07, 'lambda_l2': 0.00118123716712763, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 469, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.9449600661027929, 'min_gain_to_split': 0.01016001727434825}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:31:38,290] Trial 389 finished with value: 115.20985170679437 and parameters: {'num_leaves': 25, 'learning_rate': 0.11807707116463133, 'feature_fraction': 0.6695084270193902, 'bagging_fraction': 0.9368956972603847, 'bagging_freq': 3, 'lambda_l1': 3.96045129313664e-06, 'lambda_l2': 0.010303094271378474, 'min_child_samples': 47, 'max_depth': 10, 'max_bin': 339, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.11572202785902663, 'min_gain_to_split': 0.38167945984621837}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:32:19,112] Trial 390 finished with value: 125.90583357999085 and parameters: {'num_leaves': 21, 'learning_rate': 0.1333860720753575, 'feature_fraction': 0.6526892099156053, 'bagging_fraction': 0.9910319421810734, 'bagging_freq': 8, 'lambda_l1': 8.248913134364492e-08, 'lambda_l2': 0.03869158232774917, 'min_child_samples': 44, 'max_depth': 10, 'max_bin': 320, 'min_data_in_leaf': 45, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.3575108809916721, 'min_gain_to_split': 0.41457130876899684}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:33:16,161] Trial 391 finished with value: 139.73006310977934 and parameters: {'num_leaves': 18, 'learning_rate': 0.09945708098892858, 'feature_fraction': 0.6316103016620173, 'bagging_fraction': 0.9778825729309063, 'bagging_freq': 9, 'lambda_l1': 1.963791191291047e-05, 'lambda_l2': 0.05453149877372512, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 493, 'min_data_in_leaf': 71, 'extra_trees': True, 'early_stopping_rounds': 35, 'path_smooth': 0.4365104680971348, 'min_gain_to_split': 0.32160112316182515}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:33:56,800] Trial 392 finished with value: 117.63776247904238 and parameters: {'num_leaves': 28, 'learning_rate': 0.16770142788406012, 'feature_fraction': 0.6804124574954126, 'bagging_fraction': 0.908802571366054, 'bagging_freq': 10, 'lambda_l1': 8.50118985849969, 'lambda_l2': 0.002112404875000845, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 376, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 31, 'path_smooth': 0.4872678196272217, 'min_gain_to_split': 0.31037351376269207}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:34:48,326] Trial 393 finished with value: 139.09496924558144 and parameters: {'num_leaves': 24, 'learning_rate': 0.11206240153513665, 'feature_fraction': 0.7699679603117173, 'bagging_fraction': 0.9527569271491847, 'bagging_freq': 10, 'lambda_l1': 1.9215645946133018e-07, 'lambda_l2': 0.026889501478990385, 'min_child_samples': 35, 'max_depth': 10, 'max_bin': 478, 'min_data_in_leaf': 58, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.9614402493394545, 'min_gain_to_split': 0.2795253170204048}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:36:40,736] Trial 394 finished with value: 127.0266122051648 and parameters: {'num_leaves': 88, 'learning_rate': 0.01757356053793589, 'feature_fraction': 0.7833296637438976, 'bagging_fraction': 0.7216248615484222, 'bagging_freq': 8, 'lambda_l1': 4.5782072970394696e-07, 'lambda_l2': 0.17487835410647348, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 426, 'min_data_in_leaf': 33, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.8955952518820083, 'min_gain_to_split': 0.020318818959354445}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:37:26,638] Trial 395 finished with value: 134.51438874294604 and parameters: {'num_leaves': 15, 'learning_rate': 0.12546138075015556, 'feature_fraction': 0.6399240812545893, 'bagging_fraction': 0.9599393608513923, 'bagging_freq': 10, 'lambda_l1': 6.143699268772526e-06, 'lambda_l2': 0.01370621684637056, 'min_child_samples': 41, 'max_depth': 10, 'max_bin': 361, 'min_data_in_leaf': 65, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.931261222083679, 'min_gain_to_split': 0.357343467250006}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:38:12,985] Trial 396 finished with value: 111.81656997240869 and parameters: {'num_leaves': 20, 'learning_rate': 0.09160038167479173, 'feature_fraction': 0.6597701598124844, 'bagging_fraction': 0.8796532741832329, 'bagging_freq': 10, 'lambda_l1': 2.3234568345682725e-06, 'lambda_l2': 0.0054777371011302724, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 485, 'min_data_in_leaf': 28, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.4532820669343757, 'min_gain_to_split': 0.29894183790482065}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:39:16,631] Trial 397 finished with value: 137.50990531533142 and parameters: {'num_leaves': 17, 'learning_rate': 0.10425530151337016, 'feature_fraction': 0.6982240013762278, 'bagging_fraction': 0.832458261664084, 'bagging_freq': 10, 'lambda_l1': 3.7380223225067735e-05, 'lambda_l2': 0.12054945467485874, 'min_child_samples': 48, 'max_depth': 9, 'max_bin': 500, 'min_data_in_leaf': 68, 'extra_trees': True, 'early_stopping_rounds': 30, 'path_smooth': 0.8393800936140514, 'min_gain_to_split': 0.034512227677864146}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:40:12,575] Trial 398 finished with value: 127.08536119984623 and parameters: {'num_leaves': 23, 'learning_rate': 0.1908618673543668, 'feature_fraction': 0.6683554476637222, 'bagging_fraction': 0.9711259153416051, 'bagging_freq': 9, 'lambda_l1': 1.2458915022492897e-06, 'lambda_l2': 0.008412680280071336, 'min_child_samples': 46, 'max_depth': 10, 'max_bin': 468, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 34, 'path_smooth': 0.3817358288095252, 'min_gain_to_split': 0.045660398632300994}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:41:06,944] Trial 399 finished with value: 130.15859907607856 and parameters: {'num_leaves': 19, 'learning_rate': 0.1410442282484152, 'feature_fraction': 0.6210627532268026, 'bagging_fraction': 0.943816776884823, 'bagging_freq': 10, 'lambda_l1': 9.276618315504889e-05, 'lambda_l2': 0.06671218459433258, 'min_child_samples': 44, 'max_depth': 10, 'max_bin': 350, 'min_data_in_leaf': 63, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.9989903324275398, 'min_gain_to_split': 0.0021821110682415153}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:42:06,962] Trial 400 finished with value: 135.83278866601697 and parameters: {'num_leaves': 22, 'learning_rate': 0.11855581807348284, 'feature_fraction': 0.645410606453, 'bagging_fraction': 0.9316577839232534, 'bagging_freq': 10, 'lambda_l1': 1.625024894619235e-08, 'lambda_l2': 0.01728234404293956, 'min_child_samples': 49, 'max_depth': 9, 'max_bin': 398, 'min_data_in_leaf': 55, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.424401979255561, 'min_gain_to_split': 0.33853945624441323}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:43:03,602] Trial 401 finished with value: 124.98148982655107 and parameters: {'num_leaves': 25, 'learning_rate': 0.09688853882147104, 'feature_fraction': 0.6530398609207037, 'bagging_fraction': 0.9606163770706947, 'bagging_freq': 9, 'lambda_l1': 1.3974950602691354e-05, 'lambda_l2': 0.036470219775245366, 'min_child_samples': 47, 'max_depth': 10, 'max_bin': 387, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9628691781071438, 'min_gain_to_split': 0.025904757485647405}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:43:51,829] Trial 402 finished with value: 139.52932688059815 and parameters: {'num_leaves': 17, 'learning_rate': 0.1307196824692313, 'feature_fraction': 0.6360529714682603, 'bagging_fraction': 0.9189968234124443, 'bagging_freq': 8, 'lambda_l1': 6.332024563047815e-07, 'lambda_l2': 0.023143584351577595, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 370, 'min_data_in_leaf': 70, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.4071782167566818, 'min_gain_to_split': 0.26978058045959097}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:44:38,503] Trial 403 finished with value: 148.6950032589729 and parameters: {'num_leaves': 20, 'learning_rate': 0.08315875091000056, 'feature_fraction': 0.6607733281249635, 'bagging_fraction': 0.9661478198382496, 'bagging_freq': 10, 'lambda_l1': 3.596739844361869e-06, 'lambda_l2': 0.014807509392720221, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 252, 'min_data_in_leaf': 67, 'extra_trees': True, 'early_stopping_rounds': 23, 'path_smooth': 0.9437518332778351, 'min_gain_to_split': 0.330298994581691}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:45:31,345] Trial 404 finished with value: 122.80481283366308 and parameters: {'num_leaves': 21, 'learning_rate': 0.14934516072863183, 'feature_fraction': 0.6768221323507648, 'bagging_fraction': 0.9022385675877587, 'bagging_freq': 2, 'lambda_l1': 2.4428032159969292e-05, 'lambda_l2': 0.009629088209734647, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 490, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.9761552456787469, 'min_gain_to_split': 0.05517345531564834}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:47:51,573] Trial 405 finished with value: 122.67858091421749 and parameters: {'num_leaves': 27, 'learning_rate': 0.07549708111660436, 'feature_fraction': 0.6470847242711302, 'bagging_fraction': 0.9800088880487757, 'bagging_freq': 7, 'lambda_l1': 8.590161097215018e-06, 'lambda_l2': 0.0032923426540104514, 'min_child_samples': 45, 'max_depth': 10, 'max_bin': 476, 'min_data_in_leaf': 65, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.6141304054449195, 'min_gain_to_split': 0.10912654132085386}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:48:35,493] Trial 406 finished with value: 120.68859541681351 and parameters: {'num_leaves': 18, 'learning_rate': 0.10820324638687519, 'feature_fraction': 0.6550695984350671, 'bagging_fraction': 0.9532748911021391, 'bagging_freq': 10, 'lambda_l1': 1.2802934569348898e-07, 'lambda_l2': 0.04512453024463256, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 110, 'min_data_in_leaf': 42, 'extra_trees': True, 'early_stopping_rounds': 21, 'path_smooth': 0.4774674747379343, 'min_gain_to_split': 0.30740880551535327}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:49:30,673] Trial 407 finished with value: 139.8456172247813 and parameters: {'num_leaves': 23, 'learning_rate': 0.16009504421955936, 'feature_fraction': 0.6650506936762672, 'bagging_fraction': 0.9742679188081418, 'bagging_freq': 10, 'lambda_l1': 4.843557598868121e-06, 'lambda_l2': 0.07477749247438974, 'min_child_samples': 40, 'max_depth': 10, 'max_bin': 334, 'min_data_in_leaf': 74, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.9109283810712916, 'min_gain_to_split': 0.291949608837421}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:50:21,643] Trial 408 finished with value: 137.18615047436464 and parameters: {'num_leaves': 16, 'learning_rate': 0.10163844850290867, 'feature_fraction': 0.6875653986054066, 'bagging_fraction': 0.9402325251162389, 'bagging_freq': 10, 'lambda_l1': 3.5846345157138086e-07, 'lambda_l2': 0.021565105438717952, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 361, 'min_data_in_leaf': 61, 'extra_trees': True, 'early_stopping_rounds': 31, 'path_smooth': 0.428389191529645, 'min_gain_to_split': 0.017366709217246576}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:51:10,565] Trial 409 finished with value: 113.8322961766958 and parameters: {'num_leaves': 19, 'learning_rate': 0.11817868123030224, 'feature_fraction': 0.6254803719069546, 'bagging_fraction': 0.9464694098385283, 'bagging_freq': 9, 'lambda_l1': 1.6699850201631262e-06, 'lambda_l2': 0.01144216981492826, 'min_child_samples': 42, 'max_depth': 10, 'max_bin': 483, 'min_data_in_leaf': 25, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.457934022347075, 'min_gain_to_split': 0.039700014330463246}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:52:00,764] Trial 410 finished with value: 109.99019368042066 and parameters: {'num_leaves': 24, 'learning_rate': 0.11115445633518695, 'feature_fraction': 0.6745572837733319, 'bagging_fraction': 0.9245829302033972, 'bagging_freq': 10, 'lambda_l1': 9.800744347841663e-07, 'lambda_l2': 0.03019078667479798, 'min_child_samples': 32, 'max_depth': 10, 'max_bin': 377, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.38985957723341597, 'min_gain_to_split': 0.08155011324273684}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:53:10,052] Trial 411 finished with value: 132.5686254934521 and parameters: {'num_leaves': 21, 'learning_rate': 0.05695448003176088, 'feature_fraction': 0.6413453564558897, 'bagging_fraction': 0.9876851126908688, 'bagging_freq': 10, 'lambda_l1': 0.00018880789944184526, 'lambda_l2': 0.00743831108022985, 'min_child_samples': 46, 'max_depth': 10, 'max_bin': 463, 'min_data_in_leaf': 52, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.6749557927868343, 'min_gain_to_split': 0.06815749908406243}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:53:57,297] Trial 412 finished with value: 121.40563731197226 and parameters: {'num_leaves': 15, 'learning_rate': 0.12551638726280043, 'feature_fraction': 0.6338165698669429, 'bagging_fraction': 0.9655131702620966, 'bagging_freq': 10, 'lambda_l1': 1.0784323007359346e-05, 'lambda_l2': 0.11003843337334496, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 354, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.944043229812054, 'min_gain_to_split': 0.00023548137172177755}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:54:50,372] Trial 413 finished with value: 140.47238889675938 and parameters: {'num_leaves': 18, 'learning_rate': 0.08654194331528774, 'feature_fraction': 0.6564479740219554, 'bagging_fraction': 0.9108502148268639, 'bagging_freq': 10, 'lambda_l1': 1.9731789732972303e-05, 'lambda_l2': 5.225966592403776e-06, 'min_child_samples': 27, 'max_depth': 10, 'max_bin': 473, 'min_data_in_leaf': 68, 'extra_trees': True, 'early_stopping_rounds': 44, 'path_smooth': 0.9823833715591084, 'min_gain_to_split': 0.029254720802323005}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:55:37,167] Trial 414 finished with value: 116.82507755003726 and parameters: {'num_leaves': 22, 'learning_rate': 0.09435880480680447, 'feature_fraction': 0.6668683909707188, 'bagging_fraction': 0.9557347965651719, 'bagging_freq': 9, 'lambda_l1': 5.000026168445388e-05, 'lambda_l2': 0.005346385258654591, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 343, 'min_data_in_leaf': 40, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.9264289951292591, 'min_gain_to_split': 0.021819559354925907}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:56:36,995] Trial 415 finished with value: 130.0524616623416 and parameters: {'num_leaves': 20, 'learning_rate': 0.1390104152138639, 'feature_fraction': 0.9429650288600929, 'bagging_fraction': 0.9715369205437394, 'bagging_freq': 10, 'lambda_l1': 2.9619004240819854e-06, 'lambda_l2': 0.01923656609175725, 'min_child_samples': 44, 'max_depth': 10, 'max_bin': 493, 'min_data_in_leaf': 63, 'extra_trees': True, 'early_stopping_rounds': 33, 'path_smooth': 0.7876868528878788, 'min_gain_to_split': 0.16482943625626129}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:57:25,661] Trial 416 finished with value: 141.13021972308348 and parameters: {'num_leaves': 26, 'learning_rate': 0.10340413396450769, 'feature_fraction': 0.6490833492549684, 'bagging_fraction': 0.9954873606926854, 'bagging_freq': 10, 'lambda_l1': 6.405134387158406e-08, 'lambda_l2': 0.05545684687139654, 'min_child_samples': 47, 'max_depth': 10, 'max_bin': 326, 'min_data_in_leaf': 91, 'extra_trees': True, 'early_stopping_rounds': 32, 'path_smooth': 0.437595654011949, 'min_gain_to_split': 0.25401896229393256}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:58:24,045] Trial 417 finished with value: 116.82591311545745 and parameters: {'num_leaves': 17, 'learning_rate': 0.11465048274803087, 'feature_fraction': 0.6801065402731244, 'bagging_fraction': 0.9818433169765168, 'bagging_freq': 10, 'lambda_l1': 0.0003751156333530536, 'lambda_l2': 0.013369305565067708, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 486, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 30, 'path_smooth': 0.2762891313160427, 'min_gain_to_split': 0.3184354735695244}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 21:59:07,329] Trial 418 finished with value: 114.75852380596018 and parameters: {'num_leaves': 73, 'learning_rate': 0.13261826730339552, 'feature_fraction': 0.6170483532295463, 'bagging_fraction': 0.9620123790424104, 'bagging_freq': 8, 'lambda_l1': 2.4506470935459243e-07, 'lambda_l2': 0.03509757116297397, 'min_child_samples': 50, 'max_depth': 7, 'max_bin': 310, 'min_data_in_leaf': 31, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.4136186138332492, 'min_gain_to_split': 0.03657738737138431}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:00:04,057] Trial 419 finished with value: 138.02643858848415 and parameters: {'num_leaves': 24, 'learning_rate': 0.1214075866760853, 'feature_fraction': 0.7105083363232353, 'bagging_fraction': 0.8876037750940462, 'bagging_freq': 9, 'lambda_l1': 3.1250260292194526e-08, 'lambda_l2': 0.02597440259230859, 'min_child_samples': 45, 'max_depth': 10, 'max_bin': 387, 'min_data_in_leaf': 70, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.9547282149052482, 'min_gain_to_split': 0.009975563566532182}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:00:57,254] Trial 420 finished with value: 139.26681627918387 and parameters: {'num_leaves': 19, 'learning_rate': 0.1470331509127224, 'feature_fraction': 0.7464041238591514, 'bagging_fraction': 0.9343233285113934, 'bagging_freq': 10, 'lambda_l1': 5.970232054956519e-06, 'lambda_l2': 0.20267435314705232, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 365, 'min_data_in_leaf': 60, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.9976141917075918, 'min_gain_to_split': 0.05309624476226948}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:01:45,537] Trial 421 finished with value: 132.04709556636325 and parameters: {'num_leaves': 22, 'learning_rate': 0.1065633550032235, 'feature_fraction': 0.6594328585460626, 'bagging_fraction': 0.9516482207287742, 'bagging_freq': 10, 'lambda_l1': 5.893772988852313e-07, 'lambda_l2': 0.010327960343592837, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 371, 'min_data_in_leaf': 66, 'extra_trees': True, 'early_stopping_rounds': 37, 'path_smooth': 0.35083347517377694, 'min_gain_to_split': 0.30221784815105013}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:02:37,692] Trial 422 finished with value: 122.61502448523916 and parameters: {'num_leaves': 30, 'learning_rate': 0.09640785507009604, 'feature_fraction': 0.6426705835900227, 'bagging_fraction': 0.9749015583724395, 'bagging_freq': 10, 'lambda_l1': 3.053553065373646e-05, 'lambda_l2': 0.08401467144119867, 'min_child_samples': 47, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.4696003996137329, 'min_gain_to_split': 0.0915808397973597}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:03:27,505] Trial 423 finished with value: 139.23168655509843 and parameters: {'num_leaves': 51, 'learning_rate': 0.15929053585165312, 'feature_fraction': 0.66973627438325, 'bagging_fraction': 0.9478243652185588, 'bagging_freq': 9, 'lambda_l1': 1.5062786087207953e-05, 'lambda_l2': 0.0164700927059064, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 349, 'min_data_in_leaf': 64, 'extra_trees': True, 'early_stopping_rounds': 34, 'path_smooth': 0.3723137239835036, 'min_gain_to_split': 0.27575555218166586}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:04:38,842] Trial 424 finished with value: 105.54983055882349 and parameters: {'num_leaves': 25, 'learning_rate': 0.11345212454920484, 'feature_fraction': 0.6283091293772237, 'bagging_fraction': 0.8207251474241037, 'bagging_freq': 10, 'lambda_l1': 2.5586652315653373e-06, 'lambda_l2': 0.04532047804884321, 'min_child_samples': 38, 'max_depth': 10, 'max_bin': 455, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.896418771587015, 'min_gain_to_split': 0.48110073954882926}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:05:24,017] Trial 425 finished with value: 144.1411684791558 and parameters: {'num_leaves': 20, 'learning_rate': 0.09194631446951691, 'feature_fraction': 0.6503088572847905, 'bagging_fraction': 0.8623849373598468, 'bagging_freq': 10, 'lambda_l1': 0.0001373095399322152, 'lambda_l2': 0.0034747643276732587, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 213, 'min_data_in_leaf': 67, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.528061121119892, 'min_gain_to_split': 0.015408434391744955}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:06:08,240] Trial 426 finished with value: 118.79348562232772 and parameters: {'num_leaves': 16, 'learning_rate': 0.12666464752198445, 'feature_fraction': 0.6364886574501551, 'bagging_fraction': 0.9181771020855787, 'bagging_freq': 10, 'lambda_l1': 7.562743761930441e-05, 'lambda_l2': 0.0063991804101300774, 'min_child_samples': 47, 'max_depth': 10, 'max_bin': 494, 'min_data_in_leaf': 33, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.9643399859143593, 'min_gain_to_split': 0.32156962422767926}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:07:07,326] Trial 427 finished with value: 140.7605270739743 and parameters: {'num_leaves': 22, 'learning_rate': 0.10128098079638059, 'feature_fraction': 0.6951366077879073, 'bagging_fraction': 0.9682316389627098, 'bagging_freq': 9, 'lambda_l1': 7.980453633999557e-07, 'lambda_l2': 0.0243308871593778, 'min_child_samples': 46, 'max_depth': 10, 'max_bin': 337, 'min_data_in_leaf': 69, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.8720627649312845, 'min_gain_to_split': 0.2039830672887302}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:08:06,658] Trial 428 finished with value: 112.35580927596348 and parameters: {'num_leaves': 92, 'learning_rate': 0.10752545561353016, 'feature_fraction': 0.6623535007593472, 'bagging_fraction': 0.9575277525231004, 'bagging_freq': 10, 'lambda_l1': 8.742670175139435e-06, 'lambda_l2': 0.3823677181730258, 'min_child_samples': 44, 'max_depth': 10, 'max_bin': 500, 'min_data_in_leaf': 41, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.44802768472785487, 'min_gain_to_split': 0.28782530003530515}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:08:53,877] Trial 429 finished with value: 133.31796943300634 and parameters: {'num_leaves': 18, 'learning_rate': 0.17475538568147103, 'feature_fraction': 0.6728621988169511, 'bagging_fraction': 0.8408544989992597, 'bagging_freq': 10, 'lambda_l1': 1.807527100735932e-06, 'lambda_l2': 0.1413401148208493, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 473, 'min_data_in_leaf': 49, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.5043651475332193, 'min_gain_to_split': 0.1272099020279819}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:09:41,531] Trial 430 finished with value: 137.18762808441048 and parameters: {'num_leaves': 20, 'learning_rate': 0.11906707720364966, 'feature_fraction': 0.6548423234225861, 'bagging_fraction': 0.896457729585053, 'bagging_freq': 8, 'lambda_l1': 4.291111657155147e-06, 'lambda_l2': 0.01007827978589778, 'min_child_samples': 49, 'max_depth': 8, 'max_bin': 358, 'min_data_in_leaf': 65, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.39546032664797287, 'min_gain_to_split': 0.02764507111024485}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:10:30,975] Trial 431 finished with value: 127.85125066913315 and parameters: {'num_leaves': 24, 'learning_rate': 0.14291944939358917, 'feature_fraction': 0.6837276179252817, 'bagging_fraction': 0.930735994794925, 'bagging_freq': 10, 'lambda_l1': 3.5315486550209903e-07, 'lambda_l2': 0.0003720919578055293, 'min_child_samples': 45, 'max_depth': 10, 'max_bin': 382, 'min_data_in_leaf': 57, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.929182790394621, 'min_gain_to_split': 0.04436186647146942}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:11:18,011] Trial 432 finished with value: 116.14384665781958 and parameters: {'num_leaves': 28, 'learning_rate': 0.1360180556235421, 'feature_fraction': 0.6067903777788727, 'bagging_fraction': 0.9422379113229014, 'bagging_freq': 6, 'lambda_l1': 1.2152936114792337e-06, 'lambda_l2': 0.016208713463947762, 'min_child_samples': 42, 'max_depth': 9, 'max_bin': 486, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.42751547046455723, 'min_gain_to_split': 0.26447183896454196}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:12:09,259] Trial 433 finished with value: 119.31024454048524 and parameters: {'num_leaves': 15, 'learning_rate': 0.08897361543346358, 'feature_fraction': 0.6461134728732825, 'bagging_fraction': 0.9855842808443596, 'bagging_freq': 9, 'lambda_l1': 7.027538591543546e-06, 'lambda_l2': 0.06880927493513911, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 366, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 35, 'path_smooth': 0.4037808203617085, 'min_gain_to_split': 0.3104898825151901}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:13:03,687] Trial 434 finished with value: 145.90954338184915 and parameters: {'num_leaves': 17, 'learning_rate': 0.09891777206682031, 'feature_fraction': 0.6376202347450591, 'bagging_fraction': 0.9140395737819524, 'bagging_freq': 10, 'lambda_l1': 1.543491272217694e-05, 'lambda_l2': 0.04172453909593205, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 462, 'min_data_in_leaf': 71, 'extra_trees': True, 'early_stopping_rounds': 32, 'path_smooth': 0.908101550116445, 'min_gain_to_split': 0.24214767850452754}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:13:48,629] Trial 435 finished with value: 120.88685960135722 and parameters: {'num_leaves': 21, 'learning_rate': 0.1149388721956397, 'feature_fraction': 0.66526882752419, 'bagging_fraction': 0.9641398593964358, 'bagging_freq': 7, 'lambda_l1': 1.8461219545838562e-07, 'lambda_l2': 0.03023633645141982, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 192, 'min_data_in_leaf': 44, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.9789894554366965, 'min_gain_to_split': 0.33198465157970564}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:14:41,271] Trial 436 finished with value: 137.20237454530536 and parameters: {'num_leaves': 23, 'learning_rate': 0.12680467745584434, 'feature_fraction': 0.8698621409949814, 'bagging_fraction': 0.9773804708772353, 'bagging_freq': 10, 'lambda_l1': 3.4882201749371016e-05, 'lambda_l2': 0.007748351572319772, 'min_child_samples': 47, 'max_depth': 10, 'max_bin': 413, 'min_data_in_leaf': 62, 'extra_trees': True, 'early_stopping_rounds': 23, 'path_smooth': 0.936085794649176, 'min_gain_to_split': 0.03394910496534023}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:15:40,574] Trial 437 finished with value: 144.61765606549108 and parameters: {'num_leaves': 26, 'learning_rate': 0.10954016418747492, 'feature_fraction': 0.6540094958027977, 'bagging_fraction': 0.9529112656389608, 'bagging_freq': 10, 'lambda_l1': 9.962451218514252e-06, 'lambda_l2': 1.2663062844716958e-05, 'min_child_samples': 46, 'max_depth': 10, 'max_bin': 478, 'min_data_in_leaf': 68, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.4480022318891084, 'min_gain_to_split': 0.017177104336119006}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:16:25,831] Trial 438 finished with value: 146.81237807426209 and parameters: {'num_leaves': 19, 'learning_rate': 0.1539460203788299, 'feature_fraction': 0.627287333737715, 'bagging_fraction': 0.9055962325262956, 'bagging_freq': 10, 'lambda_l1': 2.375464374164624e-05, 'lambda_l2': 0.013535556039426808, 'min_child_samples': 44, 'max_depth': 10, 'max_bin': 324, 'min_data_in_leaf': 98, 'extra_trees': True, 'early_stopping_rounds': 30, 'path_smooth': 0.9498532845576269, 'min_gain_to_split': 0.05135855141867271}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:17:12,140] Trial 439 finished with value: 126.55288005705515 and parameters: {'num_leaves': 22, 'learning_rate': 0.10273274860499128, 'feature_fraction': 0.6768742766404362, 'bagging_fraction': 0.9385462938650514, 'bagging_freq': 9, 'lambda_l1': 2.169185268930969, 'lambda_l2': 0.020701046352713623, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 346, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.47287169135932083, 'min_gain_to_split': 0.007457336393081548}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:17:54,733] Trial 440 finished with value: 113.46489462164843 and parameters: {'num_leaves': 18, 'learning_rate': 0.11924029820803492, 'feature_fraction': 0.6453308248964579, 'bagging_fraction': 0.9256514475305784, 'bagging_freq': 10, 'lambda_l1': 1.024783499333971e-08, 'lambda_l2': 0.004150660739273455, 'min_child_samples': 20, 'max_depth': 10, 'max_bin': 375, 'min_data_in_leaf': 29, 'extra_trees': True, 'early_stopping_rounds': 33, 'path_smooth': 0.9657969686000688, 'min_gain_to_split': 0.06032867642887084}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:18:40,087] Trial 441 finished with value: 114.43555077550654 and parameters: {'num_leaves': 21, 'learning_rate': 0.13563986277293824, 'feature_fraction': 0.6618426914389437, 'bagging_fraction': 0.9699506614947062, 'bagging_freq': 10, 'lambda_l1': 0.001245965661220187, 'lambda_l2': 0.051931544473420965, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 315, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.4159788017624031, 'min_gain_to_split': 0.02750370736922784}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:19:31,772] Trial 442 finished with value: 106.87884899107223 and parameters: {'num_leaves': 24, 'learning_rate': 0.09355162016520382, 'feature_fraction': 0.6707348568632421, 'bagging_fraction': 0.9591509314010678, 'bagging_freq': 10, 'lambda_l1': 4.818722840099212e-07, 'lambda_l2': 0.030196149986788757, 'min_child_samples': 49, 'max_depth': 9, 'max_bin': 470, 'min_data_in_leaf': 20, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.9840316267388513, 'min_gain_to_split': 0.303172563853583}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:20:52,963] Trial 443 finished with value: 125.20471178852543 and parameters: {'num_leaves': 17, 'learning_rate': 0.16472576428526936, 'feature_fraction': 0.99145775674617, 'bagging_fraction': 0.9445742229521902, 'bagging_freq': 9, 'lambda_l1': 5.307569700571811e-06, 'lambda_l2': 0.09664689872335824, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 488, 'min_data_in_leaf': 66, 'extra_trees': False, 'early_stopping_rounds': 31, 'path_smooth': 0.9173579517442709, 'min_gain_to_split': 0.03671537112722364}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:21:35,906] Trial 444 finished with value: 140.17574557914116 and parameters: {'num_leaves': 19, 'learning_rate': 0.10778401269258864, 'feature_fraction': 0.6902697824458192, 'bagging_fraction': 0.8527890105585682, 'bagging_freq': 10, 'lambda_l1': 2.9800009009947946e-06, 'lambda_l2': 1.681491367303943e-07, 'min_child_samples': 45, 'max_depth': 10, 'max_bin': 353, 'min_data_in_leaf': 53, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.376226011104448, 'min_gain_to_split': 0.3147217423752509}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:22:25,190] Trial 445 finished with value: 116.6440888608151 and parameters: {'num_leaves': 55, 'learning_rate': 0.12822937435092335, 'feature_fraction': 0.6520444984942958, 'bagging_fraction': 0.8720585255996469, 'bagging_freq': 8, 'lambda_l1': 1.372036217453837e-06, 'lambda_l2': 0.010273465932239274, 'min_child_samples': 30, 'max_depth': 10, 'max_bin': 481, 'min_data_in_leaf': 22, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.5482240165061483, 'min_gain_to_split': 0.22869958802959944}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:23:15,286] Trial 446 finished with value: 122.228665567096 and parameters: {'num_leaves': 15, 'learning_rate': 0.08390293186222933, 'feature_fraction': 0.6342596203901522, 'bagging_fraction': 0.9824085056783612, 'bagging_freq': 10, 'lambda_l1': 7.457166738373205e-07, 'lambda_l2': 0.01662393913504408, 'min_child_samples': 41, 'max_depth': 10, 'max_bin': 338, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.3362889535403574, 'min_gain_to_split': 0.14277032015626107}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:24:07,934] Trial 447 finished with value: 133.3265176312324 and parameters: {'num_leaves': 26, 'learning_rate': 0.11309416992351601, 'feature_fraction': 0.6151316477585994, 'bagging_fraction': 0.9749851773040236, 'bagging_freq': 10, 'lambda_l1': 2.1129906197297814e-08, 'lambda_l2': 0.005687089017011191, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 493, 'min_data_in_leaf': 64, 'extra_trees': True, 'early_stopping_rounds': 30, 'path_smooth': 0.5916470396949637, 'min_gain_to_split': 0.3506834321142879}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:24:56,579] Trial 448 finished with value: 142.59047103257828 and parameters: {'num_leaves': 20, 'learning_rate': 0.09774169186697633, 'feature_fraction': 0.659651971209208, 'bagging_fraction': 0.9505633899807903, 'bagging_freq': 10, 'lambda_l1': 1.2603689210380784e-05, 'lambda_l2': 0.036745850019097734, 'min_child_samples': 48, 'max_depth': 5, 'max_bin': 445, 'min_data_in_leaf': 72, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.4946027542894761, 'min_gain_to_split': 0.29136632963353953}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:25:42,680] Trial 449 finished with value: 138.21976323178706 and parameters: {'num_leaves': 23, 'learning_rate': 0.06676882277746429, 'feature_fraction': 0.6817565728229521, 'bagging_fraction': 0.9618016406238182, 'bagging_freq': 9, 'lambda_l1': 1.9028223561796106e-06, 'lambda_l2': 0.0218297783113048, 'min_child_samples': 49, 'max_depth': 4, 'max_bin': 362, 'min_data_in_leaf': 59, 'extra_trees': True, 'early_stopping_rounds': 23, 'path_smooth': 0.4374672104232077, 'min_gain_to_split': 0.027202656654475018}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:26:28,526] Trial 450 finished with value: 140.8843517332632 and parameters: {'num_leaves': 33, 'learning_rate': 0.14955960106389743, 'feature_fraction': 0.6427227765352013, 'bagging_fraction': 0.9683575211511237, 'bagging_freq': 4, 'lambda_l1': 2.7711904979690016e-07, 'lambda_l2': 0.06206665839794343, 'min_child_samples': 46, 'max_depth': 10, 'max_bin': 330, 'min_data_in_leaf': 67, 'extra_trees': True, 'early_stopping_rounds': 22, 'path_smooth': 0.9513194810066707, 'min_gain_to_split': 0.04429018577196277}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:27:21,065] Trial 451 finished with value: 120.7026291897705 and parameters: {'num_leaves': 18, 'learning_rate': 0.12046286098828492, 'feature_fraction': 0.6696038382142019, 'bagging_fraction': 0.9204539395026266, 'bagging_freq': 10, 'lambda_l1': 1.833463348821949e-05, 'lambda_l2': 0.12675655702106423, 'min_child_samples': 47, 'max_depth': 10, 'max_bin': 392, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.8856334566054715, 'min_gain_to_split': 5.244706561975676e-05}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:28:20,498] Trial 452 finished with value: 128.30557729725663 and parameters: {'num_leaves': 21, 'learning_rate': 0.10270213105014309, 'feature_fraction': 0.7013364335667938, 'bagging_fraction': 0.988655785139065, 'bagging_freq': 8, 'lambda_l1': 5.6580457477216554e-05, 'lambda_l2': 0.012007368928799103, 'min_child_samples': 34, 'max_depth': 10, 'max_bin': 374, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.9968723142890574, 'min_gain_to_split': 0.01461016657535726}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:29:03,807] Trial 453 finished with value: 121.48011501751348 and parameters: {'num_leaves': 17, 'learning_rate': 0.13043888079290508, 'feature_fraction': 0.6255894709794029, 'bagging_fraction': 0.9592928580351557, 'bagging_freq': 10, 'lambda_l1': 4.035343351247226e-06, 'lambda_l2': 0.008120710610006075, 'min_child_samples': 39, 'max_depth': 10, 'max_bin': 468, 'min_data_in_leaf': 40, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.45883989648018625, 'min_gain_to_split': 0.27916495281276466}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:29:50,482] Trial 454 finished with value: 137.75695327228772 and parameters: {'num_leaves': 24, 'learning_rate': 0.1850752044958457, 'feature_fraction': 0.6515087051454093, 'bagging_fraction': 0.9366320796211921, 'bagging_freq': 10, 'lambda_l1': 6.66743107746672e-06, 'lambda_l2': 0.0006960976651203062, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 500, 'min_data_in_leaf': 62, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.4062061927637935, 'min_gain_to_split': 0.32120147567530977}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:30:46,216] Trial 455 finished with value: 138.1776842468749 and parameters: {'num_leaves': 27, 'learning_rate': 0.11247010678023445, 'feature_fraction': 0.8330286992817452, 'bagging_fraction': 0.9783037239591911, 'bagging_freq': 9, 'lambda_l1': 1.205993940463599e-07, 'lambda_l2': 0.027333616790283104, 'min_child_samples': 44, 'max_depth': 10, 'max_bin': 404, 'min_data_in_leaf': 84, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.929946018812863, 'min_gain_to_split': 0.10109665509931134}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:31:33,255] Trial 456 finished with value: 116.11503578983638 and parameters: {'num_leaves': 19, 'learning_rate': 0.1430547502023099, 'feature_fraction': 0.6411198807009004, 'bagging_fraction': 0.7984015170735068, 'bagging_freq': 10, 'lambda_l1': 0.00024522661480578416, 'lambda_l2': 0.01650895377602481, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 485, 'min_data_in_leaf': 32, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.9681386608364672, 'min_gain_to_split': 0.0199036648854271}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:32:19,916] Trial 457 finished with value: 126.80346072175469 and parameters: {'num_leaves': 22, 'learning_rate': 0.08831929131855151, 'feature_fraction': 0.6591372641795038, 'bagging_fraction': 0.947679331156034, 'bagging_freq': 10, 'lambda_l1': 2.563379578463801e-06, 'lambda_l2': 0.001605295450209069, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 368, 'min_data_in_leaf': 47, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.38506479785682773, 'min_gain_to_split': 0.0679774670983846}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:33:14,272] Trial 458 finished with value: 138.52178344369761 and parameters: {'num_leaves': 16, 'learning_rate': 0.10567785049945484, 'feature_fraction': 0.6342559529174738, 'bagging_fraction': 0.9561680117228148, 'bagging_freq': 10, 'lambda_l1': 4.822410987509269e-07, 'lambda_l2': 0.22433078028666906, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 355, 'min_data_in_leaf': 69, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.7325078056229986, 'min_gain_to_split': 0.04607723648446552}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:33:55,200] Trial 459 finished with value: 131.16118204829746 and parameters: {'num_leaves': 21, 'learning_rate': 0.12108230516541141, 'feature_fraction': 0.6752755316909126, 'bagging_fraction': 0.9116536842514501, 'bagging_freq': 10, 'lambda_l1': 1.1072039028620048e-06, 'lambda_l2': 0.04396421926592891, 'min_child_samples': 45, 'max_depth': 10, 'max_bin': 278, 'min_data_in_leaf': 56, 'extra_trees': True, 'early_stopping_rounds': 33, 'path_smooth': 0.4246009609496473, 'min_gain_to_split': 0.3349993167678712}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:34:54,268] Trial 460 finished with value: 136.01927951758142 and parameters: {'num_leaves': 44, 'learning_rate': 0.09658854715586936, 'feature_fraction': 0.6656347644665634, 'bagging_fraction': 0.968986426338527, 'bagging_freq': 9, 'lambda_l1': 1.0959731226800333e-05, 'lambda_l2': 0.06705132190828066, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 346, 'min_data_in_leaf': 65, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.9148947941140715, 'min_gain_to_split': 0.033896151890054696}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:35:35,605] Trial 461 finished with value: 106.58056711234342 and parameters: {'num_leaves': 25, 'learning_rate': 0.15965245939285683, 'feature_fraction': 0.6488750829473025, 'bagging_fraction': 0.999701384952904, 'bagging_freq': 10, 'lambda_l1': 1.889470607836796e-05, 'lambda_l2': 0.011817801348945986, 'min_child_samples': 47, 'max_depth': 10, 'max_bin': 381, 'min_data_in_leaf': 26, 'extra_trees': True, 'early_stopping_rounds': 30, 'path_smooth': 0.4389758539495201, 'min_gain_to_split': 0.29539912013575637}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:36:36,169] Trial 462 finished with value: 141.09824286456137 and parameters: {'num_leaves': 19, 'learning_rate': 0.07620293078414042, 'feature_fraction': 0.6846506958498022, 'bagging_fraction': 0.9281242406916024, 'bagging_freq': 8, 'lambda_l1': 2.834801372165765e-05, 'lambda_l2': 0.006611792944296856, 'min_child_samples': 42, 'max_depth': 10, 'max_bin': 473, 'min_data_in_leaf': 67, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.9444695920293594, 'min_gain_to_split': 0.1819350335297633}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:37:56,058] Trial 463 finished with value: 113.92274116589601 and parameters: {'num_leaves': 23, 'learning_rate': 0.12539837687879118, 'feature_fraction': 0.6565503479710028, 'bagging_fraction': 0.962065891869411, 'bagging_freq': 10, 'lambda_l1': 5.7598610992528266e-08, 'lambda_l2': 0.024444004214193807, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 480, 'min_data_in_leaf': 42, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.36294521451620515, 'min_gain_to_split': 0.009107717381912881}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:39:12,662] Trial 464 finished with value: 116.29573314418147 and parameters: {'num_leaves': 29, 'learning_rate': 0.13537748420915757, 'feature_fraction': 0.6227262149129603, 'bagging_fraction': 0.9014658076208065, 'bagging_freq': 10, 'lambda_l1': 6.4970465339722345e-06, 'lambda_l2': 0.09826247613288079, 'min_child_samples': 46, 'max_depth': 10, 'max_bin': 491, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 32, 'path_smooth': 0.21722866192015078, 'min_gain_to_split': 0.11424655335202552}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:40:10,433] Trial 465 finished with value: 120.04560354061717 and parameters: {'num_leaves': 15, 'learning_rate': 0.11081157496907745, 'feature_fraction': 0.8061889305288082, 'bagging_fraction': 0.9434422673258924, 'bagging_freq': 9, 'lambda_l1': 0.00010501391207763769, 'lambda_l2': 0.0026567276767061566, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 358, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.9779041570903235, 'min_gain_to_split': 0.025538818102024772}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:41:09,162] Trial 466 finished with value: 122.71210224253836 and parameters: {'num_leaves': 20, 'learning_rate': 0.10217851992157911, 'feature_fraction': 0.6457941730122878, 'bagging_fraction': 0.9759370655089943, 'bagging_freq': 10, 'lambda_l1': 3.831007468253254e-06, 'lambda_l2': 0.017158126700699026, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 365, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.4011110809225467, 'min_gain_to_split': 0.26329224971765985}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:42:10,174] Trial 467 finished with value: 146.34790270917392 and parameters: {'num_leaves': 17, 'learning_rate': 0.09274186701061582, 'feature_fraction': 0.6669571584322368, 'bagging_fraction': 0.8443590728168453, 'bagging_freq': 10, 'lambda_l1': 0.1406415789012877, 'lambda_l2': 0.04433142412169958, 'min_child_samples': 37, 'max_depth': 10, 'max_bin': 459, 'min_data_in_leaf': 70, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.4812521805252272, 'min_gain_to_split': 0.30808179287413656}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:43:07,978] Trial 468 finished with value: 127.72505171303753 and parameters: {'num_leaves': 22, 'learning_rate': 0.17528880667687086, 'feature_fraction': 0.6350595832836619, 'bagging_fraction': 0.9519562190938718, 'bagging_freq': 10, 'lambda_l1': 2.1124762925344444e-06, 'lambda_l2': 0.00480070071474565, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 486, 'min_data_in_leaf': 68, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.8479114114812588, 'min_gain_to_split': 0.3269262795573572}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:44:07,845] Trial 469 finished with value: 137.20093223363614 and parameters: {'num_leaves': 25, 'learning_rate': 0.15022464489084789, 'feature_fraction': 0.6565382607504303, 'bagging_fraction': 0.9918692822015426, 'bagging_freq': 9, 'lambda_l1': 7.735806393745685e-07, 'lambda_l2': 0.009027801472171347, 'min_child_samples': 44, 'max_depth': 10, 'max_bin': 336, 'min_data_in_leaf': 64, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.8975024628506425, 'min_gain_to_split': 0.038372514065197885}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:44:59,392] Trial 470 finished with value: 139.63428907845983 and parameters: {'num_leaves': 18, 'learning_rate': 0.1193130740841333, 'feature_fraction': 0.674109550668896, 'bagging_fraction': 0.9175278792341769, 'bagging_freq': 10, 'lambda_l1': 3.7435276718524853e-08, 'lambda_l2': 0.03147984156151899, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 292, 'min_data_in_leaf': 66, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.9995241309029445, 'min_gain_to_split': 0.055218604228010615}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:45:48,370] Trial 471 finished with value: 117.34903472407662 and parameters: {'num_leaves': 20, 'learning_rate': 0.1087950630724354, 'feature_fraction': 0.6917501330945421, 'bagging_fraction': 0.9816294484017359, 'bagging_freq': 10, 'lambda_l1': 4.179575797244979e-05, 'lambda_l2': 0.0132773153884844, 'min_child_samples': 46, 'max_depth': 10, 'max_bin': 381, 'min_data_in_leaf': 41, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.4609901347209438, 'min_gain_to_split': 0.01762949905939802}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:46:44,178] Trial 472 finished with value: 115.6961334370078 and parameters: {'num_leaves': 23, 'learning_rate': 0.14003821975173822, 'feature_fraction': 0.9779813712430727, 'bagging_fraction': 0.9650474149547569, 'bagging_freq': 10, 'lambda_l1': 0.0004634662777854514, 'lambda_l2': 0.02260489729148636, 'min_child_samples': 42, 'max_depth': 9, 'max_bin': 476, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.9545330438547237, 'min_gain_to_split': 0.08110449638849292}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:47:34,987] Trial 473 finished with value: 113.82617908651969 and parameters: {'num_leaves': 18, 'learning_rate': 0.12981743864725984, 'feature_fraction': 0.6421730500299287, 'bagging_fraction': 0.9548142101675821, 'bagging_freq': 9, 'lambda_l1': 1.7836673521974048e-07, 'lambda_l2': 0.075740265181585, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 493, 'min_data_in_leaf': 24, 'extra_trees': True, 'early_stopping_rounds': 34, 'path_smooth': 0.6525256684651212, 'min_gain_to_split': 0.2483404052857154}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:48:29,357] Trial 474 finished with value: 115.67302919653966 and parameters: {'num_leaves': 21, 'learning_rate': 0.11470746235005225, 'feature_fraction': 0.6500291800970835, 'bagging_fraction': 0.9707179973545983, 'bagging_freq': 10, 'lambda_l1': 8.133340712169481e-06, 'lambda_l2': 0.1658942562018548, 'min_child_samples': 47, 'max_depth': 10, 'max_bin': 467, 'min_data_in_leaf': 33, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9272351621940511, 'min_gain_to_split': 0.27450276273675933}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:49:21,381] Trial 475 finished with value: 129.65649212165698 and parameters: {'num_leaves': 27, 'learning_rate': 0.10055160773046018, 'feature_fraction': 0.6609710343076061, 'bagging_fraction': 0.9349656432535354, 'bagging_freq': 10, 'lambda_l1': 1.4412989474620438e-08, 'lambda_l2': 0.006917707634489101, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 373, 'min_data_in_leaf': 60, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.42682802603135894, 'min_gain_to_split': 0.34175276653838654}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:50:06,279] Trial 476 finished with value: 123.23449241682442 and parameters: {'num_leaves': 15, 'learning_rate': 0.08659483781481361, 'feature_fraction': 0.6790546110664503, 'bagging_fraction': 0.9489600782361383, 'bagging_freq': 8, 'lambda_l1': 3.30052139304321e-07, 'lambda_l2': 0.034752696756412335, 'min_child_samples': 44, 'max_depth': 10, 'max_bin': 320, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 14, 'path_smooth': 0.8694113148902569, 'min_gain_to_split': 0.025649590892545978}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:51:03,562] Trial 477 finished with value: 143.0845035898621 and parameters: {'num_leaves': 79, 'learning_rate': 0.12191769363334284, 'feature_fraction': 0.6313118278623749, 'bagging_fraction': 0.9069865709353349, 'bagging_freq': 10, 'lambda_l1': 1.512338385220442e-05, 'lambda_l2': 0.01827322979029947, 'min_child_samples': 47, 'max_depth': 9, 'max_bin': 345, 'min_data_in_leaf': 63, 'extra_trees': True, 'early_stopping_rounds': 20, 'path_smooth': 0.9663747484165894, 'min_gain_to_split': 0.009356118274403889}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:52:10,633] Trial 478 finished with value: 135.40468238356297 and parameters: {'num_leaves': 17, 'learning_rate': 0.1053355713056887, 'feature_fraction': 0.6630587743914127, 'bagging_fraction': 0.8777551423046294, 'bagging_freq': 10, 'lambda_l1': 1.38125520732109e-06, 'lambda_l2': 0.011344902729269359, 'min_child_samples': 45, 'max_depth': 10, 'max_bin': 397, 'min_data_in_leaf': 69, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.4088701576421734, 'min_gain_to_split': 0.315128841157711}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:53:01,687] Trial 479 finished with value: 133.47123634832576 and parameters: {'num_leaves': 24, 'learning_rate': 0.09444597899616904, 'feature_fraction': 0.6404054178527451, 'bagging_fraction': 0.8584299896067377, 'bagging_freq': 9, 'lambda_l1': 5.163034578644816e-06, 'lambda_l2': 0.0432249073582786, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 485, 'min_data_in_leaf': 54, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.9424510646358268, 'min_gain_to_split': 0.039870701106816384}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:54:07,364] Trial 480 finished with value: 131.80227732808316 and parameters: {'num_leaves': 20, 'learning_rate': 0.0416984897799028, 'feature_fraction': 0.6504439287077397, 'bagging_fraction': 0.8839770227587607, 'bagging_freq': 7, 'lambda_l1': 6.003842453779673e-07, 'lambda_l2': 0.0036567752196959556, 'min_child_samples': 35, 'max_depth': 6, 'max_bin': 433, 'min_data_in_leaf': 50, 'extra_trees': True, 'early_stopping_rounds': 31, 'path_smooth': 0.3882540967436473, 'min_gain_to_split': 0.2204540176311195}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:54:47,657] Trial 481 finished with value: 120.50770973320218 and parameters: {'num_leaves': 19, 'learning_rate': 0.16647289015708072, 'feature_fraction': 0.6220323087116463, 'bagging_fraction': 0.9418893050395746, 'bagging_freq': 10, 'lambda_l1': 9.949073652194664e-07, 'lambda_l2': 0.05877852503422761, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 352, 'min_data_in_leaf': 44, 'extra_trees': True, 'early_stopping_rounds': 35, 'path_smooth': 0.44618025579024867, 'min_gain_to_split': 0.3026406690329205}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:55:59,081] Trial 482 finished with value: 112.72423979995582 and parameters: {'num_leaves': 23, 'learning_rate': 0.11450409881879224, 'feature_fraction': 0.6701789223513981, 'bagging_fraction': 0.9639089230735253, 'bagging_freq': 10, 'lambda_l1': 3.146040640636082e-06, 'lambda_l2': 0.02322258889083186, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 493, 'min_data_in_leaf': 30, 'extra_trees': False, 'early_stopping_rounds': 34, 'path_smooth': 0.9785636741651271, 'min_gain_to_split': 0.2885707477333853}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:56:44,314] Trial 483 finished with value: 137.61298534580638 and parameters: {'num_leaves': 25, 'learning_rate': 0.14449425050706238, 'feature_fraction': 0.6557529056175543, 'bagging_fraction': 0.9850698716692439, 'bagging_freq': 10, 'lambda_l1': 8.760165899254433e-06, 'lambda_l2': 0.009878014274499945, 'min_child_samples': 33, 'max_depth': 10, 'max_bin': 363, 'min_data_in_leaf': 65, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.4737335188474269, 'min_gain_to_split': 0.194521575466689}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:57:27,395] Trial 484 finished with value: 120.00165985189619 and parameters: {'num_leaves': 22, 'learning_rate': 0.13217836999631924, 'feature_fraction': 0.6080622531447984, 'bagging_fraction': 0.9247410055383966, 'bagging_freq': 9, 'lambda_l1': 3.068916253599455e-05, 'lambda_l2': 0.014647414996473013, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 477, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.9060462206456478, 'min_gain_to_split': 0.030128348521184387}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:58:14,069] Trial 485 finished with value: 141.38026516359665 and parameters: {'num_leaves': 16, 'learning_rate': 0.09849457473560254, 'feature_fraction': 0.6453041649795614, 'bagging_fraction': 0.9731055287225948, 'bagging_freq': 8, 'lambda_l1': 0.0007610242756053315, 'lambda_l2': 0.12090647614283033, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 389, 'min_data_in_leaf': 66, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.5149194756211909, 'min_gain_to_split': 0.01881728617451487}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:58:54,846] Trial 486 finished with value: 128.23601643140805 and parameters: {'num_leaves': 19, 'learning_rate': 0.10679728417328904, 'feature_fraction': 0.7882684735421993, 'bagging_fraction': 0.9589835502868543, 'bagging_freq': 10, 'lambda_l1': 6.41572038089048e-05, 'lambda_l2': 0.005814379470414109, 'min_child_samples': 45, 'max_depth': 10, 'max_bin': 330, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 23, 'path_smooth': 0.9548607397487104, 'min_gain_to_split': 0.0503717095280207}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 22:59:47,353] Trial 487 finished with value: 140.49599834954103 and parameters: {'num_leaves': 17, 'learning_rate': 0.08190989224128951, 'feature_fraction': 0.631387531683814, 'bagging_fraction': 0.9788762048130839, 'bagging_freq': 10, 'lambda_l1': 1.3259856010682029e-05, 'lambda_l2': 0.0319078750105886, 'min_child_samples': 41, 'max_depth': 10, 'max_bin': 201, 'min_data_in_leaf': 71, 'extra_trees': True, 'early_stopping_rounds': 22, 'path_smooth': 0.421271352263502, 'min_gain_to_split': 0.06652596471039511}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:00:42,352] Trial 488 finished with value: 141.7087602126177 and parameters: {'num_leaves': 21, 'learning_rate': 0.1219378232768533, 'feature_fraction': 0.6665133118144759, 'bagging_fraction': 0.8926990949623934, 'bagging_freq': 9, 'lambda_l1': 2.1133772288294557e-06, 'lambda_l2': 0.3012111291118841, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 500, 'min_data_in_leaf': 68, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.9270197841724437, 'min_gain_to_split': 0.25690067006876116}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:01:35,275] Trial 489 finished with value: 114.94584610497421 and parameters: {'num_leaves': 65, 'learning_rate': 0.11297672088694151, 'feature_fraction': 0.677462845627266, 'bagging_fraction': 0.9550795867913906, 'bagging_freq': 10, 'lambda_l1': 9.157594529865136e-08, 'lambda_l2': 0.021093265159126188, 'min_child_samples': 46, 'max_depth': 10, 'max_bin': 372, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 36, 'path_smooth': 0.452638515085111, 'min_gain_to_split': 0.15363517536070917}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:02:22,108] Trial 490 finished with value: 119.2311030277948 and parameters: {'num_leaves': 27, 'learning_rate': 0.052599507309667046, 'feature_fraction': 0.8893803273740598, 'bagging_fraction': 0.8675006962006255, 'bagging_freq': 10, 'lambda_l1': 2.2852404005580828e-05, 'lambda_l2': 0.0843690833175306, 'min_child_samples': 47, 'max_depth': 10, 'max_bin': 153, 'min_data_in_leaf': 40, 'extra_trees': True, 'early_stopping_rounds': 32, 'path_smooth': 0.3598049055956557, 'min_gain_to_split': 0.36833177795738986}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:03:11,553] Trial 491 finished with value: 142.16217546826357 and parameters: {'num_leaves': 21, 'learning_rate': 0.09156933505073427, 'feature_fraction': 0.6849602840537943, 'bagging_fraction': 0.9134973264887839, 'bagging_freq': 10, 'lambda_l1': 4.811733295422373e-06, 'lambda_l2': 0.008575930031109099, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 303, 'min_data_in_leaf': 73, 'extra_trees': True, 'early_stopping_rounds': 30, 'path_smooth': 0.9712943586410123, 'min_gain_to_split': 0.0372938403895055}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:04:00,185] Trial 492 finished with value: 112.70976275417215 and parameters: {'num_leaves': 62, 'learning_rate': 0.2046062110993128, 'feature_fraction': 0.6556536884868718, 'bagging_fraction': 0.9686788101763989, 'bagging_freq': 9, 'lambda_l1': 4.116062900176078e-07, 'lambda_l2': 0.04762616336239015, 'min_child_samples': 40, 'max_depth': 10, 'max_bin': 470, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.4330998519622277, 'min_gain_to_split': 0.326546395794437}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:04:51,674] Trial 493 finished with value: 106.19533663059431 and parameters: {'num_leaves': 19, 'learning_rate': 0.15797512969943087, 'feature_fraction': 0.6166312365347145, 'bagging_fraction': 0.9484902682836426, 'bagging_freq': 10, 'lambda_l1': 2.3679320245848055e-07, 'lambda_l2': 0.014873122079756513, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 480, 'min_data_in_leaf': 27, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.386993120741829, 'min_gain_to_split': 0.00726016694600504}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:05:41,147] Trial 494 finished with value: 130.15008369382204 and parameters: {'num_leaves': 23, 'learning_rate': 0.13822313111701529, 'feature_fraction': 0.6390885662338981, 'bagging_fraction': 0.9297337443054083, 'bagging_freq': 10, 'lambda_l1': 1.0439100397430513e-05, 'lambda_l2': 0.026362750784002142, 'min_child_samples': 42, 'max_depth': 10, 'max_bin': 343, 'min_data_in_leaf': 62, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.49311832895345165, 'min_gain_to_split': 0.2993159974571669}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:06:32,963] Trial 495 finished with value: 140.30877321030573 and parameters: {'num_leaves': 26, 'learning_rate': 0.12703443009551957, 'feature_fraction': 0.6487456239176211, 'bagging_fraction': 0.9379855645006512, 'bagging_freq': 8, 'lambda_l1': 3.0440767096329847e-06, 'lambda_l2': 0.013628874966114491, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 357, 'min_data_in_leaf': 67, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.9347350180309824, 'min_gain_to_split': 0.28200617261889493}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:07:30,057] Trial 496 finished with value: 133.13878323855948 and parameters: {'num_leaves': 15, 'learning_rate': 0.10246296631084449, 'feature_fraction': 0.8445008775991341, 'bagging_fraction': 0.9623787161024352, 'bagging_freq': 10, 'lambda_l1': 1.4047806081156186e-06, 'lambda_l2': 0.057921917021859906, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 449, 'min_data_in_leaf': 52, 'extra_trees': True, 'early_stopping_rounds': 19, 'path_smooth': 0.4048513216653087, 'min_gain_to_split': 0.0955900665702573}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:08:20,928] Trial 497 finished with value: 119.81218795791025 and parameters: {'num_leaves': 17, 'learning_rate': 0.11206258472119536, 'feature_fraction': 0.7270532895750583, 'bagging_fraction': 0.9740767303256659, 'bagging_freq': 10, 'lambda_l1': 0.00016372290784810855, 'lambda_l2': 0.007836512310684557, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 490, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.889308508065307, 'min_gain_to_split': 0.31567270374669426}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:09:17,897] Trial 498 finished with value: 142.46510047849796 and parameters: {'num_leaves': 20, 'learning_rate': 0.15010499749816286, 'feature_fraction': 0.6634087075175236, 'bagging_fraction': 0.9877527894838792, 'bagging_freq': 10, 'lambda_l1': 7.495713427940419e-07, 'lambda_l2': 0.02016504013495006, 'min_child_samples': 44, 'max_depth': 10, 'max_bin': 463, 'min_data_in_leaf': 65, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.9884559492786571, 'min_gain_to_split': 0.023317972569350077}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:09:55,061] Trial 499 finished with value: 117.7749837407845 and parameters: {'num_leaves': 24, 'learning_rate': 0.09695067696543573, 'feature_fraction': 0.671752645514514, 'bagging_fraction': 0.8481578489990945, 'bagging_freq': 10, 'lambda_l1': 0.0030311811763039207, 'lambda_l2': 0.03449833742182005, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 127, 'min_data_in_leaf': 32, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9603522800157692, 'min_gain_to_split': 0.04683187137149227}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:10:43,708] Trial 500 finished with value: 139.7630614382093 and parameters: {'num_leaves': 18, 'learning_rate': 0.11823460510530943, 'feature_fraction': 0.7625414667578678, 'bagging_fraction': 0.9191076206394894, 'bagging_freq': 7, 'lambda_l1': 4.010978320843179e-05, 'lambda_l2': 0.004377799497023637, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 381, 'min_data_in_leaf': 69, 'extra_trees': True, 'early_stopping_rounds': 31, 'path_smooth': 0.9138077898336275, 'min_gain_to_split': 0.034959119547775946}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:11:50,692] Trial 501 finished with value: 119.25209532778399 and parameters: {'num_leaves': 22, 'learning_rate': 0.06296816043654352, 'feature_fraction': 0.6261526640080903, 'bagging_fraction': 0.9559072346207061, 'bagging_freq': 9, 'lambda_l1': 5.99338738401525e-06, 'lambda_l2': 0.15060553950581115, 'min_child_samples': 45, 'max_depth': 9, 'max_bin': 364, 'min_data_in_leaf': 42, 'extra_trees': False, 'early_stopping_rounds': 34, 'path_smooth': 0.6920023738021667, 'min_gain_to_split': 0.27078990179352014}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:12:27,362] Trial 502 finished with value: 124.09035564209712 and parameters: {'num_leaves': 25, 'learning_rate': 0.10602747146139697, 'feature_fraction': 0.6567710433186392, 'bagging_fraction': 0.9456552975640073, 'bagging_freq': 10, 'lambda_l1': 2.0978680653182147e-05, 'lambda_l2': 0.09630324332747241, 'min_child_samples': 47, 'max_depth': 3, 'max_bin': 421, 'min_data_in_leaf': 40, 'extra_trees': True, 'early_stopping_rounds': 12, 'path_smooth': 0.45531082118889143, 'min_gain_to_split': 0.12989764191359424}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:13:12,545] Trial 503 finished with value: 126.15934918114742 and parameters: {'num_leaves': 20, 'learning_rate': 0.16982651055352646, 'feature_fraction': 0.6375430829076661, 'bagging_fraction': 0.9674979079575013, 'bagging_freq': 10, 'lambda_l1': 1.1237480666743506e-05, 'lambda_l2': 0.00944129837263662, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 481, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 33, 'path_smooth': 0.9463014797334395, 'min_gain_to_split': 0.013059905064040367}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:13:54,066] Trial 504 finished with value: 138.03717485738338 and parameters: {'num_leaves': 17, 'learning_rate': 0.1319157459044597, 'feature_fraction': 0.6920852218519252, 'bagging_fraction': 0.7693217544208913, 'bagging_freq': 1, 'lambda_l1': 1.3914486882529813e-07, 'lambda_l2': 0.016832831261409796, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 336, 'min_data_in_leaf': 58, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.4382748544090928, 'min_gain_to_split': 0.02533638054697685}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:14:47,754] Trial 505 finished with value: 142.37924345419424 and parameters: {'num_leaves': 30, 'learning_rate': 0.09162638114869047, 'feature_fraction': 0.6485133417731807, 'bagging_fraction': 0.9771361752816139, 'bagging_freq': 10, 'lambda_l1': 2.4521919230308354e-08, 'lambda_l2': 0.032653434782622594, 'min_child_samples': 47, 'max_depth': 10, 'max_bin': 352, 'min_data_in_leaf': 95, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.32175926698019225, 'min_gain_to_split': 0.2377404035376243}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:15:21,536] Trial 506 finished with value: 136.3386571676413 and parameters: {'num_leaves': 22, 'learning_rate': 0.1909245619430116, 'feature_fraction': 0.6641313950079444, 'bagging_fraction': 0.9826660233805713, 'bagging_freq': 9, 'lambda_l1': 2.001546549135708e-06, 'lambda_l2': 0.050549978579133265, 'min_child_samples': 46, 'max_depth': 10, 'max_bin': 165, 'min_data_in_leaf': 64, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.4197716698496704, 'min_gain_to_split': 0.3069916428579275}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:16:00,450] Trial 507 finished with value: 144.56697674214826 and parameters: {'num_leaves': 19, 'learning_rate': 0.12480636781827179, 'feature_fraction': 0.7049978006737891, 'bagging_fraction': 0.9085188569794878, 'bagging_freq': 10, 'lambda_l1': 0.00010767324009304871, 'lambda_l2': 0.011979937209529052, 'min_child_samples': 31, 'max_depth': 10, 'max_bin': 235, 'min_data_in_leaf': 66, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.36922724092948045, 'min_gain_to_split': 0.3334906392349497}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:16:58,236] Trial 508 finished with value: 112.51767963111872 and parameters: {'num_leaves': 70, 'learning_rate': 0.11658119424496186, 'feature_fraction': 0.6808051547363506, 'bagging_fraction': 0.9513788258774771, 'bagging_freq': 10, 'lambda_l1': 3.6708975993455917e-06, 'lambda_l2': 0.005663806064394261, 'min_child_samples': 45, 'max_depth': 10, 'max_bin': 488, 'min_data_in_leaf': 22, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.9825813303402611, 'min_gain_to_split': 0.05557422433515189}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:17:53,460] Trial 509 finished with value: 128.11117471843687 and parameters: {'num_leaves': 28, 'learning_rate': 0.1012080287492598, 'feature_fraction': 0.6429299333388182, 'bagging_fraction': 0.8977324768455905, 'bagging_freq': 9, 'lambda_l1': 1.6083131754875444e-05, 'lambda_l2': 0.0751162300241548, 'min_child_samples': 24, 'max_depth': 10, 'max_bin': 474, 'min_data_in_leaf': 55, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.9350996976427939, 'min_gain_to_split': 0.39452732892143894}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:18:32,152] Trial 510 finished with value: 120.47524369708269 and parameters: {'num_leaves': 16, 'learning_rate': 0.14178087319135996, 'feature_fraction': 0.6562857450169857, 'bagging_fraction': 0.8341004678801016, 'bagging_freq': 8, 'lambda_l1': 0.00027380207842996605, 'lambda_l2': 0.018711725363954584, 'min_child_samples': 49, 'max_depth': 4, 'max_bin': 368, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.4757768681313945, 'min_gain_to_split': 0.0012264252143175346}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:19:24,839] Trial 511 finished with value: 142.6728184732689 and parameters: {'num_leaves': 23, 'learning_rate': 0.10843638958983884, 'feature_fraction': 0.857305277881487, 'bagging_fraction': 0.9629993063029106, 'bagging_freq': 10, 'lambda_l1': 1.0095951189128581e-06, 'lambda_l2': 0.02603587010346364, 'min_child_samples': 44, 'max_depth': 10, 'max_bin': 376, 'min_data_in_leaf': 70, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.967863539248958, 'min_gain_to_split': 0.07591308792520281}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:20:08,140] Trial 512 finished with value: 119.90254734348305 and parameters: {'num_leaves': 18, 'learning_rate': 0.07962267098813781, 'feature_fraction': 0.6715535879621894, 'bagging_fraction': 0.9326483092015676, 'bagging_freq': 5, 'lambda_l1': 4.638145074205535e-07, 'lambda_l2': 0.011483780953900562, 'min_child_samples': 50, 'max_depth': 6, 'max_bin': 326, 'min_data_in_leaf': 33, 'extra_trees': True, 'early_stopping_rounds': 30, 'path_smooth': 0.4055463369398839, 'min_gain_to_split': 0.043446884147395}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:20:44,595] Trial 513 finished with value: 137.3499453528688 and parameters: {'num_leaves': 21, 'learning_rate': 0.15261092672945137, 'feature_fraction': 0.6357539980906286, 'bagging_fraction': 0.9438074749944492, 'bagging_freq': 10, 'lambda_l1': 6.456316028233234e-06, 'lambda_l2': 0.0023913285885442037, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 177, 'min_data_in_leaf': 67, 'extra_trees': True, 'early_stopping_rounds': 23, 'path_smooth': 0.9008869335412487, 'min_gain_to_split': 0.015353319474035914}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:21:33,136] Trial 514 finished with value: 119.25772886841487 and parameters: {'num_leaves': 15, 'learning_rate': 0.12286786967813301, 'feature_fraction': 0.649327091222765, 'bagging_fraction': 0.9225359139648204, 'bagging_freq': 10, 'lambda_l1': 4.670902126593765e-05, 'lambda_l2': 0.2151404247466173, 'min_child_samples': 42, 'max_depth': 10, 'max_bin': 494, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.8231200899043922, 'min_gain_to_split': 0.3210461268615489}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:22:37,237] Trial 515 finished with value: 134.94954123835714 and parameters: {'num_leaves': 20, 'learning_rate': 0.08756125496242055, 'feature_fraction': 0.6284684475708572, 'bagging_fraction': 0.9910477897840718, 'bagging_freq': 10, 'lambda_l1': 2.7294107652885274e-07, 'lambda_l2': 0.04574338608310265, 'min_child_samples': 46, 'max_depth': 10, 'max_bin': 500, 'min_data_in_leaf': 63, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.99839476674296, 'min_gain_to_split': 0.2924500405518141}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:23:21,094] Trial 516 finished with value: 143.31213684218048 and parameters: {'num_leaves': 26, 'learning_rate': 0.09757913481406524, 'feature_fraction': 0.6609404373895001, 'bagging_fraction': 0.9587122176347388, 'bagging_freq': 6, 'lambda_l1': 4.361978059582762e-08, 'lambda_l2': 0.007295669530148849, 'min_child_samples': 49, 'max_depth': 9, 'max_bin': 266, 'min_data_in_leaf': 61, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.441741259210466, 'min_gain_to_split': 0.025824046344394877}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:24:01,965] Trial 517 finished with value: 116.25716910754605 and parameters: {'num_leaves': 24, 'learning_rate': 0.13254415747992718, 'feature_fraction': 0.672428969877768, 'bagging_fraction': 0.9395776712587679, 'bagging_freq': 9, 'lambda_l1': 9.2373623789289e-06, 'lambda_l2': 0.02597247007828755, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 342, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.3859860803946712, 'min_gain_to_split': 0.16934387033081813}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:24:52,461] Trial 518 finished with value: 137.17402174565785 and parameters: {'num_leaves': 18, 'learning_rate': 0.11139124651506163, 'feature_fraction': 0.6461011917844238, 'bagging_fraction': 0.9722868472139897, 'bagging_freq': 10, 'lambda_l1': 2.4463130055259096e-05, 'lambda_l2': 0.11863814091207192, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 455, 'min_data_in_leaf': 68, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.34683880258956656, 'min_gain_to_split': 0.06029561040309597}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:25:46,627] Trial 519 finished with value: 123.81815353753314 and parameters: {'num_leaves': 22, 'learning_rate': 0.1042141601933804, 'feature_fraction': 0.6652643279539497, 'bagging_fraction': 0.9657153371972401, 'bagging_freq': 10, 'lambda_l1': 4.038746890725569e-06, 'lambda_l2': 0.0167778266259832, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 389, 'min_data_in_leaf': 46, 'extra_trees': True, 'early_stopping_rounds': 31, 'path_smooth': 0.9198083162493641, 'min_gain_to_split': 0.03285471143920157}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:27:06,716] Trial 520 finished with value: 116.71534731416412 and parameters: {'num_leaves': 19, 'learning_rate': 0.119539397395375, 'feature_fraction': 0.6779875409699538, 'bagging_fraction': 0.9530240130577472, 'bagging_freq': 10, 'lambda_l1': 1.7223965093119548e-06, 'lambda_l2': 0.06847163386179607, 'min_child_samples': 44, 'max_depth': 10, 'max_bin': 484, 'min_data_in_leaf': 35, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.9604560330867038, 'min_gain_to_split': 0.3124506142377382}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:27:47,128] Trial 521 finished with value: 105.88838579647445 and parameters: {'num_leaves': 21, 'learning_rate': 0.16221413196848508, 'feature_fraction': 0.6875877069162323, 'bagging_fraction': 0.9804228881400905, 'bagging_freq': 9, 'lambda_l1': 2.827897821812923e-06, 'lambda_l2': 0.03970024443188974, 'min_child_samples': 47, 'max_depth': 10, 'max_bin': 357, 'min_data_in_leaf': 29, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.4600030294347897, 'min_gain_to_split': 0.01755419881078276}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:28:18,034] Trial 522 finished with value: 109.81874845091178 and parameters: {'num_leaves': 17, 'learning_rate': 0.1428415937469779, 'feature_fraction': 0.6548873504403367, 'bagging_fraction': 0.9744847745170989, 'bagging_freq': 8, 'lambda_l1': 5.78577650164582e-07, 'lambda_l2': 0.009496157881519196, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 101, 'min_data_in_leaf': 24, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.41643472906491996, 'min_gain_to_split': 0.12204330189219292}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:29:07,225] Trial 523 finished with value: 146.97925904130233 and parameters: {'num_leaves': 41, 'learning_rate': 0.11234975168650976, 'feature_fraction': 0.6357117780680549, 'bagging_fraction': 0.9132542199273047, 'bagging_freq': 10, 'lambda_l1': 7.398500724859963e-08, 'lambda_l2': 0.005037470059039962, 'min_child_samples': 45, 'max_depth': 10, 'max_bin': 315, 'min_data_in_leaf': 72, 'extra_trees': True, 'early_stopping_rounds': 33, 'path_smooth': 0.9515252612451975, 'min_gain_to_split': 0.46646168204951466}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:30:02,252] Trial 524 finished with value: 138.57554175335176 and parameters: {'num_leaves': 24, 'learning_rate': 0.09495133512026184, 'feature_fraction': 0.6171942226984003, 'bagging_fraction': 0.8571416499827356, 'bagging_freq': 10, 'lambda_l1': 1.4291214211131713e-05, 'lambda_l2': 0.012880179001356172, 'min_child_samples': 48, 'max_depth': 9, 'max_bin': 473, 'min_data_in_leaf': 65, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.2500366617261869, 'min_gain_to_split': 0.26425385166033916}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:30:50,701] Trial 525 finished with value: 120.77050237689676 and parameters: {'num_leaves': 21, 'learning_rate': 0.13143459408868502, 'feature_fraction': 0.6416724967991619, 'bagging_fraction': 0.9274603500223647, 'bagging_freq': 10, 'lambda_l1': 7.618584720493793e-05, 'lambda_l2': 0.024418420301344036, 'min_child_samples': 41, 'max_depth': 10, 'max_bin': 370, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.9819747760218793, 'min_gain_to_split': 0.0002525661693386547}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:31:38,684] Trial 526 finished with value: 119.30084983924382 and parameters: {'num_leaves': 19, 'learning_rate': 0.10402652475110635, 'feature_fraction': 0.6621953840267027, 'bagging_fraction': 0.9573481921524635, 'bagging_freq': 9, 'lambda_l1': 7.797953008725739e-06, 'lambda_l2': 0.003528846630120718, 'min_child_samples': 36, 'max_depth': 10, 'max_bin': 480, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.63518174372499, 'min_gain_to_split': 0.04110547037864981}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:32:26,952] Trial 527 finished with value: 112.57084846802464 and parameters: {'num_leaves': 84, 'learning_rate': 0.12387295014623018, 'feature_fraction': 0.6517492768119705, 'bagging_fraction': 0.9676297075425188, 'bagging_freq': 10, 'lambda_l1': 1.115001149971913e-06, 'lambda_l2': 0.016491242716686068, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 463, 'min_data_in_leaf': 43, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.4954835513893116, 'min_gain_to_split': 0.2826814194598528}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:33:15,934] Trial 528 finished with value: 144.6717198007262 and parameters: {'num_leaves': 26, 'learning_rate': 0.11562632874269602, 'feature_fraction': 0.6965342270194795, 'bagging_fraction': 0.9031755084183734, 'bagging_freq': 8, 'lambda_l1': 2.9616848410594334e-05, 'lambda_l2': 0.034827607817634755, 'min_child_samples': 39, 'max_depth': 10, 'max_bin': 351, 'min_data_in_leaf': 67, 'extra_trees': True, 'early_stopping_rounds': 32, 'path_smooth': 0.4264375204530444, 'min_gain_to_split': 0.030028730059407094}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:33:58,180] Trial 529 finished with value: 121.59850860648407 and parameters: {'num_leaves': 15, 'learning_rate': 0.1741915870150612, 'feature_fraction': 0.6288559625004557, 'bagging_fraction': 0.9459006620300956, 'bagging_freq': 10, 'lambda_l1': 7.839022932717693e-07, 'lambda_l2': 0.0688029859594123, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 383, 'min_data_in_leaf': 41, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.8794600285632334, 'min_gain_to_split': 0.010108647184492614}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:34:56,342] Trial 530 finished with value: 144.7262729716846 and parameters: {'num_leaves': 23, 'learning_rate': 0.09104541478460013, 'feature_fraction': 0.6689736558493335, 'bagging_fraction': 0.9497916149019129, 'bagging_freq': 10, 'lambda_l1': 5.157737489847321e-06, 'lambda_l2': 0.006996491338710811, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 487, 'min_data_in_leaf': 69, 'extra_trees': True, 'early_stopping_rounds': 21, 'path_smooth': 0.9324343772621523, 'min_gain_to_split': 0.08779523553613922}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:36:15,987] Trial 531 finished with value: 141.46720217053524 and parameters: {'num_leaves': 17, 'learning_rate': 0.03672591683019048, 'feature_fraction': 0.6818117307354721, 'bagging_fraction': 0.9618800814977713, 'bagging_freq': 9, 'lambda_l1': 1.6726635419197877e-06, 'lambda_l2': 0.02129363736880899, 'min_child_samples': 47, 'max_depth': 10, 'max_bin': 361, 'min_data_in_leaf': 75, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.39767437290403973, 'min_gain_to_split': 0.32456368567758714}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:37:29,259] Trial 532 finished with value: 139.72764293675593 and parameters: {'num_leaves': 20, 'learning_rate': 0.10690635025375589, 'feature_fraction': 0.6600499193801119, 'bagging_fraction': 0.9370907599634114, 'bagging_freq': 10, 'lambda_l1': 1.828966066009552e-07, 'lambda_l2': 0.14333975914664895, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 471, 'min_data_in_leaf': 65, 'extra_trees': True, 'early_stopping_rounds': 30, 'path_smooth': 0.46323367640325197, 'min_gain_to_split': 0.04667259971034922}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:38:20,081] Trial 533 finished with value: 132.48119730373566 and parameters: {'num_leaves': 22, 'learning_rate': 0.13714026992501022, 'feature_fraction': 0.7170755127117274, 'bagging_fraction': 0.972654010888835, 'bagging_freq': 4, 'lambda_l1': 1.7659434822644743e-08, 'lambda_l2': 0.052467452059997345, 'min_child_samples': 46, 'max_depth': 8, 'max_bin': 331, 'min_data_in_leaf': 57, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.9985872799281946, 'min_gain_to_split': 0.3020779668699227}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:39:10,270] Trial 534 finished with value: 139.20757616845506 and parameters: {'num_leaves': 25, 'learning_rate': 0.1539079911810894, 'feature_fraction': 0.6457865331381093, 'bagging_fraction': 0.9803107734815202, 'bagging_freq': 10, 'lambda_l1': 1.990335622345565e-05, 'lambda_l2': 0.011184819567949101, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 344, 'min_data_in_leaf': 63, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.7161286086638794, 'min_gain_to_split': 0.10417920571838732}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:40:04,471] Trial 535 finished with value: 121.43726746494849 and parameters: {'num_leaves': 18, 'learning_rate': 0.07283856863193035, 'feature_fraction': 0.6544804051063482, 'bagging_fraction': 0.9179372781094322, 'bagging_freq': 3, 'lambda_l1': 1.1579213935200849e-05, 'lambda_l2': 6.854640476389763e-05, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 492, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.9112873082928947, 'min_gain_to_split': 0.03469545328265999}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:40:52,958] Trial 536 finished with value: 116.50243805967925 and parameters: {'num_leaves': 20, 'learning_rate': 0.09855251978110234, 'feature_fraction': 0.6721532132606913, 'bagging_fraction': 0.9868696209744747, 'bagging_freq': 10, 'lambda_l1': 4.1201113401823475e-07, 'lambda_l2': 0.03428192790040091, 'min_child_samples': 44, 'max_depth': 10, 'max_bin': 481, 'min_data_in_leaf': 31, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.376379943489088, 'min_gain_to_split': 0.13935395804582446}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:41:36,278] Trial 537 finished with value: 125.38505542529442 and parameters: {'num_leaves': 16, 'learning_rate': 0.12571467292935898, 'feature_fraction': 0.6223838813978562, 'bagging_fraction': 0.9954063458615504, 'bagging_freq': 10, 'lambda_l1': 0.00017895559912346577, 'lambda_l2': 0.014412114315726681, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 376, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.44105981533636435, 'min_gain_to_split': 0.34186776272242864}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:42:34,575] Trial 538 finished with value: 124.60225405279023 and parameters: {'num_leaves': 28, 'learning_rate': 0.11013766590230403, 'feature_fraction': 0.6385608454319837, 'bagging_fraction': 0.9555192688132716, 'bagging_freq': 9, 'lambda_l1': 2.614615886758683e-06, 'lambda_l2': 0.09529121041170625, 'min_child_samples': 46, 'max_depth': 10, 'max_bin': 362, 'min_data_in_leaf': 49, 'extra_trees': True, 'early_stopping_rounds': 35, 'path_smooth': 0.9466139044374555, 'min_gain_to_split': 0.019056038132965743}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:43:21,811] Trial 539 finished with value: 111.39476610978652 and parameters: {'num_leaves': 23, 'learning_rate': 0.11773964114591218, 'feature_fraction': 0.6325558695367052, 'bagging_fraction': 0.8624745371997077, 'bagging_freq': 7, 'lambda_l1': 6.8345902630510326e-06, 'lambda_l2': 0.7144731529665249, 'min_child_samples': 47, 'max_depth': 10, 'max_bin': 494, 'min_data_in_leaf': 20, 'extra_trees': True, 'early_stopping_rounds': 23, 'path_smooth': 0.9666422307865136, 'min_gain_to_split': 0.05103442221986318}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:44:20,947] Trial 540 finished with value: 123.49100100674289 and parameters: {'num_leaves': 19, 'learning_rate': 0.24226279292661076, 'feature_fraction': 0.6509054544234258, 'bagging_fraction': 0.9684715331839417, 'bagging_freq': 10, 'lambda_l1': 1.643375557539551e-05, 'lambda_l2': 0.007668652954918782, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 351, 'min_data_in_leaf': 71, 'extra_trees': False, 'early_stopping_rounds': 32, 'path_smooth': 0.419157839193278, 'min_gain_to_split': 0.31531107420762916}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:45:16,013] Trial 541 finished with value: 138.1428564916259 and parameters: {'num_leaves': 25, 'learning_rate': 0.08568717306519118, 'feature_fraction': 0.6688273443369157, 'bagging_fraction': 0.814503401834755, 'bagging_freq': 10, 'lambda_l1': 0.49556043849213627, 'lambda_l2': 0.019892509157933773, 'min_child_samples': 45, 'max_depth': 10, 'max_bin': 369, 'min_data_in_leaf': 60, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.9313071845533332, 'min_gain_to_split': 0.2945565132301848}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:46:17,027] Trial 542 finished with value: 137.49922219145077 and parameters: {'num_leaves': 22, 'learning_rate': 0.10082635772787393, 'feature_fraction': 0.6426384387136594, 'bagging_fraction': 0.9613698503636572, 'bagging_freq': 10, 'lambda_l1': 1.0070383067286117e-08, 'lambda_l2': 0.026599051261968785, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 395, 'min_data_in_leaf': 68, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.5710666720761685, 'min_gain_to_split': 0.02495020981836921}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:47:07,206] Trial 543 finished with value: 139.99872114788803 and parameters: {'num_leaves': 17, 'learning_rate': 0.14416098933636093, 'feature_fraction': 0.686269643805597, 'bagging_fraction': 0.8533707190026006, 'bagging_freq': 9, 'lambda_l1': 4.1187668741378257e-05, 'lambda_l2': 0.010520586749013756, 'min_child_samples': 38, 'max_depth': 10, 'max_bin': 475, 'min_data_in_leaf': 66, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.4791698880227313, 'min_gain_to_split': 0.03784128562789487}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:47:46,463] Trial 544 finished with value: 113.23170666278722 and parameters: {'num_leaves': 49, 'learning_rate': 0.13207375012045672, 'feature_fraction': 0.6577683460441983, 'bagging_fraction': 0.9421568100666649, 'bagging_freq': 10, 'lambda_l1': 4.5160753389808734e-06, 'lambda_l2': 0.04675035127373063, 'min_child_samples': 48, 'max_depth': 5, 'max_bin': 322, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.8587432099164946, 'min_gain_to_split': 0.27129506202013953}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:48:28,146] Trial 545 finished with value: 112.67236072075691 and parameters: {'num_leaves': 21, 'learning_rate': 0.11637271490517334, 'feature_fraction': 0.6781841843637301, 'bagging_fraction': 0.9487325677909371, 'bagging_freq': 10, 'lambda_l1': 3.161960596919177e-07, 'lambda_l2': 0.004834420789825621, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 337, 'min_data_in_leaf': 40, 'extra_trees': True, 'early_stopping_rounds': 30, 'path_smooth': 0.524342158253658, 'min_gain_to_split': 0.2569390173769171}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:49:10,956] Trial 546 finished with value: 118.87780557311912 and parameters: {'num_leaves': 15, 'learning_rate': 0.09456031692909397, 'feature_fraction': 0.6616443278505991, 'bagging_fraction': 0.9222608233533194, 'bagging_freq': 10, 'lambda_l1': 1.0975122988124173e-06, 'lambda_l2': 0.015304197989736043, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 409, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 33, 'path_smooth': 0.4045383870891012, 'min_gain_to_split': 0.061546100320223535}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:50:04,436] Trial 547 finished with value: 140.567891642201 and parameters: {'num_leaves': 19, 'learning_rate': 0.10465959141757854, 'feature_fraction': 0.6093125015384399, 'bagging_fraction': 0.9771786211106681, 'bagging_freq': 10, 'lambda_l1': 3.049674990216775e-08, 'lambda_l2': 0.02810131752195186, 'min_child_samples': 44, 'max_depth': 10, 'max_bin': 464, 'min_data_in_leaf': 53, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.7551116187186295, 'min_gain_to_split': 0.3304674424913306}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:50:54,341] Trial 548 finished with value: 141.88989655799386 and parameters: {'num_leaves': 59, 'learning_rate': 0.15667220774452045, 'feature_fraction': 0.6479456603942476, 'bagging_fraction': 0.9327299783736684, 'bagging_freq': 9, 'lambda_l1': 6.119538077258224e-07, 'lambda_l2': 0.07372958047296943, 'min_child_samples': 42, 'max_depth': 10, 'max_bin': 500, 'min_data_in_leaf': 64, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.9764902703615614, 'min_gain_to_split': 0.3055975874245528}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:51:53,404] Trial 549 finished with value: 143.92386750564864 and parameters: {'num_leaves': 35, 'learning_rate': 0.11170556555745818, 'feature_fraction': 0.8183306334010025, 'bagging_fraction': 0.9080612488390377, 'bagging_freq': 10, 'lambda_l1': 8.990559964510467e-06, 'lambda_l2': 0.20986178547793893, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 486, 'min_data_in_leaf': 70, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.9000409324270531, 'min_gain_to_split': 0.01616614459250087}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:52:46,440] Trial 550 finished with value: 113.85769121274889 and parameters: {'num_leaves': 24, 'learning_rate': 0.12365712255246303, 'feature_fraction': 0.6314895136353432, 'bagging_fraction': 0.9535603857431842, 'bagging_freq': 7, 'lambda_l1': 2.2972832379058243e-06, 'lambda_l2': 0.008954892540294017, 'min_child_samples': 47, 'max_depth': 10, 'max_bin': 482, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 31, 'path_smooth': 0.4392216895798742, 'min_gain_to_split': 0.2837487644397224}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:53:37,487] Trial 551 finished with value: 148.46616293950677 and parameters: {'num_leaves': 18, 'learning_rate': 0.1468442641691208, 'feature_fraction': 0.667379247314607, 'bagging_fraction': 0.9654674512672224, 'bagging_freq': 8, 'lambda_l1': 3.7056291617319105e-06, 'lambda_l2': 0.04239049557428338, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 380, 'min_data_in_leaf': 67, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.9442580061666932, 'min_gain_to_split': 0.009486617030793863}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:54:36,972] Trial 552 finished with value: 142.95198966984398 and parameters: {'num_leaves': 27, 'learning_rate': 0.0970533072289705, 'feature_fraction': 0.7770427777561663, 'bagging_fraction': 0.9830199707769248, 'bagging_freq': 10, 'lambda_l1': 2.848888254973229e-05, 'lambda_l2': 0.11508741295032247, 'min_child_samples': 18, 'max_depth': 10, 'max_bin': 358, 'min_data_in_leaf': 100, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.9619475560085327, 'min_gain_to_split': 0.2482891188754848}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:55:36,532] Trial 553 finished with value: 137.81875841720935 and parameters: {'num_leaves': 21, 'learning_rate': 0.08909716133470082, 'feature_fraction': 0.6403892129663689, 'bagging_fraction': 0.9582731716255578, 'bagging_freq': 10, 'lambda_l1': 0.000366072035843524, 'lambda_l2': 0.019186682428128356, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 468, 'min_data_in_leaf': 62, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.4677416117149315, 'min_gain_to_split': 0.071624846931609}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:56:22,772] Trial 554 finished with value: 111.15896683398167 and parameters: {'num_leaves': 23, 'learning_rate': 0.1378964548088725, 'feature_fraction': 0.6564186244935726, 'bagging_fraction': 0.7395158514535581, 'bagging_freq': 9, 'lambda_l1': 6.710873286286994e-05, 'lambda_l2': 0.4283546732096894, 'min_child_samples': 46, 'max_depth': 10, 'max_bin': 490, 'min_data_in_leaf': 28, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.38459664804413696, 'min_gain_to_split': 0.027695346162205807}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:57:08,638] Trial 555 finished with value: 123.95212729161264 and parameters: {'num_leaves': 17, 'learning_rate': 0.1076331965907826, 'feature_fraction': 0.6759136532434122, 'bagging_fraction': 0.8430124499912408, 'bagging_freq': 8, 'lambda_l1': 9.919021337239988e-08, 'lambda_l2': 0.005821417981661302, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 368, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.42675416241841496, 'min_gain_to_split': 0.04594230578033198}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:57:51,778] Trial 556 finished with value: 137.66624231070918 and parameters: {'num_leaves': 20, 'learning_rate': 0.17827813862354744, 'feature_fraction': 0.6500399450822252, 'bagging_fraction': 0.972952138646182, 'bagging_freq': 10, 'lambda_l1': 1.4343098285303073e-06, 'lambda_l2': 0.013604378387053636, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 346, 'min_data_in_leaf': 55, 'extra_trees': True, 'early_stopping_rounds': 34, 'path_smooth': 0.9263150083126638, 'min_gain_to_split': 0.03259433470837577}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:58:39,265] Trial 557 finished with value: 121.30384848472958 and parameters: {'num_leaves': 25, 'learning_rate': 0.12835217341634578, 'feature_fraction': 0.6256429140547016, 'bagging_fraction': 0.887036713447525, 'bagging_freq': 10, 'lambda_l1': 1.4074867613098893e-05, 'lambda_l2': 0.031282140569293564, 'min_child_samples': 40, 'max_depth': 9, 'max_bin': 477, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.35649422667486735, 'min_gain_to_split': 0.3224173590792193}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-13 23:59:25,579] Trial 558 finished with value: 117.33070133547979 and parameters: {'num_leaves': 16, 'learning_rate': 0.11701384947974881, 'feature_fraction': 0.6628332949852371, 'bagging_fraction': 0.9419046237732855, 'bagging_freq': 10, 'lambda_l1': 6.842040027598381e-06, 'lambda_l2': 0.07359649689696604, 'min_child_samples': 47, 'max_depth': 10, 'max_bin': 284, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.44759592098527995, 'min_gain_to_split': 0.3505716877017456}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:00:51,001] Trial 559 finished with value: 112.55753196949249 and parameters: {'num_leaves': 22, 'learning_rate': 0.01655106007023389, 'feature_fraction': 0.6891586876510283, 'bagging_fraction': 0.9281592959896924, 'bagging_freq': 9, 'lambda_l1': 6.953153622744171e-07, 'lambda_l2': 0.022792007200835768, 'min_child_samples': 29, 'max_depth': 9, 'max_bin': 337, 'min_data_in_leaf': 25, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.9737348400517234, 'min_gain_to_split': 0.018070303895912732}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:01:34,766] Trial 560 finished with value: 139.9809958912228 and parameters: {'num_leaves': 29, 'learning_rate': 0.16741960992509256, 'feature_fraction': 0.6409532527263688, 'bagging_fraction': 0.9685677952353485, 'bagging_freq': 10, 'lambda_l1': 1.5461691732421033e-07, 'lambda_l2': 0.010188593084634871, 'min_child_samples': 45, 'max_depth': 10, 'max_bin': 308, 'min_data_in_leaf': 65, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.9458035748395787, 'min_gain_to_split': 0.295022233999403}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:02:44,998] Trial 561 finished with value: 143.00531719928264 and parameters: {'num_leaves': 18, 'learning_rate': 0.0812513988520111, 'feature_fraction': 0.670665020474593, 'bagging_fraction': 0.9490237696259152, 'bagging_freq': 10, 'lambda_l1': 2.061794938702704e-05, 'lambda_l2': 0.002881796577756407, 'min_child_samples': 44, 'max_depth': 10, 'max_bin': 456, 'min_data_in_leaf': 68, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.4076378411519425, 'min_gain_to_split': 0.42606261629598197}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:03:28,693] Trial 562 finished with value: 124.48320581165413 and parameters: {'num_leaves': 19, 'learning_rate': 0.10299441641090684, 'feature_fraction': 0.653908709639843, 'bagging_fraction': 0.988068723751906, 'bagging_freq': 10, 'lambda_l1': 2.639693564922099e-07, 'lambda_l2': 0.05008878065994851, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 387, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 22, 'path_smooth': 0.9122869227352244, 'min_gain_to_split': 0.3110628009501617}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:04:19,074] Trial 563 finished with value: 120.7574813262848 and parameters: {'num_leaves': 24, 'learning_rate': 0.11155459995112744, 'feature_fraction': 0.6972736608865815, 'bagging_fraction': 0.9164747792204584, 'bagging_freq': 9, 'lambda_l1': 2.3292265791702494e-06, 'lambda_l2': 0.01603256992393075, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 494, 'min_data_in_leaf': 41, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.9833009728050224, 'min_gain_to_split': 0.039399262252696174}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:05:05,925] Trial 564 finished with value: 137.15570789349567 and parameters: {'num_leaves': 21, 'learning_rate': 0.12443563460935458, 'feature_fraction': 0.6169347009264585, 'bagging_fraction': 0.9024611187805922, 'bagging_freq': 10, 'lambda_l1': 0.0001362345480638977, 'lambda_l2': 0.006961567627092649, 'min_child_samples': 42, 'max_depth': 7, 'max_bin': 373, 'min_data_in_leaf': 66, 'extra_trees': True, 'early_stopping_rounds': 33, 'path_smooth': 0.502792680341972, 'min_gain_to_split': 0.009183520299733159}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:05:54,394] Trial 565 finished with value: 121.2868599698345 and parameters: {'num_leaves': 15, 'learning_rate': 0.09523617283516429, 'feature_fraction': 0.9234769242205108, 'bagging_fraction': 0.9595766167755786, 'bagging_freq': 5, 'lambda_l1': 9.48626094930297e-06, 'lambda_l2': 0.03191133960211777, 'min_child_samples': 45, 'max_depth': 10, 'max_bin': 356, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.4560771627241572, 'min_gain_to_split': 0.0268114266932032}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:06:51,721] Trial 566 finished with value: 133.7106616879319 and parameters: {'num_leaves': 26, 'learning_rate': 0.1374636886247349, 'feature_fraction': 0.798978003340711, 'bagging_fraction': 0.9774555715439818, 'bagging_freq': 8, 'lambda_l1': 4.655918526362468e-06, 'lambda_l2': 0.14068205082228968, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 486, 'min_data_in_leaf': 59, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.9557047887230339, 'min_gain_to_split': 0.05067124671619198}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:07:40,237] Trial 567 finished with value: 109.65062925704456 and parameters: {'num_leaves': 19, 'learning_rate': 0.10721867750321815, 'feature_fraction': 0.6357519492054687, 'bagging_fraction': 0.9366354841517471, 'bagging_freq': 10, 'lambda_l1': 1.0131367011301232e-06, 'lambda_l2': 0.011614335382644739, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 471, 'min_data_in_leaf': 23, 'extra_trees': True, 'early_stopping_rounds': 30, 'path_smooth': 0.296124731766318, 'min_gain_to_split': 0.1112561973140155}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:08:34,931] Trial 568 finished with value: 126.00415714016319 and parameters: {'num_leaves': 23, 'learning_rate': 0.10050461243697772, 'feature_fraction': 0.6462299426752116, 'bagging_fraction': 0.9641304524946277, 'bagging_freq': 10, 'lambda_l1': 3.332861227532639e-06, 'lambda_l2': 0.05690373311553102, 'min_child_samples': 47, 'max_depth': 10, 'max_bin': 482, 'min_data_in_leaf': 51, 'extra_trees': True, 'early_stopping_rounds': 31, 'path_smooth': 0.4287176848915156, 'min_gain_to_split': 0.2776478821062404}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:09:21,538] Trial 569 finished with value: 115.13284542432375 and parameters: {'num_leaves': 20, 'learning_rate': 0.14928227685106638, 'feature_fraction': 0.6626067859433826, 'bagging_fraction': 0.9524273331167902, 'bagging_freq': 10, 'lambda_l1': 4.4419959939359175e-07, 'lambda_l2': 0.018746130793691595, 'min_child_samples': 44, 'max_depth': 10, 'max_bin': 362, 'min_data_in_leaf': 43, 'extra_trees': True, 'early_stopping_rounds': 23, 'path_smooth': 0.05410834020089772, 'min_gain_to_split': 0.33231938408261313}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:10:43,732] Trial 570 finished with value: 142.02126110793853 and parameters: {'num_leaves': 17, 'learning_rate': 0.02720611864658978, 'feature_fraction': 0.6805066106451761, 'bagging_fraction': 0.9104060653433206, 'bagging_freq': 10, 'lambda_l1': 4.880870628134684e-05, 'lambda_l2': 0.0016421267147604145, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 329, 'min_data_in_leaf': 70, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.8841116508900052, 'min_gain_to_split': 0.023412573194125274}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:11:30,842] Trial 571 finished with value: 126.84574389034279 and parameters: {'num_leaves': 22, 'learning_rate': 0.11857967729955204, 'feature_fraction': 0.6526697318892951, 'bagging_fraction': 0.9708414861203942, 'bagging_freq': 9, 'lambda_l1': 1.3298233395981812e-05, 'lambda_l2': 0.004366949774565429, 'min_child_samples': 46, 'max_depth': 10, 'max_bin': 345, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 35, 'path_smooth': 0.9963803405553621, 'min_gain_to_split': 0.03557112622848488}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:12:20,879] Trial 572 finished with value: 137.03307450224753 and parameters: {'num_leaves': 18, 'learning_rate': 0.160704615371696, 'feature_fraction': 0.6721920981311821, 'bagging_fraction': 0.8760280550178516, 'bagging_freq': 10, 'lambda_l1': 3.5497102340853635e-05, 'lambda_l2': 0.03829488439937658, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 500, 'min_data_in_leaf': 63, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.7738045346764927, 'min_gain_to_split': 0.26364136307332464}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:13:25,002] Trial 573 finished with value: 142.21746617690476 and parameters: {'num_leaves': 32, 'learning_rate': 0.08797417552235673, 'feature_fraction': 0.6015923926456792, 'bagging_fraction': 0.8266901747573256, 'bagging_freq': 2, 'lambda_l1': 1.9420834606632426e-06, 'lambda_l2': 0.02385343530447436, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 489, 'min_data_in_leaf': 69, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.6133955808837585, 'min_gain_to_split': 0.06214837028025773}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:14:07,795] Trial 574 finished with value: 121.74656754468046 and parameters: {'num_leaves': 21, 'learning_rate': 0.12558562966179324, 'feature_fraction': 0.6233444774615512, 'bagging_fraction': 0.981344891963271, 'bagging_freq': 9, 'lambda_l1': 5.6786486172198654e-08, 'lambda_l2': 0.09161824280934491, 'min_child_samples': 34, 'max_depth': 10, 'max_bin': 376, 'min_data_in_leaf': 31, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.39679092455538434, 'min_gain_to_split': 0.30462531876040116}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:15:00,919] Trial 575 finished with value: 143.74183969092908 and parameters: {'num_leaves': 26, 'learning_rate': 0.11463579425799114, 'feature_fraction': 0.6613379307847082, 'bagging_fraction': 0.8965082699046987, 'bagging_freq': 10, 'lambda_l1': 6.586945900318908e-06, 'lambda_l2': 0.007176289615490924, 'min_child_samples': 41, 'max_depth': 10, 'max_bin': 477, 'min_data_in_leaf': 67, 'extra_trees': True, 'early_stopping_rounds': 32, 'path_smooth': 0.908534711569818, 'min_gain_to_split': 0.3166655421545642}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:15:46,471] Trial 576 finished with value: 138.1608416710293 and parameters: {'num_leaves': 16, 'learning_rate': 0.13477775042051734, 'feature_fraction': 0.9639118706456099, 'bagging_fraction': 0.9569447364831221, 'bagging_freq': 10, 'lambda_l1': 2.1806176698499356e-05, 'lambda_l2': 0.010001130292666631, 'min_child_samples': 47, 'max_depth': 10, 'max_bin': 366, 'min_data_in_leaf': 57, 'extra_trees': True, 'early_stopping_rounds': 34, 'path_smooth': 0.4862644311813063, 'min_gain_to_split': 0.008993153325715639}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:16:30,237] Trial 577 finished with value: 135.78194710045153 and parameters: {'num_leaves': 24, 'learning_rate': 0.1046870185495648, 'feature_fraction': 0.6443659801415957, 'bagging_fraction': 0.9443048091677935, 'bagging_freq': 10, 'lambda_l1': 9.454849731694308e-05, 'lambda_l2': 0.014773819195234886, 'min_child_samples': 44, 'max_depth': 10, 'max_bin': 258, 'min_data_in_leaf': 48, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9370699703757434, 'min_gain_to_split': 0.04296727386555439}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:17:12,986] Trial 578 finished with value: 124.64766780302816 and parameters: {'num_leaves': 20, 'learning_rate': 0.1935774473009564, 'feature_fraction': 0.6324104225805833, 'bagging_fraction': 0.9249975891175911, 'bagging_freq': 9, 'lambda_l1': 1.5765263608704555e-06, 'lambda_l2': 0.2614108164431751, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 447, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 36, 'path_smooth': 0.37285049659242275, 'min_gain_to_split': 0.020461620531901717}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:17:59,713] Trial 579 finished with value: 136.34477591970702 and parameters: {'num_leaves': 23, 'learning_rate': 0.09541743303556621, 'feature_fraction': 0.7375117089592292, 'bagging_fraction': 0.9747933687180452, 'bagging_freq': 10, 'lambda_l1': 3.4378016646882855e-07, 'lambda_l2': 0.03371642145663023, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 319, 'min_data_in_leaf': 65, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.8018815537317467, 'min_gain_to_split': 0.28865214340289436}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:19:00,517] Trial 580 finished with value: 123.97814421503372 and parameters: {'num_leaves': 18, 'learning_rate': 0.1094511524944015, 'feature_fraction': 0.6565214886046558, 'bagging_fraction': 0.9646235747852806, 'bagging_freq': 8, 'lambda_l1': 8.306777524683042e-07, 'lambda_l2': 0.060399761539025716, 'min_child_samples': 32, 'max_depth': 10, 'max_bin': 350, 'min_data_in_leaf': 45, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.4162983498237154, 'min_gain_to_split': 0.07841783828918919}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:19:49,761] Trial 581 finished with value: 140.03936493257856 and parameters: {'num_leaves': 20, 'learning_rate': 0.1192690981536648, 'feature_fraction': 0.6666896446086353, 'bagging_fraction': 0.8672841976514468, 'bagging_freq': 10, 'lambda_l1': 9.775340545787184e-06, 'lambda_l2': 0.02035938662738662, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 61, 'extra_trees': True, 'early_stopping_rounds': 30, 'path_smooth': 0.9668903907790568, 'min_gain_to_split': 0.057417422569444515}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:20:42,457] Trial 582 finished with value: 117.55695202300387 and parameters: {'num_leaves': 15, 'learning_rate': 0.0994695107866838, 'feature_fraction': 0.683670659315056, 'bagging_fraction': 0.847766644114738, 'bagging_freq': 10, 'lambda_l1': 1.77283672780528e-08, 'lambda_l2': 0.1573904192819311, 'min_child_samples': 45, 'max_depth': 10, 'max_bin': 401, 'min_data_in_leaf': 40, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.4507915233812878, 'min_gain_to_split': 0.032017225066623085}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:21:30,666] Trial 583 finished with value: 152.3492555672778 and parameters: {'num_leaves': 27, 'learning_rate': 0.14743911085730574, 'feature_fraction': 0.7509377353406764, 'bagging_fraction': 0.947877314569502, 'bagging_freq': 10, 'lambda_l1': 4.9082538186539485e-06, 'lambda_l2': 0.012080229495740114, 'min_child_samples': 37, 'max_depth': 10, 'max_bin': 384, 'min_data_in_leaf': 64, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.3381739948594499, 'min_gain_to_split': 0.003784016976729719}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:22:14,585] Trial 584 finished with value: 119.80954460834737 and parameters: {'num_leaves': 22, 'learning_rate': 0.1292946396779566, 'feature_fraction': 0.640715179058236, 'bagging_fraction': 0.9351204465104148, 'bagging_freq': 9, 'lambda_l1': 0.0002485943941186575, 'lambda_l2': 0.09021735747594313, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 474, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.9190185138896105, 'min_gain_to_split': 0.21231153431650324}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:23:05,799] Trial 585 finished with value: 143.4938141513222 and parameters: {'num_leaves': 68, 'learning_rate': 0.11169063921417587, 'feature_fraction': 0.8751780564210536, 'bagging_fraction': 0.9148228544709858, 'bagging_freq': 6, 'lambda_l1': 2.638843300480072e-06, 'lambda_l2': 0.027910274351555762, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 356, 'min_data_in_leaf': 72, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.39212133666681864, 'min_gain_to_split': 0.29842494750823967}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:24:05,007] Trial 586 finished with value: 143.92976239872883 and parameters: {'num_leaves': 17, 'learning_rate': 0.09020202165765204, 'feature_fraction': 0.6501486317894752, 'bagging_fraction': 0.9843715232381791, 'bagging_freq': 10, 'lambda_l1': 5.960259005795671e-07, 'lambda_l2': 0.04521724122417672, 'min_child_samples': 46, 'max_depth': 9, 'max_bin': 492, 'min_data_in_leaf': 68, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.4334307806197018, 'min_gain_to_split': 0.325446364652003}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:24:51,128] Trial 587 finished with value: 133.54299699115654 and parameters: {'num_leaves': 19, 'learning_rate': 0.18307844052696737, 'feature_fraction': 0.6771166593677156, 'bagging_fraction': 0.9694102690685973, 'bagging_freq': 10, 'lambda_l1': 2.1156200645101396e-07, 'lambda_l2': 0.005883634433813207, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 340, 'min_data_in_leaf': 66, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.9986960113485256, 'min_gain_to_split': 0.02127988566393886}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:25:31,249] Trial 588 finished with value: 118.94186004773823 and parameters: {'num_leaves': 73, 'learning_rate': 0.13741992870939346, 'feature_fraction': 0.6286477565457755, 'bagging_fraction': 0.9552560429735749, 'bagging_freq': 10, 'lambda_l1': 1.2793703636541068e-05, 'lambda_l2': 0.018662910808779222, 'min_child_samples': 50, 'max_depth': 4, 'max_bin': 482, 'min_data_in_leaf': 33, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.9495745765052, 'min_gain_to_split': 0.27245428081606365}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:26:14,539] Trial 589 finished with value: 126.24698436031915 and parameters: {'num_leaves': 24, 'learning_rate': 0.08385604648107674, 'feature_fraction': 0.6677236005358217, 'bagging_fraction': 0.9618934775286018, 'bagging_freq': 9, 'lambda_l1': 2.5092062253284545e-05, 'lambda_l2': 0.0001410900305033036, 'min_child_samples': 42, 'max_depth': 10, 'max_bin': 368, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.97357927726781, 'min_gain_to_split': 0.34389415021668}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:26:56,602] Trial 590 finished with value: 131.09338273399243 and parameters: {'num_leaves': 21, 'learning_rate': 0.12233411688491398, 'feature_fraction': 0.6585695880213392, 'bagging_fraction': 0.9930404259928383, 'bagging_freq': 10, 'lambda_l1': 1.3204833516511608e-06, 'lambda_l2': 0.004156195149855094, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 330, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.4705179290554394, 'min_gain_to_split': 0.04246535258814488}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:27:41,900] Trial 591 finished with value: 106.69300776253408 and parameters: {'num_leaves': 17, 'learning_rate': 0.10266622693199709, 'feature_fraction': 0.6478872187632153, 'bagging_fraction': 0.9394692552796831, 'bagging_freq': 10, 'lambda_l1': 5.962657164296865e-06, 'lambda_l2': 2.5338897087624153e-05, 'min_child_samples': 46, 'max_depth': 10, 'max_bin': 379, 'min_data_in_leaf': 27, 'extra_trees': True, 'early_stopping_rounds': 21, 'path_smooth': 0.8781698137679508, 'min_gain_to_split': 0.0007716668395566992}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:28:30,875] Trial 592 finished with value: 122.52237116556728 and parameters: {'num_leaves': 25, 'learning_rate': 0.1580141213325541, 'feature_fraction': 0.636840449776204, 'bagging_fraction': 0.9219769902301395, 'bagging_freq': 8, 'lambda_l1': 3.5053676999574706e-06, 'lambda_l2': 0.008624321833059796, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 494, 'min_data_in_leaf': 41, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.9266064736215065, 'min_gain_to_split': 0.2523376894064556}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:29:19,206] Trial 593 finished with value: 113.36647245469116 and parameters: {'num_leaves': 19, 'learning_rate': 0.11249274593212141, 'feature_fraction': 0.6929464459506236, 'bagging_fraction': 0.7122480222078736, 'bagging_freq': 10, 'lambda_l1': 8.313160012692417e-06, 'lambda_l2': 0.016162170817983653, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 485, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.41983022136981796, 'min_gain_to_split': 0.31256267357157025}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:30:13,124] Trial 594 finished with value: 124.68979377722162 and parameters: {'num_leaves': 22, 'learning_rate': 0.09312965404140201, 'feature_fraction': 0.6753008543818224, 'bagging_fraction': 0.9762972666661665, 'bagging_freq': 9, 'lambda_l1': 3.592503446085309e-08, 'lambda_l2': 0.026870701727888274, 'min_child_samples': 47, 'max_depth': 10, 'max_bin': 351, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.9541999011316931, 'min_gain_to_split': 0.02903349282856666}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:31:07,818] Trial 595 finished with value: 142.04772158702767 and parameters: {'num_leaves': 20, 'learning_rate': 0.1305893273618671, 'feature_fraction': 0.6555490663874542, 'bagging_fraction': 0.952735772232431, 'bagging_freq': 10, 'lambda_l1': 1.39598241153421e-05, 'lambda_l2': 0.05689639339454703, 'min_child_samples': 36, 'max_depth': 10, 'max_bin': 460, 'min_data_in_leaf': 70, 'extra_trees': True, 'early_stopping_rounds': 22, 'path_smooth': 0.999892034696214, 'min_gain_to_split': 0.05535594370119406}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:31:50,725] Trial 596 finished with value: 113.24028781896803 and parameters: {'num_leaves': 15, 'learning_rate': 0.16974354163010572, 'feature_fraction': 0.7023830094015346, 'bagging_fraction': 0.9687169467330504, 'bagging_freq': 10, 'lambda_l1': 1.1204389939684352e-07, 'lambda_l2': 0.011474725719678239, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 390, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.443877660108347, 'min_gain_to_split': 0.23581648216702433}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:33:34,549] Trial 597 finished with value: 121.6057939984565 and parameters: {'num_leaves': 23, 'learning_rate': 0.10242549123331943, 'feature_fraction': 0.6655535732793099, 'bagging_fraction': 0.9300363959291903, 'bagging_freq': 10, 'lambda_l1': 0.00048258273339192326, 'lambda_l2': 0.034886330239692155, 'min_child_samples': 26, 'max_depth': 10, 'max_bin': 468, 'min_data_in_leaf': 88, 'extra_trees': False, 'early_stopping_rounds': 33, 'path_smooth': 0.5530766430841285, 'min_gain_to_split': 0.012416928231495743}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:34:20,478] Trial 598 finished with value: 115.8428368269421 and parameters: {'num_leaves': 28, 'learning_rate': 0.1188869237709109, 'feature_fraction': 0.6158044479325183, 'bagging_fraction': 0.8362431553257665, 'bagging_freq': 9, 'lambda_l1': 0.014996222633019415, 'lambda_l2': 0.08611521543215757, 'min_child_samples': 44, 'max_depth': 10, 'max_bin': 359, 'min_data_in_leaf': 30, 'extra_trees': True, 'early_stopping_rounds': 31, 'path_smooth': 0.4042949585797394, 'min_gain_to_split': 0.039545957103621965}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:35:03,311] Trial 599 finished with value: 134.46249731470203 and parameters: {'num_leaves': 18, 'learning_rate': 0.14431449873727628, 'feature_fraction': 0.6446540694704593, 'bagging_fraction': 0.8904449087797256, 'bagging_freq': 10, 'lambda_l1': 6.381112665122906e-05, 'lambda_l2': 0.007558912098467963, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 371, 'min_data_in_leaf': 62, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.46735748689212425, 'min_gain_to_split': 0.09051126895217709}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:35:52,841] Trial 600 finished with value: 141.81169233617268 and parameters: {'num_leaves': 25, 'learning_rate': 0.10538356866496965, 'feature_fraction': 0.6328002682375639, 'bagging_fraction': 0.9450065917251878, 'bagging_freq': 10, 'lambda_l1': 3.4883820430743956e-05, 'lambda_l2': 0.020897774039511166, 'min_child_samples': 48, 'max_depth': 9, 'max_bin': 479, 'min_data_in_leaf': 67, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.36318463523751293, 'min_gain_to_split': 0.1222428341679607}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:37:57,696] Trial 601 finished with value: 146.5073770862024 and parameters: {'num_leaves': 21, 'learning_rate': 0.011974214467844498, 'feature_fraction': 0.6857048864041972, 'bagging_fraction': 0.8819991616882535, 'bagging_freq': 10, 'lambda_l1': 1.945018824628253e-05, 'lambda_l2': 0.002847695189103244, 'min_child_samples': 45, 'max_depth': 10, 'max_bin': 500, 'min_data_in_leaf': 64, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.8956471862176426, 'min_gain_to_split': 0.2868395689909198}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:38:53,783] Trial 602 finished with value: 135.86855879154518 and parameters: {'num_leaves': 17, 'learning_rate': 0.09705031733578173, 'feature_fraction': 0.6520307053623959, 'bagging_fraction': 0.9587576359759048, 'bagging_freq': 9, 'lambda_l1': 1.158961241862296e-06, 'lambda_l2': 0.01258815328834046, 'min_child_samples': 50, 'max_depth': 8, 'max_bin': 335, 'min_data_in_leaf': 69, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.9373444467537742, 'min_gain_to_split': 0.014100463036835499}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:39:41,280] Trial 603 finished with value: 127.69591231444178 and parameters: {'num_leaves': 23, 'learning_rate': 0.11480490565211109, 'feature_fraction': 0.6612741686015043, 'bagging_fraction': 0.9058928820775406, 'bagging_freq': 8, 'lambda_l1': 3.2007158412703525e-06, 'lambda_l2': 1.3510667932230722, 'min_child_samples': 47, 'max_depth': 10, 'max_bin': 313, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 32, 'path_smooth': 0.9631927983631753, 'min_gain_to_split': 0.030693140368622772}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:41:29,659] Trial 604 finished with value: 143.387787575831 and parameters: {'num_leaves': 19, 'learning_rate': 0.02159889609068953, 'feature_fraction': 0.8994090246767226, 'bagging_fraction': 0.9800944861452469, 'bagging_freq': 10, 'lambda_l1': 4.6757902621340876e-07, 'lambda_l2': 0.04063692932002536, 'min_child_samples': 45, 'max_depth': 10, 'max_bin': 489, 'min_data_in_leaf': 66, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.9813761755431453, 'min_gain_to_split': 0.33577163219899253}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:42:19,840] Trial 605 finished with value: 138.98572860703365 and parameters: {'num_leaves': 21, 'learning_rate': 0.12932054259825157, 'feature_fraction': 0.7102055313535101, 'bagging_fraction': 0.9502091703998092, 'bagging_freq': 10, 'lambda_l1': 7.846423193922821e-07, 'lambda_l2': 0.024266021374929742, 'min_child_samples': 49, 'max_depth': 7, 'max_bin': 473, 'min_data_in_leaf': 53, 'extra_trees': True, 'early_stopping_rounds': 30, 'path_smooth': 0.43383015313691703, 'min_gain_to_split': 0.30279304948530306}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:43:00,669] Trial 606 finished with value: 111.82107611493468 and parameters: {'num_leaves': 16, 'learning_rate': 0.10855766680939181, 'feature_fraction': 0.6745643854110475, 'bagging_fraction': 0.9885380398374412, 'bagging_freq': 10, 'lambda_l1': 4.494231017307103, 'lambda_l2': 0.181533495696711, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 345, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.38831488668128455, 'min_gain_to_split': 0.15818174190993953}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:43:50,409] Trial 607 finished with value: 114.29637258348984 and parameters: {'num_leaves': 26, 'learning_rate': 0.15031091799622245, 'feature_fraction': 0.6226604269809992, 'bagging_fraction': 0.9724345013520739, 'bagging_freq': 10, 'lambda_l1': 5.53129298891017e-06, 'lambda_l2': 0.008435971082338315, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 361, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9211977195819424, 'min_gain_to_split': 0.13433994902337917}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:44:37,641] Trial 608 finished with value: 113.51910347759107 and parameters: {'num_leaves': 18, 'learning_rate': 0.125283954346078, 'feature_fraction': 0.6392022569346087, 'bagging_fraction': 0.964641617061777, 'bagging_freq': 9, 'lambda_l1': 2.04402086802753e-06, 'lambda_l2': 0.05625783035159523, 'min_child_samples': 46, 'max_depth': 10, 'max_bin': 486, 'min_data_in_leaf': 42, 'extra_trees': True, 'early_stopping_rounds': 17, 'path_smooth': 0.4839547655950682, 'min_gain_to_split': 0.02159187408661367}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:45:14,598] Trial 609 finished with value: 134.46320096044138 and parameters: {'num_leaves': 22, 'learning_rate': 0.1382769840040259, 'feature_fraction': 0.6686681905021987, 'bagging_fraction': 0.9582666905146499, 'bagging_freq': 10, 'lambda_l1': 1.4867932607512772e-08, 'lambda_l2': 0.11500686959627507, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 114, 'min_data_in_leaf': 73, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.41214393920942166, 'min_gain_to_split': 0.045117210218239015}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:46:06,918] Trial 610 finished with value: 137.92413347142272 and parameters: {'num_leaves': 24, 'learning_rate': 0.07953307374353612, 'feature_fraction': 0.6472968565643807, 'bagging_fraction': 0.9162034813260654, 'bagging_freq': 10, 'lambda_l1': 1.661591815690882e-05, 'lambda_l2': 0.01487979533815129, 'min_child_samples': 47, 'max_depth': 10, 'max_bin': 325, 'min_data_in_leaf': 64, 'extra_trees': True, 'early_stopping_rounds': 20, 'path_smooth': 0.4502518444700847, 'min_gain_to_split': 0.06903634765059975}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:46:55,344] Trial 611 finished with value: 129.06980505347602 and parameters: {'num_leaves': 20, 'learning_rate': 0.09194491105800687, 'feature_fraction': 0.6589333468192639, 'bagging_fraction': 0.9441758282626332, 'bagging_freq': 8, 'lambda_l1': 1.020942248653982e-05, 'lambda_l2': 0.034735220838438975, 'min_child_samples': 44, 'max_depth': 10, 'max_bin': 375, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.9462090586530152, 'min_gain_to_split': 0.3209624213802604}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:47:53,756] Trial 612 finished with value: 140.59479694297733 and parameters: {'num_leaves': 16, 'learning_rate': 0.09923646397188882, 'feature_fraction': 0.6527341152184024, 'bagging_fraction': 0.9755381551853709, 'bagging_freq': 10, 'lambda_l1': 2.963881591209771e-07, 'lambda_l2': 0.004119309497258803, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 476, 'min_data_in_leaf': 68, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.8546303399701416, 'min_gain_to_split': 0.2633136658833759}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:48:44,047] Trial 613 finished with value: 115.02361716112883 and parameters: {'num_leaves': 38, 'learning_rate': 0.12055400748112928, 'feature_fraction': 0.6301593511481587, 'bagging_fraction': 0.8604780675577264, 'bagging_freq': 9, 'lambda_l1': 1.6332859666387206e-07, 'lambda_l2': 3.8291597139475804e-08, 'min_child_samples': 42, 'max_depth': 10, 'max_bin': 365, 'min_data_in_leaf': 32, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.5082476770905228, 'min_gain_to_split': 0.03206540339680845}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:49:28,700] Trial 614 finished with value: 134.26874190311824 and parameters: {'num_leaves': 19, 'learning_rate': 0.1618872206179266, 'feature_fraction': 0.6793099333323223, 'bagging_fraction': 0.965289240491471, 'bagging_freq': 10, 'lambda_l1': 3.0583578293438474e-05, 'lambda_l2': 0.022239433648978697, 'min_child_samples': 39, 'max_depth': 10, 'max_bin': 354, 'min_data_in_leaf': 66, 'extra_trees': True, 'early_stopping_rounds': 23, 'path_smooth': 0.9741681056777776, 'min_gain_to_split': 0.050786477599528104}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:51:01,933] Trial 615 finished with value: 113.29703818073384 and parameters: {'num_leaves': 23, 'learning_rate': 0.08668646271859286, 'feature_fraction': 0.6422836473613531, 'bagging_fraction': 0.8507350033948281, 'bagging_freq': 10, 'lambda_l1': 4.628411670138303e-06, 'lambda_l2': 0.012299624192306579, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 494, 'min_data_in_leaf': 59, 'extra_trees': False, 'early_stopping_rounds': 34, 'path_smooth': 0.37262968048324197, 'min_gain_to_split': 0.3101223156737414}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:51:57,578] Trial 616 finished with value: 120.45982568127229 and parameters: {'num_leaves': 30, 'learning_rate': 0.10883786088131717, 'feature_fraction': 0.6652841327750766, 'bagging_fraction': 0.9536675014887591, 'bagging_freq': 10, 'lambda_l1': 0.00012512842579800754, 'lambda_l2': 0.006498082284707333, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.42505447063505253, 'min_gain_to_split': 0.17655452863669036}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:53:02,424] Trial 617 finished with value: 135.28194183251694 and parameters: {'num_leaves': 21, 'learning_rate': 0.04558475638311108, 'feature_fraction': 0.6546283961798194, 'bagging_fraction': 0.9347201566872766, 'bagging_freq': 10, 'lambda_l1': 1.6335285958372607e-06, 'lambda_l2': 0.07074002146935308, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 301, 'min_data_in_leaf': 55, 'extra_trees': True, 'early_stopping_rounds': 38, 'path_smooth': 0.8941767587889565, 'min_gain_to_split': 0.022298566966849093}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:53:59,023] Trial 618 finished with value: 133.18471214659053 and parameters: {'num_leaves': 27, 'learning_rate': 0.11738376809162045, 'feature_fraction': 0.6364275907081195, 'bagging_fraction': 0.9849320629265336, 'bagging_freq': 9, 'lambda_l1': 7.644155326282239e-06, 'lambda_l2': 0.01809366235152813, 'min_child_samples': 47, 'max_depth': 10, 'max_bin': 480, 'min_data_in_leaf': 63, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.5933193922889051, 'min_gain_to_split': 0.27531258991893937}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:54:33,261] Trial 619 finished with value: 127.98673887582206 and parameters: {'num_leaves': 17, 'learning_rate': 0.13530104926708525, 'feature_fraction': 0.6720605009666666, 'bagging_fraction': 0.9221838104508278, 'bagging_freq': 10, 'lambda_l1': 2.6964750154936732e-08, 'lambda_l2': 0.04740540753638167, 'min_child_samples': 46, 'max_depth': 10, 'max_bin': 186, 'min_data_in_leaf': 50, 'extra_trees': True, 'early_stopping_rounds': 30, 'path_smooth': 0.9265954789188964, 'min_gain_to_split': 0.32633256934833643}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:55:21,577] Trial 620 finished with value: 117.46028092915522 and parameters: {'num_leaves': 20, 'learning_rate': 0.10040459237188518, 'feature_fraction': 0.6104633615547382, 'bagging_fraction': 0.9998527312089015, 'bagging_freq': 10, 'lambda_l1': 5.141882937131801e-07, 'lambda_l2': 0.31097744253001985, 'min_child_samples': 50, 'max_depth': 9, 'max_bin': 385, 'min_data_in_leaf': 40, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.9579408502668444, 'min_gain_to_split': 0.09736546612849034}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:56:04,205] Trial 621 finished with value: 147.61616192063548 and parameters: {'num_leaves': 15, 'learning_rate': 0.10814888898897196, 'feature_fraction': 0.648047526707826, 'bagging_fraction': 0.9711454232737848, 'bagging_freq': 10, 'lambda_l1': 1.05282807668171e-06, 'lambda_l2': 0.02994339976430073, 'min_child_samples': 44, 'max_depth': 10, 'max_bin': 341, 'min_data_in_leaf': 68, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.39850620658399954, 'min_gain_to_split': 0.2951029512195358}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:56:48,567] Trial 622 finished with value: 103.31544004115008 and parameters: {'num_leaves': 25, 'learning_rate': 0.12761960004061568, 'feature_fraction': 0.6891819928637265, 'bagging_fraction': 0.8987853288003989, 'bagging_freq': 7, 'lambda_l1': 4.947284292751533e-05, 'lambda_l2': 0.009547481562245158, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 393, 'min_data_in_leaf': 25, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.6652063715155794, 'min_gain_to_split': 0.015577652598494378}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:57:30,917] Trial 623 finished with value: 120.30676839343137 and parameters: {'num_leaves': 19, 'learning_rate': 0.1481951970631006, 'feature_fraction': 0.6606634231649267, 'bagging_fraction': 0.948953626056209, 'bagging_freq': 9, 'lambda_l1': 0.00019591218771781936, 'lambda_l2': 0.09749851911031333, 'min_child_samples': 41, 'max_depth': 10, 'max_bin': 488, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.46016701477997113, 'min_gain_to_split': 0.03357612785847224}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:58:16,128] Trial 624 finished with value: 127.63375585580839 and parameters: {'num_leaves': 22, 'learning_rate': 0.11506563417564766, 'feature_fraction': 0.6222438805791985, 'bagging_fraction': 0.9404542927549395, 'bagging_freq': 10, 'lambda_l1': 3.48670403381357e-06, 'lambda_l2': 0.01484690718438776, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 377, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9807825029713447, 'min_gain_to_split': 0.3173885173492256}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 00:59:20,884] Trial 625 finished with value: 139.6441270060322 and parameters: {'num_leaves': 18, 'learning_rate': 0.09310353484452559, 'feature_fraction': 0.6414542817143961, 'bagging_fraction': 0.9102219105572543, 'bagging_freq': 8, 'lambda_l1': 1.6463816135148444e-05, 'lambda_l2': 0.006487672420766055, 'min_child_samples': 45, 'max_depth': 10, 'max_bin': 471, 'min_data_in_leaf': 70, 'extra_trees': True, 'early_stopping_rounds': 35, 'path_smooth': 0.9071682815014043, 'min_gain_to_split': 0.005713544512089028}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:00:09,353] Trial 626 finished with value: 142.9478231231589 and parameters: {'num_leaves': 24, 'learning_rate': 0.1748661348395563, 'feature_fraction': 0.6653608712113863, 'bagging_fraction': 0.9282185370084877, 'bagging_freq': 10, 'lambda_l1': 2.286755508168526e-06, 'lambda_l2': 0.021433330386842052, 'min_child_samples': 47, 'max_depth': 10, 'max_bin': 456, 'min_data_in_leaf': 65, 'extra_trees': True, 'early_stopping_rounds': 33, 'path_smooth': 0.43771941979380036, 'min_gain_to_split': 0.28407108502622525}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:00:52,800] Trial 627 finished with value: 117.42084446829529 and parameters: {'num_leaves': 17, 'learning_rate': 0.10367842161242585, 'feature_fraction': 0.6822023788553966, 'bagging_fraction': 0.959317588096303, 'bagging_freq': 10, 'lambda_l1': 1.11564749888984e-05, 'lambda_l2': 0.0396469630364292, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 245, 'min_data_in_leaf': 23, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.9520342081903681, 'min_gain_to_split': 0.042064477155830324}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:01:49,301] Trial 628 finished with value: 143.82193202296392 and parameters: {'num_leaves': 22, 'learning_rate': 0.12136133949497183, 'feature_fraction': 0.6306964544282962, 'bagging_fraction': 0.9821208549680569, 'bagging_freq': 9, 'lambda_l1': 2.699492463257819e-05, 'lambda_l2': 0.06796867203080344, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 500, 'min_data_in_leaf': 67, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.4171982093006747, 'min_gain_to_split': 0.021578841820294486}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:02:38,747] Trial 629 finished with value: 140.7496987660582 and parameters: {'num_leaves': 20, 'learning_rate': 0.1126994363596145, 'feature_fraction': 0.8391416253809313, 'bagging_fraction': 0.9628958132998597, 'bagging_freq': 10, 'lambda_l1': 8.64399468383398e-08, 'lambda_l2': 3.5284929275240096, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 348, 'min_data_in_leaf': 61, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.35286000857472166, 'min_gain_to_split': 0.30740962428594654}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:03:30,391] Trial 630 finished with value: 122.41745648580533 and parameters: {'num_leaves': 92, 'learning_rate': 0.13953148049239447, 'feature_fraction': 0.6538943115388837, 'bagging_fraction': 0.969228315848396, 'bagging_freq': 10, 'lambda_l1': 6.921688162086223e-07, 'lambda_l2': 0.010090426949281153, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 368, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.9360316435078535, 'min_gain_to_split': 0.08325643028024385}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:04:30,175] Trial 631 finished with value: 129.81859238982452 and parameters: {'num_leaves': 18, 'learning_rate': 0.0696362709258002, 'feature_fraction': 0.6713737585247529, 'bagging_fraction': 0.9919793816272774, 'bagging_freq': 10, 'lambda_l1': 3.277765757645823e-07, 'lambda_l2': 0.13798107869412196, 'min_child_samples': 46, 'max_depth': 10, 'max_bin': 481, 'min_data_in_leaf': 44, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.9998425771958186, 'min_gain_to_split': 0.03348323901972148}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:05:22,002] Trial 632 finished with value: 116.31380517851707 and parameters: {'num_leaves': 26, 'learning_rate': 0.15406025009925375, 'feature_fraction': 0.6444050374294863, 'bagging_fraction': 0.9785706447974101, 'bagging_freq': 9, 'lambda_l1': 6.4513963638297994e-06, 'lambda_l2': 0.029333712580713593, 'min_child_samples': 44, 'max_depth': 10, 'max_bin': 357, 'min_data_in_leaf': 41, 'extra_trees': True, 'early_stopping_rounds': 31, 'path_smooth': 0.48128817510335264, 'min_gain_to_split': 0.05650778395847799}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:06:04,244] Trial 633 finished with value: 125.25033858423237 and parameters: {'num_leaves': 15, 'learning_rate': 0.09845614464160625, 'feature_fraction': 0.6586895669010341, 'bagging_fraction': 0.958938122405903, 'bagging_freq': 10, 'lambda_l1': 7.964619393566769e-05, 'lambda_l2': 1.0110728078735024e-08, 'min_child_samples': 21, 'max_depth': 10, 'max_bin': 322, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.9782982971553407, 'min_gain_to_split': 0.017644812611467955}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:07:25,932] Trial 634 finished with value: 125.62290174070793 and parameters: {'num_leaves': 21, 'learning_rate': 0.10782609241946847, 'feature_fraction': 0.6374977832998607, 'bagging_fraction': 0.8737122255046019, 'bagging_freq': 10, 'lambda_l1': 2.1607620275931083e-07, 'lambda_l2': 0.005198902741968426, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 331, 'min_data_in_leaf': 71, 'extra_trees': False, 'early_stopping_rounds': 29, 'path_smooth': 0.44540755300651025, 'min_gain_to_split': 0.3330536715804891}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:08:16,466] Trial 635 finished with value: 129.0952594438267 and parameters: {'num_leaves': 23, 'learning_rate': 0.13303843417797384, 'feature_fraction': 0.675649036442896, 'bagging_fraction': 0.9515985374214222, 'bagging_freq': 10, 'lambda_l1': 1.3150567657898448e-06, 'lambda_l2': 0.013921519823576577, 'min_child_samples': 47, 'max_depth': 10, 'max_bin': 491, 'min_data_in_leaf': 63, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.3843767633111254, 'min_gain_to_split': 0.11153560665856176}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:08:51,738] Trial 636 finished with value: 122.71087795842507 and parameters: {'num_leaves': 28, 'learning_rate': 0.12537809970265648, 'feature_fraction': 0.6660936032934951, 'bagging_fraction': 0.91380393004477, 'bagging_freq': 7, 'lambda_l1': 2.7456021253873825e-06, 'lambda_l2': 0.017935304083642765, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 218, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.9615709808297259, 'min_gain_to_split': 0.009723010962058853}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:09:47,909] Trial 637 finished with value: 133.42734854033324 and parameters: {'num_leaves': 24, 'learning_rate': 0.08848129737249133, 'feature_fraction': 0.6480239725116569, 'bagging_fraction': 0.9721318353331306, 'bagging_freq': 8, 'lambda_l1': 1.0770013948424789e-05, 'lambda_l2': 0.03993292890879166, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 483, 'min_data_in_leaf': 68, 'extra_trees': True, 'early_stopping_rounds': 23, 'path_smooth': 0.317804561334991, 'min_gain_to_split': 0.2976562775879056}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:10:34,888] Trial 638 finished with value: 123.18184983580086 and parameters: {'num_leaves': 17, 'learning_rate': 0.16464830207334186, 'feature_fraction': 0.6539752537432141, 'bagging_fraction': 0.9455691249034587, 'bagging_freq': 10, 'lambda_l1': 6.212573862780852e-08, 'lambda_l2': 0.009081784969911877, 'min_child_samples': 42, 'max_depth': 10, 'max_bin': 473, 'min_data_in_leaf': 66, 'extra_trees': True, 'early_stopping_rounds': 33, 'path_smooth': 0.9258066399836609, 'min_gain_to_split': 0.04720852008520973}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:11:19,180] Trial 639 finished with value: 119.75056438315544 and parameters: {'num_leaves': 19, 'learning_rate': 0.2266341864617976, 'feature_fraction': 0.6286554532290672, 'bagging_fraction': 0.9327850149364149, 'bagging_freq': 10, 'lambda_l1': 4.373152986655983e-06, 'lambda_l2': 0.056193052250044104, 'min_child_samples': 45, 'max_depth': 9, 'max_bin': 417, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.8710708549361115, 'min_gain_to_split': 0.25409474375633573}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:12:13,554] Trial 640 finished with value: 144.66180898204672 and parameters: {'num_leaves': 21, 'learning_rate': 0.11538902628687522, 'feature_fraction': 0.912894823129403, 'bagging_fraction': 0.954292539283563, 'bagging_freq': 9, 'lambda_l1': 1.0198469179248487e-08, 'lambda_l2': 0.026587540764833606, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 364, 'min_data_in_leaf': 78, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.4007086467114794, 'min_gain_to_split': 0.22550417906003}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:13:09,513] Trial 641 finished with value: 122.51032245414169 and parameters: {'num_leaves': 25, 'learning_rate': 0.143627398727526, 'feature_fraction': 0.6909619620910892, 'bagging_fraction': 0.9652730317447447, 'bagging_freq': 10, 'lambda_l1': 1.9827499419176148e-05, 'lambda_l2': 0.21734786910887907, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 381, 'min_data_in_leaf': 47, 'extra_trees': True, 'early_stopping_rounds': 32, 'path_smooth': 0.8347750403388714, 'min_gain_to_split': 0.026692193763812842}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:14:01,412] Trial 642 finished with value: 105.6587267392882 and parameters: {'num_leaves': 19, 'learning_rate': 0.10194952253027972, 'feature_fraction': 0.6591433905909528, 'bagging_fraction': 0.9403360711245606, 'bagging_freq': 10, 'lambda_l1': 7.618872501456169e-07, 'lambda_l2': 0.0035388786672324295, 'min_child_samples': 47, 'max_depth': 10, 'max_bin': 437, 'min_data_in_leaf': 27, 'extra_trees': True, 'early_stopping_rounds': 30, 'path_smooth': 0.46568984983891926, 'min_gain_to_split': 0.06671191566531481}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:14:50,049] Trial 643 finished with value: 114.79237256214792 and parameters: {'num_leaves': 47, 'learning_rate': 0.1082343653723363, 'feature_fraction': 0.6809459024916455, 'bagging_fraction': 0.8397608377746387, 'bagging_freq': 10, 'lambda_l1': 0.0003113139510440749, 'lambda_l2': 0.013449178222802465, 'min_child_samples': 46, 'max_depth': 10, 'max_bin': 373, 'min_data_in_leaf': 32, 'extra_trees': True, 'early_stopping_rounds': 34, 'path_smooth': 0.5255629717968662, 'min_gain_to_split': 0.2683480887152361}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:15:29,717] Trial 644 finished with value: 138.3132286111997 and parameters: {'num_leaves': 22, 'learning_rate': 0.09457530335455262, 'feature_fraction': 0.6388171425292957, 'bagging_fraction': 0.9191213130726585, 'bagging_freq': 10, 'lambda_l1': 3.8736376297717144e-05, 'lambda_l2': 0.0009462253101791771, 'min_child_samples': 44, 'max_depth': 10, 'max_bin': 207, 'min_data_in_leaf': 58, 'extra_trees': True, 'early_stopping_rounds': 43, 'path_smooth': 0.42420738874092834, 'min_gain_to_split': 0.03620599651031542}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:16:12,602] Trial 645 finished with value: 129.78015307230697 and parameters: {'num_leaves': 16, 'learning_rate': 0.12446377936870165, 'feature_fraction': 0.6465039593534272, 'bagging_fraction': 0.9785793329623257, 'bagging_freq': 9, 'lambda_l1': 7.662845871540989e-06, 'lambda_l2': 0.10032942119239982, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 348, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9412686625184024, 'min_gain_to_split': 0.1509263897857339}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:16:59,047] Trial 646 finished with value: 131.27996262715945 and parameters: {'num_leaves': 17, 'learning_rate': 0.11799504093005742, 'feature_fraction': 0.6189699643144535, 'bagging_fraction': 0.9497370562142782, 'bagging_freq': 10, 'lambda_l1': 4.112242939583619e-07, 'lambda_l2': 0.02120449242031966, 'min_child_samples': 41, 'max_depth': 10, 'max_bin': 338, 'min_data_in_leaf': 65, 'extra_trees': True, 'early_stopping_rounds': 50, 'path_smooth': 0.9063808957695463, 'min_gain_to_split': 0.0006529614184442312}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:17:55,258] Trial 647 finished with value: 136.02873274438963 and parameters: {'num_leaves': 20, 'learning_rate': 0.08478769298499375, 'feature_fraction': 0.6652557125055264, 'bagging_fraction': 0.8536502475690492, 'bagging_freq': 9, 'lambda_l1': 1.5692565399377999e-06, 'lambda_l2': 9.198058327833045e-07, 'min_child_samples': 48, 'max_depth': 6, 'max_bin': 489, 'min_data_in_leaf': 52, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.9782686634115858, 'min_gain_to_split': 0.3161443732248051}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:18:50,023] Trial 648 finished with value: 140.2463100798107 and parameters: {'num_leaves': 24, 'learning_rate': 0.1326834716948998, 'feature_fraction': 0.6708855083268016, 'bagging_fraction': 0.9635758848898551, 'bagging_freq': 10, 'lambda_l1': 1.669326547235302e-05, 'lambda_l2': 0.007731342983767138, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 494, 'min_data_in_leaf': 56, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.45228796685126205, 'min_gain_to_split': 0.35587665809395186}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:19:34,968] Trial 649 finished with value: 136.1549662169257 and parameters: {'num_leaves': 18, 'learning_rate': 0.1855657197893095, 'feature_fraction': 0.6514573401637382, 'bagging_fraction': 0.9076099936619669, 'bagging_freq': 10, 'lambda_l1': 0.000781712447408582, 'lambda_l2': 0.04207485574548785, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 466, 'min_data_in_leaf': 70, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.9536408626507508, 'min_gain_to_split': 0.18858064825840748}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:20:27,046] Trial 650 finished with value: 120.68020368349089 and parameters: {'num_leaves': 22, 'learning_rate': 0.09990926002553174, 'feature_fraction': 0.6350422800545624, 'bagging_fraction': 0.9842076457890845, 'bagging_freq': 10, 'lambda_l1': 3.03975041954957e-06, 'lambda_l2': 0.0018911479518756702, 'min_child_samples': 35, 'max_depth': 10, 'max_bin': 478, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.4101966558384277, 'min_gain_to_split': 0.027841991714006992}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:21:13,113] Trial 651 finished with value: 126.12565361475797 and parameters: {'num_leaves': 15, 'learning_rate': 0.10765272512287884, 'feature_fraction': 0.6581296765587463, 'bagging_fraction': 0.8086306926271848, 'bagging_freq': 8, 'lambda_l1': 4.930989538374245e-06, 'lambda_l2': 0.06396479145613196, 'min_child_samples': 45, 'max_depth': 10, 'max_bin': 404, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.12955144157255105, 'min_gain_to_split': 0.013340543955529766}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:21:59,513] Trial 652 finished with value: 136.8665086851105 and parameters: {'num_leaves': 20, 'learning_rate': 0.15690910856325846, 'feature_fraction': 0.6768258488041163, 'bagging_fraction': 0.9738307051170455, 'bagging_freq': 10, 'lambda_l1': 0.034083464140249646, 'lambda_l2': 0.012329820409410467, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 367, 'min_data_in_leaf': 69, 'extra_trees': True, 'early_stopping_rounds': 22, 'path_smooth': 0.4901789932131924, 'min_gain_to_split': 0.20240978005394}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:23:31,881] Trial 653 finished with value: 131.39046325608766 and parameters: {'num_leaves': 26, 'learning_rate': 0.1421958920341591, 'feature_fraction': 0.6439321578202569, 'bagging_fraction': 0.9570385039594838, 'bagging_freq': 10, 'lambda_l1': 9.433990936121704e-07, 'lambda_l2': 0.028206145804976473, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 355, 'min_data_in_leaf': 62, 'extra_trees': False, 'early_stopping_rounds': 29, 'path_smooth': 0.3689320438037565, 'min_gain_to_split': 0.24624771246429641}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:24:29,577] Trial 654 finished with value: 142.23085462201803 and parameters: {'num_leaves': 23, 'learning_rate': 0.1151646674937649, 'feature_fraction': 0.6993975908062542, 'bagging_fraction': 0.9690972218691943, 'bagging_freq': 9, 'lambda_l1': 2.279556560452929e-08, 'lambda_l2': 0.018210973097807354, 'min_child_samples': 47, 'max_depth': 9, 'max_bin': 487, 'min_data_in_leaf': 74, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.43876783983303647, 'min_gain_to_split': 0.3416246511083854}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:25:24,553] Trial 655 finished with value: 144.55460422377172 and parameters: {'num_leaves': 18, 'learning_rate': 0.12131559389971053, 'feature_fraction': 0.664393308253275, 'bagging_fraction': 0.9228140522291326, 'bagging_freq': 10, 'lambda_l1': 1.0587004109321308e-05, 'lambda_l2': 0.0054743431890145935, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 341, 'min_data_in_leaf': 67, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.9358599960009316, 'min_gain_to_split': 0.2830820781695744}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:26:17,679] Trial 656 finished with value: 138.55481146178423 and parameters: {'num_leaves': 20, 'learning_rate': 0.09270153435605495, 'feature_fraction': 0.6278778074956144, 'bagging_fraction': 0.9453613281870058, 'bagging_freq': 10, 'lambda_l1': 2.7980787647579388e-05, 'lambda_l2': 0.010841400804252303, 'min_child_samples': 46, 'max_depth': 10, 'max_bin': 428, 'min_data_in_leaf': 65, 'extra_trees': True, 'early_stopping_rounds': 30, 'path_smooth': 0.9182323727551813, 'min_gain_to_split': 0.044133071470676355}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:27:14,393] Trial 657 finished with value: 109.2649498932841 and parameters: {'num_leaves': 28, 'learning_rate': 0.10367015618441047, 'feature_fraction': 0.6507183521256407, 'bagging_fraction': 0.9024567276066559, 'bagging_freq': 8, 'lambda_l1': 1.7841050494338816e-06, 'lambda_l2': 0.1320775909408239, 'min_child_samples': 33, 'max_depth': 10, 'max_bin': 477, 'min_data_in_leaf': 29, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.9834147792291211, 'min_gain_to_split': 0.32641674113374786}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:27:53,119] Trial 658 finished with value: 118.29151046509648 and parameters: {'num_leaves': 22, 'learning_rate': 0.07628598475599087, 'feature_fraction': 0.9425204198103794, 'bagging_fraction': 0.9371339854453198, 'bagging_freq': 10, 'lambda_l1': 4.598360129909892e-08, 'lambda_l2': 0.027422673167639876, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 136, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.3846985451257765, 'min_gain_to_split': 0.3078391497323703}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:28:44,281] Trial 659 finished with value: 117.76435717643372 and parameters: {'num_leaves': 16, 'learning_rate': 0.12952708399044632, 'feature_fraction': 0.6834099829714713, 'bagging_fraction': 0.9888254051314909, 'bagging_freq': 10, 'lambda_l1': 4.947063089253815e-07, 'lambda_l2': 0.07665063331515926, 'min_child_samples': 38, 'max_depth': 10, 'max_bin': 461, 'min_data_in_leaf': 41, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.4210817626787755, 'min_gain_to_split': 0.05101981306202323}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:29:28,622] Trial 660 finished with value: 126.713407029124 and parameters: {'num_leaves': 24, 'learning_rate': 0.11248567079083208, 'feature_fraction': 0.6588996540323488, 'bagging_fraction': 0.9281111956324807, 'bagging_freq': 9, 'lambda_l1': 5.8080453307887884e-06, 'lambda_l2': 0.045770248111080616, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 293, 'min_data_in_leaf': 60, 'extra_trees': True, 'early_stopping_rounds': 31, 'path_smooth': 0.959056813206903, 'min_gain_to_split': 0.02370900733699723}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:30:20,874] Trial 661 finished with value: 121.02691671907027 and parameters: {'num_leaves': 51, 'learning_rate': 0.09576957670957902, 'feature_fraction': 0.6711958852820961, 'bagging_fraction': 0.9617003115075513, 'bagging_freq': 10, 'lambda_l1': 2.2518134372853072e-07, 'lambda_l2': 0.007475552220551582, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 359, 'min_data_in_leaf': 33, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.897214410048973, 'min_gain_to_split': 0.035811835465677885}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:31:00,533] Trial 662 finished with value: 103.18125832366702 and parameters: {'num_leaves': 21, 'learning_rate': 0.20631137600999275, 'feature_fraction': 0.6366942638532942, 'bagging_fraction': 0.9776375709667421, 'bagging_freq': 10, 'lambda_l1': 1.2685825964658416e-07, 'lambda_l2': 0.017410993086645097, 'min_child_samples': 45, 'max_depth': 10, 'max_bin': 312, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.45343255793839327, 'min_gain_to_split': 0.01066255417016031}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:32:05,078] Trial 663 finished with value: 137.7377071197879 and parameters: {'num_leaves': 19, 'learning_rate': 0.048621232001909126, 'feature_fraction': 0.623120132227303, 'bagging_fraction': 0.9496903960812308, 'bagging_freq': 10, 'lambda_l1': 6.259505888223144e-05, 'lambda_l2': 0.03235499782092122, 'min_child_samples': 17, 'max_depth': 10, 'max_bin': 333, 'min_data_in_leaf': 64, 'extra_trees': True, 'early_stopping_rounds': 23, 'path_smooth': 0.973449905266675, 'min_gain_to_split': 0.27655182432879993}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:32:48,486] Trial 664 finished with value: 121.61135645376814 and parameters: {'num_leaves': 26, 'learning_rate': 0.166468789196463, 'feature_fraction': 0.6500681857625523, 'bagging_fraction': 0.8651405622416192, 'bagging_freq': 9, 'lambda_l1': 8.859198221584367e-06, 'lambda_l2': 0.014424867629371632, 'min_child_samples': 42, 'max_depth': 10, 'max_bin': 390, 'min_data_in_leaf': 43, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.4711379261176917, 'min_gain_to_split': 0.301529746940346}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:33:34,470] Trial 665 finished with value: 128.04937743888945 and parameters: {'num_leaves': 18, 'learning_rate': 0.1520937206761411, 'feature_fraction': 0.643927804563924, 'bagging_fraction': 0.9562818740302139, 'bagging_freq': 10, 'lambda_l1': 1.5135869908192486e-05, 'lambda_l2': 0.005343513751404, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 375, 'min_data_in_leaf': 54, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.39800376485228595, 'min_gain_to_split': 0.00015690813189055478}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:34:27,373] Trial 666 finished with value: 140.80613339759245 and parameters: {'num_leaves': 23, 'learning_rate': 0.10369039478322961, 'feature_fraction': 0.662279877466832, 'bagging_fraction': 0.9659604867722368, 'bagging_freq': 6, 'lambda_l1': 3.9256853224525336e-06, 'lambda_l2': 0.023038819234746575, 'min_child_samples': 44, 'max_depth': 10, 'max_bin': 484, 'min_data_in_leaf': 67, 'extra_trees': True, 'early_stopping_rounds': 34, 'path_smooth': 0.9992763251194444, 'min_gain_to_split': 0.062145326844164135}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:35:15,122] Trial 667 finished with value: 116.7396360034123 and parameters: {'num_leaves': 17, 'learning_rate': 0.1365608822617826, 'feature_fraction': 0.6911746448177536, 'bagging_fraction': 0.8921084428036028, 'bagging_freq': 10, 'lambda_l1': 2.4666906361124998e-05, 'lambda_l2': 0.009481108512278822, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 495, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 32, 'path_smooth': 0.9391556355076955, 'min_gain_to_split': 0.29370615005675427}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:36:03,410] Trial 668 finished with value: 143.30595349110467 and parameters: {'num_leaves': 15, 'learning_rate': 0.12015923208088702, 'feature_fraction': 0.6131767353209122, 'bagging_fraction': 0.9741917799549531, 'bagging_freq': 10, 'lambda_l1': 2.794618240122379e-06, 'lambda_l2': 0.0002318770620417894, 'min_child_samples': 46, 'max_depth': 10, 'max_bin': 500, 'min_data_in_leaf': 72, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.5018525729320407, 'min_gain_to_split': 0.3209751357240991}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:36:53,322] Trial 669 finished with value: 129.19620441932938 and parameters: {'num_leaves': 21, 'learning_rate': 0.10968593440384007, 'feature_fraction': 0.6714554901584209, 'bagging_fraction': 0.7943271772481958, 'bagging_freq': 8, 'lambda_l1': 9.795170435630783e-07, 'lambda_l2': 0.09706281191874262, 'min_child_samples': 47, 'max_depth': 9, 'max_bin': 451, 'min_data_in_leaf': 40, 'extra_trees': True, 'early_stopping_rounds': 30, 'path_smooth': 0.33996562261522495, 'min_gain_to_split': 0.019637316349850498}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:37:35,426] Trial 670 finished with value: 119.78327036996777 and parameters: {'num_leaves': 25, 'learning_rate': 0.08366570864094679, 'feature_fraction': 0.6544327053587483, 'bagging_fraction': 0.7793570880419001, 'bagging_freq': 5, 'lambda_l1': 3.4391393748460767e-07, 'lambda_l2': 0.05304703196081978, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 349, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.4337174526920445, 'min_gain_to_split': 0.04184804451196455}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:39:16,584] Trial 671 finished with value: 122.77860877321578 and parameters: {'num_leaves': 19, 'learning_rate': 0.08975058213699036, 'feature_fraction': 0.6371586694351269, 'bagging_fraction': 0.9123442853934862, 'bagging_freq': 10, 'lambda_l1': 6.961410573952351e-06, 'lambda_l2': 0.018301773722370244, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 473, 'min_data_in_leaf': 66, 'extra_trees': False, 'early_stopping_rounds': 35, 'path_smooth': 0.9190258768343706, 'min_gain_to_split': 0.26094544322610913}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:40:04,667] Trial 672 finished with value: 120.74319668651637 and parameters: {'num_leaves': 20, 'learning_rate': 0.09848058183643853, 'feature_fraction': 0.678665463330781, 'bagging_fraction': 0.9403715959568266, 'bagging_freq': 10, 'lambda_l1': 1.965041284127298e-06, 'lambda_l2': 0.18320155507299216, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 381, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.9610029069865466, 'min_gain_to_split': 0.030460695259687136}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:40:48,336] Trial 673 finished with value: 119.70313242673463 and parameters: {'num_leaves': 22, 'learning_rate': 0.12718106623303393, 'feature_fraction': 0.6305674137408024, 'bagging_fraction': 0.9554448840720795, 'bagging_freq': 10, 'lambda_l1': 3.805530024558391e-05, 'lambda_l2': 0.0037069620122785227, 'min_child_samples': 42, 'max_depth': 7, 'max_bin': 363, 'min_data_in_leaf': 31, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.8793805777714834, 'min_gain_to_split': 0.01428898867829566}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:41:45,334] Trial 674 finished with value: 146.7244355093069 and parameters: {'num_leaves': 17, 'learning_rate': 0.05975572130715802, 'feature_fraction': 0.6449237805382328, 'bagging_fraction': 0.9949596445540365, 'bagging_freq': 9, 'lambda_l1': 5.997642676633642e-07, 'lambda_l2': 2.8760590786307802e-06, 'min_child_samples': 46, 'max_depth': 10, 'max_bin': 371, 'min_data_in_leaf': 69, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.6908331480008327, 'min_gain_to_split': 0.07433320608559776}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:42:42,280] Trial 675 finished with value: 136.2132081870468 and parameters: {'num_leaves': 27, 'learning_rate': 0.1437348070895679, 'feature_fraction': 0.666303780618762, 'bagging_fraction': 0.9839373387701846, 'bagging_freq': 10, 'lambda_l1': 0.0001298643482201222, 'lambda_l2': 0.040525347818762825, 'min_child_samples': 44, 'max_depth': 10, 'max_bin': 482, 'min_data_in_leaf': 63, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.41210182308817295, 'min_gain_to_split': 0.3100319694358048}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:43:27,837] Trial 676 finished with value: 102.34625444553406 and parameters: {'num_leaves': 24, 'learning_rate': 0.11234792369572515, 'feature_fraction': 0.6551199032059565, 'bagging_fraction': 0.9701468568944596, 'bagging_freq': 9, 'lambda_l1': 1.611699653933324e-05, 'lambda_l2': 0.0111459467348506, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 352, 'min_data_in_leaf': 26, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.376015733360659, 'min_gain_to_split': 0.026818931642977217}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:44:12,735] Trial 677 finished with value: 128.1061670587735 and parameters: {'num_leaves': 56, 'learning_rate': 0.12331071477389953, 'feature_fraction': 0.6612678409363935, 'bagging_fraction': 0.9483644138172254, 'bagging_freq': 10, 'lambda_l1': 1.298915624112955e-06, 'lambda_l2': 0.026975525010982684, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 323, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.9425145521716374, 'min_gain_to_split': 0.04977119122628859}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:45:04,798] Trial 678 finished with value: 143.2728837506795 and parameters: {'num_leaves': 19, 'learning_rate': 0.10477332224754672, 'feature_fraction': 0.6851480234031142, 'bagging_fraction': 0.9327327433002836, 'bagging_freq': 8, 'lambda_l1': 9.680503341249801e-06, 'lambda_l2': 0.06736355064496731, 'min_child_samples': 40, 'max_depth': 10, 'max_bin': 469, 'min_data_in_leaf': 68, 'extra_trees': True, 'early_stopping_rounds': 33, 'path_smooth': 0.46270760135556294, 'min_gain_to_split': 0.03843668279880033}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:45:50,733] Trial 679 finished with value: 123.94113608507182 and parameters: {'num_leaves': 21, 'learning_rate': 0.13384786049089095, 'feature_fraction': 0.6748536191881647, 'bagging_fraction': 0.962355305031495, 'bagging_freq': 10, 'lambda_l1': 3.59811337820286e-06, 'lambda_l2': 0.006932932581801306, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 492, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.43172808571677596, 'min_gain_to_split': 0.10185747703343745}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:46:32,605] Trial 680 finished with value: 136.6471630839635 and parameters: {'num_leaves': 15, 'learning_rate': 0.1723010588350535, 'feature_fraction': 0.648624594079951, 'bagging_fraction': 0.9183338391012186, 'bagging_freq': 10, 'lambda_l1': 4.766084913267631e-05, 'lambda_l2': 0.015103511694774467, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 398, 'min_data_in_leaf': 65, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9810094793806464, 'min_gain_to_split': 0.33131289998736857}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:47:22,581] Trial 681 finished with value: 118.95416869140186 and parameters: {'num_leaves': 23, 'learning_rate': 0.11544071457503319, 'feature_fraction': 0.6406844736467119, 'bagging_fraction': 0.9683491097246554, 'bagging_freq': 10, 'lambda_l1': 2.1916954391156045e-06, 'lambda_l2': 0.002433047484372486, 'min_child_samples': 45, 'max_depth': 10, 'max_bin': 484, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.9095165283113513, 'min_gain_to_split': 0.01061006119267207}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:48:11,568] Trial 682 finished with value: 129.66288044047926 and parameters: {'num_leaves': 17, 'learning_rate': 0.09707376792633113, 'feature_fraction': 0.625681368167196, 'bagging_fraction': 0.9788749252960899, 'bagging_freq': 9, 'lambda_l1': 0.0016812685274630707, 'lambda_l2': 0.03434999362820256, 'min_child_samples': 47, 'max_depth': 10, 'max_bin': 360, 'min_data_in_leaf': 71, 'extra_trees': True, 'early_stopping_rounds': 21, 'path_smooth': 0.39411770853713063, 'min_gain_to_split': 0.28984073159309215}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:48:54,062] Trial 683 finished with value: 132.03370189340015 and parameters: {'num_leaves': 20, 'learning_rate': 0.15475538249568213, 'feature_fraction': 0.6567778069283015, 'bagging_fraction': 0.8214374634218851, 'bagging_freq': 10, 'lambda_l1': 1.4032885636698935e-07, 'lambda_l2': 1.3025722330942223e-05, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 476, 'min_data_in_leaf': 42, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.6312031143418941, 'min_gain_to_split': 0.12633878583679695}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:49:36,752] Trial 684 finished with value: 115.94557451605321 and parameters: {'num_leaves': 18, 'learning_rate': 0.10925745998762737, 'feature_fraction': 0.6632545783655159, 'bagging_fraction': 0.9262192406006031, 'bagging_freq': 9, 'lambda_l1': 1.2741855359124449e-05, 'lambda_l2': 0.009627849708215739, 'min_child_samples': 47, 'max_depth': 10, 'max_bin': 340, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.9577719846581583, 'min_gain_to_split': 0.023138883314085052}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:50:27,284] Trial 685 finished with value: 119.22606918687589 and parameters: {'num_leaves': 25, 'learning_rate': 0.08968242252319708, 'feature_fraction': 0.6360851268137782, 'bagging_fraction': 0.9527957348377593, 'bagging_freq': 10, 'lambda_l1': 5.7335124373653765e-06, 'lambda_l2': 0.021733400638491027, 'min_child_samples': 45, 'max_depth': 10, 'max_bin': 385, 'min_data_in_leaf': 45, 'extra_trees': True, 'early_stopping_rounds': 36, 'path_smooth': 0.4136642145729573, 'min_gain_to_split': 0.3189668514904321}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:51:20,604] Trial 686 finished with value: 149.00246015119194 and parameters: {'num_leaves': 41, 'learning_rate': 0.12469259536040968, 'feature_fraction': 0.6682173578408402, 'bagging_fraction': 0.9429310246502515, 'bagging_freq': 8, 'lambda_l1': 2.7122858064849557e-05, 'lambda_l2': 0.1389333315485111, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 464, 'min_data_in_leaf': 66, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.4440134719890197, 'min_gain_to_split': 0.05473366050483572}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:52:09,368] Trial 687 finished with value: 139.94942268690107 and parameters: {'num_leaves': 31, 'learning_rate': 0.10174425321566888, 'feature_fraction': 0.6468751480310272, 'bagging_fraction': 0.856256347788895, 'bagging_freq': 7, 'lambda_l1': 7.015891250170602e-07, 'lambda_l2': 0.04771641080766055, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 369, 'min_data_in_leaf': 64, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.9257999610116061, 'min_gain_to_split': 0.2739891473860334}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:52:57,808] Trial 688 finished with value: 119.92471481770147 and parameters: {'num_leaves': 22, 'learning_rate': 0.11772495547498818, 'feature_fraction': 0.76623382568194, 'bagging_fraction': 0.9043983157475862, 'bagging_freq': 10, 'lambda_l1': 0.000548598093650766, 'lambda_l2': 0.014503495024408692, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 500, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.9671347572071105, 'min_gain_to_split': 0.03608144794740609}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:53:49,854] Trial 689 finished with value: 135.99485241268226 and parameters: {'num_leaves': 18, 'learning_rate': 0.14319583799818794, 'feature_fraction': 0.6780664632945784, 'bagging_fraction': 0.9597037784411514, 'bagging_freq': 10, 'lambda_l1': 1.621223705923947e-08, 'lambda_l2': 6.420894215815842, 'min_child_samples': 44, 'max_depth': 8, 'max_bin': 488, 'min_data_in_leaf': 68, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.5398659930759886, 'min_gain_to_split': 0.30470650564408097}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:54:46,393] Trial 690 finished with value: 117.94663227014601 and parameters: {'num_leaves': 20, 'learning_rate': 0.03859217001213293, 'feature_fraction': 0.6202177912961863, 'bagging_fraction': 0.9741380583961907, 'bagging_freq': 10, 'lambda_l1': 0.00018453436893414046, 'lambda_l2': 0.07791770675229365, 'min_child_samples': 49, 'max_depth': 3, 'max_bin': 332, 'min_data_in_leaf': 60, 'extra_trees': False, 'early_stopping_rounds': 31, 'path_smooth': 0.47801330484552484, 'min_gain_to_split': 0.14234988787444183}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:55:30,462] Trial 691 finished with value: 111.02098246106364 and parameters: {'num_leaves': 23, 'learning_rate': 0.10724224680830974, 'feature_fraction': 0.6545608553924047, 'bagging_fraction': 0.8429591303934535, 'bagging_freq': 10, 'lambda_l1': 2.502331459820345e-07, 'lambda_l2': 0.3248140069828197, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 443, 'min_data_in_leaf': 23, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.35206074249327035, 'min_gain_to_split': 0.08657928809506243}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:56:10,183] Trial 692 finished with value: 113.60135744656023 and parameters: {'num_leaves': 25, 'learning_rate': 0.13443558203745612, 'feature_fraction': 0.7012900202482575, 'bagging_fraction': 0.8707927016074722, 'bagging_freq': 9, 'lambda_l1': 8.991541562269786e-05, 'lambda_l2': 0.005573592220813877, 'min_child_samples': 46, 'max_depth': 10, 'max_bin': 348, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 34, 'path_smooth': 0.8907781908351884, 'min_gain_to_split': 0.16289404278185793}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:56:58,765] Trial 693 finished with value: 135.8511527741603 and parameters: {'num_leaves': 17, 'learning_rate': 0.09480638925845669, 'feature_fraction': 0.6408409010714274, 'bagging_fraction': 0.9888348332921765, 'bagging_freq': 10, 'lambda_l1': 0.07121464226469104, 'lambda_l2': 0.023861534576513032, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 376, 'min_data_in_leaf': 48, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.985488867146249, 'min_gain_to_split': 0.025861856354192254}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:57:51,315] Trial 694 finished with value: 134.9299997876717 and parameters: {'num_leaves': 21, 'learning_rate': 0.1187484162494676, 'feature_fraction': 0.6080702780556496, 'bagging_fraction': 0.9629211694962201, 'bagging_freq': 9, 'lambda_l1': 4.255786214294178e-06, 'lambda_l2': 0.009152586070927582, 'min_child_samples': 41, 'max_depth': 10, 'max_bin': 477, 'min_data_in_leaf': 51, 'extra_trees': True, 'early_stopping_rounds': 32, 'path_smooth': 0.42946733618684585, 'min_gain_to_split': 0.3379617442897376}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:58:39,523] Trial 695 finished with value: 137.90637981511 and parameters: {'num_leaves': 15, 'learning_rate': 0.15793791362370474, 'feature_fraction': 0.8513307160896846, 'bagging_fraction': 0.9457294068062138, 'bagging_freq': 10, 'lambda_l1': 2.0036357658549054e-05, 'lambda_l2': 0.03632266998111326, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 358, 'min_data_in_leaf': 62, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.9388569401952194, 'min_gain_to_split': 0.015304883075779301}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 01:59:30,640] Trial 696 finished with value: 114.66229480054794 and parameters: {'num_leaves': 27, 'learning_rate': 0.12881727357990833, 'feature_fraction': 0.6848603122324883, 'bagging_fraction': 0.8977766701729913, 'bagging_freq': 10, 'lambda_l1': 1.1853824443067097e-06, 'lambda_l2': 0.01470372658953788, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 469, 'min_data_in_leaf': 40, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.4536692675936391, 'min_gain_to_split': 0.31568083559391247}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:00:27,320] Trial 697 finished with value: 144.40913444285232 and parameters: {'num_leaves': 19, 'learning_rate': 0.1004289538224542, 'feature_fraction': 0.6316583950711238, 'bagging_fraction': 0.9812237696879523, 'bagging_freq': 10, 'lambda_l1': 4.4343136485679756e-07, 'lambda_l2': 0.10442267291802271, 'min_child_samples': 47, 'max_depth': 10, 'max_bin': 490, 'min_data_in_leaf': 81, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.3994486666683348, 'min_gain_to_split': 0.036310535198198886}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:01:14,714] Trial 698 finished with value: 145.6758154719151 and parameters: {'num_leaves': 23, 'learning_rate': 0.1108615057513124, 'feature_fraction': 0.8106239133480002, 'bagging_fraction': 0.9545991234790318, 'bagging_freq': 10, 'lambda_l1': 7.597223786558939e-06, 'lambda_l2': 0.017858823852855085, 'min_child_samples': 44, 'max_depth': 10, 'max_bin': 365, 'min_data_in_leaf': 69, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.9989596871920721, 'min_gain_to_split': 0.2967152808748128}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:02:18,424] Trial 699 finished with value: 136.10714309143742 and parameters: {'num_leaves': 21, 'learning_rate': 0.09099209857634169, 'feature_fraction': 0.8251400641665363, 'bagging_fraction': 0.9680572394506357, 'bagging_freq': 10, 'lambda_l1': 2.4876585104889286e-06, 'lambda_l2': 0.050170896072595984, 'min_child_samples': 49, 'max_depth': 9, 'max_bin': 456, 'min_data_in_leaf': 57, 'extra_trees': True, 'early_stopping_rounds': 30, 'path_smooth': 0.9491448363015393, 'min_gain_to_split': 0.04555926028470258}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:03:04,708] Trial 700 finished with value: 121.18579021238106 and parameters: {'num_leaves': 17, 'learning_rate': 0.17867516831921731, 'feature_fraction': 0.6704490701483989, 'bagging_fraction': 0.759408823761269, 'bagging_freq': 8, 'lambda_l1': 1.2600355034807766e-05, 'lambda_l2': 0.007184088162357103, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 482, 'min_data_in_leaf': 33, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.3785273575387966, 'min_gain_to_split': 0.24398136972707013}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:03:52,237] Trial 701 finished with value: 144.20440979351335 and parameters: {'num_leaves': 19, 'learning_rate': 0.08061514344246606, 'feature_fraction': 0.6509110279367963, 'bagging_fraction': 0.9114080366061171, 'bagging_freq': 10, 'lambda_l1': 9.080408823920428e-07, 'lambda_l2': 0.025598827357590413, 'min_child_samples': 11, 'max_depth': 10, 'max_bin': 316, 'min_data_in_leaf': 67, 'extra_trees': True, 'early_stopping_rounds': 23, 'path_smooth': 0.9229084172897468, 'min_gain_to_split': 0.28361518063653907}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:04:40,865] Trial 702 finished with value: 113.82656542795439 and parameters: {'num_leaves': 24, 'learning_rate': 0.14151500851642004, 'feature_fraction': 0.9977221969930261, 'bagging_fraction': 0.9394480027017524, 'bagging_freq': 10, 'lambda_l1': 7.073666361351872e-08, 'lambda_l2': 0.011355167769124389, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 494, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.9637312089691552, 'min_gain_to_split': 0.4465458585474404}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:05:27,277] Trial 703 finished with value: 148.60238587015607 and parameters: {'num_leaves': 16, 'learning_rate': 0.10513501694965681, 'feature_fraction': 0.6618589989675757, 'bagging_fraction': 0.9172752821507048, 'bagging_freq': 9, 'lambda_l1': 1.6572427742657032e-06, 'lambda_l2': 0.06704849175453566, 'min_child_samples': 32, 'max_depth': 10, 'max_bin': 305, 'min_data_in_leaf': 65, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.8635482194512867, 'min_gain_to_split': 0.2675016483108718}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:06:11,932] Trial 704 finished with value: 118.2533073328256 and parameters: {'num_leaves': 29, 'learning_rate': 0.11812458109779998, 'feature_fraction': 0.6450986876621686, 'bagging_fraction': 0.8490891280361407, 'bagging_freq': 7, 'lambda_l1': 2.0757385890210283e-05, 'lambda_l2': 0.003901841556333498, 'min_child_samples': 42, 'max_depth': 9, 'max_bin': 341, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.7316004411646418, 'min_gain_to_split': 0.05950916865497878}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:06:57,795] Trial 705 finished with value: 148.7243531730801 and parameters: {'num_leaves': 22, 'learning_rate': 0.14857609604156216, 'feature_fraction': 0.6947117124784647, 'bagging_fraction': 0.8803032372415706, 'bagging_freq': 10, 'lambda_l1': 0.00032029359969944373, 'lambda_l2': 0.03391006775332064, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 381, 'min_data_in_leaf': 67, 'extra_trees': True, 'early_stopping_rounds': 33, 'path_smooth': 0.4134193796300913, 'min_gain_to_split': 0.018578230968402405}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:07:44,653] Trial 706 finished with value: 108.87220524477596 and parameters: {'num_leaves': 19, 'learning_rate': 0.12880510704931136, 'feature_fraction': 0.6323634498254654, 'bagging_fraction': 0.9338749829964176, 'bagging_freq': 10, 'lambda_l1': 5.4404023330969255e-06, 'lambda_l2': 0.18941109112654436, 'min_child_samples': 45, 'max_depth': 10, 'max_bin': 327, 'min_data_in_leaf': 30, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.9003553875711237, 'min_gain_to_split': 0.008077384181696873}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:08:28,970] Trial 707 finished with value: 116.8508050061846 and parameters: {'num_leaves': 96, 'learning_rate': 0.11260001179799636, 'feature_fraction': 0.6575119695604599, 'bagging_fraction': 0.9742109023223208, 'bagging_freq': 9, 'lambda_l1': 1.838570004981046e-07, 'lambda_l2': 0.02045615215219129, 'min_child_samples': 47, 'max_depth': 5, 'max_bin': 351, 'min_data_in_leaf': 40, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.4373568177079361, 'min_gain_to_split': 0.36815823043356566}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:09:29,496] Trial 708 finished with value: 143.7498082917613 and parameters: {'num_leaves': 86, 'learning_rate': 0.16498828130902113, 'feature_fraction': 0.6665448078470613, 'bagging_fraction': 0.9508388180687086, 'bagging_freq': 10, 'lambda_l1': 4.8387150016179596e-05, 'lambda_l2': 0.012008971434727221, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 472, 'min_data_in_leaf': 71, 'extra_trees': True, 'early_stopping_rounds': 30, 'path_smooth': 0.5033024263006196, 'min_gain_to_split': 0.029779972708116574}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:10:59,639] Trial 709 finished with value: 126.1558806438729 and parameters: {'num_leaves': 21, 'learning_rate': 0.09931988283593834, 'feature_fraction': 0.7272377556383827, 'bagging_fraction': 0.9593980461417395, 'bagging_freq': 8, 'lambda_l1': 5.592205723514534e-07, 'lambda_l2': 0.005690074707576548, 'min_child_samples': 46, 'max_depth': 10, 'max_bin': 373, 'min_data_in_leaf': 64, 'extra_trees': False, 'early_stopping_rounds': 19, 'path_smooth': 0.4667983307399116, 'min_gain_to_split': 0.3255155835615107}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:12:07,798] Trial 710 finished with value: 129.54428893604194 and parameters: {'num_leaves': 25, 'learning_rate': 0.12089169812469949, 'feature_fraction': 0.6757110644697928, 'bagging_fraction': 0.9241229146849086, 'bagging_freq': 10, 'lambda_l1': 3.390396905131133e-06, 'lambda_l2': 0.05084809314388101, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 486, 'min_data_in_leaf': 54, 'extra_trees': True, 'early_stopping_rounds': 22, 'path_smooth': 0.9772288695077808, 'min_gain_to_split': 0.040779779809736585}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:13:26,279] Trial 711 finished with value: 122.29127343911364 and parameters: {'num_leaves': 17, 'learning_rate': 0.0855807485331907, 'feature_fraction': 0.6503167463116769, 'bagging_fraction': 0.9648896992053062, 'bagging_freq': 10, 'lambda_l1': 3.3020123476350276e-08, 'lambda_l2': 0.12148114882211285, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 393, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.9326890953074697, 'min_gain_to_split': 0.03133532783407127}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:14:07,614] Trial 712 finished with value: 132.82666718297193 and parameters: {'num_leaves': 26, 'learning_rate': 0.13456930703222, 'feature_fraction': 0.6423186336876734, 'bagging_fraction': 0.9785583871564301, 'bagging_freq': 10, 'lambda_l1': 9.465316807526314e-06, 'lambda_l2': 0.03038666651542887, 'min_child_samples': 47, 'max_depth': 10, 'max_bin': 162, 'min_data_in_leaf': 70, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.950983111017594, 'min_gain_to_split': 0.3118831649945556}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:15:07,686] Trial 713 finished with value: 137.01887124783326 and parameters: {'num_leaves': 23, 'learning_rate': 0.10558647529023603, 'feature_fraction': 0.625494702106135, 'bagging_fraction': 0.9844264300986023, 'bagging_freq': 9, 'lambda_l1': 0.39726581970918967, 'lambda_l2': 0.017085236791583153, 'min_child_samples': 37, 'max_depth': 10, 'max_bin': 478, 'min_data_in_leaf': 62, 'extra_trees': True, 'early_stopping_rounds': 31, 'path_smooth': 0.4219073201046017, 'min_gain_to_split': 0.25629636776207215}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:16:02,809] Trial 714 finished with value: 141.4311336245203 and parameters: {'num_leaves': 20, 'learning_rate': 0.09705727882431599, 'feature_fraction': 0.6597466170097399, 'bagging_fraction': 0.9698084161199385, 'bagging_freq': 10, 'lambda_l1': 3.3510532807116e-05, 'lambda_l2': 0.007992262074656538, 'min_child_samples': 44, 'max_depth': 10, 'max_bin': 358, 'min_data_in_leaf': 66, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.48341672703635563, 'min_gain_to_split': 0.11063890691711119}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:16:48,594] Trial 715 finished with value: 126.32878993915105 and parameters: {'num_leaves': 15, 'learning_rate': 0.19151425169825986, 'feature_fraction': 0.6698954411419595, 'bagging_fraction': 0.9459613796352087, 'bagging_freq': 10, 'lambda_l1': 3.3128941580595857e-07, 'lambda_l2': 0.07256530010316536, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 462, 'min_data_in_leaf': 32, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.36565496823578114, 'min_gain_to_split': 0.3461187868914568}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:17:37,178] Trial 716 finished with value: 119.88944691202668 and parameters: {'num_leaves': 18, 'learning_rate': 0.11441913619867786, 'feature_fraction': 0.6355497226581402, 'bagging_fraction': 0.95502628315264, 'bagging_freq': 9, 'lambda_l1': 1.367724412801285e-06, 'lambda_l2': 0.011477944740893671, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 500, 'min_data_in_leaf': 20, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.39440670269994393, 'min_gain_to_split': 0.06893672298252737}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:18:24,497] Trial 717 finished with value: 109.24718911409266 and parameters: {'num_leaves': 75, 'learning_rate': 0.12411309447823365, 'feature_fraction': 0.6856469307895233, 'bagging_fraction': 0.9292033282282813, 'bagging_freq': 10, 'lambda_l1': 1.6948820230145405e-05, 'lambda_l2': 0.021912731769825968, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 148, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.44863130982681654, 'min_gain_to_split': 0.0013031381417460616}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:19:01,902] Trial 718 finished with value: 107.06423095905161 and parameters: {'num_leaves': 21, 'learning_rate': 0.15089405075211576, 'feature_fraction': 0.6157324305798747, 'bagging_fraction': 0.960164916093294, 'bagging_freq': 10, 'lambda_l1': 7.763726305621986e-06, 'lambda_l2': 0.03352374421400162, 'min_child_samples': 46, 'max_depth': 10, 'max_bin': 271, 'min_data_in_leaf': 28, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.9701168912903125, 'min_gain_to_split': 0.050480804134758514}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:19:51,130] Trial 719 finished with value: 121.43026238235731 and parameters: {'num_leaves': 24, 'learning_rate': 0.10862326221968194, 'feature_fraction': 0.6550736331859345, 'bagging_fraction': 0.9734365928629346, 'bagging_freq': 10, 'lambda_l1': 8.461006310000295e-07, 'lambda_l2': 0.015291728857647917, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 366, 'min_data_in_leaf': 42, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.9178399696668124, 'min_gain_to_split': 0.016980768396135795}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:20:30,154] Trial 720 finished with value: 119.77243137958139 and parameters: {'num_leaves': 18, 'learning_rate': 0.09334981348697177, 'feature_fraction': 0.6778507299345382, 'bagging_fraction': 0.9398473435425321, 'bagging_freq': 10, 'lambda_l1': 2.6672883201108773e-06, 'lambda_l2': 0.00834055729049573, 'min_child_samples': 45, 'max_depth': 10, 'max_bin': 228, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.9834380628737472, 'min_gain_to_split': 0.3017065714477817}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:21:19,667] Trial 721 finished with value: 140.06271958483325 and parameters: {'num_leaves': 27, 'learning_rate': 0.13799037859004165, 'feature_fraction': 0.6512367463273233, 'bagging_fraction': 0.8858511362437482, 'bagging_freq': 4, 'lambda_l1': 4.6623491075941265e-06, 'lambda_l2': 0.08263751945008271, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 337, 'min_data_in_leaf': 68, 'extra_trees': True, 'early_stopping_rounds': 32, 'path_smooth': 0.8873308689135124, 'min_gain_to_split': 0.020446958415712507}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:22:07,799] Trial 722 finished with value: 127.18138335968838 and parameters: {'num_leaves': 22, 'learning_rate': 0.09994263828696341, 'feature_fraction': 0.6430287711574878, 'bagging_fraction': 0.9932354861216225, 'bagging_freq': 9, 'lambda_l1': 1.3243402055775498e-05, 'lambda_l2': 0.002756079377552361, 'min_child_samples': 42, 'max_depth': 9, 'max_bin': 491, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 23, 'path_smooth': 0.946076814637524, 'min_gain_to_split': 0.2909555249315133}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:22:50,769] Trial 723 finished with value: 141.21581624654385 and parameters: {'num_leaves': 19, 'learning_rate': 0.12660682618382335, 'feature_fraction': 0.663769368649248, 'bagging_fraction': 0.8301262547145591, 'bagging_freq': 10, 'lambda_l1': 1.8323326790705185e-06, 'lambda_l2': 0.004687196254748629, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 410, 'min_data_in_leaf': 58, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.4141889149048786, 'min_gain_to_split': 0.09343845750825441}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:23:33,458] Trial 724 finished with value: 146.54996646266284 and parameters: {'num_leaves': 16, 'learning_rate': 0.11449500702003575, 'feature_fraction': 0.6714402486383576, 'bagging_fraction': 0.8614947553011635, 'bagging_freq': 10, 'lambda_l1': 1.4363354241722464e-08, 'lambda_l2': 0.04842362727203277, 'min_child_samples': 39, 'max_depth': 10, 'max_bin': 347, 'min_data_in_leaf': 64, 'extra_trees': True, 'early_stopping_rounds': 30, 'path_smooth': 0.26915338789477056, 'min_gain_to_split': 0.32409652334674877}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:24:18,417] Trial 725 finished with value: 117.81161938728323 and parameters: {'num_leaves': 21, 'learning_rate': 0.10471758652586519, 'feature_fraction': 0.6301764249757945, 'bagging_fraction': 0.9062242224708137, 'bagging_freq': 10, 'lambda_l1': 1.0317604180592261e-07, 'lambda_l2': 0.6074220026043904, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 482, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 35, 'path_smooth': 0.45546141800802337, 'min_gain_to_split': 0.033122573821480567}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:25:04,690] Trial 726 finished with value: 122.5999505250187 and parameters: {'num_leaves': 63, 'learning_rate': 0.16140556569630096, 'feature_fraction': 0.7104240030508451, 'bagging_fraction': 0.9658063338079879, 'bagging_freq': 9, 'lambda_l1': 2.5245325056514335e-05, 'lambda_l2': 0.02379842295498206, 'min_child_samples': 47, 'max_depth': 10, 'max_bin': 384, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 48, 'path_smooth': 0.43060953440510213, 'min_gain_to_split': 0.04497898026912851}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:25:49,199] Trial 727 finished with value: 114.13762172167455 and parameters: {'num_leaves': 23, 'learning_rate': 0.14695887397611512, 'feature_fraction': 0.6503094432929923, 'bagging_fraction': 0.9519756903953382, 'bagging_freq': 9, 'lambda_l1': 9.469937900636127e-05, 'lambda_l2': 0.0005061415260358116, 'min_child_samples': 30, 'max_depth': 10, 'max_bin': 373, 'min_data_in_leaf': 24, 'extra_trees': True, 'early_stopping_rounds': 33, 'path_smooth': 0.7854193338883384, 'min_gain_to_split': 0.00829792138909291}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:27:38,147] Trial 728 finished with value: 122.21516851048378 and parameters: {'num_leaves': 29, 'learning_rate': 0.08853299615395882, 'feature_fraction': 0.6003755418712221, 'bagging_fraction': 0.9176908850245639, 'bagging_freq': 10, 'lambda_l1': 5.241355067933296e-07, 'lambda_l2': 0.01116075693104633, 'min_child_samples': 44, 'max_depth': 10, 'max_bin': 470, 'min_data_in_leaf': 69, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.38686309144718406, 'min_gain_to_split': 0.23472901583814365}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:28:26,167] Trial 729 finished with value: 141.2075556975755 and parameters: {'num_leaves': 20, 'learning_rate': 0.11129827090156537, 'feature_fraction': 0.6395757314924855, 'bagging_fraction': 0.9870051203082205, 'bagging_freq': 10, 'lambda_l1': 6.909134416703319e-06, 'lambda_l2': 1.0689111914349897e-07, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 355, 'min_data_in_leaf': 66, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.3315304378012145, 'min_gain_to_split': 0.07903315664956631}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:29:14,166] Trial 730 finished with value: 121.850468125483 and parameters: {'num_leaves': 17, 'learning_rate': 0.12238111453918551, 'feature_fraction': 0.6619315928330358, 'bagging_fraction': 0.9467030666114682, 'bagging_freq': 10, 'lambda_l1': 3.668051279761205e-06, 'lambda_l2': 0.036407687058882185, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 485, 'min_data_in_leaf': 41, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.9376251892945423, 'min_gain_to_split': 0.025886621527349916}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:30:01,654] Trial 731 finished with value: 127.78095988102768 and parameters: {'num_leaves': 25, 'learning_rate': 0.09536491347230697, 'feature_fraction': 0.6853599206085565, 'bagging_fraction': 0.9578228688238831, 'bagging_freq': 2, 'lambda_l1': 0.00019437383742654463, 'lambda_l2': 0.01901996395050124, 'min_child_samples': 47, 'max_depth': 10, 'max_bin': 364, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.9132472671190417, 'min_gain_to_split': 0.2772300393688868}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:30:58,590] Trial 732 finished with value: 132.62234983089633 and parameters: {'num_leaves': 19, 'learning_rate': 0.13307086680654592, 'feature_fraction': 0.7574083082069217, 'bagging_fraction': 0.9684654709989178, 'bagging_freq': 10, 'lambda_l1': 1.0522260078699018e-05, 'lambda_l2': 0.1801417632568949, 'min_child_samples': 45, 'max_depth': 10, 'max_bin': 493, 'min_data_in_leaf': 72, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9991659625760945, 'min_gain_to_split': 0.30522831618459334}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:31:50,406] Trial 733 finished with value: 123.62141132910793 and parameters: {'num_leaves': 22, 'learning_rate': 0.10430440592108703, 'feature_fraction': 0.6550855937926023, 'bagging_fraction': 0.9755884692711047, 'bagging_freq': 8, 'lambda_l1': 6.0934434671310965e-05, 'lambda_l2': 0.09714597224334208, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 322, 'min_data_in_leaf': 49, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.4701577266176263, 'min_gain_to_split': 0.11932038565993441}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:32:39,515] Trial 734 finished with value: 138.96012010438602 and parameters: {'num_leaves': 15, 'learning_rate': 0.1171863304275132, 'feature_fraction': 0.6761867997970347, 'bagging_fraction': 0.9802804924622275, 'bagging_freq': 10, 'lambda_l1': 2.855373472777155e-07, 'lambda_l2': 0.00783380585023374, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 477, 'min_data_in_leaf': 61, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.9680757863913865, 'min_gain_to_split': 0.056514733857242094}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:33:26,555] Trial 735 finished with value: 135.83269837257336 and parameters: {'num_leaves': 18, 'learning_rate': 0.14173722328967525, 'feature_fraction': 0.693439886534407, 'bagging_fraction': 0.9325425429352129, 'bagging_freq': 8, 'lambda_l1': 9.437610841124589e-07, 'lambda_l2': 0.014740184688064682, 'min_child_samples': 40, 'max_depth': 10, 'max_bin': 331, 'min_data_in_leaf': 67, 'extra_trees': True, 'early_stopping_rounds': 31, 'path_smooth': 0.4052833349720955, 'min_gain_to_split': 0.33286278074442194}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:34:14,508] Trial 736 finished with value: 143.9678689962646 and parameters: {'num_leaves': 24, 'learning_rate': 0.10994994878164085, 'feature_fraction': 0.6451222329548023, 'bagging_fraction': 0.9217267541877546, 'bagging_freq': 10, 'lambda_l1': 1.588663425750614e-05, 'lambda_l2': 0.04625442174604683, 'min_child_samples': 38, 'max_depth': 10, 'max_bin': 377, 'min_data_in_leaf': 63, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.8460776230867314, 'min_gain_to_split': 0.041397302684625666}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:35:09,221] Trial 737 finished with value: 120.78070532119777 and parameters: {'num_leaves': 20, 'learning_rate': 0.1684021302578708, 'feature_fraction': 0.7779169489824985, 'bagging_fraction': 0.9612327609313378, 'bagging_freq': 10, 'lambda_l1': 2.223800125171184e-06, 'lambda_l2': 0.025763930545125994, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 467, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.1984716750376161, 'min_gain_to_split': 0.31573299837169805}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:35:58,413] Trial 738 finished with value: 111.47196653789243 and parameters: {'num_leaves': 26, 'learning_rate': 0.12493321710209261, 'feature_fraction': 0.62200091331955, 'bagging_fraction': 0.9109734766059516, 'bagging_freq': 9, 'lambda_l1': 3.545830972602764e-05, 'lambda_l2': 0.06052475284980462, 'min_child_samples': 46, 'max_depth': 10, 'max_bin': 346, 'min_data_in_leaf': 33, 'extra_trees': True, 'early_stopping_rounds': 34, 'path_smooth': 0.9564893927248214, 'min_gain_to_split': 0.02047814854145919}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:37:15,112] Trial 739 finished with value: 136.87169556224507 and parameters: {'num_leaves': 81, 'learning_rate': 0.09814456133949731, 'feature_fraction': 0.666718286009646, 'bagging_fraction': 0.9422176471076409, 'bagging_freq': 10, 'lambda_l1': 2.1588359074298388e-08, 'lambda_l2': 0.006228417379188796, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 492, 'min_data_in_leaf': 69, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.43919881479739936, 'min_gain_to_split': 0.012137450880734497}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:38:06,330] Trial 740 finished with value: 143.09452048226208 and parameters: {'num_leaves': 22, 'learning_rate': 0.0782811074645764, 'feature_fraction': 0.6371867327457497, 'bagging_fraction': 0.9508392075127254, 'bagging_freq': 10, 'lambda_l1': 4.2757047527903354e-08, 'lambda_l2': 0.012432462937925484, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 283, 'min_data_in_leaf': 65, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.3638968739209595, 'min_gain_to_split': 0.0294956660109539}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:39:00,815] Trial 741 finished with value: 127.26513112681009 and parameters: {'num_leaves': 17, 'learning_rate': 0.09123379511055942, 'feature_fraction': 0.6578237740795998, 'bagging_fraction': 0.9698220993336202, 'bagging_freq': 10, 'lambda_l1': 5.601173297507733e-06, 'lambda_l2': 0.02138954037516494, 'min_child_samples': 50, 'max_depth': 8, 'max_bin': 355, 'min_data_in_leaf': 52, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.9061169106413118, 'min_gain_to_split': 0.28842682592758634}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:39:47,493] Trial 742 finished with value: 121.35153836346095 and parameters: {'num_leaves': 20, 'learning_rate': 0.1537721003330812, 'feature_fraction': 0.794846476153413, 'bagging_fraction': 0.954918046886134, 'bagging_freq': 8, 'lambda_l1': 1.3417922061006575e-06, 'lambda_l2': 0.1268796852744436, 'min_child_samples': 36, 'max_depth': 10, 'max_bin': 387, 'min_data_in_leaf': 44, 'extra_trees': True, 'early_stopping_rounds': 23, 'path_smooth': 0.8135395115628179, 'min_gain_to_split': 0.26385781767798744}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:40:36,284] Trial 743 finished with value: 130.645838598265 and parameters: {'num_leaves': 16, 'learning_rate': 0.18212081706928654, 'feature_fraction': 0.6477861195773194, 'bagging_fraction': 0.8939875625182062, 'bagging_freq': 9, 'lambda_l1': 1.995008297533758e-05, 'lambda_l2': 0.03918122010517712, 'min_child_samples': 44, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 56, 'extra_trees': True, 'early_stopping_rounds': 21, 'path_smooth': 0.9998708402564611, 'min_gain_to_split': 0.038532627179711856}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:41:27,731] Trial 744 finished with value: 125.8960117266992 and parameters: {'num_leaves': 23, 'learning_rate': 0.1180639695725959, 'feature_fraction': 0.6293165108071046, 'bagging_fraction': 0.9022126913810811, 'bagging_freq': 10, 'lambda_l1': 2.1522228399341195e-07, 'lambda_l2': 0.2496889927936585, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 456, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9321075541918619, 'min_gain_to_split': 0.050521914059086646}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:42:25,825] Trial 745 finished with value: 125.42095019549981 and parameters: {'num_leaves': 19, 'learning_rate': 0.13044706623551866, 'feature_fraction': 0.6702825228150083, 'bagging_fraction': 0.9366699931623786, 'bagging_freq': 10, 'lambda_l1': 8.86791288501225e-06, 'lambda_l2': 0.0042635950908180365, 'min_child_samples': 46, 'max_depth': 9, 'max_bin': 365, 'min_data_in_leaf': 46, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.7083418906617671, 'min_gain_to_split': 0.06606159293478046}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:43:17,611] Trial 746 finished with value: 117.4801540582558 and parameters: {'num_leaves': 21, 'learning_rate': 0.10452444279196205, 'feature_fraction': 0.661569333873007, 'bagging_fraction': 0.964324540853216, 'bagging_freq': 10, 'lambda_l1': 4.09005975933759e-07, 'lambda_l2': 0.00990256213485589, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 500, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.41725320471293365, 'min_gain_to_split': 0.008604091723516578}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:48:58,290] Trial 747 finished with value: 131.94212605652194 and parameters: {'num_leaves': 60, 'learning_rate': 0.015431985347524706, 'feature_fraction': 0.6797529071632511, 'bagging_fraction': 0.9821671306582929, 'bagging_freq': 10, 'lambda_l1': 0.006093814206350636, 'lambda_l2': 0.016274731004285736, 'min_child_samples': 42, 'max_depth': 10, 'max_bin': 486, 'min_data_in_leaf': 66, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.5699528737454613, 'min_gain_to_split': 0.311270072008238}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:49:49,887] Trial 748 finished with value: 123.68700986907042 and parameters: {'num_leaves': 24, 'learning_rate': 0.11174516136044911, 'feature_fraction': 0.652412101095146, 'bagging_fraction': 0.9750044227842729, 'bagging_freq': 3, 'lambda_l1': 7.00718418979285e-07, 'lambda_l2': 0.028190639587831034, 'min_child_samples': 45, 'max_depth': 10, 'max_bin': 336, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 32, 'path_smooth': 0.9686568681077725, 'min_gain_to_split': 0.0236874655458656}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:50:37,938] Trial 749 finished with value: 115.75244949584439 and parameters: {'num_leaves': 27, 'learning_rate': 0.1347284475367635, 'feature_fraction': 0.6383230734201731, 'bagging_fraction': 0.9476498804239178, 'bagging_freq': 6, 'lambda_l1': 3.3841041783246635e-06, 'lambda_l2': 0.06363501395546274, 'min_child_samples': 47, 'max_depth': 10, 'max_bin': 397, 'min_data_in_leaf': 40, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.38505012525732424, 'min_gain_to_split': 0.1755177395611931}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:51:11,361] Trial 750 finished with value: 114.07059599983533 and parameters: {'num_leaves': 18, 'learning_rate': 0.09989996568705344, 'feature_fraction': 0.6136629417489978, 'bagging_fraction': 0.9259942710969422, 'bagging_freq': 9, 'lambda_l1': 4.933696178953812e-06, 'lambda_l2': 0.0015196420379787357, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 171, 'min_data_in_leaf': 22, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.50014471513431, 'min_gain_to_split': 0.29818468845798735}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:52:03,720] Trial 751 finished with value: 120.10555455023582 and parameters: {'num_leaves': 16, 'learning_rate': 0.08404945034396075, 'feature_fraction': 0.6450254618166565, 'bagging_fraction': 0.9587302546044236, 'bagging_freq': 7, 'lambda_l1': 1.5188814677421786e-07, 'lambda_l2': 0.009633511817755009, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 474, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 34, 'path_smooth': 0.4553638883287202, 'min_gain_to_split': 0.32467278227143953}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:52:42,503] Trial 752 finished with value: 140.20243868372395 and parameters: {'num_leaves': 20, 'learning_rate': 0.12127835228302354, 'feature_fraction': 0.6660860737815566, 'bagging_fraction': 0.9656938667766951, 'bagging_freq': 10, 'lambda_l1': 1.0381300396681314e-08, 'lambda_l2': 0.031876823367045615, 'min_child_samples': 41, 'max_depth': 10, 'max_bin': 123, 'min_data_in_leaf': 70, 'extra_trees': True, 'early_stopping_rounds': 30, 'path_smooth': 0.9514772606295249, 'min_gain_to_split': 0.00029618494057214286}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:53:32,781] Trial 753 finished with value: 139.98476272241433 and parameters: {'num_leaves': 22, 'learning_rate': 0.14364354980422, 'feature_fraction': 0.6573445159625204, 'bagging_fraction': 0.987280203177819, 'bagging_freq': 10, 'lambda_l1': 2.265157899174784e-06, 'lambda_l2': 0.006123696158412489, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 373, 'min_data_in_leaf': 68, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.48073509884209525, 'min_gain_to_split': 0.25380940752758085}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:54:26,861] Trial 754 finished with value: 144.75268560540798 and parameters: {'num_leaves': 24, 'learning_rate': 0.10540217252760647, 'feature_fraction': 0.6329336404336827, 'bagging_fraction': 0.9152397538131285, 'bagging_freq': 10, 'lambda_l1': 0.00013346657873466143, 'lambda_l2': 0.016318759986048828, 'min_child_samples': 44, 'max_depth': 6, 'max_bin': 487, 'min_data_in_leaf': 86, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.875995340789628, 'min_gain_to_split': 0.2724117091919834}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:55:19,696] Trial 755 finished with value: 144.539657945409 and parameters: {'num_leaves': 18, 'learning_rate': 0.0918535754210164, 'feature_fraction': 0.6852515115881221, 'bagging_fraction': 0.8550792648231448, 'bagging_freq': 9, 'lambda_l1': 0.00040993576221269926, 'lambda_l2': 0.08314612069600286, 'min_child_samples': 47, 'max_depth': 10, 'max_bin': 363, 'min_data_in_leaf': 65, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.43382894225459123, 'min_gain_to_split': 0.03255312163980974}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:56:03,081] Trial 756 finished with value: 136.88508285177525 and parameters: {'num_leaves': 15, 'learning_rate': 0.11533438335893087, 'feature_fraction': 0.6725366533261388, 'bagging_fraction': 0.952327013493988, 'bagging_freq': 10, 'lambda_l1': 1.4807050851016007e-05, 'lambda_l2': 0.02155090233945219, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 316, 'min_data_in_leaf': 63, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9825017016397188, 'min_gain_to_split': 0.01753325091902056}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:56:46,080] Trial 757 finished with value: 129.5836570434578 and parameters: {'num_leaves': 21, 'learning_rate': 0.12979006591283906, 'feature_fraction': 0.622864824279032, 'bagging_fraction': 0.9733952673331308, 'bagging_freq': 10, 'lambda_l1': 2.3431196274546684e-05, 'lambda_l2': 4.937391954506767e-05, 'min_child_samples': 44, 'max_depth': 10, 'max_bin': 343, 'min_data_in_leaf': 59, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.4019170098663825, 'min_gain_to_split': 0.043325852841621985}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:57:34,343] Trial 758 finished with value: 138.84898008833935 and parameters: {'num_leaves': 26, 'learning_rate': 0.1602634688344922, 'feature_fraction': 0.6501722573881578, 'bagging_fraction': 0.9453670951128109, 'bagging_freq': 8, 'lambda_l1': 1.1618102111673749e-05, 'lambda_l2': 0.041211006057321684, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 352, 'min_data_in_leaf': 67, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9312789082827241, 'min_gain_to_split': 0.02785057436507688}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:58:14,960] Trial 759 finished with value: 117.0702276133956 and parameters: {'num_leaves': 19, 'learning_rate': 0.11095686771709153, 'feature_fraction': 0.6588050018670768, 'bagging_fraction': 0.9615036859911894, 'bagging_freq': 10, 'lambda_l1': 1.3901446933135282e-06, 'lambda_l2': 0.010989709277239745, 'min_child_samples': 50, 'max_depth': 4, 'max_bin': 467, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.30545578004493873, 'min_gain_to_split': 0.3373539716550539}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:59:04,171] Trial 760 finished with value: 114.65021849907257 and parameters: {'num_leaves': 23, 'learning_rate': 0.09869188871151498, 'feature_fraction': 0.6423729546909317, 'bagging_fraction': 0.994818644977024, 'bagging_freq': 9, 'lambda_l1': 4.423040928708853e-05, 'lambda_l2': 0.12252036109938645, 'min_child_samples': 45, 'max_depth': 10, 'max_bin': 380, 'min_data_in_leaf': 31, 'extra_trees': True, 'early_stopping_rounds': 31, 'path_smooth': 0.5195881338659227, 'min_gain_to_split': 0.1025058559606039}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 02:59:56,149] Trial 761 finished with value: 136.0930604235104 and parameters: {'num_leaves': 17, 'learning_rate': 0.12094560658521382, 'feature_fraction': 0.6652024861219978, 'bagging_fraction': 0.977978417331276, 'bagging_freq': 10, 'lambda_l1': 6.94225064912428e-06, 'lambda_l2': 0.02776526142195766, 'min_child_samples': 48, 'max_depth': 9, 'max_bin': 479, 'min_data_in_leaf': 74, 'extra_trees': True, 'early_stopping_rounds': 40, 'path_smooth': 0.8968350284924901, 'min_gain_to_split': 0.05885507364852697}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 03:00:43,918] Trial 762 finished with value: 123.28027550209276 and parameters: {'num_leaves': 29, 'learning_rate': 0.10303319251943174, 'feature_fraction': 0.6952997793283615, 'bagging_fraction': 0.9374944624711422, 'bagging_freq': 10, 'lambda_l1': 6.547503803451605e-07, 'lambda_l2': 0.01583642663863118, 'min_child_samples': 46, 'max_depth': 10, 'max_bin': 494, 'min_data_in_leaf': 40, 'extra_trees': True, 'early_stopping_rounds': 11, 'path_smooth': 0.9604015258081633, 'min_gain_to_split': 0.3219327101272075}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 03:01:35,174] Trial 763 finished with value: 129.75432631468442 and parameters: {'num_leaves': 43, 'learning_rate': 0.14873097155125337, 'feature_fraction': 0.6740734108383194, 'bagging_fraction': 0.9705189177706689, 'bagging_freq': 10, 'lambda_l1': 7.255944108285283e-08, 'lambda_l2': 0.0028924678002727588, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 370, 'min_data_in_leaf': 55, 'extra_trees': True, 'early_stopping_rounds': 33, 'path_smooth': 0.4427441130430636, 'min_gain_to_split': 0.3111303791636467}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 03:02:12,894] Trial 764 finished with value: 115.96056169829706 and parameters: {'num_leaves': 20, 'learning_rate': 0.13901118243908894, 'feature_fraction': 0.6349510009072088, 'bagging_fraction': 0.956818170774751, 'bagging_freq': 9, 'lambda_l1': 2.89133089748964e-06, 'lambda_l2': 0.05467071482821269, 'min_child_samples': 47, 'max_depth': 10, 'max_bin': 325, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 37, 'path_smooth': 0.9208992330400313, 'min_gain_to_split': 0.4059359908247936}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 03:03:13,340] Trial 765 finished with value: 137.0525896339631 and parameters: {'num_leaves': 22, 'learning_rate': 0.08744885050760211, 'feature_fraction': 0.7175011319575213, 'bagging_fraction': 0.8689189233092081, 'bagging_freq': 10, 'lambda_l1': 3.3686312470383707e-07, 'lambda_l2': 0.006100333393590583, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 484, 'min_data_in_leaf': 61, 'extra_trees': True, 'early_stopping_rounds': 35, 'path_smooth': 0.41700119446418005, 'min_gain_to_split': 0.13302447931983363}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 03:03:55,854] Trial 766 finished with value: 116.3793196703489 and parameters: {'num_leaves': 17, 'learning_rate': 0.10965750535555518, 'feature_fraction': 0.6522777051205338, 'bagging_fraction': 0.9115453423517725, 'bagging_freq': 10, 'lambda_l1': 2.7352828699190434e-05, 'lambda_l2': 0.0080873203023533, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 196, 'min_data_in_leaf': 43, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.6482051301225327, 'min_gain_to_split': 0.287917784059454}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 03:04:43,739] Trial 767 finished with value: 109.66689812991815 and parameters: {'num_leaves': 24, 'learning_rate': 0.1252178411621942, 'feature_fraction': 0.646470052167186, 'bagging_fraction': 0.9275021967946122, 'bagging_freq': 10, 'lambda_l1': 4.991251207635926e-06, 'lambda_l2': 0.013269618707093247, 'min_child_samples': 28, 'max_depth': 10, 'max_bin': 473, 'min_data_in_leaf': 26, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.9832445324086625, 'min_gain_to_split': 0.03793426071756056}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 03:05:37,699] Trial 768 finished with value: 147.3743495000959 and parameters: {'num_leaves': 19, 'learning_rate': 0.09680754622406137, 'feature_fraction': 0.8813606839915593, 'bagging_fraction': 0.984618058473799, 'bagging_freq': 10, 'lambda_l1': 7.272895954860149e-05, 'lambda_l2': 0.024187215209642867, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 252, 'min_data_in_leaf': 69, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.4702364393766673, 'min_gain_to_split': 0.009988439684562946}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 03:06:18,749] Trial 769 finished with value: 110.94268002025233 and parameters: {'num_leaves': 15, 'learning_rate': 0.17691699563408403, 'feature_fraction': 0.6797501394627911, 'bagging_fraction': 0.9217718374501556, 'bagging_freq': 9, 'lambda_l1': 9.86661077428953e-07, 'lambda_l2': 0.03865208749229794, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 355, 'min_data_in_leaf': 38, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.372633829065103, 'min_gain_to_split': 7.419981458848743e-05}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 03:07:11,018] Trial 770 finished with value: 141.53851825777014 and parameters: {'num_leaves': 25, 'learning_rate': 0.11322487665390359, 'feature_fraction': 0.6649851409137325, 'bagging_fraction': 0.8440053142223298, 'bagging_freq': 8, 'lambda_l1': 1.0325616565205762e-05, 'lambda_l2': 0.0798665511105821, 'min_child_samples': 45, 'max_depth': 10, 'max_bin': 342, 'min_data_in_leaf': 64, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.9481985491726279, 'min_gain_to_split': 0.0225873222073874}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 03:08:03,889] Trial 771 finished with value: 130.17335896880212 and parameters: {'num_leaves': 21, 'learning_rate': 0.19929614647887134, 'feature_fraction': 0.6565600040064239, 'bagging_fraction': 0.9648319434244099, 'bagging_freq': 10, 'lambda_l1': 0.00023009590614256301, 'lambda_l2': 0.01871810486160738, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 459, 'min_data_in_leaf': 67, 'extra_trees': True, 'early_stopping_rounds': 30, 'path_smooth': 0.39431041459380484, 'min_gain_to_split': 0.3002550256342464}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 03:08:58,018] Trial 772 finished with value: 109.48086607501236 and parameters: {'num_leaves': 34, 'learning_rate': 0.10394437186887365, 'feature_fraction': 0.6396682872288899, 'bagging_fraction': 0.9504794852228295, 'bagging_freq': 10, 'lambda_l1': 1.98603675116687e-06, 'lambda_l2': 0.42272593792896695, 'min_child_samples': 42, 'max_depth': 9, 'max_bin': 492, 'min_data_in_leaf': 33, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.4287847909469684, 'min_gain_to_split': 0.21678337292101527}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 03:10:13,918] Trial 773 finished with value: 111.74810300489153 and parameters: {'num_leaves': 18, 'learning_rate': 0.018941265384108837, 'feature_fraction': 0.6263280769185585, 'bagging_fraction': 0.9791993663033649, 'bagging_freq': 10, 'lambda_l1': 3.564360872995183e-06, 'lambda_l2': 0.010764682673029073, 'min_child_samples': 46, 'max_depth': 10, 'max_bin': 361, 'min_data_in_leaf': 28, 'extra_trees': True, 'early_stopping_rounds': 15, 'path_smooth': 0.3513393785023222, 'min_gain_to_split': 0.3861004236289958}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 03:10:57,313] Trial 774 finished with value: 107.57591419286345 and parameters: {'num_leaves': 27, 'learning_rate': 0.130088077060192, 'feature_fraction': 0.690474825426594, 'bagging_fraction': 0.9427842990389484, 'bagging_freq': 10, 'lambda_l1': 8.212692729073123e-06, 'lambda_l2': 0.004706860368803758, 'min_child_samples': 34, 'max_depth': 10, 'max_bin': 389, 'min_data_in_leaf': 25, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.9662250357822383, 'min_gain_to_split': 0.03383556938497562}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 03:11:52,372] Trial 775 finished with value: 125.29698555865926 and parameters: {'num_leaves': 22, 'learning_rate': 0.09427702862756875, 'feature_fraction': 0.6736005322369425, 'bagging_fraction': 0.9555592635711931, 'bagging_freq': 9, 'lambda_l1': 4.79398348649131e-07, 'lambda_l2': 0.03137669819466106, 'min_child_samples': 47, 'max_depth': 10, 'max_bin': 481, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 20, 'path_smooth': 0.7541080297164773, 'min_gain_to_split': 0.04871850558564596}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 03:12:35,654] Trial 776 finished with value: 141.74530944847905 and parameters: {'num_leaves': 20, 'learning_rate': 0.12282350667857204, 'feature_fraction': 0.6494724012587121, 'bagging_fraction': 0.9704859803131058, 'bagging_freq': 9, 'lambda_l1': 1.4500168413789547e-05, 'lambda_l2': 0.06566467400016648, 'min_child_samples': 44, 'max_depth': 10, 'max_bin': 307, 'min_data_in_leaf': 76, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.456899432299029, 'min_gain_to_split': 0.2784297113240496}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 03:13:32,294] Trial 777 finished with value: 138.57993022697298 and parameters: {'num_leaves': 23, 'learning_rate': 0.11546302420854712, 'feature_fraction': 0.6604068686908996, 'bagging_fraction': 0.9323172652362822, 'bagging_freq': 10, 'lambda_l1': 0.1549203303254916, 'lambda_l2': 0.21015494303217006, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 369, 'min_data_in_leaf': 71, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9999836685821439, 'min_gain_to_split': 0.017504298627977366}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 03:14:20,348] Trial 778 finished with value: 139.9820934918256 and parameters: {'num_leaves': 17, 'learning_rate': 0.13917908941032223, 'feature_fraction': 0.6319052205543477, 'bagging_fraction': 0.9076590271002105, 'bagging_freq': 10, 'lambda_l1': 1.56912073036233e-06, 'lambda_l2': 0.015793113022997393, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 334, 'min_data_in_leaf': 66, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.6014691273354867, 'min_gain_to_split': 0.07234850010411593}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 03:15:04,554] Trial 779 finished with value: 117.7836299017471 and parameters: {'num_leaves': 25, 'learning_rate': 0.15417513730529134, 'feature_fraction': 0.7053938561395704, 'bagging_fraction': 0.9903823982078465, 'bagging_freq': 10, 'lambda_l1': 1.060127478529038e-07, 'lambda_l2': 0.11218459912171937, 'min_child_samples': 26, 'max_depth': 10, 'max_bin': 472, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.9384870137090754, 'min_gain_to_split': 0.15175409641247878}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 03:15:45,913] Trial 780 finished with value: 133.0924564548069 and parameters: {'num_leaves': 19, 'learning_rate': 0.16889079615862504, 'feature_fraction': 0.6420533160720011, 'bagging_fraction': 0.963123735263755, 'bagging_freq': 8, 'lambda_l1': 2.479873208159019e-07, 'lambda_l2': 0.046425061981998084, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 298, 'min_data_in_leaf': 64, 'extra_trees': True, 'early_stopping_rounds': 22, 'path_smooth': 0.9193314562555015, 'min_gain_to_split': 0.026768678652439495}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 03:16:40,230] Trial 781 finished with value: 113.47316089414703 and parameters: {'num_leaves': 21, 'learning_rate': 0.06576687503645337, 'feature_fraction': 0.6198935457982849, 'bagging_fraction': 0.8493864630057083, 'bagging_freq': 10, 'lambda_l1': 2.989525609020595e-05, 'lambda_l2': 0.0001024406024552537, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 500, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 28, 'path_smooth': 0.41433067776939625, 'min_gain_to_split': 0.26571609883886926}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 03:17:37,854] Trial 782 finished with value: 134.2498606141691 and parameters: {'num_leaves': 17, 'learning_rate': 0.07440868977131894, 'feature_fraction': 0.667331374480809, 'bagging_fraction': 0.8982314649457349, 'bagging_freq': 7, 'lambda_l1': 0.0010950509984649927, 'lambda_l2': 0.008072093705575958, 'min_child_samples': 47, 'max_depth': 10, 'max_bin': 382, 'min_data_in_leaf': 53, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.48976357139558757, 'min_gain_to_split': 0.3081982308302321}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 03:18:23,847] Trial 783 finished with value: 130.2758306505229 and parameters: {'num_leaves': 15, 'learning_rate': 0.08389104830548492, 'feature_fraction': 0.6833912195173846, 'bagging_fraction': 0.8385927001392208, 'bagging_freq': 10, 'lambda_l1': 6.20373573722406e-06, 'lambda_l2': 0.025570689531753045, 'min_child_samples': 24, 'max_depth': 10, 'max_bin': 492, 'min_data_in_leaf': 42, 'extra_trees': True, 'early_stopping_rounds': 32, 'path_smooth': 0.8958915731607074, 'min_gain_to_split': 0.3306200362841736}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 03:19:04,745] Trial 784 finished with value: 151.93666591069297 and parameters: {'num_leaves': 19, 'learning_rate': 0.10808667233518572, 'feature_fraction': 0.6546914147221891, 'bagging_fraction': 0.8766028483661055, 'bagging_freq': 10, 'lambda_l1': 7.102666684262727e-07, 'lambda_l2': 0.012069535253920073, 'min_child_samples': 41, 'max_depth': 10, 'max_bin': 347, 'min_data_in_leaf': 69, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.4486757940856694, 'min_gain_to_split': 0.08507766775695688}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 03:20:39,870] Trial 785 finished with value: 112.94393250597363 and parameters: {'num_leaves': 23, 'learning_rate': 0.10143188587311247, 'feature_fraction': 0.6473085273085529, 'bagging_fraction': 0.9486042294521245, 'bagging_freq': 9, 'lambda_l1': 4.184350499532172e-08, 'lambda_l2': 0.019375353189188725, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 484, 'min_data_in_leaf': 50, 'extra_trees': False, 'early_stopping_rounds': 33, 'path_smooth': 0.021206502476853184, 'min_gain_to_split': 0.35939944600320006}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 03:21:36,498] Trial 786 finished with value: 141.31686632410484 and parameters: {'num_leaves': 28, 'learning_rate': 0.09231806921312356, 'feature_fraction': 0.6577956874645954, 'bagging_fraction': 0.9395960163386192, 'bagging_freq': 10, 'lambda_l1': 1.1199606253053821e-06, 'lambda_l2': 0.004140097597309821, 'min_child_samples': 48, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 62, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.982919641765072, 'min_gain_to_split': 0.23964443551095316}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 03:22:19,487] Trial 787 finished with value: 111.0677084003574 and parameters: {'num_leaves': 21, 'learning_rate': 0.117427100422794, 'feature_fraction': 0.6361322283763446, 'bagging_fraction': 0.9739571567914658, 'bagging_freq': 10, 'lambda_l1': 2.209430554948189e-08, 'lambda_l2': 0.05323831387671234, 'min_child_samples': 45, 'max_depth': 10, 'max_bin': 360, 'min_data_in_leaf': 30, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.9632268878294241, 'min_gain_to_split': 0.04781117627974818}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}

[I 2025-07-14 03:23:04,615] Trial 788 finished with value: 111.29473651694619 and parameters: {'num_leaves': 53, 'learning_rate': 0.13029234087438643, 'feature_fraction': 0.6717772540370822, 'bagging_fraction': 0.8887508440038063, 'bagging_freq': 10, 'lambda_l1': 4.124916386111299e-06, 'lambda_l2': 0.15850050323163212, 'min_child_samples': 50, 'max_depth': 10, 'max_bin': 451, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.9436288910461358, 'min_gain_to_split': 0.31760807751623843}. Best is trial 257 with value: 0.44357105642948386.

Mejor trial hasta ahora: RMSE=0.443571, Parámetros={'num_leaves': 24, 'learning_rate': 0.08756616330710833, 'feature_fraction': 0.6330071641441583, 'bagging_fraction': 0.9678808037613486, 'bagging_freq': 10, 'lambda_l1': 1.1634123907122364e-08, 'lambda_l2': 0.047286936432928375, 'min_child_samples': 43, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 29, 'path_smooth': 0.9996568294482207, 'min_gain_to_split': 0.03491779707899573}
Estudio guardado en: sqlite:///optuna_studies_v22.db

Mejores hiperparámetros encontrados:
num_leaves: 24
learning_rate: 0.08756616330710833
feature_fraction: 0.6330071641441583
bagging_fraction: 0.9678808037613486
bagging_freq: 10
lambda_l1: 1.1634123907122364e-08
lambda_l2: 0.047286936432928375
min_child_samples: 43
max_depth: 10
max_bin: 479
min_data_in_leaf: 37
extra_trees: True
early_stopping_rounds: 29
path_smooth: 0.9996568294482207
min_gain_to_split: 0.03491779707899573

(<optuna.study.study.Study at 0x1cf87870210>,
 {'num_leaves': 24,
  'learning_rate': 0.08756616330710833,
  'feature_fraction': 0.6330071641441583,
  'bagging_fraction': 0.9678808037613486,
  'bagging_freq': 10,
  'lambda_l1': 1.1634123907122364e-08,
  'lambda_l2': 0.047286936432928375,
  'min_child_samples': 43,
  'max_depth': 10,
  'max_bin': 479,
  'min_data_in_leaf': 37,
  'extra_trees': True,
  'early_stopping_rounds': 29,
  'path_smooth': 0.9996568294482207,
  'min_gain_to_split': 0.03491779707899573,
  'objective': 'regression',
  'metric': 'rmse',
  'boosting_type': 'gbdt',
  'verbosity': -1})

Prediccion

In [71]:
df_future = model_lgb_simple.semillerio_en_prediccion_con_pesos(train, test, version="v22")

In [72]:
df_future

       periodo  product_id  target      pred
30476   201912       20001     0.0  0.744316
30477   201912       20002     0.0  0.353683
30478   201912       20003     0.0 -0.050623
30479   201912       20004     0.0  0.743757
30480   201912       20005     0.0  0.510273
...        ...         ...     ...       ...
31357   201912       21265     0.0  1.267023
31358   201912       21266     0.0 -0.337602
31359   201912       21267     0.0 -5.911647
31360   201912       21271     0.0 -0.513513
31361   201912       21276     0.0  9.035025

[886 rows x 4 columns]

Filtramos los 180 productos

In [76]:
productos_ok = pd.read_csv("../../data/raw/product_id_apredecir201912.csv", sep="\t")
df_future = df_future[df_future['periodo'] == 201912]
df_future = df_future[df_future['product_id'].isin(productos_ok['product_id'].unique())]

In [78]:
df_future

       periodo  product_id  target      pred
30476   201912       20001     0.0  0.744316
30477   201912       20002     0.0  0.353683
30478   201912       20003     0.0 -0.050623
30479   201912       20004     0.0  0.743757
30480   201912       20005     0.0  0.510273
...        ...         ...     ...       ...
31355   201912       21263     0.0 -0.717058
31357   201912       21265     0.0  1.267023
31358   201912       21266     0.0 -0.337602
31359   201912       21267     0.0 -5.911647
31361   201912       21276     0.0  9.035025

[780 rows x 4 columns]

In [79]:
df_future_copy = df_future.copy()

In [80]:
import os
ruta_archivo = f'./datasets/tn_stats_201906.csv'
    
df_stats = pd.DataFrame()

if os.path.exists(ruta_archivo) and ruta_archivo.endswith('.csv'):
    df_stats = pd.read_csv(ruta_archivo, sep=',')

df_stats

      product_id      tn_mean      tn_std
0          20001  1375.882837  310.489330
1          20002   962.547075  258.093361
2          20003   892.114038  307.871182
3          20004   665.386502  225.992372
4          20005   627.744458  220.138757
...          ...          ...         ...
1111       21271     0.026155    0.020938
1112       21273     0.057242    0.124272
1113       21274     0.067028    0.096980
1114       21276     0.089478    0.030062
1115       21281     0.021060    0.031414

[1116 rows x 3 columns]

In [81]:
df_future_copy = df_future_copy.merge(df_stats, on=['product_id'], how='left')
df_future_copy

     periodo  product_id  target      pred      tn_mean      tn_std
0     201912       20001     0.0  0.744316  1375.882837  310.489330
1     201912       20002     0.0  0.353683   962.547075  258.093361
2     201912       20003     0.0 -0.050623   892.114038  307.871182
3     201912       20004     0.0  0.743757   665.386502  225.992372
4     201912       20005     0.0  0.510273   627.744458  220.138757
..       ...         ...     ...       ...          ...         ...
775   201912       21263     0.0 -0.717058     0.133198    0.178028
776   201912       21265     0.0  1.267023     0.151885    0.136228
777   201912       21266     0.0 -0.337602     0.151885    0.134848
778   201912       21267     0.0 -5.911647     0.160505    0.073935
779   201912       21276     0.0  9.035025     0.089478    0.030062

[780 rows x 6 columns]

In [82]:

df_future_copy['tn'] = df_future_copy['pred'] * df_future_copy['tn_std'] + df_future_copy['tn_mean']
df_future_copy

,periodo,product_id,target,pred,tn_mean,tn_std,tn
0,201912,20001,0.0,0.744316,1375.882837,310.489330,1606.984862
1,201912,20002,0.0,0.353683,962.547075,258.093361,1053.830220
2,201912,20003,0.0,-0.050623,892.114038,307.871182,876.528653
3,201912,20004,0.0,0.743757,665.386502,225.992372,833.469882
4,201912,20005,0.0,0.510273,627.744458,220.138757,740.075351
...,...,...,...,...,...,...,...
775,201912,21263,0.0,-0.717058,0.133198,0.178028,0.005541
776,201912,21265,0.0,1.267023,0.151885,0.136228,0.324488
777,201912,21266,0.0,-0.337602,0.151885,0.134848,0.106360
778,201912,21267,0.0,-5.911647,0.160505,0.073935,-0.276571
779,201912,21276,0.0,9.035025,0.089478,0.030062,0.361087

Vemos cuantos negativos hay

In [83]:
df_future_copy[df_future_copy['tn'] < 0]

     periodo  product_id  target       pred     tn_mean     tn_std          tn
27    201912       20028     0.0  -7.330667  272.583402  72.774864 -260.904923
142   201912       20168     0.0  -3.042174   55.091778  21.561215  -10.501185
172   201912       20211     0.0  -5.002917   40.769387  11.408079  -16.304291
266   201912       20325     0.0  -1.826853   22.116357  12.551165   -0.812780
307   201912       20379     0.0  -3.550195   16.493350   5.841961   -4.246752
329   201912       20408     0.0  -4.162707   23.317603   7.136667   -6.390249
369   201912       20477     0.0  -4.763937   22.091404   7.804544  -15.088949
379   201912       20491     0.0  -2.167091   19.221130   9.400429   -1.150452
389   201912       20510     0.0  -2.555218   33.025903  13.501399   -1.473119
394   201912       20521     0.0  -2.306823   25.250207  12.197611   -2.887518
413   201912       20548     0.0  -6.538538   24.747545   6.194771  -15.757204
460   201912       20617     0.0  -3.591229    6.675988   2.529617   -2.408448
511   201912       20689     0.0  -9.207997   10.857210   2.957304  -16.373639
529   201912       20715     0.0  -4.434112    3.902711   1.172641   -1.296911
559   201912       20771     0.0  -2.117761    3.595532   1.723456   -0.054337
575   201912       20802     0.0  -2.928887    2.753383   1.228473   -0.844676
583   201912       20817     0.0 -11.629001    7.828730   2.264659  -18.506993
641   201912       20932     0.0  -2.396231    2.982335   1.377765   -0.319108
687   201912       21033     0.0  -6.708457    2.165118   0.669381   -2.325395
702   201912       21064     0.0  -6.246111    2.777970   0.849090   -2.525540
712   201912       21088     0.0  -8.178104    0.560924   0.202358   -1.093979
727   201912       21131     0.0  -5.269159    0.323497   0.099125   -0.198807
730   201912       21142     0.0  -1.307589    0.505803   0.520037   -0.174192
733   201912       21153     0.0  -3.699946    0.645348   0.262375   -0.325426
737   201912       21159     0.0  -3.304270    0.604720   0.225690   -0.141021
741   201912       21168     0.0  -6.451667    0.573926   0.214431   -0.809513
745   201912       21179     0.0  -4.653590    0.570530   0.135019   -0.057793
753   201912       21196     0.0  -7.167478    0.568063   0.153575   -0.532682
778   201912       21267     0.0  -5.911647    0.160505   0.073935   -0.276571

Reemplazamos los negativos por el promedio de ultimos 12 meses

In [88]:
promedio780 = model_lgb.promedio_12_meses_780p()
promedio780.rename(columns={"tn":"tn_780"}, inplace=True)
df_future_copy = df_future_copy.merge(promedio780, on='product_id', how='left')
df_future_copy.drop(columns=['target','periodo'], inplace=True)
df_future_copy.loc[df_future_copy['tn'] < 0, 'tn'] = df_future_copy['tn_780']
df_future_copy

     product_id      pred      tn_mean      tn_std           tn       tn_780
0         20001  0.744316  1375.882837  310.489330  1606.984862  1454.732720
1         20002  0.353683   962.547075  258.093361  1053.830220  1175.437142
2         20003 -0.050623   892.114038  307.871182   876.528653   784.976407
3         20004  0.743757   665.386502  225.992372   833.469882   627.215328
4         20005  0.510273   627.744458  220.138757   740.075351   668.270104
..          ...       ...          ...         ...          ...          ...
775       21263 -0.717058     0.133198    0.178028     0.005541     0.029993
776       21265  1.267023     0.151885    0.136228     0.324488     0.089541
777       21266 -0.337602     0.151885    0.134848     0.106360     0.094659
778       21267 -5.911647     0.160505    0.073935     0.092835     0.092835
779       21276  9.035025     0.089478    0.030062     0.361087     0.045447

[780 rows x 6 columns]

Reemplazo NaN

In [93]:
promedio780 = model_lgb.promedio_12_meses_780p()
promedio780.rename(columns={"tn":"tn_780"}, inplace=True)
df_future_copy = df_future_copy.merge(promedio780, on='product_id', how='left')
# df_future_copy.drop(columns=['target','periodo'], inplace=True)
df_future_copy.loc[df_future_copy['tn'].isna(), 'tn'] = df_future_copy['tn_780']
df_future_copy

,product_id,pred,tn_mean,tn_std,tn,tn_780_x,tn_780_y,tn_780
0,20001,0.744316,1375.882837,310.489330,1606.984862,1454.732720,1454.732720,1454.732720
1,20002,0.353683,962.547075,258.093361,1053.830220,1175.437142,1175.437142,1175.437142
2,20003,-0.050623,892.114038,307.871182,876.528653,784.976407,784.976407,784.976407
3,20004,0.743757,665.386502,225.992372,833.469882,627.215328,627.215328,627.215328
4,20005,0.510273,627.744458,220.138757,740.075351,668.270104,668.270104,668.270104
...,...,...,...,...,...,...,...,...
775,21263,-0.717058,0.133198,0.178028,0.005541,0.029993,0.029993,0.029993
776,21265,1.267023,0.151885,0.136228,0.324488,0.089541,0.089541,0.089541
777,21266,-0.337602,0.151885,0.134848,0.106360,0.094659,0.094659,0.094659
778,21267,-5.911647,0.160505,0.073935,0.092835,0.092835,0.092835,0.092835
779,21276,9.035025,0.089478,0.030062,0.361087,0.045447,0.045447,0.045447

In [94]:
df_future_copy

,product_id,pred,tn_mean,tn_std,tn,tn_780_x,tn_780_y,tn_780
0,20001,0.744316,1375.882837,310.489330,1606.984862,1454.732720,1454.732720,1454.732720
1,20002,0.353683,962.547075,258.093361,1053.830220,1175.437142,1175.437142,1175.437142
2,20003,-0.050623,892.114038,307.871182,876.528653,784.976407,784.976407,784.976407
3,20004,0.743757,665.386502,225.992372,833.469882,627.215328,627.215328,627.215328
4,20005,0.510273,627.744458,220.138757,740.075351,668.270104,668.270104,668.270104
...,...,...,...,...,...,...,...,...
775,21263,-0.717058,0.133198,0.178028,0.005541,0.029993,0.029993,0.029993
776,21265,1.267023,0.151885,0.136228,0.324488,0.089541,0.089541,0.089541
777,21266,-0.337602,0.151885,0.134848,0.106360,0.094659,0.094659,0.094659
778,21267,-5.911647,0.160505,0.073935,0.092835,0.092835,0.092835,0.092835
779,21276,9.035025,0.089478,0.030062,0.361087,0.045447,0.045447,0.045447

Guardamos el archivo

In [95]:
# df_future_copy.drop(columns=['tn'], inplace=True)
# df_future_copy.rename(columns={'pred': 'tn'}, inplace=True)
df_future_copy[['product_id', 'tn']].to_csv("./outputs/predicciones_exp_09_lgb_v1.csv", index=False, sep=',')

Ensemble

In [31]:
df_lgb = df_future_copy[['product_id', 'tn']].rename(columns={'tn': 'tn_lgb'})
df_rl = pd.read_csv("./outputs/predicciones_regresion_lineal_v1.csv", sep=',', encoding='utf-8').rename(columns={'tn': 'tn_rl'})
df_ensemble = df_lgb.merge(df_rl, on='product_id', how='left')
df_ensemble['tn'] = (df_ensemble['tn_lgb'] + df_ensemble['tn_rl']) / 2
df_ensemble[['product_id', 'tn']].to_csv("./outputs/predicciones_exp_07_lgb_v6_ensemble.csv", index=False, sep=',')

In [32]:
df_lgb = df_future_copy[['product_id', 'tn']].rename(columns={'tn': 'tn_lgb'})
df_rl = pd.read_csv("./outputs/predicciones_regresion_lineal_v1.csv", sep=',', encoding='utf-8').rename(columns={'tn': 'tn_rl'})
df_ag = pd.read_csv("./outputs/prediccion_autogluon_2ventanas.csv", sep=',', encoding='utf-8').rename(columns={'tn': 'tn_ag'})
df_ensemble = df_lgb.merge(df_rl, on='product_id', how='left')
df_ensemble = df_ensemble.merge(df_ag, on='product_id', how='left')
df_ensemble['tn'] = (df_ensemble['tn_lgb'] + df_ensemble['tn_rl'] + df_ensemble['tn_ag']) / 3
df_ensemble[['product_id', 'tn']].to_csv("./outputs/predicciones_exp_07_lgb_v6_ensemble_3models.csv", index=False, sep=',')