In [21]:
import pandas as pd
import numpy as np
import importlib
import gc
import sys
import warnings
sys.path.append('./scripts')  
import preprocesamiento
import feature_engineering
import model_lgb
importlib.reload(preprocesamiento)
importlib.reload(model_lgb)
importlib.reload(feature_engineering)
warnings.filterwarnings("ignore")

# Experimento 7: 
- LGBM
- Estandarizacion del target
- Usando funcion entrenamiento: semillerio_en_prediccion
- Mismas variables
- Pesos: (log o max?)
- sqlite:///optuna_studies_v16.db
- Kaggle =  0.30

##### Levantamos el dataset con target ya calculado

In [2]:
df = pd.read_csv("./datasets/periodo_x_producto_con_target_transformado_201912.csv", sep=',', encoding='utf-8')
print("Dataset sin transformar tenia esto: (31362, 19)")
df.shape

Dataset sin transformar tenia esto: (31362, 19)

(31362, 35)

In [3]:
columnas_baseline = df.columns.tolist()
columnas_baseline

['product_id',
 'periodo',
 'nacimiento_producto',
 'muerte_producto',
 'mes_n',
 'total_meses',
 'producto_nuevo',
 'ciclo_de_vida_inicial',
 'cat1',
 'cat2',
 'cat3',
 'brand',
 'sku_size',
 'stock_final',
 'tn',
 'plan_precios_cuidados',
 'cust_request_qty',
 'cust_request_tn',
 'target',
 'tn_mean',
 'tn_std',
 'tn_zscore',
 'stock_final_mean',
 'stock_final_std',
 'stock_final_zscore',
 'cust_request_qty_mean',
 'cust_request_qty_std',
 'cust_request_qty_zscore',
 'cust_request_tn_mean',
 'cust_request_tn_std',
 'cust_request_tn_zscore',
 'tn_log',
 'stock_final_log',
 'cust_request_qty_log',
 'cust_request_tn_log']

##### Preprocesamiento a la minima expresión :)

In [4]:
df = feature_engineering.create_category_features_cat1(df)
df = feature_engineering.create_category_features_cat2(df)
df = feature_engineering.create_category_features_cat3(df)

In [5]:
# ##### aplicamos OHE
df = preprocesamiento.aplicarOHE(df)
df.shape

(31362, 187)

### Feature Engineering

##### Neural Prophet

In [6]:
neural_prophet_fe = pd.read_csv("./datasets/features_neuralprophet_completo.csv", sep=',', encoding='utf-8')
neural_prophet_fe['ds'] = pd.to_datetime(neural_prophet_fe['ds'], errors='coerce')
# Versión alternativa más robusta:
neural_prophet_fe['periodo'] = neural_prophet_fe['ds'].apply(
    lambda x: x.year * 100 + x.month if pd.notnull(x) else None
)
neural_prophet_fe = neural_prophet_fe[['periodo', 'product_id', 'trend', "season_yearly", "season_monthly"]]
df = df.merge(neural_prophet_fe, on=['periodo', 'product_id'], how='left')
df.shape

(31362, 190)

##### Prophet

In [7]:
prophet_fe = pd.read_csv("./datasets/prophet_features_tn_zscore.csv", sep=',', encoding='utf-8')
prophet_fe['ds'] = pd.to_datetime(prophet_fe['ds'], errors='coerce')
prophet_fe['periodo'] = prophet_fe['ds'].apply(
    lambda x: x.year * 100 + x.month if pd.notnull(x) else None
)
prophet_fe = prophet_fe[['periodo', 'product_id', 'trend_add', "yearly_add", "additive_terms", 'trend_mult', 'yearly_mult', 'multiplicative_terms']]
df = df.merge(prophet_fe, on=['periodo', 'product_id'], how='left')
df.shape

(31362, 196)

##### FE Moviles

In [8]:
df = feature_engineering.get_lags(df, "tn", 201912)
df = feature_engineering.get_delta_lags(df, "tn", 24)
df = feature_engineering.get_rolling_means(df, "tn", 201912)
df = feature_engineering.get_rolling_stds(df, "tn", 201912)
df = feature_engineering.get_rolling_mins(df, "tn", 201912)
df = feature_engineering.get_rolling_maxs(df, "tn", 201912)
df = feature_engineering.get_rolling_medians(df, "tn", 201912)
df = feature_engineering.get_rolling_skewness(df, "tn", 201912)
df = feature_engineering.get_autocorrelaciones(df, "tn", 201912)
df.shape

(31362, 758)

In [9]:
df = feature_engineering.get_lags(df, "cust_request_qty", 201912)
df = feature_engineering.get_delta_lags(df, "cust_request_qty", 24)
df = feature_engineering.get_rolling_means(df, "cust_request_qty", 201912)
df = feature_engineering.get_rolling_stds(df, "cust_request_qty", 201912)
df = feature_engineering.get_rolling_mins(df, "cust_request_qty", 201912)
df = feature_engineering.get_rolling_maxs(df, "cust_request_qty", 201912)
df.shape

(31362, 1213)

In [10]:
df = feature_engineering.get_lags(df, "stock_final", 201912)
df = feature_engineering.get_delta_lags(df, "stock_final", 24)
df = feature_engineering.get_rolling_means(df, "stock_final", 201912)
df = feature_engineering.get_rolling_stds(df, "stock_final", 201912)
df = feature_engineering.get_rolling_mins(df, "stock_final", 201912)
df = feature_engineering.get_rolling_maxs(df, "stock_final", 201912)
df.shape

(31362, 1668)

Features Diana

In [ ]:
df = feature_engineering.calcular_diferencia_con_medias_moviles(df)
df = feature_engineering.calcular_ratios_con_medias_moviles(df)
df.shape

(31362, 1704)

##### FE Moviles sobre otras variables

In [56]:
# #  stock final
# df = feature_engineering.get_lagsEspecificos(df, col='stock_final_zscore')
# df = feature_engineering.get_delta_lags_especificos(df, col='stock_final_zscore')
# df = feature_engineering.get_rolling_means_especificos(df, col='stock_final_zscore')
# df = feature_engineering.get_rolling_stds_especificos(df, col='stock_final_zscore')
# df = feature_engineering.get_rolling_medians_especificos(df, col='stock_final_zscore')
# df = feature_engineering.get_rolling_mins_especificos(df, col='stock_final_zscore')
# df = feature_engineering.get_rolling_maxs_especificos(df, col='stock_final_zscore')
# df = feature_engineering.get_rolling_skewness_especificos(df, col='stock_final_zscore')

#  cust_request_qty
# df = feature_engineering.get_lagsEspecificos(df, col='cust_request_qty')
# df = feature_engineering.get_delta_lags_especificos(df, col='cust_request_qty')
# df = feature_engineering.get_rolling_means_especificos(df, col='cust_request_qty')
# df = feature_engineering.get_rolling_stds_especificos(df, col='cust_request_qty')
# df = feature_engineering.get_rolling_mins_especificos(df, col='cust_request_qty')
# df = feature_engineering.get_rolling_maxs_especificos(df, col='cust_request_qty')
# df = feature_engineering.get_rolling_medians_especificos(df, col='cust_request_qty')
# df = feature_engineering.get_rolling_skewness_especificos(df, col='cust_request_qty')

##### FE Calendario

In [12]:
df = feature_engineering.generar_ids(df)
df = feature_engineering.get_componentesTemporales(df)
df = feature_engineering.get_anomaliasPoliticas(df)
# df = feature_engineering.descomposicion_serie_temporal(df, col='tn')
df.shape

(31362, 1729)

##### FE sobre FE

In [13]:
df = feature_engineering.chatGPT_features_serie(df, "tn")
df = feature_engineering.mes_con_feriado(df)
df.shape

(31362, 1758)

##### Variables Exogenas

In [14]:
df = feature_engineering.get_dolar(df)
df = feature_engineering.get_IPC(df)
df['ipc'] = df['ipc'].str.replace(',', '.').astype(float)
df['dolar'] = df['dolar'].str.replace(',', '.').astype(float)
# df.drop(columns=['ds'], inplace=True)
df.fillna(0, inplace=True) ##### EXPERIMENTAR
df = feature_engineering.correlacion_exogenas(df)
df = feature_engineering.get_mes_receso_escolar(df)
df.shape

(31362, 1761)

##### Nuevas FE

In [15]:
df = feature_engineering.create_ratio_features(df)
df = feature_engineering.enhance_lifecycle_features(df)
# df = feature_engineering.create_category_features(df)
df = feature_engineering.create_regime_features(df)
df = feature_engineering.create_nonlinear_trends(df)
df = feature_engineering.create_temporal_interactions(df)
df = feature_engineering.create_asymmetric_window_features(df)
df = feature_engineering.recomendaciones_deepseek(df)
df = feature_engineering.get_nuevas_features(df)
df.shape

(31362, 1798)

##### Elimino aquellas que no sirven

In [ ]:
import json
import pandas as pd
import csv

with open("./feature_importance/v19.json") as f:
    data = json.load(f)

# Crear una lista de tuplas (feature, value)
features_values = [(feature, value) for feature, value in data.items()]

# Guardar en un archivo CSV
with open('./feature_importance/v19.csv', 'w', newline='') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow(['feature', 'importance'])  # Escribir el encabezado
    writer.writerows(features_values)      # Escribir los datos

print("Archivo CSV generado exitosamente: features_values.csv")

Archivo CSV generado exitosamente: features_values.csv

In [16]:
importantes = pd.read_csv("./feature_importance/v19.csv", sep=',', encoding='utf-8')
no_importantes = importantes[importantes['importance'] == 0]
no_importantes = no_importantes[~no_importantes['feature'].isin(columnas_baseline)]
no_importantes

                         feature  importance
1103           tn_rolling_std_20         0.0
1104           tn_rolling_std_22         0.0
1105           tn_rolling_std_25         0.0
1106           tn_rolling_std_26         0.0
1107           tn_rolling_std_27         0.0
...                          ...         ...
1781             cat3_Acond Bebe         0.0
1782        tn_rolling_median_25         0.0
1783        tn_rolling_median_24         0.0
1786            tn_rolling_std_1         0.0
1787  stock_final_rolling_min_23         0.0

[682 rows x 2 columns]

In [17]:
cols_a_eliminar = no_importantes.feature.unique()
print(f"Antes de eliminar: {df.shape[1]} columnas")
df = df.drop(columns=cols_a_eliminar, errors='ignore')
print(f"Después de eliminar: {df.shape[1]} columnas")

Antes de eliminar: 1798 columnas
Después de eliminar: 1116 columnas

Eliminar object/categorical columnas

In [18]:
df = df.select_dtypes(exclude=['datetime', 'datetime64', 'object'])

Train Test Split

In [19]:
train = df[df['periodo'] <= 201912]
test = df[df['periodo'] == 201912]

Entrenamiento

In [20]:
model_lgb.optimizar_con_optuna_con_semillerio_db(train, version="v20", n_trials=500)

Para visualizar los resultados en tiempo real:
1. Abre otra terminal y ejecuta:
   optuna-dashboard sqlite:///optuna_studies_v20.db
2. Abre en tu navegador: http://127.0.0.1:8080/

[I 2025-07-09 10:16:20,395] Using an existing study with name 'lightgbm_optimization_v20' instead of creating a new one.
[I 2025-07-09 10:24:27,886] Trial 120 finished with value: 0.33345932270869916 and parameters: {'num_leaves': 73, 'learning_rate': 0.24407684875617658, 'feature_fraction': 0.8237624154096727, 'bagging_fraction': 0.9776262944059598, 'bagging_freq': 5, 'lambda_l1': 0.000867696677065586, 'lambda_l2': 3.1753580321836803e-06, 'min_child_samples': 35, 'max_depth': 10, 'max_bin': 461, 'min_data_in_leaf': 98, 'extra_trees': False, 'early_stopping_rounds': 16, 'path_smooth': 0.01855501975285532, 'min_gain_to_split': 0.059906632092850645}. Best is trial 91 with value: 0.05452697337146212.

Mejor trial hasta ahora: RMSE=0.054527, Parámetros={'num_leaves': 65, 'learning_rate': 0.21216746368001035, 'feature_fraction': 0.9781407572059055, 'bagging_fraction': 0.9911984609582816, 'bagging_freq': 6, 'lambda_l1': 0.014755364659435312, 'lambda_l2': 7.391699873589852e-06, 'min_child_samples': 31, 'max_depth': 10, 'max_bin': 481, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.0392891614991775, 'min_gain_to_split': 0.02082318088761467}

[I 2025-07-09 10:38:27,200] Trial 121 finished with value: 0.1239903318460078 and parameters: {'num_leaves': 66, 'learning_rate': 0.22514439322776278, 'feature_fraction': 0.999781789698398, 'bagging_fraction': 0.9919476580835159, 'bagging_freq': 6, 'lambda_l1': 1.2396414771128246e-07, 'lambda_l2': 1.1555691800459419e-05, 'min_child_samples': 29, 'max_depth': 9, 'max_bin': 472, 'min_data_in_leaf': 46, 'extra_trees': False, 'early_stopping_rounds': 19, 'path_smooth': 0.06982189279718097, 'min_gain_to_split': 0.022361415841808216}. Best is trial 91 with value: 0.05452697337146212.

Mejor trial hasta ahora: RMSE=0.054527, Parámetros={'num_leaves': 65, 'learning_rate': 0.21216746368001035, 'feature_fraction': 0.9781407572059055, 'bagging_fraction': 0.9911984609582816, 'bagging_freq': 6, 'lambda_l1': 0.014755364659435312, 'lambda_l2': 7.391699873589852e-06, 'min_child_samples': 31, 'max_depth': 10, 'max_bin': 481, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.0392891614991775, 'min_gain_to_split': 0.02082318088761467}

[I 2025-07-09 10:51:39,989] Trial 122 finished with value: 0.21047118838483653 and parameters: {'num_leaves': 66, 'learning_rate': 0.22342542652959846, 'feature_fraction': 0.985949881234076, 'bagging_fraction': 0.9851419443032426, 'bagging_freq': 6, 'lambda_l1': 2.005863634595767e-07, 'lambda_l2': 2.3824256038410916e-05, 'min_child_samples': 29, 'max_depth': 9, 'max_bin': 476, 'min_data_in_leaf': 46, 'extra_trees': False, 'early_stopping_rounds': 19, 'path_smooth': 0.06732289566814681, 'min_gain_to_split': 0.02123808692593961}. Best is trial 91 with value: 0.05452697337146212.

Mejor trial hasta ahora: RMSE=0.054527, Parámetros={'num_leaves': 65, 'learning_rate': 0.21216746368001035, 'feature_fraction': 0.9781407572059055, 'bagging_fraction': 0.9911984609582816, 'bagging_freq': 6, 'lambda_l1': 0.014755364659435312, 'lambda_l2': 7.391699873589852e-06, 'min_child_samples': 31, 'max_depth': 10, 'max_bin': 481, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.0392891614991775, 'min_gain_to_split': 0.02082318088761467}

[I 2025-07-09 11:01:05,975] Trial 123 finished with value: 0.25884154169074697 and parameters: {'num_leaves': 60, 'learning_rate': 0.29868634604857525, 'feature_fraction': 0.9990422648348797, 'bagging_fraction': 0.9953905535451043, 'bagging_freq': 6, 'lambda_l1': 4.957605977289482e-08, 'lambda_l2': 1.1718009082858706e-05, 'min_child_samples': 33, 'max_depth': 9, 'max_bin': 492, 'min_data_in_leaf': 39, 'extra_trees': False, 'early_stopping_rounds': 16, 'path_smooth': 0.0010130142015628285, 'min_gain_to_split': 0.04637814722942908}. Best is trial 91 with value: 0.05452697337146212.

Mejor trial hasta ahora: RMSE=0.054527, Parámetros={'num_leaves': 65, 'learning_rate': 0.21216746368001035, 'feature_fraction': 0.9781407572059055, 'bagging_fraction': 0.9911984609582816, 'bagging_freq': 6, 'lambda_l1': 0.014755364659435312, 'lambda_l2': 7.391699873589852e-06, 'min_child_samples': 31, 'max_depth': 10, 'max_bin': 481, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.0392891614991775, 'min_gain_to_split': 0.02082318088761467}

[I 2025-07-09 11:14:22,545] Trial 124 finished with value: 0.08913307713942514 and parameters: {'num_leaves': 68, 'learning_rate': 0.1853947674764919, 'feature_fraction': 0.9751303467080612, 'bagging_fraction': 0.9916117130397334, 'bagging_freq': 5, 'lambda_l1': 1.3284590356834202e-07, 'lambda_l2': 4.530325753374318e-06, 'min_child_samples': 28, 'max_depth': 9, 'max_bin': 469, 'min_data_in_leaf': 42, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.26407036646237014, 'min_gain_to_split': 0.03167233674621458}. Best is trial 91 with value: 0.05452697337146212.

Mejor trial hasta ahora: RMSE=0.054527, Parámetros={'num_leaves': 65, 'learning_rate': 0.21216746368001035, 'feature_fraction': 0.9781407572059055, 'bagging_fraction': 0.9911984609582816, 'bagging_freq': 6, 'lambda_l1': 0.014755364659435312, 'lambda_l2': 7.391699873589852e-06, 'min_child_samples': 31, 'max_depth': 10, 'max_bin': 481, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.0392891614991775, 'min_gain_to_split': 0.02082318088761467}

[I 2025-07-09 11:29:56,734] Trial 125 finished with value: 0.13195045671166206 and parameters: {'num_leaves': 67, 'learning_rate': 0.14850227796093682, 'feature_fraction': 0.974511784363681, 'bagging_fraction': 0.9926416437888567, 'bagging_freq': 5, 'lambda_l1': 1.0529131093379045e-07, 'lambda_l2': 6.510695717104314e-06, 'min_child_samples': 30, 'max_depth': 9, 'max_bin': 467, 'min_data_in_leaf': 48, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.27793597611240767, 'min_gain_to_split': 0.033647905437297204}. Best is trial 91 with value: 0.05452697337146212.

Mejor trial hasta ahora: RMSE=0.054527, Parámetros={'num_leaves': 65, 'learning_rate': 0.21216746368001035, 'feature_fraction': 0.9781407572059055, 'bagging_fraction': 0.9911984609582816, 'bagging_freq': 6, 'lambda_l1': 0.014755364659435312, 'lambda_l2': 7.391699873589852e-06, 'min_child_samples': 31, 'max_depth': 10, 'max_bin': 481, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.0392891614991775, 'min_gain_to_split': 0.02082318088761467}

[I 2025-07-09 11:37:40,217] Trial 126 finished with value: 0.1623060329739829 and parameters: {'num_leaves': 70, 'learning_rate': 0.18297924911787075, 'feature_fraction': 0.9626179992810647, 'bagging_fraction': 0.9738679291485527, 'bagging_freq': 5, 'lambda_l1': 1.3835487659786293e-07, 'lambda_l2': 9.539039297907669e-06, 'min_child_samples': 28, 'max_depth': 10, 'max_bin': 219, 'min_data_in_leaf': 42, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.17717304457586897, 'min_gain_to_split': 0.06703545095819104}. Best is trial 91 with value: 0.05452697337146212.

Mejor trial hasta ahora: RMSE=0.054527, Parámetros={'num_leaves': 65, 'learning_rate': 0.21216746368001035, 'feature_fraction': 0.9781407572059055, 'bagging_fraction': 0.9911984609582816, 'bagging_freq': 6, 'lambda_l1': 0.014755364659435312, 'lambda_l2': 7.391699873589852e-06, 'min_child_samples': 31, 'max_depth': 10, 'max_bin': 481, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.0392891614991775, 'min_gain_to_split': 0.02082318088761467}

[I 2025-07-09 11:51:10,994] Trial 127 finished with value: 0.17282200014246127 and parameters: {'num_leaves': 68, 'learning_rate': 0.2120683732344531, 'feature_fraction': 0.9917631647533326, 'bagging_fraction': 0.9897118690840376, 'bagging_freq': 5, 'lambda_l1': 1.6963449705716556e-08, 'lambda_l2': 3.7489425120885267e-06, 'min_child_samples': 31, 'max_depth': 9, 'max_bin': 455, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.1412542980064801, 'min_gain_to_split': 0.027125000661878375}. Best is trial 91 with value: 0.05452697337146212.

Mejor trial hasta ahora: RMSE=0.054527, Parámetros={'num_leaves': 65, 'learning_rate': 0.21216746368001035, 'feature_fraction': 0.9781407572059055, 'bagging_fraction': 0.9911984609582816, 'bagging_freq': 6, 'lambda_l1': 0.014755364659435312, 'lambda_l2': 7.391699873589852e-06, 'min_child_samples': 31, 'max_depth': 10, 'max_bin': 481, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.0392891614991775, 'min_gain_to_split': 0.02082318088761467}

[I 2025-07-09 12:02:48,405] Trial 128 finished with value: 0.36942101237661784 and parameters: {'num_leaves': 77, 'learning_rate': 0.1979855369214501, 'feature_fraction': 0.9816095739544125, 'bagging_fraction': 0.9636271541561418, 'bagging_freq': 5, 'lambda_l1': 2.656489059443754e-08, 'lambda_l2': 5.8635982676641424e-05, 'min_child_samples': 34, 'max_depth': 10, 'max_bin': 436, 'min_data_in_leaf': 52, 'extra_trees': False, 'early_stopping_rounds': 17, 'path_smooth': 0.047887128522246865, 'min_gain_to_split': 0.052548032427937263}. Best is trial 91 with value: 0.05452697337146212.

Mejor trial hasta ahora: RMSE=0.054527, Parámetros={'num_leaves': 65, 'learning_rate': 0.21216746368001035, 'feature_fraction': 0.9781407572059055, 'bagging_fraction': 0.9911984609582816, 'bagging_freq': 6, 'lambda_l1': 0.014755364659435312, 'lambda_l2': 7.391699873589852e-06, 'min_child_samples': 31, 'max_depth': 10, 'max_bin': 481, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.0392891614991775, 'min_gain_to_split': 0.02082318088761467}

[I 2025-07-09 12:34:07,681] Trial 129 finished with value: 0.6097542779498883 and parameters: {'num_leaves': 65, 'learning_rate': 0.041906408195709954, 'feature_fraction': 0.9733909558532667, 'bagging_fraction': 0.9796993301679177, 'bagging_freq': 6, 'lambda_l1': 2.460705584183418e-07, 'lambda_l2': 1.6754481411188646e-05, 'min_child_samples': 26, 'max_depth': 9, 'max_bin': 487, 'min_data_in_leaf': 35, 'extra_trees': False, 'early_stopping_rounds': 21, 'path_smooth': 0.024992117195256368, 'min_gain_to_split': 0.01941400887712436}. Best is trial 91 with value: 0.05452697337146212.

Mejor trial hasta ahora: RMSE=0.054527, Parámetros={'num_leaves': 65, 'learning_rate': 0.21216746368001035, 'feature_fraction': 0.9781407572059055, 'bagging_fraction': 0.9911984609582816, 'bagging_freq': 6, 'lambda_l1': 0.014755364659435312, 'lambda_l2': 7.391699873589852e-06, 'min_child_samples': 31, 'max_depth': 10, 'max_bin': 481, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.0392891614991775, 'min_gain_to_split': 0.02082318088761467}

[I 2025-07-09 12:41:45,486] Trial 130 finished with value: 0.13853853442865022 and parameters: {'num_leaves': 63, 'learning_rate': 0.27695181472908825, 'feature_fraction': 0.9634723989408597, 'bagging_fraction': 0.999146085359879, 'bagging_freq': 7, 'lambda_l1': 7.194230467012065e-08, 'lambda_l2': 1.9456408004927604e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 445, 'min_data_in_leaf': 45, 'extra_trees': False, 'early_stopping_rounds': 32, 'path_smooth': 0.08779865561521455, 'min_gain_to_split': 0.1421861076372753}. Best is trial 91 with value: 0.05452697337146212.

Mejor trial hasta ahora: RMSE=0.054527, Parámetros={'num_leaves': 65, 'learning_rate': 0.21216746368001035, 'feature_fraction': 0.9781407572059055, 'bagging_fraction': 0.9911984609582816, 'bagging_freq': 6, 'lambda_l1': 0.014755364659435312, 'lambda_l2': 7.391699873589852e-06, 'min_child_samples': 31, 'max_depth': 10, 'max_bin': 481, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.0392891614991775, 'min_gain_to_split': 0.02082318088761467}

[I 2025-07-09 12:53:37,856] Trial 131 finished with value: 0.2530465108384519 and parameters: {'num_leaves': 73, 'learning_rate': 0.1558944265214981, 'feature_fraction': 0.9467141434750642, 'bagging_fraction': 0.9935561843268544, 'bagging_freq': 5, 'lambda_l1': 4.065996089953002e-08, 'lambda_l2': 2.8369345756745194e-05, 'min_child_samples': 32, 'max_depth': 9, 'max_bin': 470, 'min_data_in_leaf': 31, 'extra_trees': False, 'early_stopping_rounds': 20, 'path_smooth': 0.13061021366313064, 'min_gain_to_split': 0.09415847269285596}. Best is trial 91 with value: 0.05452697337146212.

Mejor trial hasta ahora: RMSE=0.054527, Parámetros={'num_leaves': 65, 'learning_rate': 0.21216746368001035, 'feature_fraction': 0.9781407572059055, 'bagging_fraction': 0.9911984609582816, 'bagging_freq': 6, 'lambda_l1': 0.014755364659435312, 'lambda_l2': 7.391699873589852e-06, 'min_child_samples': 31, 'max_depth': 10, 'max_bin': 481, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.0392891614991775, 'min_gain_to_split': 0.02082318088761467}

[I 2025-07-09 13:06:53,730] Trial 132 finished with value: 0.1841807829808055 and parameters: {'num_leaves': 68, 'learning_rate': 0.17123315388826946, 'feature_fraction': 0.9748522481605805, 'bagging_fraction': 0.9927736343432974, 'bagging_freq': 5, 'lambda_l1': 1.071894189116994e-07, 'lambda_l2': 5.719362512711025e-06, 'min_child_samples': 30, 'max_depth': 9, 'max_bin': 464, 'min_data_in_leaf': 48, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.05884863099229451, 'min_gain_to_split': 0.04220848673152705}. Best is trial 91 with value: 0.05452697337146212.

Mejor trial hasta ahora: RMSE=0.054527, Parámetros={'num_leaves': 65, 'learning_rate': 0.21216746368001035, 'feature_fraction': 0.9781407572059055, 'bagging_fraction': 0.9911984609582816, 'bagging_freq': 6, 'lambda_l1': 0.014755364659435312, 'lambda_l2': 7.391699873589852e-06, 'min_child_samples': 31, 'max_depth': 10, 'max_bin': 481, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.0392891614991775, 'min_gain_to_split': 0.02082318088761467}

[I 2025-07-09 13:14:15,229] Trial 133 finished with value: 0.21210177150369897 and parameters: {'num_leaves': 66, 'learning_rate': 0.1470393231949391, 'feature_fraction': 0.9845003494157202, 'bagging_fraction': 0.9845066068456935, 'bagging_freq': 5, 'lambda_l1': 7.765705590863261e-07, 'lambda_l2': 5.483649036184875e-06, 'min_child_samples': 29, 'max_depth': 9, 'max_bin': 168, 'min_data_in_leaf': 48, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.33426287024137713, 'min_gain_to_split': 0.03563875546156306}. Best is trial 91 with value: 0.05452697337146212.

Mejor trial hasta ahora: RMSE=0.054527, Parámetros={'num_leaves': 65, 'learning_rate': 0.21216746368001035, 'feature_fraction': 0.9781407572059055, 'bagging_fraction': 0.9911984609582816, 'bagging_freq': 6, 'lambda_l1': 0.014755364659435312, 'lambda_l2': 7.391699873589852e-06, 'min_child_samples': 31, 'max_depth': 10, 'max_bin': 481, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.0392891614991775, 'min_gain_to_split': 0.02082318088761467}

[I 2025-07-09 13:27:39,280] Trial 134 finished with value: 0.15474808501274467 and parameters: {'num_leaves': 63, 'learning_rate': 0.18609702148319554, 'feature_fraction': 0.9956621405407403, 'bagging_fraction': 0.9739449404887409, 'bagging_freq': 6, 'lambda_l1': 1.1568606308777782e-07, 'lambda_l2': 3.1634051841831974e-06, 'min_child_samples': 27, 'max_depth': 9, 'max_bin': 482, 'min_data_in_leaf': 46, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.016070140977913677, 'min_gain_to_split': 0.0015885078917640127}. Best is trial 91 with value: 0.05452697337146212.

Mejor trial hasta ahora: RMSE=0.054527, Parámetros={'num_leaves': 65, 'learning_rate': 0.21216746368001035, 'feature_fraction': 0.9781407572059055, 'bagging_fraction': 0.9911984609582816, 'bagging_freq': 6, 'lambda_l1': 0.014755364659435312, 'lambda_l2': 7.391699873589852e-06, 'min_child_samples': 31, 'max_depth': 10, 'max_bin': 481, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.0392891614991775, 'min_gain_to_split': 0.02082318088761467}

[I 2025-07-09 13:40:06,196] Trial 135 finished with value: 0.11918217540709737 and parameters: {'num_leaves': 69, 'learning_rate': 0.22462451672530406, 'feature_fraction': 0.9740134698991898, 'bagging_fraction': 0.9888992714289939, 'bagging_freq': 5, 'lambda_l1': 1.1966066946744227e-05, 'lambda_l2': 1.3025786226187955e-05, 'min_child_samples': 32, 'max_depth': 10, 'max_bin': 470, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.11199870204649648, 'min_gain_to_split': 0.03214298961630715}. Best is trial 91 with value: 0.05452697337146212.

Mejor trial hasta ahora: RMSE=0.054527, Parámetros={'num_leaves': 65, 'learning_rate': 0.21216746368001035, 'feature_fraction': 0.9781407572059055, 'bagging_fraction': 0.9911984609582816, 'bagging_freq': 6, 'lambda_l1': 0.014755364659435312, 'lambda_l2': 7.391699873589852e-06, 'min_child_samples': 31, 'max_depth': 10, 'max_bin': 481, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.0392891614991775, 'min_gain_to_split': 0.02082318088761467}

[I 2025-07-09 13:53:11,430] Trial 136 finished with value: 0.1412579137038969 and parameters: {'num_leaves': 71, 'learning_rate': 0.2257885274164136, 'feature_fraction': 0.9999333172119454, 'bagging_fraction': 0.966590639523296, 'bagging_freq': 4, 'lambda_l1': 0.0001316788368759523, 'lambda_l2': 1.5317162862509946e-05, 'min_child_samples': 32, 'max_depth': 10, 'max_bin': 426, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.10602710609779828, 'min_gain_to_split': 0.020048142435736747}. Best is trial 91 with value: 0.05452697337146212.

Mejor trial hasta ahora: RMSE=0.054527, Parámetros={'num_leaves': 65, 'learning_rate': 0.21216746368001035, 'feature_fraction': 0.9781407572059055, 'bagging_fraction': 0.9911984609582816, 'bagging_freq': 6, 'lambda_l1': 0.014755364659435312, 'lambda_l2': 7.391699873589852e-06, 'min_child_samples': 31, 'max_depth': 10, 'max_bin': 481, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.0392891614991775, 'min_gain_to_split': 0.02082318088761467}

[I 2025-07-09 14:03:21,771] Trial 137 finished with value: 0.27049482028376387 and parameters: {'num_leaves': 69, 'learning_rate': 0.2080752977811949, 'feature_fraction': 0.9858799505614828, 'bagging_fraction': 0.9994779712878133, 'bagging_freq': 6, 'lambda_l1': 1.4483846717469032e-05, 'lambda_l2': 9.562781411070292e-05, 'min_child_samples': 32, 'max_depth': 10, 'max_bin': 453, 'min_data_in_leaf': 39, 'extra_trees': False, 'early_stopping_rounds': 21, 'path_smooth': 0.03505374082907055, 'min_gain_to_split': 0.07537696069586274}. Best is trial 91 with value: 0.05452697337146212.

Mejor trial hasta ahora: RMSE=0.054527, Parámetros={'num_leaves': 65, 'learning_rate': 0.21216746368001035, 'feature_fraction': 0.9781407572059055, 'bagging_fraction': 0.9911984609582816, 'bagging_freq': 6, 'lambda_l1': 0.014755364659435312, 'lambda_l2': 7.391699873589852e-06, 'min_child_samples': 31, 'max_depth': 10, 'max_bin': 481, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.0392891614991775, 'min_gain_to_split': 0.02082318088761467}

[I 2025-07-09 14:14:58,161] Trial 138 finished with value: 0.11272856231991454 and parameters: {'num_leaves': 79, 'learning_rate': 0.2664053613775121, 'feature_fraction': 0.9675390670551792, 'bagging_fraction': 0.9881462707203436, 'bagging_freq': 5, 'lambda_l1': 2.632517929488939e-05, 'lambda_l2': 1.0713664686240881e-05, 'min_child_samples': 34, 'max_depth': 10, 'max_bin': 494, 'min_data_in_leaf': 35, 'extra_trees': False, 'early_stopping_rounds': 14, 'path_smooth': 0.0583711757839227, 'min_gain_to_split': 0.028036258337482182}. Best is trial 91 with value: 0.05452697337146212.

Mejor trial hasta ahora: RMSE=0.054527, Parámetros={'num_leaves': 65, 'learning_rate': 0.21216746368001035, 'feature_fraction': 0.9781407572059055, 'bagging_fraction': 0.9911984609582816, 'bagging_freq': 6, 'lambda_l1': 0.014755364659435312, 'lambda_l2': 7.391699873589852e-06, 'min_child_samples': 31, 'max_depth': 10, 'max_bin': 481, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.0392891614991775, 'min_gain_to_split': 0.02082318088761467}

[I 2025-07-09 14:24:36,678] Trial 139 finished with value: 0.28308340944793536 and parameters: {'num_leaves': 81, 'learning_rate': 0.2662530302100425, 'feature_fraction': 0.9659230732309978, 'bagging_fraction': 0.7948881189281487, 'bagging_freq': 6, 'lambda_l1': 4.481950037169302e-05, 'lambda_l2': 1.1564143055277462e-06, 'min_child_samples': 34, 'max_depth': 10, 'max_bin': 494, 'min_data_in_leaf': 27, 'extra_trees': False, 'early_stopping_rounds': 13, 'path_smooth': 0.25530794593658446, 'min_gain_to_split': 0.048438288056562584}. Best is trial 91 with value: 0.05452697337146212.

Mejor trial hasta ahora: RMSE=0.054527, Parámetros={'num_leaves': 65, 'learning_rate': 0.21216746368001035, 'feature_fraction': 0.9781407572059055, 'bagging_fraction': 0.9911984609582816, 'bagging_freq': 6, 'lambda_l1': 0.014755364659435312, 'lambda_l2': 7.391699873589852e-06, 'min_child_samples': 31, 'max_depth': 10, 'max_bin': 481, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.0392891614991775, 'min_gain_to_split': 0.02082318088761467}

[I 2025-07-09 14:29:05,697] Trial 140 finished with value: 0.551140982935203 and parameters: {'num_leaves': 74, 'learning_rate': 0.23505984424976684, 'feature_fraction': 0.9771355596482963, 'bagging_fraction': 0.9881360625194814, 'bagging_freq': 8, 'lambda_l1': 2.6131559869390934e-05, 'lambda_l2': 9.851305768791244e-06, 'min_child_samples': 35, 'max_depth': 10, 'max_bin': 473, 'min_data_in_leaf': 30, 'extra_trees': True, 'early_stopping_rounds': 14, 'path_smooth': 0.11485314037071753, 'min_gain_to_split': 0.02983451938700004}. Best is trial 91 with value: 0.05452697337146212.

Mejor trial hasta ahora: RMSE=0.054527, Parámetros={'num_leaves': 65, 'learning_rate': 0.21216746368001035, 'feature_fraction': 0.9781407572059055, 'bagging_fraction': 0.9911984609582816, 'bagging_freq': 6, 'lambda_l1': 0.014755364659435312, 'lambda_l2': 7.391699873589852e-06, 'min_child_samples': 31, 'max_depth': 10, 'max_bin': 481, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.0392891614991775, 'min_gain_to_split': 0.02082318088761467}

[I 2025-07-09 14:41:28,474] Trial 141 finished with value: 0.07652979292491932 and parameters: {'num_leaves': 78, 'learning_rate': 0.25773881459188813, 'feature_fraction': 0.9523605711118457, 'bagging_fraction': 0.9834179907856407, 'bagging_freq': 4, 'lambda_l1': 1.563275909645464e-06, 'lambda_l2': 4.028169553215792e-06, 'min_child_samples': 33, 'max_depth': 8, 'max_bin': 498, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.06673568102822103, 'min_gain_to_split': 0.012501571102851924}. Best is trial 91 with value: 0.05452697337146212.

Mejor trial hasta ahora: RMSE=0.054527, Parámetros={'num_leaves': 65, 'learning_rate': 0.21216746368001035, 'feature_fraction': 0.9781407572059055, 'bagging_fraction': 0.9911984609582816, 'bagging_freq': 6, 'lambda_l1': 0.014755364659435312, 'lambda_l2': 7.391699873589852e-06, 'min_child_samples': 31, 'max_depth': 10, 'max_bin': 481, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.0392891614991775, 'min_gain_to_split': 0.02082318088761467}

[I 2025-07-09 14:52:20,775] Trial 142 finished with value: 0.05647626566217824 and parameters: {'num_leaves': 81, 'learning_rate': 0.2650127141357063, 'feature_fraction': 0.9483525700911173, 'bagging_fraction': 0.9820921972578589, 'bagging_freq': 4, 'lambda_l1': 7.034737571926691e-06, 'lambda_l2': 2.624884044414342e-06, 'min_child_samples': 33, 'max_depth': 8, 'max_bin': 495, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.07178170667608524, 'min_gain_to_split': 0.010358619458500667}. Best is trial 91 with value: 0.05452697337146212.

Mejor trial hasta ahora: RMSE=0.054527, Parámetros={'num_leaves': 65, 'learning_rate': 0.21216746368001035, 'feature_fraction': 0.9781407572059055, 'bagging_fraction': 0.9911984609582816, 'bagging_freq': 6, 'lambda_l1': 0.014755364659435312, 'lambda_l2': 7.391699873589852e-06, 'min_child_samples': 31, 'max_depth': 10, 'max_bin': 481, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.0392891614991775, 'min_gain_to_split': 0.02082318088761467}

[I 2025-07-09 15:03:11,989] Trial 143 finished with value: 0.07176792669444373 and parameters: {'num_leaves': 84, 'learning_rate': 0.2664196740435369, 'feature_fraction': 0.9393890980930623, 'bagging_fraction': 0.9813347459450912, 'bagging_freq': 4, 'lambda_l1': 8.253083656035499e-06, 'lambda_l2': 2.388586323401624e-06, 'min_child_samples': 33, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.0025878695334043706, 'min_gain_to_split': 0.010748622642051916}. Best is trial 91 with value: 0.05452697337146212.

Mejor trial hasta ahora: RMSE=0.054527, Parámetros={'num_leaves': 65, 'learning_rate': 0.21216746368001035, 'feature_fraction': 0.9781407572059055, 'bagging_fraction': 0.9911984609582816, 'bagging_freq': 6, 'lambda_l1': 0.014755364659435312, 'lambda_l2': 7.391699873589852e-06, 'min_child_samples': 31, 'max_depth': 10, 'max_bin': 481, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.0392891614991775, 'min_gain_to_split': 0.02082318088761467}

[I 2025-07-09 15:16:21,870] Trial 144 finished with value: 0.05217602942733361 and parameters: {'num_leaves': 85, 'learning_rate': 0.2588994585077432, 'feature_fraction': 0.9288755876368779, 'bagging_fraction': 0.9815799532038488, 'bagging_freq': 4, 'lambda_l1': 5.9353433717208255e-06, 'lambda_l2': 2.6415000547072924e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.01650272232710863, 'min_gain_to_split': 0.009261560783558349}. Best is trial 144 with value: 0.05217602942733361.

Mejor trial hasta ahora: RMSE=0.052176, Parámetros={'num_leaves': 85, 'learning_rate': 0.2588994585077432, 'feature_fraction': 0.9288755876368779, 'bagging_fraction': 0.9815799532038488, 'bagging_freq': 4, 'lambda_l1': 5.9353433717208255e-06, 'lambda_l2': 2.6415000547072924e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.01650272232710863, 'min_gain_to_split': 0.009261560783558349}

[I 2025-07-09 15:29:08,652] Trial 145 finished with value: 0.09904815968620165 and parameters: {'num_leaves': 84, 'learning_rate': 0.25843058815207537, 'feature_fraction': 0.9272645100327516, 'bagging_fraction': 0.9787488034257107, 'bagging_freq': 4, 'lambda_l1': 3.031733498401233e-06, 'lambda_l2': 2.1661012604383144e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 494, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.009382321273808667, 'min_gain_to_split': 0.008756187387014475}. Best is trial 144 with value: 0.05217602942733361.

Mejor trial hasta ahora: RMSE=0.052176, Parámetros={'num_leaves': 85, 'learning_rate': 0.2588994585077432, 'feature_fraction': 0.9288755876368779, 'bagging_fraction': 0.9815799532038488, 'bagging_freq': 4, 'lambda_l1': 5.9353433717208255e-06, 'lambda_l2': 2.6415000547072924e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.01650272232710863, 'min_gain_to_split': 0.009261560783558349}

[I 2025-07-09 15:41:44,927] Trial 146 finished with value: 0.20407226922181337 and parameters: {'num_leaves': 86, 'learning_rate': 0.25589462882407094, 'feature_fraction': 0.9489142012653159, 'bagging_fraction': 0.9787931469820617, 'bagging_freq': 3, 'lambda_l1': 4.567652477427356e-06, 'lambda_l2': 5.709445402481988e-07, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 36, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.0010692589859973688, 'min_gain_to_split': 0.008243287680093034}. Best is trial 144 with value: 0.05217602942733361.

Mejor trial hasta ahora: RMSE=0.052176, Parámetros={'num_leaves': 85, 'learning_rate': 0.2588994585077432, 'feature_fraction': 0.9288755876368779, 'bagging_fraction': 0.9815799532038488, 'bagging_freq': 4, 'lambda_l1': 5.9353433717208255e-06, 'lambda_l2': 2.6415000547072924e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.01650272232710863, 'min_gain_to_split': 0.009261560783558349}

[I 2025-07-09 15:53:07,850] Trial 147 finished with value: 0.2570092306314896 and parameters: {'num_leaves': 79, 'learning_rate': 0.2762616271498736, 'feature_fraction': 0.9365842764734085, 'bagging_fraction': 0.9709166996961603, 'bagging_freq': 4, 'lambda_l1': 2.112675807350803e-06, 'lambda_l2': 1.725347426837592e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 496, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.04366217328475227, 'min_gain_to_split': 0.008577766043404675}. Best is trial 144 with value: 0.05217602942733361.

Mejor trial hasta ahora: RMSE=0.052176, Parámetros={'num_leaves': 85, 'learning_rate': 0.2588994585077432, 'feature_fraction': 0.9288755876368779, 'bagging_fraction': 0.9815799532038488, 'bagging_freq': 4, 'lambda_l1': 5.9353433717208255e-06, 'lambda_l2': 2.6415000547072924e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.01650272232710863, 'min_gain_to_split': 0.009261560783558349}

[I 2025-07-09 16:06:46,590] Trial 148 finished with value: 0.06489551631189035 and parameters: {'num_leaves': 90, 'learning_rate': 0.2590292710250787, 'feature_fraction': 0.9381988556324671, 'bagging_fraction': 0.9827379938159692, 'bagging_freq': 4, 'lambda_l1': 8.675701553135313e-06, 'lambda_l2': 2.5151139429804582e-06, 'min_child_samples': 33, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 35, 'extra_trees': False, 'early_stopping_rounds': 28, 'path_smooth': 0.060940471063360736, 'min_gain_to_split': 0.0010816848549261016}. Best is trial 144 with value: 0.05217602942733361.

Mejor trial hasta ahora: RMSE=0.052176, Parámetros={'num_leaves': 85, 'learning_rate': 0.2588994585077432, 'feature_fraction': 0.9288755876368779, 'bagging_fraction': 0.9815799532038488, 'bagging_freq': 4, 'lambda_l1': 5.9353433717208255e-06, 'lambda_l2': 2.6415000547072924e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.01650272232710863, 'min_gain_to_split': 0.009261560783558349}

[I 2025-07-09 16:19:23,392] Trial 149 finished with value: 0.21307765626727213 and parameters: {'num_leaves': 84, 'learning_rate': 0.24941151836347106, 'feature_fraction': 0.919199683734465, 'bagging_fraction': 0.9815292869919292, 'bagging_freq': 4, 'lambda_l1': 8.681275560141076e-06, 'lambda_l2': 1.995466471781549e-06, 'min_child_samples': 33, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.08423750168476324, 'min_gain_to_split': 0.0021894541809164905}. Best is trial 144 with value: 0.05217602942733361.

Mejor trial hasta ahora: RMSE=0.052176, Parámetros={'num_leaves': 85, 'learning_rate': 0.2588994585077432, 'feature_fraction': 0.9288755876368779, 'bagging_fraction': 0.9815799532038488, 'bagging_freq': 4, 'lambda_l1': 5.9353433717208255e-06, 'lambda_l2': 2.6415000547072924e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.01650272232710863, 'min_gain_to_split': 0.009261560783558349}

[I 2025-07-09 16:30:17,958] Trial 150 finished with value: 0.1670180137895383 and parameters: {'num_leaves': 89, 'learning_rate': 0.2866266533167312, 'feature_fraction': 0.9278543169242446, 'bagging_fraction': 0.9702069358152431, 'bagging_freq': 4, 'lambda_l1': 1.1308408635182367e-06, 'lambda_l2': 1.2943744717586104e-06, 'min_child_samples': 33, 'max_depth': 8, 'max_bin': 487, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 29, 'path_smooth': 0.015539028853218666, 'min_gain_to_split': 0.010831942945719649}. Best is trial 144 with value: 0.05217602942733361.

Mejor trial hasta ahora: RMSE=0.052176, Parámetros={'num_leaves': 85, 'learning_rate': 0.2588994585077432, 'feature_fraction': 0.9288755876368779, 'bagging_fraction': 0.9815799532038488, 'bagging_freq': 4, 'lambda_l1': 5.9353433717208255e-06, 'lambda_l2': 2.6415000547072924e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.01650272232710863, 'min_gain_to_split': 0.009261560783558349}

[I 2025-07-09 16:42:01,734] Trial 151 finished with value: 0.05659402491306002 and parameters: {'num_leaves': 91, 'learning_rate': 0.24304179270923834, 'feature_fraction': 0.9385400141587311, 'bagging_fraction': 0.995365369287485, 'bagging_freq': 4, 'lambda_l1': 3.680965233957446e-06, 'lambda_l2': 2.8904540925271548e-06, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 489, 'min_data_in_leaf': 42, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.03318651179087955, 'min_gain_to_split': 0.0003177283931720242}. Best is trial 144 with value: 0.05217602942733361.

Mejor trial hasta ahora: RMSE=0.052176, Parámetros={'num_leaves': 85, 'learning_rate': 0.2588994585077432, 'feature_fraction': 0.9288755876368779, 'bagging_fraction': 0.9815799532038488, 'bagging_freq': 4, 'lambda_l1': 5.9353433717208255e-06, 'lambda_l2': 2.6415000547072924e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.01650272232710863, 'min_gain_to_split': 0.009261560783558349}

[I 2025-07-09 16:53:30,840] Trial 152 finished with value: 0.12694336893911787 and parameters: {'num_leaves': 92, 'learning_rate': 0.2410018334220863, 'feature_fraction': 0.9360632341054861, 'bagging_fraction': 0.9979374364389415, 'bagging_freq': 4, 'lambda_l1': 3.43501297843598e-06, 'lambda_l2': 2.6150021914131183e-06, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 489, 'min_data_in_leaf': 42, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.030620283109431566, 'min_gain_to_split': 0.017479485860501916}. Best is trial 144 with value: 0.05217602942733361.

Mejor trial hasta ahora: RMSE=0.052176, Parámetros={'num_leaves': 85, 'learning_rate': 0.2588994585077432, 'feature_fraction': 0.9288755876368779, 'bagging_fraction': 0.9815799532038488, 'bagging_freq': 4, 'lambda_l1': 5.9353433717208255e-06, 'lambda_l2': 2.6415000547072924e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.01650272232710863, 'min_gain_to_split': 0.009261560783558349}

[I 2025-07-09 17:04:39,589] Trial 153 finished with value: 0.21456134176564098 and parameters: {'num_leaves': 82, 'learning_rate': 0.262511348905913, 'feature_fraction': 0.9391162503493762, 'bagging_fraction': 0.983473259003607, 'bagging_freq': 4, 'lambda_l1': 6.275425929514786e-06, 'lambda_l2': 9.145039147487574e-07, 'min_child_samples': 35, 'max_depth': 8, 'max_bin': 480, 'min_data_in_leaf': 36, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.06266098616913626, 'min_gain_to_split': 0.0007742191463780829}. Best is trial 144 with value: 0.05217602942733361.

Mejor trial hasta ahora: RMSE=0.052176, Parámetros={'num_leaves': 85, 'learning_rate': 0.2588994585077432, 'feature_fraction': 0.9288755876368779, 'bagging_fraction': 0.9815799532038488, 'bagging_freq': 4, 'lambda_l1': 5.9353433717208255e-06, 'lambda_l2': 2.6415000547072924e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.01650272232710863, 'min_gain_to_split': 0.009261560783558349}

[I 2025-07-09 17:14:47,698] Trial 154 finished with value: 0.31669215718348204 and parameters: {'num_leaves': 91, 'learning_rate': 0.20918430186533166, 'feature_fraction': 0.9247992905300865, 'bagging_fraction': 0.9764728942306354, 'bagging_freq': 4, 'lambda_l1': 1.8800954778706038e-06, 'lambda_l2': 3.05829598991429e-06, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 491, 'min_data_in_leaf': 40, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.03186675723123408, 'min_gain_to_split': 0.01591828342318055}. Best is trial 144 with value: 0.05217602942733361.

Mejor trial hasta ahora: RMSE=0.052176, Parámetros={'num_leaves': 85, 'learning_rate': 0.2588994585077432, 'feature_fraction': 0.9288755876368779, 'bagging_fraction': 0.9815799532038488, 'bagging_freq': 4, 'lambda_l1': 5.9353433717208255e-06, 'lambda_l2': 2.6415000547072924e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.01650272232710863, 'min_gain_to_split': 0.009261560783558349}

[I 2025-07-09 17:26:56,868] Trial 155 finished with value: 0.2488717534539783 and parameters: {'num_leaves': 84, 'learning_rate': 0.24260998496847572, 'feature_fraction': 0.9013466178459345, 'bagging_fraction': 0.9934511204965604, 'bagging_freq': 4, 'lambda_l1': 8.399062734485496e-06, 'lambda_l2': 4.396194613276929e-06, 'min_child_samples': 33, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 35, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 7.782782559970225e-05, 'min_gain_to_split': 0.0005376854571810634}. Best is trial 144 with value: 0.05217602942733361.

Mejor trial hasta ahora: RMSE=0.052176, Parámetros={'num_leaves': 85, 'learning_rate': 0.2588994585077432, 'feature_fraction': 0.9288755876368779, 'bagging_fraction': 0.9815799532038488, 'bagging_freq': 4, 'lambda_l1': 5.9353433717208255e-06, 'lambda_l2': 2.6415000547072924e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.01650272232710863, 'min_gain_to_split': 0.009261560783558349}

[I 2025-07-09 17:37:20,051] Trial 156 finished with value: 0.11689741133589689 and parameters: {'num_leaves': 96, 'learning_rate': 0.27291746218717133, 'feature_fraction': 0.9435048674510018, 'bagging_fraction': 0.9825669195042777, 'bagging_freq': 4, 'lambda_l1': 2.628034189546479e-06, 'lambda_l2': 2.627197442361182e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 482, 'min_data_in_leaf': 39, 'extra_trees': False, 'early_stopping_rounds': 20, 'path_smooth': 0.09487603834103374, 'min_gain_to_split': 0.018118351931151647}. Best is trial 144 with value: 0.05217602942733361.

Mejor trial hasta ahora: RMSE=0.052176, Parámetros={'num_leaves': 85, 'learning_rate': 0.2588994585077432, 'feature_fraction': 0.9288755876368779, 'bagging_fraction': 0.9815799532038488, 'bagging_freq': 4, 'lambda_l1': 5.9353433717208255e-06, 'lambda_l2': 2.6415000547072924e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.01650272232710863, 'min_gain_to_split': 0.009261560783558349}

[I 2025-07-09 17:45:35,139] Trial 157 finished with value: 0.5346054197137873 and parameters: {'num_leaves': 88, 'learning_rate': 0.25385979310862417, 'feature_fraction': 0.9535599867048898, 'bagging_fraction': 0.740125946406199, 'bagging_freq': 4, 'lambda_l1': 4.345763291278768e-06, 'lambda_l2': 5.9702914662031486e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 487, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 21, 'path_smooth': 0.05171758513451944, 'min_gain_to_split': 0.039212598294146056}. Best is trial 144 with value: 0.05217602942733361.

Mejor trial hasta ahora: RMSE=0.052176, Parámetros={'num_leaves': 85, 'learning_rate': 0.2588994585077432, 'feature_fraction': 0.9288755876368779, 'bagging_fraction': 0.9815799532038488, 'bagging_freq': 4, 'lambda_l1': 5.9353433717208255e-06, 'lambda_l2': 2.6415000547072924e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.01650272232710863, 'min_gain_to_split': 0.009261560783558349}

[I 2025-07-09 17:57:04,945] Trial 158 finished with value: 0.2415359112607645 and parameters: {'num_leaves': 90, 'learning_rate': 0.19843772947808896, 'feature_fraction': 0.9246442608426831, 'bagging_fraction': 0.9637548381677563, 'bagging_freq': 4, 'lambda_l1': 1.5755190361219186e-05, 'lambda_l2': 6.663485302825703e-07, 'min_child_samples': 33, 'max_depth': 8, 'max_bin': 491, 'min_data_in_leaf': 43, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.023972736268930102, 'min_gain_to_split': 0.023664315614395214}. Best is trial 144 with value: 0.05217602942733361.

Mejor trial hasta ahora: RMSE=0.052176, Parámetros={'num_leaves': 85, 'learning_rate': 0.2588994585077432, 'feature_fraction': 0.9288755876368779, 'bagging_fraction': 0.9815799532038488, 'bagging_freq': 4, 'lambda_l1': 5.9353433717208255e-06, 'lambda_l2': 2.6415000547072924e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.01650272232710863, 'min_gain_to_split': 0.009261560783558349}

[I 2025-07-09 18:09:40,779] Trial 159 finished with value: 0.1627419700814264 and parameters: {'num_leaves': 87, 'learning_rate': 0.217390308122901, 'feature_fraction': 0.931915944654544, 'bagging_fraction': 0.9993278236413655, 'bagging_freq': 4, 'lambda_l1': 9.017053662155193e-06, 'lambda_l2': 1.426339506229541e-06, 'min_child_samples': 34, 'max_depth': 8, 'max_bin': 478, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.08161155299733165, 'min_gain_to_split': 0.010826859085951334}. Best is trial 144 with value: 0.05217602942733361.

Mejor trial hasta ahora: RMSE=0.052176, Parámetros={'num_leaves': 85, 'learning_rate': 0.2588994585077432, 'feature_fraction': 0.9288755876368779, 'bagging_fraction': 0.9815799532038488, 'bagging_freq': 4, 'lambda_l1': 5.9353433717208255e-06, 'lambda_l2': 2.6415000547072924e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.01650272232710863, 'min_gain_to_split': 0.009261560783558349}

[I 2025-07-09 18:20:38,591] Trial 160 finished with value: 0.09975309001825375 and parameters: {'num_leaves': 83, 'learning_rate': 0.23263276951635858, 'feature_fraction': 0.9529739210274307, 'bagging_fraction': 0.9877054793352291, 'bagging_freq': 4, 'lambda_l1': 6.002815051149033e-06, 'lambda_l2': 4.23471431391882e-06, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 495, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 21, 'path_smooth': 0.0513498473175178, 'min_gain_to_split': 0.04171088596804441}. Best is trial 144 with value: 0.05217602942733361.

Mejor trial hasta ahora: RMSE=0.052176, Parámetros={'num_leaves': 85, 'learning_rate': 0.2588994585077432, 'feature_fraction': 0.9288755876368779, 'bagging_fraction': 0.9815799532038488, 'bagging_freq': 4, 'lambda_l1': 5.9353433717208255e-06, 'lambda_l2': 2.6415000547072924e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.01650272232710863, 'min_gain_to_split': 0.009261560783558349}

[I 2025-07-09 18:31:48,321] Trial 161 finished with value: 0.19992625872216124 and parameters: {'num_leaves': 83, 'learning_rate': 0.22913459759752067, 'feature_fraction': 0.9526892424804603, 'bagging_fraction': 0.9875473693658665, 'bagging_freq': 3, 'lambda_l1': 5.331215934632597e-06, 'lambda_l2': 1.872838106711873e-06, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 493, 'min_data_in_leaf': 31, 'extra_trees': False, 'early_stopping_rounds': 21, 'path_smooth': 0.06594017143217402, 'min_gain_to_split': 0.04306915773978152}. Best is trial 144 with value: 0.05217602942733361.

Mejor trial hasta ahora: RMSE=0.052176, Parámetros={'num_leaves': 85, 'learning_rate': 0.2588994585077432, 'feature_fraction': 0.9288755876368779, 'bagging_fraction': 0.9815799532038488, 'bagging_freq': 4, 'lambda_l1': 5.9353433717208255e-06, 'lambda_l2': 2.6415000547072924e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.01650272232710863, 'min_gain_to_split': 0.009261560783558349}

[I 2025-07-09 18:42:38,242] Trial 162 finished with value: 0.13729383937119477 and parameters: {'num_leaves': 85, 'learning_rate': 0.2580298850784047, 'feature_fraction': 0.9457952018282438, 'bagging_fraction': 0.9758960515186339, 'bagging_freq': 4, 'lambda_l1': 3.10100343951792e-06, 'lambda_l2': 3.8037486594590932e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.047176008266019566, 'min_gain_to_split': 6.815965817861917e-05}. Best is trial 144 with value: 0.05217602942733361.

Mejor trial hasta ahora: RMSE=0.052176, Parámetros={'num_leaves': 85, 'learning_rate': 0.2588994585077432, 'feature_fraction': 0.9288755876368779, 'bagging_fraction': 0.9815799532038488, 'bagging_freq': 4, 'lambda_l1': 5.9353433717208255e-06, 'lambda_l2': 2.6415000547072924e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.01650272232710863, 'min_gain_to_split': 0.009261560783558349}

[I 2025-07-09 18:55:35,824] Trial 163 finished with value: 0.09979413958493424 and parameters: {'num_leaves': 81, 'learning_rate': 0.2391822732605903, 'feature_fraction': 0.9162420080784189, 'bagging_fraction': 0.993575075244197, 'bagging_freq': 4, 'lambda_l1': 1.7131092005037682e-05, 'lambda_l2': 4.836397843158124e-06, 'min_child_samples': 30, 'max_depth': 8, 'max_bin': 481, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.01990321135171128, 'min_gain_to_split': 0.012795322512161356}. Best is trial 144 with value: 0.05217602942733361.

Mejor trial hasta ahora: RMSE=0.052176, Parámetros={'num_leaves': 85, 'learning_rate': 0.2588994585077432, 'feature_fraction': 0.9288755876368779, 'bagging_fraction': 0.9815799532038488, 'bagging_freq': 4, 'lambda_l1': 5.9353433717208255e-06, 'lambda_l2': 2.6415000547072924e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.01650272232710863, 'min_gain_to_split': 0.009261560783558349}

[I 2025-07-09 19:09:13,443] Trial 164 finished with value: 0.10443528582446174 and parameters: {'num_leaves': 82, 'learning_rate': 0.21229232424118397, 'feature_fraction': 0.9178261649702351, 'bagging_fraction': 0.9952983855437139, 'bagging_freq': 4, 'lambda_l1': 1.7147878907641772e-05, 'lambda_l2': 6.9326810476443525e-06, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 477, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.012927679383213313, 'min_gain_to_split': 0.012361647013843258}. Best is trial 144 with value: 0.05217602942733361.

Mejor trial hasta ahora: RMSE=0.052176, Parámetros={'num_leaves': 85, 'learning_rate': 0.2588994585077432, 'feature_fraction': 0.9288755876368779, 'bagging_fraction': 0.9815799532038488, 'bagging_freq': 4, 'lambda_l1': 5.9353433717208255e-06, 'lambda_l2': 2.6415000547072924e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.01650272232710863, 'min_gain_to_split': 0.009261560783558349}

[I 2025-07-09 19:19:03,511] Trial 165 finished with value: 0.27901647530892804 and parameters: {'num_leaves': 81, 'learning_rate': 0.28323016887534963, 'feature_fraction': 0.9102604057847273, 'bagging_fraction': 0.9922396695233227, 'bagging_freq': 4, 'lambda_l1': 1.865203262666915e-05, 'lambda_l2': 7.009547765587366e-06, 'min_child_samples': 30, 'max_depth': 8, 'max_bin': 478, 'min_data_in_leaf': 30, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.04064255943821086, 'min_gain_to_split': 0.023460585686009137}. Best is trial 144 with value: 0.05217602942733361.

Mejor trial hasta ahora: RMSE=0.052176, Parámetros={'num_leaves': 85, 'learning_rate': 0.2588994585077432, 'feature_fraction': 0.9288755876368779, 'bagging_fraction': 0.9815799532038488, 'bagging_freq': 4, 'lambda_l1': 5.9353433717208255e-06, 'lambda_l2': 2.6415000547072924e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.01650272232710863, 'min_gain_to_split': 0.009261560783558349}

[I 2025-07-09 19:31:19,229] Trial 166 finished with value: 0.1959071256560057 and parameters: {'num_leaves': 77, 'learning_rate': 0.23362160523576686, 'feature_fraction': 0.9289835577817916, 'bagging_fraction': 0.9869515919307398, 'bagging_freq': 4, 'lambda_l1': 1.2174788328565355e-05, 'lambda_l2': 2.6531075744476825e-06, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 481, 'min_data_in_leaf': 27, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.01683645801552506, 'min_gain_to_split': 0.012450271646568456}. Best is trial 144 with value: 0.05217602942733361.

Mejor trial hasta ahora: RMSE=0.052176, Parámetros={'num_leaves': 85, 'learning_rate': 0.2588994585077432, 'feature_fraction': 0.9288755876368779, 'bagging_fraction': 0.9815799532038488, 'bagging_freq': 4, 'lambda_l1': 5.9353433717208255e-06, 'lambda_l2': 2.6415000547072924e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.01650272232710863, 'min_gain_to_split': 0.009261560783558349}

[I 2025-07-09 19:49:37,716] Trial 167 finished with value: 0.6030797294401148 and parameters: {'num_leaves': 87, 'learning_rate': 0.06654954711733262, 'feature_fraction': 0.9176447698493838, 'bagging_fraction': 0.9813286384395113, 'bagging_freq': 4, 'lambda_l1': 4.0144987922752225e-05, 'lambda_l2': 1.0084900659640967e-06, 'min_child_samples': 30, 'max_depth': 8, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.07866205402536627, 'min_gain_to_split': 0.02527773421818947}. Best is trial 144 with value: 0.05217602942733361.

Mejor trial hasta ahora: RMSE=0.052176, Parámetros={'num_leaves': 85, 'learning_rate': 0.2588994585077432, 'feature_fraction': 0.9288755876368779, 'bagging_fraction': 0.9815799532038488, 'bagging_freq': 4, 'lambda_l1': 5.9353433717208255e-06, 'lambda_l2': 2.6415000547072924e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.01650272232710863, 'min_gain_to_split': 0.009261560783558349}

[I 2025-07-09 20:00:53,022] Trial 168 finished with value: 0.17351927598877587 and parameters: {'num_leaves': 83, 'learning_rate': 0.18947450489690248, 'feature_fraction': 0.8963442323276466, 'bagging_fraction': 0.9941308839234575, 'bagging_freq': 4, 'lambda_l1': 5.758196558134531e-06, 'lambda_l2': 7.4651013422829606e-06, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 491, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.05751054157256492, 'min_gain_to_split': 0.05253931165657359}. Best is trial 144 with value: 0.05217602942733361.

Mejor trial hasta ahora: RMSE=0.052176, Parámetros={'num_leaves': 85, 'learning_rate': 0.2588994585077432, 'feature_fraction': 0.9288755876368779, 'bagging_fraction': 0.9815799532038488, 'bagging_freq': 4, 'lambda_l1': 5.9353433717208255e-06, 'lambda_l2': 2.6415000547072924e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.01650272232710863, 'min_gain_to_split': 0.009261560783558349}

[I 2025-07-09 20:05:27,345] Trial 169 finished with value: 0.5067388490972521 and parameters: {'num_leaves': 80, 'learning_rate': 0.21861084742477785, 'feature_fraction': 0.9405178298249164, 'bagging_fraction': 0.9865708789491058, 'bagging_freq': 3, 'lambda_l1': 1.3661501408200682e-06, 'lambda_l2': 2.370878131994287e-06, 'min_child_samples': 28, 'max_depth': 8, 'max_bin': 474, 'min_data_in_leaf': 32, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.0031629067793541143, 'min_gain_to_split': 0.014006957407923015}. Best is trial 144 with value: 0.05217602942733361.

Mejor trial hasta ahora: RMSE=0.052176, Parámetros={'num_leaves': 85, 'learning_rate': 0.2588994585077432, 'feature_fraction': 0.9288755876368779, 'bagging_fraction': 0.9815799532038488, 'bagging_freq': 4, 'lambda_l1': 5.9353433717208255e-06, 'lambda_l2': 2.6415000547072924e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.01650272232710863, 'min_gain_to_split': 0.009261560783558349}

[I 2025-07-09 20:15:21,607] Trial 170 finished with value: 0.26644253982003085 and parameters: {'num_leaves': 85, 'learning_rate': 0.2505119470541213, 'feature_fraction': 0.9160720734564742, 'bagging_fraction': 0.9773175099574016, 'bagging_freq': 4, 'lambda_l1': 7.730261363598413e-06, 'lambda_l2': 5.097181981173887e-06, 'min_child_samples': 30, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 36, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.09378674350581956, 'min_gain_to_split': 0.03997197450337751}. Best is trial 144 with value: 0.05217602942733361.

Mejor trial hasta ahora: RMSE=0.052176, Parámetros={'num_leaves': 85, 'learning_rate': 0.2588994585077432, 'feature_fraction': 0.9288755876368779, 'bagging_fraction': 0.9815799532038488, 'bagging_freq': 4, 'lambda_l1': 5.9353433717208255e-06, 'lambda_l2': 2.6415000547072924e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.01650272232710863, 'min_gain_to_split': 0.009261560783558349}

[I 2025-07-09 20:29:45,670] Trial 171 finished with value: 0.12941916918580063 and parameters: {'num_leaves': 82, 'learning_rate': 0.20291919483816293, 'feature_fraction': 0.9363102249539923, 'bagging_fraction': 0.9940253603311591, 'bagging_freq': 4, 'lambda_l1': 8.991016091541401e-05, 'lambda_l2': 1.7113763865432369e-06, 'min_child_samples': 28, 'max_depth': 8, 'max_bin': 485, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 20, 'path_smooth': 0.037470378254089984, 'min_gain_to_split': 0.009587056910183401}. Best is trial 144 with value: 0.05217602942733361.

Mejor trial hasta ahora: RMSE=0.052176, Parámetros={'num_leaves': 85, 'learning_rate': 0.2588994585077432, 'feature_fraction': 0.9288755876368779, 'bagging_fraction': 0.9815799532038488, 'bagging_freq': 4, 'lambda_l1': 5.9353433717208255e-06, 'lambda_l2': 2.6415000547072924e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.01650272232710863, 'min_gain_to_split': 0.009261560783558349}

[I 2025-07-09 20:43:55,591] Trial 172 finished with value: 0.09023147956851658 and parameters: {'num_leaves': 76, 'learning_rate': 0.21339656919391217, 'feature_fraction': 0.9578484772823377, 'bagging_fraction': 0.9996511533560233, 'bagging_freq': 4, 'lambda_l1': 3.5807838961512823e-06, 'lambda_l2': 3.908182017101468e-06, 'min_child_samples': 33, 'max_depth': 8, 'max_bin': 493, 'min_data_in_leaf': 41, 'extra_trees': False, 'early_stopping_rounds': 21, 'path_smooth': 0.01948285406047581, 'min_gain_to_split': 0.00029854068898594807}. Best is trial 144 with value: 0.05217602942733361.

Mejor trial hasta ahora: RMSE=0.052176, Parámetros={'num_leaves': 85, 'learning_rate': 0.2588994585077432, 'feature_fraction': 0.9288755876368779, 'bagging_fraction': 0.9815799532038488, 'bagging_freq': 4, 'lambda_l1': 5.9353433717208255e-06, 'lambda_l2': 2.6415000547072924e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.01650272232710863, 'min_gain_to_split': 0.009261560783558349}

[I 2025-07-09 20:56:17,270] Trial 173 finished with value: 0.06858309449935245 and parameters: {'num_leaves': 78, 'learning_rate': 0.2337271446534229, 'feature_fraction': 0.8829965170841408, 'bagging_fraction': 0.9999565851624473, 'bagging_freq': 4, 'lambda_l1': 3.4600678257772368e-06, 'lambda_l2': 3.672960517853881e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 493, 'min_data_in_leaf': 41, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.0001837598960578949, 'min_gain_to_split': 0.021111589999894438}. Best is trial 144 with value: 0.05217602942733361.

Mejor trial hasta ahora: RMSE=0.052176, Parámetros={'num_leaves': 85, 'learning_rate': 0.2588994585077432, 'feature_fraction': 0.9288755876368779, 'bagging_fraction': 0.9815799532038488, 'bagging_freq': 4, 'lambda_l1': 5.9353433717208255e-06, 'lambda_l2': 2.6415000547072924e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.01650272232710863, 'min_gain_to_split': 0.009261560783558349}

[I 2025-07-09 21:06:48,927] Trial 174 finished with value: 0.16563261147733493 and parameters: {'num_leaves': 78, 'learning_rate': 0.2378338135717812, 'feature_fraction': 0.878827968790159, 'bagging_fraction': 0.99993637884792, 'bagging_freq': 4, 'lambda_l1': 3.2014667499853544e-06, 'lambda_l2': 3.6194450401176337e-06, 'min_child_samples': 33, 'max_depth': 8, 'max_bin': 493, 'min_data_in_leaf': 41, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.00017315332077129375, 'min_gain_to_split': 0.025353572495483416}. Best is trial 144 with value: 0.05217602942733361.

Mejor trial hasta ahora: RMSE=0.052176, Parámetros={'num_leaves': 85, 'learning_rate': 0.2588994585077432, 'feature_fraction': 0.9288755876368779, 'bagging_fraction': 0.9815799532038488, 'bagging_freq': 4, 'lambda_l1': 5.9353433717208255e-06, 'lambda_l2': 2.6415000547072924e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.01650272232710863, 'min_gain_to_split': 0.009261560783558349}

[I 2025-07-09 21:18:34,913] Trial 175 finished with value: 0.21084139561969337 and parameters: {'num_leaves': 80, 'learning_rate': 0.2755980623270502, 'feature_fraction': 0.9551988155994227, 'bagging_fraction': 0.9895910179739188, 'bagging_freq': 4, 'lambda_l1': 1.6465509260983423e-06, 'lambda_l2': 3.2755779666288258e-06, 'min_child_samples': 30, 'max_depth': 8, 'max_bin': 479, 'min_data_in_leaf': 39, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.015911489432222335, 'min_gain_to_split': 0.007007664676016134}. Best is trial 144 with value: 0.05217602942733361.

Mejor trial hasta ahora: RMSE=0.052176, Parámetros={'num_leaves': 85, 'learning_rate': 0.2588994585077432, 'feature_fraction': 0.9288755876368779, 'bagging_fraction': 0.9815799532038488, 'bagging_freq': 4, 'lambda_l1': 5.9353433717208255e-06, 'lambda_l2': 2.6415000547072924e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.01650272232710863, 'min_gain_to_split': 0.009261560783558349}

[I 2025-07-09 21:28:03,684] Trial 176 finished with value: 0.1809303381334918 and parameters: {'num_leaves': 76, 'learning_rate': 0.2982016016828113, 'feature_fraction': 0.8678284883762438, 'bagging_fraction': 0.9936386618838504, 'bagging_freq': 4, 'lambda_l1': 4.310788670204151e-06, 'lambda_l2': 1.3226913073576586e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 41, 'extra_trees': False, 'early_stopping_rounds': 20, 'path_smooth': 0.021817483325819342, 'min_gain_to_split': 0.033928816226405874}. Best is trial 144 with value: 0.05217602942733361.

Mejor trial hasta ahora: RMSE=0.052176, Parámetros={'num_leaves': 85, 'learning_rate': 0.2588994585077432, 'feature_fraction': 0.9288755876368779, 'bagging_fraction': 0.9815799532038488, 'bagging_freq': 4, 'lambda_l1': 5.9353433717208255e-06, 'lambda_l2': 2.6415000547072924e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.01650272232710863, 'min_gain_to_split': 0.009261560783558349}

[I 2025-07-09 21:40:09,252] Trial 177 finished with value: 0.142898356431379 and parameters: {'num_leaves': 82, 'learning_rate': 0.22497841371204252, 'feature_fraction': 0.891858301575357, 'bagging_fraction': 0.9826750745392466, 'bagging_freq': 4, 'lambda_l1': 2.0472435928943655e-05, 'lambda_l2': 5.573377696052735e-06, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 466, 'min_data_in_leaf': 43, 'extra_trees': False, 'early_stopping_rounds': 21, 'path_smooth': 0.062487317576532496, 'min_gain_to_split': 0.0003539329648033062}. Best is trial 144 with value: 0.05217602942733361.

Mejor trial hasta ahora: RMSE=0.052176, Parámetros={'num_leaves': 85, 'learning_rate': 0.2588994585077432, 'feature_fraction': 0.9288755876368779, 'bagging_fraction': 0.9815799532038488, 'bagging_freq': 4, 'lambda_l1': 5.9353433717208255e-06, 'lambda_l2': 2.6415000547072924e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.01650272232710863, 'min_gain_to_split': 0.009261560783558349}

[I 2025-07-09 21:52:21,577] Trial 178 finished with value: 0.08724629454518952 and parameters: {'num_leaves': 89, 'learning_rate': 0.2578723479593454, 'feature_fraction': 0.9228092443934983, 'bagging_fraction': 0.9725143101879279, 'bagging_freq': 3, 'lambda_l1': 1.0379760191197114e-05, 'lambda_l2': 1.8547666960284526e-06, 'min_child_samples': 33, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 28, 'path_smooth': 0.020578071632187857, 'min_gain_to_split': 0.019651347056656}. Best is trial 144 with value: 0.05217602942733361.

Mejor trial hasta ahora: RMSE=0.052176, Parámetros={'num_leaves': 85, 'learning_rate': 0.2588994585077432, 'feature_fraction': 0.9288755876368779, 'bagging_fraction': 0.9815799532038488, 'bagging_freq': 4, 'lambda_l1': 5.9353433717208255e-06, 'lambda_l2': 2.6415000547072924e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.01650272232710863, 'min_gain_to_split': 0.009261560783558349}

[I 2025-07-09 22:02:48,402] Trial 179 finished with value: 0.2269497096130816 and parameters: {'num_leaves': 89, 'learning_rate': 0.2610032648573049, 'feature_fraction': 0.9053515292457706, 'bagging_fraction': 0.9713947118370411, 'bagging_freq': 3, 'lambda_l1': 2.55186260475791e-06, 'lambda_l2': 7.363005222412789e-07, 'min_child_samples': 34, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 29, 'path_smooth': 0.04155321028378001, 'min_gain_to_split': 0.01982106717621024}. Best is trial 144 with value: 0.05217602942733361.

Mejor trial hasta ahora: RMSE=0.052176, Parámetros={'num_leaves': 85, 'learning_rate': 0.2588994585077432, 'feature_fraction': 0.9288755876368779, 'bagging_fraction': 0.9815799532038488, 'bagging_freq': 4, 'lambda_l1': 5.9353433717208255e-06, 'lambda_l2': 2.6415000547072924e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.01650272232710863, 'min_gain_to_split': 0.009261560783558349}

[I 2025-07-09 22:12:53,863] Trial 180 finished with value: 0.19764711357155768 and parameters: {'num_leaves': 96, 'learning_rate': 0.24984309312467293, 'feature_fraction': 0.9313738671657468, 'bagging_fraction': 0.9773314278279861, 'bagging_freq': 3, 'lambda_l1': 1.142580239136918e-05, 'lambda_l2': 2.449088621322275e-06, 'min_child_samples': 50, 'max_depth': 8, 'max_bin': 490, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.07299338913701316, 'min_gain_to_split': 0.06191559600229894}. Best is trial 144 with value: 0.05217602942733361.

Mejor trial hasta ahora: RMSE=0.052176, Parámetros={'num_leaves': 85, 'learning_rate': 0.2588994585077432, 'feature_fraction': 0.9288755876368779, 'bagging_fraction': 0.9815799532038488, 'bagging_freq': 4, 'lambda_l1': 5.9353433717208255e-06, 'lambda_l2': 2.6415000547072924e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.01650272232710863, 'min_gain_to_split': 0.009261560783558349}

[I 2025-07-09 22:21:08,795] Trial 181 finished with value: 0.33895111107894554 and parameters: {'num_leaves': 86, 'learning_rate': 0.2736003407234515, 'feature_fraction': 0.9465447387678063, 'bagging_fraction': 0.8536607433930343, 'bagging_freq': 3, 'lambda_l1': 6.570288908362052e-06, 'lambda_l2': 0.14750335707119241, 'min_child_samples': 33, 'max_depth': 7, 'max_bin': 494, 'min_data_in_leaf': 40, 'extra_trees': False, 'early_stopping_rounds': 28, 'path_smooth': 0.12650463789137195, 'min_gain_to_split': 0.02985273097407512}. Best is trial 144 with value: 0.05217602942733361.

Mejor trial hasta ahora: RMSE=0.052176, Parámetros={'num_leaves': 85, 'learning_rate': 0.2588994585077432, 'feature_fraction': 0.9288755876368779, 'bagging_fraction': 0.9815799532038488, 'bagging_freq': 4, 'lambda_l1': 5.9353433717208255e-06, 'lambda_l2': 2.6415000547072924e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.01650272232710863, 'min_gain_to_split': 0.009261560783558349}

[I 2025-07-09 22:33:19,567] Trial 182 finished with value: 0.17705538902107698 and parameters: {'num_leaves': 84, 'learning_rate': 0.23624464261373343, 'feature_fraction': 0.9239996750546032, 'bagging_fraction': 0.9879571046239369, 'bagging_freq': 4, 'lambda_l1': 1.0146009387743723e-05, 'lambda_l2': 1.7667095545483497e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 475, 'min_data_in_leaf': 35, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.01856138542552469, 'min_gain_to_split': 0.010567570742791244}. Best is trial 144 with value: 0.05217602942733361.

Mejor trial hasta ahora: RMSE=0.052176, Parámetros={'num_leaves': 85, 'learning_rate': 0.2588994585077432, 'feature_fraction': 0.9288755876368779, 'bagging_fraction': 0.9815799532038488, 'bagging_freq': 4, 'lambda_l1': 5.9353433717208255e-06, 'lambda_l2': 2.6415000547072924e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.01650272232710863, 'min_gain_to_split': 0.009261560783558349}

[I 2025-07-09 22:47:38,114] Trial 183 finished with value: 0.1519623337067598 and parameters: {'num_leaves': 88, 'learning_rate': 0.21962898686854262, 'feature_fraction': 0.9148018897528714, 'bagging_fraction': 0.9830420407504081, 'bagging_freq': 4, 'lambda_l1': 6.955375107117603e-07, 'lambda_l2': 4.090503319500107e-06, 'min_child_samples': 34, 'max_depth': 8, 'max_bin': 483, 'min_data_in_leaf': 25, 'extra_trees': False, 'early_stopping_rounds': 30, 'path_smooth': 0.00015715271304864728, 'min_gain_to_split': 0.00017010235471144435}. Best is trial 144 with value: 0.05217602942733361.

Mejor trial hasta ahora: RMSE=0.052176, Parámetros={'num_leaves': 85, 'learning_rate': 0.2588994585077432, 'feature_fraction': 0.9288755876368779, 'bagging_fraction': 0.9815799532038488, 'bagging_freq': 4, 'lambda_l1': 5.9353433717208255e-06, 'lambda_l2': 2.6415000547072924e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.01650272232710863, 'min_gain_to_split': 0.009261560783558349}

[I 2025-07-09 22:59:04,947] Trial 184 finished with value: 0.13360013082891084 and parameters: {'num_leaves': 79, 'learning_rate': 0.25597318474664627, 'feature_fraction': 0.9383260012251853, 'bagging_fraction': 0.9933427522574718, 'bagging_freq': 4, 'lambda_l1': 3.871622073131486e-06, 'lambda_l2': 2.481535845841549e-06, 'min_child_samples': 46, 'max_depth': 8, 'max_bin': 472, 'min_data_in_leaf': 36, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.02620307195233506, 'min_gain_to_split': 0.017555685008285807}. Best is trial 144 with value: 0.05217602942733361.

Mejor trial hasta ahora: RMSE=0.052176, Parámetros={'num_leaves': 85, 'learning_rate': 0.2588994585077432, 'feature_fraction': 0.9288755876368779, 'bagging_fraction': 0.9815799532038488, 'bagging_freq': 4, 'lambda_l1': 5.9353433717208255e-06, 'lambda_l2': 2.6415000547072924e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.01650272232710863, 'min_gain_to_split': 0.009261560783558349}

[I 2025-07-09 23:10:55,182] Trial 185 finished with value: 0.14165598246190983 and parameters: {'num_leaves': 86, 'learning_rate': 0.1987140300635567, 'feature_fraction': 0.9612195658975531, 'bagging_fraction': 0.9871136229565873, 'bagging_freq': 4, 'lambda_l1': 3.1429294357669384e-05, 'lambda_l2': 1.0155601277556247e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 44, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.044505830246168346, 'min_gain_to_split': 0.041861663440622095}. Best is trial 144 with value: 0.05217602942733361.

Mejor trial hasta ahora: RMSE=0.052176, Parámetros={'num_leaves': 85, 'learning_rate': 0.2588994585077432, 'feature_fraction': 0.9288755876368779, 'bagging_fraction': 0.9815799532038488, 'bagging_freq': 4, 'lambda_l1': 5.9353433717208255e-06, 'lambda_l2': 2.6415000547072924e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.01650272232710863, 'min_gain_to_split': 0.009261560783558349}

[I 2025-07-09 23:19:12,948] Trial 186 finished with value: 0.10485453577791763 and parameters: {'num_leaves': 93, 'learning_rate': 0.2344942948025777, 'feature_fraction': 0.925222844017756, 'bagging_fraction': 0.9734508696443611, 'bagging_freq': 4, 'lambda_l1': 6.597900367153458e-06, 'lambda_l2': 7.951097737507854e-06, 'min_child_samples': 30, 'max_depth': 8, 'max_bin': 276, 'min_data_in_leaf': 42, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.06177049408807263, 'min_gain_to_split': 0.02319350129205349}. Best is trial 144 with value: 0.05217602942733361.

Mejor trial hasta ahora: RMSE=0.052176, Parámetros={'num_leaves': 85, 'learning_rate': 0.2588994585077432, 'feature_fraction': 0.9288755876368779, 'bagging_fraction': 0.9815799532038488, 'bagging_freq': 4, 'lambda_l1': 5.9353433717208255e-06, 'lambda_l2': 2.6415000547072924e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.01650272232710863, 'min_gain_to_split': 0.009261560783558349}

[I 2025-07-09 23:32:07,867] Trial 187 finished with value: 0.0678567033503142 and parameters: {'num_leaves': 75, 'learning_rate': 0.214799306113645, 'feature_fraction': 0.9478644733481877, 'bagging_fraction': 0.9818708517007892, 'bagging_freq': 4, 'lambda_l1': 5.0084201003308816e-05, 'lambda_l2': 4.8617852164740085e-06, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 484, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 31, 'path_smooth': 0.024218233973944063, 'min_gain_to_split': 0.031326730339288955}. Best is trial 144 with value: 0.05217602942733361.

Mejor trial hasta ahora: RMSE=0.052176, Parámetros={'num_leaves': 85, 'learning_rate': 0.2588994585077432, 'feature_fraction': 0.9288755876368779, 'bagging_fraction': 0.9815799532038488, 'bagging_freq': 4, 'lambda_l1': 5.9353433717208255e-06, 'lambda_l2': 2.6415000547072924e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.01650272232710863, 'min_gain_to_split': 0.009261560783558349}

[I 2025-07-09 23:41:27,327] Trial 188 finished with value: 0.2369015320424655 and parameters: {'num_leaves': 76, 'learning_rate': 0.2790477606438406, 'feature_fraction': 0.9515861678761788, 'bagging_fraction': 0.9681712390588626, 'bagging_freq': 3, 'lambda_l1': 0.0004227870262377628, 'lambda_l2': 3.892130486688777e-06, 'min_child_samples': 29, 'max_depth': 8, 'max_bin': 487, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 31, 'path_smooth': 0.034455172438499486, 'min_gain_to_split': 0.05053139161572236}. Best is trial 144 with value: 0.05217602942733361.

Mejor trial hasta ahora: RMSE=0.052176, Parámetros={'num_leaves': 85, 'learning_rate': 0.2588994585077432, 'feature_fraction': 0.9288755876368779, 'bagging_fraction': 0.9815799532038488, 'bagging_freq': 4, 'lambda_l1': 5.9353433717208255e-06, 'lambda_l2': 2.6415000547072924e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.01650272232710863, 'min_gain_to_split': 0.009261560783558349}

[I 2025-07-09 23:51:53,094] Trial 189 finished with value: 0.14809019937134446 and parameters: {'num_leaves': 78, 'learning_rate': 0.24656810105576601, 'feature_fraction': 0.8532310765713352, 'bagging_fraction': 0.9801929992928615, 'bagging_freq': 4, 'lambda_l1': 4.9612023120235326e-05, 'lambda_l2': 1.565137428530778e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 459, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 36, 'path_smooth': 0.08560572314313483, 'min_gain_to_split': 0.03240923368473859}. Best is trial 144 with value: 0.05217602942733361.

Mejor trial hasta ahora: RMSE=0.052176, Parámetros={'num_leaves': 85, 'learning_rate': 0.2588994585077432, 'feature_fraction': 0.9288755876368779, 'bagging_fraction': 0.9815799532038488, 'bagging_freq': 4, 'lambda_l1': 5.9353433717208255e-06, 'lambda_l2': 2.6415000547072924e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.01650272232710863, 'min_gain_to_split': 0.009261560783558349}

[I 2025-07-10 00:03:45,034] Trial 190 finished with value: 0.21252508053399416 and parameters: {'num_leaves': 90, 'learning_rate': 0.22256362968880125, 'feature_fraction': 0.9593093294819274, 'bagging_fraction': 0.9832562323135063, 'bagging_freq': 4, 'lambda_l1': 0.00016476009332999173, 'lambda_l2': 3.1481942737274256e-06, 'min_child_samples': 38, 'max_depth': 8, 'max_bin': 492, 'min_data_in_leaf': 40, 'extra_trees': False, 'early_stopping_rounds': 21, 'path_smooth': 0.05880707601221277, 'min_gain_to_split': 0.029434222906626895}. Best is trial 144 with value: 0.05217602942733361.

Mejor trial hasta ahora: RMSE=0.052176, Parámetros={'num_leaves': 85, 'learning_rate': 0.2588994585077432, 'feature_fraction': 0.9288755876368779, 'bagging_fraction': 0.9815799532038488, 'bagging_freq': 4, 'lambda_l1': 5.9353433717208255e-06, 'lambda_l2': 2.6415000547072924e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.01650272232710863, 'min_gain_to_split': 0.009261560783558349}

[I 2025-07-10 00:23:40,388] Trial 191 finished with value: 0.9561888946099236 and parameters: {'num_leaves': 74, 'learning_rate': 0.02586704229658569, 'feature_fraction': 0.9446169975207628, 'bagging_fraction': 0.975616034255816, 'bagging_freq': 4, 'lambda_l1': 2.138297125920291e-06, 'lambda_l2': 4.723105367878935e-06, 'min_child_samples': 33, 'max_depth': 7, 'max_bin': 500, 'min_data_in_leaf': 35, 'extra_trees': False, 'early_stopping_rounds': 21, 'path_smooth': 0.00029815589749070115, 'min_gain_to_split': 0.04110441230881156}. Best is trial 144 with value: 0.05217602942733361.

Mejor trial hasta ahora: RMSE=0.052176, Parámetros={'num_leaves': 85, 'learning_rate': 0.2588994585077432, 'feature_fraction': 0.9288755876368779, 'bagging_fraction': 0.9815799532038488, 'bagging_freq': 4, 'lambda_l1': 5.9353433717208255e-06, 'lambda_l2': 2.6415000547072924e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.01650272232710863, 'min_gain_to_split': 0.009261560783558349}

[I 2025-07-10 00:36:40,212] Trial 192 finished with value: 0.18189505751666338 and parameters: {'num_leaves': 81, 'learning_rate': 0.21607299904336946, 'feature_fraction': 0.9314983336164447, 'bagging_fraction': 0.9939717343290135, 'bagging_freq': 4, 'lambda_l1': 1.36962715362152e-05, 'lambda_l2': 6.396126763921782e-06, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 481, 'min_data_in_leaf': 30, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.019150237203644036, 'min_gain_to_split': 0.010613016049406567}. Best is trial 144 with value: 0.05217602942733361.

Mejor trial hasta ahora: RMSE=0.052176, Parámetros={'num_leaves': 85, 'learning_rate': 0.2588994585077432, 'feature_fraction': 0.9288755876368779, 'bagging_fraction': 0.9815799532038488, 'bagging_freq': 4, 'lambda_l1': 5.9353433717208255e-06, 'lambda_l2': 2.6415000547072924e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.01650272232710863, 'min_gain_to_split': 0.009261560783558349}

[I 2025-07-10 00:58:18,074] Trial 193 finished with value: 0.6671738983745428 and parameters: {'num_leaves': 83, 'learning_rate': 0.05558926558349452, 'feature_fraction': 0.9426865709501665, 'bagging_fraction': 0.9894948680209444, 'bagging_freq': 4, 'lambda_l1': 2.2289078128355818e-05, 'lambda_l2': 9.920730747547102e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 477, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 29, 'path_smooth': 0.02222409277730855, 'min_gain_to_split': 0.01803707111348805}. Best is trial 144 with value: 0.05217602942733361.

Mejor trial hasta ahora: RMSE=0.052176, Parámetros={'num_leaves': 85, 'learning_rate': 0.2588994585077432, 'feature_fraction': 0.9288755876368779, 'bagging_fraction': 0.9815799532038488, 'bagging_freq': 4, 'lambda_l1': 5.9353433717208255e-06, 'lambda_l2': 2.6415000547072924e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.01650272232710863, 'min_gain_to_split': 0.009261560783558349}

[I 2025-07-10 01:12:51,595] Trial 194 finished with value: 0.04515360263262301 and parameters: {'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 01:25:45,641] Trial 195 finished with value: 0.07398290471901348 and parameters: {'num_leaves': 78, 'learning_rate': 0.2636894400746393, 'feature_fraction': 0.936355181551644, 'bagging_fraction': 0.9888154347743586, 'bagging_freq': 4, 'lambda_l1': 4.352189569200285e-06, 'lambda_l2': 2.0291860153420586e-05, 'min_child_samples': 33, 'max_depth': 8, 'max_bin': 487, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.047856137270987746, 'min_gain_to_split': 0.006578222523565793}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 01:37:18,107] Trial 196 finished with value: 0.14588535739970845 and parameters: {'num_leaves': 75, 'learning_rate': 0.26594131568974255, 'feature_fraction': 0.9360486513261475, 'bagging_fraction': 0.9994707546005549, 'bagging_freq': 4, 'lambda_l1': 4.737182339281066e-06, 'lambda_l2': 1.4759027125175726e-05, 'min_child_samples': 33, 'max_depth': 8, 'max_bin': 487, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.04984636846653238, 'min_gain_to_split': 0.0019246950871019105}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 01:59:17,495] Trial 197 finished with value: 0.3652281383947087 and parameters: {'num_leaves': 78, 'learning_rate': 0.07782598822755699, 'feature_fraction': 0.9525277781205546, 'bagging_fraction': 0.9899149796473187, 'bagging_freq': 4, 'lambda_l1': 8.65782694259862e-06, 'lambda_l2': 2.1495724595379594e-06, 'min_child_samples': 35, 'max_depth': 8, 'max_bin': 493, 'min_data_in_leaf': 39, 'extra_trees': False, 'early_stopping_rounds': 31, 'path_smooth': 0.09065458098787141, 'min_gain_to_split': 0.023029605154593034}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 02:11:34,573] Trial 198 finished with value: 0.29008381889755464 and parameters: {'num_leaves': 79, 'learning_rate': 0.18842974408827445, 'feature_fraction': 0.9292396934062888, 'bagging_fraction': 0.9805836343949771, 'bagging_freq': 3, 'lambda_l1': 6.403397683670429e-06, 'lambda_l2': 2.0001901775359904e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 485, 'min_data_in_leaf': 74, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.07218334251403263, 'min_gain_to_split': 0.011572812726537759}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 02:22:02,937] Trial 199 finished with value: 0.04873131990623058 and parameters: {'num_leaves': 81, 'learning_rate': 0.288235098858203, 'feature_fraction': 0.9043903223766959, 'bagging_fraction': 0.9936218281974978, 'bagging_freq': 4, 'lambda_l1': 3.002041689018127e-06, 'lambda_l2': 3.2111064870615767e-06, 'min_child_samples': 34, 'max_depth': 8, 'max_bin': 494, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 33, 'path_smooth': 0.9574384656744148, 'min_gain_to_split': 0.02908185739410488}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 02:26:30,521] Trial 200 finished with value: 0.4646812774290071 and parameters: {'num_leaves': 85, 'learning_rate': 0.28255373732870015, 'feature_fraction': 0.9068787673075499, 'bagging_fraction': 0.9871361770216461, 'bagging_freq': 4, 'lambda_l1': 9.7150326395183e-07, 'lambda_l2': 2.9973014195943383e-06, 'min_child_samples': 34, 'max_depth': 8, 'max_bin': 492, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 33, 'path_smooth': 0.7568494780343825, 'min_gain_to_split': 0.03286402724237381}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 02:37:56,921] Trial 201 finished with value: 0.07883039726749605 and parameters: {'num_leaves': 80, 'learning_rate': 0.29508308322098936, 'feature_fraction': 0.9402800836704874, 'bagging_fraction': 0.971652594376376, 'bagging_freq': 4, 'lambda_l1': 1.4719856091955728e-06, 'lambda_l2': 1.7043116585925892e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 495, 'min_data_in_leaf': 35, 'extra_trees': False, 'early_stopping_rounds': 33, 'path_smooth': 0.8522106563000293, 'min_gain_to_split': 0.00010337620820227884}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 02:49:50,520] Trial 202 finished with value: 0.10393216985629486 and parameters: {'num_leaves': 76, 'learning_rate': 0.2930671897849225, 'feature_fraction': 0.9414279027681678, 'bagging_fraction': 0.9999434345787532, 'bagging_freq': 4, 'lambda_l1': 1.3290793381104786e-06, 'lambda_l2': 1.3074992398289313e-06, 'min_child_samples': 37, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 35, 'extra_trees': False, 'early_stopping_rounds': 34, 'path_smooth': 0.941449764626088, 'min_gain_to_split': 0.0009760397105278325}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 03:00:29,582] Trial 203 finished with value: 0.1395785506553041 and parameters: {'num_leaves': 80, 'learning_rate': 0.2642637116066764, 'feature_fraction': 0.9237653773384872, 'bagging_fraction': 0.9714291580037274, 'bagging_freq': 4, 'lambda_l1': 3.1526556798718143e-06, 'lambda_l2': 1.943109475150403e-06, 'min_child_samples': 35, 'max_depth': 8, 'max_bin': 494, 'min_data_in_leaf': 36, 'extra_trees': False, 'early_stopping_rounds': 32, 'path_smooth': 0.8490676900478031, 'min_gain_to_split': 0.02147585423248298}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 03:11:44,969] Trial 204 finished with value: 0.14205945794671732 and parameters: {'num_leaves': 77, 'learning_rate': 0.28593396677904803, 'feature_fraction': 0.9520641906730875, 'bagging_fraction': 0.9799079003451232, 'bagging_freq': 4, 'lambda_l1': 2.5934897586571126e-06, 'lambda_l2': 1.0971488365667207e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 488, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 33, 'path_smooth': 0.9044665157421886, 'min_gain_to_split': 0.007737707236514714}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 03:22:55,058] Trial 205 finished with value: 0.12709271559824115 and parameters: {'num_leaves': 80, 'learning_rate': 0.26079334272684324, 'feature_fraction': 0.9371958910806056, 'bagging_fraction': 0.9866482458030476, 'bagging_freq': 4, 'lambda_l1': 1.7395035341181735e-06, 'lambda_l2': 3.116580953977416e-06, 'min_child_samples': 33, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 40, 'extra_trees': False, 'early_stopping_rounds': 31, 'path_smooth': 0.9454511952611879, 'min_gain_to_split': 0.026169258081412863}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 03:33:42,145] Trial 206 finished with value: 0.0795795703144413 and parameters: {'num_leaves': 84, 'learning_rate': 0.2941240559654333, 'feature_fraction': 0.9601689819706907, 'bagging_fraction': 0.9660698478762304, 'bagging_freq': 4, 'lambda_l1': 4.06809257261043e-06, 'lambda_l2': 5.245974499277956e-06, 'min_child_samples': 34, 'max_depth': 8, 'max_bin': 471, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 34, 'path_smooth': 0.7098664566509811, 'min_gain_to_split': 0.018215253676562026}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 03:44:58,892] Trial 207 finished with value: 0.08031064329511525 and parameters: {'num_leaves': 75, 'learning_rate': 0.29185000093297214, 'feature_fraction': 0.965083185082785, 'bagging_fraction': 0.9648517074432342, 'bagging_freq': 4, 'lambda_l1': 3.4201934382712894e-06, 'lambda_l2': 8.879993396806281e-06, 'min_child_samples': 35, 'max_depth': 8, 'max_bin': 465, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 36, 'path_smooth': 0.8755809790607363, 'min_gain_to_split': 0.0005722635728505274}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 03:55:23,825] Trial 208 finished with value: 0.1523427605719576 and parameters: {'num_leaves': 75, 'learning_rate': 0.2807787269618013, 'feature_fraction': 0.963029354971957, 'bagging_fraction': 0.9602917503041444, 'bagging_freq': 3, 'lambda_l1': 3.920930936316814e-06, 'lambda_l2': 1.1595466642674797e-05, 'min_child_samples': 35, 'max_depth': 8, 'max_bin': 463, 'min_data_in_leaf': 39, 'extra_trees': False, 'early_stopping_rounds': 36, 'path_smooth': 0.8788038955886405, 'min_gain_to_split': 0.017886653628246277}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 04:06:01,252] Trial 209 finished with value: 0.27287912480822973 and parameters: {'num_leaves': 78, 'learning_rate': 0.2964962759830128, 'feature_fraction': 0.9633848266365242, 'bagging_fraction': 0.9554045185596105, 'bagging_freq': 4, 'lambda_l1': 1.1978683325792857e-06, 'lambda_l2': 8.506403890878402e-06, 'min_child_samples': 34, 'max_depth': 8, 'max_bin': 471, 'min_data_in_leaf': 41, 'extra_trees': False, 'early_stopping_rounds': 34, 'path_smooth': 0.9320440767090027, 'min_gain_to_split': 0.0011502847905505928}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 04:17:22,224] Trial 210 finished with value: 0.05483465515877486 and parameters: {'num_leaves': 73, 'learning_rate': 0.2930935565951459, 'feature_fraction': 0.9688432099847913, 'bagging_fraction': 0.9659968690799958, 'bagging_freq': 4, 'lambda_l1': 2.0370219654329174e-06, 'lambda_l2': 1.975770351221507e-05, 'min_child_samples': 33, 'max_depth': 8, 'max_bin': 470, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 35, 'path_smooth': 0.8187987306110958, 'min_gain_to_split': 0.015502863778658001}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 04:28:12,033] Trial 211 finished with value: 0.08947715093460265 and parameters: {'num_leaves': 73, 'learning_rate': 0.2901635352396117, 'feature_fraction': 0.96836683125096, 'bagging_fraction': 0.9660377247112005, 'bagging_freq': 4, 'lambda_l1': 2.150677755280556e-06, 'lambda_l2': 2.3096027527159473e-05, 'min_child_samples': 34, 'max_depth': 8, 'max_bin': 481, 'min_data_in_leaf': 39, 'extra_trees': False, 'early_stopping_rounds': 35, 'path_smooth': 0.792071358674265, 'min_gain_to_split': 0.015050667879042905}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 04:38:16,829] Trial 212 finished with value: 0.15775789377568805 and parameters: {'num_leaves': 72, 'learning_rate': 0.28973176499814773, 'feature_fraction': 0.9703114966040365, 'bagging_fraction': 0.965757582504713, 'bagging_freq': 4, 'lambda_l1': 1.918411995791431e-06, 'lambda_l2': 2.9718273311106015e-05, 'min_child_samples': 34, 'max_depth': 8, 'max_bin': 482, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 37, 'path_smooth': 0.8491127206678367, 'min_gain_to_split': 0.017200008062241118}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 04:48:20,981] Trial 213 finished with value: 0.11803960988594228 and parameters: {'num_leaves': 74, 'learning_rate': 0.29831315391731594, 'feature_fraction': 0.957309962587972, 'bagging_fraction': 0.9695638250442541, 'bagging_freq': 4, 'lambda_l1': 4.415845462936176e-06, 'lambda_l2': 1.859151936721889e-05, 'min_child_samples': 33, 'max_depth': 8, 'max_bin': 470, 'min_data_in_leaf': 42, 'extra_trees': False, 'early_stopping_rounds': 35, 'path_smooth': 0.8107013268616443, 'min_gain_to_split': 0.010096232938103798}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 04:59:41,323] Trial 214 finished with value: 0.16196488181127935 and parameters: {'num_leaves': 75, 'learning_rate': 0.27315604922229647, 'feature_fraction': 0.945469235702267, 'bagging_fraction': 0.9468945866858349, 'bagging_freq': 4, 'lambda_l1': 5.288688243373247e-07, 'lambda_l2': 5.766712848772746e-06, 'min_child_samples': 35, 'max_depth': 8, 'max_bin': 478, 'min_data_in_leaf': 39, 'extra_trees': False, 'early_stopping_rounds': 35, 'path_smooth': 0.7868287965068658, 'min_gain_to_split': 8.73772936469131e-05}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 05:08:27,146] Trial 215 finished with value: 0.3632848837324947 and parameters: {'num_leaves': 73, 'learning_rate': 0.29829026929588387, 'feature_fraction': 0.9685429495579065, 'bagging_fraction': 0.9729408503912086, 'bagging_freq': 4, 'lambda_l1': 2.156244492087568e-06, 'lambda_l2': 1.5886818900575683e-05, 'min_child_samples': 33, 'max_depth': 8, 'max_bin': 485, 'min_data_in_leaf': 68, 'extra_trees': False, 'early_stopping_rounds': 34, 'path_smooth': 0.8202104892476417, 'min_gain_to_split': 0.02713056718335024}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 05:19:17,768] Trial 216 finished with value: 0.10145046957155235 and parameters: {'num_leaves': 79, 'learning_rate': 0.27859608680830444, 'feature_fraction': 0.9590789026496112, 'bagging_fraction': 0.9640584686814309, 'bagging_freq': 8, 'lambda_l1': 2.9639839716369704e-06, 'lambda_l2': 5.422596981074549e-06, 'min_child_samples': 34, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 36, 'extra_trees': False, 'early_stopping_rounds': 35, 'path_smooth': 0.7298418061017844, 'min_gain_to_split': 0.01862407831610375}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 07:48:52,499] Trial 217 finished with value: 0.07376343060986795 and parameters: {'num_leaves': 91, 'learning_rate': 0.26311467046979864, 'feature_fraction': 0.8852995468033719, 'bagging_fraction': 0.9752503739869566, 'bagging_freq': 4, 'lambda_l1': 1.1144381443141456e-06, 'lambda_l2': 3.014180803137442e-06, 'min_child_samples': 35, 'max_depth': 8, 'max_bin': 473, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 37, 'path_smooth': 0.8782622879369885, 'min_gain_to_split': 0.008532850573677128}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 07:58:20,143] Trial 218 finished with value: 0.20115744794977522 and parameters: {'num_leaves': 91, 'learning_rate': 0.2999727622481958, 'feature_fraction': 0.8856758395474309, 'bagging_fraction': 0.9548491489176505, 'bagging_freq': 4, 'lambda_l1': 1.2812083936211263e-06, 'lambda_l2': 2.3529608345956947e-06, 'min_child_samples': 37, 'max_depth': 8, 'max_bin': 460, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 38, 'path_smooth': 0.8656019218715081, 'min_gain_to_split': 0.0318859389620313}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 08:11:37,233] Trial 219 finished with value: 0.2449088903339876 and parameters: {'num_leaves': 93, 'learning_rate': 0.2676718706409776, 'feature_fraction': 0.9481316362811758, 'bagging_fraction': 0.9687971082130872, 'bagging_freq': 4, 'lambda_l1': 1.0530480411083832e-06, 'lambda_l2': 4.578355342953913, 'min_child_samples': 35, 'max_depth': 8, 'max_bin': 471, 'min_data_in_leaf': 36, 'extra_trees': False, 'early_stopping_rounds': 32, 'path_smooth': 0.788777344971835, 'min_gain_to_split': 0.01314253784044455}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 08:22:58,359] Trial 220 finished with value: 0.12115707375171074 and parameters: {'num_leaves': 88, 'learning_rate': 0.2549887086956174, 'feature_fraction': 0.8748185765938793, 'bagging_fraction': 0.9754166518303442, 'bagging_freq': 4, 'lambda_l1': 7.636540336769457e-07, 'lambda_l2': 2.342188172269547e-05, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 479, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 38, 'path_smooth': 0.8352263642463801, 'min_gain_to_split': 0.02209881650303009}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 08:35:15,566] Trial 221 finished with value: 0.09189646530075671 and parameters: {'num_leaves': 90, 'learning_rate': 0.2524539983557256, 'feature_fraction': 0.9090382208632161, 'bagging_fraction': 0.9648941122867672, 'bagging_freq': 3, 'lambda_l1': 1.6621050206151165e-06, 'lambda_l2': 8.206348739345088e-06, 'min_child_samples': 34, 'max_depth': 8, 'max_bin': 467, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 37, 'path_smooth': 0.6911328151734408, 'min_gain_to_split': 0.012677329192513962}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 08:49:55,933] Trial 222 finished with value: 0.12715281823829322 and parameters: {'num_leaves': 77, 'learning_rate': 0.2747832368212399, 'feature_fraction': 0.9009980282760819, 'bagging_fraction': 0.9931577691067317, 'bagging_freq': 4, 'lambda_l1': 9.757152204352811e-06, 'lambda_l2': 3.3174104551208666e-06, 'min_child_samples': 33, 'max_depth': 8, 'max_bin': 490, 'min_data_in_leaf': 40, 'extra_trees': False, 'early_stopping_rounds': 36, 'path_smooth': 0.865021175757122, 'min_gain_to_split': 0.00947680512340374}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 09:03:09,537] Trial 223 finished with value: 0.1539084457600604 and parameters: {'num_leaves': 71, 'learning_rate': 0.26796239434071795, 'feature_fraction': 0.9388749681207664, 'bagging_fraction': 0.9825668729738692, 'bagging_freq': 4, 'lambda_l1': 5.253084666198291e-06, 'lambda_l2': 5.110034453032259e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 476, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 34, 'path_smooth': 0.777348062648127, 'min_gain_to_split': 0.000918387134975867}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 09:14:30,775] Trial 224 finished with value: 0.38504385743973557 and parameters: {'num_leaves': 75, 'learning_rate': 0.2473110869792893, 'feature_fraction': 0.9624308902756247, 'bagging_fraction': 0.8034150049012387, 'bagging_freq': 4, 'lambda_l1': 3.240519766733618e-06, 'lambda_l2': 1.599835170644016e-06, 'min_child_samples': 34, 'max_depth': 8, 'max_bin': 489, 'min_data_in_leaf': 35, 'extra_trees': False, 'early_stopping_rounds': 35, 'path_smooth': 0.9727810515438864, 'min_gain_to_split': 0.02498501099562027}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 09:23:07,704] Trial 225 finished with value: 0.24906188116491856 and parameters: {'num_leaves': 77, 'learning_rate': 0.279412977495051, 'feature_fraction': 0.8014377614753676, 'bagging_fraction': 0.9944972497089484, 'bagging_freq': 4, 'lambda_l1': 2.1733106351169805e-06, 'lambda_l2': 3.5367030052642e-06, 'min_child_samples': 35, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 86, 'extra_trees': False, 'early_stopping_rounds': 33, 'path_smooth': 0.8887942607204746, 'min_gain_to_split': 0.00874469020395403}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 09:35:58,635] Trial 226 finished with value: 0.1835499372790746 and parameters: {'num_leaves': 81, 'learning_rate': 0.24802754661938883, 'feature_fraction': 0.9501056608851745, 'bagging_fraction': 0.9763777740875846, 'bagging_freq': 4, 'lambda_l1': 7.95336888174605e-06, 'lambda_l2': 2.2638358783256593e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 482, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 32, 'path_smooth': 0.8466516708365751, 'min_gain_to_split': 0.036723358549825134}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 09:49:01,375] Trial 227 finished with value: 0.1302106219599219 and parameters: {'num_leaves': 73, 'learning_rate': 0.26393372781532176, 'feature_fraction': 0.9727085069751039, 'bagging_fraction': 0.9849173250395074, 'bagging_freq': 4, 'lambda_l1': 4.425139161375936e-06, 'lambda_l2': 9.40815483854111e-06, 'min_child_samples': 33, 'max_depth': 8, 'max_bin': 491, 'min_data_in_leaf': 41, 'extra_trees': False, 'early_stopping_rounds': 36, 'path_smooth': 0.9010158705304171, 'min_gain_to_split': 0.019525837600420575}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 09:59:59,061] Trial 228 finished with value: 0.4916001576526689 and parameters: {'num_leaves': 79, 'learning_rate': 0.2794281320842486, 'feature_fraction': 0.9336888674777154, 'bagging_fraction': 0.9906725937940726, 'bagging_freq': 4, 'lambda_l1': 1.8393245509666496, 'lambda_l2': 5.200389059838474e-05, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 475, 'min_data_in_leaf': 36, 'extra_trees': False, 'early_stopping_rounds': 33, 'path_smooth': 0.8275096184620964, 'min_gain_to_split': 0.008280789702387511}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 10:09:33,286] Trial 229 finished with value: 0.2847417802229429 and parameters: {'num_leaves': 95, 'learning_rate': 0.23947275984616861, 'feature_fraction': 0.8943874016978655, 'bagging_fraction': 0.9997575349847796, 'bagging_freq': 4, 'lambda_l1': 3.53428088724981e-06, 'lambda_l2': 3.6318804395341794e-06, 'min_child_samples': 32, 'max_depth': 7, 'max_bin': 484, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 37, 'path_smooth': 0.8100522963641714, 'min_gain_to_split': 0.030217453425997617}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 10:15:30,198] Trial 230 finished with value: 0.33237579122706185 and parameters: {'num_leaves': 91, 'learning_rate': 0.2975553023733497, 'feature_fraction': 0.9697862618354022, 'bagging_fraction': 0.9792894057806915, 'bagging_freq': 4, 'lambda_l1': 7.367036389632525e-06, 'lambda_l2': 6.400332181840284e-06, 'min_child_samples': 34, 'max_depth': 8, 'max_bin': 121, 'min_data_in_leaf': 39, 'extra_trees': False, 'early_stopping_rounds': 30, 'path_smooth': 0.8730942875342524, 'min_gain_to_split': 0.017624844618380042}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 10:29:05,562] Trial 231 finished with value: 0.07719140664987449 and parameters: {'num_leaves': 76, 'learning_rate': 0.26242608641829396, 'feature_fraction': 0.9431446345453136, 'bagging_fraction': 0.9726408725613956, 'bagging_freq': 4, 'lambda_l1': 2.3678787360628466e-06, 'lambda_l2': 1.4553929298620794e-06, 'min_child_samples': 35, 'max_depth': 8, 'max_bin': 492, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 34, 'path_smooth': 0.9225888456979728, 'min_gain_to_split': 8.252611658030008e-05}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 10:42:32,755] Trial 232 finished with value: 0.17510752930166512 and parameters: {'num_leaves': 75, 'learning_rate': 0.2652818061910488, 'feature_fraction': 0.9425913407077586, 'bagging_fraction': 0.765882014909963, 'bagging_freq': 4, 'lambda_l1': 2.342507852034295e-06, 'lambda_l2': 1.4516828140172707e-06, 'min_child_samples': 35, 'max_depth': 8, 'max_bin': 494, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 35, 'path_smooth': 0.9215026211630769, 'min_gain_to_split': 0.00038246097598091874}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 10:55:51,402] Trial 233 finished with value: 0.08618746167489966 and parameters: {'num_leaves': 77, 'learning_rate': 0.2480803290514748, 'feature_fraction': 0.9552803509299279, 'bagging_fraction': 0.9609186241088912, 'bagging_freq': 4, 'lambda_l1': 1.7068025914831255e-06, 'lambda_l2': 2.3815696292809583e-06, 'min_child_samples': 33, 'max_depth': 8, 'max_bin': 493, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 34, 'path_smooth': 0.980403532643338, 'min_gain_to_split': 0.009614368145906937}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 11:08:11,978] Trial 234 finished with value: 0.0794457373667827 and parameters: {'num_leaves': 77, 'learning_rate': 0.251804837830022, 'feature_fraction': 0.9329507457121021, 'bagging_fraction': 0.9591316290427689, 'bagging_freq': 4, 'lambda_l1': 1.453023844574153e-06, 'lambda_l2': 6.499520052057132e-07, 'min_child_samples': 34, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 33, 'path_smooth': 0.9454465280622191, 'min_gain_to_split': 0.015814750988813034}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 11:20:29,206] Trial 235 finished with value: 0.09345597330390856 and parameters: {'num_leaves': 78, 'learning_rate': 0.2520736481079217, 'feature_fraction': 0.9215660795161459, 'bagging_fraction': 0.9595550749765803, 'bagging_freq': 4, 'lambda_l1': 1.4060390891338977e-06, 'lambda_l2': 9.000591294115743e-07, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 34, 'path_smooth': 0.9456065932492531, 'min_gain_to_split': 0.00879061336467828}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 11:32:29,737] Trial 236 finished with value: 0.16935852487834052 and parameters: {'num_leaves': 81, 'learning_rate': 0.2438041997692403, 'feature_fraction': 0.9294678289998716, 'bagging_fraction': 0.9724003744906748, 'bagging_freq': 4, 'lambda_l1': 9.982930218363155e-07, 'lambda_l2': 3.4557797243521676e-07, 'min_child_samples': 33, 'max_depth': 8, 'max_bin': 488, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 33, 'path_smooth': 0.9242416928126176, 'min_gain_to_split': 0.02304325052528317}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 11:43:35,310] Trial 237 finished with value: 0.24403792763848942 and parameters: {'num_leaves': 77, 'learning_rate': 0.2304150882380597, 'feature_fraction': 0.9346877734928405, 'bagging_fraction': 0.9588940880812741, 'bagging_freq': 4, 'lambda_l1': 5.533429039855964e-06, 'lambda_l2': 9.291564939093063e-07, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 494, 'min_data_in_leaf': 35, 'extra_trees': False, 'early_stopping_rounds': 32, 'path_smooth': 0.9125731338699478, 'min_gain_to_split': 0.033764404652798036}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 11:55:06,016] Trial 238 finished with value: 0.21169332276578792 and parameters: {'num_leaves': 80, 'learning_rate': 0.2629015818498599, 'feature_fraction': 0.9411807771412729, 'bagging_fraction': 0.9693788180394969, 'bagging_freq': 4, 'lambda_l1': 5.191065324324659e-07, 'lambda_l2': 1.7246421155902898e-06, 'min_child_samples': 35, 'max_depth': 8, 'max_bin': 489, 'min_data_in_leaf': 31, 'extra_trees': False, 'early_stopping_rounds': 34, 'path_smooth': 0.9819529483140795, 'min_gain_to_split': 0.009831160692055712}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 11:59:54,914] Trial 239 finished with value: 0.4124679145729946 and parameters: {'num_leaves': 86, 'learning_rate': 0.24987343379419105, 'feature_fraction': 0.9492016012916716, 'bagging_fraction': 0.9487963259926687, 'bagging_freq': 4, 'lambda_l1': 1.516876569312871e-06, 'lambda_l2': 4.6998346236811553e-07, 'min_child_samples': 37, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 34, 'path_smooth': 0.9672945690666452, 'min_gain_to_split': 0.02496784698827531}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 12:11:47,887] Trial 240 finished with value: 0.05246002573214183 and parameters: {'num_leaves': 82, 'learning_rate': 0.2710438301487577, 'feature_fraction': 0.9230385754495486, 'bagging_fraction': 0.9762164485076377, 'bagging_freq': 4, 'lambda_l1': 0.00024836343577416136, 'lambda_l2': 2.459554038130632e-06, 'min_child_samples': 34, 'max_depth': 8, 'max_bin': 472, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 33, 'path_smooth': 0.9583985946241949, 'min_gain_to_split': 0.016780347286727348}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 12:23:48,856] Trial 241 finished with value: 0.12741002636842713 and parameters: {'num_leaves': 82, 'learning_rate': 0.2729409570856022, 'feature_fraction': 0.9206228989503205, 'bagging_fraction': 0.973831818928644, 'bagging_freq': 4, 'lambda_l1': 6.915825640324892e-05, 'lambda_l2': 7.214320230379132e-07, 'min_child_samples': 34, 'max_depth': 8, 'max_bin': 482, 'min_data_in_leaf': 31, 'extra_trees': False, 'early_stopping_rounds': 33, 'path_smooth': 0.9542994919776838, 'min_gain_to_split': 0.01701216885099805}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 12:37:15,790] Trial 242 finished with value: 0.09503008146803715 and parameters: {'num_leaves': 79, 'learning_rate': 0.2648613711291566, 'feature_fraction': 0.9301843805148047, 'bagging_fraction': 0.9802954948736845, 'bagging_freq': 4, 'lambda_l1': 0.00017683230394273397, 'lambda_l2': 2.5124846273362665e-06, 'min_child_samples': 33, 'max_depth': 8, 'max_bin': 472, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 31, 'path_smooth': 0.9782651032556596, 'min_gain_to_split': 0.007753085332553443}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 12:48:42,716] Trial 243 finished with value: 0.11433587263180685 and parameters: {'num_leaves': 82, 'learning_rate': 0.2788817042052254, 'feature_fraction': 0.9375581422731385, 'bagging_fraction': 0.9626766097923499, 'bagging_freq': 4, 'lambda_l1': 0.0002561965563956537, 'lambda_l2': 1.6464526832856337e-06, 'min_child_samples': 34, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 36, 'extra_trees': False, 'early_stopping_rounds': 33, 'path_smooth': 0.9657848241502033, 'min_gain_to_split': 0.00010519780691677777}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 12:59:48,330] Trial 244 finished with value: 0.3428969204151838 and parameters: {'num_leaves': 84, 'learning_rate': 0.23246890366156256, 'feature_fraction': 0.9118528658744572, 'bagging_fraction': 0.984657295578829, 'bagging_freq': 4, 'lambda_l1': 2.762958835568044e-06, 'lambda_l2': 2.257191263930528e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 487, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 32, 'path_smooth': 0.9930614869087001, 'min_gain_to_split': 0.018600102217451207}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 13:12:20,842] Trial 245 finished with value: 0.08590304778324255 and parameters: {'num_leaves': 77, 'learning_rate': 0.2518098855548502, 'feature_fraction': 0.9452395995875479, 'bagging_fraction': 0.9739109637786361, 'bagging_freq': 4, 'lambda_l1': 1.2633767461620958e-05, 'lambda_l2': 1.1770854797805494e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 464, 'min_data_in_leaf': 35, 'extra_trees': False, 'early_stopping_rounds': 34, 'path_smooth': 0.9485302171553832, 'min_gain_to_split': 0.02752705182800761}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 13:24:41,123] Trial 246 finished with value: 0.17442699234238904 and parameters: {'num_leaves': 78, 'learning_rate': 0.2512127715291465, 'feature_fraction': 0.945416310090709, 'bagging_fraction': 0.8944345771896166, 'bagging_freq': 4, 'lambda_l1': 1.0996650984082735e-05, 'lambda_l2': 1.152605439726042e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 455, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 36, 'path_smooth': 0.9569787732310704, 'min_gain_to_split': 0.009636712986741717}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 13:30:20,192] Trial 247 finished with value: 0.3763051899492432 and parameters: {'num_leaves': 77, 'learning_rate': 0.29835585470522924, 'feature_fraction': 0.9247840044715238, 'bagging_fraction': 0.9680173226855029, 'bagging_freq': 4, 'lambda_l1': 1.165519292494498e-05, 'lambda_l2': 6.885000688916624e-07, 'min_child_samples': 35, 'max_depth': 8, 'max_bin': 178, 'min_data_in_leaf': 91, 'extra_trees': False, 'early_stopping_rounds': 34, 'path_smooth': 0.8952453199742263, 'min_gain_to_split': 0.025916856901333468}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 13:43:38,950] Trial 248 finished with value: 0.11228033960892495 and parameters: {'num_leaves': 80, 'learning_rate': 0.2418165990996675, 'feature_fraction': 0.9332951643629341, 'bagging_fraction': 0.9756940871964374, 'bagging_freq': 4, 'lambda_l1': 0.0007919914487593451, 'lambda_l2': 1.499557182789827e-06, 'min_child_samples': 35, 'max_depth': 8, 'max_bin': 462, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 28, 'path_smooth': 0.9201655494848744, 'min_gain_to_split': 0.016467237428026922}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 13:49:29,030] Trial 249 finished with value: 0.26724607107473 and parameters: {'num_leaves': 76, 'learning_rate': 0.26165787504225285, 'feature_fraction': 0.948762674149423, 'bagging_fraction': 0.9545522223607651, 'bagging_freq': 4, 'lambda_l1': 0.0004210110298602455, 'lambda_l2': 2.7125772532606782e-06, 'min_child_samples': 38, 'max_depth': 8, 'max_bin': 477, 'min_data_in_leaf': 35, 'extra_trees': False, 'early_stopping_rounds': 35, 'path_smooth': 0.9288004658986992, 'min_gain_to_split': 0.42354815999784245}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 13:59:01,311] Trial 250 finished with value: 0.0914635325927859 and parameters: {'num_leaves': 93, 'learning_rate': 0.28179330668456504, 'feature_fraction': 0.9549034520908897, 'bagging_fraction': 0.9717944912592206, 'bagging_freq': 3, 'lambda_l1': 0.00013723561892061244, 'lambda_l2': 1.2372305101747422e-06, 'min_child_samples': 34, 'max_depth': 8, 'max_bin': 492, 'min_data_in_leaf': 36, 'extra_trees': False, 'early_stopping_rounds': 32, 'path_smooth': 0.9907872776134159, 'min_gain_to_split': 0.03938120061576056}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 14:13:13,758] Trial 251 finished with value: 0.08735868170115171 and parameters: {'num_leaves': 87, 'learning_rate': 0.22375258752887636, 'feature_fraction': 0.9399736240255991, 'bagging_fraction': 0.9795537117157262, 'bagging_freq': 4, 'lambda_l1': 4.5518956892870395e-06, 'lambda_l2': 5.168729598623489e-07, 'min_child_samples': 33, 'max_depth': 8, 'max_bin': 483, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 34, 'path_smooth': 0.9485385618939421, 'min_gain_to_split': 0.007987399134902658}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 14:18:31,050] Trial 252 finished with value: 0.278362474131494 and parameters: {'num_leaves': 83, 'learning_rate': 0.2623330324027881, 'feature_fraction': 0.922096455820139, 'bagging_fraction': 0.9613487118242173, 'bagging_freq': 4, 'lambda_l1': 9.294689986224137e-07, 'lambda_l2': 2.60532746844557e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 494, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 33, 'path_smooth': 0.9400310493596891, 'min_gain_to_split': 0.38868360524261114}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 14:31:59,655] Trial 253 finished with value: 0.11363003147672246 and parameters: {'num_leaves': 79, 'learning_rate': 0.24117309886931462, 'feature_fraction': 0.8854290775630149, 'bagging_fraction': 0.9687482057751102, 'bagging_freq': 4, 'lambda_l1': 7.095229461718718e-06, 'lambda_l2': 4.039508372358221e-06, 'min_child_samples': 37, 'max_depth': 8, 'max_bin': 474, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 35, 'path_smooth': 0.9961269389678309, 'min_gain_to_split': 0.00039345724392830426}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 14:42:33,666] Trial 254 finished with value: 0.16868577680039631 and parameters: {'num_leaves': 75, 'learning_rate': 0.28121156416170434, 'feature_fraction': 0.9320637135527892, 'bagging_fraction': 0.9843112137738593, 'bagging_freq': 9, 'lambda_l1': 1.6754264468467097e-06, 'lambda_l2': 1.965920464398776e-06, 'min_child_samples': 35, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.8919438488967084, 'min_gain_to_split': 0.027269082681294222}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 14:46:56,161] Trial 255 finished with value: 0.30503989378647195 and parameters: {'num_leaves': 88, 'learning_rate': 0.2994817491130499, 'feature_fraction': 0.9157023915980216, 'bagging_fraction': 0.9763030409974911, 'bagging_freq': 4, 'lambda_l1': 1.4038615219582006e-05, 'lambda_l2': 1.0112747939008169e-06, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 35, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.9137170604641053, 'min_gain_to_split': 0.48110073954882926}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 14:56:48,255] Trial 256 finished with value: 0.1486668339796046 and parameters: {'num_leaves': 81, 'learning_rate': 0.25558919334537245, 'feature_fraction': 0.8636956564084344, 'bagging_fraction': 0.9886969894782965, 'bagging_freq': 4, 'lambda_l1': 2.5651656249693376e-06, 'lambda_l2': 3.054454020062345e-06, 'min_child_samples': 34, 'max_depth': 8, 'max_bin': 466, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 37, 'path_smooth': 0.9525065208535822, 'min_gain_to_split': 0.017202697742533496}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 15:04:15,779] Trial 257 finished with value: 0.8020000414462528 and parameters: {'num_leaves': 85, 'learning_rate': 0.2239290213771144, 'feature_fraction': 0.9431843535511155, 'bagging_fraction': 0.8398133916117818, 'bagging_freq': 3, 'lambda_l1': 5.027425717685223, 'lambda_l2': 5.2199412018751795e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 491, 'min_data_in_leaf': 36, 'extra_trees': False, 'early_stopping_rounds': 36, 'path_smooth': 0.9663361096166332, 'min_gain_to_split': 0.034904859085099924}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 15:10:34,464] Trial 258 finished with value: 0.32842494316326715 and parameters: {'num_leaves': 78, 'learning_rate': 0.27161067682371226, 'feature_fraction': 0.9533339698998612, 'bagging_fraction': 0.9654203674217782, 'bagging_freq': 4, 'lambda_l1': 5.048341992378421e-06, 'lambda_l2': 1.734863632395158e-06, 'min_child_samples': 33, 'max_depth': 5, 'max_bin': 478, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 30, 'path_smooth': 0.878857156023227, 'min_gain_to_split': 0.008908220349249497}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 15:22:12,285] Trial 259 finished with value: 0.14627599881410153 and parameters: {'num_leaves': 76, 'learning_rate': 0.24029727302958043, 'feature_fraction': 0.9275469330649474, 'bagging_fraction': 0.9801635632691769, 'bagging_freq': 4, 'lambda_l1': 0.0013169671072014396, 'lambda_l2': 3.2489796613456775e-06, 'min_child_samples': 12, 'max_depth': 8, 'max_bin': 485, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 33, 'path_smooth': 0.9309616004545325, 'min_gain_to_split': 0.02135710405076277}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 15:31:38,811] Trial 260 finished with value: 0.33384810630950934 and parameters: {'num_leaves': 90, 'learning_rate': 0.25574740584842776, 'feature_fraction': 0.8478582955768907, 'bagging_fraction': 0.9733395165989066, 'bagging_freq': 2, 'lambda_l1': 0.0005420776340225731, 'lambda_l2': 5.890655256566982e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 492, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.9053291240020347, 'min_gain_to_split': 0.015080191679130628}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 15:47:24,357] Trial 261 finished with value: 0.3839396796897317 and parameters: {'num_leaves': 80, 'learning_rate': 0.0983679353288492, 'feature_fraction': 0.9379549489805842, 'bagging_fraction': 0.9879590039261471, 'bagging_freq': 4, 'lambda_l1': 8.085891443873046e-07, 'lambda_l2': 7.844030694722806e-07, 'min_child_samples': 33, 'max_depth': 7, 'max_bin': 500, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 34, 'path_smooth': 0.854949062381877, 'min_gain_to_split': 0.0002358023399156042}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 16:10:13,309] Trial 262 finished with value: 0.6804226400599447 and parameters: {'num_leaves': 83, 'learning_rate': 0.04278000434804848, 'feature_fraction': 0.9011719106547869, 'bagging_fraction': 0.982275993700515, 'bagging_freq': 4, 'lambda_l1': 9.006900958227753e-06, 'lambda_l2': 1.2943713667996723e-06, 'min_child_samples': 35, 'max_depth': 8, 'max_bin': 468, 'min_data_in_leaf': 30, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.9598014785122171, 'min_gain_to_split': 0.0285295379605096}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 16:15:24,616] Trial 263 finished with value: 0.2882890313306481 and parameters: {'num_leaves': 78, 'learning_rate': 0.21276399464246804, 'feature_fraction': 0.9471429250412207, 'bagging_fraction': 0.9935654236687221, 'bagging_freq': 4, 'lambda_l1': 2.828344480100292e-05, 'lambda_l2': 2.4193829360194386e-06, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 477, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 23, 'path_smooth': 0.6384512445966593, 'min_gain_to_split': 0.010397240276159101}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 16:24:43,301] Trial 264 finished with value: 0.2284933323703584 and parameters: {'num_leaves': 92, 'learning_rate': 0.27405346907590006, 'feature_fraction': 0.9605813979499277, 'bagging_fraction': 0.9760765872871804, 'bagging_freq': 4, 'lambda_l1': 3.5104693472087246e-06, 'lambda_l2': 9.895692575718408e-06, 'min_child_samples': 34, 'max_depth': 8, 'max_bin': 484, 'min_data_in_leaf': 35, 'extra_trees': False, 'early_stopping_rounds': 39, 'path_smooth': 0.694539225048468, 'min_gain_to_split': 0.039090485931271665}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 16:35:50,022] Trial 265 finished with value: 0.11301385983527559 and parameters: {'num_leaves': 74, 'learning_rate': 0.23244225298344506, 'feature_fraction': 0.9325318045288797, 'bagging_fraction': 0.9682103743381966, 'bagging_freq': 4, 'lambda_l1': 1.7127742833561978e-06, 'lambda_l2': 4.281427164398765e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 492, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 31, 'path_smooth': 0.9768658708884409, 'min_gain_to_split': 0.01994684219049659}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 16:46:29,419] Trial 266 finished with value: 0.3934339707811759 and parameters: {'num_leaves': 98, 'learning_rate': 0.20179127740476602, 'feature_fraction': 0.9561893146922802, 'bagging_fraction': 0.9530334833297086, 'bagging_freq': 3, 'lambda_l1': 5.734626250441325e-06, 'lambda_l2': 1.838711832157262e-06, 'min_child_samples': 33, 'max_depth': 8, 'max_bin': 458, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 35, 'path_smooth': 0.9371285144397352, 'min_gain_to_split': 0.04845752384294541}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 16:53:06,306] Trial 267 finished with value: 0.30067990975189834 and parameters: {'num_leaves': 82, 'learning_rate': 0.28164036147931604, 'feature_fraction': 0.919333791816068, 'bagging_fraction': 0.961065155635237, 'bagging_freq': 4, 'lambda_l1': 0.00010463078616178994, 'lambda_l2': 6.802301452427394e-06, 'min_child_samples': 32, 'max_depth': 7, 'max_bin': 254, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.8795400668977845, 'min_gain_to_split': 0.009143753906968654}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 17:03:11,002] Trial 268 finished with value: 0.17308799062142916 and parameters: {'num_leaves': 76, 'learning_rate': 0.2513834269356328, 'feature_fraction': 0.942621823898433, 'bagging_fraction': 0.9848662171576154, 'bagging_freq': 7, 'lambda_l1': 2.3117037644930955e-06, 'lambda_l2': 3.2163821992894597e-06, 'min_child_samples': 35, 'max_depth': 8, 'max_bin': 478, 'min_data_in_leaf': 36, 'extra_trees': False, 'early_stopping_rounds': 29, 'path_smooth': 0.04385658022246236, 'min_gain_to_split': 0.025188965016020096}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 17:12:40,656] Trial 269 finished with value: 0.1895450104807824 and parameters: {'num_leaves': 89, 'learning_rate': 0.2988389586933055, 'feature_fraction': 0.9092682500771365, 'bagging_fraction': 0.9913745770987431, 'bagging_freq': 4, 'lambda_l1': 1.1734372329767118e-06, 'lambda_l2': 2.2034449712713695e-07, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 493, 'min_data_in_leaf': 40, 'extra_trees': False, 'early_stopping_rounds': 32, 'path_smooth': 0.0353994603053543, 'min_gain_to_split': 0.015643580851315838}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 17:23:45,748] Trial 270 finished with value: 0.11476139655209869 and parameters: {'num_leaves': 79, 'learning_rate': 0.22709859589221354, 'feature_fraction': 0.9493935677147799, 'bagging_fraction': 0.9736136905470768, 'bagging_freq': 4, 'lambda_l1': 0.0002644194917147792, 'lambda_l2': 1.3381175703802693e-05, 'min_child_samples': 33, 'max_depth': 8, 'max_bin': 470, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.06697938325811253, 'min_gain_to_split': 0.03254732081365701}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 17:33:54,545] Trial 271 finished with value: 0.09311562515101364 and parameters: {'num_leaves': 85, 'learning_rate': 0.26626854126404054, 'feature_fraction': 0.9260291679972139, 'bagging_fraction': 0.9091718342858365, 'bagging_freq': 4, 'lambda_l1': 1.5508999290937637e-05, 'lambda_l2': 4.6570515257363665e-06, 'min_child_samples': 34, 'max_depth': 8, 'max_bin': 485, 'min_data_in_leaf': 35, 'extra_trees': False, 'early_stopping_rounds': 34, 'path_smooth': 0.915373289431881, 'min_gain_to_split': 0.001241681739423222}. Best is trial 194 with value: 0.04515360263262301.

Mejor trial hasta ahora: RMSE=0.045154, Parámetros={'num_leaves': 79, 'learning_rate': 0.18787373335880653, 'feature_fraction': 0.9219550706082272, 'bagging_fraction': 0.9996932596274555, 'bagging_freq': 4, 'lambda_l1': 1.048653344976581e-05, 'lambda_l2': 1.6741748540140548e-05, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.045109016293702904, 'min_gain_to_split': 0.008706700452920976}

[I 2025-07-10 17:45:39,745] Trial 272 finished with value: 0.04277612373730953 and parameters: {'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-10 17:58:11,828] Trial 273 finished with value: 0.062110805810548966 and parameters: {'num_leaves': 77, 'learning_rate': 0.2429712248063157, 'feature_fraction': 0.93926336890687, 'bagging_fraction': 0.9954957467267568, 'bagging_freq': 4, 'lambda_l1': 3.2421603290855483e-06, 'lambda_l2': 4.904199020440902e-07, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 485, 'min_data_in_leaf': 31, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9952891954487378, 'min_gain_to_split': 0.00015062142373245026}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-10 18:12:37,794] Trial 274 finished with value: 0.06629213165040534 and parameters: {'num_leaves': 75, 'learning_rate': 0.21056942785443675, 'feature_fraction': 0.937933973300952, 'bagging_fraction': 0.994373826817534, 'bagging_freq': 4, 'lambda_l1': 3.5635223016896726e-06, 'lambda_l2': 7.734523081172434e-07, 'min_child_samples': 30, 'max_depth': 8, 'max_bin': 474, 'min_data_in_leaf': 31, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9610093745810094, 'min_gain_to_split': 0.0008969253900956622}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-10 18:28:00,980] Trial 275 finished with value: 0.1922438382660729 and parameters: {'num_leaves': 72, 'learning_rate': 0.199228182547843, 'feature_fraction': 0.9350320862563644, 'bagging_fraction': 0.9965564610199195, 'bagging_freq': 4, 'lambda_l1': 3.889678856621928e-06, 'lambda_l2': 5.032839213266555e-07, 'min_child_samples': 30, 'max_depth': 8, 'max_bin': 474, 'min_data_in_leaf': 30, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.9776824260336422, 'min_gain_to_split': 0.0007481976540325164}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-10 18:40:53,980] Trial 276 finished with value: 0.16838551771735394 and parameters: {'num_leaves': 75, 'learning_rate': 0.2093281852162814, 'feature_fraction': 0.9380539126924625, 'bagging_fraction': 0.9939597144763974, 'bagging_freq': 4, 'lambda_l1': 2.9610593404214614e-06, 'lambda_l2': 5.898803729108584e-07, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 482, 'min_data_in_leaf': 31, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9963450552546186, 'min_gain_to_split': 0.0008837670686096027}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-10 18:53:26,772] Trial 277 finished with value: 0.3176847900462837 and parameters: {'num_leaves': 73, 'learning_rate': 0.21733739491275567, 'feature_fraction': 0.9307112050454143, 'bagging_fraction': 0.9895992953975458, 'bagging_freq': 4, 'lambda_l1': 0.5813136312948332, 'lambda_l2': 2.8753556591615555e-07, 'min_child_samples': 30, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.968009724454948, 'min_gain_to_split': 0.01303544598625858}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-10 19:34:59,440] Trial 278 finished with value: 0.7796167394664553 and parameters: {'num_leaves': 80, 'learning_rate': 0.018959966845736004, 'feature_fraction': 0.939235971354888, 'bagging_fraction': 0.9993362389412209, 'bagging_freq': 4, 'lambda_l1': 4.085914090832416e-06, 'lambda_l2': 4.1552609330901713e-07, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 478, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.9970783782000077, 'min_gain_to_split': 0.01123240391234859}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-10 19:47:50,718] Trial 279 finished with value: 0.2353938882331334 and parameters: {'num_leaves': 74, 'learning_rate': 0.2315879966146483, 'feature_fraction': 0.8303380872019812, 'bagging_fraction': 0.9880934816967594, 'bagging_freq': 4, 'lambda_l1': 2.2270931388506995e-06, 'lambda_l2': 3.0406265952944673e-07, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 31, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.9599659428225588, 'min_gain_to_split': 0.00874891831319334}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-10 19:57:37,900] Trial 280 finished with value: 0.1805242108344011 and parameters: {'num_leaves': 81, 'learning_rate': 0.2801739972783551, 'feature_fraction': 0.979401871798166, 'bagging_fraction': 0.9942527466424339, 'bagging_freq': 4, 'lambda_l1': 6.004118466777904e-06, 'lambda_l2': 8.543294631495031e-07, 'min_child_samples': 32, 'max_depth': 7, 'max_bin': 488, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.8353647220332902, 'min_gain_to_split': 0.02124143999888498}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-10 20:19:44,878] Trial 281 finished with value: 0.7342544925069834 and parameters: {'num_leaves': 78, 'learning_rate': 0.05149606150413855, 'feature_fraction': 0.9473901461806343, 'bagging_fraction': 0.9862615638051038, 'bagging_freq': 4, 'lambda_l1': 2.9974858373130654e-06, 'lambda_l2': 6.58589810355044e-07, 'min_child_samples': 30, 'max_depth': 8, 'max_bin': 471, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.931759932233712, 'min_gain_to_split': 0.018889829405965154}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-10 20:27:42,341] Trial 282 finished with value: 0.2685225370257963 and parameters: {'num_leaves': 75, 'learning_rate': 0.22306594103164223, 'feature_fraction': 0.8804929623231785, 'bagging_fraction': 0.9822423556143318, 'bagging_freq': 5, 'lambda_l1': 0.0033113668839037614, 'lambda_l2': 7.960583969375936e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 490, 'min_data_in_leaf': 31, 'extra_trees': True, 'early_stopping_rounds': 22, 'path_smooth': 0.8927424785527733, 'min_gain_to_split': 3.093397140944314e-05}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-10 20:42:16,526] Trial 283 finished with value: 0.25036195537425754 and parameters: {'num_leaves': 70, 'learning_rate': 0.19292525611280983, 'feature_fraction': 0.9275755082382965, 'bagging_fraction': 0.873702755274017, 'bagging_freq': 4, 'lambda_l1': 6.177685865843508e-07, 'lambda_l2': 1.3354458811211917e-07, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 479, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.07705013773972304, 'min_gain_to_split': 0.007552840950589351}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-10 20:53:48,993] Trial 284 finished with value: 0.19068094771749783 and parameters: {'num_leaves': 79, 'learning_rate': 0.2386260872386755, 'feature_fraction': 0.9173544252984154, 'bagging_fraction': 0.9951001040439518, 'bagging_freq': 4, 'lambda_l1': 1.5203382081534256e-06, 'lambda_l2': 1.0697497946837215e-06, 'min_child_samples': 34, 'max_depth': 8, 'max_bin': 492, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.863209803664339, 'min_gain_to_split': 0.04069284942344194}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-10 21:05:51,283] Trial 285 finished with value: 0.11794636449331405 and parameters: {'num_leaves': 83, 'learning_rate': 0.2725421764309877, 'feature_fraction': 0.965627669837582, 'bagging_fraction': 0.9896984048957528, 'bagging_freq': 4, 'lambda_l1': 4.241474856905173e-06, 'lambda_l2': 3.8561145558754905e-06, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 482, 'min_data_in_leaf': 36, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.05378766733468682, 'min_gain_to_split': 0.02880909704916014}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-10 21:18:33,412] Trial 286 finished with value: 0.13826747536647427 and parameters: {'num_leaves': 76, 'learning_rate': 0.23992203000080628, 'feature_fraction': 0.9392086882298457, 'bagging_fraction': 0.9820445990135388, 'bagging_freq': 4, 'lambda_l1': 2.435530232601847e-06, 'lambda_l2': 1.4813777782133833e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 452, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.09563291365341628, 'min_gain_to_split': 0.016370529892237227}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-10 21:26:37,799] Trial 287 finished with value: 0.07973532306815119 and parameters: {'num_leaves': 81, 'learning_rate': 0.2133706711546061, 'feature_fraction': 0.9315734929013929, 'bagging_fraction': 0.999140672986787, 'bagging_freq': 4, 'lambda_l1': 1.3677011308605545e-06, 'lambda_l2': 0.0327766897598032, 'min_child_samples': 34, 'max_depth': 8, 'max_bin': 203, 'min_data_in_leaf': 40, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.9459294215427884, 'min_gain_to_split': 0.000977289862350789}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-10 21:43:36,845] Trial 288 finished with value: 0.1279137991363698 and parameters: {'num_leaves': 83, 'learning_rate': 0.20641725932557078, 'feature_fraction': 0.9338055812688123, 'bagging_fraction': 0.9994467926447278, 'bagging_freq': 4, 'lambda_l1': 0.09347569380072178, 'lambda_l2': 0.24688333458300732, 'min_child_samples': 30, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 65, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.9641215278921169, 'min_gain_to_split': 0.009528121700900474}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-10 21:54:51,055] Trial 289 finished with value: 0.08778917517410338 and parameters: {'num_leaves': 80, 'learning_rate': 0.2049943358517168, 'feature_fraction': 0.9256539179409247, 'bagging_fraction': 0.9942085135026707, 'bagging_freq': 4, 'lambda_l1': 3.7619482988898774e-07, 'lambda_l2': 1.4890232960907709e-06, 'min_child_samples': 34, 'max_depth': 10, 'max_bin': 277, 'min_data_in_leaf': 40, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9993325748531909, 'min_gain_to_split': 0.026177210166121807}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-10 22:05:18,310] Trial 290 finished with value: 0.8322914761264306 and parameters: {'num_leaves': 81, 'learning_rate': 0.037942751483375635, 'feature_fraction': 0.9125001658179852, 'bagging_fraction': 0.9910372517302799, 'bagging_freq': 5, 'lambda_l1': 1.0495427606060097e-06, 'lambda_l2': 0.0001950692289770045, 'min_child_samples': 33, 'max_depth': 8, 'max_bin': 130, 'min_data_in_leaf': 31, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.9502335139569161, 'min_gain_to_split': 0.01748759312553999}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-10 22:09:35,101] Trial 291 finished with value: 0.8574385035965616 and parameters: {'num_leaves': 86, 'learning_rate': 0.21825180787922271, 'feature_fraction': 0.8961736209446053, 'bagging_fraction': 0.9995621473735864, 'bagging_freq': 4, 'lambda_l1': 1.6482936119994938e-06, 'lambda_l2': 2.326426814010812e-06, 'min_child_samples': 32, 'max_depth': 4, 'max_bin': 307, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 21, 'path_smooth': 0.9733979003296214, 'min_gain_to_split': 0.000197079625992606}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-10 22:21:32,331] Trial 292 finished with value: 0.2623455124181481 and parameters: {'num_leaves': 82, 'learning_rate': 0.2250709100076647, 'feature_fraction': 0.9422336469693104, 'bagging_fraction': 0.9849802323625665, 'bagging_freq': 4, 'lambda_l1': 6.668249220322288e-06, 'lambda_l2': 2.602329425413939, 'min_child_samples': 29, 'max_depth': 8, 'max_bin': 494, 'min_data_in_leaf': 39, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.9429299092149269, 'min_gain_to_split': 0.036824259735444294}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-10 22:29:54,852] Trial 293 finished with value: 0.22954701118425044 and parameters: {'num_leaves': 84, 'learning_rate': 0.18224424136672784, 'feature_fraction': 0.931316905799462, 'bagging_fraction': 0.9907393853725269, 'bagging_freq': 7, 'lambda_l1': 9.8131272979441e-07, 'lambda_l2': 1.3072062191200422, 'min_child_samples': 33, 'max_depth': 8, 'max_bin': 198, 'min_data_in_leaf': 36, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.03594265383359507, 'min_gain_to_split': 0.012468734526448212}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-10 22:33:38,285] Trial 294 finished with value: 0.30634860956021853 and parameters: {'num_leaves': 78, 'learning_rate': 0.2413882723031947, 'feature_fraction': 0.9212205782390167, 'bagging_fraction': 0.9948784014485458, 'bagging_freq': 8, 'lambda_l1': 2.192391475578499e-06, 'lambda_l2': 8.118774437828343e-07, 'min_child_samples': 34, 'max_depth': 8, 'max_bin': 224, 'min_data_in_leaf': 42, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.9155789876633423, 'min_gain_to_split': 0.3595330183461603}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-10 22:39:29,530] Trial 295 finished with value: 0.36123103875530066 and parameters: {'num_leaves': 79, 'learning_rate': 0.19122222830161817, 'feature_fraction': 0.9512706296813047, 'bagging_fraction': 0.9802104679986903, 'bagging_freq': 4, 'lambda_l1': 7.230062916211323e-07, 'lambda_l2': 5.433125231399724e-06, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 148, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.11226790419888635, 'min_gain_to_split': 0.0239352681167047}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-10 22:49:03,287] Trial 296 finished with value: 0.12309660698309832 and parameters: {'num_leaves': 95, 'learning_rate': 0.2574686352918909, 'feature_fraction': 0.9356745758552748, 'bagging_fraction': 0.9864669950778839, 'bagging_freq': 4, 'lambda_l1': 1.2895601764359415e-06, 'lambda_l2': 0.020840355737278323, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 485, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.15112770887277957, 'min_gain_to_split': 0.045371909765924666}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-10 23:01:38,519] Trial 297 finished with value: 0.19141137863270843 and parameters: {'num_leaves': 81, 'learning_rate': 0.21609440045769499, 'feature_fraction': 0.9447793195691431, 'bagging_fraction': 0.995184728813105, 'bagging_freq': 4, 'lambda_l1': 4.16980166399006e-06, 'lambda_l2': 0.009700347145879753, 'min_child_samples': 33, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 30, 'extra_trees': False, 'early_stopping_rounds': 21, 'path_smooth': 0.38154656709753504, 'min_gain_to_split': 0.008865474085892174}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-10 23:12:09,924] Trial 298 finished with value: 0.05598683471328767 and parameters: {'num_leaves': 77, 'learning_rate': 0.2346540789435931, 'feature_fraction': 0.9265708351926755, 'bagging_fraction': 0.9789540411579628, 'bagging_freq': 5, 'lambda_l1': 7.808878139993864e-06, 'lambda_l2': 3.280240737173472e-06, 'min_child_samples': 34, 'max_depth': 8, 'max_bin': 492, 'min_data_in_leaf': 40, 'extra_trees': False, 'early_stopping_rounds': 20, 'path_smooth': 0.9316465922303917, 'min_gain_to_split': 0.033151857465981746}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-10 23:22:24,387] Trial 299 finished with value: 0.0990644597992403 and parameters: {'num_leaves': 76, 'learning_rate': 0.23761543569666913, 'feature_fraction': 0.9159728578558012, 'bagging_fraction': 0.9790626260564921, 'bagging_freq': 5, 'lambda_l1': 8.245100223958584e-06, 'lambda_l2': 3.3173594925976595e-06, 'min_child_samples': 32, 'max_depth': 10, 'max_bin': 491, 'min_data_in_leaf': 35, 'extra_trees': False, 'early_stopping_rounds': 20, 'path_smooth': 0.05687288737228002, 'min_gain_to_split': 0.054483482823717844}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-10 23:31:54,229] Trial 300 finished with value: 0.10486313561281779 and parameters: {'num_leaves': 77, 'learning_rate': 0.2630921255612448, 'feature_fraction': 0.8118660352583017, 'bagging_fraction': 0.9786085279766445, 'bagging_freq': 5, 'lambda_l1': 5.8637576763070815e-06, 'lambda_l2': 1.5650771216506456e-06, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 475, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 20, 'path_smooth': 0.6703720465739849, 'min_gain_to_split': 0.03503147561071406}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-10 23:37:53,152] Trial 301 finished with value: 0.582722527003418 and parameters: {'num_leaves': 17, 'learning_rate': 0.24858008895823744, 'feature_fraction': 0.9060550530677288, 'bagging_fraction': 0.9864808791446137, 'bagging_freq': 5, 'lambda_l1': 8.278100402889027e-06, 'lambda_l2': 2.971195409780564e-06, 'min_child_samples': 37, 'max_depth': 7, 'max_bin': 485, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 31, 'path_smooth': 0.00013411337937151852, 'min_gain_to_split': 0.20172520533161398}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-10 23:41:12,434] Trial 302 finished with value: 0.8414415606446412 and parameters: {'num_leaves': 72, 'learning_rate': 0.27619484503187275, 'feature_fraction': 0.7564027410690595, 'bagging_fraction': 0.9844251126376378, 'bagging_freq': 4, 'lambda_l1': 5.211215362711508e-06, 'lambda_l2': 4.666418412136491e-06, 'min_child_samples': 35, 'max_depth': 3, 'max_bin': 494, 'min_data_in_leaf': 39, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.032292258201240244, 'min_gain_to_split': 0.031036141560043157}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-10 23:45:31,309] Trial 303 finished with value: 0.47925090000568565 and parameters: {'num_leaves': 78, 'learning_rate': 0.25960067916615714, 'feature_fraction': 0.9239622387286999, 'bagging_fraction': 0.9778924332293726, 'bagging_freq': 4, 'lambda_l1': 5.585105230058688e-05, 'lambda_l2': 1.9627147516962015e-06, 'min_child_samples': 33, 'max_depth': 8, 'max_bin': 480, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 33, 'path_smooth': 0.9255020816529541, 'min_gain_to_split': 0.021765123918893327}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-10 23:55:50,096] Trial 304 finished with value: 0.22700636781673506 and parameters: {'num_leaves': 77, 'learning_rate': 0.229559095533217, 'feature_fraction': 0.9561087073773649, 'bagging_fraction': 0.9893517603868937, 'bagging_freq': 3, 'lambda_l1': 2.6838512701852833e-06, 'lambda_l2': 1.0296683567424007e-06, 'min_child_samples': 30, 'max_depth': 8, 'max_bin': 493, 'min_data_in_leaf': 36, 'extra_trees': False, 'early_stopping_rounds': 20, 'path_smooth': 0.07328252660845556, 'min_gain_to_split': 0.04776652736573941}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 00:05:12,564] Trial 305 finished with value: 0.11458827614730493 and parameters: {'num_leaves': 74, 'learning_rate': 0.2809634235282161, 'feature_fraction': 0.7882659303083898, 'bagging_fraction': 0.9824263027694836, 'bagging_freq': 4, 'lambda_l1': 0.0003577243476404857, 'lambda_l2': 2.713461801397146e-06, 'min_child_samples': 34, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 41, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5915944695389541, 'min_gain_to_split': 0.01997829035846454}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 00:16:02,206] Trial 306 finished with value: 0.15394041412177653 and parameters: {'num_leaves': 79, 'learning_rate': 0.24224559880590005, 'feature_fraction': 0.942938021535733, 'bagging_fraction': 0.9893985452061376, 'bagging_freq': 4, 'lambda_l1': 4.453506780455385e-06, 'lambda_l2': 5.347716153213831e-07, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 44, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.7465189649594834, 'min_gain_to_split': 0.03156116962287584}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 00:26:30,354] Trial 307 finished with value: 0.0545439722593226 and parameters: {'num_leaves': 84, 'learning_rate': 0.2619769355812929, 'feature_fraction': 0.928498605598008, 'bagging_fraction': 0.9773695827257955, 'bagging_freq': 4, 'lambda_l1': 7.965048149467168e-06, 'lambda_l2': 5.489479090670694e-06, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 472, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.04601776628970331, 'min_gain_to_split': 0.017366988254787663}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 00:40:32,977] Trial 308 finished with value: 0.15328074500902406 and parameters: {'num_leaves': 74, 'learning_rate': 0.22805167447607916, 'feature_fraction': 0.9280462904322183, 'bagging_fraction': 0.9786064329357397, 'bagging_freq': 4, 'lambda_l1': 3.5772299457269646e-05, 'lambda_l2': 7.424835982287043e-06, 'min_child_samples': 30, 'max_depth': 10, 'max_bin': 487, 'min_data_in_leaf': 30, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.0478989260437516, 'min_gain_to_split': 0.011638485535172093}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 00:50:57,211] Trial 309 finished with value: 0.26490825914562566 and parameters: {'num_leaves': 80, 'learning_rate': 0.25678582265547667, 'feature_fraction': 0.919468456046112, 'bagging_fraction': 0.986526883274414, 'bagging_freq': 4, 'lambda_l1': 9.536752035353233e-06, 'lambda_l2': 1.2341326690469178e-06, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 475, 'min_data_in_leaf': 26, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.09777801028942833, 'min_gain_to_split': 0.04220623766333451}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 01:03:19,183] Trial 310 finished with value: 0.18358150989817712 and parameters: {'num_leaves': 76, 'learning_rate': 0.20105751597993127, 'feature_fraction': 0.9364955634771033, 'bagging_fraction': 0.9746750194413689, 'bagging_freq': 5, 'lambda_l1': 1.8605934561393224e-05, 'lambda_l2': 1.9540921049897815e-06, 'min_child_samples': 30, 'max_depth': 8, 'max_bin': 493, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.02417757618976075, 'min_gain_to_split': 0.026019811306293057}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 01:15:43,853] Trial 311 finished with value: 0.1222771521379298 and parameters: {'num_leaves': 86, 'learning_rate': 0.24284173519135663, 'feature_fraction': 0.9275373810010898, 'bagging_fraction': 0.9927830134997212, 'bagging_freq': 9, 'lambda_l1': 6.97836288595192e-06, 'lambda_l2': 3.857093970785491e-06, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 480, 'min_data_in_leaf': 57, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.06488111122782549, 'min_gain_to_split': 0.008547366769698557}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 01:34:11,381] Trial 312 finished with value: 0.4492153936448922 and parameters: {'num_leaves': 78, 'learning_rate': 0.11285065721359551, 'feature_fraction': 0.9043505707138146, 'bagging_fraction': 0.9810494865937458, 'bagging_freq': 4, 'lambda_l1': 0.20059694593668492, 'lambda_l2': 2.771788231602045e-06, 'min_child_samples': 33, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.04624564893299241, 'min_gain_to_split': 0.014899746329576824}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 01:43:45,673] Trial 313 finished with value: 0.26708062151703116 and parameters: {'num_leaves': 62, 'learning_rate': 0.26585539457951235, 'feature_fraction': 0.9366578870790473, 'bagging_fraction': 0.9848456292325479, 'bagging_freq': 3, 'lambda_l1': 1.1974409003589946e-05, 'lambda_l2': 3.9067082586773535e-07, 'min_child_samples': 31, 'max_depth': 7, 'max_bin': 464, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 21, 'path_smooth': 0.9798457247441656, 'min_gain_to_split': 0.03301705463990645}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 01:52:59,881] Trial 314 finished with value: 0.2595572273071326 and parameters: {'num_leaves': 71, 'learning_rate': 0.22683667205733377, 'feature_fraction': 0.9914024758014087, 'bagging_fraction': 0.9741579560807369, 'bagging_freq': 4, 'lambda_l1': 8.906820153500764e-05, 'lambda_l2': 6.068282606102975e-06, 'min_child_samples': 32, 'max_depth': 6, 'max_bin': 487, 'min_data_in_leaf': 31, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.030081032578246392, 'min_gain_to_split': 0.00014549570992158348}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 02:05:45,644] Trial 315 finished with value: 0.133427376957903 and parameters: {'num_leaves': 82, 'learning_rate': 0.2140711978489799, 'feature_fraction': 0.9140603495556235, 'bagging_fraction': 0.9928278960093257, 'bagging_freq': 4, 'lambda_l1': 2.8655699488263183e-06, 'lambda_l2': 1.4573832767731945e-06, 'min_child_samples': 29, 'max_depth': 8, 'max_bin': 473, 'min_data_in_leaf': 35, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.014774221990076067, 'min_gain_to_split': 0.022078909541749334}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 02:17:51,750] Trial 316 finished with value: 0.13380970751130544 and parameters: {'num_leaves': 76, 'learning_rate': 0.24812707961213487, 'feature_fraction': 0.888224369729972, 'bagging_fraction': 0.9995790356780097, 'bagging_freq': 4, 'lambda_l1': 1.9523250408779926e-06, 'lambda_l2': 3.862384330143016e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 493, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 21, 'path_smooth': 0.07452172153061998, 'min_gain_to_split': 0.011301255237640192}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 02:42:54,680] Trial 317 finished with value: 0.5251436492678867 and parameters: {'num_leaves': 91, 'learning_rate': 0.06039895285350392, 'feature_fraction': 0.946138048078152, 'bagging_fraction': 0.983035010035485, 'bagging_freq': 4, 'lambda_l1': 0.0001815211985806035, 'lambda_l2': 1.1380636988320028e-05, 'min_child_samples': 33, 'max_depth': 8, 'max_bin': 482, 'min_data_in_leaf': 31, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.12109318210543021, 'min_gain_to_split': 0.024876309458717816}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 02:55:52,373] Trial 318 finished with value: 0.28023869911432747 and parameters: {'num_leaves': 80, 'learning_rate': 0.1705358358141, 'feature_fraction': 0.922949609258782, 'bagging_fraction': 0.9720130612503973, 'bagging_freq': 4, 'lambda_l1': 6.0760195115470224e-06, 'lambda_l2': 2.1159412494790212e-06, 'min_child_samples': 29, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 19, 'path_smooth': 0.966191783511962, 'min_gain_to_split': 0.037979803520713395}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 03:07:24,223] Trial 319 finished with value: 0.21469837591625582 and parameters: {'num_leaves': 64, 'learning_rate': 0.2739336464626578, 'feature_fraction': 0.9325847996954076, 'bagging_fraction': 0.9891744570103556, 'bagging_freq': 7, 'lambda_l1': 2.2430829549747617e-05, 'lambda_l2': 7.368058278680421e-07, 'min_child_samples': 31, 'max_depth': 10, 'max_bin': 488, 'min_data_in_leaf': 39, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.048079019025795026, 'min_gain_to_split': 0.00958783220413904}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 03:18:19,280] Trial 320 finished with value: 0.22086426757138064 and parameters: {'num_leaves': 94, 'learning_rate': 0.23447125525015639, 'feature_fraction': 0.9409981120195524, 'bagging_fraction': 0.8177558662340312, 'bagging_freq': 5, 'lambda_l1': 3.2557418508731453e-06, 'lambda_l2': 6.861329995429279e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 470, 'min_data_in_leaf': 35, 'extra_trees': False, 'early_stopping_rounds': 32, 'path_smooth': 0.49272801756873374, 'min_gain_to_split': 0.0176888970697808}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 03:29:48,427] Trial 321 finished with value: 0.24521503385840795 and parameters: {'num_leaves': 77, 'learning_rate': 0.24958592356909515, 'feature_fraction': 0.8702500270316764, 'bagging_fraction': 0.9768423915023695, 'bagging_freq': 4, 'lambda_l1': 9.253819175279179e-06, 'lambda_l2': 2.785023701115662e-06, 'min_child_samples': 35, 'max_depth': 8, 'max_bin': 479, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.9025939566387053, 'min_gain_to_split': 0.02818573212816207}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 03:34:58,426] Trial 322 finished with value: 0.29243659281554624 and parameters: {'num_leaves': 84, 'learning_rate': 0.29941769357101217, 'feature_fraction': 0.9516031894833271, 'bagging_fraction': 0.993613904488081, 'bagging_freq': 5, 'lambda_l1': 1.978853622233698e-06, 'lambda_l2': 3.491561614336008e-05, 'min_child_samples': 33, 'max_depth': 8, 'max_bin': 493, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.07996038752381045, 'min_gain_to_split': 0.008673262346066463}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 03:47:11,650] Trial 323 finished with value: 0.06709591586458694 and parameters: {'num_leaves': 79, 'learning_rate': 0.26603027834155774, 'feature_fraction': 0.9283719720652978, 'bagging_fraction': 0.9843179744987354, 'bagging_freq': 4, 'lambda_l1': 3.9912731589319764e-06, 'lambda_l2': 1.2572519150227115e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 460, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 21, 'path_smooth': 0.9301900242704347, 'min_gain_to_split': 0.01803800146543272}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 03:52:51,968] Trial 324 finished with value: 0.3018743127714728 and parameters: {'num_leaves': 87, 'learning_rate': 0.27115198062843243, 'feature_fraction': 0.9831188669942909, 'bagging_fraction': 0.9843880790928726, 'bagging_freq': 4, 'lambda_l1': 5.150164906789749e-06, 'lambda_l2': 1.423290960072026e-06, 'min_child_samples': 37, 'max_depth': 8, 'max_bin': 458, 'min_data_in_leaf': 30, 'extra_trees': False, 'early_stopping_rounds': 21, 'path_smooth': 0.028246455726353682, 'min_gain_to_split': 0.3307795834634101}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 04:06:56,574] Trial 325 finished with value: 0.12680356525688902 and parameters: {'num_leaves': 79, 'learning_rate': 0.19435833544514794, 'feature_fraction': 0.9205859809800969, 'bagging_fraction': 0.9899549560176726, 'bagging_freq': 3, 'lambda_l1': 0.0006346822635090398, 'lambda_l2': 4.4395147578878825e-06, 'min_child_samples': 36, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 20, 'path_smooth': 0.058200478194848006, 'min_gain_to_split': 0.04206445561525338}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 04:15:05,364] Trial 326 finished with value: 0.3524834214196183 and parameters: {'num_leaves': 83, 'learning_rate': 0.28198731512939773, 'feature_fraction': 0.9142451039096695, 'bagging_fraction': 0.7397985903859177, 'bagging_freq': 4, 'lambda_l1': 1.572881757747472e-05, 'lambda_l2': 2.0402361939798696e-06, 'min_child_samples': 30, 'max_depth': 7, 'max_bin': 471, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.44289101231250955, 'min_gain_to_split': 0.05453637514571241}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 04:27:17,817] Trial 327 finished with value: 0.2879508240643104 and parameters: {'num_leaves': 81, 'learning_rate': 0.22651035360569546, 'feature_fraction': 0.9280426989737564, 'bagging_fraction': 0.9795672407737355, 'bagging_freq': 4, 'lambda_l1': 3.560313339897391e-06, 'lambda_l2': 3.0659021399672205e-06, 'min_child_samples': 38, 'max_depth': 8, 'max_bin': 479, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.3434104328542681, 'min_gain_to_split': 0.020584391871373363}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 05:06:35,658] Trial 328 finished with value: 0.935217479768841 and parameters: {'num_leaves': 68, 'learning_rate': 0.012946825233975041, 'feature_fraction': 0.9008814736962962, 'bagging_fraction': 0.9938822773683779, 'bagging_freq': 4, 'lambda_l1': 5.835739042519351e-06, 'lambda_l2': 1.034266946187639e-06, 'min_child_samples': 35, 'max_depth': 8, 'max_bin': 456, 'min_data_in_leaf': 27, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.9279951515053603, 'min_gain_to_split': 0.0071775677044289355}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 05:18:26,465] Trial 329 finished with value: 0.15718399594316748 and parameters: {'num_leaves': 60, 'learning_rate': 0.2602539763947095, 'feature_fraction': 0.9414661680406733, 'bagging_fraction': 0.9855178784365989, 'bagging_freq': 4, 'lambda_l1': 8.075089217491439e-06, 'lambda_l2': 1.8458719699053566e-05, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 484, 'min_data_in_leaf': 41, 'extra_trees': False, 'early_stopping_rounds': 20, 'path_smooth': 0.006200529392467142, 'min_gain_to_split': 0.0005105930312860798}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 05:25:59,748] Trial 330 finished with value: 0.3233958876610764 and parameters: {'num_leaves': 80, 'learning_rate': 0.21197523266794982, 'feature_fraction': 0.6288446017780681, 'bagging_fraction': 0.9993092682429371, 'bagging_freq': 4, 'lambda_l1': 0.04639585912089539, 'lambda_l2': 9.597600526051163e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 351, 'min_data_in_leaf': 77, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.9999767649458108, 'min_gain_to_split': 0.029624450984036148}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 05:35:34,864] Trial 331 finished with value: 0.3857153707673514 and parameters: {'num_leaves': 74, 'learning_rate': 0.2668026281851418, 'feature_fraction': 0.9485843994155626, 'bagging_fraction': 0.7154719542233153, 'bagging_freq': 4, 'lambda_l1': 0.006506758192622032, 'lambda_l2': 5.335903361784121e-06, 'min_child_samples': 37, 'max_depth': 8, 'max_bin': 466, 'min_data_in_leaf': 36, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.10185955636201441, 'min_gain_to_split': 0.0001481389474901491}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 05:47:27,892] Trial 332 finished with value: 0.257568763104386 and parameters: {'num_leaves': 92, 'learning_rate': 0.23646336839779988, 'feature_fraction': 0.9366987165683801, 'bagging_fraction': 0.9798652103899907, 'bagging_freq': 6, 'lambda_l1': 2.944949577686607e-06, 'lambda_l2': 1.8989361840828677e-06, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 475, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 21, 'path_smooth': 0.03266265027563711, 'min_gain_to_split': 0.01649526448936415}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 05:58:07,034] Trial 333 finished with value: 0.24292694588430744 and parameters: {'num_leaves': 88, 'learning_rate': 0.2778903213926127, 'feature_fraction': 0.9279912558721052, 'bagging_fraction': 0.9891452015192421, 'bagging_freq': 3, 'lambda_l1': 1.1701876690522646e-05, 'lambda_l2': 4.2940110273726625e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 488, 'min_data_in_leaf': 35, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 9.921581367813704e-05, 'min_gain_to_split': 0.035116540949803494}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 06:10:39,537] Trial 334 finished with value: 0.06156345129407361 and parameters: {'num_leaves': 82, 'learning_rate': 0.2527524980333184, 'feature_fraction': 0.9749527018566706, 'bagging_fraction': 0.9696534066848719, 'bagging_freq': 7, 'lambda_l1': 4.411334269645772e-06, 'lambda_l2': 1.2993360260297864e-06, 'min_child_samples': 33, 'max_depth': 8, 'max_bin': 477, 'min_data_in_leaf': 30, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.18941927771692357, 'min_gain_to_split': 0.023302480462774864}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 07:49:10,584] Trial 335 finished with value: 0.23687625551249467 and parameters: {'num_leaves': 85, 'learning_rate': 0.2175657162123329, 'feature_fraction': 0.9804527104247306, 'bagging_fraction': 0.9948320534329338, 'bagging_freq': 7, 'lambda_l1': 4.595059085840911e-06, 'lambda_l2': 1.235863652833215e-06, 'min_child_samples': 30, 'max_depth': 8, 'max_bin': 467, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.15617153722633348, 'min_gain_to_split': 0.0454837900768891}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 08:03:55,667] Trial 336 finished with value: 0.13332177716417054 and parameters: {'num_leaves': 82, 'learning_rate': 0.24156894165292553, 'feature_fraction': 0.9877750917420931, 'bagging_fraction': 0.984242037785585, 'bagging_freq': 7, 'lambda_l1': 7.0203295629252546e-06, 'lambda_l2': 2.8134147839404213e-06, 'min_child_samples': 33, 'max_depth': 10, 'max_bin': 461, 'min_data_in_leaf': 30, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.09364331678907716, 'min_gain_to_split': 0.025874146159673136}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 08:16:54,692] Trial 337 finished with value: 0.2551072138119095 and parameters: {'num_leaves': 72, 'learning_rate': 0.20508194643572533, 'feature_fraction': 0.9077264735715322, 'bagging_fraction': 0.9998512436298232, 'bagging_freq': 7, 'lambda_l1': 3.903228593450345e-06, 'lambda_l2': 8.870182627762772e-07, 'min_child_samples': 33, 'max_depth': 8, 'max_bin': 449, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 21, 'path_smooth': 0.13600461060823688, 'min_gain_to_split': 0.036222608309657664}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 08:30:16,825] Trial 338 finished with value: 0.1331360989330789 and parameters: {'num_leaves': 83, 'learning_rate': 0.2534228986753014, 'feature_fraction': 0.9759394368236991, 'bagging_fraction': 0.990047057160405, 'bagging_freq': 7, 'lambda_l1': 8.466489564448356e-06, 'lambda_l2': 8.987612891863907e-06, 'min_child_samples': 34, 'max_depth': 8, 'max_bin': 476, 'min_data_in_leaf': 31, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.06550769390254883, 'min_gain_to_split': 0.02080031464083336}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 08:43:53,728] Trial 339 finished with value: 0.18547768301883294 and parameters: {'num_leaves': 78, 'learning_rate': 0.22996981877158623, 'feature_fraction': 0.9934963989409921, 'bagging_fraction': 0.9768984756233648, 'bagging_freq': 7, 'lambda_l1': 2.5315158554368245e-06, 'lambda_l2': 3.490356480534631e-06, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 482, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.2262031016781817, 'min_gain_to_split': 0.028577741860339952}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 08:57:42,990] Trial 340 finished with value: 0.161892550546373 and parameters: {'num_leaves': 85, 'learning_rate': 0.1843489627922994, 'feature_fraction': 0.9659512508899755, 'bagging_fraction': 0.9831039222671478, 'bagging_freq': 5, 'lambda_l1': 5.187798815840603e-06, 'lambda_l2': 6.5073919654870805e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 472, 'min_data_in_leaf': 40, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.04390596792814755, 'min_gain_to_split': 0.015054250306074676}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 09:01:28,382] Trial 341 finished with value: 0.7705511350908409 and parameters: {'num_leaves': 75, 'learning_rate': 0.25933465212041185, 'feature_fraction': 0.8586200116550745, 'bagging_fraction': 0.9713387126322272, 'bagging_freq': 7, 'lambda_l1': 0.0013167326629171972, 'lambda_l2': 1.9577399149955746e-06, 'min_child_samples': 34, 'max_depth': 4, 'max_bin': 486, 'min_data_in_leaf': 43, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.9620223737711315, 'min_gain_to_split': 0.06104725143141807}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 09:13:52,799] Trial 342 finished with value: 0.08422925491831783 and parameters: {'num_leaves': 98, 'learning_rate': 0.24151682011225512, 'feature_fraction': 0.980675467810825, 'bagging_fraction': 0.989921589755316, 'bagging_freq': 6, 'lambda_l1': 1.3985600780352659e-05, 'lambda_l2': 1.4455097981672944e-05, 'min_child_samples': 31, 'max_depth': 7, 'max_bin': 479, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.08374248374442479, 'min_gain_to_split': 0.012848459251055978}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 09:27:12,896] Trial 343 finished with value: 0.1874495015057244 and parameters: {'num_leaves': 82, 'learning_rate': 0.2229182100388342, 'feature_fraction': 0.8926898233716293, 'bagging_fraction': 0.9785407907035842, 'bagging_freq': 6, 'lambda_l1': 0.0001266326589130414, 'lambda_l2': 1.3332439092163423e-06, 'min_child_samples': 33, 'max_depth': 8, 'max_bin': 490, 'min_data_in_leaf': 30, 'extra_trees': False, 'early_stopping_rounds': 19, 'path_smooth': 0.17833255876579035, 'min_gain_to_split': 0.026660293897914255}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 09:48:11,161] Trial 344 finished with value: 0.610524825784616 and parameters: {'num_leaves': 79, 'learning_rate': 0.07675868208238387, 'feature_fraction': 0.9718599976879094, 'bagging_fraction': 0.9933811145743652, 'bagging_freq': 4, 'lambda_l1': 0.00023422232323308897, 'lambda_l2': 2.5176753126359823e-06, 'min_child_samples': 30, 'max_depth': 8, 'max_bin': 471, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.9790637571533907, 'min_gain_to_split': 0.04173982806135547}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 10:04:36,281] Trial 345 finished with value: 0.05331002429998964 and parameters: {'num_leaves': 87, 'learning_rate': 0.202245662232869, 'feature_fraction': 0.9537485671390803, 'bagging_fraction': 0.9688513283410529, 'bagging_freq': 10, 'lambda_l1': 3.46696359050357e-06, 'lambda_l2': 4.412628819758676e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 460, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.021263392649052824, 'min_gain_to_split': 0.018363432476353546}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 10:22:36,582] Trial 346 finished with value: 0.21778700282597113 and parameters: {'num_leaves': 87, 'learning_rate': 0.1940575351374919, 'feature_fraction': 0.9627894360557913, 'bagging_fraction': 0.9999640958556215, 'bagging_freq': 9, 'lambda_l1': 3.957174579956984e-06, 'lambda_l2': 4.9825705328817e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 453, 'min_data_in_leaf': 27, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.022442719167455855, 'min_gain_to_split': 0.03373746958547131}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 10:41:17,780] Trial 347 finished with value: 0.10441117698696267 and parameters: {'num_leaves': 90, 'learning_rate': 0.17381394384849144, 'feature_fraction': 0.9564238910631249, 'bagging_fraction': 0.9861145310219216, 'bagging_freq': 10, 'lambda_l1': 2.660240561213354e-05, 'lambda_l2': 7.340979627876874e-06, 'min_child_samples': 28, 'max_depth': 10, 'max_bin': 461, 'min_data_in_leaf': 39, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.0473772769883349, 'min_gain_to_split': 0.020933155160672443}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 11:00:55,195] Trial 348 finished with value: 0.11675219236371903 and parameters: {'num_leaves': 89, 'learning_rate': 0.21306222995814417, 'feature_fraction': 0.9557909872728103, 'bagging_fraction': 0.9682380884824762, 'bagging_freq': 10, 'lambda_l1': 6.832858947635644e-06, 'lambda_l2': 4.247359067174768e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 470, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.018164443811895664, 'min_gain_to_split': 0.0178511832317801}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 11:09:48,152] Trial 349 finished with value: 0.5735786945062933 and parameters: {'num_leaves': 87, 'learning_rate': 0.2029064169240168, 'feature_fraction': 0.9742121780695873, 'bagging_fraction': 0.9808618310531803, 'bagging_freq': 8, 'lambda_l1': 1.029222832835699e-05, 'lambda_l2': 1.081982572746719e-05, 'min_child_samples': 30, 'max_depth': 5, 'max_bin': 448, 'min_data_in_leaf': 31, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.05921362727167676, 'min_gain_to_split': 0.046690537603873636}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 11:17:19,459] Trial 350 finished with value: 0.3308679193467575 and parameters: {'num_leaves': 85, 'learning_rate': 0.19323958394374538, 'feature_fraction': 0.9494047029685994, 'bagging_fraction': 0.9929998253992433, 'bagging_freq': 8, 'lambda_l1': 3.5754785392592722e-06, 'lambda_l2': 3.2920639648401944e-06, 'min_child_samples': 32, 'max_depth': 10, 'max_bin': 460, 'min_data_in_leaf': 36, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.030152695488626258, 'min_gain_to_split': 0.44729280551086553}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 11:33:20,355] Trial 351 finished with value: 0.35769770921926974 and parameters: {'num_leaves': 88, 'learning_rate': 0.22520758514693864, 'feature_fraction': 0.917545444661658, 'bagging_fraction': 0.9872765963800548, 'bagging_freq': 8, 'lambda_l1': 0.9165410749963111, 'lambda_l2': 2.6924803892076897e-05, 'min_child_samples': 31, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 41, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 4.63621331275102e-05, 'min_gain_to_split': 0.03433553691771345}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 11:51:15,071] Trial 352 finished with value: 0.12801959019486098 and parameters: {'num_leaves': 84, 'learning_rate': 0.2066636000962171, 'feature_fraction': 0.9857257890468473, 'bagging_fraction': 0.9760016173129681, 'bagging_freq': 5, 'lambda_l1': 6.1291228982139005e-06, 'lambda_l2': 5.884401476734861e-06, 'min_child_samples': 32, 'max_depth': 10, 'max_bin': 462, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.19021328736868517, 'min_gain_to_split': 0.010697788662744404}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 12:10:07,378] Trial 353 finished with value: 0.08454152181805072 and parameters: {'num_leaves': 91, 'learning_rate': 0.1802911813189071, 'feature_fraction': 0.9220267769713225, 'bagging_fraction': 0.9941013891941506, 'bagging_freq': 10, 'lambda_l1': 3.15759614985928e-06, 'lambda_l2': 2.9936938688782165e-06, 'min_child_samples': 33, 'max_depth': 10, 'max_bin': 475, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.11345354704767557, 'min_gain_to_split': 0.026191722357503548}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 12:27:29,763] Trial 354 finished with value: 0.11008445396047875 and parameters: {'num_leaves': 85, 'learning_rate': 0.23804937816623234, 'feature_fraction': 0.9095555971834844, 'bagging_fraction': 0.9838779092412216, 'bagging_freq': 5, 'lambda_l1': 2.022169106707062e-05, 'lambda_l2': 4.875671383848429e-06, 'min_child_samples': 31, 'max_depth': 10, 'max_bin': 441, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 40, 'path_smooth': 0.03664944189231596, 'min_gain_to_split': 0.010303539477913801}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 12:46:20,573] Trial 355 finished with value: 0.15236254568709467 and parameters: {'num_leaves': 82, 'learning_rate': 0.24918158733324294, 'feature_fraction': 0.932600654859623, 'bagging_fraction': 0.9685288886706482, 'bagging_freq': 4, 'lambda_l1': 5.498367354530638e-06, 'lambda_l2': 8.186421763293138e-06, 'min_child_samples': 29, 'max_depth': 8, 'max_bin': 484, 'min_data_in_leaf': 36, 'extra_trees': False, 'early_stopping_rounds': 21, 'path_smooth': 0.3000539834437283, 'min_gain_to_split': 0.021494032045125455}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 13:29:49,999] Trial 356 finished with value: 0.891177519622836 and parameters: {'num_leaves': 67, 'learning_rate': 0.028792702309906937, 'feature_fraction': 0.9949713301382512, 'bagging_fraction': 0.9308408994278906, 'bagging_freq': 6, 'lambda_l1': 1.0556945378798027e-05, 'lambda_l2': 7.97711912050369e-05, 'min_child_samples': 33, 'max_depth': 8, 'max_bin': 469, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.07236418546759832, 'min_gain_to_split': 0.03135693321486313}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 13:53:07,831] Trial 357 finished with value: 0.1925661260998779 and parameters: {'num_leaves': 89, 'learning_rate': 0.21788469689076612, 'feature_fraction': 0.9670585680551143, 'bagging_fraction': 0.9898346458924547, 'bagging_freq': 4, 'lambda_l1': 0.0003410058753333364, 'lambda_l2': 2.190809607056961e-06, 'min_child_samples': 30, 'max_depth': 8, 'max_bin': 493, 'min_data_in_leaf': 40, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.018987743004189248, 'min_gain_to_split': 0.051592029675049875}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 14:12:44,116] Trial 358 finished with value: 0.21394612187111567 and parameters: {'num_leaves': 87, 'learning_rate': 0.2735773053514401, 'feature_fraction': 0.959338310403066, 'bagging_fraction': 0.9795292053834602, 'bagging_freq': 4, 'lambda_l1': 2.0073578873871053e-06, 'lambda_l2': 1.7461284349577763e-05, 'min_child_samples': 32, 'max_depth': 7, 'max_bin': 482, 'min_data_in_leaf': 25, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.05039773170421635, 'min_gain_to_split': 0.008749832094298561}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 14:37:08,116] Trial 359 finished with value: 0.19901572845432364 and parameters: {'num_leaves': 93, 'learning_rate': 0.23239803704333742, 'feature_fraction': 0.9480519422729332, 'bagging_fraction': 0.9947448080545127, 'bagging_freq': 3, 'lambda_l1': 0.3141711946380065, 'lambda_l2': 0.000433347733425979, 'min_child_samples': 30, 'max_depth': 8, 'max_bin': 487, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 20, 'path_smooth': 0.08902697922916017, 'min_gain_to_split': 0.017659110347507705}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 15:01:07,701] Trial 360 finished with value: 0.05529013242158574 and parameters: {'num_leaves': 83, 'learning_rate': 0.2541118035770768, 'feature_fraction': 0.9267341706076113, 'bagging_fraction': 0.9855059380342666, 'bagging_freq': 5, 'lambda_l1': 4.444035878908111e-06, 'lambda_l2': 3.8203226679281785e-06, 'min_child_samples': 34, 'max_depth': 10, 'max_bin': 500, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.06518563855090864, 'min_gain_to_split': 0.02670666458334264}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 15:10:42,924] Trial 361 finished with value: 0.4817139883341165 and parameters: {'num_leaves': 84, 'learning_rate': 0.2016017831360978, 'feature_fraction': 0.9261004035566416, 'bagging_fraction': 0.9877070956453259, 'bagging_freq': 5, 'lambda_l1': 7.815340354633497e-06, 'lambda_l2': 3.4552634580927276e-06, 'min_child_samples': 34, 'max_depth': 10, 'max_bin': 456, 'min_data_in_leaf': 43, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.040988417111389785, 'min_gain_to_split': 0.04068747158221797}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 15:39:47,894] Trial 362 finished with value: 0.1110633750868493 and parameters: {'num_leaves': 83, 'learning_rate': 0.24666604341850826, 'feature_fraction': 0.9140566564046477, 'bagging_fraction': 0.9737303943249838, 'bagging_freq': 5, 'lambda_l1': 3.7995599258563145e-06, 'lambda_l2': 8.309460374366436e-07, 'min_child_samples': 32, 'max_depth': 10, 'max_bin': 475, 'min_data_in_leaf': 35, 'extra_trees': False, 'early_stopping_rounds': 29, 'path_smooth': 0.018704485441125133, 'min_gain_to_split': 0.02791448336198643}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 17:05:31,335] Trial 363 finished with value: 0.7070456971882004 and parameters: {'num_leaves': 65, 'learning_rate': 0.020812818269522842, 'feature_fraction': 0.9247506581812012, 'bagging_fraction': 0.9953140882334249, 'bagging_freq': 5, 'lambda_l1': 5.070221091131222e-06, 'lambda_l2': 2.1375710086069727e-06, 'min_child_samples': 34, 'max_depth': 10, 'max_bin': 500, 'min_data_in_leaf': 30, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.1278929071172487, 'min_gain_to_split': 0.03767207578154742}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 17:22:51,577] Trial 364 finished with value: 0.15122477645317672 and parameters: {'num_leaves': 85, 'learning_rate': 0.2816097167527577, 'feature_fraction': 0.9392884204856178, 'bagging_fraction': 0.982897211285568, 'bagging_freq': 6, 'lambda_l1': 1.3676186952479831e-05, 'lambda_l2': 4.867311927775724e-07, 'min_child_samples': 28, 'max_depth': 10, 'max_bin': 490, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.06346613463118664, 'min_gain_to_split': 0.0660582763966083}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 17:47:58,881] Trial 365 finished with value: 0.06187592603385215 and parameters: {'num_leaves': 81, 'learning_rate': 0.22114530184587916, 'feature_fraction': 0.8776417484170544, 'bagging_fraction': 0.9764931786974347, 'bagging_freq': 5, 'lambda_l1': 3.663612441295386e-05, 'lambda_l2': 1.1475274567130934e-05, 'min_child_samples': 31, 'max_depth': 10, 'max_bin': 464, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9783020548773044, 'min_gain_to_split': 0.023249038619906504}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 18:08:59,306] Trial 366 finished with value: 0.21517425973187407 and parameters: {'num_leaves': 81, 'learning_rate': 0.21358438215450026, 'feature_fraction': 0.8743016640928417, 'bagging_fraction': 0.8878145707884553, 'bagging_freq': 5, 'lambda_l1': 5.7582582404988736e-05, 'lambda_l2': 1.1247666578020766e-05, 'min_child_samples': 31, 'max_depth': 10, 'max_bin': 446, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9655152860668026, 'min_gain_to_split': 0.0536615355369906}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 19:00:39,603] Trial 367 finished with value: 0.15030188137376843 and parameters: {'num_leaves': 83, 'learning_rate': 0.19438985023344033, 'feature_fraction': 0.8795743824878743, 'bagging_fraction': 0.9672401785968845, 'bagging_freq': 5, 'lambda_l1': 0.00010441230802118518, 'lambda_l2': 6.357590270724319e-06, 'min_child_samples': 31, 'max_depth': 10, 'max_bin': 462, 'min_data_in_leaf': 31, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.9997859704293132, 'min_gain_to_split': 0.03413530829576534}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 20:07:08,293] Trial 368 finished with value: 0.15203094710179887 and parameters: {'num_leaves': 86, 'learning_rate': 0.22338549866220536, 'feature_fraction': 0.8964326315777494, 'bagging_fraction': 0.9733240588188681, 'bagging_freq': 5, 'lambda_l1': 3.155195811266904e-05, 'lambda_l2': 1.6478475590069473e-06, 'min_child_samples': 30, 'max_depth': 10, 'max_bin': 386, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 38, 'path_smooth': 0.9842423133177675, 'min_gain_to_split': 0.025461211349903964}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 20:48:37,506] Trial 369 finished with value: 0.06419600915378328 and parameters: {'num_leaves': 82, 'learning_rate': 0.22955615670330312, 'feature_fraction': 0.8979341329454233, 'bagging_fraction': 0.9776218249822795, 'bagging_freq': 5, 'lambda_l1': 3.913349271108815e-05, 'lambda_l2': 3.971122135043308e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 466, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.9486532038729717, 'min_gain_to_split': 0.04186537516372447}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 22:59:50,683] Trial 370 finished with value: 0.9216593698220796 and parameters: {'num_leaves': 82, 'learning_rate': 0.010113703163574255, 'feature_fraction': 0.8883600590966654, 'bagging_fraction': 0.9998931734871703, 'bagging_freq': 5, 'lambda_l1': 4.376480084220848e-05, 'lambda_l2': 7.726322742535734e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 452, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.9506301048621034, 'min_gain_to_split': 0.04511511673640448}. Best is trial 272 with value: 0.04277612373730953.

Mejor trial hasta ahora: RMSE=0.042776, Parámetros={'num_leaves': 77, 'learning_rate': 0.2451931266447765, 'feature_fraction': 0.9374080714486916, 'bagging_fraction': 0.9805517118978127, 'bagging_freq': 4, 'lambda_l1': 3.1119919722196896e-06, 'lambda_l2': 1.3192716280818084e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9755895661202072, 'min_gain_to_split': 0.02152465296961507}

[I 2025-07-11 23:20:29,758] Trial 371 finished with value: 0.01917960973943581 and parameters: {'num_leaves': 81, 'learning_rate': 0.2067657403659724, 'feature_fraction': 0.897740362101773, 'bagging_fraction': 0.9783984895510337, 'bagging_freq': 5, 'lambda_l1': 6.437768634924736e-05, 'lambda_l2': 4.723296621845035e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9836390817928878, 'min_gain_to_split': 0.04278735382396155}. Best is trial 371 with value: 0.01917960973943581.

Mejor trial hasta ahora: RMSE=0.019180, Parámetros={'num_leaves': 81, 'learning_rate': 0.2067657403659724, 'feature_fraction': 0.897740362101773, 'bagging_fraction': 0.9783984895510337, 'bagging_freq': 5, 'lambda_l1': 6.437768634924736e-05, 'lambda_l2': 4.723296621845035e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9836390817928878, 'min_gain_to_split': 0.04278735382396155}

[I 2025-07-11 23:40:09,896] Trial 372 finished with value: 0.21190320984155822 and parameters: {'num_leaves': 80, 'learning_rate': 0.19058784827028882, 'feature_fraction': 0.9091453100617765, 'bagging_fraction': 0.9787312129298624, 'bagging_freq': 5, 'lambda_l1': 8.615670685065443e-05, 'lambda_l2': 5.629950423034138e-06, 'min_child_samples': 27, 'max_depth': 10, 'max_bin': 458, 'min_data_in_leaf': 23, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.9855574740783103, 'min_gain_to_split': 0.053657787075194946}. Best is trial 371 with value: 0.01917960973943581.

Mejor trial hasta ahora: RMSE=0.019180, Parámetros={'num_leaves': 81, 'learning_rate': 0.2067657403659724, 'feature_fraction': 0.897740362101773, 'bagging_fraction': 0.9783984895510337, 'bagging_freq': 5, 'lambda_l1': 6.437768634924736e-05, 'lambda_l2': 4.723296621845035e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9836390817928878, 'min_gain_to_split': 0.04278735382396155}

[I 2025-07-12 00:05:16,529] Trial 373 finished with value: 0.037603727251008655 and parameters: {'num_leaves': 81, 'learning_rate': 0.16709536421538057, 'feature_fraction': 0.9060687192776563, 'bagging_fraction': 0.970454370839239, 'bagging_freq': 5, 'lambda_l1': 3.866056323461306e-05, 'lambda_l2': 1.1755096317535548e-05, 'min_child_samples': 28, 'max_depth': 10, 'max_bin': 464, 'min_data_in_leaf': 26, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.9748544792980716, 'min_gain_to_split': 0.0470518907597946}. Best is trial 371 with value: 0.01917960973943581.

Mejor trial hasta ahora: RMSE=0.019180, Parámetros={'num_leaves': 81, 'learning_rate': 0.2067657403659724, 'feature_fraction': 0.897740362101773, 'bagging_fraction': 0.9783984895510337, 'bagging_freq': 5, 'lambda_l1': 6.437768634924736e-05, 'lambda_l2': 4.723296621845035e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9836390817928878, 'min_gain_to_split': 0.04278735382396155}

[I 2025-07-12 00:25:26,048] Trial 374 finished with value: 0.1329234104732093 and parameters: {'num_leaves': 82, 'learning_rate': 0.18451562220138204, 'feature_fraction': 0.9005182532604661, 'bagging_fraction': 0.9672847225137016, 'bagging_freq': 5, 'lambda_l1': 5.415809688436602e-05, 'lambda_l2': 1.2788581380298667e-05, 'min_child_samples': 28, 'max_depth': 10, 'max_bin': 449, 'min_data_in_leaf': 21, 'extra_trees': False, 'early_stopping_rounds': 28, 'path_smooth': 0.9750526339388708, 'min_gain_to_split': 0.06031633572990344}. Best is trial 371 with value: 0.01917960973943581.

Mejor trial hasta ahora: RMSE=0.019180, Parámetros={'num_leaves': 81, 'learning_rate': 0.2067657403659724, 'feature_fraction': 0.897740362101773, 'bagging_fraction': 0.9783984895510337, 'bagging_freq': 5, 'lambda_l1': 6.437768634924736e-05, 'lambda_l2': 4.723296621845035e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9836390817928878, 'min_gain_to_split': 0.04278735382396155}

[I 2025-07-12 00:49:43,758] Trial 375 finished with value: 0.16233310629145806 and parameters: {'num_leaves': 81, 'learning_rate': 0.16637356366317446, 'feature_fraction': 0.8991304787187838, 'bagging_fraction': 0.9691413502817695, 'bagging_freq': 5, 'lambda_l1': 4.084649432952172e-05, 'lambda_l2': 1.1107720010846243e-05, 'min_child_samples': 28, 'max_depth': 10, 'max_bin': 466, 'min_data_in_leaf': 25, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9594901677696922, 'min_gain_to_split': 0.042934241576142854}. Best is trial 371 with value: 0.01917960973943581.

Mejor trial hasta ahora: RMSE=0.019180, Parámetros={'num_leaves': 81, 'learning_rate': 0.2067657403659724, 'feature_fraction': 0.897740362101773, 'bagging_fraction': 0.9783984895510337, 'bagging_freq': 5, 'lambda_l1': 6.437768634924736e-05, 'lambda_l2': 4.723296621845035e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9836390817928878, 'min_gain_to_split': 0.04278735382396155}

[I 2025-07-12 01:09:49,577] Trial 376 finished with value: 0.22149321042396536 and parameters: {'num_leaves': 80, 'learning_rate': 0.17453217722291978, 'feature_fraction': 0.8941967391332863, 'bagging_fraction': 0.9635007700546768, 'bagging_freq': 5, 'lambda_l1': 6.977382653487538e-05, 'lambda_l2': 9.010396254736807e-06, 'min_child_samples': 27, 'max_depth': 10, 'max_bin': 454, 'min_data_in_leaf': 26, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.9435707520334147, 'min_gain_to_split': 0.07159962562789095}. Best is trial 371 with value: 0.01917960973943581.

Mejor trial hasta ahora: RMSE=0.019180, Parámetros={'num_leaves': 81, 'learning_rate': 0.2067657403659724, 'feature_fraction': 0.897740362101773, 'bagging_fraction': 0.9783984895510337, 'bagging_freq': 5, 'lambda_l1': 6.437768634924736e-05, 'lambda_l2': 4.723296621845035e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9836390817928878, 'min_gain_to_split': 0.04278735382396155}

[I 2025-07-12 01:26:10,384] Trial 377 finished with value: 0.058260441807809246 and parameters: {'num_leaves': 84, 'learning_rate': 0.20376494295175981, 'feature_fraction': 0.9026381336934434, 'bagging_fraction': 0.9755610867360976, 'bagging_freq': 5, 'lambda_l1': 2.6125397252931178e-05, 'lambda_l2': 1.5867912862396333e-05, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 439, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.9869067176172935, 'min_gain_to_split': 0.04787239856054786}. Best is trial 371 with value: 0.01917960973943581.

Mejor trial hasta ahora: RMSE=0.019180, Parámetros={'num_leaves': 81, 'learning_rate': 0.2067657403659724, 'feature_fraction': 0.897740362101773, 'bagging_fraction': 0.9783984895510337, 'bagging_freq': 5, 'lambda_l1': 6.437768634924736e-05, 'lambda_l2': 4.723296621845035e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9836390817928878, 'min_gain_to_split': 0.04278735382396155}

[I 2025-07-12 01:39:19,576] Trial 378 finished with value: 0.13614237408075133 and parameters: {'num_leaves': 84, 'learning_rate': 0.20206058492301404, 'feature_fraction': 0.908651998430458, 'bagging_fraction': 0.9706595613361538, 'bagging_freq': 5, 'lambda_l1': 3.105737486122692e-05, 'lambda_l2': 1.7521108405041793e-05, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 459, 'min_data_in_leaf': 27, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.9893837525212856, 'min_gain_to_split': 0.03938067009054555}. Best is trial 371 with value: 0.01917960973943581.

Mejor trial hasta ahora: RMSE=0.019180, Parámetros={'num_leaves': 81, 'learning_rate': 0.2067657403659724, 'feature_fraction': 0.897740362101773, 'bagging_fraction': 0.9783984895510337, 'bagging_freq': 5, 'lambda_l1': 6.437768634924736e-05, 'lambda_l2': 4.723296621845035e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9836390817928878, 'min_gain_to_split': 0.04278735382396155}

[I 2025-07-12 01:50:38,859] Trial 379 finished with value: 0.2489939013711508 and parameters: {'num_leaves': 84, 'learning_rate': 0.18367164003376485, 'feature_fraction': 0.9052322991578847, 'bagging_fraction': 0.9758444863858288, 'bagging_freq': 5, 'lambda_l1': 3.867037174782102e-05, 'lambda_l2': 2.613337408336562e-05, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 439, 'min_data_in_leaf': 26, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.970867592190787, 'min_gain_to_split': 0.06121745823432217}. Best is trial 371 with value: 0.01917960973943581.

Mejor trial hasta ahora: RMSE=0.019180, Parámetros={'num_leaves': 81, 'learning_rate': 0.2067657403659724, 'feature_fraction': 0.897740362101773, 'bagging_fraction': 0.9783984895510337, 'bagging_freq': 5, 'lambda_l1': 6.437768634924736e-05, 'lambda_l2': 4.723296621845035e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9836390817928878, 'min_gain_to_split': 0.04278735382396155}

[I 2025-07-12 02:04:29,476] Trial 380 finished with value: 0.12580239377656205 and parameters: {'num_leaves': 82, 'learning_rate': 0.15510698687941504, 'feature_fraction': 0.896720199937634, 'bagging_fraction': 0.9652790866184435, 'bagging_freq': 5, 'lambda_l1': 2.677400408630229e-05, 'lambda_l2': 1.4547870940339587e-05, 'min_child_samples': 27, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.9626644295431794, 'min_gain_to_split': 0.07903054422628583}. Best is trial 371 with value: 0.01917960973943581.

Mejor trial hasta ahora: RMSE=0.019180, Parámetros={'num_leaves': 81, 'learning_rate': 0.2067657403659724, 'feature_fraction': 0.897740362101773, 'bagging_fraction': 0.9783984895510337, 'bagging_freq': 5, 'lambda_l1': 6.437768634924736e-05, 'lambda_l2': 4.723296621845035e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9836390817928878, 'min_gain_to_split': 0.04278735382396155}

[I 2025-07-12 02:16:16,731] Trial 381 finished with value: 0.29957574235176865 and parameters: {'num_leaves': 86, 'learning_rate': 0.19890240591978056, 'feature_fraction': 0.9041751966068767, 'bagging_fraction': 0.97604491281347, 'bagging_freq': 5, 'lambda_l1': 6.552103107793143e-05, 'lambda_l2': 3.499139777353035e-05, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 435, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.9771332259303147, 'min_gain_to_split': 0.05060664160434536}. Best is trial 371 with value: 0.01917960973943581.

Mejor trial hasta ahora: RMSE=0.019180, Parámetros={'num_leaves': 81, 'learning_rate': 0.2067657403659724, 'feature_fraction': 0.897740362101773, 'bagging_fraction': 0.9783984895510337, 'bagging_freq': 5, 'lambda_l1': 6.437768634924736e-05, 'lambda_l2': 4.723296621845035e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9836390817928878, 'min_gain_to_split': 0.04278735382396155}

[I 2025-07-12 02:26:12,813] Trial 382 finished with value: 0.088367260842694 and parameters: {'num_leaves': 83, 'learning_rate': 0.2080997381985664, 'feature_fraction': 0.9120092746007136, 'bagging_fraction': 0.9709612380459629, 'bagging_freq': 5, 'lambda_l1': 2.0315662997544517e-05, 'lambda_l2': 1.99565146904539e-05, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 330, 'min_data_in_leaf': 26, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.9376853489887547, 'min_gain_to_split': 0.047571144588183296}. Best is trial 371 with value: 0.01917960973943581.

Mejor trial hasta ahora: RMSE=0.019180, Parámetros={'num_leaves': 81, 'learning_rate': 0.2067657403659724, 'feature_fraction': 0.897740362101773, 'bagging_fraction': 0.9783984895510337, 'bagging_freq': 5, 'lambda_l1': 6.437768634924736e-05, 'lambda_l2': 4.723296621845035e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9836390817928878, 'min_gain_to_split': 0.04278735382396155}

[I 2025-07-12 02:31:01,451] Trial 383 finished with value: 0.5532983030689034 and parameters: {'num_leaves': 81, 'learning_rate': 0.17945391773625666, 'feature_fraction': 0.9173043294893646, 'bagging_fraction': 0.9785997880245487, 'bagging_freq': 5, 'lambda_l1': 4.091434074384996e-05, 'lambda_l2': 1.1212274109873422e-05, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 445, 'min_data_in_leaf': 30, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.9929489333956739, 'min_gain_to_split': 0.04011905735997061}. Best is trial 371 with value: 0.01917960973943581.

Mejor trial hasta ahora: RMSE=0.019180, Parámetros={'num_leaves': 81, 'learning_rate': 0.2067657403659724, 'feature_fraction': 0.897740362101773, 'bagging_fraction': 0.9783984895510337, 'bagging_freq': 5, 'lambda_l1': 6.437768634924736e-05, 'lambda_l2': 4.723296621845035e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9836390817928878, 'min_gain_to_split': 0.04278735382396155}

[I 2025-07-12 02:42:07,583] Trial 384 finished with value: 0.16766132284479512 and parameters: {'num_leaves': 80, 'learning_rate': 0.2163206558097327, 'feature_fraction': 0.8884160437480872, 'bagging_fraction': 0.9588487082519973, 'bagging_freq': 5, 'lambda_l1': 6.770706484921178e-05, 'lambda_l2': 7.86411558859232e-06, 'min_child_samples': 28, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 28, 'path_smooth': 0.9567461315890987, 'min_gain_to_split': 0.057447128601991596}. Best is trial 371 with value: 0.01917960973943581.

Mejor trial hasta ahora: RMSE=0.019180, Parámetros={'num_leaves': 81, 'learning_rate': 0.2067657403659724, 'feature_fraction': 0.897740362101773, 'bagging_fraction': 0.9783984895510337, 'bagging_freq': 5, 'lambda_l1': 6.437768634924736e-05, 'lambda_l2': 4.723296621845035e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9836390817928878, 'min_gain_to_split': 0.04278735382396155}

[I 2025-07-12 02:49:54,399] Trial 385 finished with value: 0.18890820290197174 and parameters: {'num_leaves': 83, 'learning_rate': 0.16280644424881136, 'feature_fraction': 0.9146691898115042, 'bagging_fraction': 0.9798006390803173, 'bagging_freq': 5, 'lambda_l1': 2.3086792192231375e-05, 'lambda_l2': 1.5806924693773906e-07, 'min_child_samples': 26, 'max_depth': 10, 'max_bin': 458, 'min_data_in_leaf': 23, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.9812697461676172, 'min_gain_to_split': 0.2465903630219601}. Best is trial 371 with value: 0.01917960973943581.

Mejor trial hasta ahora: RMSE=0.019180, Parámetros={'num_leaves': 81, 'learning_rate': 0.2067657403659724, 'feature_fraction': 0.897740362101773, 'bagging_fraction': 0.9783984895510337, 'bagging_freq': 5, 'lambda_l1': 6.437768634924736e-05, 'lambda_l2': 4.723296621845035e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9836390817928878, 'min_gain_to_split': 0.04278735382396155}

[I 2025-07-12 03:02:27,565] Trial 386 finished with value: 0.11886687294417464 and parameters: {'num_leaves': 81, 'learning_rate': 0.19531549660777733, 'feature_fraction': 0.9027828922861408, 'bagging_fraction': 0.9735567629276335, 'bagging_freq': 5, 'lambda_l1': 0.00014343951851054852, 'lambda_l2': 5.135643723334228e-05, 'min_child_samples': 40, 'max_depth': 10, 'max_bin': 468, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.952071606819759, 'min_gain_to_split': 0.04775215504753391}. Best is trial 371 with value: 0.01917960973943581.

Mejor trial hasta ahora: RMSE=0.019180, Parámetros={'num_leaves': 81, 'learning_rate': 0.2067657403659724, 'feature_fraction': 0.897740362101773, 'bagging_fraction': 0.9783984895510337, 'bagging_freq': 5, 'lambda_l1': 6.437768634924736e-05, 'lambda_l2': 4.723296621845035e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9836390817928878, 'min_gain_to_split': 0.04278735382396155}

[I 2025-07-12 03:15:18,963] Trial 387 finished with value: 0.2509320144417272 and parameters: {'num_leaves': 86, 'learning_rate': 0.2049921553166408, 'feature_fraction': 0.9183794682252477, 'bagging_fraction': 0.9821347131353066, 'bagging_freq': 5, 'lambda_l1': 1.6715794078477037e-05, 'lambda_l2': 5.66130865464061e-06, 'min_child_samples': 30, 'max_depth': 10, 'max_bin': 451, 'min_data_in_leaf': 27, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.9942539334529373, 'min_gain_to_split': 0.03548065364277592}. Best is trial 371 with value: 0.01917960973943581.

Mejor trial hasta ahora: RMSE=0.019180, Parámetros={'num_leaves': 81, 'learning_rate': 0.2067657403659724, 'feature_fraction': 0.897740362101773, 'bagging_fraction': 0.9783984895510337, 'bagging_freq': 5, 'lambda_l1': 6.437768634924736e-05, 'lambda_l2': 4.723296621845035e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9836390817928878, 'min_gain_to_split': 0.04278735382396155}

[I 2025-07-12 03:23:14,817] Trial 388 finished with value: 0.17587863654047187 and parameters: {'num_leaves': 85, 'learning_rate': 0.2252689366711757, 'feature_fraction': 0.8404706043130383, 'bagging_fraction': 0.9637602196603491, 'bagging_freq': 5, 'lambda_l1': 9.808389642572234e-05, 'lambda_l2': 2.879746932956997e-07, 'min_child_samples': 28, 'max_depth': 10, 'max_bin': 467, 'min_data_in_leaf': 30, 'extra_trees': False, 'early_stopping_rounds': 30, 'path_smooth': 0.9374040374013086, 'min_gain_to_split': 0.1227076637682128}. Best is trial 371 with value: 0.01917960973943581.

Mejor trial hasta ahora: RMSE=0.019180, Parámetros={'num_leaves': 81, 'learning_rate': 0.2067657403659724, 'feature_fraction': 0.897740362101773, 'bagging_fraction': 0.9783984895510337, 'bagging_freq': 5, 'lambda_l1': 6.437768634924736e-05, 'lambda_l2': 4.723296621845035e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9836390817928878, 'min_gain_to_split': 0.04278735382396155}

[I 2025-07-12 03:30:27,930] Trial 389 finished with value: 0.29597518669964584 and parameters: {'num_leaves': 79, 'learning_rate': 0.2192576232185337, 'feature_fraction': 0.907990939542252, 'bagging_fraction': 0.9696948008548792, 'bagging_freq': 5, 'lambda_l1': 4.250688061944414e-05, 'lambda_l2': 1.3989086500265188e-05, 'min_child_samples': 30, 'max_depth': 10, 'max_bin': 472, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.968452812687194, 'min_gain_to_split': 0.18235891754145364}. Best is trial 371 with value: 0.01917960973943581.

Mejor trial hasta ahora: RMSE=0.019180, Parámetros={'num_leaves': 81, 'learning_rate': 0.2067657403659724, 'feature_fraction': 0.897740362101773, 'bagging_fraction': 0.9783984895510337, 'bagging_freq': 5, 'lambda_l1': 6.437768634924736e-05, 'lambda_l2': 4.723296621845035e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9836390817928878, 'min_gain_to_split': 0.04278735382396155}

[I 2025-07-12 03:43:53,964] Trial 390 finished with value: 0.25447819874349903 and parameters: {'num_leaves': 83, 'learning_rate': 0.18663207341953494, 'feature_fraction': 0.9216453580272984, 'bagging_fraction': 0.8627990649424405, 'bagging_freq': 5, 'lambda_l1': 2.4920860681610795e-05, 'lambda_l2': 7.875403400672021e-06, 'min_child_samples': 28, 'max_depth': 10, 'max_bin': 457, 'min_data_in_leaf': 25, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.9976872866782652, 'min_gain_to_split': 0.02896059182830139}. Best is trial 371 with value: 0.01917960973943581.

Mejor trial hasta ahora: RMSE=0.019180, Parámetros={'num_leaves': 81, 'learning_rate': 0.2067657403659724, 'feature_fraction': 0.897740362101773, 'bagging_fraction': 0.9783984895510337, 'bagging_freq': 5, 'lambda_l1': 6.437768634924736e-05, 'lambda_l2': 4.723296621845035e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9836390817928878, 'min_gain_to_split': 0.04278735382396155}

[I 2025-07-12 03:56:55,231] Trial 391 finished with value: 0.2005973284322061 and parameters: {'num_leaves': 81, 'learning_rate': 0.1378945509996745, 'feature_fraction': 0.9012114640381246, 'bagging_fraction': 0.9844813903442146, 'bagging_freq': 5, 'lambda_l1': 5.55745585043755e-05, 'lambda_l2': 4.853996477665177e-06, 'min_child_samples': 30, 'max_depth': 10, 'max_bin': 463, 'min_data_in_leaf': 31, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.940941683039795, 'min_gain_to_split': 0.06651114007354032}. Best is trial 371 with value: 0.01917960973943581.

Mejor trial hasta ahora: RMSE=0.019180, Parámetros={'num_leaves': 81, 'learning_rate': 0.2067657403659724, 'feature_fraction': 0.897740362101773, 'bagging_fraction': 0.9783984895510337, 'bagging_freq': 5, 'lambda_l1': 6.437768634924736e-05, 'lambda_l2': 4.723296621845035e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9836390817928878, 'min_gain_to_split': 0.04278735382396155}

[I 2025-07-12 04:08:18,921] Trial 392 finished with value: 0.15565534212767304 and parameters: {'num_leaves': 58, 'learning_rate': 0.2081501005077669, 'feature_fraction': 0.8920339794782808, 'bagging_fraction': 0.9773687235665645, 'bagging_freq': 6, 'lambda_l1': 3.309324251600985e-05, 'lambda_l2': 4.378259281217896e-06, 'min_child_samples': 28, 'max_depth': 10, 'max_bin': 477, 'min_data_in_leaf': 31, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.9664420867996276, 'min_gain_to_split': 0.03778763815328242}. Best is trial 371 with value: 0.01917960973943581.

Mejor trial hasta ahora: RMSE=0.019180, Parámetros={'num_leaves': 81, 'learning_rate': 0.2067657403659724, 'feature_fraction': 0.897740362101773, 'bagging_fraction': 0.9783984895510337, 'bagging_freq': 5, 'lambda_l1': 6.437768634924736e-05, 'lambda_l2': 4.723296621845035e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9836390817928878, 'min_gain_to_split': 0.04278735382396155}

[I 2025-07-12 04:19:40,605] Trial 393 finished with value: 0.18384169774826598 and parameters: {'num_leaves': 87, 'learning_rate': 0.2329383245369589, 'feature_fraction': 0.9293819861515987, 'bagging_fraction': 0.9848504376451428, 'bagging_freq': 5, 'lambda_l1': 1.617575372818855e-05, 'lambda_l2': 2.650158587275212e-05, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 408, 'min_data_in_leaf': 27, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9233735727915086, 'min_gain_to_split': 0.027210876753327062}. Best is trial 371 with value: 0.01917960973943581.

Mejor trial hasta ahora: RMSE=0.019180, Parámetros={'num_leaves': 81, 'learning_rate': 0.2067657403659724, 'feature_fraction': 0.897740362101773, 'bagging_fraction': 0.9783984895510337, 'bagging_freq': 5, 'lambda_l1': 6.437768634924736e-05, 'lambda_l2': 4.723296621845035e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9836390817928878, 'min_gain_to_split': 0.04278735382396155}

[I 2025-07-12 04:25:06,981] Trial 394 finished with value: 0.3517601829097782 and parameters: {'num_leaves': 80, 'learning_rate': 0.23747988139488507, 'feature_fraction': 0.9124308491734964, 'bagging_fraction': 0.9744423210300475, 'bagging_freq': 5, 'lambda_l1': 0.00022487971265499623, 'lambda_l2': 1.035246402042634e-05, 'min_child_samples': 27, 'max_depth': 6, 'max_bin': 472, 'min_data_in_leaf': 62, 'extra_trees': False, 'early_stopping_rounds': 29, 'path_smooth': 0.9815640194323186, 'min_gain_to_split': 0.3022613177055334}. Best is trial 371 with value: 0.01917960973943581.

Mejor trial hasta ahora: RMSE=0.019180, Parámetros={'num_leaves': 81, 'learning_rate': 0.2067657403659724, 'feature_fraction': 0.897740362101773, 'bagging_fraction': 0.9783984895510337, 'bagging_freq': 5, 'lambda_l1': 6.437768634924736e-05, 'lambda_l2': 4.723296621845035e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9836390817928878, 'min_gain_to_split': 0.04278735382396155}

[I 2025-07-12 04:36:02,801] Trial 395 finished with value: 0.29138243046920664 and parameters: {'num_leaves': 84, 'learning_rate': 0.19303873251063403, 'feature_fraction': 0.9199629240552667, 'bagging_fraction': 0.9868948650434398, 'bagging_freq': 5, 'lambda_l1': 8.711163169339513e-05, 'lambda_l2': 7.297109184537875e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 451, 'min_data_in_leaf': 71, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.9581403727943698, 'min_gain_to_split': 0.04482192398911004}. Best is trial 371 with value: 0.01917960973943581.

Mejor trial hasta ahora: RMSE=0.019180, Parámetros={'num_leaves': 81, 'learning_rate': 0.2067657403659724, 'feature_fraction': 0.897740362101773, 'bagging_fraction': 0.9783984895510337, 'bagging_freq': 5, 'lambda_l1': 6.437768634924736e-05, 'lambda_l2': 4.723296621845035e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9836390817928878, 'min_gain_to_split': 0.04278735382396155}

[I 2025-07-12 04:49:01,356] Trial 396 finished with value: 0.32845176485711913 and parameters: {'num_leaves': 79, 'learning_rate': 0.2187337327778333, 'feature_fraction': 0.9289145203947117, 'bagging_fraction': 0.9228371556383367, 'bagging_freq': 6, 'lambda_l1': 1.7879492427093506e-05, 'lambda_l2': 1.0833042822543487e-06, 'min_child_samples': 30, 'max_depth': 10, 'max_bin': 479, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.9747913257333719, 'min_gain_to_split': 0.021730733137092333}. Best is trial 371 with value: 0.01917960973943581.

Mejor trial hasta ahora: RMSE=0.019180, Parámetros={'num_leaves': 81, 'learning_rate': 0.2067657403659724, 'feature_fraction': 0.897740362101773, 'bagging_fraction': 0.9783984895510337, 'bagging_freq': 5, 'lambda_l1': 6.437768634924736e-05, 'lambda_l2': 4.723296621845035e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9836390817928878, 'min_gain_to_split': 0.04278735382396155}

[I 2025-07-12 05:02:13,344] Trial 397 finished with value: 0.2780048511432879 and parameters: {'num_leaves': 82, 'learning_rate': 0.16852861672272856, 'feature_fraction': 0.9220388748033294, 'bagging_fraction': 0.9639455139777638, 'bagging_freq': 9, 'lambda_l1': 1.0583050726027777e-05, 'lambda_l2': 3.7129669913942583e-06, 'min_child_samples': 31, 'max_depth': 9, 'max_bin': 466, 'min_data_in_leaf': 24, 'extra_trees': False, 'early_stopping_rounds': 19, 'path_smooth': 0.9174668064557999, 'min_gain_to_split': 0.03300649654409087}. Best is trial 371 with value: 0.01917960973943581.

Mejor trial hasta ahora: RMSE=0.019180, Parámetros={'num_leaves': 81, 'learning_rate': 0.2067657403659724, 'feature_fraction': 0.897740362101773, 'bagging_fraction': 0.9783984895510337, 'bagging_freq': 5, 'lambda_l1': 6.437768634924736e-05, 'lambda_l2': 4.723296621845035e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9836390817928878, 'min_gain_to_split': 0.04278735382396155}

[I 2025-07-12 05:13:21,731] Trial 398 finished with value: 0.050813776005781075 and parameters: {'num_leaves': 78, 'learning_rate': 0.20528657003221376, 'feature_fraction': 0.9102932583135341, 'bagging_fraction': 0.98112300276498, 'bagging_freq': 5, 'lambda_l1': 0.00015006626294920781, 'lambda_l2': 6.18275142482901e-07, 'min_child_samples': 28, 'max_depth': 10, 'max_bin': 442, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 21, 'path_smooth': 0.9491990038577798, 'min_gain_to_split': 0.05582693601602849}. Best is trial 371 with value: 0.01917960973943581.

Mejor trial hasta ahora: RMSE=0.019180, Parámetros={'num_leaves': 81, 'learning_rate': 0.2067657403659724, 'feature_fraction': 0.897740362101773, 'bagging_fraction': 0.9783984895510337, 'bagging_freq': 5, 'lambda_l1': 6.437768634924736e-05, 'lambda_l2': 4.723296621845035e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9836390817928878, 'min_gain_to_split': 0.04278735382396155}

[I 2025-07-12 05:24:30,009] Trial 399 finished with value: 0.06265233638867305 and parameters: {'num_leaves': 78, 'learning_rate': 0.1842984821468131, 'feature_fraction': 0.9056499108526401, 'bagging_fraction': 0.9711681830667047, 'bagging_freq': 5, 'lambda_l1': 0.00014825672720442866, 'lambda_l2': 5.075913888016071e-07, 'min_child_samples': 26, 'max_depth': 10, 'max_bin': 414, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 20, 'path_smooth': 0.40687444142038287, 'min_gain_to_split': 0.05415989990572106}. Best is trial 371 with value: 0.01917960973943581.

Mejor trial hasta ahora: RMSE=0.019180, Parámetros={'num_leaves': 81, 'learning_rate': 0.2067657403659724, 'feature_fraction': 0.897740362101773, 'bagging_fraction': 0.9783984895510337, 'bagging_freq': 5, 'lambda_l1': 6.437768634924736e-05, 'lambda_l2': 4.723296621845035e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9836390817928878, 'min_gain_to_split': 0.04278735382396155}

[I 2025-07-12 05:35:18,089] Trial 400 finished with value: 0.2048951963131504 and parameters: {'num_leaves': 77, 'learning_rate': 0.17713265145711535, 'feature_fraction': 0.8993030992414074, 'bagging_fraction': 0.9691346437958758, 'bagging_freq': 5, 'lambda_l1': 0.0001588074067516276, 'lambda_l2': 2.45105078462228e-07, 'min_child_samples': 26, 'max_depth': 10, 'max_bin': 418, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 20, 'path_smooth': 0.9960022580724525, 'min_gain_to_split': 0.06656609665303487}. Best is trial 371 with value: 0.01917960973943581.

Mejor trial hasta ahora: RMSE=0.019180, Parámetros={'num_leaves': 81, 'learning_rate': 0.2067657403659724, 'feature_fraction': 0.897740362101773, 'bagging_fraction': 0.9783984895510337, 'bagging_freq': 5, 'lambda_l1': 6.437768634924736e-05, 'lambda_l2': 4.723296621845035e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9836390817928878, 'min_gain_to_split': 0.04278735382396155}

[I 2025-07-12 05:45:53,361] Trial 401 finished with value: 0.10705412932419096 and parameters: {'num_leaves': 82, 'learning_rate': 0.1836951386964125, 'feature_fraction': 0.9075876397279445, 'bagging_fraction': 0.9620700316705085, 'bagging_freq': 5, 'lambda_l1': 0.00028226203864788505, 'lambda_l2': 5.399489095294388e-07, 'min_child_samples': 24, 'max_depth': 10, 'max_bin': 430, 'min_data_in_leaf': 60, 'extra_trees': False, 'early_stopping_rounds': 18, 'path_smooth': 0.9521152466159273, 'min_gain_to_split': 0.05219344292981812}. Best is trial 371 with value: 0.01917960973943581.

Mejor trial hasta ahora: RMSE=0.019180, Parámetros={'num_leaves': 81, 'learning_rate': 0.2067657403659724, 'feature_fraction': 0.897740362101773, 'bagging_fraction': 0.9783984895510337, 'bagging_freq': 5, 'lambda_l1': 6.437768634924736e-05, 'lambda_l2': 4.723296621845035e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9836390817928878, 'min_gain_to_split': 0.04278735382396155}

[I 2025-07-12 05:54:49,111] Trial 402 finished with value: 0.3929591185220154 and parameters: {'num_leaves': 84, 'learning_rate': 0.19447665817223508, 'feature_fraction': 0.8963142161240395, 'bagging_fraction': 0.9516998371591261, 'bagging_freq': 5, 'lambda_l1': 0.00016053649022681498, 'lambda_l2': 7.279697605942279e-07, 'min_child_samples': 25, 'max_depth': 10, 'max_bin': 426, 'min_data_in_leaf': 82, 'extra_trees': False, 'early_stopping_rounds': 21, 'path_smooth': 0.553749378201494, 'min_gain_to_split': 0.05587300136939762}. Best is trial 371 with value: 0.01917960973943581.

Mejor trial hasta ahora: RMSE=0.019180, Parámetros={'num_leaves': 81, 'learning_rate': 0.2067657403659724, 'feature_fraction': 0.897740362101773, 'bagging_fraction': 0.9783984895510337, 'bagging_freq': 5, 'lambda_l1': 6.437768634924736e-05, 'lambda_l2': 4.723296621845035e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9836390817928878, 'min_gain_to_split': 0.04278735382396155}

[I 2025-07-12 05:59:08,204] Trial 403 finished with value: 0.6698827786311119 and parameters: {'num_leaves': 78, 'learning_rate': 0.16970990714297943, 'feature_fraction': 0.8869208753643492, 'bagging_fraction': 0.9724818924613646, 'bagging_freq': 5, 'lambda_l1': 0.0003056525621829234, 'lambda_l2': 5.478337335971812e-07, 'min_child_samples': 28, 'max_depth': 10, 'max_bin': 439, 'min_data_in_leaf': 33, 'extra_trees': True, 'early_stopping_rounds': 20, 'path_smooth': 0.28470692959359944, 'min_gain_to_split': 0.058014309807431934}. Best is trial 371 with value: 0.01917960973943581.

Mejor trial hasta ahora: RMSE=0.019180, Parámetros={'num_leaves': 81, 'learning_rate': 0.2067657403659724, 'feature_fraction': 0.897740362101773, 'bagging_fraction': 0.9783984895510337, 'bagging_freq': 5, 'lambda_l1': 6.437768634924736e-05, 'lambda_l2': 4.723296621845035e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9836390817928878, 'min_gain_to_split': 0.04278735382396155}

[I 2025-07-12 06:09:22,065] Trial 404 finished with value: 0.1343861889478837 and parameters: {'num_leaves': 87, 'learning_rate': 0.19372681315870813, 'feature_fraction': 0.9065565857535606, 'bagging_fraction': 0.9582524494230512, 'bagging_freq': 5, 'lambda_l1': 0.0004800231726881052, 'lambda_l2': 3.361994828323294e-07, 'min_child_samples': 26, 'max_depth': 10, 'max_bin': 429, 'min_data_in_leaf': 30, 'extra_trees': False, 'early_stopping_rounds': 19, 'path_smooth': 0.31684990625334686, 'min_gain_to_split': 0.07170347390733461}. Best is trial 371 with value: 0.01917960973943581.

Mejor trial hasta ahora: RMSE=0.019180, Parámetros={'num_leaves': 81, 'learning_rate': 0.2067657403659724, 'feature_fraction': 0.897740362101773, 'bagging_fraction': 0.9783984895510337, 'bagging_freq': 5, 'lambda_l1': 6.437768634924736e-05, 'lambda_l2': 4.723296621845035e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9836390817928878, 'min_gain_to_split': 0.04278735382396155}

[I 2025-07-12 07:31:58,287] Trial 405 finished with value: 0.2799224918974598 and parameters: {'num_leaves': 80, 'learning_rate': 0.15781352313928554, 'feature_fraction': 0.9112797601494925, 'bagging_fraction': 0.9404916683398014, 'bagging_freq': 5, 'lambda_l1': 0.00022197023688186915, 'lambda_l2': 2.1984530481001905e-07, 'min_child_samples': 27, 'max_depth': 10, 'max_bin': 412, 'min_data_in_leaf': 100, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.9775964490639809, 'min_gain_to_split': 0.04499751539266529}. Best is trial 371 with value: 0.01917960973943581.

Mejor trial hasta ahora: RMSE=0.019180, Parámetros={'num_leaves': 81, 'learning_rate': 0.2067657403659724, 'feature_fraction': 0.897740362101773, 'bagging_fraction': 0.9783984895510337, 'bagging_freq': 5, 'lambda_l1': 6.437768634924736e-05, 'lambda_l2': 4.723296621845035e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9836390817928878, 'min_gain_to_split': 0.04278735382396155}

[I 2025-07-12 07:42:39,182] Trial 406 finished with value: 0.16103977903742156 and parameters: {'num_leaves': 81, 'learning_rate': 0.20723724095244792, 'feature_fraction': 0.8920169930675031, 'bagging_fraction': 0.9775449370516909, 'bagging_freq': 5, 'lambda_l1': 8.065699535283965e-05, 'lambda_l2': 3.2212246424546694e-07, 'min_child_samples': 28, 'max_depth': 10, 'max_bin': 420, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 18, 'path_smooth': 0.521567821189433, 'min_gain_to_split': 0.05166100977521586}. Best is trial 371 with value: 0.01917960973943581.

Mejor trial hasta ahora: RMSE=0.019180, Parámetros={'num_leaves': 81, 'learning_rate': 0.2067657403659724, 'feature_fraction': 0.897740362101773, 'bagging_fraction': 0.9783984895510337, 'bagging_freq': 5, 'lambda_l1': 6.437768634924736e-05, 'lambda_l2': 4.723296621845035e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9836390817928878, 'min_gain_to_split': 0.04278735382396155}

[I 2025-07-12 07:55:53,854] Trial 407 finished with value: 0.09275166640938816 and parameters: {'num_leaves': 85, 'learning_rate': 0.1789058916046668, 'feature_fraction': 0.9045664969099667, 'bagging_fraction': 0.9683189119154026, 'bagging_freq': 5, 'lambda_l1': 0.00010569418747430342, 'lambda_l2': 5.44055542538147e-07, 'min_child_samples': 25, 'max_depth': 10, 'max_bin': 451, 'min_data_in_leaf': 35, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.9448485876523793, 'min_gain_to_split': 0.04169023849165398}. Best is trial 371 with value: 0.01917960973943581.

Mejor trial hasta ahora: RMSE=0.019180, Parámetros={'num_leaves': 81, 'learning_rate': 0.2067657403659724, 'feature_fraction': 0.897740362101773, 'bagging_fraction': 0.9783984895510337, 'bagging_freq': 5, 'lambda_l1': 6.437768634924736e-05, 'lambda_l2': 4.723296621845035e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9836390817928878, 'min_gain_to_split': 0.04278735382396155}

[I 2025-07-12 08:05:37,630] Trial 408 finished with value: 0.14398010152918536 and parameters: {'num_leaves': 77, 'learning_rate': 0.2015288784159497, 'feature_fraction': 0.914691491639877, 'bagging_fraction': 0.9763628373462314, 'bagging_freq': 5, 'lambda_l1': 0.00013396811755850028, 'lambda_l2': 7.977122314445525e-07, 'min_child_samples': 26, 'max_depth': 10, 'max_bin': 403, 'min_data_in_leaf': 31, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.387603066666123, 'min_gain_to_split': 0.07636560808295406}. Best is trial 371 with value: 0.01917960973943581.

Mejor trial hasta ahora: RMSE=0.019180, Parámetros={'num_leaves': 81, 'learning_rate': 0.2067657403659724, 'feature_fraction': 0.897740362101773, 'bagging_fraction': 0.9783984895510337, 'bagging_freq': 5, 'lambda_l1': 6.437768634924736e-05, 'lambda_l2': 4.723296621845035e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9836390817928878, 'min_gain_to_split': 0.04278735382396155}

[I 2025-07-12 08:19:06,924] Trial 409 finished with value: 0.25599403341655264 and parameters: {'num_leaves': 88, 'learning_rate': 0.12465783676747627, 'feature_fraction': 0.9145954974812809, 'bagging_fraction': 0.9794320444179475, 'bagging_freq': 5, 'lambda_l1': 0.0002476440776514929, 'lambda_l2': 1.816903982927417e-05, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 447, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9634174893223533, 'min_gain_to_split': 0.08341883594246774}. Best is trial 371 with value: 0.01917960973943581.

Mejor trial hasta ahora: RMSE=0.019180, Parámetros={'num_leaves': 81, 'learning_rate': 0.2067657403659724, 'feature_fraction': 0.897740362101773, 'bagging_fraction': 0.9783984895510337, 'bagging_freq': 5, 'lambda_l1': 6.437768634924736e-05, 'lambda_l2': 4.723296621845035e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9836390817928878, 'min_gain_to_split': 0.04278735382396155}

[I 2025-07-12 08:28:53,797] Trial 410 finished with value: 0.09927724358450787 and parameters: {'num_leaves': 83, 'learning_rate': 0.22534804457189414, 'feature_fraction': 0.9021454498661102, 'bagging_fraction': 0.989028121366285, 'bagging_freq': 5, 'lambda_l1': 0.00012554682435128836, 'lambda_l2': 8.138571215647813e-08, 'min_child_samples': 27, 'max_depth': 10, 'max_bin': 442, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.25399434953329364, 'min_gain_to_split': 0.06461781813939947}. Best is trial 371 with value: 0.01917960973943581.

Mejor trial hasta ahora: RMSE=0.019180, Parámetros={'num_leaves': 81, 'learning_rate': 0.2067657403659724, 'feature_fraction': 0.897740362101773, 'bagging_fraction': 0.9783984895510337, 'bagging_freq': 5, 'lambda_l1': 6.437768634924736e-05, 'lambda_l2': 4.723296621845035e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9836390817928878, 'min_gain_to_split': 0.04278735382396155}

[I 2025-07-12 08:39:57,640] Trial 411 finished with value: 0.17044097881185913 and parameters: {'num_leaves': 79, 'learning_rate': 0.20943335415422745, 'feature_fraction': 0.7148766466587041, 'bagging_fraction': 0.9697951810472383, 'bagging_freq': 6, 'lambda_l1': 4.553238520992719e-05, 'lambda_l2': 3.398083778488817e-07, 'min_child_samples': 28, 'max_depth': 10, 'max_bin': 475, 'min_data_in_leaf': 36, 'extra_trees': False, 'early_stopping_rounds': 21, 'path_smooth': 0.4620053445505698, 'min_gain_to_split': 0.03590846612698408}. Best is trial 371 with value: 0.01917960973943581.

Mejor trial hasta ahora: RMSE=0.019180, Parámetros={'num_leaves': 81, 'learning_rate': 0.2067657403659724, 'feature_fraction': 0.897740362101773, 'bagging_fraction': 0.9783984895510337, 'bagging_freq': 5, 'lambda_l1': 6.437768634924736e-05, 'lambda_l2': 4.723296621845035e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9836390817928878, 'min_gain_to_split': 0.04278735382396155}

[I 2025-07-12 08:52:01,621] Trial 412 finished with value: 0.1611317676006899 and parameters: {'num_leaves': 55, 'learning_rate': 0.2381670409220604, 'feature_fraction': 0.8917433908028537, 'bagging_fraction': 0.9821795456802659, 'bagging_freq': 5, 'lambda_l1': 0.0004998637161975226, 'lambda_l2': 7.407508012698934e-07, 'min_child_samples': 44, 'max_depth': 10, 'max_bin': 455, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.6346839927459844, 'min_gain_to_split': 0.02067620982839992}. Best is trial 371 with value: 0.01917960973943581.

Mejor trial hasta ahora: RMSE=0.019180, Parámetros={'num_leaves': 81, 'learning_rate': 0.2067657403659724, 'feature_fraction': 0.897740362101773, 'bagging_fraction': 0.9783984895510337, 'bagging_freq': 5, 'lambda_l1': 6.437768634924736e-05, 'lambda_l2': 4.723296621845035e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9836390817928878, 'min_gain_to_split': 0.04278735382396155}

[I 2025-07-12 09:03:34,955] Trial 413 finished with value: 0.152813391636695 and parameters: {'num_leaves': 81, 'learning_rate': 0.18731784351039835, 'feature_fraction': 0.8793610808826847, 'bagging_fraction': 0.9555959390903178, 'bagging_freq': 6, 'lambda_l1': 1.1778563011670476e-05, 'lambda_l2': 2.228645597002139e-08, 'min_child_samples': 49, 'max_depth': 10, 'max_bin': 434, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9774813821816271, 'min_gain_to_split': 0.047622245296360825}. Best is trial 371 with value: 0.01917960973943581.

Mejor trial hasta ahora: RMSE=0.019180, Parámetros={'num_leaves': 81, 'learning_rate': 0.2067657403659724, 'feature_fraction': 0.897740362101773, 'bagging_fraction': 0.9783984895510337, 'bagging_freq': 5, 'lambda_l1': 6.437768634924736e-05, 'lambda_l2': 4.723296621845035e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9836390817928878, 'min_gain_to_split': 0.04278735382396155}

[I 2025-07-12 09:10:26,710] Trial 414 finished with value: 0.09788653565321397 and parameters: {'num_leaves': 78, 'learning_rate': 0.22683690327397057, 'feature_fraction': 0.920851980873241, 'bagging_fraction': 0.9901405751104323, 'bagging_freq': 5, 'lambda_l1': 0.00016928014836361594, 'lambda_l2': 4.444921750770665e-07, 'min_child_samples': 27, 'max_depth': 10, 'max_bin': 287, 'min_data_in_leaf': 35, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.2066966512629767, 'min_gain_to_split': 0.09259071993846127}. Best is trial 371 with value: 0.01917960973943581.

Mejor trial hasta ahora: RMSE=0.019180, Parámetros={'num_leaves': 81, 'learning_rate': 0.2067657403659724, 'feature_fraction': 0.897740362101773, 'bagging_fraction': 0.9783984895510337, 'bagging_freq': 5, 'lambda_l1': 6.437768634924736e-05, 'lambda_l2': 4.723296621845035e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9836390817928878, 'min_gain_to_split': 0.04278735382396155}

[I 2025-07-12 09:16:31,834] Trial 415 finished with value: 0.24461809811727592 and parameters: {'num_leaves': 86, 'learning_rate': 0.24464778684359248, 'feature_fraction': 0.9115064371106488, 'bagging_fraction': 0.9729758483945598, 'bagging_freq': 5, 'lambda_l1': 2.2655365206596124e-05, 'lambda_l2': 1.3468344879105833e-05, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 30, 'extra_trees': False, 'early_stopping_rounds': 20, 'path_smooth': 0.40321475188428174, 'min_gain_to_split': 0.26766916447609096}. Best is trial 371 with value: 0.01917960973943581.

Mejor trial hasta ahora: RMSE=0.019180, Parámetros={'num_leaves': 81, 'learning_rate': 0.2067657403659724, 'feature_fraction': 0.897740362101773, 'bagging_fraction': 0.9783984895510337, 'bagging_freq': 5, 'lambda_l1': 6.437768634924736e-05, 'lambda_l2': 4.723296621845035e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9836390817928878, 'min_gain_to_split': 0.04278735382396155}

[I 2025-07-12 09:26:23,407] Trial 416 finished with value: 0.491327957252994 and parameters: {'num_leaves': 83, 'learning_rate': 0.2043299071432917, 'feature_fraction': 0.9031980509794656, 'bagging_fraction': 0.7803017480618893, 'bagging_freq': 5, 'lambda_l1': 8.90629244991782e-05, 'lambda_l2': 2.5769144708548024e-06, 'min_child_samples': 30, 'max_depth': 9, 'max_bin': 398, 'min_data_in_leaf': 31, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.9445469841001706, 'min_gain_to_split': 0.025348341695755006}. Best is trial 371 with value: 0.01917960973943581.

Mejor trial hasta ahora: RMSE=0.019180, Parámetros={'num_leaves': 81, 'learning_rate': 0.2067657403659724, 'feature_fraction': 0.897740362101773, 'bagging_fraction': 0.9783984895510337, 'bagging_freq': 5, 'lambda_l1': 6.437768634924736e-05, 'lambda_l2': 4.723296621845035e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9836390817928878, 'min_gain_to_split': 0.04278735382396155}

[I 2025-07-12 09:38:39,304] Trial 417 finished with value: 0.2551718250749979 and parameters: {'num_leaves': 76, 'learning_rate': 0.2153560532791946, 'feature_fraction': 0.9218378003460345, 'bagging_fraction': 0.9651349181796407, 'bagging_freq': 6, 'lambda_l1': 7.430129386183962e-06, 'lambda_l2': 1.1426430861751297e-06, 'min_child_samples': 31, 'max_depth': 10, 'max_bin': 478, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.9941848805175134, 'min_gain_to_split': 0.03502681719055825}. Best is trial 371 with value: 0.01917960973943581.

Mejor trial hasta ahora: RMSE=0.019180, Parámetros={'num_leaves': 81, 'learning_rate': 0.2067657403659724, 'feature_fraction': 0.897740362101773, 'bagging_fraction': 0.9783984895510337, 'bagging_freq': 5, 'lambda_l1': 6.437768634924736e-05, 'lambda_l2': 4.723296621845035e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9836390817928878, 'min_gain_to_split': 0.04278735382396155}

[I 2025-07-12 09:52:16,050] Trial 418 finished with value: 0.10787254229509355 and parameters: {'num_leaves': 80, 'learning_rate': 0.24871190011637445, 'feature_fraction': 0.9314781300787626, 'bagging_fraction': 0.981011992006284, 'bagging_freq': 5, 'lambda_l1': 3.2718510578466693e-05, 'lambda_l2': 3.939192869129857e-05, 'min_child_samples': 30, 'max_depth': 10, 'max_bin': 483, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 21, 'path_smooth': 0.9735589532723571, 'min_gain_to_split': 0.009847287121439879}. Best is trial 371 with value: 0.01917960973943581.

Mejor trial hasta ahora: RMSE=0.019180, Parámetros={'num_leaves': 81, 'learning_rate': 0.2067657403659724, 'feature_fraction': 0.897740362101773, 'bagging_fraction': 0.9783984895510337, 'bagging_freq': 5, 'lambda_l1': 6.437768634924736e-05, 'lambda_l2': 4.723296621845035e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9836390817928878, 'min_gain_to_split': 0.04278735382396155}

[I 2025-07-12 10:02:58,424] Trial 419 finished with value: 0.3030252188610813 and parameters: {'num_leaves': 89, 'learning_rate': 0.17692009577389084, 'feature_fraction': 0.8966992391422336, 'bagging_fraction': 0.9913785336116377, 'bagging_freq': 5, 'lambda_l1': 5.8578399875021334e-05, 'lambda_l2': 0.5308730438584816, 'min_child_samples': 29, 'max_depth': 9, 'max_bin': 442, 'min_data_in_leaf': 36, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.998829211004776, 'min_gain_to_split': 0.05820393658802439}. Best is trial 371 with value: 0.01917960973943581.

Mejor trial hasta ahora: RMSE=0.019180, Parámetros={'num_leaves': 81, 'learning_rate': 0.2067657403659724, 'feature_fraction': 0.897740362101773, 'bagging_fraction': 0.9783984895510337, 'bagging_freq': 5, 'lambda_l1': 6.437768634924736e-05, 'lambda_l2': 4.723296621845035e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9836390817928878, 'min_gain_to_split': 0.04278735382396155}

[I 2025-07-12 10:16:07,313] Trial 420 finished with value: 0.29201634137121574 and parameters: {'num_leaves': 82, 'learning_rate': 0.227143349237452, 'feature_fraction': 0.9160951960154565, 'bagging_fraction': 0.9761069102212239, 'bagging_freq': 10, 'lambda_l1': 1.055328993912688e-05, 'lambda_l2': 7.199872423617586e-06, 'min_child_samples': 30, 'max_depth': 10, 'max_bin': 471, 'min_data_in_leaf': 27, 'extra_trees': False, 'early_stopping_rounds': 28, 'path_smooth': 0.9534435639864683, 'min_gain_to_split': 0.0172848217320848}. Best is trial 371 with value: 0.01917960973943581.

Mejor trial hasta ahora: RMSE=0.019180, Parámetros={'num_leaves': 81, 'learning_rate': 0.2067657403659724, 'feature_fraction': 0.897740362101773, 'bagging_fraction': 0.9783984895510337, 'bagging_freq': 5, 'lambda_l1': 6.437768634924736e-05, 'lambda_l2': 4.723296621845035e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9836390817928878, 'min_gain_to_split': 0.04278735382396155}

[I 2025-07-12 10:49:26,854] Trial 421 finished with value: 0.49700976781221307 and parameters: {'num_leaves': 85, 'learning_rate': 0.04737111817811871, 'feature_fraction': 0.9730638296736132, 'bagging_fraction': 0.9869199190119768, 'bagging_freq': 5, 'lambda_l1': 1.4251696452175481e-05, 'lambda_l2': 1.869104692989137e-06, 'min_child_samples': 31, 'max_depth': 10, 'max_bin': 492, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.9343715304632452, 'min_gain_to_split': 0.030274242687886182}. Best is trial 371 with value: 0.01917960973943581.

Mejor trial hasta ahora: RMSE=0.019180, Parámetros={'num_leaves': 81, 'learning_rate': 0.2067657403659724, 'feature_fraction': 0.897740362101773, 'bagging_fraction': 0.9783984895510337, 'bagging_freq': 5, 'lambda_l1': 6.437768634924736e-05, 'lambda_l2': 4.723296621845035e-06, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9836390817928878, 'min_gain_to_split': 0.04278735382396155}
Estudio guardado en: sqlite:///optuna_studies_v20.db

Mejores hiperparámetros encontrados:
num_leaves: 81
learning_rate: 0.2067657403659724
feature_fraction: 0.897740362101773
bagging_fraction: 0.9783984895510337
bagging_freq: 5
lambda_l1: 6.437768634924736e-05
lambda_l2: 4.723296621845035e-06
min_child_samples: 29
max_depth: 10
max_bin: 465
min_data_in_leaf: 28
extra_trees: False
early_stopping_rounds: 24
path_smooth: 0.9836390817928878
min_gain_to_split: 0.04278735382396155

(<optuna.study.study.Study at 0x27185e765d0>,
 {'num_leaves': 81,
  'learning_rate': 0.2067657403659724,
  'feature_fraction': 0.897740362101773,
  'bagging_fraction': 0.9783984895510337,
  'bagging_freq': 5,
  'lambda_l1': 6.437768634924736e-05,
  'lambda_l2': 4.723296621845035e-06,
  'min_child_samples': 29,
  'max_depth': 10,
  'max_bin': 465,
  'min_data_in_leaf': 28,
  'extra_trees': False,
  'early_stopping_rounds': 24,
  'path_smooth': 0.9836390817928878,
  'min_gain_to_split': 0.04278735382396155,
  'objective': 'regression',
  'metric': 'rmse',
  'boosting_type': 'gbdt',
  'verbosity': -1})

Prediccion

In [22]:
df_future = model_lgb.semillerio_en_prediccion_con_pesos(train, test, version="v20")

In [23]:
df_future

       periodo  product_id  target      pred
30476   201912       20001     0.0  0.492389
30477   201912       20002     0.0  0.257005
30478   201912       20003     0.0 -0.084902
30479   201912       20004     0.0  0.067027
30480   201912       20005     0.0  0.520183
...        ...         ...     ...       ...
31357   201912       21265     0.0  0.055806
31358   201912       21266     0.0  0.002210
31359   201912       21267     0.0 -0.173355
31360   201912       21271     0.0  0.038051
31361   201912       21276     0.0 -0.121066

[886 rows x 4 columns]

Filtramos los 180 productos

In [24]:
productos_ok = pd.read_csv("https://storage.googleapis.com/open-courses/austral2025-af91/labo3v/product_id_apredecir201912.txt", sep="\t")
df_future = df_future[df_future['periodo'] == 201912]
df_future = df_future[df_future['product_id'].isin(productos_ok['product_id'].unique())]

In [25]:
df_future

       periodo  product_id  target      pred
30476   201912       20001     0.0  0.492389
30477   201912       20002     0.0  0.257005
30478   201912       20003     0.0 -0.084902
30479   201912       20004     0.0  0.067027
30480   201912       20005     0.0  0.520183
...        ...         ...     ...       ...
31355   201912       21263     0.0 -0.171320
31357   201912       21265     0.0  0.055806
31358   201912       21266     0.0  0.002210
31359   201912       21267     0.0 -0.173355
31361   201912       21276     0.0 -0.121066

[780 rows x 4 columns]

In [26]:
df_future_copy = df_future.copy()

In [27]:
import os
ruta_archivo = f'./datasets/tn_stats_201912.csv'
    
df_stats = pd.DataFrame()

if os.path.exists(ruta_archivo) and ruta_archivo.endswith('.csv'):
    df_stats = pd.read_csv(ruta_archivo, sep=',')

df_stats

      product_id      tn_mean      tn_std
0          20001  1398.344322  293.975388
1          20002  1009.368178  299.585187
2          20003   889.004243  287.951952
3          20004   671.615383  221.310769
4          20005   644.200514  215.220300
...          ...          ...         ...
1159       21271     0.024268    0.019484
1160       21273     0.057242    0.124272
1161       21274     0.067028    0.096980
1162       21276     0.045447    0.041380
1163       21281     0.021060    0.031414

[1164 rows x 3 columns]

In [28]:
df_future_copy = df_future_copy.merge(df_stats, on=['product_id'], how='left')
df_future_copy

     periodo  product_id  target      pred      tn_mean      tn_std
0     201912       20001     0.0  0.492389  1398.344322  293.975388
1     201912       20002     0.0  0.257005  1009.368178  299.585187
2     201912       20003     0.0 -0.084902   889.004243  287.951952
3     201912       20004     0.0  0.067027   671.615383  221.310769
4     201912       20005     0.0  0.520183   644.200514  215.220300
..       ...         ...     ...       ...          ...         ...
775   201912       21263     0.0 -0.171320     0.089233    0.148180
776   201912       21265     0.0  0.055806     0.089541    0.103219
777   201912       21266     0.0  0.002210     0.094659    0.100530
778   201912       21267     0.0 -0.173355     0.092835    0.075836
779   201912       21276     0.0 -0.121066     0.045447    0.041380

[780 rows x 6 columns]

In [29]:
df_future_copy['tn'] = df_future_copy['pred'] * df_future_copy['tn_std'] + df_future_copy['tn_mean']
df_future_copy

,periodo,product_id,target,pred,tn_mean,tn_std,tn
0,201912,20001,0.0,0.492389,1398.344322,293.975388,1543.094708
1,201912,20002,0.0,0.257005,1009.368178,299.585187,1086.362960
2,201912,20003,0.0,-0.084902,889.004243,287.951952,864.556542
3,201912,20004,0.0,0.067027,671.615383,221.310769,686.449089
4,201912,20005,0.0,0.520183,644.200514,215.220300,756.154405
...,...,...,...,...,...,...,...
775,201912,21263,0.0,-0.171320,0.089233,0.148180,0.063847
776,201912,21265,0.0,0.055806,0.089541,0.103219,0.095301
777,201912,21266,0.0,0.002210,0.094659,0.100530,0.094881
778,201912,21267,0.0,-0.173355,0.092835,0.075836,0.079688
779,201912,21276,0.0,-0.121066,0.045447,0.041380,0.040437

Vemos cuantos negativos hay

In [30]:
df_future_copy[df_future_copy['tn'] < 0]

Empty DataFrame
Columns: [periodo, product_id, target, pred, tn_mean, tn_std, tn]
Index: []

Reemplazamos los negativos por el promedio de ultimos 12 meses

In [ ]:
# promedio780 = model_lgb.promedio_12_meses_780p()
# df_future = df_future.merge(promedio780, on='product_id', how='left')
# df_future.drop(columns=['target','periodo'], inplace=True)
# df_future.loc[df_future['pred'] < 0, 'pred'] = df_future['tn']
# df_future

     product_id         pred           tn
0         20001  1397.305481  1454.732720
1         20002  1086.538942  1175.437142
2         20003   747.163659   784.976407
3         20004   565.799872   627.215328
4         20005   638.965713   668.270104
..          ...          ...          ...
775       21263     0.029993     0.029993
776       21265     0.791975     0.089541
777       21266     0.094659     0.094659
778       21267     0.092835     0.092835
779       21276     0.045447     0.045447

[780 rows x 3 columns]

Guardamos el archivo

In [31]:
# df_future_copy.drop(columns=['tn'], inplace=True)
# df_future_copy.rename(columns={'pred': 'tn'}, inplace=True)
df_future_copy[['product_id', 'tn']].to_csv("./outputs/predicciones_exp_07_lgb_v8_semicompleto.csv", index=False, sep=',')

Ensemble

In [32]:
df_lgb = df_future_copy[['product_id', 'tn']].rename(columns={'tn': 'tn_lgb'})
df_rl = pd.read_csv("./outputs/predicciones_regresion_lineal_v1.csv", sep=',', encoding='utf-8').rename(columns={'tn': 'tn_rl'})
df_ensemble = df_lgb.merge(df_rl, on='product_id', how='left')
df_ensemble['tn'] = (df_ensemble['tn_lgb'] + df_ensemble['tn_rl']) / 2
df_ensemble[['product_id', 'tn']].to_csv("./outputs/predicciones_exp_07_lgb_v8_ensemble_v2.csv", index=False, sep=',')

In [33]:
df_lgb = df_future_copy[['product_id', 'tn']].rename(columns={'tn': 'tn_lgb'})
df_rl = pd.read_csv("./outputs/predicciones_regresion_lineal_v1.csv", sep=',', encoding='utf-8').rename(columns={'tn': 'tn_rl'})
df_ag = pd.read_csv("./outputs/prediccion_autogluon_2ventanas.csv", sep=',', encoding='utf-8').rename(columns={'tn': 'tn_ag'})
df_ensemble = df_lgb.merge(df_rl, on='product_id', how='left')
df_ensemble = df_ensemble.merge(df_ag, on='product_id', how='left')
df_ensemble['tn'] = (df_ensemble['tn_lgb'] + df_ensemble['tn_rl'] + df_ensemble['tn_ag']) / 3
df_ensemble[['product_id', 'tn']].to_csv("./outputs/predicciones_exp_07_lgb_v8_ensemble_3models_semicompleto.csv", index=False, sep=',')