In [22]:
import pandas as pd
import numpy as np
import importlib
import gc
import sys
import warnings
sys.path.append('./scripts')  
import preprocesamiento
import feature_engineering
import model_lgb
importlib.reload(preprocesamiento)
importlib.reload(model_lgb)
importlib.reload(feature_engineering)
warnings.filterwarnings("ignore")

# Experimento 7: 
- LGBM
- Estandarizacion del target
- Usando funcion entrenamiento: quito semillerio para ir mas rapido sino no termino mas.
- Agrego variables: agrego los ceros que dijo el profesor.
- Pesos: logaritmo
- sqlite:///optuna_studies_v21.db
- Kaggle =

##### Levantamos el dataset con target ya calculado

In [2]:
df = pd.read_csv("./datasets/periodo_x_producto_con_target_transformado_201912.csv", sep=',', encoding='utf-8')
print("Dataset sin transformar tenia esto: (31362, 19)")
df.shape

Dataset sin transformar tenia esto: (31362, 19)

(31362, 35)

In [3]:
columnas_baseline = df.columns.tolist()
columnas_baseline

['product_id',
 'periodo',
 'nacimiento_producto',
 'muerte_producto',
 'mes_n',
 'total_meses',
 'producto_nuevo',
 'ciclo_de_vida_inicial',
 'cat1',
 'cat2',
 'cat3',
 'brand',
 'sku_size',
 'stock_final',
 'tn',
 'plan_precios_cuidados',
 'cust_request_qty',
 'cust_request_tn',
 'target',
 'tn_mean',
 'tn_std',
 'tn_zscore',
 'stock_final_mean',
 'stock_final_std',
 'stock_final_zscore',
 'cust_request_qty_mean',
 'cust_request_qty_std',
 'cust_request_qty_zscore',
 'cust_request_tn_mean',
 'cust_request_tn_std',
 'cust_request_tn_zscore',
 'tn_log',
 'stock_final_log',
 'cust_request_qty_log',
 'cust_request_tn_log']

##### Preprocesamiento a la minima expresión :)

In [4]:
df = feature_engineering.create_category_features_cat1(df)
df = feature_engineering.create_category_features_cat2(df)
df = feature_engineering.create_category_features_cat3(df)

In [5]:
# ##### aplicamos OHE
df = preprocesamiento.aplicarOHE(df)
df.shape

(31362, 187)

### Feature Engineering

##### Neural Prophet

In [6]:
neural_prophet_fe = pd.read_csv("./datasets/features_neuralprophet_completo.csv", sep=',', encoding='utf-8')
neural_prophet_fe['ds'] = pd.to_datetime(neural_prophet_fe['ds'], errors='coerce')
# Versión alternativa más robusta:
neural_prophet_fe['periodo'] = neural_prophet_fe['ds'].apply(
    lambda x: x.year * 100 + x.month if pd.notnull(x) else None
)
neural_prophet_fe = neural_prophet_fe[['periodo', 'product_id', 'trend', "season_yearly", "season_monthly"]]
df = df.merge(neural_prophet_fe, on=['periodo', 'product_id'], how='left')
df.shape

(31362, 190)

##### Prophet

In [7]:
prophet_fe = pd.read_csv("./datasets/prophet_features_tn_zscore.csv", sep=',', encoding='utf-8')
prophet_fe['ds'] = pd.to_datetime(prophet_fe['ds'], errors='coerce')
prophet_fe['periodo'] = prophet_fe['ds'].apply(
    lambda x: x.year * 100 + x.month if pd.notnull(x) else None
)
prophet_fe = prophet_fe[['periodo', 'product_id', 'trend_add', "yearly_add", "additive_terms", 'trend_mult', 'yearly_mult', 'multiplicative_terms']]
df = df.merge(prophet_fe, on=['periodo', 'product_id'], how='left')
df.shape

(31362, 196)

##### FE Moviles

In [8]:
df = feature_engineering.get_lags(df, "tn", 201912)
df = feature_engineering.get_delta_lags(df, "tn", 24)
df = feature_engineering.get_rolling_means(df, "tn", 201912)
df = feature_engineering.get_rolling_stds(df, "tn", 201912)
df = feature_engineering.get_rolling_mins(df, "tn", 201912)
df = feature_engineering.get_rolling_maxs(df, "tn", 201912)
df = feature_engineering.get_rolling_medians(df, "tn", 201912)
df = feature_engineering.get_rolling_skewness(df, "tn", 201912)
df = feature_engineering.get_autocorrelaciones(df, "tn", 201912)
df.shape

(31362, 758)

In [9]:
df = feature_engineering.get_lags(df, "cust_request_qty", 201912)
df = feature_engineering.get_delta_lags(df, "cust_request_qty", 24)
df = feature_engineering.get_rolling_means(df, "cust_request_qty", 201912)
df = feature_engineering.get_rolling_stds(df, "cust_request_qty", 201912)
df = feature_engineering.get_rolling_mins(df, "cust_request_qty", 201912)
df = feature_engineering.get_rolling_maxs(df, "cust_request_qty", 201912)
df.shape

(31362, 1213)

In [10]:
df = feature_engineering.get_lags(df, "stock_final", 201912)
df = feature_engineering.get_delta_lags(df, "stock_final", 24)
df = feature_engineering.get_rolling_means(df, "stock_final", 201912)
df = feature_engineering.get_rolling_stds(df, "stock_final", 201912)
df = feature_engineering.get_rolling_mins(df, "stock_final", 201912)
df = feature_engineering.get_rolling_maxs(df, "stock_final", 201912)
df.shape

(31362, 1668)

Features Diana

In [11]:
df = feature_engineering.calcular_diferencia_con_medias_moviles(df)
df = feature_engineering.calcular_ratios_con_medias_moviles(df)
df.shape

(31362, 1704)

##### FE Moviles sobre otras variables

In [56]:
# #  stock final
# df = feature_engineering.get_lagsEspecificos(df, col='stock_final_zscore')
# df = feature_engineering.get_delta_lags_especificos(df, col='stock_final_zscore')
# df = feature_engineering.get_rolling_means_especificos(df, col='stock_final_zscore')
# df = feature_engineering.get_rolling_stds_especificos(df, col='stock_final_zscore')
# df = feature_engineering.get_rolling_medians_especificos(df, col='stock_final_zscore')
# df = feature_engineering.get_rolling_mins_especificos(df, col='stock_final_zscore')
# df = feature_engineering.get_rolling_maxs_especificos(df, col='stock_final_zscore')
# df = feature_engineering.get_rolling_skewness_especificos(df, col='stock_final_zscore')

#  cust_request_qty
# df = feature_engineering.get_lagsEspecificos(df, col='cust_request_qty')
# df = feature_engineering.get_delta_lags_especificos(df, col='cust_request_qty')
# df = feature_engineering.get_rolling_means_especificos(df, col='cust_request_qty')
# df = feature_engineering.get_rolling_stds_especificos(df, col='cust_request_qty')
# df = feature_engineering.get_rolling_mins_especificos(df, col='cust_request_qty')
# df = feature_engineering.get_rolling_maxs_especificos(df, col='cust_request_qty')
# df = feature_engineering.get_rolling_medians_especificos(df, col='cust_request_qty')
# df = feature_engineering.get_rolling_skewness_especificos(df, col='cust_request_qty')

##### FE Calendario

In [12]:
df = feature_engineering.generar_ids(df)
df = feature_engineering.get_componentesTemporales(df)
df = feature_engineering.get_anomaliasPoliticas(df)
# df = feature_engineering.descomposicion_serie_temporal(df, col='tn')
df.shape

(31362, 1729)

##### FE sobre FE

In [13]:
df = feature_engineering.chatGPT_features_serie(df, "tn")
df = feature_engineering.mes_con_feriado(df)
df.shape

(31362, 1758)

##### Variables Exogenas

In [14]:
df = feature_engineering.get_dolar(df)
df = feature_engineering.get_IPC(df)
df['ipc'] = df['ipc'].str.replace(',', '.').astype(float)
df['dolar'] = df['dolar'].str.replace(',', '.').astype(float)
# df.drop(columns=['ds'], inplace=True)
df.fillna(0, inplace=True) ##### EXPERIMENTAR
df = feature_engineering.correlacion_exogenas(df)
df = feature_engineering.get_mes_receso_escolar(df)
df.shape

(31362, 1761)

##### Nuevas FE

In [15]:
df = feature_engineering.create_ratio_features(df)
df = feature_engineering.enhance_lifecycle_features(df)
# df = feature_engineering.create_category_features(df)
df = feature_engineering.create_regime_features(df)
df = feature_engineering.create_nonlinear_trends(df)
df = feature_engineering.create_temporal_interactions(df)
df = feature_engineering.create_asymmetric_window_features(df)
df = feature_engineering.recomendaciones_deepseek(df)
df = feature_engineering.get_nuevas_features(df)
df.shape

(31362, 1798)

##### Ceros

In [16]:
df = feature_engineering.agregar_ceros_consecutivos_atras(df)
df = feature_engineering.agregar_no_ceros_consecutivos_atras(df)
df = feature_engineering.agregar_ceros_ultimos_n_meses(df, ventanas=[1,2,3,4,5,6,12])
df = feature_engineering.agregar_min_max_ult_n(df, n_list=(1,2,3,4,5,6,12))
df.shape

(31362, 1821)

##### Elimino aquellas que no sirven

In [ ]:
import json
import pandas as pd
import csv

with open("./feature_importance/v19.json") as f:
    data = json.load(f)

# Crear una lista de tuplas (feature, value)
features_values = [(feature, value) for feature, value in data.items()]

# Guardar en un archivo CSV
with open('./feature_importance/v19.csv', 'w', newline='') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow(['feature', 'importance'])  # Escribir el encabezado
    writer.writerows(features_values)      # Escribir los datos

print("Archivo CSV generado exitosamente: features_values.csv")

Archivo CSV generado exitosamente: features_values.csv

In [17]:
importantes = pd.read_csv("./feature_importance/v19.csv", sep=',', encoding='utf-8')
no_importantes = importantes[importantes['importance'] == 0]
no_importantes = no_importantes[~no_importantes['feature'].isin(columnas_baseline)]
no_importantes

                         feature  importance
1103           tn_rolling_std_20         0.0
1104           tn_rolling_std_22         0.0
1105           tn_rolling_std_25         0.0
1106           tn_rolling_std_26         0.0
1107           tn_rolling_std_27         0.0
...                          ...         ...
1781             cat3_Acond Bebe         0.0
1782        tn_rolling_median_25         0.0
1783        tn_rolling_median_24         0.0
1786            tn_rolling_std_1         0.0
1787  stock_final_rolling_min_23         0.0

[682 rows x 2 columns]

In [18]:
cols_a_eliminar = no_importantes.feature.unique()
print(f"Antes de eliminar: {df.shape[1]} columnas")
df = df.drop(columns=cols_a_eliminar, errors='ignore')
print(f"Después de eliminar: {df.shape[1]} columnas")

Antes de eliminar: 1821 columnas
Después de eliminar: 1139 columnas

Eliminar object/categorical columnas

In [19]:
df = df.select_dtypes(exclude=['datetime', 'datetime64', 'object'])

Train Test Split

In [20]:
train = df[df['periodo'] <= 201912]
test = df[df['periodo'] == 201912]

Entrenamiento

In [21]:
model_lgb.optimizar_con_optuna_sin_semillerio_db(train, version="v21", n_trials=500)

Para visualizar los resultados en tiempo real:
1. Abre otra terminal y ejecuta:
   optuna-dashboard sqlite:///optuna_studies_v21.db
2. Abre en tu navegador: http://127.0.0.1:8080/

[I 2025-07-11 12:32:56,635] A new study created in RDB with name: lightgbm_optimization_v21
[I 2025-07-11 12:34:03,389] Trial 0 finished with value: 1.1289816591470523 and parameters: {'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 12:35:10,499] Trial 1 finished with value: 1.5755570118905065 and parameters: {'num_leaves': 41, 'learning_rate': 0.05958389350068958, 'feature_fraction': 0.7727780074568463, 'bagging_fraction': 0.7873687420594125, 'bagging_freq': 7, 'lambda_l1': 1.8007140198129195e-07, 'lambda_l2': 4.258943089524393e-06, 'min_child_samples': 25, 'max_depth': 6, 'max_bin': 414, 'min_data_in_leaf': 36, 'extra_trees': False, 'early_stopping_rounds': 11, 'path_smooth': 0.6075448519014384, 'min_gain_to_split': 0.08526206184364576}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 12:35:55,084] Trial 2 finished with value: 1.2767467101564907 and parameters: {'num_leaves': 20, 'learning_rate': 0.2521267904777921, 'feature_fraction': 0.9862528132298237, 'bagging_fraction': 0.9425192044349383, 'bagging_freq': 4, 'lambda_l1': 7.569183361880229e-08, 'lambda_l2': 0.014391207615728067, 'min_child_samples': 28, 'max_depth': 3, 'max_bin': 298, 'min_data_in_leaf': 22, 'extra_trees': True, 'early_stopping_rounds': 37, 'path_smooth': 0.31171107608941095, 'min_gain_to_split': 0.2600340105889054}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 12:36:50,533] Trial 3 finished with value: 1.5455380132953072 and parameters: {'num_leaves': 62, 'learning_rate': 0.01875220945578641, 'feature_fraction': 0.9878338511058234, 'bagging_fraction': 0.9325398470083344, 'bagging_freq': 10, 'lambda_l1': 1.1309571585271483, 'lambda_l2': 0.002404915432737351, 'min_child_samples': 47, 'max_depth': 3, 'max_bin': 178, 'min_data_in_leaf': 23, 'extra_trees': False, 'early_stopping_rounds': 21, 'path_smooth': 0.8287375091519293, 'min_gain_to_split': 0.17837666334679464}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 12:37:37,959] Trial 4 finished with value: 1.5501601764368975 and parameters: {'num_leaves': 39, 'learning_rate': 0.06333268775321843, 'feature_fraction': 0.6563696899899051, 'bagging_fraction': 0.9406590942262119, 'bagging_freq': 1, 'lambda_l1': 7.620481786158549, 'lambda_l2': 0.08916674715636537, 'min_child_samples': 18, 'max_depth': 3, 'max_bin': 427, 'min_data_in_leaf': 77, 'extra_trees': False, 'early_stopping_rounds': 13, 'path_smooth': 0.3584657285442726, 'min_gain_to_split': 0.05793452976256486}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 12:39:48,933] Trial 5 finished with value: 1.320967830071074 and parameters: {'num_leaves': 89, 'learning_rate': 0.08330803890301997, 'feature_fraction': 0.7323592099410596, 'bagging_fraction': 0.7190675050858071, 'bagging_freq': 4, 'lambda_l1': 8.445977074223802e-06, 'lambda_l2': 0.036851536911881845, 'min_child_samples': 36, 'max_depth': 10, 'max_bin': 289, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 33, 'path_smooth': 0.770967179954561, 'min_gain_to_split': 0.24689779818219537}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 12:40:52,970] Trial 6 finished with value: 1.4840795620468452 and parameters: {'num_leaves': 59, 'learning_rate': 0.042808491617570936, 'feature_fraction': 0.610167650697638, 'bagging_fraction': 0.7323674280979913, 'bagging_freq': 1, 'lambda_l1': 0.005341874754868531, 'lambda_l2': 6.748446817464346e-06, 'min_child_samples': 30, 'max_depth': 10, 'max_bin': 199, 'min_data_in_leaf': 53, 'extra_trees': True, 'early_stopping_rounds': 13, 'path_smooth': 0.289751452913768, 'min_gain_to_split': 0.08061064362700221}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 12:42:34,154] Trial 7 finished with value: 1.5474846112026437 and parameters: {'num_leaves': 94, 'learning_rate': 0.156203869845265, 'feature_fraction': 0.8533615026041694, 'bagging_fraction': 0.9614381770563153, 'bagging_freq': 9, 'lambda_l1': 4.776728196949699e-07, 'lambda_l2': 1.0790237065789294, 'min_child_samples': 32, 'max_depth': 9, 'max_bin': 459, 'min_data_in_leaf': 45, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.8180147659224931, 'min_gain_to_split': 0.4303652916281717}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 12:43:41,599] Trial 8 finished with value: 1.5783282134008199 and parameters: {'num_leaves': 15, 'learning_rate': 0.05681142678077596, 'feature_fraction': 0.7669644012595116, 'bagging_fraction': 0.7666323431412191, 'bagging_freq': 2, 'lambda_l1': 1.0927895733904103e-05, 'lambda_l2': 3.0632845126552133, 'min_child_samples': 23, 'max_depth': 7, 'max_bin': 381, 'min_data_in_leaf': 49, 'extra_trees': True, 'early_stopping_rounds': 20, 'path_smooth': 0.49724850589238545, 'min_gain_to_split': 0.15043915490838483}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 12:44:49,106] Trial 9 finished with value: 1.65423615778233 and parameters: {'num_leaves': 39, 'learning_rate': 0.011336695817840537, 'feature_fraction': 0.8438257335919588, 'bagging_fraction': 0.8508037069686585, 'bagging_freq': 1, 'lambda_l1': 3.21972053981427e-06, 'lambda_l2': 1.49414578394363, 'min_child_samples': 19, 'max_depth': 4, 'max_bin': 296, 'min_data_in_leaf': 99, 'extra_trees': False, 'early_stopping_rounds': 41, 'path_smooth': 0.23763754399239967, 'min_gain_to_split': 0.3641081743059298}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 12:45:49,553] Trial 10 finished with value: 1.2849549154700308 and parameters: {'num_leaves': 81, 'learning_rate': 0.23875379742034003, 'feature_fraction': 0.9198060649701774, 'bagging_fraction': 0.8659028016035462, 'bagging_freq': 4, 'lambda_l1': 0.0007387460530836874, 'lambda_l2': 1.3686680646913219e-08, 'min_child_samples': 50, 'max_depth': 7, 'max_bin': 104, 'min_data_in_leaf': 68, 'extra_trees': True, 'early_stopping_rounds': 47, 'path_smooth': 0.056598765017552566, 'min_gain_to_split': 0.01721008191645282}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 12:46:41,654] Trial 11 finished with value: 1.1740139028805727 and parameters: {'num_leaves': 16, 'learning_rate': 0.29090072068684847, 'feature_fraction': 0.9995614594624898, 'bagging_fraction': 0.8899523871243832, 'bagging_freq': 4, 'lambda_l1': 5.038237681909755e-08, 'lambda_l2': 1.7270812116459777e-08, 'min_child_samples': 41, 'max_depth': 5, 'max_bin': 351, 'min_data_in_leaf': 22, 'extra_trees': True, 'early_stopping_rounds': 36, 'path_smooth': 0.07846238496678071, 'min_gain_to_split': 0.3009682184831003}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 12:47:36,640] Trial 12 finished with value: 1.421300504969762 and parameters: {'num_leaves': 28, 'learning_rate': 0.13396912486123683, 'feature_fraction': 0.9195051166358591, 'bagging_fraction': 0.8895167218891852, 'bagging_freq': 3, 'lambda_l1': 1.6224573274582516e-08, 'lambda_l2': 1.31299430222377e-08, 'min_child_samples': 41, 'max_depth': 5, 'max_bin': 357, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 27, 'path_smooth': 0.0801463875192891, 'min_gain_to_split': 0.3054737816916923}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 12:48:32,444] Trial 13 finished with value: 1.2831528537931243 and parameters: {'num_leaves': 72, 'learning_rate': 0.297230248560765, 'feature_fraction': 0.9178581456448356, 'bagging_fraction': 0.8121933117224753, 'bagging_freq': 6, 'lambda_l1': 0.00010715070780083933, 'lambda_l2': 8.964365911538218e-07, 'min_child_samples': 10, 'max_depth': 8, 'max_bin': 487, 'min_data_in_leaf': 20, 'extra_trees': True, 'early_stopping_rounds': 50, 'path_smooth': 0.0036987682420707435, 'min_gain_to_split': 0.4734024632067818}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 12:49:28,132] Trial 14 finished with value: 1.4936269933524824 and parameters: {'num_leaves': 46, 'learning_rate': 0.14039368806060168, 'feature_fraction': 0.8666142557230876, 'bagging_fraction': 0.9009312770749308, 'bagging_freq': 6, 'lambda_l1': 1.601043042488262e-08, 'lambda_l2': 2.4637944791127676e-07, 'min_child_samples': 42, 'max_depth': 5, 'max_bin': 351, 'min_data_in_leaf': 36, 'extra_trees': True, 'early_stopping_rounds': 21, 'path_smooth': 0.17533680985174965, 'min_gain_to_split': 0.1671876770805229}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 12:50:11,489] Trial 15 finished with value: 1.5514234185414923 and parameters: {'num_leaves': 28, 'learning_rate': 0.18220318158347246, 'feature_fraction': 0.9454610497262719, 'bagging_fraction': 0.9889458246924632, 'bagging_freq': 3, 'lambda_l1': 1.100862060501112e-06, 'lambda_l2': 7.674363555969651e-05, 'min_child_samples': 42, 'max_depth': 6, 'max_bin': 235, 'min_data_in_leaf': 66, 'extra_trees': True, 'early_stopping_rounds': 40, 'path_smooth': 0.4536605357502874, 'min_gain_to_split': 0.3608688908031164}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 12:51:16,883] Trial 16 finished with value: 1.3272270229155114 and parameters: {'num_leaves': 52, 'learning_rate': 0.0917740313331887, 'feature_fraction': 0.9984901537620982, 'bagging_fraction': 0.8297521980629978, 'bagging_freq': 5, 'lambda_l1': 0.03141951598789899, 'lambda_l2': 1.0497079540154665e-07, 'min_child_samples': 37, 'max_depth': 8, 'max_bin': 342, 'min_data_in_leaf': 86, 'extra_trees': True, 'early_stopping_rounds': 32, 'path_smooth': 0.9734291410284922, 'min_gain_to_split': 0.22527845467350988}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 12:52:31,960] Trial 17 finished with value: 1.5402541826418674 and parameters: {'num_leaves': 69, 'learning_rate': 0.030147309977275976, 'feature_fraction': 0.8251323334561256, 'bagging_fraction': 0.8976369323205313, 'bagging_freq': 3, 'lambda_l1': 8.306630840098401e-05, 'lambda_l2': 0.00014593568357602004, 'min_child_samples': 47, 'max_depth': 5, 'max_bin': 407, 'min_data_in_leaf': 42, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.1524881585046796, 'min_gain_to_split': 0.3315751931095466}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 12:53:24,291] Trial 18 finished with value: 1.451295770122639 and parameters: {'num_leaves': 29, 'learning_rate': 0.10787862331013662, 'feature_fraction': 0.8868966470660125, 'bagging_fraction': 0.8640962143968572, 'bagging_freq': 8, 'lambda_l1': 1.0209699332115752e-07, 'lambda_l2': 1.5927111084655748e-05, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 251, 'min_data_in_leaf': 55, 'extra_trees': True, 'early_stopping_rounds': 26, 'path_smooth': 0.38992563832047583, 'min_gain_to_split': 0.39725972845678376}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 12:54:25,430] Trial 19 finished with value: 1.390846722705351 and parameters: {'num_leaves': 52, 'learning_rate': 0.21624414040287293, 'feature_fraction': 0.9345678277672508, 'bagging_fraction': 0.8055689495236655, 'bagging_freq': 2, 'lambda_l1': 1.0121907468277043e-08, 'lambda_l2': 2.348957762343796e-07, 'min_child_samples': 45, 'max_depth': 4, 'max_bin': 326, 'min_data_in_leaf': 29, 'extra_trees': True, 'early_stopping_rounds': 36, 'path_smooth': 0.16973610660115593, 'min_gain_to_split': 0.11799078444667399}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 12:56:08,196] Trial 20 finished with value: 1.5855675397733335 and parameters: {'num_leaves': 33, 'learning_rate': 0.03619655643178413, 'feature_fraction': 0.9591750380569787, 'bagging_fraction': 0.9144572394836572, 'bagging_freq': 5, 'lambda_l1': 2.6370402835993827e-05, 'lambda_l2': 4.896899785314463e-08, 'min_child_samples': 39, 'max_depth': 6, 'max_bin': 456, 'min_data_in_leaf': 30, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.6093939481234154, 'min_gain_to_split': 0.0007852848070882129}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 12:56:58,511] Trial 21 finished with value: 1.2034994218409005 and parameters: {'num_leaves': 15, 'learning_rate': 0.2801590985558207, 'feature_fraction': 0.9739299253824694, 'bagging_fraction': 0.9682127019154457, 'bagging_freq': 4, 'lambda_l1': 1.0894482695054191e-07, 'lambda_l2': 0.001932008976215061, 'min_child_samples': 30, 'max_depth': 4, 'max_bin': 273, 'min_data_in_leaf': 20, 'extra_trees': True, 'early_stopping_rounds': 38, 'path_smooth': 0.28478495439109325, 'min_gain_to_split': 0.29169517495840985}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 12:57:39,828] Trial 22 finished with value: 1.4601092279052394 and parameters: {'num_leaves': 15, 'learning_rate': 0.29528510175635525, 'feature_fraction': 0.8899173707553103, 'bagging_fraction': 0.9989948092002299, 'bagging_freq': 2, 'lambda_l1': 1.1860813769041782e-06, 'lambda_l2': 0.0011489789198387433, 'min_child_samples': 33, 'max_depth': 4, 'max_bin': 261, 'min_data_in_leaf': 27, 'extra_trees': True, 'early_stopping_rounds': 43, 'path_smooth': 0.22992957861532956, 'min_gain_to_split': 0.3083696858007166}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 12:58:32,566] Trial 23 finished with value: 1.3668463005517384 and parameters: {'num_leaves': 20, 'learning_rate': 0.18143718562104943, 'feature_fraction': 0.963249428123241, 'bagging_fraction': 0.9700640927047376, 'bagging_freq': 4, 'lambda_l1': 9.581581908853545e-08, 'lambda_l2': 0.0018981146657836474, 'min_child_samples': 50, 'max_depth': 5, 'max_bin': 384, 'min_data_in_leaf': 20, 'extra_trees': True, 'early_stopping_rounds': 36, 'path_smooth': 0.055695955694737925, 'min_gain_to_split': 0.20734972697977533}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 12:59:24,433] Trial 24 finished with value: 1.3153558491243094 and parameters: {'num_leaves': 23, 'learning_rate': 0.2087726572114949, 'feature_fraction': 0.9612604851657397, 'bagging_fraction': 0.8776407028600179, 'bagging_freq': 5, 'lambda_l1': 6.01314234867389e-07, 'lambda_l2': 1.6076263255450631e-06, 'min_child_samples': 43, 'max_depth': 7, 'max_bin': 325, 'min_data_in_leaf': 40, 'extra_trees': True, 'early_stopping_rounds': 30, 'path_smooth': 0.11494061737779453, 'min_gain_to_split': 0.2755693365094575}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 13:00:17,385] Trial 25 finished with value: 1.3943476956087268 and parameters: {'num_leaves': 31, 'learning_rate': 0.10898245528162961, 'feature_fraction': 0.8977946208721354, 'bagging_fraction': 0.917933630904141, 'bagging_freq': 3, 'lambda_l1': 3.393919865398472e-06, 'lambda_l2': 0.00046142266986074615, 'min_child_samples': 39, 'max_depth': 6, 'max_bin': 209, 'min_data_in_leaf': 33, 'extra_trees': True, 'early_stopping_rounds': 43, 'path_smooth': 0.24347314326542763, 'min_gain_to_split': 0.3002830627528589}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 13:00:56,576] Trial 26 finished with value: 1.3851079234762687 and parameters: {'num_leaves': 46, 'learning_rate': 0.2917508958459953, 'feature_fraction': 0.9998139199102047, 'bagging_fraction': 0.8361527404678437, 'bagging_freq': 7, 'lambda_l1': 9.188065402030682e-08, 'lambda_l2': 3.7425844322818504e-05, 'min_child_samples': 34, 'max_depth': 4, 'max_bin': 146, 'min_data_in_leaf': 24, 'extra_trees': True, 'early_stopping_rounds': 38, 'path_smooth': 0.4167599572194926, 'min_gain_to_split': 0.21403474239243814}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 13:01:44,930] Trial 27 finished with value: 1.3693608882778978 and parameters: {'num_leaves': 23, 'learning_rate': 0.17347703821726915, 'feature_fraction': 0.9673874519887151, 'bagging_fraction': 0.9588746674157779, 'bagging_freq': 2, 'lambda_l1': 0.0004376831503855519, 'lambda_l2': 7.947152837952005e-07, 'min_child_samples': 28, 'max_depth': 5, 'max_bin': 276, 'min_data_in_leaf': 46, 'extra_trees': True, 'early_stopping_rounds': 33, 'path_smooth': 0.0038601476959079645, 'min_gain_to_split': 0.349857717978171}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 13:02:28,449] Trial 28 finished with value: 1.4404233513747793 and parameters: {'num_leaves': 67, 'learning_rate': 0.22112495551239714, 'feature_fraction': 0.796335720531138, 'bagging_fraction': 0.9191721759306203, 'bagging_freq': 4, 'lambda_l1': 2.4872253109416223e-08, 'lambda_l2': 0.17682047643567722, 'min_child_samples': 46, 'max_depth': 4, 'max_bin': 317, 'min_data_in_leaf': 62, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.30139488515982177, 'min_gain_to_split': 0.4054578651141591}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 13:03:25,201] Trial 29 finished with value: 1.8348450062791481 and parameters: {'num_leaves': 33, 'learning_rate': 0.12159183334765294, 'feature_fraction': 0.9318987339271511, 'bagging_fraction': 0.787590462080435, 'bagging_freq': 7, 'lambda_l1': 1.922640565166692e-07, 'lambda_l2': 0.006985917256731969, 'min_child_samples': 24, 'max_depth': 6, 'max_bin': 385, 'min_data_in_leaf': 40, 'extra_trees': False, 'early_stopping_rounds': 10, 'path_smooth': 0.5593666018484245, 'min_gain_to_split': 0.12113402907359722}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 13:05:28,044] Trial 30 finished with value: 1.4997818737350719 and parameters: {'num_leaves': 44, 'learning_rate': 0.02334434115618033, 'feature_fraction': 0.7413315119267839, 'bagging_fraction': 0.9801531924326798, 'bagging_freq': 6, 'lambda_l1': 3.824316990473455e-07, 'lambda_l2': 5.2346983400388414e-08, 'min_child_samples': 10, 'max_depth': 7, 'max_bin': 423, 'min_data_in_leaf': 32, 'extra_trees': True, 'early_stopping_rounds': 30, 'path_smooth': 0.17632655991602184, 'min_gain_to_split': 0.04590821744788088}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 13:06:17,719] Trial 31 finished with value: 1.4751823047260242 and parameters: {'num_leaves': 20, 'learning_rate': 0.2513735904117689, 'feature_fraction': 0.9858144819267143, 'bagging_fraction': 0.9477652249855929, 'bagging_freq': 4, 'lambda_l1': 5.3322844222159944e-08, 'lambda_l2': 0.012783367666960558, 'min_child_samples': 28, 'max_depth': 3, 'max_bin': 314, 'min_data_in_leaf': 20, 'extra_trees': True, 'early_stopping_rounds': 36, 'path_smooth': 0.29469416826023453, 'min_gain_to_split': 0.2585751174722428}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 13:07:02,053] Trial 32 finished with value: 1.4739102347544022 and parameters: {'num_leaves': 15, 'learning_rate': 0.23931747763218789, 'feature_fraction': 0.9759002605842894, 'bagging_fraction': 0.9301322456260416, 'bagging_freq': 3, 'lambda_l1': 4.2539738703564894e-08, 'lambda_l2': 0.007248342313401176, 'min_child_samples': 27, 'max_depth': 3, 'max_bin': 365, 'min_data_in_leaf': 25, 'extra_trees': True, 'early_stopping_rounds': 46, 'path_smooth': 0.30303680036849695, 'min_gain_to_split': 0.2754014654100501}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 13:07:41,895] Trial 33 finished with value: 1.4797502807443557 and parameters: {'num_leaves': 22, 'learning_rate': 0.18283674438366962, 'feature_fraction': 0.9451378219080803, 'bagging_fraction': 0.9475979440620044, 'bagging_freq': 5, 'lambda_l1': 2.2457733581300918e-07, 'lambda_l2': 0.3792867874210924, 'min_child_samples': 21, 'max_depth': 3, 'max_bin': 232, 'min_data_in_leaf': 24, 'extra_trees': True, 'early_stopping_rounds': 39, 'path_smooth': 0.33309301330168917, 'min_gain_to_split': 0.1955507407972173}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 13:08:42,369] Trial 34 finished with value: 1.596032186274383 and parameters: {'num_leaves': 36, 'learning_rate': 0.08612456956292924, 'feature_fraction': 0.9789623486422246, 'bagging_fraction': 0.8841917393740063, 'bagging_freq': 4, 'lambda_l1': 2.0679377404739304e-06, 'lambda_l2': 0.025213748169263566, 'min_child_samples': 31, 'max_depth': 3, 'max_bin': 283, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 34, 'path_smooth': 0.11565257140914617, 'min_gain_to_split': 0.23909637899892086}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 13:09:25,709] Trial 35 finished with value: 1.4724551739231502 and parameters: {'num_leaves': 26, 'learning_rate': 0.25685470378446273, 'feature_fraction': 0.9005478802753398, 'bagging_fraction': 0.9280645518641344, 'bagging_freq': 1, 'lambda_l1': 0.07414519969112422, 'lambda_l2': 0.0008292447689986118, 'min_child_samples': 15, 'max_depth': 4, 'max_bin': 301, 'min_data_in_leaf': 27, 'extra_trees': True, 'early_stopping_rounds': 37, 'path_smooth': 0.21122868538419576, 'min_gain_to_split': 0.26696173260032924}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 13:10:07,548] Trial 36 finished with value: 1.5954604992522283 and parameters: {'num_leaves': 19, 'learning_rate': 0.15204784216930955, 'feature_fraction': 0.6584848472933433, 'bagging_fraction': 0.9093689712561569, 'bagging_freq': 10, 'lambda_l1': 8.414567778232073e-06, 'lambda_l2': 0.06690501139809629, 'min_child_samples': 26, 'max_depth': 3, 'max_bin': 408, 'min_data_in_leaf': 20, 'extra_trees': False, 'early_stopping_rounds': 42, 'path_smooth': 0.3601235184367711, 'min_gain_to_split': 0.14645308899011983}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 13:11:00,548] Trial 37 finished with value: 1.4549790125899422 and parameters: {'num_leaves': 78, 'learning_rate': 0.20084053898145493, 'feature_fraction': 0.998148517024039, 'bagging_fraction': 0.9380997580211298, 'bagging_freq': 2, 'lambda_l1': 6.087278230819692, 'lambda_l2': 7.1123077095800875e-06, 'min_child_samples': 30, 'max_depth': 9, 'max_bin': 449, 'min_data_in_leaf': 79, 'extra_trees': True, 'early_stopping_rounds': 45, 'path_smooth': 0.5984674681706509, 'min_gain_to_split': 0.3311473088709314}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 13:12:06,161] Trial 38 finished with value: 1.5341326514689608 and parameters: {'num_leaves': 52, 'learning_rate': 0.06607995122618036, 'feature_fraction': 0.8747503052649312, 'bagging_fraction': 0.9688066832402673, 'bagging_freq': 3, 'lambda_l1': 3.3119452926268504e-07, 'lambda_l2': 0.003955120025855143, 'min_child_samples': 22, 'max_depth': 5, 'max_bin': 173, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 31, 'path_smooth': 0.47354274016265024, 'min_gain_to_split': 0.1773626588648825}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 13:12:48,559] Trial 39 finished with value: 1.4547281537077663 and parameters: {'num_leaves': 98, 'learning_rate': 0.15925464978767973, 'feature_fraction': 0.8340618472195901, 'bagging_fraction': 0.8646806903589644, 'bagging_freq': 5, 'lambda_l1': 0.0018502862624037446, 'lambda_l2': 0.00019934952125783698, 'min_child_samples': 35, 'max_depth': 4, 'max_bin': 339, 'min_data_in_leaf': 24, 'extra_trees': True, 'early_stopping_rounds': 14, 'path_smooth': 0.2707267151161186, 'min_gain_to_split': 0.29396161724822123}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 13:13:46,027] Trial 40 finished with value: 1.4516647530265687 and parameters: {'num_leaves': 37, 'learning_rate': 0.06975708260200968, 'feature_fraction': 0.9448633997678564, 'bagging_fraction': 0.8483967160262826, 'bagging_freq': 1, 'lambda_l1': 2.7179874726599322e-05, 'lambda_l2': 2.9684199491127464e-08, 'min_child_samples': 39, 'max_depth': 6, 'max_bin': 268, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 34, 'path_smooth': 0.6939494659267003, 'min_gain_to_split': 0.39251768999436754}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 13:14:36,050] Trial 41 finished with value: 1.2795824918093754 and parameters: {'num_leaves': 79, 'learning_rate': 0.28823749496351964, 'feature_fraction': 0.9187503843813165, 'bagging_fraction': 0.8043048527659507, 'bagging_freq': 6, 'lambda_l1': 0.019799968473449347, 'lambda_l2': 8.694548256584233e-07, 'min_child_samples': 13, 'max_depth': 8, 'max_bin': 490, 'min_data_in_leaf': 20, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.017281298382362524, 'min_gain_to_split': 0.439355160429448}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 13:15:28,215] Trial 42 finished with value: 1.32045239436905 and parameters: {'num_leaves': 80, 'learning_rate': 0.25865430135283474, 'feature_fraction': 0.914914295697677, 'bagging_fraction': 0.7533381282181283, 'bagging_freq': 7, 'lambda_l1': 0.007739036224553872, 'lambda_l2': 9.306998894813363, 'min_child_samples': 44, 'max_depth': 9, 'max_bin': 475, 'min_data_in_leaf': 23, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.10114134814146275, 'min_gain_to_split': 0.4654868117170444}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 13:16:24,035] Trial 43 finished with value: 1.2863608954832564 and parameters: {'num_leaves': 87, 'learning_rate': 0.29866373378393146, 'feature_fraction': 0.9771818523956242, 'bagging_fraction': 0.7944840864990438, 'bagging_freq': 6, 'lambda_l1': 0.08023876724855773, 'lambda_l2': 3.4023342127722265e-07, 'min_child_samples': 17, 'max_depth': 8, 'max_bin': 441, 'min_data_in_leaf': 30, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.049447290509494854, 'min_gain_to_split': 0.4255485794905008}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 13:17:54,258] Trial 44 finished with value: 1.595302385585492 and parameters: {'num_leaves': 59, 'learning_rate': 0.01165841072784702, 'feature_fraction': 0.9533332652268857, 'bagging_fraction': 0.7551540332091311, 'bagging_freq': 8, 'lambda_l1': 3.090208827296896e-08, 'lambda_l2': 1.271924967327017e-08, 'min_child_samples': 12, 'max_depth': 7, 'max_bin': 366, 'min_data_in_leaf': 20, 'extra_trees': True, 'early_stopping_rounds': 19, 'path_smooth': 0.13971209174151794, 'min_gain_to_split': 0.4944085386082771}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 13:18:59,096] Trial 45 finished with value: 1.5404747300820136 and parameters: {'num_leaves': 25, 'learning_rate': 0.049266798528701056, 'feature_fraction': 0.8620916074848963, 'bagging_fraction': 0.8283496742704796, 'bagging_freq': 4, 'lambda_l1': 0.3273373859634143, 'lambda_l2': 1.4066144447864242e-07, 'min_child_samples': 14, 'max_depth': 8, 'max_bin': 491, 'min_data_in_leaf': 26, 'extra_trees': True, 'early_stopping_rounds': 22, 'path_smooth': 5.748633545925308e-05, 'min_gain_to_split': 0.239780089070451}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 13:20:21,036] Trial 46 finished with value: 1.2851933298985596 and parameters: {'num_leaves': 90, 'learning_rate': 0.25390018396686503, 'feature_fraction': 0.9272504456386066, 'bagging_fraction': 0.7702386977535982, 'bagging_freq': 6, 'lambda_l1': 0.008387063379541369, 'lambda_l2': 3.767814981417601e-06, 'min_child_samples': 48, 'max_depth': 9, 'max_bin': 300, 'min_data_in_leaf': 92, 'extra_trees': False, 'early_stopping_rounds': 28, 'path_smooth': 0.19256352529995002, 'min_gain_to_split': 0.3216700230406784}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 13:21:16,882] Trial 47 finished with value: 1.186666133495904 and parameters: {'num_leaves': 63, 'learning_rate': 0.2024534525577278, 'feature_fraction': 0.9095060444372752, 'bagging_fraction': 0.8507733867231243, 'bagging_freq': 5, 'lambda_l1': 5.824130003983842e-07, 'lambda_l2': 3.078649343494023e-08, 'min_child_samples': 21, 'max_depth': 10, 'max_bin': 387, 'min_data_in_leaf': 33, 'extra_trees': True, 'early_stopping_rounds': 17, 'path_smooth': 0.05108884397964539, 'min_gain_to_split': 0.3634587110357547}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 13:22:16,918] Trial 48 finished with value: 1.4238258926866207 and parameters: {'num_leaves': 63, 'learning_rate': 0.1320961942891801, 'feature_fraction': 0.6539801391979497, 'bagging_fraction': 0.8772765907829335, 'bagging_freq': 5, 'lambda_l1': 6.325084726123792e-06, 'lambda_l2': 2.415749855391305e-08, 'min_child_samples': 18, 'max_depth': 10, 'max_bin': 400, 'min_data_in_leaf': 51, 'extra_trees': True, 'early_stopping_rounds': 15, 'path_smooth': 0.07558724181868787, 'min_gain_to_split': 0.376506655564554}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 13:23:04,331] Trial 49 finished with value: 1.2306415816332963 and parameters: {'num_leaves': 74, 'learning_rate': 0.2103573183816805, 'feature_fraction': 0.8443326287693044, 'bagging_fraction': 0.8954624969229511, 'bagging_freq': 3, 'lambda_l1': 8.116002906271821e-07, 'lambda_l2': 0.020642337683516428, 'min_child_samples': 20, 'max_depth': 10, 'max_bin': 351, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 40, 'path_smooth': 0.2565606064437038, 'min_gain_to_split': 0.35163211787533544}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 13:23:54,779] Trial 50 finished with value: 1.482934626721295 and parameters: {'num_leaves': 72, 'learning_rate': 0.20015309797699612, 'feature_fraction': 0.8096600161165114, 'bagging_fraction': 0.8461774289737252, 'bagging_freq': 3, 'lambda_l1': 7.817103337267254e-07, 'lambda_l2': 4.625060946163828e-08, 'min_child_samples': 21, 'max_depth': 10, 'max_bin': 342, 'min_data_in_leaf': 44, 'extra_trees': True, 'early_stopping_rounds': 40, 'path_smooth': 0.26129706207739967, 'min_gain_to_split': 0.35657471261933155}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 13:24:47,075] Trial 51 finished with value: 1.6486122625820285 and parameters: {'num_leaves': 75, 'learning_rate': 0.2241515387511733, 'feature_fraction': 0.8539991491086992, 'bagging_fraction': 0.9004345526475256, 'bagging_freq': 4, 'lambda_l1': 1.349351743336002e-07, 'lambda_l2': 0.0473224235739147, 'min_child_samples': 20, 'max_depth': 10, 'max_bin': 374, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 17, 'path_smooth': 0.367912012139309, 'min_gain_to_split': 0.2823707802664803}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 13:25:31,976] Trial 52 finished with value: 1.4143020960881472 and parameters: {'num_leaves': 18, 'learning_rate': 0.1575800326022221, 'feature_fraction': 0.9055923753036599, 'bagging_fraction': 0.8585397789520641, 'bagging_freq': 4, 'lambda_l1': 1.0114080640172752e-08, 'lambda_l2': 0.02393177436832202, 'min_child_samples': 24, 'max_depth': 10, 'max_bin': 390, 'min_data_in_leaf': 33, 'extra_trees': True, 'early_stopping_rounds': 12, 'path_smooth': 0.42242668364894864, 'min_gain_to_split': 0.3195865038888055}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 13:26:40,670] Trial 53 finished with value: 1.2840776820432462 and parameters: {'num_leaves': 65, 'learning_rate': 0.19786505189534467, 'feature_fraction': 0.8815083787404775, 'bagging_fraction': 0.8954330405884191, 'bagging_freq': 3, 'lambda_l1': 1.9536896334627028e-06, 'lambda_l2': 0.17639024711220688, 'min_child_samples': 30, 'max_depth': 9, 'max_bin': 350, 'min_data_in_leaf': 28, 'extra_trees': True, 'early_stopping_rounds': 49, 'path_smooth': 0.14239294556007637, 'min_gain_to_split': 0.06284001355701319}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 13:27:26,987] Trial 54 finished with value: 1.4386764603669493 and parameters: {'num_leaves': 57, 'learning_rate': 0.2362293960193349, 'feature_fraction': 0.8475331641051452, 'bagging_fraction': 0.8759346665582772, 'bagging_freq': 2, 'lambda_l1': 4.029471446852024e-08, 'lambda_l2': 0.0023900848151732186, 'min_child_samples': 26, 'max_depth': 3, 'max_bin': 247, 'min_data_in_leaf': 23, 'extra_trees': True, 'early_stopping_rounds': 41, 'path_smooth': 0.2103910135193681, 'min_gain_to_split': 0.3412128700132272}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 13:28:19,389] Trial 55 finished with value: 1.5692643726397024 and parameters: {'num_leaves': 57, 'learning_rate': 0.2569946753792494, 'feature_fraction': 0.7799462876965917, 'bagging_fraction': 0.907015286445352, 'bagging_freq': 5, 'lambda_l1': 5.342176462963562e-07, 'lambda_l2': 9.880628884650043e-08, 'min_child_samples': 32, 'max_depth': 4, 'max_bin': 423, 'min_data_in_leaf': 56, 'extra_trees': True, 'early_stopping_rounds': 38, 'path_smooth': 0.9424287245151237, 'min_gain_to_split': 0.3739191021234873}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 13:29:16,469] Trial 56 finished with value: 1.4770536746836125 and parameters: {'num_leaves': 15, 'learning_rate': 0.1676308206303196, 'feature_fraction': 0.8216735737268508, 'bagging_fraction': 0.8882386421217401, 'bagging_freq': 3, 'lambda_l1': 8.255437443106307e-08, 'lambda_l2': 0.00048674311532449115, 'min_child_samples': 48, 'max_depth': 9, 'max_bin': 329, 'min_data_in_leaf': 31, 'extra_trees': True, 'early_stopping_rounds': 35, 'path_smooth': 0.3363607885439542, 'min_gain_to_split': 0.2909829859450149}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 13:30:13,751] Trial 57 finished with value: 1.549374863037291 and parameters: {'num_leaves': 83, 'learning_rate': 0.10692448317658837, 'feature_fraction': 0.988465603189377, 'bagging_fraction': 0.950769218154186, 'bagging_freq': 4, 'lambda_l1': 2.1391947939905738e-07, 'lambda_l2': 0.01261749276116685, 'min_child_samples': 17, 'max_depth': 5, 'max_bin': 306, 'min_data_in_leaf': 47, 'extra_trees': True, 'early_stopping_rounds': 43, 'path_smooth': 0.08624368024234892, 'min_gain_to_split': 0.2506867145008286}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 13:31:16,782] Trial 58 finished with value: 1.4961574664169173 and parameters: {'num_leaves': 70, 'learning_rate': 0.1423401846413253, 'feature_fraction': 0.8694665837688059, 'bagging_fraction': 0.988587990799734, 'bagging_freq': 2, 'lambda_l1': 1.0877062148824896e-06, 'lambda_l2': 0.5679373961632025, 'min_child_samples': 23, 'max_depth': 10, 'max_bin': 359, 'min_data_in_leaf': 40, 'extra_trees': True, 'early_stopping_rounds': 32, 'path_smooth': 0.22966194928181027, 'min_gain_to_split': 0.31048625278965214}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 13:32:11,154] Trial 59 finished with value: 1.5036946408306207 and parameters: {'num_leaves': 42, 'learning_rate': 0.19109512417064814, 'feature_fraction': 0.9356182713199115, 'bagging_fraction': 0.8273983493406805, 'bagging_freq': 1, 'lambda_l1': 1.674314649685864e-05, 'lambda_l2': 3.592310981142886e-05, 'min_child_samples': 37, 'max_depth': 4, 'max_bin': 397, 'min_data_in_leaf': 71, 'extra_trees': False, 'early_stopping_rounds': 38, 'path_smooth': 0.04063072267947432, 'min_gain_to_split': 0.33712083658544634}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 13:33:09,945] Trial 60 finished with value: 1.3505315513553584 and parameters: {'num_leaves': 62, 'learning_rate': 0.21895491240952025, 'feature_fraction': 0.9655843465719921, 'bagging_fraction': 0.9226319894910947, 'bagging_freq': 3, 'lambda_l1': 2.084639966157435e-08, 'lambda_l2': 0.1517357389949474, 'min_child_samples': 29, 'max_depth': 6, 'max_bin': 289, 'min_data_in_leaf': 27, 'extra_trees': True, 'early_stopping_rounds': 40, 'path_smooth': 0.15805942958410948, 'min_gain_to_split': 0.2237336592560592}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 13:34:00,764] Trial 61 finished with value: 1.398085170578853 and parameters: {'num_leaves': 75, 'learning_rate': 0.2645532612517673, 'feature_fraction': 0.8876708533420086, 'bagging_fraction': 0.8171880789239314, 'bagging_freq': 5, 'lambda_l1': 9.29331446241922e-05, 'lambda_l2': 3.6786167073938605e-07, 'min_child_samples': 15, 'max_depth': 8, 'max_bin': 372, 'min_data_in_leaf': 22, 'extra_trees': True, 'early_stopping_rounds': 21, 'path_smooth': 0.027333997699641788, 'min_gain_to_split': 0.44792250896133073}. Best is trial 0 with value: 1.1289816591470523.

Mejor trial hasta ahora: RMSE=1.128982, Parámetros={'num_leaves': 47, 'learning_rate': 0.2536999076681772, 'feature_fraction': 0.892797576724562, 'bagging_fraction': 0.8795975452591109, 'bagging_freq': 2, 'lambda_l1': 2.5348407664333426e-07, 'lambda_l2': 3.3323645788192616e-08, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 383, 'min_data_in_leaf': 21, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18182496720710062, 'min_gain_to_split': 0.09170225492671691}

[I 2025-07-11 13:34:52,055] Trial 62 finished with value: 0.9693953906653073 and parameters: {'num_leaves': 84, 'learning_rate': 0.29220726754644083, 'feature_fraction': 0.9166983380437564, 'bagging_fraction': 0.7210618190308755, 'bagging_freq': 4, 'lambda_l1': 0.0020633704895237316, 'lambda_l2': 2.144477782729592e-08, 'min_child_samples': 12, 'max_depth': 7, 'max_bin': 434, 'min_data_in_leaf': 22, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.12178912234710147, 'min_gain_to_split': 0.378635820691341}. Best is trial 62 with value: 0.9693953906653073.

Mejor trial hasta ahora: RMSE=0.969395, Parámetros={'num_leaves': 84, 'learning_rate': 0.29220726754644083, 'feature_fraction': 0.9166983380437564, 'bagging_fraction': 0.7210618190308755, 'bagging_freq': 4, 'lambda_l1': 0.0020633704895237316, 'lambda_l2': 2.144477782729592e-08, 'min_child_samples': 12, 'max_depth': 7, 'max_bin': 434, 'min_data_in_leaf': 22, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.12178912234710147, 'min_gain_to_split': 0.378635820691341}

[I 2025-07-11 13:35:43,024] Trial 63 finished with value: 1.0653442227598968 and parameters: {'num_leaves': 89, 'learning_rate': 0.2831142254400488, 'feature_fraction': 0.9021568351955398, 'bagging_fraction': 0.7134156627094854, 'bagging_freq': 4, 'lambda_l1': 0.000853836419167132, 'lambda_l2': 2.2119217393672867e-08, 'min_child_samples': 33, 'max_depth': 7, 'max_bin': 436, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.12876652612768222, 'min_gain_to_split': 0.40680651445160876}. Best is trial 62 with value: 0.9693953906653073.

Mejor trial hasta ahora: RMSE=0.969395, Parámetros={'num_leaves': 84, 'learning_rate': 0.29220726754644083, 'feature_fraction': 0.9166983380437564, 'bagging_fraction': 0.7210618190308755, 'bagging_freq': 4, 'lambda_l1': 0.0020633704895237316, 'lambda_l2': 2.144477782729592e-08, 'min_child_samples': 12, 'max_depth': 7, 'max_bin': 434, 'min_data_in_leaf': 22, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.12178912234710147, 'min_gain_to_split': 0.378635820691341}

[I 2025-07-11 13:36:36,456] Trial 64 finished with value: 1.3486786593769196 and parameters: {'num_leaves': 85, 'learning_rate': 0.2780954010601959, 'feature_fraction': 0.9042586611756176, 'bagging_fraction': 0.7054118993256832, 'bagging_freq': 4, 'lambda_l1': 0.0028731473498380313, 'lambda_l2': 2.2310211676503467e-08, 'min_child_samples': 41, 'max_depth': 7, 'max_bin': 436, 'min_data_in_leaf': 37, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.1253474216625966, 'min_gain_to_split': 0.41844661618033796}. Best is trial 62 with value: 0.9693953906653073.

Mejor trial hasta ahora: RMSE=0.969395, Parámetros={'num_leaves': 84, 'learning_rate': 0.29220726754644083, 'feature_fraction': 0.9166983380437564, 'bagging_fraction': 0.7210618190308755, 'bagging_freq': 4, 'lambda_l1': 0.0020633704895237316, 'lambda_l2': 2.144477782729592e-08, 'min_child_samples': 12, 'max_depth': 7, 'max_bin': 434, 'min_data_in_leaf': 22, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.12178912234710147, 'min_gain_to_split': 0.378635820691341}

[I 2025-07-11 13:37:26,196] Trial 65 finished with value: 1.3479057351211883 and parameters: {'num_leaves': 94, 'learning_rate': 0.2283332247510553, 'feature_fraction': 0.836920935649734, 'bagging_fraction': 0.7273290598811888, 'bagging_freq': 4, 'lambda_l1': 0.0008633550600947813, 'lambda_l2': 1.1951666084803888e-08, 'min_child_samples': 11, 'max_depth': 7, 'max_bin': 418, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 15, 'path_smooth': 0.07497596488359916, 'min_gain_to_split': 0.38854837579187473}. Best is trial 62 with value: 0.9693953906653073.

Mejor trial hasta ahora: RMSE=0.969395, Parámetros={'num_leaves': 84, 'learning_rate': 0.29220726754644083, 'feature_fraction': 0.9166983380437564, 'bagging_fraction': 0.7210618190308755, 'bagging_freq': 4, 'lambda_l1': 0.0020633704895237316, 'lambda_l2': 2.144477782729592e-08, 'min_child_samples': 12, 'max_depth': 7, 'max_bin': 434, 'min_data_in_leaf': 22, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.12178912234710147, 'min_gain_to_split': 0.378635820691341}

[I 2025-07-11 13:38:18,452] Trial 66 finished with value: 1.2227149480004686 and parameters: {'num_leaves': 91, 'learning_rate': 0.29407009671053813, 'feature_fraction': 0.8936703908255678, 'bagging_fraction': 0.7027543753457919, 'bagging_freq': 3, 'lambda_l1': 0.00018691048901588224, 'lambda_l2': 6.809647453786974e-08, 'min_child_samples': 41, 'max_depth': 7, 'max_bin': 465, 'min_data_in_leaf': 42, 'extra_trees': True, 'early_stopping_rounds': 19, 'path_smooth': 0.18924991220861193, 'min_gain_to_split': 0.37650641141138425}. Best is trial 62 with value: 0.9693953906653073.

Mejor trial hasta ahora: RMSE=0.969395, Parámetros={'num_leaves': 84, 'learning_rate': 0.29220726754644083, 'feature_fraction': 0.9166983380437564, 'bagging_fraction': 0.7210618190308755, 'bagging_freq': 4, 'lambda_l1': 0.0020633704895237316, 'lambda_l2': 2.144477782729592e-08, 'min_child_samples': 12, 'max_depth': 7, 'max_bin': 434, 'min_data_in_leaf': 22, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.12178912234710147, 'min_gain_to_split': 0.378635820691341}

[I 2025-07-11 13:39:08,878] Trial 67 finished with value: 1.2522416108424694 and parameters: {'num_leaves': 91, 'learning_rate': 0.2792696637946931, 'feature_fraction': 0.9510344259508818, 'bagging_fraction': 0.7089070544306526, 'bagging_freq': 5, 'lambda_l1': 0.0002077266939962954, 'lambda_l2': 1.1723978083907192e-07, 'min_child_samples': 40, 'max_depth': 7, 'max_bin': 457, 'min_data_in_leaf': 26, 'extra_trees': True, 'early_stopping_rounds': 20, 'path_smooth': 0.19349646742807694, 'min_gain_to_split': 0.3693480730540773}. Best is trial 62 with value: 0.9693953906653073.

Mejor trial hasta ahora: RMSE=0.969395, Parámetros={'num_leaves': 84, 'learning_rate': 0.29220726754644083, 'feature_fraction': 0.9166983380437564, 'bagging_fraction': 0.7210618190308755, 'bagging_freq': 4, 'lambda_l1': 0.0020633704895237316, 'lambda_l2': 2.144477782729592e-08, 'min_child_samples': 12, 'max_depth': 7, 'max_bin': 434, 'min_data_in_leaf': 22, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.12178912234710147, 'min_gain_to_split': 0.378635820691341}

[I 2025-07-11 13:39:57,566] Trial 68 finished with value: 1.319515656741486 and parameters: {'num_leaves': 98, 'learning_rate': 0.24512172997891346, 'feature_fraction': 0.9104330350857502, 'bagging_fraction': 0.7199985016247983, 'bagging_freq': 4, 'lambda_l1': 0.0007972086903846655, 'lambda_l2': 5.1310806514871624e-08, 'min_child_samples': 43, 'max_depth': 7, 'max_bin': 468, 'min_data_in_leaf': 43, 'extra_trees': True, 'early_stopping_rounds': 17, 'path_smooth': 0.16440753643606001, 'min_gain_to_split': 0.41296092482666646}. Best is trial 62 with value: 0.9693953906653073.

Mejor trial hasta ahora: RMSE=0.969395, Parámetros={'num_leaves': 84, 'learning_rate': 0.29220726754644083, 'feature_fraction': 0.9166983380437564, 'bagging_fraction': 0.7210618190308755, 'bagging_freq': 4, 'lambda_l1': 0.0020633704895237316, 'lambda_l2': 2.144477782729592e-08, 'min_child_samples': 12, 'max_depth': 7, 'max_bin': 434, 'min_data_in_leaf': 22, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.12178912234710147, 'min_gain_to_split': 0.378635820691341}

[I 2025-07-11 13:40:44,285] Trial 69 finished with value: 1.3096494023464338 and parameters: {'num_leaves': 100, 'learning_rate': 0.29543445463194706, 'feature_fraction': 0.8950631843018632, 'bagging_fraction': 0.7427743811666492, 'bagging_freq': 3, 'lambda_l1': 4.549169338635985e-05, 'lambda_l2': 7.42934637720743e-08, 'min_child_samples': 45, 'max_depth': 6, 'max_bin': 476, 'min_data_in_leaf': 30, 'extra_trees': True, 'early_stopping_rounds': 13, 'path_smooth': 0.09964382868272707, 'min_gain_to_split': 0.38423844807446644}. Best is trial 62 with value: 0.9693953906653073.

Mejor trial hasta ahora: RMSE=0.969395, Parámetros={'num_leaves': 84, 'learning_rate': 0.29220726754644083, 'feature_fraction': 0.9166983380437564, 'bagging_fraction': 0.7210618190308755, 'bagging_freq': 4, 'lambda_l1': 0.0020633704895237316, 'lambda_l2': 2.144477782729592e-08, 'min_child_samples': 12, 'max_depth': 7, 'max_bin': 434, 'min_data_in_leaf': 22, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.12178912234710147, 'min_gain_to_split': 0.378635820691341}

[I 2025-07-11 13:41:35,200] Trial 70 finished with value: 1.3806372134678164 and parameters: {'num_leaves': 87, 'learning_rate': 0.17151536897497036, 'feature_fraction': 0.9280854669001573, 'bagging_fraction': 0.7171237013523576, 'bagging_freq': 5, 'lambda_l1': 0.00016196052474275424, 'lambda_l2': 1.0090819213174075e-08, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 500, 'min_data_in_leaf': 23, 'extra_trees': True, 'early_stopping_rounds': 19, 'path_smooth': 0.1237713419435455, 'min_gain_to_split': 0.399284494295832}. Best is trial 62 with value: 0.9693953906653073.

Mejor trial hasta ahora: RMSE=0.969395, Parámetros={'num_leaves': 84, 'learning_rate': 0.29220726754644083, 'feature_fraction': 0.9166983380437564, 'bagging_fraction': 0.7210618190308755, 'bagging_freq': 4, 'lambda_l1': 0.0020633704895237316, 'lambda_l2': 2.144477782729592e-08, 'min_child_samples': 12, 'max_depth': 7, 'max_bin': 434, 'min_data_in_leaf': 22, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.12178912234710147, 'min_gain_to_split': 0.378635820691341}

[I 2025-07-11 13:42:25,519] Trial 71 finished with value: 1.3000185799028157 and parameters: {'num_leaves': 95, 'learning_rate': 0.21615488953951098, 'feature_fraction': 0.8763282047597405, 'bagging_fraction': 0.7043607374285511, 'bagging_freq': 3, 'lambda_l1': 0.003973803773856293, 'lambda_l2': 2.2014035853532428e-07, 'min_child_samples': 41, 'max_depth': 7, 'max_bin': 438, 'min_data_in_leaf': 39, 'extra_trees': True, 'early_stopping_rounds': 16, 'path_smooth': 0.24374923195738027, 'min_gain_to_split': 0.3429559858291634}. Best is trial 62 with value: 0.9693953906653073.

Mejor trial hasta ahora: RMSE=0.969395, Parámetros={'num_leaves': 84, 'learning_rate': 0.29220726754644083, 'feature_fraction': 0.9166983380437564, 'bagging_fraction': 0.7210618190308755, 'bagging_freq': 4, 'lambda_l1': 0.0020633704895237316, 'lambda_l2': 2.144477782729592e-08, 'min_child_samples': 12, 'max_depth': 7, 'max_bin': 434, 'min_data_in_leaf': 22, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.12178912234710147, 'min_gain_to_split': 0.378635820691341}

[I 2025-07-11 13:43:18,891] Trial 72 finished with value: 1.1133571048054045 and parameters: {'num_leaves': 82, 'learning_rate': 0.23379106390838814, 'feature_fraction': 0.8557722505485726, 'bagging_fraction': 0.7354642586256782, 'bagging_freq': 2, 'lambda_l1': 0.0004472165623510428, 'lambda_l2': 2.892095878720321e-08, 'min_child_samples': 34, 'max_depth': 6, 'max_bin': 406, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 22, 'path_smooth': 0.06658744232487113, 'min_gain_to_split': 0.356287804066613}. Best is trial 62 with value: 0.9693953906653073.

Mejor trial hasta ahora: RMSE=0.969395, Parámetros={'num_leaves': 84, 'learning_rate': 0.29220726754644083, 'feature_fraction': 0.9166983380437564, 'bagging_fraction': 0.7210618190308755, 'bagging_freq': 4, 'lambda_l1': 0.0020633704895237316, 'lambda_l2': 2.144477782729592e-08, 'min_child_samples': 12, 'max_depth': 7, 'max_bin': 434, 'min_data_in_leaf': 22, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.12178912234710147, 'min_gain_to_split': 0.378635820691341}

[I 2025-07-11 13:44:09,385] Trial 73 finished with value: 1.5832681672462157 and parameters: {'num_leaves': 83, 'learning_rate': 0.2726751421597091, 'feature_fraction': 0.8917835038127567, 'bagging_fraction': 0.7348371036727624, 'bagging_freq': 2, 'lambda_l1': 0.00045775747332593085, 'lambda_l2': 2.6475707553402472e-08, 'min_child_samples': 34, 'max_depth': 5, 'max_bin': 424, 'min_data_in_leaf': 35, 'extra_trees': True, 'early_stopping_rounds': 20, 'path_smooth': 0.07088981501617482, 'min_gain_to_split': 0.3577873304586541}. Best is trial 62 with value: 0.9693953906653073.

Mejor trial hasta ahora: RMSE=0.969395, Parámetros={'num_leaves': 84, 'learning_rate': 0.29220726754644083, 'feature_fraction': 0.9166983380437564, 'bagging_fraction': 0.7210618190308755, 'bagging_freq': 4, 'lambda_l1': 0.0020633704895237316, 'lambda_l2': 2.144477782729592e-08, 'min_child_samples': 12, 'max_depth': 7, 'max_bin': 434, 'min_data_in_leaf': 22, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.12178912234710147, 'min_gain_to_split': 0.378635820691341}

[I 2025-07-11 13:44:56,592] Trial 74 finished with value: 1.3767074026261672 and parameters: {'num_leaves': 92, 'learning_rate': 0.23232948779576784, 'feature_fraction': 0.866000861765915, 'bagging_fraction': 0.7135996950405477, 'bagging_freq': 2, 'lambda_l1': 0.0014410611185059251, 'lambda_l2': 1.9940570756966503e-08, 'min_child_samples': 36, 'max_depth': 6, 'max_bin': 402, 'min_data_in_leaf': 31, 'extra_trees': True, 'early_stopping_rounds': 23, 'path_smooth': 0.045863487420068835, 'min_gain_to_split': 0.4528303044018742}. Best is trial 62 with value: 0.9693953906653073.

Mejor trial hasta ahora: RMSE=0.969395, Parámetros={'num_leaves': 84, 'learning_rate': 0.29220726754644083, 'feature_fraction': 0.9166983380437564, 'bagging_fraction': 0.7210618190308755, 'bagging_freq': 4, 'lambda_l1': 0.0020633704895237316, 'lambda_l2': 2.144477782729592e-08, 'min_child_samples': 12, 'max_depth': 7, 'max_bin': 434, 'min_data_in_leaf': 22, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.12178912234710147, 'min_gain_to_split': 0.378635820691341}

[I 2025-07-11 13:45:47,279] Trial 75 finished with value: 1.3338417635531883 and parameters: {'num_leaves': 88, 'learning_rate': 0.2694283954989287, 'feature_fraction': 0.9368255411935356, 'bagging_fraction': 0.7290183979209206, 'bagging_freq': 2, 'lambda_l1': 0.0002751846213046038, 'lambda_l2': 4.1539312755724767e-08, 'min_child_samples': 32, 'max_depth': 6, 'max_bin': 409, 'min_data_in_leaf': 28, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.18869042996025204, 'min_gain_to_split': 0.32379484930294916}. Best is trial 62 with value: 0.9693953906653073.

Mejor trial hasta ahora: RMSE=0.969395, Parámetros={'num_leaves': 84, 'learning_rate': 0.29220726754644083, 'feature_fraction': 0.9166983380437564, 'bagging_fraction': 0.7210618190308755, 'bagging_freq': 4, 'lambda_l1': 0.0020633704895237316, 'lambda_l2': 2.144477782729592e-08, 'min_child_samples': 12, 'max_depth': 7, 'max_bin': 434, 'min_data_in_leaf': 22, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.12178912234710147, 'min_gain_to_split': 0.378635820691341}

[I 2025-07-11 13:46:40,994] Trial 76 finished with value: 1.3540917345895531 and parameters: {'num_leaves': 54, 'learning_rate': 0.18476139508556574, 'feature_fraction': 0.9182728113037322, 'bagging_fraction': 0.7414245045185698, 'bagging_freq': 4, 'lambda_l1': 0.0016885576622797083, 'lambda_l2': 4.811967798247717e-07, 'min_child_samples': 43, 'max_depth': 5, 'max_bin': 431, 'min_data_in_leaf': 47, 'extra_trees': True, 'early_stopping_rounds': 11, 'path_smooth': 0.10397499043363524, 'min_gain_to_split': 0.09779877017094196}. Best is trial 62 with value: 0.9693953906653073.

Mejor trial hasta ahora: RMSE=0.969395, Parámetros={'num_leaves': 84, 'learning_rate': 0.29220726754644083, 'feature_fraction': 0.9166983380437564, 'bagging_fraction': 0.7210618190308755, 'bagging_freq': 4, 'lambda_l1': 0.0020633704895237316, 'lambda_l2': 2.144477782729592e-08, 'min_child_samples': 12, 'max_depth': 7, 'max_bin': 434, 'min_data_in_leaf': 22, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.12178912234710147, 'min_gain_to_split': 0.378635820691341}

[I 2025-07-11 13:48:12,554] Trial 77 finished with value: 1.1632171404643852 and parameters: {'num_leaves': 82, 'learning_rate': 0.2356895876352972, 'feature_fraction': 0.8576101249397424, 'bagging_fraction': 0.7007943024800363, 'bagging_freq': 1, 'lambda_l1': 0.0204228689630513, 'lambda_l2': 1.5625087442277279e-07, 'min_child_samples': 35, 'max_depth': 7, 'max_bin': 450, 'min_data_in_leaf': 25, 'extra_trees': False, 'early_stopping_rounds': 21, 'path_smooth': 0.16027431872856657, 'min_gain_to_split': 0.4046787689799592}. Best is trial 62 with value: 0.9693953906653073.

Mejor trial hasta ahora: RMSE=0.969395, Parámetros={'num_leaves': 84, 'learning_rate': 0.29220726754644083, 'feature_fraction': 0.9166983380437564, 'bagging_fraction': 0.7210618190308755, 'bagging_freq': 4, 'lambda_l1': 0.0020633704895237316, 'lambda_l2': 2.144477782729592e-08, 'min_child_samples': 12, 'max_depth': 7, 'max_bin': 434, 'min_data_in_leaf': 22, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.12178912234710147, 'min_gain_to_split': 0.378635820691341}

[I 2025-07-11 13:49:30,413] Trial 78 finished with value: 1.332317954210119 and parameters: {'num_leaves': 84, 'learning_rate': 0.2406038771359177, 'feature_fraction': 0.8588442287467072, 'bagging_fraction': 0.7722238245365193, 'bagging_freq': 1, 'lambda_l1': 0.2558218960833351, 'lambda_l2': 1.8917470007954584e-07, 'min_child_samples': 33, 'max_depth': 8, 'max_bin': 449, 'min_data_in_leaf': 25, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.14419938145442568, 'min_gain_to_split': 0.4057613935000105}. Best is trial 62 with value: 0.9693953906653073.

Mejor trial hasta ahora: RMSE=0.969395, Parámetros={'num_leaves': 84, 'learning_rate': 0.29220726754644083, 'feature_fraction': 0.9166983380437564, 'bagging_fraction': 0.7210618190308755, 'bagging_freq': 4, 'lambda_l1': 0.0020633704895237316, 'lambda_l2': 2.144477782729592e-08, 'min_child_samples': 12, 'max_depth': 7, 'max_bin': 434, 'min_data_in_leaf': 22, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.12178912234710147, 'min_gain_to_split': 0.378635820691341}

[I 2025-07-11 13:50:45,494] Trial 79 finished with value: 1.404034597895053 and parameters: {'num_leaves': 78, 'learning_rate': 0.2124333470617907, 'feature_fraction': 0.820879465923325, 'bagging_fraction': 0.8398750909988317, 'bagging_freq': 1, 'lambda_l1': 5.822976440662893e-08, 'lambda_l2': 2.225026273295003e-06, 'min_child_samples': 35, 'max_depth': 6, 'max_bin': 416, 'min_data_in_leaf': 22, 'extra_trees': False, 'early_stopping_rounds': 28, 'path_smooth': 0.02647570676993463, 'min_gain_to_split': 0.42759693830669493}. Best is trial 62 with value: 0.9693953906653073.

Mejor trial hasta ahora: RMSE=0.969395, Parámetros={'num_leaves': 84, 'learning_rate': 0.29220726754644083, 'feature_fraction': 0.9166983380437564, 'bagging_fraction': 0.7210618190308755, 'bagging_freq': 4, 'lambda_l1': 0.0020633704895237316, 'lambda_l2': 2.144477782729592e-08, 'min_child_samples': 12, 'max_depth': 7, 'max_bin': 434, 'min_data_in_leaf': 22, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.12178912234710147, 'min_gain_to_split': 0.378635820691341}

[I 2025-07-11 13:51:50,328] Trial 80 finished with value: 1.6251596703435751 and parameters: {'num_leaves': 86, 'learning_rate': 0.03246978064604362, 'feature_fraction': 0.879908472623338, 'bagging_fraction': 0.7223613643618845, 'bagging_freq': 1, 'lambda_l1': 0.0193357307862839, 'lambda_l2': 1.6613995447154762e-08, 'min_child_samples': 31, 'max_depth': 5, 'max_bin': 394, 'min_data_in_leaf': 22, 'extra_trees': False, 'early_stopping_rounds': 16, 'path_smooth': 0.12033417998181012, 'min_gain_to_split': 0.02600468114168608}. Best is trial 62 with value: 0.9693953906653073.

Mejor trial hasta ahora: RMSE=0.969395, Parámetros={'num_leaves': 84, 'learning_rate': 0.29220726754644083, 'feature_fraction': 0.9166983380437564, 'bagging_fraction': 0.7210618190308755, 'bagging_freq': 4, 'lambda_l1': 0.0020633704895237316, 'lambda_l2': 2.144477782729592e-08, 'min_child_samples': 12, 'max_depth': 7, 'max_bin': 434, 'min_data_in_leaf': 22, 'extra_trees': True, 'early_stopping_rounds': 18, 'path_smooth': 0.12178912234710147, 'min_gain_to_split': 0.378635820691341}

[I 2025-07-11 13:53:14,673] Trial 81 finished with value: 0.647173334975515 and parameters: {'num_leaves': 81, 'learning_rate': 0.2921368243287838, 'feature_fraction': 0.9041268776963804, 'bagging_fraction': 0.702448436521742, 'bagging_freq': 2, 'lambda_l1': 0.008900421072650216, 'lambda_l2': 8.897034525718933e-08, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 447, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.20894699872344127, 'min_gain_to_split': 0.38188439239381}. Best is trial 81 with value: 0.647173334975515.

Mejor trial hasta ahora: RMSE=0.647173, Parámetros={'num_leaves': 81, 'learning_rate': 0.2921368243287838, 'feature_fraction': 0.9041268776963804, 'bagging_fraction': 0.702448436521742, 'bagging_freq': 2, 'lambda_l1': 0.008900421072650216, 'lambda_l2': 8.897034525718933e-08, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 447, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.20894699872344127, 'min_gain_to_split': 0.38188439239381}

[I 2025-07-11 13:54:37,460] Trial 82 finished with value: 1.2042703980892158 and parameters: {'num_leaves': 80, 'learning_rate': 0.2507340569159218, 'feature_fraction': 0.9083991527246138, 'bagging_fraction': 0.7126887941630423, 'bagging_freq': 2, 'lambda_l1': 0.011109944383305882, 'lambda_l2': 3.366895965229258e-08, 'min_child_samples': 37, 'max_depth': 7, 'max_bin': 389, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.2780328525326045, 'min_gain_to_split': 0.3649508444177941}. Best is trial 81 with value: 0.647173334975515.

Mejor trial hasta ahora: RMSE=0.647173, Parámetros={'num_leaves': 81, 'learning_rate': 0.2921368243287838, 'feature_fraction': 0.9041268776963804, 'bagging_fraction': 0.702448436521742, 'bagging_freq': 2, 'lambda_l1': 0.008900421072650216, 'lambda_l2': 8.897034525718933e-08, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 447, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.20894699872344127, 'min_gain_to_split': 0.38188439239381}

[I 2025-07-11 13:55:56,654] Trial 83 finished with value: 1.0180666677127206 and parameters: {'num_leaves': 77, 'learning_rate': 0.2723905089634271, 'feature_fraction': 0.9449354905802038, 'bagging_fraction': 0.7510636035281781, 'bagging_freq': 1, 'lambda_l1': 0.03233308772108352, 'lambda_l2': 8.508030244905046e-08, 'min_child_samples': 34, 'max_depth': 7, 'max_bin': 450, 'min_data_in_leaf': 26, 'extra_trees': False, 'early_stopping_rounds': 21, 'path_smooth': 0.21842455146888567, 'min_gain_to_split': 0.39183668244247327}. Best is trial 81 with value: 0.647173334975515.

Mejor trial hasta ahora: RMSE=0.647173, Parámetros={'num_leaves': 81, 'learning_rate': 0.2921368243287838, 'feature_fraction': 0.9041268776963804, 'bagging_fraction': 0.702448436521742, 'bagging_freq': 2, 'lambda_l1': 0.008900421072650216, 'lambda_l2': 8.897034525718933e-08, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 447, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.20894699872344127, 'min_gain_to_split': 0.38188439239381}

[I 2025-07-11 13:57:21,091] Trial 84 finished with value: 0.8630619861572919 and parameters: {'num_leaves': 82, 'learning_rate': 0.29985566933669083, 'feature_fraction': 0.9248634800266705, 'bagging_fraction': 0.700366082345527, 'bagging_freq': 1, 'lambda_l1': 0.06632710496567475, 'lambda_l2': 1.2170823331653594e-07, 'min_child_samples': 34, 'max_depth': 7, 'max_bin': 445, 'min_data_in_leaf': 26, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.22591589276062982, 'min_gain_to_split': 0.41256338385414665}. Best is trial 81 with value: 0.647173334975515.

Mejor trial hasta ahora: RMSE=0.647173, Parámetros={'num_leaves': 81, 'learning_rate': 0.2921368243287838, 'feature_fraction': 0.9041268776963804, 'bagging_fraction': 0.702448436521742, 'bagging_freq': 2, 'lambda_l1': 0.008900421072650216, 'lambda_l2': 8.897034525718933e-08, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 447, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.20894699872344127, 'min_gain_to_split': 0.38188439239381}

[I 2025-07-11 13:58:40,372] Trial 85 finished with value: 1.1822729031231434 and parameters: {'num_leaves': 82, 'learning_rate': 0.29909368474241665, 'feature_fraction': 0.9217795096369683, 'bagging_fraction': 0.7004297637744678, 'bagging_freq': 1, 'lambda_l1': 0.07078899974217615, 'lambda_l2': 1.4052732718563298e-07, 'min_child_samples': 35, 'max_depth': 7, 'max_bin': 446, 'min_data_in_leaf': 26, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.21844562794501668, 'min_gain_to_split': 0.4427798175468316}. Best is trial 81 with value: 0.647173334975515.

Mejor trial hasta ahora: RMSE=0.647173, Parámetros={'num_leaves': 81, 'learning_rate': 0.2921368243287838, 'feature_fraction': 0.9041268776963804, 'bagging_fraction': 0.702448436521742, 'bagging_freq': 2, 'lambda_l1': 0.008900421072650216, 'lambda_l2': 8.897034525718933e-08, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 447, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.20894699872344127, 'min_gain_to_split': 0.38188439239381}

[I 2025-07-11 14:00:47,606] Trial 86 finished with value: 1.646855965498095 and parameters: {'num_leaves': 48, 'learning_rate': 0.016387861451241065, 'feature_fraction': 0.933613040689597, 'bagging_fraction': 0.761165444301186, 'bagging_freq': 1, 'lambda_l1': 0.050138551391818525, 'lambda_l2': 5.791152461509836e-07, 'min_child_samples': 38, 'max_depth': 8, 'max_bin': 476, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 21, 'path_smooth': 0.16604112221588563, 'min_gain_to_split': 0.4138190818977645}. Best is trial 81 with value: 0.647173334975515.

Mejor trial hasta ahora: RMSE=0.647173, Parámetros={'num_leaves': 81, 'learning_rate': 0.2921368243287838, 'feature_fraction': 0.9041268776963804, 'bagging_fraction': 0.702448436521742, 'bagging_freq': 2, 'lambda_l1': 0.008900421072650216, 'lambda_l2': 8.897034525718933e-08, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 447, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.20894699872344127, 'min_gain_to_split': 0.38188439239381}

[I 2025-07-11 14:02:17,773] Trial 87 finished with value: 0.8092826801948068 and parameters: {'num_leaves': 89, 'learning_rate': 0.2606910079814657, 'feature_fraction': 0.9433336674220162, 'bagging_fraction': 0.7397490353255239, 'bagging_freq': 1, 'lambda_l1': 0.2510040541293284, 'lambda_l2': 8.323800798290633e-08, 'min_child_samples': 34, 'max_depth': 7, 'max_bin': 432, 'min_data_in_leaf': 25, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.09876527925754722, 'min_gain_to_split': 0.46371632123939477}. Best is trial 81 with value: 0.647173334975515.

Mejor trial hasta ahora: RMSE=0.647173, Parámetros={'num_leaves': 81, 'learning_rate': 0.2921368243287838, 'feature_fraction': 0.9041268776963804, 'bagging_fraction': 0.702448436521742, 'bagging_freq': 2, 'lambda_l1': 0.008900421072650216, 'lambda_l2': 8.897034525718933e-08, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 447, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.20894699872344127, 'min_gain_to_split': 0.38188439239381}

[I 2025-07-11 14:03:48,147] Trial 88 finished with value: 0.9306480052863458 and parameters: {'num_leaves': 89, 'learning_rate': 0.2673785705493482, 'feature_fraction': 0.9475856731538967, 'bagging_fraction': 0.7472808935584746, 'bagging_freq': 1, 'lambda_l1': 0.18367056957053568, 'lambda_l2': 2.7049766803027275e-07, 'min_child_samples': 33, 'max_depth': 7, 'max_bin': 457, 'min_data_in_leaf': 25, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.20517697132833804, 'min_gain_to_split': 0.4862307102659038}. Best is trial 81 with value: 0.647173334975515.

Mejor trial hasta ahora: RMSE=0.647173, Parámetros={'num_leaves': 81, 'learning_rate': 0.2921368243287838, 'feature_fraction': 0.9041268776963804, 'bagging_fraction': 0.702448436521742, 'bagging_freq': 2, 'lambda_l1': 0.008900421072650216, 'lambda_l2': 8.897034525718933e-08, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 447, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.20894699872344127, 'min_gain_to_split': 0.38188439239381}

[I 2025-07-11 14:05:04,481] Trial 89 finished with value: 1.089986970526796 and parameters: {'num_leaves': 77, 'learning_rate': 0.26540202234515653, 'feature_fraction': 0.9433953230743998, 'bagging_fraction': 0.7402872442575755, 'bagging_freq': 1, 'lambda_l1': 0.1791659901965262, 'lambda_l2': 3.115317547635134e-07, 'min_child_samples': 33, 'max_depth': 7, 'max_bin': 462, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.3224955440079262, 'min_gain_to_split': 0.49001277384349146}. Best is trial 81 with value: 0.647173334975515.

Mejor trial hasta ahora: RMSE=0.647173, Parámetros={'num_leaves': 81, 'learning_rate': 0.2921368243287838, 'feature_fraction': 0.9041268776963804, 'bagging_fraction': 0.702448436521742, 'bagging_freq': 2, 'lambda_l1': 0.008900421072650216, 'lambda_l2': 8.897034525718933e-08, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 447, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.20894699872344127, 'min_gain_to_split': 0.38188439239381}

[I 2025-07-11 14:06:26,514] Trial 90 finished with value: 0.920706527852728 and parameters: {'num_leaves': 77, 'learning_rate': 0.2723238772911478, 'feature_fraction': 0.9429314403344365, 'bagging_fraction': 0.7438190003638795, 'bagging_freq': 1, 'lambda_l1': 0.47790099529560554, 'lambda_l2': 1.3734316887796445e-06, 'min_child_samples': 33, 'max_depth': 7, 'max_bin': 463, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.308164584453801, 'min_gain_to_split': 0.49037540503815735}. Best is trial 81 with value: 0.647173334975515.

Mejor trial hasta ahora: RMSE=0.647173, Parámetros={'num_leaves': 81, 'learning_rate': 0.2921368243287838, 'feature_fraction': 0.9041268776963804, 'bagging_fraction': 0.702448436521742, 'bagging_freq': 2, 'lambda_l1': 0.008900421072650216, 'lambda_l2': 8.897034525718933e-08, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 447, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.20894699872344127, 'min_gain_to_split': 0.38188439239381}

[I 2025-07-11 14:07:54,329] Trial 91 finished with value: 0.9325433088182307 and parameters: {'num_leaves': 89, 'learning_rate': 0.2668228123192924, 'feature_fraction': 0.9428481365811792, 'bagging_fraction': 0.7394193318681603, 'bagging_freq': 1, 'lambda_l1': 0.24485922060212956, 'lambda_l2': 1.4378589260573174e-06, 'min_child_samples': 33, 'max_depth': 7, 'max_bin': 466, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.3240395786116019, 'min_gain_to_split': 0.4931557411623611}. Best is trial 81 with value: 0.647173334975515.

Mejor trial hasta ahora: RMSE=0.647173, Parámetros={'num_leaves': 81, 'learning_rate': 0.2921368243287838, 'feature_fraction': 0.9041268776963804, 'bagging_fraction': 0.702448436521742, 'bagging_freq': 2, 'lambda_l1': 0.008900421072650216, 'lambda_l2': 8.897034525718933e-08, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 447, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.20894699872344127, 'min_gain_to_split': 0.38188439239381}

[I 2025-07-11 14:09:11,208] Trial 92 finished with value: 0.9116552229250902 and parameters: {'num_leaves': 89, 'learning_rate': 0.27169702256100314, 'feature_fraction': 0.9447261229333069, 'bagging_fraction': 0.7476927933375296, 'bagging_freq': 1, 'lambda_l1': 0.2446477849029404, 'lambda_l2': 1.4863350544559648e-06, 'min_child_samples': 33, 'max_depth': 7, 'max_bin': 465, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.3102800328998755, 'min_gain_to_split': 0.4876303424079125}. Best is trial 81 with value: 0.647173334975515.

Mejor trial hasta ahora: RMSE=0.647173, Parámetros={'num_leaves': 81, 'learning_rate': 0.2921368243287838, 'feature_fraction': 0.9041268776963804, 'bagging_fraction': 0.702448436521742, 'bagging_freq': 2, 'lambda_l1': 0.008900421072650216, 'lambda_l2': 8.897034525718933e-08, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 447, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.20894699872344127, 'min_gain_to_split': 0.38188439239381}

[I 2025-07-11 14:10:20,493] Trial 93 finished with value: 1.3189171289275863 and parameters: {'num_leaves': 89, 'learning_rate': 0.2713714331411818, 'feature_fraction': 0.9561750457584443, 'bagging_fraction': 0.7532681926854471, 'bagging_freq': 1, 'lambda_l1': 2.0151043542795732, 'lambda_l2': 1.3509557228270876e-06, 'min_child_samples': 31, 'max_depth': 7, 'max_bin': 485, 'min_data_in_leaf': 24, 'extra_trees': False, 'early_stopping_rounds': 28, 'path_smooth': 0.3448071623553823, 'min_gain_to_split': 0.47940104841859077}. Best is trial 81 with value: 0.647173334975515.

Mejor trial hasta ahora: RMSE=0.647173, Parámetros={'num_leaves': 81, 'learning_rate': 0.2921368243287838, 'feature_fraction': 0.9041268776963804, 'bagging_fraction': 0.702448436521742, 'bagging_freq': 2, 'lambda_l1': 0.008900421072650216, 'lambda_l2': 8.897034525718933e-08, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 447, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.20894699872344127, 'min_gain_to_split': 0.38188439239381}

[I 2025-07-11 14:11:45,933] Trial 94 finished with value: 1.6364114670549177 and parameters: {'num_leaves': 93, 'learning_rate': 0.24789717426833632, 'feature_fraction': 0.9671173195447832, 'bagging_fraction': 0.779145975706844, 'bagging_freq': 1, 'lambda_l1': 0.6578106208706217, 'lambda_l2': 5.5761797336739385e-06, 'min_child_samples': 29, 'max_depth': 7, 'max_bin': 432, 'min_data_in_leaf': 31, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.39406372287093894, 'min_gain_to_split': 0.46490720177337336}. Best is trial 81 with value: 0.647173334975515.

Mejor trial hasta ahora: RMSE=0.647173, Parámetros={'num_leaves': 81, 'learning_rate': 0.2921368243287838, 'feature_fraction': 0.9041268776963804, 'bagging_fraction': 0.702448436521742, 'bagging_freq': 2, 'lambda_l1': 0.008900421072650216, 'lambda_l2': 8.897034525718933e-08, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 447, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.20894699872344127, 'min_gain_to_split': 0.38188439239381}

[I 2025-07-11 14:13:10,116] Trial 95 finished with value: 1.2438720886256527 and parameters: {'num_leaves': 95, 'learning_rate': 0.2721756036639625, 'feature_fraction': 0.9443105932372455, 'bagging_fraction': 0.7499717574265381, 'bagging_freq': 1, 'lambda_l1': 0.5363646141425769, 'lambda_l2': 1.2033179136162645e-05, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 481, 'min_data_in_leaf': 27, 'extra_trees': False, 'early_stopping_rounds': 29, 'path_smooth': 0.28456138018253513, 'min_gain_to_split': 0.48151721413082393}. Best is trial 81 with value: 0.647173334975515.

Mejor trial hasta ahora: RMSE=0.647173, Parámetros={'num_leaves': 81, 'learning_rate': 0.2921368243287838, 'feature_fraction': 0.9041268776963804, 'bagging_fraction': 0.702448436521742, 'bagging_freq': 2, 'lambda_l1': 0.008900421072650216, 'lambda_l2': 8.897034525718933e-08, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 447, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.20894699872344127, 'min_gain_to_split': 0.38188439239381}

[I 2025-07-11 14:14:30,039] Trial 96 finished with value: 0.8650071617014186 and parameters: {'num_leaves': 88, 'learning_rate': 0.29951906259251454, 'feature_fraction': 0.9548587974846778, 'bagging_fraction': 0.7471037672422539, 'bagging_freq': 1, 'lambda_l1': 0.21871451276178677, 'lambda_l2': 1.2343122410821148e-06, 'min_child_samples': 36, 'max_depth': 7, 'max_bin': 467, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.2439162591422381, 'min_gain_to_split': 0.460707103717225}. Best is trial 81 with value: 0.647173334975515.

Mejor trial hasta ahora: RMSE=0.647173, Parámetros={'num_leaves': 81, 'learning_rate': 0.2921368243287838, 'feature_fraction': 0.9041268776963804, 'bagging_fraction': 0.702448436521742, 'bagging_freq': 2, 'lambda_l1': 0.008900421072650216, 'lambda_l2': 8.897034525718933e-08, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 447, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.20894699872344127, 'min_gain_to_split': 0.38188439239381}

[I 2025-07-11 14:15:48,006] Trial 97 finished with value: 1.4990785366750967 and parameters: {'num_leaves': 85, 'learning_rate': 0.1905830818277346, 'feature_fraction': 0.9509282182443011, 'bagging_fraction': 0.759906854304345, 'bagging_freq': 1, 'lambda_l1': 0.14322134101936812, 'lambda_l2': 3.419361168241758e-06, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 496, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.30873868009613115, 'min_gain_to_split': 0.4613763638794228}. Best is trial 81 with value: 0.647173334975515.

Mejor trial hasta ahora: RMSE=0.647173, Parámetros={'num_leaves': 81, 'learning_rate': 0.2921368243287838, 'feature_fraction': 0.9041268776963804, 'bagging_fraction': 0.702448436521742, 'bagging_freq': 2, 'lambda_l1': 0.008900421072650216, 'lambda_l2': 8.897034525718933e-08, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 447, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.20894699872344127, 'min_gain_to_split': 0.38188439239381}

[I 2025-07-11 14:16:59,220] Trial 98 finished with value: 1.439849309979447 and parameters: {'num_leaves': 87, 'learning_rate': 0.2181256170481822, 'feature_fraction': 0.9735368536298216, 'bagging_fraction': 0.7481074859942787, 'bagging_freq': 1, 'lambda_l1': 2.904850805059619, 'lambda_l2': 1.0800816935175774e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 469, 'min_data_in_leaf': 25, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.24852122461492382, 'min_gain_to_split': 0.4970559500119807}. Best is trial 81 with value: 0.647173334975515.

Mejor trial hasta ahora: RMSE=0.647173, Parámetros={'num_leaves': 81, 'learning_rate': 0.2921368243287838, 'feature_fraction': 0.9041268776963804, 'bagging_fraction': 0.702448436521742, 'bagging_freq': 2, 'lambda_l1': 0.008900421072650216, 'lambda_l2': 8.897034525718933e-08, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 447, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.20894699872344127, 'min_gain_to_split': 0.38188439239381}

[I 2025-07-11 14:18:07,973] Trial 99 finished with value: 1.917476890161251 and parameters: {'num_leaves': 77, 'learning_rate': 0.2535908616137739, 'feature_fraction': 0.9896427620557493, 'bagging_fraction': 0.7248943452837174, 'bagging_freq': 2, 'lambda_l1': 0.9344040054161354, 'lambda_l2': 1.8427923433399986e-06, 'min_child_samples': 34, 'max_depth': 7, 'max_bin': 456, 'min_data_in_leaf': 21, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.208883720747793, 'min_gain_to_split': 0.47388194047434007}. Best is trial 81 with value: 0.647173334975515.

Mejor trial hasta ahora: RMSE=0.647173, Parámetros={'num_leaves': 81, 'learning_rate': 0.2921368243287838, 'feature_fraction': 0.9041268776963804, 'bagging_fraction': 0.702448436521742, 'bagging_freq': 2, 'lambda_l1': 0.008900421072650216, 'lambda_l2': 8.897034525718933e-08, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 447, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.20894699872344127, 'min_gain_to_split': 0.38188439239381}

[I 2025-07-11 14:19:38,705] Trial 100 finished with value: 1.1219770686053168 and parameters: {'num_leaves': 97, 'learning_rate': 0.20653143190240653, 'feature_fraction': 0.9579721776717669, 'bagging_fraction': 0.7641495805414532, 'bagging_freq': 1, 'lambda_l1': 0.0345883761724117, 'lambda_l2': 5.825719756837281e-07, 'min_child_samples': 36, 'max_depth': 7, 'max_bin': 444, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.36972516699727564, 'min_gain_to_split': 0.4549913563652317}. Best is trial 81 with value: 0.647173334975515.

Mejor trial hasta ahora: RMSE=0.647173, Parámetros={'num_leaves': 81, 'learning_rate': 0.2921368243287838, 'feature_fraction': 0.9041268776963804, 'bagging_fraction': 0.702448436521742, 'bagging_freq': 2, 'lambda_l1': 0.008900421072650216, 'lambda_l2': 8.897034525718933e-08, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 447, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.20894699872344127, 'min_gain_to_split': 0.38188439239381}

[I 2025-07-11 14:20:49,140] Trial 101 finished with value: 1.2564157237767024 and parameters: {'num_leaves': 89, 'learning_rate': 0.28323770906825885, 'feature_fraction': 0.9407525135065715, 'bagging_fraction': 0.7325244256772858, 'bagging_freq': 1, 'lambda_l1': 0.14917822491461968, 'lambda_l2': 9.125219507022635e-08, 'min_child_samples': 33, 'max_depth': 7, 'max_bin': 455, 'min_data_in_leaf': 30, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.261967804839912, 'min_gain_to_split': 0.43666907887207357}. Best is trial 81 with value: 0.647173334975515.

Mejor trial hasta ahora: RMSE=0.647173, Parámetros={'num_leaves': 81, 'learning_rate': 0.2921368243287838, 'feature_fraction': 0.9041268776963804, 'bagging_fraction': 0.702448436521742, 'bagging_freq': 2, 'lambda_l1': 0.008900421072650216, 'lambda_l2': 8.897034525718933e-08, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 447, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.20894699872344127, 'min_gain_to_split': 0.38188439239381}

[I 2025-07-11 14:22:02,455] Trial 102 finished with value: 1.0929446507834704 and parameters: {'num_leaves': 85, 'learning_rate': 0.2652267227560843, 'feature_fraction': 0.9254090511751123, 'bagging_fraction': 0.7157835068060725, 'bagging_freq': 2, 'lambda_l1': 0.41474701791834306, 'lambda_l2': 2.9120804267684088e-06, 'min_child_samples': 32, 'max_depth': 7, 'max_bin': 464, 'min_data_in_leaf': 27, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.22764653452477707, 'min_gain_to_split': 0.47917260068190876}. Best is trial 81 with value: 0.647173334975515.

Mejor trial hasta ahora: RMSE=0.647173, Parámetros={'num_leaves': 81, 'learning_rate': 0.2921368243287838, 'feature_fraction': 0.9041268776963804, 'bagging_fraction': 0.702448436521742, 'bagging_freq': 2, 'lambda_l1': 0.008900421072650216, 'lambda_l2': 8.897034525718933e-08, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 447, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.20894699872344127, 'min_gain_to_split': 0.38188439239381}

[I 2025-07-11 14:23:09,693] Trial 103 finished with value: 1.2496699695613847 and parameters: {'num_leaves': 80, 'learning_rate': 0.29747994605203193, 'feature_fraction': 0.9312648867229117, 'bagging_fraction': 0.7447721357469866, 'bagging_freq': 1, 'lambda_l1': 0.09263563417904022, 'lambda_l2': 8.306064774047514e-07, 'min_child_samples': 33, 'max_depth': 7, 'max_bin': 472, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.2977288214467109, 'min_gain_to_split': 0.4891450713229934}. Best is trial 81 with value: 0.647173334975515.

Mejor trial hasta ahora: RMSE=0.647173, Parámetros={'num_leaves': 81, 'learning_rate': 0.2921368243287838, 'feature_fraction': 0.9041268776963804, 'bagging_fraction': 0.702448436521742, 'bagging_freq': 2, 'lambda_l1': 0.008900421072650216, 'lambda_l2': 8.897034525718933e-08, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 447, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.20894699872344127, 'min_gain_to_split': 0.38188439239381}

[I 2025-07-11 14:24:25,974] Trial 104 finished with value: 0.8436216449424527 and parameters: {'num_leaves': 91, 'learning_rate': 0.2437353821205799, 'feature_fraction': 0.9490830738221971, 'bagging_fraction': 0.737359045809198, 'bagging_freq': 1, 'lambda_l1': 0.27100894966937394, 'lambda_l2': 2.5363094561679993e-07, 'min_child_samples': 29, 'max_depth': 8, 'max_bin': 439, 'min_data_in_leaf': 24, 'extra_trees': False, 'early_stopping_rounds': 30, 'path_smooth': 0.20101314512018598, 'min_gain_to_split': 0.49779024014326473}. Best is trial 81 with value: 0.647173334975515.

Mejor trial hasta ahora: RMSE=0.647173, Parámetros={'num_leaves': 81, 'learning_rate': 0.2921368243287838, 'feature_fraction': 0.9041268776963804, 'bagging_fraction': 0.702448436521742, 'bagging_freq': 2, 'lambda_l1': 0.008900421072650216, 'lambda_l2': 8.897034525718933e-08, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 447, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.20894699872344127, 'min_gain_to_split': 0.38188439239381}

[I 2025-07-11 14:25:38,372] Trial 105 finished with value: 1.4723194995403748 and parameters: {'num_leaves': 92, 'learning_rate': 0.2324663350971995, 'feature_fraction': 0.9514263747421365, 'bagging_fraction': 0.7386707411371529, 'bagging_freq': 1, 'lambda_l1': 1.6861733405476302, 'lambda_l2': 2.7050161766436705e-07, 'min_child_samples': 31, 'max_depth': 8, 'max_bin': 486, 'min_data_in_leaf': 24, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.20926082796462148, 'min_gain_to_split': 0.471138551892288}. Best is trial 81 with value: 0.647173334975515.

Mejor trial hasta ahora: RMSE=0.647173, Parámetros={'num_leaves': 81, 'learning_rate': 0.2921368243287838, 'feature_fraction': 0.9041268776963804, 'bagging_fraction': 0.702448436521742, 'bagging_freq': 2, 'lambda_l1': 0.008900421072650216, 'lambda_l2': 8.897034525718933e-08, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 447, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.20894699872344127, 'min_gain_to_split': 0.38188439239381}

[I 2025-07-11 14:26:56,938] Trial 106 finished with value: 1.1561459495795412 and parameters: {'num_leaves': 73, 'learning_rate': 0.25302034030115467, 'feature_fraction': 0.9818449698775719, 'bagging_fraction': 0.7563829454318706, 'bagging_freq': 1, 'lambda_l1': 0.2651031805754968, 'lambda_l2': 4.1130959757163624e-07, 'min_child_samples': 29, 'max_depth': 8, 'max_bin': 454, 'min_data_in_leaf': 21, 'extra_trees': False, 'early_stopping_rounds': 29, 'path_smooth': 0.2381905876305075, 'min_gain_to_split': 0.4990628651629699}. Best is trial 81 with value: 0.647173334975515.

Mejor trial hasta ahora: RMSE=0.647173, Parámetros={'num_leaves': 81, 'learning_rate': 0.2921368243287838, 'feature_fraction': 0.9041268776963804, 'bagging_fraction': 0.702448436521742, 'bagging_freq': 2, 'lambda_l1': 0.008900421072650216, 'lambda_l2': 8.897034525718933e-08, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 447, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.20894699872344127, 'min_gain_to_split': 0.38188439239381}

[I 2025-07-11 14:28:12,137] Trial 107 finished with value: 1.192929911626603 and parameters: {'num_leaves': 90, 'learning_rate': 0.22452422343150874, 'feature_fraction': 0.9591424072871623, 'bagging_fraction': 0.728832054283122, 'bagging_freq': 1, 'lambda_l1': 0.9828122850944407, 'lambda_l2': 9.27629742701605e-06, 'min_child_samples': 37, 'max_depth': 7, 'max_bin': 445, 'min_data_in_leaf': 23, 'extra_trees': False, 'early_stopping_rounds': 31, 'path_smooth': 0.42646030671841073, 'min_gain_to_split': 0.4863168973961517}. Best is trial 81 with value: 0.647173334975515.

Mejor trial hasta ahora: RMSE=0.647173, Parámetros={'num_leaves': 81, 'learning_rate': 0.2921368243287838, 'feature_fraction': 0.9041268776963804, 'bagging_fraction': 0.702448436521742, 'bagging_freq': 2, 'lambda_l1': 0.008900421072650216, 'lambda_l2': 8.897034525718933e-08, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 447, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.20894699872344127, 'min_gain_to_split': 0.38188439239381}

[I 2025-07-11 14:29:32,145] Trial 108 finished with value: 1.8887849857540833 and parameters: {'num_leaves': 96, 'learning_rate': 0.2999755063747156, 'feature_fraction': 0.9691008168736827, 'bagging_fraction': 0.7780104598301609, 'bagging_freq': 2, 'lambda_l1': 0.03541901506979175, 'lambda_l2': 2.381017635676707e-05, 'min_child_samples': 34, 'max_depth': 8, 'max_bin': 426, 'min_data_in_leaf': 26, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.27532094901934445, 'min_gain_to_split': 0.434448130721644}. Best is trial 81 with value: 0.647173334975515.

Mejor trial hasta ahora: RMSE=0.647173, Parámetros={'num_leaves': 81, 'learning_rate': 0.2921368243287838, 'feature_fraction': 0.9041268776963804, 'bagging_fraction': 0.702448436521742, 'bagging_freq': 2, 'lambda_l1': 0.008900421072650216, 'lambda_l2': 8.897034525718933e-08, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 447, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.20894699872344127, 'min_gain_to_split': 0.38188439239381}

[I 2025-07-11 14:30:56,260] Trial 109 finished with value: 1.533026774946421 and parameters: {'num_leaves': 87, 'learning_rate': 0.052126825714421364, 'feature_fraction': 0.9147337365028899, 'bagging_fraction': 0.7483577444692245, 'bagging_freq': 1, 'lambda_l1': 0.09961538293874303, 'lambda_l2': 7.86850290284641e-08, 'min_child_samples': 35, 'max_depth': 6, 'max_bin': 482, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.31802097185352945, 'min_gain_to_split': 0.45866534042325974}. Best is trial 81 with value: 0.647173334975515.

Mejor trial hasta ahora: RMSE=0.647173, Parámetros={'num_leaves': 81, 'learning_rate': 0.2921368243287838, 'feature_fraction': 0.9041268776963804, 'bagging_fraction': 0.702448436521742, 'bagging_freq': 2, 'lambda_l1': 0.008900421072650216, 'lambda_l2': 8.897034525718933e-08, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 447, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.20894699872344127, 'min_gain_to_split': 0.38188439239381}

[I 2025-07-11 14:32:16,575] Trial 110 finished with value: 0.8658356073788316 and parameters: {'num_leaves': 70, 'learning_rate': 0.2441048314722336, 'feature_fraction': 0.9404981451094189, 'bagging_fraction': 0.7234065665803339, 'bagging_freq': 1, 'lambda_l1': 0.23704381338441788, 'lambda_l2': 6.766438588635422e-07, 'min_child_samples': 30, 'max_depth': 7, 'max_bin': 462, 'min_data_in_leaf': 30, 'extra_trees': False, 'early_stopping_rounds': 29, 'path_smooth': 0.5232231193915637, 'min_gain_to_split': 0.44690766574644775}. Best is trial 81 with value: 0.647173334975515.

Mejor trial hasta ahora: RMSE=0.647173, Parámetros={'num_leaves': 81, 'learning_rate': 0.2921368243287838, 'feature_fraction': 0.9041268776963804, 'bagging_fraction': 0.702448436521742, 'bagging_freq': 2, 'lambda_l1': 0.008900421072650216, 'lambda_l2': 8.897034525718933e-08, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 447, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.20894699872344127, 'min_gain_to_split': 0.38188439239381}

[I 2025-07-11 14:33:35,556] Trial 111 finished with value: 1.0940555433994075 and parameters: {'num_leaves': 69, 'learning_rate': 0.24574038022826078, 'feature_fraction': 0.9414874912954084, 'bagging_fraction': 0.709497093125914, 'bagging_freq': 1, 'lambda_l1': 0.23676571104528854, 'lambda_l2': 6.012096242059604e-07, 'min_child_samples': 32, 'max_depth': 7, 'max_bin': 459, 'min_data_in_leaf': 31, 'extra_trees': False, 'early_stopping_rounds': 29, 'path_smooth': 0.510192555345244, 'min_gain_to_split': 0.47187129941007167}. Best is trial 81 with value: 0.647173334975515.

Mejor trial hasta ahora: RMSE=0.647173, Parámetros={'num_leaves': 81, 'learning_rate': 0.2921368243287838, 'feature_fraction': 0.9041268776963804, 'bagging_fraction': 0.702448436521742, 'bagging_freq': 2, 'lambda_l1': 0.008900421072650216, 'lambda_l2': 8.897034525718933e-08, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 447, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.20894699872344127, 'min_gain_to_split': 0.38188439239381}

[I 2025-07-11 14:34:53,966] Trial 112 finished with value: 0.8447604179828527 and parameters: {'num_leaves': 84, 'learning_rate': 0.27446588833517915, 'feature_fraction': 0.9291801395805722, 'bagging_fraction': 0.724968752524277, 'bagging_freq': 1, 'lambda_l1': 0.4407016654044665, 'lambda_l2': 1.4052144027263562e-06, 'min_child_samples': 30, 'max_depth': 7, 'max_bin': 436, 'min_data_in_leaf': 24, 'extra_trees': False, 'early_stopping_rounds': 31, 'path_smooth': 0.5142291003276089, 'min_gain_to_split': 0.4476135500209606}. Best is trial 81 with value: 0.647173334975515.

Mejor trial hasta ahora: RMSE=0.647173, Parámetros={'num_leaves': 81, 'learning_rate': 0.2921368243287838, 'feature_fraction': 0.9041268776963804, 'bagging_fraction': 0.702448436521742, 'bagging_freq': 2, 'lambda_l1': 0.008900421072650216, 'lambda_l2': 8.897034525718933e-08, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 447, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.20894699872344127, 'min_gain_to_split': 0.38188439239381}

[I 2025-07-11 14:36:17,545] Trial 113 finished with value: 0.9066420915831126 and parameters: {'num_leaves': 84, 'learning_rate': 0.2594811098863741, 'feature_fraction': 0.924577343706422, 'bagging_fraction': 0.7232350368311048, 'bagging_freq': 2, 'lambda_l1': 0.4844720731997005, 'lambda_l2': 1.1714875514145432e-06, 'min_child_samples': 30, 'max_depth': 7, 'max_bin': 440, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 31, 'path_smooth': 0.5572216998034495, 'min_gain_to_split': 0.44298961424163513}. Best is trial 81 with value: 0.647173334975515.

Mejor trial hasta ahora: RMSE=0.647173, Parámetros={'num_leaves': 81, 'learning_rate': 0.2921368243287838, 'feature_fraction': 0.9041268776963804, 'bagging_fraction': 0.702448436521742, 'bagging_freq': 2, 'lambda_l1': 0.008900421072650216, 'lambda_l2': 8.897034525718933e-08, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 447, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.20894699872344127, 'min_gain_to_split': 0.38188439239381}

[I 2025-07-11 14:37:36,138] Trial 114 finished with value: 1.0452642677529589 and parameters: {'num_leaves': 81, 'learning_rate': 0.21022975975499206, 'feature_fraction': 0.9300026099258075, 'bagging_fraction': 0.730286285355416, 'bagging_freq': 2, 'lambda_l1': 0.630755781550857, 'lambda_l2': 1.3909565889062536e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 442, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 31, 'path_smooth': 0.5606510913354947, 'min_gain_to_split': 0.4473393190951732}. Best is trial 81 with value: 0.647173334975515.

Mejor trial hasta ahora: RMSE=0.647173, Parámetros={'num_leaves': 81, 'learning_rate': 0.2921368243287838, 'feature_fraction': 0.9041268776963804, 'bagging_fraction': 0.702448436521742, 'bagging_freq': 2, 'lambda_l1': 0.008900421072650216, 'lambda_l2': 8.897034525718933e-08, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 447, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.20894699872344127, 'min_gain_to_split': 0.38188439239381}

[I 2025-07-11 14:39:21,455] Trial 115 finished with value: 1.519100712212493 and parameters: {'num_leaves': 93, 'learning_rate': 0.04159375419507631, 'feature_fraction': 0.7131902319004079, 'bagging_fraction': 0.7216248615484222, 'bagging_freq': 2, 'lambda_l1': 0.44170126397958265, 'lambda_l2': 5.540138395111506e-06, 'min_child_samples': 27, 'max_depth': 7, 'max_bin': 468, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 32, 'path_smooth': 0.5457467801770698, 'min_gain_to_split': 0.4215868124894677}. Best is trial 81 with value: 0.647173334975515.

Mejor trial hasta ahora: RMSE=0.647173, Parámetros={'num_leaves': 81, 'learning_rate': 0.2921368243287838, 'feature_fraction': 0.9041268776963804, 'bagging_fraction': 0.702448436521742, 'bagging_freq': 2, 'lambda_l1': 0.008900421072650216, 'lambda_l2': 8.897034525718933e-08, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 447, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.20894699872344127, 'min_gain_to_split': 0.38188439239381}

[I 2025-07-11 14:40:51,076] Trial 116 finished with value: 1.4472800372209391 and parameters: {'num_leaves': 84, 'learning_rate': 0.17636781239084218, 'feature_fraction': 0.9513482802212122, 'bagging_fraction': 0.7383216747277955, 'bagging_freq': 1, 'lambda_l1': 0.17086696018141523, 'lambda_l2': 2.349444623120511e-06, 'min_child_samples': 30, 'max_depth': 8, 'max_bin': 413, 'min_data_in_leaf': 30, 'extra_trees': False, 'early_stopping_rounds': 30, 'path_smooth': 0.6400907467630206, 'min_gain_to_split': 0.465681091712682}. Best is trial 81 with value: 0.647173334975515.

Mejor trial hasta ahora: RMSE=0.647173, Parámetros={'num_leaves': 81, 'learning_rate': 0.2921368243287838, 'feature_fraction': 0.9041268776963804, 'bagging_fraction': 0.702448436521742, 'bagging_freq': 2, 'lambda_l1': 0.008900421072650216, 'lambda_l2': 8.897034525718933e-08, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 447, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.20894699872344127, 'min_gain_to_split': 0.38188439239381}

[I 2025-07-11 14:41:31,937] Trial 117 finished with value: 1.3702044535043103 and parameters: {'num_leaves': 88, 'learning_rate': 0.22899509081056957, 'feature_fraction': 0.9219588436504155, 'bagging_fraction': 0.7088005168352101, 'bagging_freq': 1, 'lambda_l1': 5.12269816908948, 'lambda_l2': 1.190975169301846e-06, 'min_child_samples': 29, 'max_depth': 7, 'max_bin': 113, 'min_data_in_leaf': 24, 'extra_trees': False, 'early_stopping_rounds': 33, 'path_smooth': 0.4956993544447832, 'min_gain_to_split': 0.4991903428996021}. Best is trial 81 with value: 0.647173334975515.

Mejor trial hasta ahora: RMSE=0.647173, Parámetros={'num_leaves': 81, 'learning_rate': 0.2921368243287838, 'feature_fraction': 0.9041268776963804, 'bagging_fraction': 0.702448436521742, 'bagging_freq': 2, 'lambda_l1': 0.008900421072650216, 'lambda_l2': 8.897034525718933e-08, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 447, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.20894699872344127, 'min_gain_to_split': 0.38188439239381}

[I 2025-07-11 14:43:08,779] Trial 118 finished with value: 1.6446130489994473 and parameters: {'num_leaves': 91, 'learning_rate': 0.07349130694428724, 'feature_fraction': 0.9648038046118904, 'bagging_fraction': 0.7348757750686606, 'bagging_freq': 2, 'lambda_l1': 1.5155613982591283, 'lambda_l2': 2.3295430986717927e-07, 'min_child_samples': 30, 'max_depth': 6, 'max_bin': 492, 'min_data_in_leaf': 27, 'extra_trees': False, 'early_stopping_rounds': 28, 'path_smooth': 0.5233708980567399, 'min_gain_to_split': 0.4520972094599084}. Best is trial 81 with value: 0.647173334975515.

Mejor trial hasta ahora: RMSE=0.647173, Parámetros={'num_leaves': 81, 'learning_rate': 0.2921368243287838, 'feature_fraction': 0.9041268776963804, 'bagging_fraction': 0.702448436521742, 'bagging_freq': 2, 'lambda_l1': 0.008900421072650216, 'lambda_l2': 8.897034525718933e-08, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 447, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.20894699872344127, 'min_gain_to_split': 0.38188439239381}

[I 2025-07-11 14:44:26,387] Trial 119 finished with value: 0.8685522836521151 and parameters: {'num_leaves': 86, 'learning_rate': 0.25964147677468435, 'feature_fraction': 0.9355838999088015, 'bagging_fraction': 0.7249485633906366, 'bagging_freq': 1, 'lambda_l1': 0.3569695256721286, 'lambda_l2': 7.524792351197857e-07, 'min_child_samples': 31, 'max_depth': 7, 'max_bin': 419, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 29, 'path_smooth': 0.472509651918253, 'min_gain_to_split': 0.4322367319249205}. Best is trial 81 with value: 0.647173334975515.

Mejor trial hasta ahora: RMSE=0.647173, Parámetros={'num_leaves': 81, 'learning_rate': 0.2921368243287838, 'feature_fraction': 0.9041268776963804, 'bagging_fraction': 0.702448436521742, 'bagging_freq': 2, 'lambda_l1': 0.008900421072650216, 'lambda_l2': 8.897034525718933e-08, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 447, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.20894699872344127, 'min_gain_to_split': 0.38188439239381}

[I 2025-07-11 14:45:35,442] Trial 120 finished with value: 1.5435996710813473 and parameters: {'num_leaves': 86, 'learning_rate': 0.19789871381567622, 'feature_fraction': 0.9352978255498443, 'bagging_fraction': 0.7234950984238879, 'bagging_freq': 9, 'lambda_l1': 3.3527372470545678, 'lambda_l2': 6.031309753803464e-07, 'min_child_samples': 27, 'max_depth': 7, 'max_bin': 423, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 30, 'path_smooth': 0.45653138608732147, 'min_gain_to_split': 0.4348423477796788}. Best is trial 81 with value: 0.647173334975515.

Mejor trial hasta ahora: RMSE=0.647173, Parámetros={'num_leaves': 81, 'learning_rate': 0.2921368243287838, 'feature_fraction': 0.9041268776963804, 'bagging_fraction': 0.702448436521742, 'bagging_freq': 2, 'lambda_l1': 0.008900421072650216, 'lambda_l2': 8.897034525718933e-08, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 447, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.20894699872344127, 'min_gain_to_split': 0.38188439239381}

[I 2025-07-11 14:46:57,793] Trial 121 finished with value: 1.3654866637562788 and parameters: {'num_leaves': 79, 'learning_rate': 0.2548943546502971, 'feature_fraction': 0.936630754618214, 'bagging_fraction': 0.7451807632814111, 'bagging_freq': 1, 'lambda_l1': 0.3308075402125222, 'lambda_l2': 1.0419474191345094e-06, 'min_child_samples': 31, 'max_depth': 7, 'max_bin': 438, 'min_data_in_leaf': 99, 'extra_trees': False, 'early_stopping_rounds': 29, 'path_smooth': 0.6020018856759086, 'min_gain_to_split': 0.48643744183835724}. Best is trial 81 with value: 0.647173334975515.

Mejor trial hasta ahora: RMSE=0.647173, Parámetros={'num_leaves': 81, 'learning_rate': 0.2921368243287838, 'feature_fraction': 0.9041268776963804, 'bagging_fraction': 0.702448436521742, 'bagging_freq': 2, 'lambda_l1': 0.008900421072650216, 'lambda_l2': 8.897034525718933e-08, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 447, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.20894699872344127, 'min_gain_to_split': 0.38188439239381}

[I 2025-07-11 14:48:04,491] Trial 122 finished with value: 1.4172036784863953 and parameters: {'num_leaves': 83, 'learning_rate': 0.2765329245839071, 'feature_fraction': 0.924991365467851, 'bagging_fraction': 0.7277236628116431, 'bagging_freq': 1, 'lambda_l1': 0.799338217650245, 'lambda_l2': 1.8340235844465047e-06, 'min_child_samples': 31, 'max_depth': 7, 'max_bin': 462, 'min_data_in_leaf': 62, 'extra_trees': False, 'early_stopping_rounds': 31, 'path_smooth': 0.5678848777773154, 'min_gain_to_split': 0.44479204939775524}. Best is trial 81 with value: 0.647173334975515.

Mejor trial hasta ahora: RMSE=0.647173, Parámetros={'num_leaves': 81, 'learning_rate': 0.2921368243287838, 'feature_fraction': 0.9041268776963804, 'bagging_fraction': 0.702448436521742, 'bagging_freq': 2, 'lambda_l1': 0.008900421072650216, 'lambda_l2': 8.897034525718933e-08, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 447, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.20894699872344127, 'min_gain_to_split': 0.38188439239381}

[I 2025-07-11 14:49:26,599] Trial 123 finished with value: 0.5252677588695865 and parameters: {'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 14:50:41,040] Trial 124 finished with value: 2.001423738294922 and parameters: {'num_leaves': 86, 'learning_rate': 0.24488835589031074, 'feature_fraction': 0.976442303318429, 'bagging_fraction': 0.7193754857453052, 'bagging_freq': 2, 'lambda_l1': 0.13346821740008738, 'lambda_l2': 3.872975867760731e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 430, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.6564255407804036, 'min_gain_to_split': 0.4275299160155126}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 14:52:14,357] Trial 125 finished with value: 1.098589100011261 and parameters: {'num_leaves': 93, 'learning_rate': 0.22587496902700657, 'feature_fraction': 0.9608500681557595, 'bagging_fraction': 0.7081859999215581, 'bagging_freq': 1, 'lambda_l1': 0.055422694261012935, 'lambda_l2': 3.1797624557438504e-07, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 437, 'min_data_in_leaf': 80, 'extra_trees': False, 'early_stopping_rounds': 28, 'path_smooth': 0.586134650694768, 'min_gain_to_split': 0.4694071159036889}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 14:53:48,403] Trial 126 finished with value: 1.0786622792157095 and parameters: {'num_leaves': 75, 'learning_rate': 0.24315437370718002, 'feature_fraction': 0.9546059502746319, 'bagging_fraction': 0.7167784453683387, 'bagging_freq': 1, 'lambda_l1': 0.4055029719708558, 'lambda_l2': 7.777718333692474e-07, 'min_child_samples': 29, 'max_depth': 8, 'max_bin': 421, 'min_data_in_leaf': 25, 'extra_trees': False, 'early_stopping_rounds': 34, 'path_smooth': 0.5394609085956797, 'min_gain_to_split': 0.4568207335793891}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 14:55:12,652] Trial 127 finished with value: 1.214902969641426 and parameters: {'num_leaves': 90, 'learning_rate': 0.27983041650894436, 'feature_fraction': 0.9124428419315302, 'bagging_fraction': 0.7329221708552693, 'bagging_freq': 2, 'lambda_l1': 0.11823021841367179, 'lambda_l2': 1.685731182027204e-07, 'min_child_samples': 24, 'max_depth': 6, 'max_bin': 476, 'min_data_in_leaf': 30, 'extra_trees': False, 'early_stopping_rounds': 30, 'path_smooth': 0.47436063649686516, 'min_gain_to_split': 0.47461100673118944}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 14:56:53,682] Trial 128 finished with value: 0.681823407750817 and parameters: {'num_leaves': 82, 'learning_rate': 0.2587922357925225, 'feature_fraction': 0.9483037446425259, 'bagging_fraction': 0.768117319603211, 'bagging_freq': 1, 'lambda_l1': 0.18360681886159458, 'lambda_l2': 7.827205732427661e-07, 'min_child_samples': 27, 'max_depth': 7, 'max_bin': 447, 'min_data_in_leaf': 94, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.6392282869691632, 'min_gain_to_split': 0.44369059533634}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 14:58:15,361] Trial 129 finished with value: 1.4870237008871154 and parameters: {'num_leaves': 81, 'learning_rate': 0.2989955103564034, 'feature_fraction': 0.9295999585823707, 'bagging_fraction': 0.714206257158862, 'bagging_freq': 1, 'lambda_l1': 1.1888209657575182, 'lambda_l2': 2.776745585110663e-06, 'min_child_samples': 27, 'max_depth': 7, 'max_bin': 444, 'min_data_in_leaf': 93, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.6263432182856169, 'min_gain_to_split': 0.44348750952002597}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 14:59:54,339] Trial 130 finished with value: 1.6913564480525523 and parameters: {'num_leaves': 84, 'learning_rate': 0.21423939657009491, 'feature_fraction': 0.9686030496233529, 'bagging_fraction': 0.7257825339290522, 'bagging_freq': 2, 'lambda_l1': 0.054870971465905014, 'lambda_l2': 4.0584702264528023e-07, 'min_child_samples': 30, 'max_depth': 7, 'max_bin': 452, 'min_data_in_leaf': 69, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.6822444427557497, 'min_gain_to_split': 0.43232474977964824}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 15:01:17,068] Trial 131 finished with value: 1.3617915779815037 and parameters: {'num_leaves': 87, 'learning_rate': 0.2621558854682064, 'feature_fraction': 0.9496033850485273, 'bagging_fraction': 0.7672522462442138, 'bagging_freq': 1, 'lambda_l1': 0.1943105395827231, 'lambda_l2': 4.677476332055887e-07, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 431, 'min_data_in_leaf': 85, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.6618073610109213, 'min_gain_to_split': 0.4617053904569718}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 15:02:32,442] Trial 132 finished with value: 1.2722668835786926 and parameters: {'num_leaves': 79, 'learning_rate': 0.25915568482612633, 'feature_fraction': 0.9377512214543808, 'bagging_fraction': 0.7331176248293414, 'bagging_freq': 1, 'lambda_l1': 0.502342469426936, 'lambda_l2': 6.67856290190598e-07, 'min_child_samples': 25, 'max_depth': 7, 'max_bin': 417, 'min_data_in_leaf': 96, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.8020844669532997, 'min_gain_to_split': 0.48246591305977776}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 15:03:53,068] Trial 133 finished with value: 1.52968937036831 and parameters: {'num_leaves': 83, 'learning_rate': 0.2402939670190775, 'feature_fraction': 0.9581901788134827, 'bagging_fraction': 0.7571538233846964, 'bagging_freq': 1, 'lambda_l1': 0.3286167617077192, 'lambda_l2': 2.1977911538163445e-07, 'min_child_samples': 32, 'max_depth': 7, 'max_bin': 458, 'min_data_in_leaf': 73, 'extra_trees': False, 'early_stopping_rounds': 28, 'path_smooth': 0.6244284077041545, 'min_gain_to_split': 0.4174706905269238}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 15:05:57,608] Trial 134 finished with value: 1.0407218875985405 and parameters: {'num_leaves': 85, 'learning_rate': 0.2741367415210655, 'feature_fraction': 0.9474235044238831, 'bagging_fraction': 0.74402704726668, 'bagging_freq': 1, 'lambda_l1': 0.09781383206574082, 'lambda_l2': 8.597316697485918e-07, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 442, 'min_data_in_leaf': 26, 'extra_trees': False, 'early_stopping_rounds': 33, 'path_smooth': 0.6946637925828867, 'min_gain_to_split': 0.4496321096985223}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 15:07:08,681] Trial 135 finished with value: 1.1190730517590388 and parameters: {'num_leaves': 88, 'learning_rate': 0.28459349686368096, 'feature_fraction': 0.9225230583347088, 'bagging_fraction': 0.7050503388335893, 'bagging_freq': 1, 'lambda_l1': 0.1866834985671066, 'lambda_l2': 1.1140676714711466e-07, 'min_child_samples': 29, 'max_depth': 6, 'max_bin': 474, 'min_data_in_leaf': 35, 'extra_trees': False, 'early_stopping_rounds': 29, 'path_smooth': 0.7456942959031226, 'min_gain_to_split': 0.45885993336849423}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 15:08:20,659] Trial 136 finished with value: 1.2682747663132174 and parameters: {'num_leaves': 81, 'learning_rate': 0.22685125217901767, 'feature_fraction': 0.9043061094485474, 'bagging_fraction': 0.718255955072872, 'bagging_freq': 1, 'lambda_l1': 0.7680909787951281, 'lambda_l2': 1.7676621279561587e-06, 'min_child_samples': 30, 'max_depth': 7, 'max_bin': 428, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.578272250176928, 'min_gain_to_split': 0.47691484608462625}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 15:09:35,103] Trial 137 finished with value: 1.8236683836744845 and parameters: {'num_leaves': 91, 'learning_rate': 0.1902386065177316, 'feature_fraction': 0.9923759768200843, 'bagging_fraction': 0.7235347610673295, 'bagging_freq': 1, 'lambda_l1': 0.319153915695391, 'lambda_l2': 4.317616579974021e-06, 'min_child_samples': 31, 'max_depth': 7, 'max_bin': 410, 'min_data_in_leaf': 23, 'extra_trees': False, 'early_stopping_rounds': 32, 'path_smooth': 0.5269662688097313, 'min_gain_to_split': 0.44195819840138906}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 15:10:52,015] Trial 138 finished with value: 1.1172100506584859 and parameters: {'num_leaves': 76, 'learning_rate': 0.25914777776686054, 'feature_fraction': 0.9728591551266592, 'bagging_fraction': 0.7000165839010531, 'bagging_freq': 2, 'lambda_l1': 0.6089166623491054, 'lambda_l2': 3.485063941893485e-07, 'min_child_samples': 35, 'max_depth': 8, 'max_bin': 454, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.4843480190048339, 'min_gain_to_split': 0.46770087783641107}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 15:13:09,255] Trial 139 finished with value: 0.7777686998304933 and parameters: {'num_leaves': 86, 'learning_rate': 0.20406827368903552, 'feature_fraction': 0.9304280741337247, 'bagging_fraction': 0.751930014058735, 'bagging_freq': 1, 'lambda_l1': 0.07796668376295068, 'lambda_l2': 5.9133827207005065e-08, 'min_child_samples': 25, 'max_depth': 7, 'max_bin': 448, 'min_data_in_leaf': 31, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.1776908263485876, 'min_gain_to_split': 0.427335947679028}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 15:14:51,133] Trial 140 finished with value: 0.9042771654233788 and parameters: {'num_leaves': 82, 'learning_rate': 0.2034435751289246, 'feature_fraction': 0.9291774710787586, 'bagging_fraction': 0.7533773649645893, 'bagging_freq': 1, 'lambda_l1': 0.07830754071221604, 'lambda_l2': 1.4866262125629024e-07, 'min_child_samples': 24, 'max_depth': 7, 'max_bin': 448, 'min_data_in_leaf': 31, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.44164591093780114, 'min_gain_to_split': 0.4237768288604922}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 15:16:09,246] Trial 141 finished with value: 1.6067255022177462 and parameters: {'num_leaves': 82, 'learning_rate': 0.20528487969214365, 'feature_fraction': 0.9304929434868453, 'bagging_fraction': 0.7531528006694195, 'bagging_freq': 1, 'lambda_l1': 0.07183868276464664, 'lambda_l2': 6.105430544524767e-08, 'min_child_samples': 25, 'max_depth': 7, 'max_bin': 446, 'min_data_in_leaf': 55, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.44039566000679453, 'min_gain_to_split': 0.4232608014581371}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 15:17:34,164] Trial 142 finished with value: 1.1673862489539464 and parameters: {'num_leaves': 79, 'learning_rate': 0.2425788130396038, 'feature_fraction': 0.915986158049958, 'bagging_fraction': 0.7743925751457529, 'bagging_freq': 1, 'lambda_l1': 0.055672631648660174, 'lambda_l2': 1.5356482322869308e-07, 'min_child_samples': 22, 'max_depth': 7, 'max_bin': 437, 'min_data_in_leaf': 31, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.45899170861215155, 'min_gain_to_split': 0.4005509624530116}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 15:19:24,598] Trial 143 finished with value: 0.8747238187479359 and parameters: {'num_leaves': 71, 'learning_rate': 0.2196839143404392, 'feature_fraction': 0.9385461049863338, 'bagging_fraction': 0.7646223280792142, 'bagging_freq': 1, 'lambda_l1': 0.013847315087627867, 'lambda_l2': 5.450328386918628e-08, 'min_child_samples': 25, 'max_depth': 7, 'max_bin': 465, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.5486603445051216, 'min_gain_to_split': 0.4128500824196965}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 15:20:45,819] Trial 144 finished with value: 1.28558134705921 and parameters: {'num_leaves': 70, 'learning_rate': 0.22021516307147926, 'feature_fraction': 0.9360149474075095, 'bagging_fraction': 0.7650713743865057, 'bagging_freq': 1, 'lambda_l1': 0.014251578499729646, 'lambda_l2': 6.257303500566421e-08, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 452, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.5100389050173681, 'min_gain_to_split': 0.4259589701865469}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 15:22:15,917] Trial 145 finished with value: 1.1878619998647162 and parameters: {'num_leaves': 86, 'learning_rate': 0.16776594697524805, 'feature_fraction': 0.6099847306375522, 'bagging_fraction': 0.7994491973498343, 'bagging_freq': 1, 'lambda_l1': 0.0067049201474235, 'lambda_l2': 1.9607935359794756e-07, 'min_child_samples': 23, 'max_depth': 7, 'max_bin': 427, 'min_data_in_leaf': 30, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.39871718395415384, 'min_gain_to_split': 0.4124533528440044}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 15:24:41,280] Trial 146 finished with value: 1.6121880193060079 and parameters: {'num_leaves': 84, 'learning_rate': 0.025144433913963347, 'feature_fraction': 0.9214739228655356, 'bagging_fraction': 0.7605835574728622, 'bagging_freq': 2, 'lambda_l1': 0.02305934015307519, 'lambda_l2': 4.023450241625621e-08, 'min_child_samples': 24, 'max_depth': 7, 'max_bin': 481, 'min_data_in_leaf': 36, 'extra_trees': False, 'early_stopping_rounds': 30, 'path_smooth': 0.5584164599922619, 'min_gain_to_split': 0.4359438073273575}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 15:25:56,551] Trial 147 finished with value: 1.2079341965460362 and parameters: {'num_leaves': 86, 'learning_rate': 0.19405586695401844, 'feature_fraction': 0.9095266101725956, 'bagging_fraction': 0.7382025540143393, 'bagging_freq': 1, 'lambda_l1': 0.08127281540803775, 'lambda_l2': 1.490055070501432e-07, 'min_child_samples': 25, 'max_depth': 6, 'max_bin': 446, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.591669809102381, 'min_gain_to_split': 0.4146442484714083}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 15:27:39,909] Trial 148 finished with value: 1.857183515736282 and parameters: {'num_leaves': 67, 'learning_rate': 0.299989619507627, 'feature_fraction': 0.9616558416741079, 'bagging_fraction': 0.7857796759270537, 'bagging_freq': 1, 'lambda_l1': 0.03966273170434715, 'lambda_l2': 5.112156793025803e-08, 'min_child_samples': 27, 'max_depth': 7, 'max_bin': 468, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 28, 'path_smooth': 0.5377185514459998, 'min_gain_to_split': 0.44779021241212247}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 15:31:07,671] Trial 149 finished with value: 1.0222656739733815 and parameters: {'num_leaves': 88, 'learning_rate': 0.23492101575239813, 'feature_fraction': 0.9005863982016183, 'bagging_fraction': 0.7090750963326605, 'bagging_freq': 1, 'lambda_l1': 0.1191104947297182, 'lambda_l2': 6.875301261683718e-05, 'min_child_samples': 24, 'max_depth': 8, 'max_bin': 435, 'min_data_in_leaf': 58, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.49337770463246783, 'min_gain_to_split': 0.39437487244532127}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 15:33:48,819] Trial 150 finished with value: 1.2799055213027795 and parameters: {'num_leaves': 72, 'learning_rate': 0.20706902737357485, 'feature_fraction': 0.9284343188410791, 'bagging_fraction': 0.7294055945134268, 'bagging_freq': 2, 'lambda_l1': 0.24758707179848807, 'lambda_l2': 1.042593666403294e-07, 'min_child_samples': 25, 'max_depth': 7, 'max_bin': 418, 'min_data_in_leaf': 27, 'extra_trees': False, 'early_stopping_rounds': 31, 'path_smooth': 0.18009807057508526, 'min_gain_to_split': 0.4293026595242161}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 15:35:09,594] Trial 151 finished with value: 0.9103684316975185 and parameters: {'num_leaves': 81, 'learning_rate': 0.2827271445948046, 'feature_fraction': 0.9448363257279191, 'bagging_fraction': 0.7504525724091077, 'bagging_freq': 1, 'lambda_l1': 0.39346641923506065, 'lambda_l2': 1.0024687539190923e-06, 'min_child_samples': 36, 'max_depth': 7, 'max_bin': 468, 'min_data_in_leaf': 51, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.7199129177607518, 'min_gain_to_split': 0.45562087342701474}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 15:36:22,032] Trial 152 finished with value: 1.730641663703457 and parameters: {'num_leaves': 82, 'learning_rate': 0.2525663687469929, 'feature_fraction': 0.9410519814291366, 'bagging_fraction': 0.7534453304743842, 'bagging_freq': 1, 'lambda_l1': 0.12316748475946096, 'lambda_l2': 9.574656732696398e-07, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 463, 'min_data_in_leaf': 50, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.7329336416848362, 'min_gain_to_split': 0.4569563853653234}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 15:37:39,807] Trial 153 finished with value: 0.7951442954222971 and parameters: {'num_leaves': 91, 'learning_rate': 0.278589335483965, 'feature_fraction': 0.9524705530493325, 'bagging_fraction': 0.7690258225726682, 'bagging_freq': 1, 'lambda_l1': 1.1182577325280907, 'lambda_l2': 4.777588489870184e-07, 'min_child_samples': 36, 'max_depth': 7, 'max_bin': 475, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 29, 'path_smooth': 0.711934332232744, 'min_gain_to_split': 0.43442157906744966}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 15:38:57,931] Trial 154 finished with value: 1.1106705657773293 and parameters: {'num_leaves': 60, 'learning_rate': 0.23439828375722807, 'feature_fraction': 0.9540081276115185, 'bagging_fraction': 0.7831103249416891, 'bagging_freq': 1, 'lambda_l1': 1.3337547928815383, 'lambda_l2': 5.151455170558514e-07, 'min_child_samples': 36, 'max_depth': 7, 'max_bin': 475, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 30, 'path_smooth': 0.7193764921201228, 'min_gain_to_split': 0.4387207096811179}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 15:40:06,493] Trial 155 finished with value: 0.9437415854920236 and parameters: {'num_leaves': 95, 'learning_rate': 0.28204330774687303, 'feature_fraction': 0.9377988379475625, 'bagging_fraction': 0.7630235609463293, 'bagging_freq': 1, 'lambda_l1': 2.644259665632741, 'lambda_l2': 3.0449992871976996e-07, 'min_child_samples': 39, 'max_depth': 7, 'max_bin': 449, 'min_data_in_leaf': 31, 'extra_trees': False, 'early_stopping_rounds': 29, 'path_smooth': 0.8007906112629618, 'min_gain_to_split': 0.4218434736875885}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 15:42:15,702] Trial 156 finished with value: 1.6869707842997912 and parameters: {'num_leaves': 92, 'learning_rate': 0.010457499229045713, 'feature_fraction': 0.9252923444637782, 'bagging_fraction': 0.7902270607581598, 'bagging_freq': 1, 'lambda_l1': 0.37205994132254994, 'lambda_l2': 1.1528752993181065e-07, 'min_child_samples': 22, 'max_depth': 7, 'max_bin': 488, 'min_data_in_leaf': 39, 'extra_trees': False, 'early_stopping_rounds': 32, 'path_smooth': 0.7049942227880257, 'min_gain_to_split': 0.40394751536100926}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 15:43:22,994] Trial 157 finished with value: 1.9372844126450501 and parameters: {'num_leaves': 80, 'learning_rate': 0.2516246522586454, 'feature_fraction': 0.9807473191193021, 'bagging_fraction': 0.7688210338831091, 'bagging_freq': 1, 'lambda_l1': 0.9820261933055595, 'lambda_l2': 4.921214586981821e-07, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 438, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 28, 'path_smooth': 0.6590260339098977, 'min_gain_to_split': 0.4495110687442958}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 15:44:39,617] Trial 158 finished with value: 1.2253992940259055 and parameters: {'num_leaves': 83, 'learning_rate': 0.2221955940681534, 'feature_fraction': 0.950551021248457, 'bagging_fraction': 0.7571111455941073, 'bagging_freq': 2, 'lambda_l1': 0.16767193897481694, 'lambda_l2': 2.267668987538327e-07, 'min_child_samples': 36, 'max_depth': 7, 'max_bin': 458, 'min_data_in_leaf': 26, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.7461045712544472, 'min_gain_to_split': 0.4378719867463917}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 15:45:46,774] Trial 159 finished with value: 1.0893484075521822 and parameters: {'num_leaves': 90, 'learning_rate': 0.28303935215107495, 'feature_fraction': 0.9654464086672183, 'bagging_fraction': 0.7145228755016682, 'bagging_freq': 1, 'lambda_l1': 0.6975138799728227, 'lambda_l2': 2.352632041219209e-06, 'min_child_samples': 37, 'max_depth': 6, 'max_bin': 471, 'min_data_in_leaf': 36, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.6097588849220048, 'min_gain_to_split': 0.41415136603631447}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 15:47:25,161] Trial 160 finished with value: 1.5383524755438385 and parameters: {'num_leaves': 85, 'learning_rate': 0.09647160140992106, 'feature_fraction': 0.93282318802725, 'bagging_fraction': 0.7749229508227061, 'bagging_freq': 1, 'lambda_l1': 0.07782160336360174, 'lambda_l2': 7.99410710797473e-08, 'min_child_samples': 23, 'max_depth': 8, 'max_bin': 442, 'min_data_in_leaf': 61, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.5218474255361915, 'min_gain_to_split': 0.38585974913511484}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 15:48:34,422] Trial 161 finished with value: 1.0802856231368598 and parameters: {'num_leaves': 89, 'learning_rate': 0.29975931398252065, 'feature_fraction': 0.9443490330042884, 'bagging_fraction': 0.7498381841615361, 'bagging_freq': 1, 'lambda_l1': 0.22941077148758984, 'lambda_l2': 1.0361533061679975e-06, 'min_child_samples': 27, 'max_depth': 7, 'max_bin': 481, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.7617270784098652, 'min_gain_to_split': 0.46037097330460175}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 15:49:49,999] Trial 162 finished with value: 1.161434901477498 and parameters: {'num_leaves': 87, 'learning_rate': 0.26394173240071217, 'feature_fraction': 0.9576535447161612, 'bagging_fraction': 0.7376897933481726, 'bagging_freq': 1, 'lambda_l1': 0.32463037914139925, 'lambda_l2': 7.400554267276222e-07, 'min_child_samples': 34, 'max_depth': 7, 'max_bin': 467, 'min_data_in_leaf': 52, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.6785212040468074, 'min_gain_to_split': 0.4333769518947871}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 15:51:08,247] Trial 163 finished with value: 0.6792114740610598 and parameters: {'num_leaves': 93, 'learning_rate': 0.2729228937225971, 'feature_fraction': 0.915778693461039, 'bagging_fraction': 0.7448179220771466, 'bagging_freq': 1, 'lambda_l1': 0.5085256557486282, 'lambda_l2': 1.6554956266933974e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 500, 'min_data_in_leaf': 30, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.5485314280848503, 'min_gain_to_split': 0.4679204292593358}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 15:52:29,850] Trial 164 finished with value: 0.9982528429678199 and parameters: {'num_leaves': 99, 'learning_rate': 0.24528995847090584, 'feature_fraction': 0.9182600114423473, 'bagging_fraction': 0.7423829214288087, 'bagging_freq': 1, 'lambda_l1': 0.4561490260170304, 'lambda_l2': 3.8107137497300476e-07, 'min_child_samples': 29, 'max_depth': 7, 'max_bin': 428, 'min_data_in_leaf': 66, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.5554264966622426, 'min_gain_to_split': 0.4472779237268437}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 15:54:01,289] Trial 165 finished with value: 1.1976229727436414 and parameters: {'num_leaves': 93, 'learning_rate': 0.2607339014061529, 'feature_fraction': 0.9097178317204803, 'bagging_fraction': 0.7319269461970751, 'bagging_freq': 1, 'lambda_l1': 0.025416122235178047, 'lambda_l2': 1.4587401710134797e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 497, 'min_data_in_leaf': 31, 'extra_trees': False, 'early_stopping_rounds': 29, 'path_smooth': 0.5760721529217725, 'min_gain_to_split': 0.46923839847853305}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 15:55:46,889] Trial 166 finished with value: 1.0990371989085594 and parameters: {'num_leaves': 94, 'learning_rate': 0.2828412509072237, 'feature_fraction': 0.9292089174118743, 'bagging_fraction': 0.724029204271843, 'bagging_freq': 1, 'lambda_l1': 0.13897496054422348, 'lambda_l2': 2.5654439059580103e-06, 'min_child_samples': 40, 'max_depth': 7, 'max_bin': 452, 'min_data_in_leaf': 25, 'extra_trees': False, 'early_stopping_rounds': 28, 'path_smooth': 0.8726070114288048, 'min_gain_to_split': 0.45282999812185515}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 15:57:45,826] Trial 167 finished with value: 1.0787945131548253 and parameters: {'num_leaves': 78, 'learning_rate': 0.2343795570041881, 'feature_fraction': 0.9393054740826391, 'bagging_fraction': 0.7600065073186429, 'bagging_freq': 2, 'lambda_l1': 0.011577316889841248, 'lambda_l2': 6.752783761194842e-06, 'min_child_samples': 25, 'max_depth': 7, 'max_bin': 489, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 31, 'path_smooth': 0.6192627339509243, 'min_gain_to_split': 0.42747385879476824}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 15:59:43,069] Trial 168 finished with value: 1.0624838321266215 and parameters: {'num_leaves': 97, 'learning_rate': 0.21334981848126258, 'feature_fraction': 0.9169972997868429, 'bagging_fraction': 0.7711959898420025, 'bagging_freq': 1, 'lambda_l1': 0.6145613055922826, 'lambda_l2': 7.330603339435792e-07, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 498, 'min_data_in_leaf': 30, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.5048036792706111, 'min_gain_to_split': 0.408587841150768}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 16:00:48,283] Trial 169 finished with value: 1.2895424825897264 and parameters: {'num_leaves': 81, 'learning_rate': 0.27541809993656957, 'feature_fraction': 0.9485643343706626, 'bagging_fraction': 0.7120006764923759, 'bagging_freq': 1, 'lambda_l1': 9.226361095992266, 'lambda_l2': 4.632914614480259e-08, 'min_child_samples': 27, 'max_depth': 7, 'max_bin': 205, 'min_data_in_leaf': 22, 'extra_trees': False, 'early_stopping_rounds': 30, 'path_smooth': 0.6432401584848475, 'min_gain_to_split': 0.46753152962138267}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 16:02:20,219] Trial 170 finished with value: 1.2136522167812909 and parameters: {'num_leaves': 91, 'learning_rate': 0.2546502329592111, 'feature_fraction': 0.8969009948473986, 'bagging_fraction': 0.7416227242486113, 'bagging_freq': 1, 'lambda_l1': 1.9754364327275047, 'lambda_l2': 1.4593065130011586e-07, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 478, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.47430663054594485, 'min_gain_to_split': 0.44110355618179253}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 16:03:47,932] Trial 171 finished with value: 0.6061764306495634 and parameters: {'num_leaves': 87, 'learning_rate': 0.2784334296007914, 'feature_fraction': 0.9347228709010634, 'bagging_fraction': 0.744927129662371, 'bagging_freq': 1, 'lambda_l1': 0.18623296115718516, 'lambda_l2': 3.6987776595966475e-06, 'min_child_samples': 35, 'max_depth': 7, 'max_bin': 462, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5411040042839819, 'min_gain_to_split': 0.47826265299277887}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 16:04:55,997] Trial 172 finished with value: 0.8177904848660796 and parameters: {'num_leaves': 84, 'learning_rate': 0.2989322120174586, 'feature_fraction': 0.9326006779051561, 'bagging_fraction': 0.749462313292161, 'bagging_freq': 1, 'lambda_l1': 0.2126867463816691, 'lambda_l2': 4.4128495755166565e-06, 'min_child_samples': 37, 'max_depth': 7, 'max_bin': 459, 'min_data_in_leaf': 27, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5373777992233708, 'min_gain_to_split': 0.47729885592786964}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 16:06:01,520] Trial 173 finished with value: 1.1234744405384105 and parameters: {'num_leaves': 85, 'learning_rate': 0.2967449270516954, 'feature_fraction': 0.9250952561979521, 'bagging_fraction': 0.7375552376374459, 'bagging_freq': 1, 'lambda_l1': 0.05326466016408076, 'lambda_l2': 1.0719169940078816e-05, 'min_child_samples': 37, 'max_depth': 7, 'max_bin': 459, 'min_data_in_leaf': 27, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.5425920656649622, 'min_gain_to_split': 0.4765097706363772}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 16:07:03,305] Trial 174 finished with value: 0.8524484794846666 and parameters: {'num_leaves': 87, 'learning_rate': 0.2639123556937464, 'feature_fraction': 0.7437407427708962, 'bagging_fraction': 0.7459612015492644, 'bagging_freq': 1, 'lambda_l1': 0.004461210227241327, 'lambda_l2': 4.578582466845844e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 446, 'min_data_in_leaf': 24, 'extra_trees': False, 'early_stopping_rounds': 29, 'path_smooth': 0.5362989789793492, 'min_gain_to_split': 0.4796313477625221}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 16:08:12,510] Trial 175 finished with value: 1.238355782325476 and parameters: {'num_leaves': 88, 'learning_rate': 0.2431185761245765, 'feature_fraction': 0.696300548719269, 'bagging_fraction': 0.7478803387722451, 'bagging_freq': 1, 'lambda_l1': 0.0038374963606086637, 'lambda_l2': 2.1747965714672398e-05, 'min_child_samples': 35, 'max_depth': 7, 'max_bin': 449, 'min_data_in_leaf': 23, 'extra_trees': False, 'early_stopping_rounds': 29, 'path_smooth': 0.5191019532814269, 'min_gain_to_split': 0.4998327155041381}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 16:09:17,660] Trial 176 finished with value: 0.9800440834279884 and parameters: {'num_leaves': 91, 'learning_rate': 0.2657574788499782, 'feature_fraction': 0.725292802838541, 'bagging_fraction': 0.7558176717015679, 'bagging_freq': 1, 'lambda_l1': 0.015350421477152518, 'lambda_l2': 4.160256474251509e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 432, 'min_data_in_leaf': 25, 'extra_trees': False, 'early_stopping_rounds': 28, 'path_smooth': 0.5322622821233587, 'min_gain_to_split': 0.4799764084132561}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 16:10:20,497] Trial 177 finished with value: 1.2536881403239968 and parameters: {'num_leaves': 86, 'learning_rate': 0.28215873755925674, 'feature_fraction': 0.7539379358058902, 'bagging_fraction': 0.7660972211092864, 'bagging_freq': 1, 'lambda_l1': 0.007608789088741766, 'lambda_l2': 1.5791041298433794e-05, 'min_child_samples': 29, 'max_depth': 9, 'max_bin': 458, 'min_data_in_leaf': 20, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.49207317560124386, 'min_gain_to_split': 0.4806497245722825}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 16:11:29,085] Trial 178 finished with value: 0.8873523906070894 and parameters: {'num_leaves': 88, 'learning_rate': 0.2998002037660639, 'feature_fraction': 0.9363421836966846, 'bagging_fraction': 0.7342801520391792, 'bagging_freq': 1, 'lambda_l1': 0.20777102508599699, 'lambda_l2': 4.086164576899669e-06, 'min_child_samples': 37, 'max_depth': 7, 'max_bin': 447, 'min_data_in_leaf': 24, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.5842563268405547, 'min_gain_to_split': 0.46804403911296094}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 16:12:37,701] Trial 179 finished with value: 1.1291680127639854 and parameters: {'num_leaves': 90, 'learning_rate': 0.2811718987527961, 'feature_fraction': 0.6252235788540342, 'bagging_fraction': 0.7331021197687524, 'bagging_freq': 1, 'lambda_l1': 0.19505275933371566, 'lambda_l2': 7.1953596610471635e-06, 'min_child_samples': 39, 'max_depth': 8, 'max_bin': 443, 'min_data_in_leaf': 24, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.5777233603551667, 'min_gain_to_split': 0.4657930225284463}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 16:13:54,115] Trial 180 finished with value: 0.8965339831188037 and parameters: {'num_leaves': 88, 'learning_rate': 0.2991319112378813, 'feature_fraction': 0.6865761041173557, 'bagging_fraction': 0.7288586116037542, 'bagging_freq': 1, 'lambda_l1': 0.12960406157695603, 'lambda_l2': 4.8400344668974896e-06, 'min_child_samples': 37, 'max_depth': 7, 'max_bin': 422, 'min_data_in_leaf': 26, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.5978832437565541, 'min_gain_to_split': 0.48955374986928835}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 16:15:10,809] Trial 181 finished with value: 1.0693620511204416 and parameters: {'num_leaves': 88, 'learning_rate': 0.2634965596713963, 'feature_fraction': 0.6357332890005206, 'bagging_fraction': 0.7309135364949083, 'bagging_freq': 1, 'lambda_l1': 0.1425980752800432, 'lambda_l2': 3.4689911619696386e-06, 'min_child_samples': 37, 'max_depth': 7, 'max_bin': 414, 'min_data_in_leaf': 26, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.5962682335287703, 'min_gain_to_split': 0.4889121364704451}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 16:16:52,341] Trial 182 finished with value: 1.2004662778882242 and parameters: {'num_leaves': 87, 'learning_rate': 0.29972584924086393, 'feature_fraction': 0.6880686745712745, 'bagging_fraction': 0.743921443856323, 'bagging_freq': 1, 'lambda_l1': 0.21913136481401818, 'lambda_l2': 5.509613712316232e-06, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 432, 'min_data_in_leaf': 24, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.604353488572738, 'min_gain_to_split': 0.471626499116272}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 16:21:14,876] Trial 183 finished with value: 0.645723421201259 and parameters: {'num_leaves': 92, 'learning_rate': 0.2771751853674353, 'feature_fraction': 0.9371648062074013, 'bagging_fraction': 0.7181214959358149, 'bagging_freq': 1, 'lambda_l1': 0.3133900846953819, 'lambda_l2': 7.980502951214498e-06, 'min_child_samples': 36, 'max_depth': 7, 'max_bin': 422, 'min_data_in_leaf': 22, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.5701685390879193, 'min_gain_to_split': 0.48831699617002694}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 16:22:27,470] Trial 184 finished with value: 1.1132182039193204 and parameters: {'num_leaves': 92, 'learning_rate': 0.24866872513490126, 'feature_fraction': 0.9379696342291358, 'bagging_fraction': 0.7154459709319814, 'bagging_freq': 1, 'lambda_l1': 0.2931099920643039, 'lambda_l2': 2.6260633150696364e-06, 'min_child_samples': 35, 'max_depth': 7, 'max_bin': 400, 'min_data_in_leaf': 20, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.5719225115566948, 'min_gain_to_split': 0.46274112684241897}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 16:23:33,659] Trial 185 finished with value: 0.995295889900991 and parameters: {'num_leaves': 95, 'learning_rate': 0.2705984030133965, 'feature_fraction': 0.9547195428805656, 'bagging_fraction': 0.7382715165443613, 'bagging_freq': 1, 'lambda_l1': 0.974782302192236, 'lambda_l2': 8.829822348578246e-06, 'min_child_samples': 35, 'max_depth': 7, 'max_bin': 455, 'min_data_in_leaf': 21, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.5455212831987499, 'min_gain_to_split': 0.4807844105558725}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 16:24:47,590] Trial 186 finished with value: 0.6705941988435492 and parameters: {'num_leaves': 93, 'learning_rate': 0.2358447858655541, 'feature_fraction': 0.9352272691520106, 'bagging_fraction': 0.7034002673540272, 'bagging_freq': 1, 'lambda_l1': 0.0914343386772564, 'lambda_l2': 2.1609638904015608e-06, 'min_child_samples': 36, 'max_depth': 7, 'max_bin': 439, 'min_data_in_leaf': 22, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.5623871652143035, 'min_gain_to_split': 0.4734365376168212}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 16:25:58,548] Trial 187 finished with value: 1.1377349358791018 and parameters: {'num_leaves': 93, 'learning_rate': 0.2325529666306527, 'feature_fraction': 0.962147749111609, 'bagging_fraction': 0.7053220339259159, 'bagging_freq': 8, 'lambda_l1': 0.0482180424274043, 'lambda_l2': 1.9662176132926822e-06, 'min_child_samples': 36, 'max_depth': 7, 'max_bin': 438, 'min_data_in_leaf': 22, 'extra_trees': False, 'early_stopping_rounds': 20, 'path_smooth': 0.5100992626995074, 'min_gain_to_split': 0.4980151092160852}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 16:27:25,016] Trial 188 finished with value: 0.8280138246359143 and parameters: {'num_leaves': 90, 'learning_rate': 0.2225750444679918, 'feature_fraction': 0.9479614679616549, 'bagging_fraction': 0.7062469555276608, 'bagging_freq': 1, 'lambda_l1': 0.035556004911550754, 'lambda_l2': 1.949183733221472e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 424, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.5375502462614915, 'min_gain_to_split': 0.4565852952229364}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 16:28:35,394] Trial 189 finished with value: 1.1487606486247877 and parameters: {'num_leaves': 95, 'learning_rate': 0.24868691007458252, 'feature_fraction': 0.9502215212495138, 'bagging_fraction': 0.701951525453124, 'bagging_freq': 1, 'lambda_l1': 0.09000074105203433, 'lambda_l2': 1.974980456412702e-06, 'min_child_samples': 36, 'max_depth': 6, 'max_bin': 407, 'min_data_in_leaf': 27, 'extra_trees': False, 'early_stopping_rounds': 28, 'path_smooth': 0.5298667567025639, 'min_gain_to_split': 0.4575905156362128}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 16:30:37,786] Trial 190 finished with value: 1.49383178648309 and parameters: {'num_leaves': 90, 'learning_rate': 0.06083241748973181, 'feature_fraction': 0.9333982173063726, 'bagging_fraction': 0.7080342608042306, 'bagging_freq': 1, 'lambda_l1': 0.11017158076974946, 'lambda_l2': 3.2237647132095163e-06, 'min_child_samples': 27, 'max_depth': 7, 'max_bin': 423, 'min_data_in_leaf': 23, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.6360307733581498, 'min_gain_to_split': 0.47429911002781877}. Best is trial 123 with value: 0.5252677588695865.

Mejor trial hasta ahora: RMSE=0.525268, Parámetros={'num_leaves': 89, 'learning_rate': 0.26374037217824453, 'feature_fraction': 0.956061182240291, 'bagging_fraction': 0.7170511229719391, 'bagging_freq': 1, 'lambda_l1': 0.11567536324087734, 'lambda_l2': 4.355289603938009e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6254736510606045, 'min_gain_to_split': 0.47185963548665294}

[I 2025-07-11 16:32:38,606] Trial 191 finished with value: 0.4882488232313609 and parameters: {'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 16:34:12,960] Trial 192 finished with value: 0.8890547596442568 and parameters: {'num_leaves': 93, 'learning_rate': 0.2299163707177124, 'feature_fraction': 0.7699225314472615, 'bagging_fraction': 0.7173358531269279, 'bagging_freq': 1, 'lambda_l1': 0.037645822879302696, 'lambda_l2': 1.8659793462334703e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 431, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5655493201379803, 'min_gain_to_split': 0.4527148799746016}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 16:35:24,657] Trial 193 finished with value: 1.1648140943015428 and parameters: {'num_leaves': 96, 'learning_rate': 0.26522561766232083, 'feature_fraction': 0.9466447796722963, 'bagging_fraction': 0.7110581888397914, 'bagging_freq': 1, 'lambda_l1': 0.028146299706394335, 'lambda_l2': 1.523098707691851e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 416, 'min_data_in_leaf': 25, 'extra_trees': False, 'early_stopping_rounds': 29, 'path_smooth': 0.18596558673858032, 'min_gain_to_split': 0.4832138954370325}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 16:36:49,948] Trial 194 finished with value: 0.8850091485748767 and parameters: {'num_leaves': 91, 'learning_rate': 0.2509701530169786, 'feature_fraction': 0.9573759243840951, 'bagging_fraction': 0.7205388251689029, 'bagging_freq': 1, 'lambda_l1': 0.05609374883233087, 'lambda_l2': 2.885898323338604e-06, 'min_child_samples': 29, 'max_depth': 7, 'max_bin': 426, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.5539059908449058, 'min_gain_to_split': 0.46155170587864025}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 16:37:55,670] Trial 195 finished with value: 0.976571951743845 and parameters: {'num_leaves': 92, 'learning_rate': 0.27216170421169433, 'feature_fraction': 0.7882659303083898, 'bagging_fraction': 0.7007693188358238, 'bagging_freq': 1, 'lambda_l1': 0.29222213195743774, 'lambda_l2': 6.551272350725122e-06, 'min_child_samples': 30, 'max_depth': 7, 'max_bin': 438, 'min_data_in_leaf': 27, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5088202516084839, 'min_gain_to_split': 0.4740282120311188}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 16:39:14,102] Trial 196 finished with value: 1.2614618493558771 and parameters: {'num_leaves': 90, 'learning_rate': 0.23630705937520013, 'feature_fraction': 0.9705228752731224, 'bagging_fraction': 0.7060497147653897, 'bagging_freq': 1, 'lambda_l1': 0.10030868670997299, 'lambda_l2': 1.405080149077556e-05, 'min_child_samples': 34, 'max_depth': 7, 'max_bin': 442, 'min_data_in_leaf': 22, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.5395598125845542, 'min_gain_to_split': 0.45022906058973833}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 16:40:23,978] Trial 197 finished with value: 0.9856626919996081 and parameters: {'num_leaves': 86, 'learning_rate': 0.28194920735026474, 'feature_fraction': 0.8077642566752117, 'bagging_fraction': 0.7248779405058958, 'bagging_freq': 1, 'lambda_l1': 0.5286768541767166, 'lambda_l2': 1.1518108590657317e-06, 'min_child_samples': 27, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 84, 'extra_trees': False, 'early_stopping_rounds': 29, 'path_smooth': 0.153620821073003, 'min_gain_to_split': 0.4897459255843418}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 16:41:28,733] Trial 198 finished with value: 1.4341626501363225 and parameters: {'num_leaves': 94, 'learning_rate': 0.22030176789317002, 'feature_fraction': 0.9202805855660766, 'bagging_fraction': 0.7180466457920387, 'bagging_freq': 1, 'lambda_l1': 0.06930151265530099, 'lambda_l2': 6.369740983513822e-07, 'min_child_samples': 29, 'max_depth': 7, 'max_bin': 423, 'min_data_in_leaf': 88, 'extra_trees': False, 'early_stopping_rounds': 30, 'path_smooth': 0.23328127877611388, 'min_gain_to_split': 0.4438385484533789}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 16:42:41,202] Trial 199 finished with value: 0.7784197764602236 and parameters: {'num_leaves': 89, 'learning_rate': 0.26127148484210183, 'feature_fraction': 0.9325708832419382, 'bagging_fraction': 0.7210788407268455, 'bagging_freq': 1, 'lambda_l1': 0.16836568724889492, 'lambda_l2': 2.329418950191476e-06, 'min_child_samples': 31, 'max_depth': 7, 'max_bin': 451, 'min_data_in_leaf': 30, 'extra_trees': False, 'early_stopping_rounds': 28, 'path_smooth': 0.5293293685277125, 'min_gain_to_split': 0.4633155393174986}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 16:43:56,384] Trial 200 finished with value: 0.8951659834857194 and parameters: {'num_leaves': 97, 'learning_rate': 0.2449288225328065, 'feature_fraction': 0.9460338334073346, 'bagging_fraction': 0.7095888035941814, 'bagging_freq': 1, 'lambda_l1': 0.16013194341740716, 'lambda_l2': 3.315017237034839e-06, 'min_child_samples': 34, 'max_depth': 7, 'max_bin': 451, 'min_data_in_leaf': 30, 'extra_trees': False, 'early_stopping_rounds': 28, 'path_smooth': 0.5204495628394823, 'min_gain_to_split': 0.464048161637994}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 16:44:51,510] Trial 201 finished with value: 0.9941972455791905 and parameters: {'num_leaves': 89, 'learning_rate': 0.26498341240254786, 'feature_fraction': 0.936118493153478, 'bagging_fraction': 0.7192533993668057, 'bagging_freq': 1, 'lambda_l1': 0.28610709946375035, 'lambda_l2': 2.093015330567523e-06, 'min_child_samples': 31, 'max_depth': 7, 'max_bin': 177, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5535840497660082, 'min_gain_to_split': 0.47525880768894035}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 16:46:36,833] Trial 202 finished with value: 1.6664825427305896 and parameters: {'num_leaves': 84, 'learning_rate': 0.015915291551287455, 'feature_fraction': 0.9295588073717445, 'bagging_fraction': 0.7265340859294671, 'bagging_freq': 1, 'lambda_l1': 0.18806796233879539, 'lambda_l2': 1.3767651929702337e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 461, 'min_data_in_leaf': 26, 'extra_trees': False, 'early_stopping_rounds': 28, 'path_smooth': 0.4915439071924339, 'min_gain_to_split': 0.45655045688156387}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 16:47:55,042] Trial 203 finished with value: 0.6391648540708867 and parameters: {'num_leaves': 92, 'learning_rate': 0.25881241635667657, 'feature_fraction': 0.9425667677435389, 'bagging_fraction': 0.7119520621480291, 'bagging_freq': 1, 'lambda_l1': 0.38651580977223154, 'lambda_l2': 5.6113789487434565e-06, 'min_child_samples': 31, 'max_depth': 7, 'max_bin': 446, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.5681180561956382, 'min_gain_to_split': 0.43509457760133946}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 16:49:08,241] Trial 204 finished with value: 0.8871654684808098 and parameters: {'num_leaves': 92, 'learning_rate': 0.27961159154722254, 'feature_fraction': 0.9533355763459442, 'bagging_fraction': 0.7118006323260089, 'bagging_freq': 1, 'lambda_l1': 0.09904739703819311, 'lambda_l2': 6.028406204910694e-06, 'min_child_samples': 30, 'max_depth': 7, 'max_bin': 446, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.5761814441764613, 'min_gain_to_split': 0.48318254537720146}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 16:50:33,740] Trial 205 finished with value: 1.2289379660527486 and parameters: {'num_leaves': 90, 'learning_rate': 0.23933287454416322, 'feature_fraction': 0.942477033776723, 'bagging_fraction': 0.7052034559196079, 'bagging_freq': 1, 'lambda_l1': 0.03586312125291262, 'lambda_l2': 3.6800904956082824e-06, 'min_child_samples': 36, 'max_depth': 7, 'max_bin': 452, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.528550428144365, 'min_gain_to_split': 0.4440754509345419}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 16:51:58,533] Trial 206 finished with value: 0.7532561964519735 and parameters: {'num_leaves': 94, 'learning_rate': 0.25761623034102976, 'feature_fraction': 0.7526926388948427, 'bagging_fraction': 0.715019773021629, 'bagging_freq': 1, 'lambda_l1': 0.7073460529736496, 'lambda_l2': 9.805385603713689e-06, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 439, 'min_data_in_leaf': 27, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.5624486246522705, 'min_gain_to_split': 0.46246511558147696}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 16:53:04,232] Trial 207 finished with value: 1.1996979064792919 and parameters: {'num_leaves': 94, 'learning_rate': 0.2811228062098188, 'feature_fraction': 0.7159914568638357, 'bagging_fraction': 0.7113193431545147, 'bagging_freq': 1, 'lambda_l1': 0.7766753078911707, 'lambda_l2': 1.03054165617122e-05, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 441, 'min_data_in_leaf': 25, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.6138282652655965, 'min_gain_to_split': 0.4643784022070409}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 16:54:11,603] Trial 208 finished with value: 1.1682074573610362 and parameters: {'num_leaves': 96, 'learning_rate': 0.2619364797926235, 'feature_fraction': 0.7495966389702173, 'bagging_fraction': 0.7003921380508881, 'bagging_freq': 1, 'lambda_l1': 1.339676403554752, 'lambda_l2': 5.098636779557752e-06, 'min_child_samples': 39, 'max_depth': 7, 'max_bin': 435, 'min_data_in_leaf': 23, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.5628772851907425, 'min_gain_to_split': 0.4723727792133013}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 16:55:24,532] Trial 209 finished with value: 1.287045244538183 and parameters: {'num_leaves': 92, 'learning_rate': 0.22325801458669145, 'feature_fraction': 0.9147533940778312, 'bagging_fraction': 0.7135394546114469, 'bagging_freq': 2, 'lambda_l1': 0.3545887613465002, 'lambda_l2': 2.335173993570747e-05, 'min_child_samples': 40, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 27, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5919024779942922, 'min_gain_to_split': 0.49367013428759193}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 16:56:54,906] Trial 210 finished with value: 0.7864470136855553 and parameters: {'num_leaves': 90, 'learning_rate': 0.2600463279362273, 'feature_fraction': 0.7574130088791804, 'bagging_fraction': 0.7177477622254355, 'bagging_freq': 1, 'lambda_l1': 0.5823380267668586, 'lambda_l2': 8.245698586616272e-06, 'min_child_samples': 35, 'max_depth': 7, 'max_bin': 443, 'min_data_in_leaf': 27, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.5756814765153375, 'min_gain_to_split': 0.45536442005160216}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 16:58:27,229] Trial 211 finished with value: 1.031351574603347 and parameters: {'num_leaves': 94, 'learning_rate': 0.26177783402208415, 'feature_fraction': 0.7478385328115915, 'bagging_fraction': 0.7181893784400085, 'bagging_freq': 1, 'lambda_l1': 0.540426999999133, 'lambda_l2': 1.1350185695492989e-05, 'min_child_samples': 35, 'max_depth': 7, 'max_bin': 444, 'min_data_in_leaf': 27, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.5700135435242828, 'min_gain_to_split': 0.4588883256913419}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 16:59:42,141] Trial 212 finished with value: 1.1656120441277702 and parameters: {'num_leaves': 90, 'learning_rate': 0.29962560005197175, 'feature_fraction': 0.7617203510837696, 'bagging_fraction': 0.7050017384803992, 'bagging_freq': 1, 'lambda_l1': 0.6696318863409554, 'lambda_l2': 8.085824980813465e-06, 'min_child_samples': 37, 'max_depth': 7, 'max_bin': 454, 'min_data_in_leaf': 24, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.5402776969443628, 'min_gain_to_split': 0.45095014002308376}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 17:00:57,945] Trial 213 finished with value: 0.9602169616121579 and parameters: {'num_leaves': 92, 'learning_rate': 0.2540553186773435, 'feature_fraction': 0.7439961148342235, 'bagging_fraction': 0.7148635392904976, 'bagging_freq': 1, 'lambda_l1': 1.1100065297759902, 'lambda_l2': 4.911485382469825e-06, 'min_child_samples': 36, 'max_depth': 7, 'max_bin': 438, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 21, 'path_smooth': 0.5902234011636995, 'min_gain_to_split': 0.47851921029768457}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 17:02:29,295] Trial 214 finished with value: 1.0107367632890818 and parameters: {'num_leaves': 89, 'learning_rate': 0.2731834959807198, 'feature_fraction': 0.7308618497088392, 'bagging_fraction': 0.7083330046379028, 'bagging_freq': 1, 'lambda_l1': 0.16034157764614082, 'lambda_l2': 3.65004564058578e-05, 'min_child_samples': 35, 'max_depth': 7, 'max_bin': 453, 'min_data_in_leaf': 26, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.19684122876078902, 'min_gain_to_split': 0.46620490171792106}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 17:03:52,962] Trial 215 finished with value: 0.8984352788333135 and parameters: {'num_leaves': 87, 'learning_rate': 0.2790370072312755, 'feature_fraction': 0.782294032491263, 'bagging_fraction': 0.7443721658811021, 'bagging_freq': 1, 'lambda_l1': 0.41901801205295686, 'lambda_l2': 2.2341586707751126e-06, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 446, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.557035708338929, 'min_gain_to_split': 0.4339299857412253}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 17:05:15,344] Trial 216 finished with value: 1.0857602993187936 and parameters: {'num_leaves': 91, 'learning_rate': 0.23857004464543535, 'feature_fraction': 0.7551640891312196, 'bagging_fraction': 0.7213279424112069, 'bagging_freq': 1, 'lambda_l1': 0.07272744418652953, 'lambda_l2': 7.78527548414633e-06, 'min_child_samples': 34, 'max_depth': 7, 'max_bin': 432, 'min_data_in_leaf': 25, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.6127293579787673, 'min_gain_to_split': 0.45444567947719167}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 17:06:42,465] Trial 217 finished with value: 1.16343361029107 and parameters: {'num_leaves': 94, 'learning_rate': 0.2527571002946881, 'feature_fraction': 0.9606612773628219, 'bagging_fraction': 0.7282754343715128, 'bagging_freq': 1, 'lambda_l1': 0.24333513469462534, 'lambda_l2': 2.8086955866277486e-06, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 460, 'min_data_in_leaf': 21, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.5775623766365183, 'min_gain_to_split': 0.48587436019356395}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 17:07:53,082] Trial 218 finished with value: 1.0002050141806156 and parameters: {'num_leaves': 100, 'learning_rate': 0.2831087831759668, 'feature_fraction': 0.7404365140271851, 'bagging_fraction': 0.7139678845888715, 'bagging_freq': 1, 'lambda_l1': 0.12790739004854473, 'lambda_l2': 1.8411564201192744e-05, 'min_child_samples': 36, 'max_depth': 7, 'max_bin': 439, 'min_data_in_leaf': 30, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5405345450019827, 'min_gain_to_split': 0.4397122084322752}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 17:09:28,813] Trial 219 finished with value: 1.4522376022847363 and parameters: {'num_leaves': 89, 'learning_rate': 0.22673917339634397, 'feature_fraction': 0.7654672049843126, 'bagging_fraction': 0.7378368891066814, 'bagging_freq': 1, 'lambda_l1': 0.45965359807059386, 'lambda_l2': 4.234921792005664e-06, 'min_child_samples': 37, 'max_depth': 7, 'max_bin': 473, 'min_data_in_leaf': 23, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.5155952594676478, 'min_gain_to_split': 0.15978938407246918}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 17:10:56,110] Trial 220 finished with value: 1.2361532576754213 and parameters: {'num_leaves': 87, 'learning_rate': 0.263061672886733, 'feature_fraction': 0.9266477430164612, 'bagging_fraction': 0.8145936234216148, 'bagging_freq': 1, 'lambda_l1': 0.8120773812039765, 'lambda_l2': 1.7130760526920061e-06, 'min_child_samples': 27, 'max_depth': 7, 'max_bin': 427, 'min_data_in_leaf': 27, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.25318221034108584, 'min_gain_to_split': 0.4709689925744024}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 17:12:22,824] Trial 221 finished with value: 1.0541566770117448 and parameters: {'num_leaves': 85, 'learning_rate': 0.24233961185969458, 'feature_fraction': 0.9426378893836035, 'bagging_fraction': 0.7248177026670898, 'bagging_freq': 1, 'lambda_l1': 0.23741922390091735, 'lambda_l2': 9.056327127414894e-07, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 459, 'min_data_in_leaf': 30, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5291747216694215, 'min_gain_to_split': 0.4464828124359355}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 17:13:42,215] Trial 222 finished with value: 0.9621575220170003 and parameters: {'num_leaves': 91, 'learning_rate': 0.25116550561502, 'feature_fraction': 0.7385915609272435, 'bagging_fraction': 0.7002864107381113, 'bagging_freq': 1, 'lambda_l1': 0.2945738093395442, 'lambda_l2': 2.8885708047037062e-06, 'min_child_samples': 29, 'max_depth': 7, 'max_bin': 446, 'min_data_in_leaf': 31, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.5588345587184189, 'min_gain_to_split': 0.46108298578803053}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 17:15:00,710] Trial 223 finished with value: 0.821616878360339 and parameters: {'num_leaves': 93, 'learning_rate': 0.2808506599508116, 'feature_fraction': 0.9513482433536692, 'bagging_fraction': 0.7199542780439842, 'bagging_freq': 1, 'lambda_l1': 0.1683603585948692, 'lambda_l2': 1.3225158428024842e-06, 'min_child_samples': 30, 'max_depth': 7, 'max_bin': 468, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.5088557400267532, 'min_gain_to_split': 0.45021764115616814}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 17:16:25,712] Trial 224 finished with value: 0.9369190539807762 and parameters: {'num_leaves': 93, 'learning_rate': 0.28601763264501345, 'feature_fraction': 0.9533549760838463, 'bagging_fraction': 0.7187736074348235, 'bagging_freq': 1, 'lambda_l1': 0.09507213052080568, 'lambda_l2': 6.11120132056561e-06, 'min_child_samples': 35, 'max_depth': 7, 'max_bin': 473, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.5095109868251898, 'min_gain_to_split': 0.47617465582686674}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 17:17:46,903] Trial 225 finished with value: 0.9177618814497084 and parameters: {'num_leaves': 96, 'learning_rate': 0.2985558282375755, 'feature_fraction': 0.9493741004131263, 'bagging_fraction': 0.7080478294558, 'bagging_freq': 1, 'lambda_l1': 0.174465225621682, 'lambda_l2': 1.2528811930081442e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 452, 'min_data_in_leaf': 25, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.5003343635086782, 'min_gain_to_split': 0.45536348402805504}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 17:19:10,299] Trial 226 finished with value: 1.115434706411318 and parameters: {'num_leaves': 98, 'learning_rate': 0.2716440939594113, 'feature_fraction': 0.9309386710391674, 'bagging_fraction': 0.7493471427358379, 'bagging_freq': 1, 'lambda_l1': 0.04675640560714349, 'lambda_l2': 1.989864045371624e-06, 'min_child_samples': 29, 'max_depth': 7, 'max_bin': 465, 'min_data_in_leaf': 26, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5439247500881289, 'min_gain_to_split': 0.43605021479832784}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 17:20:56,293] Trial 227 finished with value: 1.6350168311526763 and parameters: {'num_leaves': 93, 'learning_rate': 0.2662495404339886, 'feature_fraction': 0.961855539076895, 'bagging_fraction': 0.7299590505448356, 'bagging_freq': 1, 'lambda_l1': 0.13808942734046942, 'lambda_l2': 4.230089741264436e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 438, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.21355234080408933, 'min_gain_to_split': 0.4989768642101573}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 17:22:19,655] Trial 228 finished with value: 0.749019107325792 and parameters: {'num_leaves': 89, 'learning_rate': 0.28686145395988366, 'feature_fraction': 0.9389163091571753, 'bagging_fraction': 0.7143043050795126, 'bagging_freq': 1, 'lambda_l1': 0.0213543905059357, 'lambda_l2': 9.778059657619172e-06, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 447, 'min_data_in_leaf': 24, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.5692064680378509, 'min_gain_to_split': 0.4640226481924802}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 17:23:40,227] Trial 229 finished with value: 1.1223062641637787 and parameters: {'num_leaves': 90, 'learning_rate': 0.2314072578346709, 'feature_fraction': 0.9341321037188793, 'bagging_fraction': 0.7157710161825983, 'bagging_freq': 1, 'lambda_l1': 0.011336419678623273, 'lambda_l2': 1.3902888459934175e-05, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 22, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.5793486795288155, 'min_gain_to_split': 0.48330573669635024}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 17:25:09,223] Trial 230 finished with value: 1.1022363241315731 and parameters: {'num_leaves': 91, 'learning_rate': 0.21271997531347323, 'feature_fraction': 0.9205545166640373, 'bagging_fraction': 0.7102827042865272, 'bagging_freq': 1, 'lambda_l1': 0.020007176198306022, 'lambda_l2': 7.794747688181348e-06, 'min_child_samples': 31, 'max_depth': 7, 'max_bin': 449, 'min_data_in_leaf': 24, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.5986693004711177, 'min_gain_to_split': 0.47086118683375916}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 17:26:18,882] Trial 231 finished with value: 1.1201753193620734 and parameters: {'num_leaves': 88, 'learning_rate': 0.2821034384200883, 'feature_fraction': 0.9424178666557681, 'bagging_fraction': 0.7217726380373366, 'bagging_freq': 1, 'lambda_l1': 0.030470719557664894, 'lambda_l2': 0.00018591203172909626, 'min_child_samples': 37, 'max_depth': 7, 'max_bin': 230, 'min_data_in_leaf': 27, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5557822130721652, 'min_gain_to_split': 0.4632654508122801}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 17:27:35,270] Trial 232 finished with value: 1.1740266855906012 and parameters: {'num_leaves': 89, 'learning_rate': 0.25751881553779643, 'feature_fraction': 0.9506490181763481, 'bagging_fraction': 0.7050583937035164, 'bagging_freq': 1, 'lambda_l1': 0.004333025714365249, 'lambda_l2': 2.852475505010964e-06, 'min_child_samples': 39, 'max_depth': 7, 'max_bin': 440, 'min_data_in_leaf': 24, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.5292876503255018, 'min_gain_to_split': 0.45208506254566266}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 17:28:42,110] Trial 233 finished with value: 1.0965761707303312 and parameters: {'num_leaves': 92, 'learning_rate': 0.28173176446142084, 'feature_fraction': 0.7576780590129617, 'bagging_fraction': 0.7423658073995307, 'bagging_freq': 1, 'lambda_l1': 0.01908547531735145, 'lambda_l2': 1.487696872265448e-06, 'min_child_samples': 36, 'max_depth': 7, 'max_bin': 457, 'min_data_in_leaf': 76, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.17554533250523421, 'min_gain_to_split': 0.464319689483233}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 17:30:01,988] Trial 234 finished with value: 0.983417474328632 and parameters: {'num_leaves': 87, 'learning_rate': 0.2857499043992751, 'feature_fraction': 0.9399401100137652, 'bagging_fraction': 0.7153850110058535, 'bagging_freq': 1, 'lambda_l1': 0.05940515618737071, 'lambda_l2': 1.1689125636303366e-05, 'min_child_samples': 39, 'max_depth': 7, 'max_bin': 446, 'min_data_in_leaf': 26, 'extra_trees': False, 'early_stopping_rounds': 28, 'path_smooth': 0.5654156623472426, 'min_gain_to_split': 0.42856842492397057}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 17:31:30,975] Trial 235 finished with value: 0.831322260979604 and parameters: {'num_leaves': 95, 'learning_rate': 0.26172361469385774, 'feature_fraction': 0.9267701172336325, 'bagging_fraction': 0.7344760455658261, 'bagging_freq': 1, 'lambda_l1': 0.38792583699570177, 'lambda_l2': 5.451684520056222e-06, 'min_child_samples': 35, 'max_depth': 7, 'max_bin': 422, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5457922172194899, 'min_gain_to_split': 0.44111091163734906}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 17:32:46,816] Trial 236 finished with value: 0.6586143298582733 and parameters: {'num_leaves': 95, 'learning_rate': 0.25413791824754367, 'feature_fraction': 0.9241133208227923, 'bagging_fraction': 0.7335030197828268, 'bagging_freq': 1, 'lambda_l1': 0.4550347724172739, 'lambda_l2': 7.926856155422889e-06, 'min_child_samples': 32, 'max_depth': 7, 'max_bin': 418, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.48603085907176286, 'min_gain_to_split': 0.4429887512671662}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 17:34:06,213] Trial 237 finished with value: 1.0740500630021104 and parameters: {'num_leaves': 97, 'learning_rate': 0.24736980162321345, 'feature_fraction': 0.9307003997449015, 'bagging_fraction': 0.735295598029121, 'bagging_freq': 1, 'lambda_l1': 0.5561051244424039, 'lambda_l2': 9.677654572176693e-06, 'min_child_samples': 32, 'max_depth': 7, 'max_bin': 421, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.5370793464039156, 'min_gain_to_split': 0.44183974707009005}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 17:35:23,256] Trial 238 finished with value: 0.9436642455035354 and parameters: {'num_leaves': 95, 'learning_rate': 0.2361277449173917, 'feature_fraction': 0.9240592556239878, 'bagging_fraction': 0.7311312606265977, 'bagging_freq': 1, 'lambda_l1': 0.3474270805038419, 'lambda_l2': 5.932989334936683e-06, 'min_child_samples': 31, 'max_depth': 7, 'max_bin': 411, 'min_data_in_leaf': 31, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5809894116580976, 'min_gain_to_split': 0.4495345968321213}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 17:36:30,811] Trial 239 finished with value: 1.5610528147495173 and parameters: {'num_leaves': 95, 'learning_rate': 0.12694713390823195, 'feature_fraction': 0.9124869012663847, 'bagging_fraction': 0.7230904565676342, 'bagging_freq': 1, 'lambda_l1': 0.6682607721159609, 'lambda_l2': 3.920662361982858e-06, 'min_child_samples': 30, 'max_depth': 7, 'max_bin': 416, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 28, 'path_smooth': 0.49635924061948977, 'min_gain_to_split': 0.4780848238229708}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 17:37:51,989] Trial 240 finished with value: 0.8057059504252267 and parameters: {'num_leaves': 93, 'learning_rate': 0.2582176563032414, 'feature_fraction': 0.9363266536231516, 'bagging_fraction': 0.7281033323936171, 'bagging_freq': 1, 'lambda_l1': 0.400492079661105, 'lambda_l2': 7.346636159396481e-06, 'min_child_samples': 33, 'max_depth': 7, 'max_bin': 425, 'min_data_in_leaf': 20, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.4709444245524359, 'min_gain_to_split': 0.43845306433367687}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 17:38:58,779] Trial 241 finished with value: 1.2174920583406645 and parameters: {'num_leaves': 94, 'learning_rate': 0.2575272769758214, 'feature_fraction': 0.9325391464095, 'bagging_fraction': 0.728320353350594, 'bagging_freq': 10, 'lambda_l1': 0.4428624846025465, 'lambda_l2': 8.418356060516615e-06, 'min_child_samples': 32, 'max_depth': 7, 'max_bin': 425, 'min_data_in_leaf': 21, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.5118469919307843, 'min_gain_to_split': 0.4347416566725896}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 17:40:09,281] Trial 242 finished with value: 1.1017576803954108 and parameters: {'num_leaves': 93, 'learning_rate': 0.263742311076522, 'feature_fraction': 0.943648902311892, 'bagging_fraction': 0.735770981438964, 'bagging_freq': 1, 'lambda_l1': 0.36761396732044727, 'lambda_l2': 1.918911461504353e-05, 'min_child_samples': 34, 'max_depth': 7, 'max_bin': 428, 'min_data_in_leaf': 23, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.4836345621219892, 'min_gain_to_split': 0.4459865479305148}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 17:41:41,471] Trial 243 finished with value: 1.0634387915345624 and parameters: {'num_leaves': 96, 'learning_rate': 0.24320221330766914, 'feature_fraction': 0.9360837464208253, 'bagging_fraction': 0.741199511275785, 'bagging_freq': 1, 'lambda_l1': 0.9700641651598352, 'lambda_l2': 5.063477835181083e-06, 'min_child_samples': 33, 'max_depth': 7, 'max_bin': 409, 'min_data_in_leaf': 20, 'extra_trees': False, 'early_stopping_rounds': 28, 'path_smooth': 0.4750572893603612, 'min_gain_to_split': 0.4572643500991548}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 17:43:00,581] Trial 244 finished with value: 1.0825312341249915 and parameters: {'num_leaves': 92, 'learning_rate': 0.26410641487680475, 'feature_fraction': 0.9225439234627392, 'bagging_fraction': 0.7207827304559672, 'bagging_freq': 1, 'lambda_l1': 0.25896029076739263, 'lambda_l2': 7.030114775149287e-06, 'min_child_samples': 30, 'max_depth': 7, 'max_bin': 434, 'min_data_in_leaf': 20, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.5488782523122411, 'min_gain_to_split': 0.4247918001547604}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 17:44:20,418] Trial 245 finished with value: 1.2019790462309876 and parameters: {'num_leaves': 98, 'learning_rate': 0.22948013518635446, 'feature_fraction': 0.9488442113285266, 'bagging_fraction': 0.7318532358438633, 'bagging_freq': 1, 'lambda_l1': 0.5348744950221497, 'lambda_l2': 1.3734522063063877e-05, 'min_child_samples': 33, 'max_depth': 7, 'max_bin': 421, 'min_data_in_leaf': 22, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6388128892220104, 'min_gain_to_split': 0.44007922059303634}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 17:45:44,327] Trial 246 finished with value: 1.1018207489981067 and parameters: {'num_leaves': 94, 'learning_rate': 0.25063631396153596, 'feature_fraction': 0.9396780469915531, 'bagging_fraction': 0.7259635206613837, 'bagging_freq': 1, 'lambda_l1': 1.3110992705404405, 'lambda_l2': 3.6772927699523694e-06, 'min_child_samples': 33, 'max_depth': 7, 'max_bin': 435, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.5262771113287226, 'min_gain_to_split': 0.46691132048674144}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 17:47:01,873] Trial 247 finished with value: 0.9979248726137302 and parameters: {'num_leaves': 90, 'learning_rate': 0.2759074091466311, 'feature_fraction': 0.9288529958433686, 'bagging_fraction': 0.7180052706032781, 'bagging_freq': 1, 'lambda_l1': 0.19419241452283292, 'lambda_l2': 2.3914399955970058e-06, 'min_child_samples': 35, 'max_depth': 7, 'max_bin': 428, 'min_data_in_leaf': 25, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.5697469024815981, 'min_gain_to_split': 0.48905104145366046}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 17:48:38,462] Trial 248 finished with value: 0.9428046513677965 and parameters: {'num_leaves': 92, 'learning_rate': 0.2145419423606474, 'feature_fraction': 0.917286735249189, 'bagging_fraction': 0.7364313893892692, 'bagging_freq': 1, 'lambda_l1': 0.3264533112885609, 'lambda_l2': 1.0456667286388774e-05, 'min_child_samples': 29, 'max_depth': 7, 'max_bin': 441, 'min_data_in_leaf': 27, 'extra_trees': False, 'early_stopping_rounds': 30, 'path_smooth': 0.6139579591376454, 'min_gain_to_split': 0.4515550070834517}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 17:49:52,079] Trial 249 finished with value: 1.3135483186650918 and parameters: {'num_leaves': 94, 'learning_rate': 0.2663643447705291, 'feature_fraction': 0.9461112160710556, 'bagging_fraction': 0.7130579449832202, 'bagging_freq': 1, 'lambda_l1': 0.7506014509951169, 'lambda_l2': 6.2252882943485215e-06, 'min_child_samples': 32, 'max_depth': 7, 'max_bin': 416, 'min_data_in_leaf': 30, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5453849326202594, 'min_gain_to_split': 0.4714302236281446}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 17:51:14,822] Trial 250 finished with value: 1.1085886809191101 and parameters: {'num_leaves': 91, 'learning_rate': 0.24360478700642774, 'feature_fraction': 0.9342161609545041, 'bagging_fraction': 0.7451467590844199, 'bagging_freq': 1, 'lambda_l1': 0.45839537276966624, 'lambda_l2': 2.7586821930579563e-05, 'min_child_samples': 27, 'max_depth': 7, 'max_bin': 425, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 28, 'path_smooth': 0.5856762016534071, 'min_gain_to_split': 0.4592103427692612}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 17:52:42,346] Trial 251 finished with value: 0.9796497286421287 and parameters: {'num_leaves': 89, 'learning_rate': 0.22705061741352564, 'feature_fraction': 0.9067084870177161, 'bagging_fraction': 0.7260804681477819, 'bagging_freq': 1, 'lambda_l1': 0.13214044739944428, 'lambda_l2': 4.623377203774952e-06, 'min_child_samples': 31, 'max_depth': 7, 'max_bin': 449, 'min_data_in_leaf': 25, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.09937744098653695, 'min_gain_to_split': 0.4416040586252223}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 17:54:06,898] Trial 252 finished with value: 1.173947842665965 and parameters: {'num_leaves': 96, 'learning_rate': 0.27080183158676957, 'feature_fraction': 0.9585185673397898, 'bagging_fraction': 0.7202337157011998, 'bagging_freq': 2, 'lambda_l1': 1.7891404204203523, 'lambda_l2': 2.7709586393626133e-06, 'min_child_samples': 34, 'max_depth': 7, 'max_bin': 438, 'min_data_in_leaf': 23, 'extra_trees': False, 'early_stopping_rounds': 29, 'path_smooth': 0.5147194961302093, 'min_gain_to_split': 0.48069795143733485}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 17:55:32,478] Trial 253 finished with value: 1.0646770758596111 and parameters: {'num_leaves': 93, 'learning_rate': 0.2512419701766731, 'feature_fraction': 0.9269757376509855, 'bagging_fraction': 0.7112078976148106, 'bagging_freq': 1, 'lambda_l1': 0.2558206040028617, 'lambda_l2': 7.962904000814675e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 403, 'min_data_in_leaf': 31, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.8654423674117113, 'min_gain_to_split': 0.4301362668007709}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 17:56:50,245] Trial 254 finished with value: 1.3691228511656213 and parameters: {'num_leaves': 90, 'learning_rate': 0.2810410434446959, 'feature_fraction': 0.9409750311604133, 'bagging_fraction': 0.7550028730414832, 'bagging_freq': 7, 'lambda_l1': 0.00964609635742256, 'lambda_l2': 1.910913299828852e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 432, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5566135949544615, 'min_gain_to_split': 0.448709746079936}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 17:57:50,931] Trial 255 finished with value: 0.9320645724557275 and parameters: {'num_leaves': 92, 'learning_rate': 0.25692060821903717, 'feature_fraction': 0.951481525912589, 'bagging_fraction': 0.7401295025974418, 'bagging_freq': 1, 'lambda_l1': 0.1661123414061173, 'lambda_l2': 3.818934664600394e-06, 'min_child_samples': 37, 'max_depth': 7, 'max_bin': 151, 'min_data_in_leaf': 26, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.6751743559959006, 'min_gain_to_split': 0.49016530208018283}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 17:59:26,547] Trial 256 finished with value: 1.1890401996777433 and parameters: {'num_leaves': 86, 'learning_rate': 0.23450546675997025, 'feature_fraction': 0.9366262090641372, 'bagging_fraction': 0.7329783568185616, 'bagging_freq': 1, 'lambda_l1': 0.6501033703978365, 'lambda_l2': 5.189112110524022e-06, 'min_child_samples': 30, 'max_depth': 7, 'max_bin': 453, 'min_data_in_leaf': 22, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.4617317444543072, 'min_gain_to_split': 0.20046254088751142}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 18:00:33,987] Trial 257 finished with value: 0.93172015321564 and parameters: {'num_leaves': 88, 'learning_rate': 0.2814313814113583, 'feature_fraction': 0.7336575217349812, 'bagging_fraction': 0.726895956861789, 'bagging_freq': 1, 'lambda_l1': 0.005811511625975618, 'lambda_l2': 1.3275472582916597e-05, 'min_child_samples': 38, 'max_depth': 6, 'max_bin': 444, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 28, 'path_smooth': 0.5013866522791904, 'min_gain_to_split': 0.4696947778009297}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 18:02:26,074] Trial 258 finished with value: 1.1212638685710552 and parameters: {'num_leaves': 95, 'learning_rate': 0.2020593340877492, 'feature_fraction': 0.9225271942012679, 'bagging_fraction': 0.749777202449809, 'bagging_freq': 1, 'lambda_l1': 0.3642458096995357, 'lambda_l2': 1.1391202832139917e-06, 'min_child_samples': 36, 'max_depth': 8, 'max_bin': 417, 'min_data_in_leaf': 24, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5318475128244603, 'min_gain_to_split': 0.4560906013761645}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 18:04:36,180] Trial 259 finished with value: 1.0890273577519949 and parameters: {'num_leaves': 91, 'learning_rate': 0.26336880809326785, 'feature_fraction': 0.7770286664239743, 'bagging_fraction': 0.7136495670138444, 'bagging_freq': 1, 'lambda_l1': 0.10300695031795586, 'lambda_l2': 2.7699266611002785e-06, 'min_child_samples': 34, 'max_depth': 7, 'max_bin': 459, 'min_data_in_leaf': 27, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.5672598554493916, 'min_gain_to_split': 0.435830271197419}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 18:06:03,844] Trial 260 finished with value: 1.3025834132277736 and parameters: {'num_leaves': 84, 'learning_rate': 0.2999472183334722, 'feature_fraction': 0.944072632078056, 'bagging_fraction': 0.7060033761497865, 'bagging_freq': 1, 'lambda_l1': 0.9119344006064654, 'lambda_l2': 4.9631159746148675e-05, 'min_child_samples': 35, 'max_depth': 9, 'max_bin': 433, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.5946927718019916, 'min_gain_to_split': 0.42110299152845243}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 18:07:52,119] Trial 261 finished with value: 0.6314374817479175 and parameters: {'num_leaves': 93, 'learning_rate': 0.24724370737601126, 'feature_fraction': 0.9316414193006417, 'bagging_fraction': 0.7198553877118236, 'bagging_freq': 1, 'lambda_l1': 0.03552647421803429, 'lambda_l2': 8.46308855103831e-06, 'min_child_samples': 27, 'max_depth': 7, 'max_bin': 444, 'min_data_in_leaf': 30, 'extra_trees': False, 'early_stopping_rounds': 29, 'path_smooth': 0.5415803389047629, 'min_gain_to_split': 0.47743474641119826}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 18:09:35,912] Trial 262 finished with value: 0.8518312413249369 and parameters: {'num_leaves': 98, 'learning_rate': 0.22183918792695745, 'feature_fraction': 0.9316758388429013, 'bagging_fraction': 0.7190920415420102, 'bagging_freq': 1, 'lambda_l1': 0.023006758274693128, 'lambda_l2': 9.862359224911803e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 424, 'min_data_in_leaf': 30, 'extra_trees': False, 'early_stopping_rounds': 30, 'path_smooth': 0.5526485593888901, 'min_gain_to_split': 0.46353915693949}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 18:11:49,005] Trial 263 finished with value: 0.9900324567781 and parameters: {'num_leaves': 94, 'learning_rate': 0.24008999372786102, 'feature_fraction': 0.9146722850621244, 'bagging_fraction': 0.7222023383359146, 'bagging_freq': 9, 'lambda_l1': 0.037234338108311435, 'lambda_l2': 3.7573313128819277, 'min_child_samples': 37, 'max_depth': 7, 'max_bin': 440, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5730216542789868, 'min_gain_to_split': 0.44947769668177295}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 18:14:20,031] Trial 264 finished with value: 0.9842868151883089 and parameters: {'num_leaves': 92, 'learning_rate': 0.24710505806542532, 'feature_fraction': 0.9671657455613032, 'bagging_fraction': 0.7115054483227774, 'bagging_freq': 2, 'lambda_l1': 0.08717092475033855, 'lambda_l2': 2.035066399202573e-05, 'min_child_samples': 40, 'max_depth': 7, 'max_bin': 453, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.49277702417772423, 'min_gain_to_split': 0.4719297502237225}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 18:17:12,732] Trial 265 finished with value: 1.533578003948263 and parameters: {'num_leaves': 96, 'learning_rate': 0.2201313303373426, 'feature_fraction': 0.9556509400371507, 'bagging_fraction': 0.728977777112877, 'bagging_freq': 1, 'lambda_l1': 0.21023270067112734, 'lambda_l2': 7.2632707263608135e-06, 'min_child_samples': 33, 'max_depth': 7, 'max_bin': 484, 'min_data_in_leaf': 64, 'extra_trees': False, 'early_stopping_rounds': 28, 'path_smooth': 0.522120864568451, 'min_gain_to_split': 0.45846572141280334}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 18:20:59,223] Trial 266 finished with value: 0.7388150304275671 and parameters: {'num_leaves': 93, 'learning_rate': 0.279196117189132, 'feature_fraction': 0.9266661917231687, 'bagging_fraction': 0.7165935345076524, 'bagging_freq': 1, 'lambda_l1': 0.048372112658099285, 'lambda_l2': 0.0004573283662169509, 'min_child_samples': 35, 'max_depth': 7, 'max_bin': 429, 'min_data_in_leaf': 31, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.5977364264459087, 'min_gain_to_split': 0.1256084591185753}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 18:24:43,973] Trial 267 finished with value: 1.5359436320501352 and parameters: {'num_leaves': 93, 'learning_rate': 0.0399499773992371, 'feature_fraction': 0.9224689058755906, 'bagging_fraction': 0.7083315515012136, 'bagging_freq': 1, 'lambda_l1': 0.03645459184544308, 'lambda_l2': 0.0012502583206025872, 'min_child_samples': 37, 'max_depth': 7, 'max_bin': 412, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.6262209980862222, 'min_gain_to_split': 0.12251559124972082}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 18:27:27,705] Trial 268 finished with value: 0.8855377001123601 and parameters: {'num_leaves': 95, 'learning_rate': 0.27879088961942267, 'feature_fraction': 0.9462370437211618, 'bagging_fraction': 0.7169706198495263, 'bagging_freq': 1, 'lambda_l1': 0.05682140865966779, 'lambda_l2': 8.323945096668416e-06, 'min_child_samples': 35, 'max_depth': 7, 'max_bin': 430, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.5886990099278657, 'min_gain_to_split': 0.49248484411826104}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 18:30:06,098] Trial 269 finished with value: 1.0948981012530707 and parameters: {'num_leaves': 90, 'learning_rate': 0.25325995436849086, 'feature_fraction': 0.9376048206096957, 'bagging_fraction': 0.7061237103728317, 'bagging_freq': 1, 'lambda_l1': 0.027043777253486383, 'lambda_l2': 0.0003446764924056935, 'min_child_samples': 35, 'max_depth': 7, 'max_bin': 462, 'min_data_in_leaf': 30, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.9907003300485953, 'min_gain_to_split': 0.49972699894304945}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 18:33:28,803] Trial 270 finished with value: 1.245725649126282 and parameters: {'num_leaves': 93, 'learning_rate': 0.28654245820512003, 'feature_fraction': 0.9298501030593003, 'bagging_fraction': 0.7158500324431909, 'bagging_freq': 1, 'lambda_l1': 0.047644668658213096, 'lambda_l2': 0.0007627363759978625, 'min_child_samples': 36, 'max_depth': 7, 'max_bin': 443, 'min_data_in_leaf': 31, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.6104030872145698, 'min_gain_to_split': 0.009826360860240815}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 18:36:35,641] Trial 271 finished with value: 1.4044525090822586 and parameters: {'num_leaves': 91, 'learning_rate': 0.08246444211164171, 'feature_fraction': 0.9496432928040069, 'bagging_fraction': 0.7217624716177138, 'bagging_freq': 1, 'lambda_l1': 0.07313154182307259, 'lambda_l2': 0.00042010021367825745, 'min_child_samples': 35, 'max_depth': 6, 'max_bin': 419, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.5988333590109617, 'min_gain_to_split': 0.4813373350234556}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 18:40:21,372] Trial 272 finished with value: 1.0110246424435911 and parameters: {'num_leaves': 97, 'learning_rate': 0.23712996921730697, 'feature_fraction': 0.9081885381605374, 'bagging_fraction': 0.7107707663517118, 'bagging_freq': 1, 'lambda_l1': 0.09861724786201553, 'lambda_l2': 1.6503609604113436e-05, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 430, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6352010959963225, 'min_gain_to_split': 0.21833027125782767}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 18:43:37,664] Trial 273 finished with value: 0.9013805081717632 and parameters: {'num_leaves': 89, 'learning_rate': 0.26545706456021845, 'feature_fraction': 0.939605456433083, 'bagging_fraction': 0.7345460387912646, 'bagging_freq': 1, 'lambda_l1': 0.1322591187153051, 'lambda_l2': 5.453525277617132e-06, 'min_child_samples': 25, 'max_depth': 7, 'max_bin': 467, 'min_data_in_leaf': 30, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.6577844748925655, 'min_gain_to_split': 0.4727440555273302}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 18:46:11,004] Trial 274 finished with value: 1.4230988814333831 and parameters: {'num_leaves': 94, 'learning_rate': 0.20571222879775017, 'feature_fraction': 0.9596559122192272, 'bagging_fraction': 0.7172988262228852, 'bagging_freq': 2, 'lambda_l1': 0.24506209445402333, 'lambda_l2': 0.00023444713370065494, 'min_child_samples': 27, 'max_depth': 7, 'max_bin': 451, 'min_data_in_leaf': 27, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.5677649819728919, 'min_gain_to_split': 0.4643643776020008}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 18:49:38,818] Trial 275 finished with value: 0.8540187327817552 and parameters: {'num_leaves': 50, 'learning_rate': 0.25006063628590736, 'feature_fraction': 0.9189603100825178, 'bagging_fraction': 0.7009245783146086, 'bagging_freq': 1, 'lambda_l1': 0.043278102172557946, 'lambda_l2': 8.461350206559952e-08, 'min_child_samples': 32, 'max_depth': 8, 'max_bin': 422, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.14063306426038402, 'min_gain_to_split': 0.06764546341719097}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 18:53:55,283] Trial 276 finished with value: 0.9075261695016031 and parameters: {'num_leaves': 91, 'learning_rate': 0.2991139652411681, 'feature_fraction': 0.9324489257839299, 'bagging_fraction': 0.8691610928913319, 'bagging_freq': 1, 'lambda_l1': 0.17352457047392078, 'lambda_l2': 4.5277810050286043e-07, 'min_child_samples': 36, 'max_depth': 7, 'max_bin': 437, 'min_data_in_leaf': 31, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5512319063982651, 'min_gain_to_split': 0.11183666096104902}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 18:57:53,973] Trial 277 finished with value: 1.2022317361394619 and parameters: {'num_leaves': 93, 'learning_rate': 0.2294969582917545, 'feature_fraction': 0.9456057648179516, 'bagging_fraction': 0.7286019348359112, 'bagging_freq': 1, 'lambda_l1': 0.33847012532782955, 'lambda_l2': 0.0006267195271267768, 'min_child_samples': 34, 'max_depth': 7, 'max_bin': 396, 'min_data_in_leaf': 26, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.6112970695865183, 'min_gain_to_split': 0.2368512298481014}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 19:00:28,396] Trial 278 finished with value: 1.4312504076640433 and parameters: {'num_leaves': 95, 'learning_rate': 0.2714122797268964, 'feature_fraction': 0.9229690082901412, 'bagging_fraction': 0.7220231185603205, 'bagging_freq': 6, 'lambda_l1': 0.016443876561615264, 'lambda_l2': 0.00012966659238341222, 'min_child_samples': 27, 'max_depth': 7, 'max_bin': 407, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 28, 'path_smooth': 0.5835763421079091, 'min_gain_to_split': 0.4406007705288448}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 19:04:12,126] Trial 279 finished with value: 1.2393403756620336 and parameters: {'num_leaves': 89, 'learning_rate': 0.2998887560766361, 'feature_fraction': 0.9550889563598142, 'bagging_fraction': 0.7072635617552687, 'bagging_freq': 1, 'lambda_l1': 0.06808769497085022, 'lambda_l2': 3.068364908552444e-06, 'min_child_samples': 33, 'max_depth': 7, 'max_bin': 479, 'min_data_in_leaf': 27, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.5449415762788408, 'min_gain_to_split': 0.17364368971115252}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 19:09:17,617] Trial 280 finished with value: 0.9596424851006342 and parameters: {'num_leaves': 91, 'learning_rate': 0.25192542682865754, 'feature_fraction': 0.9346082011182822, 'bagging_fraction': 0.737504891007556, 'bagging_freq': 1, 'lambda_l1': 0.46843728586719835, 'lambda_l2': 1.3891923507906723e-05, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 446, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.5746254910553344, 'min_gain_to_split': 0.267685536057252}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 19:12:59,746] Trial 281 finished with value: 2.1794366198066037 and parameters: {'num_leaves': 99, 'learning_rate': 0.27546067196081125, 'feature_fraction': 0.9688497186487677, 'bagging_fraction': 0.7143858668556201, 'bagging_freq': 2, 'lambda_l1': 0.026910157687222956, 'lambda_l2': 1.9337464495368597e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 459, 'min_data_in_leaf': 30, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.5983617216129707, 'min_gain_to_split': 0.48277676078727183}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 19:19:46,353] Trial 282 finished with value: 1.5066229176025778 and parameters: {'num_leaves': 93, 'learning_rate': 0.0466504596099362, 'feature_fraction': 0.9389352259433684, 'bagging_fraction': 0.7261373396156592, 'bagging_freq': 1, 'lambda_l1': 0.12058926046147374, 'lambda_l2': 8.331775593316633e-07, 'min_child_samples': 36, 'max_depth': 7, 'max_bin': 493, 'min_data_in_leaf': 26, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.533966873395795, 'min_gain_to_split': 0.04679938551191176}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 19:22:42,458] Trial 283 finished with value: 1.0149131102570719 and parameters: {'num_leaves': 96, 'learning_rate': 0.2154977258969963, 'feature_fraction': 0.8341455948086186, 'bagging_fraction': 0.7403212932326156, 'bagging_freq': 1, 'lambda_l1': 1.347347300478166, 'lambda_l2': 3.929683796006705e-06, 'min_child_samples': 34, 'max_depth': 7, 'max_bin': 424, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 21, 'path_smooth': 0.7864162509228123, 'min_gain_to_split': 0.4543346354753191}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 19:25:41,907] Trial 284 finished with value: 1.1641086775693215 and parameters: {'num_leaves': 88, 'learning_rate': 0.24202452775979155, 'feature_fraction': 0.9151651254466886, 'bagging_fraction': 0.7322005445406361, 'bagging_freq': 1, 'lambda_l1': 0.2763548749071604, 'lambda_l2': 0.0011892980620827856, 'min_child_samples': 28, 'max_depth': 6, 'max_bin': 439, 'min_data_in_leaf': 20, 'extra_trees': False, 'early_stopping_rounds': 29, 'path_smooth': 0.556895099875295, 'min_gain_to_split': 0.4333612391189068}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 19:28:33,539] Trial 285 finished with value: 1.1239888768164668 and parameters: {'num_leaves': 91, 'learning_rate': 0.2600199377084188, 'feature_fraction': 0.9281448678028681, 'bagging_fraction': 0.7108872194310917, 'bagging_freq': 1, 'lambda_l1': 0.6006620832714737, 'lambda_l2': 1.0629413331519406e-05, 'min_child_samples': 39, 'max_depth': 7, 'max_bin': 449, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.5839713979897364, 'min_gain_to_split': 0.47169939996010957}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 19:33:04,956] Trial 286 finished with value: 0.7074344038867189 and parameters: {'num_leaves': 92, 'learning_rate': 0.28120828623511934, 'feature_fraction': 0.9492245067890327, 'bagging_fraction': 0.7192693413681379, 'bagging_freq': 1, 'lambda_l1': 0.1833874692829624, 'lambda_l2': 6.1763118692696e-06, 'min_child_samples': 29, 'max_depth': 7, 'max_bin': 471, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6260455868343457, 'min_gain_to_split': 0.46154594946069205}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 19:37:14,817] Trial 287 finished with value: 0.7553160860670438 and parameters: {'num_leaves': 94, 'learning_rate': 0.27741160928070324, 'feature_fraction': 0.9446394880211718, 'bagging_fraction': 0.718948997007339, 'bagging_freq': 1, 'lambda_l1': 0.17110127859449883, 'lambda_l2': 3.280863107309277e-08, 'min_child_samples': 31, 'max_depth': 7, 'max_bin': 478, 'min_data_in_leaf': 45, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6255902355560259, 'min_gain_to_split': 0.44577127044210824}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 19:41:58,025] Trial 288 finished with value: 1.1293218587344167 and parameters: {'num_leaves': 93, 'learning_rate': 0.28375059285559956, 'feature_fraction': 0.9535780899267414, 'bagging_fraction': 0.8209916533614271, 'bagging_freq': 1, 'lambda_l1': 0.0837460773122446, 'lambda_l2': 2.0447902622149462e-08, 'min_child_samples': 31, 'max_depth': 7, 'max_bin': 473, 'min_data_in_leaf': 31, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.6403156340466177, 'min_gain_to_split': 0.1354749797813365}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 19:45:21,068] Trial 289 finished with value: 1.2625453069636756 and parameters: {'num_leaves': 89, 'learning_rate': 0.29912740126558585, 'feature_fraction': 0.9638146541714575, 'bagging_fraction': 0.7190935262592085, 'bagging_freq': 2, 'lambda_l1': 0.16922909128371755, 'lambda_l2': 4.157550772011413e-08, 'min_child_samples': 32, 'max_depth': 7, 'max_bin': 487, 'min_data_in_leaf': 59, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.6285163033862992, 'min_gain_to_split': 0.4630773199232209}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 19:48:22,277] Trial 290 finished with value: 0.7687926939620041 and parameters: {'num_leaves': 92, 'learning_rate': 0.27731060667455815, 'feature_fraction': 0.9466489054923677, 'bagging_fraction': 0.7145658555243911, 'bagging_freq': 1, 'lambda_l1': 0.1132346982401046, 'lambda_l2': 3.4099298856177484e-08, 'min_child_samples': 31, 'max_depth': 7, 'max_bin': 481, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.671403968467036, 'min_gain_to_split': 0.454742418158061}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 19:51:38,503] Trial 291 finished with value: 1.3032444171818014 and parameters: {'num_leaves': 94, 'learning_rate': 0.27964863278815233, 'feature_fraction': 0.9424114378377096, 'bagging_fraction': 0.7153791306868811, 'bagging_freq': 1, 'lambda_l1': 0.11939613308888078, 'lambda_l2': 1.5647062842341693e-08, 'min_child_samples': 31, 'max_depth': 7, 'max_bin': 487, 'min_data_in_leaf': 46, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.7082514739492124, 'min_gain_to_split': 0.44807148976320876}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 19:55:18,107] Trial 292 finished with value: 1.0408557255236695 and parameters: {'num_leaves': 92, 'learning_rate': 0.28131570745885426, 'feature_fraction': 0.9411513229360672, 'bagging_fraction': 0.7180398245046705, 'bagging_freq': 1, 'lambda_l1': 0.18303912257050386, 'lambda_l2': 7.353310306762036e-08, 'min_child_samples': 32, 'max_depth': 7, 'max_bin': 476, 'min_data_in_leaf': 36, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6542490064830655, 'min_gain_to_split': 0.4636609571542259}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 20:00:54,293] Trial 293 finished with value: 0.5024461975199883 and parameters: {'num_leaves': 97, 'learning_rate': 0.26875336265113137, 'feature_fraction': 0.9501618671644171, 'bagging_fraction': 0.7241179010226225, 'bagging_freq': 1, 'lambda_l1': 0.10201699743753098, 'lambda_l2': 3.143101663932797e-05, 'min_child_samples': 31, 'max_depth': 7, 'max_bin': 499, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.6929529061288392, 'min_gain_to_split': 0.41932465550927306}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 20:04:23,113] Trial 294 finished with value: 1.2340990490717096 and parameters: {'num_leaves': 100, 'learning_rate': 0.2668656692701244, 'feature_fraction': 0.7918729714825599, 'bagging_fraction': 0.7238198044316697, 'bagging_freq': 1, 'lambda_l1': 0.0667802272148254, 'lambda_l2': 3.057878848621152e-08, 'min_child_samples': 31, 'max_depth': 7, 'max_bin': 497, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.6810920296951527, 'min_gain_to_split': 0.426459919369344}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 20:07:03,268] Trial 295 finished with value: 1.4879488849614384 and parameters: {'num_leaves': 97, 'learning_rate': 0.2623806681862154, 'feature_fraction': 0.9338391257328008, 'bagging_fraction': 0.7250508199497044, 'bagging_freq': 2, 'lambda_l1': 0.1060181554523484, 'lambda_l2': 3.683862841879401e-08, 'min_child_samples': 31, 'max_depth': 7, 'max_bin': 492, 'min_data_in_leaf': 100, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.6915353409663275, 'min_gain_to_split': 0.41684715130284494}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 20:10:02,753] Trial 296 finished with value: 1.296000629545516 and parameters: {'num_leaves': 98, 'learning_rate': 0.28430254790892284, 'feature_fraction': 0.9586945391061401, 'bagging_fraction': 0.7119741606812215, 'bagging_freq': 1, 'lambda_l1': 0.0786477840679911, 'lambda_l2': 5.821068608732203e-08, 'min_child_samples': 32, 'max_depth': 7, 'max_bin': 498, 'min_data_in_leaf': 54, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.652879072243148, 'min_gain_to_split': 0.426187912794518}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 20:12:55,869] Trial 297 finished with value: 1.0869524838429645 and parameters: {'num_leaves': 96, 'learning_rate': 0.2988074480719425, 'feature_fraction': 0.943173996028368, 'bagging_fraction': 0.7130887860396327, 'bagging_freq': 1, 'lambda_l1': 0.05364064001383938, 'lambda_l2': 3.1874308860179875e-08, 'min_child_samples': 33, 'max_depth': 7, 'max_bin': 482, 'min_data_in_leaf': 38, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6691531537784347, 'min_gain_to_split': 0.44140356380471135}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 20:15:13,594] Trial 298 finished with value: 1.4248547337345054 and parameters: {'num_leaves': 95, 'learning_rate': 0.2523175553683012, 'feature_fraction': 0.9500113388677486, 'bagging_fraction': 0.7278705853608736, 'bagging_freq': 1, 'lambda_l1': 0.13814057143130612, 'lambda_l2': 2.739625259013424e-08, 'min_child_samples': 37, 'max_depth': 7, 'max_bin': 500, 'min_data_in_leaf': 44, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.7242048549855149, 'min_gain_to_split': 0.4757990593596197}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 20:17:38,562] Trial 299 finished with value: 1.4972039207470256 and parameters: {'num_leaves': 86, 'learning_rate': 0.26917152262046384, 'feature_fraction': 0.9319923194108765, 'bagging_fraction': 0.7000008810006507, 'bagging_freq': 1, 'lambda_l1': 0.24496467142669956, 'lambda_l2': 2.2238414082340756e-05, 'min_child_samples': 30, 'max_depth': 7, 'max_bin': 489, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.6278449749642959, 'min_gain_to_split': 0.43161777532384515}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 20:19:26,823] Trial 300 finished with value: 1.1865542092746721 and parameters: {'num_leaves': 90, 'learning_rate': 0.23990386697630914, 'feature_fraction': 0.9386206113074962, 'bagging_fraction': 0.7587345742537468, 'bagging_freq': 1, 'lambda_l1': 2.95794627597624, 'lambda_l2': 1.1570065531478975e-05, 'min_child_samples': 33, 'max_depth': 7, 'max_bin': 478, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.6956073313337172, 'min_gain_to_split': 0.4567692171096148}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 20:21:05,036] Trial 301 finished with value: 1.1028383706019351 and parameters: {'num_leaves': 92, 'learning_rate': 0.27228298659614375, 'feature_fraction': 0.9744780337561155, 'bagging_fraction': 0.7062892096028733, 'bagging_freq': 1, 'lambda_l1': 0.13085444331463952, 'lambda_l2': 0.004656448498984294, 'min_child_samples': 32, 'max_depth': 7, 'max_bin': 472, 'min_data_in_leaf': 48, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6705345247091534, 'min_gain_to_split': 0.46925675873189054}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 20:24:15,143] Trial 302 finished with value: 1.2231567541400925 and parameters: {'num_leaves': 88, 'learning_rate': 0.11157469437073632, 'feature_fraction': 0.9242966330886959, 'bagging_fraction': 0.7208021534886527, 'bagging_freq': 1, 'lambda_l1': 0.09097797202977294, 'lambda_l2': 6.938842370517819e-06, 'min_child_samples': 39, 'max_depth': 7, 'max_bin': 481, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.6241100189719071, 'min_gain_to_split': 0.41949503158708995}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 20:26:37,524] Trial 303 finished with value: 1.330287399254895 and parameters: {'num_leaves': 94, 'learning_rate': 0.25256059554200017, 'feature_fraction': 0.9471098767077928, 'bagging_fraction': 0.71591389419092, 'bagging_freq': 1, 'lambda_l1': 0.9469545791391855, 'lambda_l2': 3.2104001514055e-05, 'min_child_samples': 25, 'max_depth': 7, 'max_bin': 467, 'min_data_in_leaf': 36, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.645792622357553, 'min_gain_to_split': 0.44065736972213027}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 20:28:44,819] Trial 304 finished with value: 1.280963520709922 and parameters: {'num_leaves': 32, 'learning_rate': 0.2857194137802168, 'feature_fraction': 0.9022803700433112, 'bagging_fraction': 0.7234973814423594, 'bagging_freq': 1, 'lambda_l1': 0.2530952346983503, 'lambda_l2': 1.6269100686012577e-05, 'min_child_samples': 31, 'max_depth': 7, 'max_bin': 500, 'min_data_in_leaf': 35, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.6061650462341761, 'min_gain_to_split': 0.4789805296277841}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 20:32:16,389] Trial 305 finished with value: 1.684223207155636 and parameters: {'num_leaves': 97, 'learning_rate': 0.027000657053894976, 'feature_fraction': 0.9622270757022066, 'bagging_fraction': 0.7112068305845045, 'bagging_freq': 1, 'lambda_l1': 0.0465980236539028, 'lambda_l2': 1.1578594648291402e-08, 'min_child_samples': 37, 'max_depth': 7, 'max_bin': 380, 'min_data_in_leaf': 31, 'extra_trees': False, 'early_stopping_rounds': 47, 'path_smooth': 0.7369326022932069, 'min_gain_to_split': 0.1890764596075557}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 20:34:36,584] Trial 306 finished with value: 1.1836762878650546 and parameters: {'num_leaves': 92, 'learning_rate': 0.2347942997369652, 'feature_fraction': 0.9138914508638949, 'bagging_fraction': 0.8044324060255346, 'bagging_freq': 2, 'lambda_l1': 0.18864878217116135, 'lambda_l2': 9.141822270613844e-05, 'min_child_samples': 29, 'max_depth': 7, 'max_bin': 490, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.6682824656683876, 'min_gain_to_split': 0.4528246986814901}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 20:37:58,802] Trial 307 finished with value: 1.2571425394577986 and parameters: {'num_leaves': 86, 'learning_rate': 0.26203541712885126, 'feature_fraction': 0.9357310177221296, 'bagging_fraction': 0.7306393605050365, 'bagging_freq': 7, 'lambda_l1': 0.5999195457695932, 'lambda_l2': 8.769395095577887e-06, 'min_child_samples': 34, 'max_depth': 7, 'max_bin': 460, 'min_data_in_leaf': 31, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.7067634643038124, 'min_gain_to_split': 0.40306838404956175}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 20:40:57,302] Trial 308 finished with value: 1.2319656932656833 and parameters: {'num_leaves': 90, 'learning_rate': 0.27123581524509127, 'feature_fraction': 0.9542677624210191, 'bagging_fraction': 0.7187882349259541, 'bagging_freq': 1, 'lambda_l1': 0.3576619845202111, 'lambda_l2': 7.1293114783844776e-06, 'min_child_samples': 36, 'max_depth': 7, 'max_bin': 470, 'min_data_in_leaf': 30, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.6130998820415835, 'min_gain_to_split': 0.46134227031823066}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 20:43:14,860] Trial 309 finished with value: 1.503305587631198 and parameters: {'num_leaves': 95, 'learning_rate': 0.2484289123925144, 'feature_fraction': 0.9235433051388042, 'bagging_fraction': 0.7070165317333059, 'bagging_freq': 1, 'lambda_l1': 1.945668822694459, 'lambda_l2': 4.292490939158763e-08, 'min_child_samples': 38, 'max_depth': 7, 'max_bin': 456, 'min_data_in_leaf': 42, 'extra_trees': False, 'early_stopping_rounds': 28, 'path_smooth': 0.6449043443811624, 'min_gain_to_split': 0.4843672313235281}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 20:45:50,674] Trial 310 finished with value: 1.2051742195750936 and parameters: {'num_leaves': 88, 'learning_rate': 0.29776431994103236, 'feature_fraction': 0.9452717037950642, 'bagging_fraction': 0.7523755219664043, 'bagging_freq': 1, 'lambda_l1': 0.07885253054363695, 'lambda_l2': 4.609462090074886e-06, 'min_child_samples': 30, 'max_depth': 7, 'max_bin': 483, 'min_data_in_leaf': 22, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.08510608016835841, 'min_gain_to_split': 0.43374513284917926}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 20:49:20,145] Trial 311 finished with value: 1.65196555141246 and parameters: {'num_leaves': 92, 'learning_rate': 0.020606256897884215, 'feature_fraction': 0.9304901789198127, 'bagging_fraction': 0.7785904009159113, 'bagging_freq': 1, 'lambda_l1': 0.13179561706083173, 'lambda_l2': 5.098716350533973e-05, 'min_child_samples': 35, 'max_depth': 7, 'max_bin': 454, 'min_data_in_leaf': 30, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.05398450770429399, 'min_gain_to_split': 0.4692864780831708}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 20:52:00,591] Trial 312 finished with value: 1.4615815371276208 and parameters: {'num_leaves': 94, 'learning_rate': 0.22921896719157436, 'feature_fraction': 0.9402320340304702, 'bagging_fraction': 0.7246040919603971, 'bagging_freq': 1, 'lambda_l1': 0.24925071394596068, 'lambda_l2': 1.9616134695235244e-08, 'min_child_samples': 33, 'max_depth': 7, 'max_bin': 464, 'min_data_in_leaf': 90, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.6213058269106672, 'min_gain_to_split': 0.4493232187981472}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 20:55:17,857] Trial 313 finished with value: 1.397763619842571 and parameters: {'num_leaves': 83, 'learning_rate': 0.2583225998902689, 'feature_fraction': 0.8094804132768566, 'bagging_fraction': 0.715148022765352, 'bagging_freq': 1, 'lambda_l1': 0.4405435332829394, 'lambda_l2': 3.3072814461628805e-06, 'min_child_samples': 32, 'max_depth': 7, 'max_bin': 477, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 21, 'path_smooth': 0.6873241526948174, 'min_gain_to_split': 0.4615340931413022}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 20:59:06,208] Trial 314 finished with value: 1.3785672987187656 and parameters: {'num_leaves': 90, 'learning_rate': 0.2825977076194875, 'feature_fraction': 0.9504604162080098, 'bagging_fraction': 0.7442456411041409, 'bagging_freq': 1, 'lambda_l1': 0.824446086807397, 'lambda_l2': 6.298722933635274e-08, 'min_child_samples': 34, 'max_depth': 7, 'max_bin': 448, 'min_data_in_leaf': 57, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.7600107322682059, 'min_gain_to_split': 0.4431918439986664}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 21:02:13,139] Trial 315 finished with value: 1.2268905290080276 and parameters: {'num_leaves': 37, 'learning_rate': 0.24107618383938814, 'feature_fraction': 0.8880923378867399, 'bagging_fraction': 0.7056065555036057, 'bagging_freq': 2, 'lambda_l1': 5.281572522822526e-05, 'lambda_l2': 1.4949121180064781e-05, 'min_child_samples': 27, 'max_depth': 7, 'max_bin': 462, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.5970784693219034, 'min_gain_to_split': 0.48773319530554915}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 21:07:15,054] Trial 316 finished with value: 0.7480152620120714 and parameters: {'num_leaves': 98, 'learning_rate': 0.2702940019423542, 'feature_fraction': 0.9207056693507912, 'bagging_fraction': 0.8406126090330449, 'bagging_freq': 1, 'lambda_l1': 0.0509507114926318, 'lambda_l2': 6.42840533898701e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 489, 'min_data_in_leaf': 25, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.016815690212754975, 'min_gain_to_split': 0.29971475821827676}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 21:10:35,504] Trial 317 finished with value: 1.3910929652759585 and parameters: {'num_leaves': 100, 'learning_rate': 0.25506584463075577, 'feature_fraction': 0.9133845453237969, 'bagging_fraction': 0.7293827955962358, 'bagging_freq': 1, 'lambda_l1': 0.025212522575989958, 'lambda_l2': 7.749279973304424e-06, 'min_child_samples': 24, 'max_depth': 7, 'max_bin': 484, 'min_data_in_leaf': 82, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.030620478351808436, 'min_gain_to_split': 0.41650765273408247}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 21:15:51,021] Trial 318 finished with value: 1.6697831562809164 and parameters: {'num_leaves': 98, 'learning_rate': 0.013785453178068273, 'feature_fraction': 0.9207192720259856, 'bagging_fraction': 0.7901955449841973, 'bagging_freq': 1, 'lambda_l1': 0.053416024562070834, 'lambda_l2': 9.768331096255348e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 490, 'min_data_in_leaf': 97, 'extra_trees': False, 'early_stopping_rounds': 28, 'path_smooth': 0.6374349782976452, 'min_gain_to_split': 0.29929573685753313}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 21:20:01,192] Trial 319 finished with value: 1.6626799060601036 and parameters: {'num_leaves': 99, 'learning_rate': 0.23366455994201504, 'feature_fraction': 0.9644553958080949, 'bagging_fraction': 0.8362431553257665, 'bagging_freq': 1, 'lambda_l1': 0.03892570213963836, 'lambda_l2': 1.0336372534228153e-07, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 495, 'min_data_in_leaf': 21, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.014444996918135375, 'min_gain_to_split': 0.27746353949890884}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 21:23:32,192] Trial 320 finished with value: 1.0240752220832636 and parameters: {'num_leaves': 96, 'learning_rate': 0.2696006197609193, 'feature_fraction': 0.9053555938233819, 'bagging_fraction': 0.7195978387017121, 'bagging_freq': 1, 'lambda_l1': 0.07061436020665475, 'lambda_l2': 0.00027993947937590593, 'min_child_samples': 27, 'max_depth': 7, 'max_bin': 493, 'min_data_in_leaf': 25, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.0661674088861958, 'min_gain_to_split': 0.33660998188455493}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 21:27:28,910] Trial 321 finished with value: 0.9830952280811589 and parameters: {'num_leaves': 97, 'learning_rate': 0.24677455681637225, 'feature_fraction': 0.9283674644549511, 'bagging_fraction': 0.9353473624751497, 'bagging_freq': 1, 'lambda_l1': 0.021933822985148836, 'lambda_l2': 5.903504851098354e-06, 'min_child_samples': 29, 'max_depth': 7, 'max_bin': 485, 'min_data_in_leaf': 23, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.10709248705617468, 'min_gain_to_split': 0.3200866555498361}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 21:31:45,370] Trial 322 finished with value: 0.8754460308597333 and parameters: {'num_leaves': 93, 'learning_rate': 0.2680510593489187, 'feature_fraction': 0.9548112720264018, 'bagging_fraction': 0.7125839943233212, 'bagging_freq': 1, 'lambda_l1': 0.04014932974185997, 'lambda_l2': 2.550513397100495e-05, 'min_child_samples': 25, 'max_depth': 7, 'max_bin': 500, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.65896880912421, 'min_gain_to_split': 0.308187675896826}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 21:37:44,123] Trial 323 finished with value: 0.9708290235967081 and parameters: {'num_leaves': 96, 'learning_rate': 0.22511568938644044, 'feature_fraction': 0.9382631311464932, 'bagging_fraction': 0.8468500712143792, 'bagging_freq': 1, 'lambda_l1': 0.094654857279061, 'lambda_l2': 1.2929542801512147e-05, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 475, 'min_data_in_leaf': 26, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.6058875518170795, 'min_gain_to_split': 0.029332229132356655}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 21:40:11,880] Trial 324 finished with value: 0.7337784313366117 and parameters: {'num_leaves': 94, 'learning_rate': 0.2783448106827533, 'feature_fraction': 0.9220142847223309, 'bagging_fraction': 0.885350863472057, 'bagging_freq': 2, 'lambda_l1': 0.0668219374557585, 'lambda_l2': 2.7243037668413187e-06, 'min_child_samples': 31, 'max_depth': 7, 'max_bin': 329, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 28, 'path_smooth': 0.5811947798117267, 'min_gain_to_split': 0.36623790507660026}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 21:42:03,208] Trial 325 finished with value: 1.1779522520872825 and parameters: {'num_leaves': 94, 'learning_rate': 0.284217494598985, 'feature_fraction': 0.8982748683579105, 'bagging_fraction': 0.9020028296762685, 'bagging_freq': 3, 'lambda_l1': 0.06017255097075435, 'lambda_l2': 2.9935410877933055e-06, 'min_child_samples': 31, 'max_depth': 7, 'max_bin': 341, 'min_data_in_leaf': 30, 'extra_trees': False, 'early_stopping_rounds': 29, 'path_smooth': 0.5778860695861513, 'min_gain_to_split': 0.35900149156866756}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 21:44:06,535] Trial 326 finished with value: 1.0270958465800604 and parameters: {'num_leaves': 54, 'learning_rate': 0.2996939723295188, 'feature_fraction': 0.9119043113646065, 'bagging_fraction': 0.9589550937785448, 'bagging_freq': 2, 'lambda_l1': 0.016262949677278263, 'lambda_l2': 2.1051960340540123e-06, 'min_child_samples': 30, 'max_depth': 7, 'max_bin': 479, 'min_data_in_leaf': 35, 'extra_trees': False, 'early_stopping_rounds': 28, 'path_smooth': 0.5915381510065223, 'min_gain_to_split': 0.4085572499415811}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 21:46:00,001] Trial 327 finished with value: 1.2382452841261995 and parameters: {'num_leaves': 98, 'learning_rate': 0.14979481683498957, 'feature_fraction': 0.9203019095614279, 'bagging_fraction': 0.7095708698117796, 'bagging_freq': 2, 'lambda_l1': 0.028175929018700342, 'lambda_l2': 4.985932796931027e-06, 'min_child_samples': 31, 'max_depth': 7, 'max_bin': 329, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 28, 'path_smooth': 0.5690488983181125, 'min_gain_to_split': 0.4260469866558599}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 21:47:31,731] Trial 328 finished with value: 1.1718519195436563 and parameters: {'num_leaves': 94, 'learning_rate': 0.2562352461821655, 'feature_fraction': 0.9195420770234323, 'bagging_fraction': 0.9459624003670531, 'bagging_freq': 2, 'lambda_l1': 0.05363376434779047, 'lambda_l2': 2.3596268904406568e-06, 'min_child_samples': 30, 'max_depth': 6, 'max_bin': 269, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.6202976596724193, 'min_gain_to_split': 0.28476743898705}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 21:48:54,187] Trial 329 finished with value: 1.6074942656491136 and parameters: {'num_leaves': 92, 'learning_rate': 0.2756600118163603, 'feature_fraction': 0.9272318743922825, 'bagging_fraction': 0.8560024682291971, 'bagging_freq': 1, 'lambda_l1': 0.10598274467606032, 'lambda_l2': 3.097123254665832e-06, 'min_child_samples': 29, 'max_depth': 7, 'max_bin': 369, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.5942940402561669, 'min_gain_to_split': 0.3753447603826028}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 21:50:48,946] Trial 330 finished with value: 1.0249718499568954 and parameters: {'num_leaves': 95, 'learning_rate': 0.24353153771695538, 'feature_fraction': 0.9350669902730744, 'bagging_fraction': 0.9069574381196727, 'bagging_freq': 1, 'lambda_l1': 0.0011725195840623253, 'lambda_l2': 6.574991034583621e-06, 'min_child_samples': 32, 'max_depth': 7, 'max_bin': 443, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 29, 'path_smooth': 0.566430358951587, 'min_gain_to_split': 0.09425155617366904}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 21:52:29,491] Trial 331 finished with value: 0.6385051010641298 and parameters: {'num_leaves': 41, 'learning_rate': 0.26913856949869724, 'feature_fraction': 0.9111001071362771, 'bagging_fraction': 0.8570907907355347, 'bagging_freq': 1, 'lambda_l1': 0.04485648098210282, 'lambda_l2': 4.065009671046531e-06, 'min_child_samples': 24, 'max_depth': 7, 'max_bin': 282, 'min_data_in_leaf': 31, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.6957334479896391, 'min_gain_to_split': 0.2534795590685929}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 21:53:23,657] Trial 332 finished with value: 1.0919289364482077 and parameters: {'num_leaves': 24, 'learning_rate': 0.27891189170116415, 'feature_fraction': 0.9059908917017483, 'bagging_fraction': 0.8778143838590324, 'bagging_freq': 1, 'lambda_l1': 0.032070581004498944, 'lambda_l2': 3.5774146612068543e-06, 'min_child_samples': 24, 'max_depth': 7, 'max_bin': 239, 'min_data_in_leaf': 31, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.7110610218865729, 'min_gain_to_split': 0.23606523239485744}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 21:54:46,734] Trial 333 finished with value: 1.470633035011664 and parameters: {'num_leaves': 41, 'learning_rate': 0.269846550271658, 'feature_fraction': 0.9070723439585324, 'bagging_fraction': 0.8409837488012539, 'bagging_freq': 3, 'lambda_l1': 0.055384365593758665, 'lambda_l2': 1.5461836831247522e-06, 'min_child_samples': 23, 'max_depth': 7, 'max_bin': 297, 'min_data_in_leaf': 76, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.688132724755782, 'min_gain_to_split': 0.38377292352439507}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 21:56:11,363] Trial 334 finished with value: 1.5501760427819922 and parameters: {'num_leaves': 29, 'learning_rate': 0.2994765935750124, 'feature_fraction': 0.9187157688278668, 'bagging_fraction': 0.8236951088606586, 'bagging_freq': 1, 'lambda_l1': 0.04257028432535068, 'lambda_l2': 0.0005336373786409854, 'min_child_samples': 25, 'max_depth': 7, 'max_bin': 471, 'min_data_in_leaf': 30, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.6863556929095196, 'min_gain_to_split': 0.26682838601866327}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 21:57:14,290] Trial 335 finished with value: 1.075698063072057 and parameters: {'num_leaves': 67, 'learning_rate': 0.2124677088333044, 'feature_fraction': 0.7630801398676381, 'bagging_fraction': 0.8863805736672588, 'bagging_freq': 8, 'lambda_l1': 0.06894889830799741, 'lambda_l2': 4.181878740834134e-06, 'min_child_samples': 24, 'max_depth': 7, 'max_bin': 258, 'min_data_in_leaf': 35, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.6668457406453506, 'min_gain_to_split': 0.4491815169333589}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 21:58:20,543] Trial 336 finished with value: 1.6174398161965358 and parameters: {'num_leaves': 27, 'learning_rate': 0.28002534937002393, 'feature_fraction': 0.8984642618743461, 'bagging_fraction': 0.8603753210048996, 'bagging_freq': 1, 'lambda_l1': 0.09719589613747254, 'lambda_l2': 2.241492460710434e-06, 'min_child_samples': 25, 'max_depth': 7, 'max_bin': 491, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.7181227553222053, 'min_gain_to_split': 0.2290735484747334}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 22:00:06,756] Trial 337 finished with value: 0.7121903746767806 and parameters: {'num_leaves': 97, 'learning_rate': 0.2387760977791996, 'feature_fraction': 0.9133905109849947, 'bagging_fraction': 0.8903032568232722, 'bagging_freq': 2, 'lambda_l1': 0.019504620422479454, 'lambda_l2': 1.0987769914070145e-05, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 484, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.6476591115205096, 'min_gain_to_split': 0.18893282823762264}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 22:01:41,148] Trial 338 finished with value: 1.146888451398836 and parameters: {'num_leaves': 45, 'learning_rate': 0.22271017471547394, 'feature_fraction': 0.8935778225968382, 'bagging_fraction': 0.8709699836372683, 'bagging_freq': 2, 'lambda_l1': 0.022565393573450505, 'lambda_l2': 1.2301911180274602e-05, 'min_child_samples': 27, 'max_depth': 7, 'max_bin': 487, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 20, 'path_smooth': 0.6273863188033475, 'min_gain_to_split': 0.24960643725573492}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 22:02:54,175] Trial 339 finished with value: 1.250041972340728 and parameters: {'num_leaves': 99, 'learning_rate': 0.23807004476718813, 'feature_fraction': 0.9138841906642876, 'bagging_fraction': 0.8996382424758772, 'bagging_freq': 2, 'lambda_l1': 0.017696767646411933, 'lambda_l2': 1.7773126840064602e-05, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 452, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.6457562171568628, 'min_gain_to_split': 0.3452069627520596}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 22:04:10,001] Trial 340 finished with value: 1.1837919215294135 and parameters: {'num_leaves': 97, 'learning_rate': 0.20268928167963343, 'feature_fraction': 0.8826880931337648, 'bagging_fraction': 0.8920615367060084, 'bagging_freq': 2, 'lambda_l1': 0.03146042745953805, 'lambda_l2': 9.363361293607248e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 297, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.35233470741170003, 'min_gain_to_split': 0.2587360229670089}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 22:05:50,096] Trial 341 finished with value: 0.6205668427479085 and parameters: {'num_leaves': 100, 'learning_rate': 0.24679670359780476, 'feature_fraction': 0.9084886830262872, 'bagging_fraction': 0.8860611597538368, 'bagging_freq': 2, 'lambda_l1': 0.03270312849706524, 'lambda_l2': 5.373157770898201e-06, 'min_child_samples': 42, 'max_depth': 7, 'max_bin': 493, 'min_data_in_leaf': 72, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.3773610641033464, 'min_gain_to_split': 0.15225997706835095}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 22:06:59,713] Trial 342 finished with value: 1.2499908137715787 and parameters: {'num_leaves': 98, 'learning_rate': 0.2347146475449113, 'feature_fraction': 0.9076345032971186, 'bagging_fraction': 0.8806395966117365, 'bagging_freq': 2, 'lambda_l1': 0.010719497390752463, 'lambda_l2': 5.533139702753924e-06, 'min_child_samples': 42, 'max_depth': 6, 'max_bin': 308, 'min_data_in_leaf': 70, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.6543706643503521, 'min_gain_to_split': 0.1851243371712107}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 22:08:01,918] Trial 343 finished with value: 1.4557038667990814 and parameters: {'num_leaves': 100, 'learning_rate': 0.2513493727479142, 'feature_fraction': 0.914627119687485, 'bagging_fraction': 0.8877130649666845, 'bagging_freq': 2, 'lambda_l1': 0.01794236058651626, 'lambda_l2': 4.007894221742092e-06, 'min_child_samples': 50, 'max_depth': 7, 'max_bin': 492, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.3858401591247971, 'min_gain_to_split': 0.169623579399569}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 22:09:07,836] Trial 344 finished with value: 1.3223607798206105 and parameters: {'num_leaves': 99, 'learning_rate': 0.18285015899201454, 'feature_fraction': 0.9051051851236516, 'bagging_fraction': 0.9125204123392525, 'bagging_freq': 2, 'lambda_l1': 0.01407048140074561, 'lambda_l2': 3.07225681100229e-06, 'min_child_samples': 27, 'max_depth': 7, 'max_bin': 321, 'min_data_in_leaf': 88, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6121809071760929, 'min_gain_to_split': 0.13409842943670794}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 22:10:15,782] Trial 345 finished with value: 1.2560415028381335 and parameters: {'num_leaves': 100, 'learning_rate': 0.22503019029009175, 'feature_fraction': 0.9013235907192062, 'bagging_fraction': 0.8910288354603798, 'bagging_freq': 2, 'lambda_l1': 0.03979656796356451, 'lambda_l2': 5.774066874350384e-06, 'min_child_samples': 44, 'max_depth': 7, 'max_bin': 485, 'min_data_in_leaf': 74, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.40931878063054855, 'min_gain_to_split': 0.35431680754439143}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 22:11:38,773] Trial 346 finished with value: 1.214892853958651 and parameters: {'num_leaves': 97, 'learning_rate': 0.24225158816139888, 'feature_fraction': 0.8912843019500982, 'bagging_fraction': 0.8815202821081197, 'bagging_freq': 3, 'lambda_l1': 0.028077201629273667, 'lambda_l2': 1.2215956678894084e-05, 'min_child_samples': 47, 'max_depth': 8, 'max_bin': 499, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.6402117112111967, 'min_gain_to_split': 0.288909719807389}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 22:12:32,904] Trial 347 finished with value: 1.6910883378832657 and parameters: {'num_leaves': 97, 'learning_rate': 0.259741444664014, 'feature_fraction': 0.6653608712113863, 'bagging_fraction': 0.8118617015575738, 'bagging_freq': 2, 'lambda_l1': 0.009796478672688489, 'lambda_l2': 3.078227465574433e-05, 'min_child_samples': 41, 'max_depth': 7, 'max_bin': 355, 'min_data_in_leaf': 94, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.3814947543219253, 'min_gain_to_split': 0.14776570753261778}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 22:13:47,401] Trial 348 finished with value: 1.1177832893521011 and parameters: {'num_leaves': 17, 'learning_rate': 0.2103262571562574, 'feature_fraction': 0.9139501883125293, 'bagging_fraction': 0.927403063847915, 'bagging_freq': 2, 'lambda_l1': 0.051716657279433524, 'lambda_l2': 4.522507903716926e-06, 'min_child_samples': 43, 'max_depth': 7, 'max_bin': 484, 'min_data_in_leaf': 31, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.6751377294403098, 'min_gain_to_split': 0.21080337932966464}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 22:14:51,226] Trial 349 finished with value: 1.4093779209209198 and parameters: {'num_leaves': 61, 'learning_rate': 0.2490899564003336, 'feature_fraction': 0.9231820126811393, 'bagging_fraction': 0.8832719702214894, 'bagging_freq': 2, 'lambda_l1': 0.08170682042531077, 'lambda_l2': 2.6239541475715846e-06, 'min_child_samples': 23, 'max_depth': 7, 'max_bin': 272, 'min_data_in_leaf': 40, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.5982318091837424, 'min_gain_to_split': 0.3188595271799277}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 22:16:15,986] Trial 350 finished with value: 1.1136748297545804 and parameters: {'num_leaves': 95, 'learning_rate': 0.1936107290977208, 'feature_fraction': 0.9247922390351385, 'bagging_fraction': 0.895789328352141, 'bagging_freq': 2, 'lambda_l1': 0.030377539326834856, 'lambda_l2': 8.83650295434751e-06, 'min_child_samples': 40, 'max_depth': 7, 'max_bin': 281, 'min_data_in_leaf': 65, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6282427302391469, 'min_gain_to_split': 0.11660486966325256}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 22:18:18,784] Trial 351 finished with value: 1.4262300567738981 and parameters: {'num_leaves': 35, 'learning_rate': 0.03483750451887497, 'feature_fraction': 0.9127480179014386, 'bagging_fraction': 0.8988355871845702, 'bagging_freq': 2, 'lambda_l1': 0.14068452469448497, 'lambda_l2': 2.3638009538520667e-08, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 500, 'min_data_in_leaf': 30, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.4259276611841666, 'min_gain_to_split': 0.13290915582442034}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 22:19:33,355] Trial 352 finished with value: 0.8626351157117378 and parameters: {'num_leaves': 96, 'learning_rate': 0.2711099087225499, 'feature_fraction': 0.9274530867906489, 'bagging_fraction': 0.9780631757726483, 'bagging_freq': 1, 'lambda_l1': 0.045146423999834345, 'lambda_l2': 5.798346041483275e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 282, 'min_data_in_leaf': 35, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.5577767058305992, 'min_gain_to_split': 0.1523248372488551}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 22:20:51,991] Trial 353 finished with value: 1.6125725777770392 and parameters: {'num_leaves': 98, 'learning_rate': 0.055783361641788265, 'feature_fraction': 0.9197842233550261, 'bagging_fraction': 0.8650216342908498, 'bagging_freq': 3, 'lambda_l1': 0.0804585126649177, 'lambda_l2': 1.8015141086875792e-06, 'min_child_samples': 25, 'max_depth': 7, 'max_bin': 224, 'min_data_in_leaf': 82, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.2779560639144491, 'min_gain_to_split': 0.16149898350487277}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 22:22:36,143] Trial 354 finished with value: 1.281008129737002 and parameters: {'num_leaves': 96, 'learning_rate': 0.06990664285008791, 'feature_fraction': 0.9299088429890658, 'bagging_fraction': 0.9183609648740405, 'bagging_freq': 1, 'lambda_l1': 0.02312985194304063, 'lambda_l2': 2.177490384246968e-05, 'min_child_samples': 42, 'max_depth': 7, 'max_bin': 257, 'min_data_in_leaf': 67, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.5840666606107141, 'min_gain_to_split': 0.11640141487565218}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 22:24:01,346] Trial 355 finished with value: 1.1322213353685202 and parameters: {'num_leaves': 94, 'learning_rate': 0.2313333313127931, 'feature_fraction': 0.896492206546499, 'bagging_fraction': 0.889602653899215, 'bagging_freq': 2, 'lambda_l1': 0.1442307202629825, 'lambda_l2': 4.038230514521961e-06, 'min_child_samples': 29, 'max_depth': 7, 'max_bin': 492, 'min_data_in_leaf': 31, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.6598689448444344, 'min_gain_to_split': 0.18015086997390303}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 22:24:58,610] Trial 356 finished with value: 1.2296461967964878 and parameters: {'num_leaves': 64, 'learning_rate': 0.2832117328149408, 'feature_fraction': 0.9124868415825157, 'bagging_fraction': 0.8331501748806444, 'bagging_freq': 1, 'lambda_l1': 0.06294139578739995, 'lambda_l2': 9.038819747316066e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 478, 'min_data_in_leaf': 27, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.6098638804146762, 'min_gain_to_split': 0.4735439663525297}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 22:26:16,506] Trial 357 finished with value: 1.2829743859430773 and parameters: {'num_leaves': 57, 'learning_rate': 0.2590203038776584, 'feature_fraction': 0.8216221703784574, 'bagging_fraction': 0.8752400354541587, 'bagging_freq': 1, 'lambda_l1': 0.016138548519366084, 'lambda_l2': 4.986428611458829e-05, 'min_child_samples': 46, 'max_depth': 7, 'max_bin': 472, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.3412350242645219, 'min_gain_to_split': 0.1065846829239952}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 22:27:56,522] Trial 358 finished with value: 0.5398560063951731 and parameters: {'num_leaves': 99, 'learning_rate': 0.24497641161412126, 'feature_fraction': 0.9321898871595365, 'bagging_fraction': 0.8736420469680718, 'bagging_freq': 2, 'lambda_l1': 0.10123570097993276, 'lambda_l2': 2.7733942795614656e-06, 'min_child_samples': 27, 'max_depth': 7, 'max_bin': 482, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5559237682604177, 'min_gain_to_split': 0.2025661124379241}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 22:29:20,562] Trial 359 finished with value: 1.1983738898879497 and parameters: {'num_leaves': 99, 'learning_rate': 0.21475311712575754, 'feature_fraction': 0.9437450194033686, 'bagging_fraction': 0.8549883456229912, 'bagging_freq': 2, 'lambda_l1': 0.03810503290037635, 'lambda_l2': 1.4163409220163879e-05, 'min_child_samples': 27, 'max_depth': 7, 'max_bin': 487, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.566944500640403, 'min_gain_to_split': 0.20201570497350152}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 22:30:30,493] Trial 360 finished with value: 1.2660486972502594 and parameters: {'num_leaves': 96, 'learning_rate': 0.24008213369681028, 'feature_fraction': 0.9216336011839071, 'bagging_fraction': 0.8870057212330802, 'bagging_freq': 2, 'lambda_l1': 0.09797277414789281, 'lambda_l2': 6.536683098770171e-06, 'min_child_samples': 26, 'max_depth': 6, 'max_bin': 481, 'min_data_in_leaf': 25, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.5848043159729789, 'min_gain_to_split': 0.39315534362099486}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 22:32:12,010] Trial 361 finished with value: 0.8786123972383928 and parameters: {'num_leaves': 100, 'learning_rate': 0.22331374741734547, 'feature_fraction': 0.9362513865839099, 'bagging_fraction': 0.8707250523689246, 'bagging_freq': 2, 'lambda_l1': 0.05477770731106955, 'lambda_l2': 3.461188032875645e-06, 'min_child_samples': 24, 'max_depth': 7, 'max_bin': 491, 'min_data_in_leaf': 27, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6213400204448499, 'min_gain_to_split': 0.19072260394990861}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 22:32:58,719] Trial 362 finished with value: 1.352720896802022 and parameters: {'num_leaves': 98, 'learning_rate': 0.2990730814506285, 'feature_fraction': 0.9075338968222316, 'bagging_fraction': 0.8817623701433593, 'bagging_freq': 2, 'lambda_l1': 0.034223198806515406, 'lambda_l2': 1.4809827455398718e-06, 'min_child_samples': 27, 'max_depth': 8, 'max_bin': 500, 'min_data_in_leaf': 29, 'extra_trees': True, 'early_stopping_rounds': 24, 'path_smooth': 0.6441689971924297, 'min_gain_to_split': 0.1417931582240308}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 22:34:15,258] Trial 363 finished with value: 1.2811582416228637 and parameters: {'num_leaves': 100, 'learning_rate': 0.2477731262068814, 'feature_fraction': 0.8712355147829755, 'bagging_fraction': 0.8636570888970454, 'bagging_freq': 2, 'lambda_l1': 0.0735686972524118, 'lambda_l2': 1.4051646936444918e-08, 'min_child_samples': 25, 'max_depth': 7, 'max_bin': 479, 'min_data_in_leaf': 73, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.5578851048938678, 'min_gain_to_split': 0.1618346019433338}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 22:35:10,293] Trial 364 finished with value: 1.1485724184165254 and parameters: {'num_leaves': 47, 'learning_rate': 0.27031232014628725, 'feature_fraction': 0.9275822699523572, 'bagging_fraction': 0.8766668014125656, 'bagging_freq': 2, 'lambda_l1': 0.10929545554058143, 'lambda_l2': 5.298744692526141e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 186, 'min_data_in_leaf': 37, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.6011029911218486, 'min_gain_to_split': 0.21540352934534968}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 22:36:03,373] Trial 365 finished with value: 1.8163483432288552 and parameters: {'num_leaves': 95, 'learning_rate': 0.2834508592321451, 'feature_fraction': 0.918704189522139, 'bagging_fraction': 0.8945738694718162, 'bagging_freq': 3, 'lambda_l1': 0.04747720936950129, 'lambda_l2': 2.4125193082473048e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 114, 'min_data_in_leaf': 79, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6936162452540785, 'min_gain_to_split': 0.15449616002653632}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 22:37:36,818] Trial 366 finished with value: 1.0336266485325063 and parameters: {'num_leaves': 98, 'learning_rate': 0.2340687848451676, 'feature_fraction': 0.9410270100381066, 'bagging_fraction': 0.8542915930669102, 'bagging_freq': 2, 'lambda_l1': 0.02106811748465181, 'lambda_l2': 1.0398482322109487e-05, 'min_child_samples': 27, 'max_depth': 7, 'max_bin': 465, 'min_data_in_leaf': 26, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.574119892826804, 'min_gain_to_split': 0.1757898159057437}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 22:39:04,701] Trial 367 finished with value: 1.174341857253264 and parameters: {'num_leaves': 97, 'learning_rate': 0.26271524100607263, 'feature_fraction': 0.9485516412046764, 'bagging_fraction': 0.8743130231583149, 'bagging_freq': 1, 'lambda_l1': 0.1452798458741595, 'lambda_l2': 3.231622525169797e-08, 'min_child_samples': 29, 'max_depth': 8, 'max_bin': 287, 'min_data_in_leaf': 31, 'extra_trees': False, 'early_stopping_rounds': 50, 'path_smooth': 0.6680462031666332, 'min_gain_to_split': 0.12778030752654831}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 22:40:10,616] Trial 368 finished with value: 0.7582393692112518 and parameters: {'num_leaves': 95, 'learning_rate': 0.2527110835480954, 'feature_fraction': 0.9010255964628991, 'bagging_fraction': 0.9040503712904906, 'bagging_freq': 1, 'lambda_l1': 0.06492508335548504, 'lambda_l2': 0.0001326823758240222, 'min_child_samples': 24, 'max_depth': 7, 'max_bin': 309, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.5470052169152777, 'min_gain_to_split': 0.3674023126345026}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 22:41:22,307] Trial 369 finished with value: 0.7354436377104909 and parameters: {'num_leaves': 95, 'learning_rate': 0.28260390136750957, 'feature_fraction': 0.9065754648347142, 'bagging_fraction': 0.9075866314830451, 'bagging_freq': 1, 'lambda_l1': 0.013757737634642496, 'lambda_l2': 8.193234130277406e-05, 'min_child_samples': 21, 'max_depth': 7, 'max_bin': 331, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.5448170750171687, 'min_gain_to_split': 0.36953591332280744}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 22:42:31,025] Trial 370 finished with value: 0.8297558700132941 and parameters: {'num_leaves': 95, 'learning_rate': 0.25029228120524494, 'feature_fraction': 0.8981964715279964, 'bagging_fraction': 0.9007329221361624, 'bagging_freq': 1, 'lambda_l1': 0.009898477269676565, 'lambda_l2': 8.428518269403252e-05, 'min_child_samples': 21, 'max_depth': 7, 'max_bin': 313, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.5473234018804888, 'min_gain_to_split': 0.3709978724919205}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 22:43:34,679] Trial 371 finished with value: 0.8296559487443778 and parameters: {'num_leaves': 43, 'learning_rate': 0.270027063860159, 'feature_fraction': 0.8908619852316668, 'bagging_fraction': 0.9044167108975125, 'bagging_freq': 1, 'lambda_l1': 0.008403044755579377, 'lambda_l2': 0.00010986893408984978, 'min_child_samples': 16, 'max_depth': 7, 'max_bin': 295, 'min_data_in_leaf': 25, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.5252656039977726, 'min_gain_to_split': 0.3627743841187911}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 22:44:30,346] Trial 372 finished with value: 1.1349817537535818 and parameters: {'num_leaves': 97, 'learning_rate': 0.28433698519709916, 'feature_fraction': 0.9025590824210183, 'bagging_fraction': 0.8947367882781739, 'bagging_freq': 1, 'lambda_l1': 0.012364246621431511, 'lambda_l2': 6.546916006858387e-05, 'min_child_samples': 22, 'max_depth': 7, 'max_bin': 329, 'min_data_in_leaf': 27, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.5430448218210713, 'min_gain_to_split': 0.3675906615284006}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 22:45:25,571] Trial 373 finished with value: 1.206276068489561 and parameters: {'num_leaves': 95, 'learning_rate': 0.25143842703381064, 'feature_fraction': 0.886405049306964, 'bagging_fraction': 0.8910154471672306, 'bagging_freq': 2, 'lambda_l1': 0.0024317502293303974, 'lambda_l2': 0.00011950520042305797, 'min_child_samples': 20, 'max_depth': 6, 'max_bin': 304, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.5855215941654626, 'min_gain_to_split': 0.3775344295298747}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 22:46:24,668] Trial 374 finished with value: 0.9709315495652362 and parameters: {'num_leaves': 98, 'learning_rate': 0.26494797617133364, 'feature_fraction': 0.9081470330174403, 'bagging_fraction': 0.9067280112904235, 'bagging_freq': 1, 'lambda_l1': 0.014847836205090033, 'lambda_l2': 0.0002349765640276733, 'min_child_samples': 19, 'max_depth': 7, 'max_bin': 311, 'min_data_in_leaf': 24, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.563603095510825, 'min_gain_to_split': 0.39534624694574694}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 22:47:20,051] Trial 375 finished with value: 1.1826288894353922 and parameters: {'num_leaves': 94, 'learning_rate': 0.2846329801949103, 'feature_fraction': 0.9006038381177586, 'bagging_fraction': 0.9057765244155898, 'bagging_freq': 3, 'lambda_l1': 0.02343313915198574, 'lambda_l2': 0.00017845202185199022, 'min_child_samples': 20, 'max_depth': 7, 'max_bin': 318, 'min_data_in_leaf': 62, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.5495859575672877, 'min_gain_to_split': 0.35164347852445854}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 22:48:17,724] Trial 376 finished with value: 1.2188449089251585 and parameters: {'num_leaves': 100, 'learning_rate': 0.29910336922688524, 'feature_fraction': 0.9105234667764159, 'bagging_fraction': 0.9095363197332289, 'bagging_freq': 1, 'lambda_l1': 0.028813179886207956, 'lambda_l2': 4.5586750301054624e-05, 'min_child_samples': 22, 'max_depth': 7, 'max_bin': 332, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.5743226602215037, 'min_gain_to_split': 0.36388670941437495}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 22:49:21,576] Trial 377 finished with value: 1.1328481587044434 and parameters: {'num_leaves': 96, 'learning_rate': 0.23983628900869228, 'feature_fraction': 0.9171505088549046, 'bagging_fraction': 0.8496677238746363, 'bagging_freq': 1, 'lambda_l1': 0.03695920358301011, 'lambda_l2': 0.00016398873496766716, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 275, 'min_data_in_leaf': 50, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.5256449871838521, 'min_gain_to_split': 0.3288732890222509}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 22:50:30,376] Trial 378 finished with value: 1.1695787332180165 and parameters: {'num_leaves': 39, 'learning_rate': 0.2584413676521102, 'feature_fraction': 0.9018935243695043, 'bagging_fraction': 0.8829088846599119, 'bagging_freq': 2, 'lambda_l1': 0.0176693583314783, 'lambda_l2': 1.672818317704899e-05, 'min_child_samples': 27, 'max_depth': 7, 'max_bin': 345, 'min_data_in_leaf': 26, 'extra_trees': False, 'early_stopping_rounds': 21, 'path_smooth': 0.00017398293549276272, 'min_gain_to_split': 0.24640948066621704}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 22:51:49,395] Trial 379 finished with value: 0.8131093540170202 and parameters: {'num_leaves': 93, 'learning_rate': 0.2995722332907897, 'feature_fraction': 0.8777811366217065, 'bagging_fraction': 0.9106046117437303, 'bagging_freq': 1, 'lambda_l1': 0.005827686772682753, 'lambda_l2': 3.313035383904985e-05, 'min_child_samples': 21, 'max_depth': 7, 'max_bin': 332, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.5969500128000145, 'min_gain_to_split': 0.08724467342424347}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 22:52:55,134] Trial 380 finished with value: 1.2874344185200532 and parameters: {'num_leaves': 96, 'learning_rate': 0.23641420612160857, 'feature_fraction': 0.907905061572702, 'bagging_fraction': 0.9155949663083621, 'bagging_freq': 1, 'lambda_l1': 0.0612664731840228, 'lambda_l2': 0.00033255129505362546, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 319, 'min_data_in_leaf': 27, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.4441395520390804, 'min_gain_to_split': 0.38213587109686803}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 22:53:43,103] Trial 381 finished with value: 1.119947332936692 and parameters: {'num_leaves': 93, 'learning_rate': 0.26867517821597553, 'feature_fraction': 0.9175160310278424, 'bagging_fraction': 0.8979192617344355, 'bagging_freq': 6, 'lambda_l1': 0.03600311289381046, 'lambda_l2': 3.716512148672567e-05, 'min_child_samples': 29, 'max_depth': 7, 'max_bin': 338, 'min_data_in_leaf': 30, 'extra_trees': True, 'early_stopping_rounds': 25, 'path_smooth': 0.5496384505894729, 'min_gain_to_split': 0.38494517819570545}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 22:54:49,494] Trial 382 finished with value: 1.3969058762034874 and parameters: {'num_leaves': 99, 'learning_rate': 0.2234203818624542, 'feature_fraction': 0.8901865228265017, 'bagging_fraction': 0.9202909810428301, 'bagging_freq': 1, 'lambda_l1': 0.02271341639030728, 'lambda_l2': 1.775052570930091e-05, 'min_child_samples': 40, 'max_depth': 7, 'max_bin': 286, 'min_data_in_leaf': 23, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.6108264091697034, 'min_gain_to_split': 0.351022393707871}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 22:55:53,218] Trial 383 finished with value: 0.9916660087935434 and parameters: {'num_leaves': 94, 'learning_rate': 0.2530369965327232, 'feature_fraction': 0.7097024698289413, 'bagging_fraction': 0.8623168252241085, 'bagging_freq': 1, 'lambda_l1': 0.007226527668399075, 'lambda_l2': 9.250024106875442e-05, 'min_child_samples': 27, 'max_depth': 7, 'max_bin': 302, 'min_data_in_leaf': 25, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.562690684926534, 'min_gain_to_split': 0.20432430519280198}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 22:56:57,679] Trial 384 finished with value: 1.2652412182968344 and parameters: {'num_leaves': 98, 'learning_rate': 0.27155988518312985, 'feature_fraction': 0.9254927905464505, 'bagging_fraction': 0.7000056802088278, 'bagging_freq': 1, 'lambda_l1': 0.18972572997814963, 'lambda_l2': 2.3429833378224505e-05, 'min_child_samples': 41, 'max_depth': 7, 'max_bin': 434, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.5826435371655069, 'min_gain_to_split': 0.371696887216182}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 22:57:51,128] Trial 385 finished with value: 1.1162776203389349 and parameters: {'num_leaves': 20, 'learning_rate': 0.28040851129363553, 'feature_fraction': 0.9106354895750882, 'bagging_fraction': 0.8418939119460023, 'bagging_freq': 2, 'lambda_l1': 0.012771435811244184, 'lambda_l2': 6.756738728967234e-05, 'min_child_samples': 18, 'max_depth': 8, 'max_bin': 265, 'min_data_in_leaf': 27, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.5131649926670232, 'min_gain_to_split': 0.10126706444966077}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 22:59:10,159] Trial 386 finished with value: 1.1280683501248276 and parameters: {'num_leaves': 96, 'learning_rate': 0.2501959689217307, 'feature_fraction': 0.9336379833623255, 'bagging_fraction': 0.8690769789408527, 'bagging_freq': 5, 'lambda_l1': 0.06395575690287555, 'lambda_l2': 7.713998118986273e-06, 'min_child_samples': 19, 'max_depth': 7, 'max_bin': 493, 'min_data_in_leaf': 31, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.5330756663658933, 'min_gain_to_split': 0.3372833079815621}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 23:00:24,908] Trial 387 finished with value: 1.1273420772506224 and parameters: {'num_leaves': 92, 'learning_rate': 0.23575481311771052, 'feature_fraction': 0.9186191920017216, 'bagging_fraction': 0.7956475586152026, 'bagging_freq': 1, 'lambda_l1': 0.09456825293743724, 'lambda_l2': 0.0004529083650906413, 'min_child_samples': 23, 'max_depth': 7, 'max_bin': 365, 'min_data_in_leaf': 26, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.5928482339354452, 'min_gain_to_split': 0.22484186645722648}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 23:01:31,099] Trial 388 finished with value: 1.2274543932925446 and parameters: {'num_leaves': 95, 'learning_rate': 0.2810262756179068, 'feature_fraction': 0.9586347319649111, 'bagging_fraction': 0.7060503133221888, 'bagging_freq': 1, 'lambda_l1': 0.038969365065406145, 'lambda_l2': 4.198574063045586e-06, 'min_child_samples': 24, 'max_depth': 7, 'max_bin': 472, 'min_data_in_leaf': 24, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.5601317827671135, 'min_gain_to_split': 0.3436651832607663}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 23:02:34,841] Trial 389 finished with value: 1.3895051713449695 and parameters: {'num_leaves': 94, 'learning_rate': 0.261619839816677, 'feature_fraction': 0.9280611084007659, 'bagging_fraction': 0.9249653907701838, 'bagging_freq': 1, 'lambda_l1': 0.19171808623006592, 'lambda_l2': 1.1224778433179552e-06, 'min_child_samples': 48, 'max_depth': 7, 'max_bin': 293, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.6162871607770093, 'min_gain_to_split': 0.2693643442201999}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 23:04:01,509] Trial 390 finished with value: 1.1373012765178299 and parameters: {'num_leaves': 98, 'learning_rate': 0.21740756930139565, 'feature_fraction': 0.7999426834337143, 'bagging_fraction': 0.8862909677470467, 'bagging_freq': 1, 'lambda_l1': 0.027697838951402532, 'lambda_l2': 2.7263041340655527e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 490, 'min_data_in_leaf': 30, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5762933439225411, 'min_gain_to_split': 0.1921008447820011}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 23:05:48,265] Trial 391 finished with value: 1.0192674742416499 and parameters: {'num_leaves': 74, 'learning_rate': 0.2466177867077667, 'feature_fraction': 0.8982352478719482, 'bagging_fraction': 0.7051964033546159, 'bagging_freq': 2, 'lambda_l1': 0.05318740910318577, 'lambda_l2': 9.676446485166644e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 434, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.6297895347533422, 'min_gain_to_split': 0.07664538908281804}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 23:07:02,429] Trial 392 finished with value: 0.9688518403174108 and parameters: {'num_leaves': 92, 'learning_rate': 0.2992525783620208, 'feature_fraction': 0.9704476158896012, 'bagging_fraction': 0.8952867621902256, 'bagging_freq': 1, 'lambda_l1': 0.2547099398579846, 'lambda_l2': 5.584713080951596e-06, 'min_child_samples': 39, 'max_depth': 7, 'max_bin': 487, 'min_data_in_leaf': 26, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.5360248082239952, 'min_gain_to_split': 0.2998434106907619}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 23:08:10,793] Trial 393 finished with value: 1.1331204398061279 and parameters: {'num_leaves': 96, 'learning_rate': 0.2660524003230159, 'feature_fraction': 0.8476309995374102, 'bagging_fraction': 0.8782015901520146, 'bagging_freq': 1, 'lambda_l1': 1.3995704576700818e-05, 'lambda_l2': 1.6953304510080211e-06, 'min_child_samples': 45, 'max_depth': 7, 'max_bin': 438, 'min_data_in_leaf': 53, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.5007241440228416, 'min_gain_to_split': 0.3646751976279456}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 23:09:15,468] Trial 394 finished with value: 0.5675887152684392 and parameters: {'num_leaves': 93, 'learning_rate': 0.2842046216411442, 'feature_fraction': 0.9389768026569837, 'bagging_fraction': 0.7113027611715513, 'bagging_freq': 1, 'lambda_l1': 4.0425624528761165e-06, 'lambda_l2': 0.0009754468889988064, 'min_child_samples': 23, 'max_depth': 7, 'max_bin': 470, 'min_data_in_leaf': 30, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.5557916419241783, 'min_gain_to_split': 0.4849798834377387}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 23:10:13,088] Trial 395 finished with value: 1.4181715021410686 and parameters: {'num_leaves': 91, 'learning_rate': 0.28445906375123575, 'feature_fraction': 0.9425954475474584, 'bagging_fraction': 0.7104706622471944, 'bagging_freq': 2, 'lambda_l1': 0.31936037266858547, 'lambda_l2': 3.4678422172870694e-06, 'min_child_samples': 21, 'max_depth': 7, 'max_bin': 384, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.593677338525409, 'min_gain_to_split': 0.48882694485903033}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 23:11:09,848] Trial 396 finished with value: 1.2790406708940563 and parameters: {'num_leaves': 53, 'learning_rate': 0.2842671065173908, 'feature_fraction': 0.935650186917121, 'bagging_fraction': 0.7127199558776676, 'bagging_freq': 1, 'lambda_l1': 2.138294656721626e-07, 'lambda_l2': 0.0023491607172854137, 'min_child_samples': 22, 'max_depth': 6, 'max_bin': 467, 'min_data_in_leaf': 22, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5648484674037961, 'min_gain_to_split': 0.4929395207076322}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 23:12:36,264] Trial 397 finished with value: 0.8157241789935517 and parameters: {'num_leaves': 49, 'learning_rate': 0.27342110506599243, 'feature_fraction': 0.9562937167416128, 'bagging_fraction': 0.7038984432862276, 'bagging_freq': 1, 'lambda_l1': 0.015986450542498132, 'lambda_l2': 0.000766460329828115, 'min_child_samples': 30, 'max_depth': 7, 'max_bin': 477, 'min_data_in_leaf': 30, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.6084819998452576, 'min_gain_to_split': 0.14475429459992847}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 23:13:51,832] Trial 398 finished with value: 1.5896474753579874 and parameters: {'num_leaves': 93, 'learning_rate': 0.08068081554139069, 'feature_fraction': 0.9258092172116554, 'bagging_fraction': 0.7191320737440009, 'bagging_freq': 1, 'lambda_l1': 0.0002583024169177069, 'lambda_l2': 7.50329991345615e-06, 'min_child_samples': 23, 'max_depth': 7, 'max_bin': 500, 'min_data_in_leaf': 91, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5793150947558916, 'min_gain_to_split': 0.4776594699676635}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 23:14:28,960] Trial 399 finished with value: 1.3416510828473787 and parameters: {'num_leaves': 91, 'learning_rate': 0.29917637548192316, 'feature_fraction': 0.9461958696581474, 'bagging_fraction': 0.7091849535592304, 'bagging_freq': 1, 'lambda_l1': 1.05634661007931e-07, 'lambda_l2': 0.0016812650950574506, 'min_child_samples': 29, 'max_depth': 7, 'max_bin': 469, 'min_data_in_leaf': 97, 'extra_trees': True, 'early_stopping_rounds': 10, 'path_smooth': 0.6388636459413333, 'min_gain_to_split': 0.49194831571925224}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 23:16:00,140] Trial 400 finished with value: 1.2111820270764124 and parameters: {'num_leaves': 100, 'learning_rate': 0.09437345125437407, 'feature_fraction': 0.9359510929089543, 'bagging_fraction': 0.7217731746659104, 'bagging_freq': 4, 'lambda_l1': 8.583713090637459e-07, 'lambda_l2': 0.001292415287054391, 'min_child_samples': 30, 'max_depth': 7, 'max_bin': 462, 'min_data_in_leaf': 31, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.5214175769098884, 'min_gain_to_split': 0.48402112147148035}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 23:16:59,246] Trial 401 finished with value: 1.3638216834684747 and parameters: {'num_leaves': 93, 'learning_rate': 0.2648316705190194, 'feature_fraction': 0.9314858175077497, 'bagging_fraction': 0.7129467658355937, 'bagging_freq': 2, 'lambda_l1': 0.1292054656027306, 'lambda_l2': 1.3556662499485223e-05, 'min_child_samples': 42, 'max_depth': 7, 'max_bin': 481, 'min_data_in_leaf': 34, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.5603350841631467, 'min_gain_to_split': 0.47141965389677654}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 23:18:31,349] Trial 402 finished with value: 0.7494272489746816 and parameters: {'num_leaves': 97, 'learning_rate': 0.23014306353935138, 'feature_fraction': 0.9224133634386145, 'bagging_fraction': 0.8707724092888056, 'bagging_freq': 1, 'lambda_l1': 0.1875182242357199, 'lambda_l2': 5.052428650560575e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 455, 'min_data_in_leaf': 25, 'extra_trees': False, 'early_stopping_rounds': 28, 'path_smooth': 0.5906584358915485, 'min_gain_to_split': 0.23274560682334106}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 23:20:16,127] Trial 403 finished with value: 0.6937662309516437 and parameters: {'num_leaves': 97, 'learning_rate': 0.21274898237210077, 'feature_fraction': 0.9202707119209727, 'bagging_fraction': 0.8690895389211492, 'bagging_freq': 1, 'lambda_l1': 2.641223640295457e-05, 'lambda_l2': 0.0007861580009141446, 'min_child_samples': 28, 'max_depth': 8, 'max_bin': 455, 'min_data_in_leaf': 24, 'extra_trees': False, 'early_stopping_rounds': 28, 'path_smooth': 0.5908760633596751, 'min_gain_to_split': 0.1966873369788099}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 23:21:43,201] Trial 404 finished with value: 1.2428105161192031 and parameters: {'num_leaves': 98, 'learning_rate': 0.19451782597031814, 'feature_fraction': 0.9173250266775481, 'bagging_fraction': 0.867460999199598, 'bagging_freq': 2, 'lambda_l1': 4.576849396800308e-06, 'lambda_l2': 0.0006499797377426136, 'min_child_samples': 28, 'max_depth': 8, 'max_bin': 456, 'min_data_in_leaf': 23, 'extra_trees': False, 'early_stopping_rounds': 28, 'path_smooth': 0.5942597692317135, 'min_gain_to_split': 0.2169107111603628}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 23:23:27,249] Trial 405 finished with value: 1.1133079362243479 and parameters: {'num_leaves': 100, 'learning_rate': 0.2144231192942227, 'feature_fraction': 0.92258821744251, 'bagging_fraction': 0.8754119027581124, 'bagging_freq': 1, 'lambda_l1': 1.239654151901495e-05, 'lambda_l2': 0.0012590793017110363, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 448, 'min_data_in_leaf': 24, 'extra_trees': False, 'early_stopping_rounds': 29, 'path_smooth': 0.606525349854914, 'min_gain_to_split': 0.1866084995606002}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 23:25:16,441] Trial 406 finished with value: 1.1873536112486303 and parameters: {'num_leaves': 97, 'learning_rate': 0.20519093493125062, 'feature_fraction': 0.9119676911069989, 'bagging_fraction': 0.8704148742301007, 'bagging_freq': 1, 'lambda_l1': 4.904277268303019e-05, 'lambda_l2': 0.0017339715461294856, 'min_child_samples': 27, 'max_depth': 9, 'max_bin': 459, 'min_data_in_leaf': 21, 'extra_trees': False, 'early_stopping_rounds': 28, 'path_smooth': 0.5818983635853476, 'min_gain_to_split': 0.20694957829949034}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 23:26:54,618] Trial 407 finished with value: 1.0703022061723189 and parameters: {'num_leaves': 97, 'learning_rate': 0.226224512547263, 'feature_fraction': 0.9236327661398219, 'bagging_fraction': 0.8596265419860712, 'bagging_freq': 1, 'lambda_l1': 3.1260422633178045e-06, 'lambda_l2': 0.0008680190221898687, 'min_child_samples': 28, 'max_depth': 8, 'max_bin': 459, 'min_data_in_leaf': 24, 'extra_trees': False, 'early_stopping_rounds': 29, 'path_smooth': 0.5472948581039736, 'min_gain_to_split': 0.23137711126823907}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 23:28:17,269] Trial 408 finished with value: 1.2417664593296398 and parameters: {'num_leaves': 99, 'learning_rate': 0.23011597462888836, 'feature_fraction': 0.9163064366750576, 'bagging_fraction': 0.8871872340448688, 'bagging_freq': 9, 'lambda_l1': 8.984152484508172e-06, 'lambda_l2': 3.19571905677022e-06, 'min_child_samples': 27, 'max_depth': 8, 'max_bin': 467, 'min_data_in_leaf': 25, 'extra_trees': False, 'early_stopping_rounds': 44, 'path_smooth': 0.571398426792512, 'min_gain_to_split': 0.19117514680368836}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 23:30:04,531] Trial 409 finished with value: 0.881502230798618 and parameters: {'num_leaves': 97, 'learning_rate': 0.20855803609071724, 'feature_fraction': 0.9282374159691704, 'bagging_fraction': 0.8632925560272332, 'bagging_freq': 1, 'lambda_l1': 4.7349099616603064e-06, 'lambda_l2': 0.00043767943930607015, 'min_child_samples': 29, 'max_depth': 10, 'max_bin': 453, 'min_data_in_leaf': 22, 'extra_trees': False, 'early_stopping_rounds': 28, 'path_smooth': 0.5964107585447274, 'min_gain_to_split': 0.24186046864894398}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 23:31:21,881] Trial 410 finished with value: 1.0275425503539435 and parameters: {'num_leaves': 59, 'learning_rate': 0.23706770527118784, 'feature_fraction': 0.909668401715383, 'bagging_fraction': 0.8718063644280641, 'bagging_freq': 2, 'lambda_l1': 0.021551297257926497, 'lambda_l2': 0.0006167772951424617, 'min_child_samples': 28, 'max_depth': 6, 'max_bin': 442, 'min_data_in_leaf': 26, 'extra_trees': False, 'early_stopping_rounds': 28, 'path_smooth': 0.9513665314720147, 'min_gain_to_split': 0.20580217797387038}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 23:32:08,106] Trial 411 finished with value: 1.127139854304469 and parameters: {'num_leaves': 96, 'learning_rate': 0.22691913106246012, 'feature_fraction': 0.9349535799175942, 'bagging_fraction': 0.8753903186431067, 'bagging_freq': 1, 'lambda_l1': 1.794093520721184e-05, 'lambda_l2': 0.0009633063096820588, 'min_child_samples': 26, 'max_depth': 3, 'max_bin': 447, 'min_data_in_leaf': 22, 'extra_trees': False, 'early_stopping_rounds': 21, 'path_smooth': 0.6121020397109455, 'min_gain_to_split': 0.168617829007788}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 23:33:06,658] Trial 412 finished with value: 1.177034998843073 and parameters: {'num_leaves': 98, 'learning_rate': 0.1852810065415606, 'feature_fraction': 0.9215861483354327, 'bagging_fraction': 0.8587367816045244, 'bagging_freq': 1, 'lambda_l1': 1.975008983589027e-06, 'lambda_l2': 4.742777557405098e-06, 'min_child_samples': 27, 'max_depth': 6, 'max_bin': 250, 'min_data_in_leaf': 25, 'extra_trees': False, 'early_stopping_rounds': 30, 'path_smooth': 0.5397534124272524, 'min_gain_to_split': 0.18181601842889367}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 23:34:40,607] Trial 413 finished with value: 1.070380983192103 and parameters: {'num_leaves': 100, 'learning_rate': 0.24335081150766985, 'feature_fraction': 0.9293270837941586, 'bagging_fraction': 0.8644664224047652, 'bagging_freq': 1, 'lambda_l1': 0.00015690127836492275, 'lambda_l2': 1.9002857375195879e-06, 'min_child_samples': 25, 'max_depth': 7, 'max_bin': 462, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.5843740226981232, 'min_gain_to_split': 0.21940832831511678}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 23:36:08,837] Trial 414 finished with value: 1.3919227029810606 and parameters: {'num_leaves': 95, 'learning_rate': 0.2175836699850447, 'feature_fraction': 0.9175005545980889, 'bagging_fraction': 0.8831650740512098, 'bagging_freq': 2, 'lambda_l1': 0.0005082072358306355, 'lambda_l2': 2.4052685156473825e-06, 'min_child_samples': 28, 'max_depth': 9, 'max_bin': 455, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.5621571124337262, 'min_gain_to_split': 0.22520582134317896}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 23:37:32,607] Trial 415 finished with value: 0.8581327672888909 and parameters: {'num_leaves': 91, 'learning_rate': 0.2469250895423128, 'feature_fraction': 0.6007047105309866, 'bagging_fraction': 0.8544222940359272, 'bagging_freq': 1, 'lambda_l1': 0.08862831640935806, 'lambda_l2': 0.00034538642832205457, 'min_child_samples': 29, 'max_depth': 8, 'max_bin': 470, 'min_data_in_leaf': 23, 'extra_trees': False, 'early_stopping_rounds': 29, 'path_smooth': 0.3671255798751004, 'min_gain_to_split': 0.1933302571239678}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 23:38:45,227] Trial 416 finished with value: 1.3483282649297512 and parameters: {'num_leaves': 93, 'learning_rate': 0.25761240009295705, 'feature_fraction': 0.9400119850950992, 'bagging_fraction': 0.9995748388706682, 'bagging_freq': 1, 'lambda_l1': 1.9543669957317666e-05, 'lambda_l2': 0.4483257506571652, 'min_child_samples': 29, 'max_depth': 7, 'max_bin': 411, 'min_data_in_leaf': 27, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.5191250180765157, 'min_gain_to_split': 0.2114074995133035}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 23:40:00,791] Trial 417 finished with value: 0.894342089632351 and parameters: {'num_leaves': 96, 'learning_rate': 0.23950616871989758, 'feature_fraction': 0.9264155305003107, 'bagging_fraction': 0.8709157011869266, 'bagging_freq': 1, 'lambda_l1': 3.1330242178026154e-06, 'lambda_l2': 6.282984812484753e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 491, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 28, 'path_smooth': 0.6315641090263819, 'min_gain_to_split': 0.4988205540426345}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 23:40:53,791] Trial 418 finished with value: 1.1255075872211062 and parameters: {'num_leaves': 98, 'learning_rate': 0.19996746140897215, 'feature_fraction': 0.9062417843591418, 'bagging_fraction': 0.8780687210338928, 'bagging_freq': 1, 'lambda_l1': 6.112529599879393e-06, 'lambda_l2': 1.066485781711203e-06, 'min_child_samples': 25, 'max_depth': 8, 'max_bin': 429, 'min_data_in_leaf': 25, 'extra_trees': True, 'early_stopping_rounds': 20, 'path_smooth': 0.29534867510540136, 'min_gain_to_split': 0.2006133999991595}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 23:42:31,730] Trial 419 finished with value: 0.9947996515024572 and parameters: {'num_leaves': 95, 'learning_rate': 0.2815107154178562, 'feature_fraction': 0.9346895300543694, 'bagging_fraction': 0.8678013689229028, 'bagging_freq': 2, 'lambda_l1': 1.3699327355238266e-06, 'lambda_l2': 3.917806042102415e-06, 'min_child_samples': 27, 'max_depth': 7, 'max_bin': 443, 'min_data_in_leaf': 31, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.5388418798043393, 'min_gain_to_split': 0.17846243962148}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 23:43:59,521] Trial 420 finished with value: 0.611655202484396 and parameters: {'num_leaves': 90, 'learning_rate': 0.26348117980875735, 'feature_fraction': 0.9516479833049376, 'bagging_fraction': 0.8747677608224479, 'bagging_freq': 1, 'lambda_l1': 0.04043883952916193, 'lambda_l2': 5.3987423333278905e-06, 'min_child_samples': 23, 'max_depth': 7, 'max_bin': 350, 'min_data_in_leaf': 27, 'extra_trees': False, 'early_stopping_rounds': 28, 'path_smooth': 0.579553707043735, 'min_gain_to_split': 0.2456626025108229}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 23:45:06,172] Trial 421 finished with value: 0.8857324977927217 and parameters: {'num_leaves': 90, 'learning_rate': 0.2664626556903365, 'feature_fraction': 0.9514809059780515, 'bagging_fraction': 0.8821005176862985, 'bagging_freq': 1, 'lambda_l1': 0.0287768405159597, 'lambda_l2': 2.695433484482534e-06, 'min_child_samples': 23, 'max_depth': 7, 'max_bin': 347, 'min_data_in_leaf': 30, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.4923757691449542, 'min_gain_to_split': 0.27954223100707315}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 23:46:14,233] Trial 422 finished with value: 0.6478150376994014 and parameters: {'num_leaves': 89, 'learning_rate': 0.28367019877214456, 'feature_fraction': 0.9521452803968965, 'bagging_fraction': 0.7036367497702579, 'bagging_freq': 1, 'lambda_l1': 0.04123344551188426, 'lambda_l2': 8.092214564856772e-06, 'min_child_samples': 22, 'max_depth': 6, 'max_bin': 492, 'min_data_in_leaf': 27, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5592540037851292, 'min_gain_to_split': 0.4817435301979756}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 23:47:24,302] Trial 423 finished with value: 1.2738739041697023 and parameters: {'num_leaves': 91, 'learning_rate': 0.26501716444045986, 'feature_fraction': 0.9722320323792472, 'bagging_fraction': 0.7000061146221657, 'bagging_freq': 2, 'lambda_l1': 7.149307224185989e-05, 'lambda_l2': 0.0009106871004669093, 'min_child_samples': 23, 'max_depth': 6, 'max_bin': 352, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.5520804671702458, 'min_gain_to_split': 0.2524176108502666}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 23:48:32,534] Trial 424 finished with value: 1.049380689422374 and parameters: {'num_leaves': 89, 'learning_rate': 0.2849567931782201, 'feature_fraction': 0.9629619402329647, 'bagging_fraction': 0.8866571005394789, 'bagging_freq': 1, 'lambda_l1': 0.04142299079428317, 'lambda_l2': 6.257932742588821e-06, 'min_child_samples': 22, 'max_depth': 6, 'max_bin': 378, 'min_data_in_leaf': 30, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5324308955221614, 'min_gain_to_split': 0.2544417393670539}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 23:49:45,087] Trial 425 finished with value: 1.3165136487605014 and parameters: {'num_leaves': 92, 'learning_rate': 0.251487455300329, 'feature_fraction': 0.9630074491016282, 'bagging_fraction': 0.7041991359389524, 'bagging_freq': 1, 'lambda_l1': 3.5571793116093134e-05, 'lambda_l2': 1.453429950490741e-06, 'min_child_samples': 21, 'max_depth': 8, 'max_bin': 487, 'min_data_in_leaf': 78, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.32401581620910197, 'min_gain_to_split': 0.4857587930660272}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 23:50:36,586] Trial 426 finished with value: 1.1504321824727621 and parameters: {'num_leaves': 22, 'learning_rate': 0.25803193129125984, 'feature_fraction': 0.95588824006784, 'bagging_fraction': 0.7060300976559473, 'bagging_freq': 7, 'lambda_l1': 2.9403514790731415e-05, 'lambda_l2': 3.6524276834225467e-06, 'min_child_samples': 21, 'max_depth': 6, 'max_bin': 391, 'min_data_in_leaf': 27, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5153358763161806, 'min_gain_to_split': 0.479867498515152}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 23:51:39,127] Trial 427 finished with value: 1.2586409973014008 and parameters: {'num_leaves': 93, 'learning_rate': 0.29875868766674113, 'feature_fraction': 0.9504261867143922, 'bagging_fraction': 0.8824174613063569, 'bagging_freq': 1, 'lambda_l1': 0.047245915553738936, 'lambda_l2': 0.0028380841628272814, 'min_child_samples': 22, 'max_depth': 6, 'max_bin': 500, 'min_data_in_leaf': 87, 'extra_trees': False, 'early_stopping_rounds': 28, 'path_smooth': 0.5669658752084534, 'min_gain_to_split': 0.2935434685797747}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 23:52:39,020] Trial 428 finished with value: 1.1291873332412703 and parameters: {'num_leaves': 56, 'learning_rate': 0.27190599693383627, 'feature_fraction': 0.9759843883086599, 'bagging_fraction': 0.7013764584227421, 'bagging_freq': 1, 'lambda_l1': 0.07433172777650383, 'lambda_l2': 1.1329663240810464e-05, 'min_child_samples': 22, 'max_depth': 5, 'max_bin': 493, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.7320097544590555, 'min_gain_to_split': 0.49213690513222363}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 23:53:33,971] Trial 429 finished with value: 1.2751237545218816 and parameters: {'num_leaves': 88, 'learning_rate': 0.299641885511556, 'feature_fraction': 0.9574227058984532, 'bagging_fraction': 0.890173482290285, 'bagging_freq': 2, 'lambda_l1': 0.03607166502209876, 'lambda_l2': 2.0881407262589177e-06, 'min_child_samples': 23, 'max_depth': 6, 'max_bin': 400, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 29, 'path_smooth': 0.6487555847420792, 'min_gain_to_split': 0.4789217642083855}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 23:54:30,519] Trial 430 finished with value: 1.3864501393818893 and parameters: {'num_leaves': 91, 'learning_rate': 0.2518097618978237, 'feature_fraction': 0.9469823535514551, 'bagging_fraction': 0.8788841970552377, 'bagging_freq': 1, 'lambda_l1': 0.054115169815198434, 'lambda_l2': 7.3524708535164186e-06, 'min_child_samples': 22, 'max_depth': 6, 'max_bin': 358, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.5821007107099471, 'min_gain_to_split': 0.3951990193204443}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 23:55:33,068] Trial 431 finished with value: 1.009968288873653 and parameters: {'num_leaves': 94, 'learning_rate': 0.27447893511831917, 'feature_fraction': 0.9648481577276513, 'bagging_fraction': 0.7091482137524225, 'bagging_freq': 1, 'lambda_l1': 0.09218122054837352, 'lambda_l2': 0.0004991588973010143, 'min_child_samples': 20, 'max_depth': 5, 'max_bin': 484, 'min_data_in_leaf': 31, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6112369995970017, 'min_gain_to_split': 0.16655578511351898}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 23:57:02,710] Trial 432 finished with value: 1.7797520392062922 and parameters: {'num_leaves': 90, 'learning_rate': 0.23771832730318784, 'feature_fraction': 0.9882819109854475, 'bagging_fraction': 0.8513477037026865, 'bagging_freq': 1, 'lambda_l1': 0.03282549577808893, 'lambda_l2': 4.747024329138101e-06, 'min_child_samples': 24, 'max_depth': 7, 'max_bin': 336, 'min_data_in_leaf': 27, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.5554794428651705, 'min_gain_to_split': 0.12704996113727068}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 23:58:08,613] Trial 433 finished with value: 0.9206995611868809 and parameters: {'num_leaves': 51, 'learning_rate': 0.26909282201485635, 'feature_fraction': 0.9426373699836108, 'bagging_fraction': 0.8743321427623438, 'bagging_freq': 1, 'lambda_l1': 0.00012676344186911495, 'lambda_l2': 3.13892090634909e-06, 'min_child_samples': 24, 'max_depth': 7, 'max_bin': 322, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.6284038374933204, 'min_gain_to_split': 0.2674019052710764}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-11 23:59:28,830] Trial 434 finished with value: 0.8161114049122992 and parameters: {'num_leaves': 92, 'learning_rate': 0.2470386627366923, 'feature_fraction': 0.9483522807860972, 'bagging_fraction': 0.8646963716095453, 'bagging_freq': 1, 'lambda_l1': 0.055269814596715455, 'lambda_l2': 1.9791863763930245e-05, 'min_child_samples': 24, 'max_depth': 7, 'max_bin': 491, 'min_data_in_leaf': 95, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5421014614916009, 'min_gain_to_split': 0.4844706443645177}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 00:00:41,311] Trial 435 finished with value: 0.9174784126936991 and parameters: {'num_leaves': 87, 'learning_rate': 0.28313009647457216, 'feature_fraction': 0.9370144781229518, 'bagging_fraction': 0.7254464866906787, 'bagging_freq': 3, 'lambda_l1': 0.012477389108533812, 'lambda_l2': 7.239511165911353e-06, 'min_child_samples': 22, 'max_depth': 7, 'max_bin': 500, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.6009473832946168, 'min_gain_to_split': 0.49854686766203127}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 00:01:52,453] Trial 436 finished with value: 0.9808658622832299 and parameters: {'num_leaves': 94, 'learning_rate': 0.22331051351094808, 'feature_fraction': 0.9540790463288897, 'bagging_fraction': 0.7108483620670424, 'bagging_freq': 2, 'lambda_l1': 3.6869893688144934e-07, 'lambda_l2': 1.8459855721703239e-06, 'min_child_samples': 25, 'max_depth': 7, 'max_bin': 475, 'min_data_in_leaf': 27, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.5738221410041263, 'min_gain_to_split': 0.4706894969488327}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 00:03:36,335] Trial 437 finished with value: 0.6630114383098469 and parameters: {'num_leaves': 90, 'learning_rate': 0.2561731779739637, 'feature_fraction': 0.9448132902261469, 'bagging_fraction': 0.7158652422897344, 'bagging_freq': 1, 'lambda_l1': 0.1135050066521192, 'lambda_l2': 8.256806332166904e-07, 'min_child_samples': 23, 'max_depth': 9, 'max_bin': 483, 'min_data_in_leaf': 30, 'extra_trees': False, 'early_stopping_rounds': 28, 'path_smooth': 0.48175007815526383, 'min_gain_to_split': 0.19601378371285738}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 00:04:17,447] Trial 438 finished with value: 1.3377973533227552 and parameters: {'num_leaves': 89, 'learning_rate': 0.23877910077652406, 'feature_fraction': 0.9589767133941199, 'bagging_fraction': 0.7194351991125704, 'bagging_freq': 1, 'lambda_l1': 0.1186397313925091, 'lambda_l2': 1.4024007636574172e-06, 'min_child_samples': 21, 'max_depth': 9, 'max_bin': 480, 'min_data_in_leaf': 34, 'extra_trees': True, 'early_stopping_rounds': 30, 'path_smooth': 0.48379801646555387, 'min_gain_to_split': 0.20416375320572785}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 00:06:28,366] Trial 439 finished with value: 0.8536900832797916 and parameters: {'num_leaves': 90, 'learning_rate': 0.14177728297718378, 'feature_fraction': 0.9434484665064157, 'bagging_fraction': 0.7006008759336322, 'bagging_freq': 1, 'lambda_l1': 0.1262101581053019, 'lambda_l2': 1.0393206308672068e-06, 'min_child_samples': 22, 'max_depth': 9, 'max_bin': 476, 'min_data_in_leaf': 30, 'extra_trees': False, 'early_stopping_rounds': 29, 'path_smooth': 0.47224024607592946, 'min_gain_to_split': 0.17731184545521242}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 00:08:10,294] Trial 440 finished with value: 0.7466400950586796 and parameters: {'num_leaves': 87, 'learning_rate': 0.2552137305869742, 'feature_fraction': 0.9507530941840462, 'bagging_fraction': 0.7156447506955999, 'bagging_freq': 1, 'lambda_l1': 0.2498369629110939, 'lambda_l2': 8.915242388979946e-07, 'min_child_samples': 20, 'max_depth': 9, 'max_bin': 419, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 28, 'path_smooth': 0.49483579963210456, 'min_gain_to_split': 0.14219700012130845}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 00:09:43,807] Trial 441 finished with value: 1.6496694340634093 and parameters: {'num_leaves': 35, 'learning_rate': 0.030103978140462753, 'feature_fraction': 0.9410543300220775, 'bagging_fraction': 0.7256706795094303, 'bagging_freq': 2, 'lambda_l1': 0.08669372543625925, 'lambda_l2': 9.498874421040601e-07, 'min_child_samples': 24, 'max_depth': 8, 'max_bin': 474, 'min_data_in_leaf': 30, 'extra_trees': False, 'early_stopping_rounds': 28, 'path_smooth': 0.4428985020540095, 'min_gain_to_split': 0.19907070306007033}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 00:11:18,072] Trial 442 finished with value: 1.1833890792400095 and parameters: {'num_leaves': 91, 'learning_rate': 0.22003838445412677, 'feature_fraction': 0.9702189179781294, 'bagging_fraction': 0.708673817305683, 'bagging_freq': 1, 'lambda_l1': 0.170187369434163, 'lambda_l2': 2.0917832093526228e-06, 'min_child_samples': 23, 'max_depth': 9, 'max_bin': 326, 'min_data_in_leaf': 82, 'extra_trees': False, 'early_stopping_rounds': 30, 'path_smooth': 0.5104998686327116, 'min_gain_to_split': 0.19615391072652952}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 00:12:46,136] Trial 443 finished with value: 0.8977935615957643 and parameters: {'num_leaves': 92, 'learning_rate': 0.24568474113532546, 'feature_fraction': 0.9512548692293604, 'bagging_fraction': 0.7300867838690808, 'bagging_freq': 1, 'lambda_l1': 0.32145438463706116, 'lambda_l2': 6.88008749416064e-07, 'min_child_samples': 23, 'max_depth': 8, 'max_bin': 484, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 28, 'path_smooth': 0.5226364964970062, 'min_gain_to_split': 0.47686077112283287}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 00:13:49,958] Trial 444 finished with value: 1.1789971507878891 and parameters: {'num_leaves': 88, 'learning_rate': 0.2999279272798995, 'feature_fraction': 0.9381389523367143, 'bagging_fraction': 0.7161662032082952, 'bagging_freq': 1, 'lambda_l1': 0.025230370973877543, 'lambda_l2': 3.9071352761104504e-06, 'min_child_samples': 21, 'max_depth': 6, 'max_bin': 342, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.46458005070736824, 'min_gain_to_split': 0.15534513058514382}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 00:15:31,627] Trial 445 finished with value: 0.8248463690250327 and parameters: {'num_leaves': 93, 'learning_rate': 0.2628541688632389, 'feature_fraction': 0.9608141734103284, 'bagging_fraction': 0.7066742629792122, 'bagging_freq': 1, 'lambda_l1': 0.07379489747842223, 'lambda_l2': 6.114243949868309e-07, 'min_child_samples': 30, 'max_depth': 9, 'max_bin': 429, 'min_data_in_leaf': 31, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.42191124872123775, 'min_gain_to_split': 0.18042230900903014}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 00:16:52,178] Trial 446 finished with value: 0.8117089183842701 and parameters: {'num_leaves': 90, 'learning_rate': 0.28240649304725546, 'feature_fraction': 0.9305506576561737, 'bagging_fraction': 0.7230022198963324, 'bagging_freq': 2, 'lambda_l1': 0.10242998660818974, 'lambda_l2': 1.1946085567498906e-05, 'min_child_samples': 23, 'max_depth': 8, 'max_bin': 361, 'min_data_in_leaf': 35, 'extra_trees': False, 'early_stopping_rounds': 29, 'path_smooth': 0.5535686317478483, 'min_gain_to_split': 0.19301924434431297}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 00:18:14,739] Trial 447 finished with value: 0.9731720139626964 and parameters: {'num_leaves': 41, 'learning_rate': 0.2406764016879677, 'feature_fraction': 0.9408025692146968, 'bagging_fraction': 0.7131612084985592, 'bagging_freq': 1, 'lambda_l1': 0.16043529366962123, 'lambda_l2': 1.359711717595428e-06, 'min_child_samples': 22, 'max_depth': 5, 'max_bin': 494, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.5074937214292397, 'min_gain_to_split': 0.10741249552023274}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 00:19:53,356] Trial 448 finished with value: 1.2550718004062664 and parameters: {'num_leaves': 92, 'learning_rate': 0.11386817868794126, 'feature_fraction': 0.9485671521893781, 'bagging_fraction': 0.7333408206863188, 'bagging_freq': 1, 'lambda_l1': 0.01866279009646589, 'lambda_l2': 2.5752290085956773e-06, 'min_child_samples': 23, 'max_depth': 7, 'max_bin': 467, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.5351014765933223, 'min_gain_to_split': 0.21350711461211558}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 00:20:55,265] Trial 449 finished with value: 1.5800516588124585 and parameters: {'num_leaves': 94, 'learning_rate': 0.2618648534659199, 'feature_fraction': 0.931523624880729, 'bagging_fraction': 0.7214399043142462, 'bagging_freq': 2, 'lambda_l1': 0.04201063478315661, 'lambda_l2': 0.0002989524078274059, 'min_child_samples': 23, 'max_depth': 7, 'max_bin': 485, 'min_data_in_leaf': 85, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.5798889374527624, 'min_gain_to_split': 0.4869091287435418}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 00:22:10,821] Trial 450 finished with value: 1.3398657490434045 and parameters: {'num_leaves': 89, 'learning_rate': 0.22811569374455776, 'feature_fraction': 0.965264030226675, 'bagging_fraction': 0.7058200447419792, 'bagging_freq': 1, 'lambda_l1': 0.008623565003547575, 'lambda_l2': 0.0016291756531179342, 'min_child_samples': 19, 'max_depth': 10, 'max_bin': 415, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 22, 'path_smooth': 0.6098779626340863, 'min_gain_to_split': 0.47281030025685794}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 00:23:14,724] Trial 451 finished with value: 1.0060642594714588 and parameters: {'num_leaves': 92, 'learning_rate': 0.28283821358370737, 'feature_fraction': 0.954296389747235, 'bagging_fraction': 0.7159112726655916, 'bagging_freq': 1, 'lambda_l1': 6.10213480427112e-07, 'lambda_l2': 0.0006795455977642171, 'min_child_samples': 10, 'max_depth': 7, 'max_bin': 277, 'min_data_in_leaf': 31, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.6550445194596957, 'min_gain_to_split': 0.46872810332351433}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 00:24:19,398] Trial 452 finished with value: 1.6238498901340144 and parameters: {'num_leaves': 95, 'learning_rate': 0.2566078648445512, 'feature_fraction': 0.9121081037008036, 'bagging_fraction': 0.7001049495007048, 'bagging_freq': 3, 'lambda_l1': 8.075539134643382e-05, 'lambda_l2': 3.967145935694308e-06, 'min_child_samples': 30, 'max_depth': 10, 'max_bin': 433, 'min_data_in_leaf': 64, 'extra_trees': False, 'early_stopping_rounds': 28, 'path_smooth': 0.7563770850026825, 'min_gain_to_split': 0.490123501170668}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 00:25:22,027] Trial 453 finished with value: 1.1155189812321367 and parameters: {'num_leaves': 85, 'learning_rate': 0.2746542875311966, 'feature_fraction': 0.9441247091558839, 'bagging_fraction': 0.7105807492703533, 'bagging_freq': 1, 'lambda_l1': 0.412724289747417, 'lambda_l2': 2.5783132305249477e-06, 'min_child_samples': 29, 'max_depth': 7, 'max_bin': 473, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.5590228636622283, 'min_gain_to_split': 0.499535346951492}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 00:27:05,400] Trial 454 finished with value: 0.9518955849827415 and parameters: {'num_leaves': 76, 'learning_rate': 0.21621982636363107, 'feature_fraction': 0.9330357339060132, 'bagging_fraction': 0.8786135458536529, 'bagging_freq': 2, 'lambda_l1': 0.07024727144943328, 'lambda_l2': 3.06100111324314e-05, 'min_child_samples': 24, 'max_depth': 7, 'max_bin': 483, 'min_data_in_leaf': 26, 'extra_trees': False, 'early_stopping_rounds': 30, 'path_smooth': 0.45468412999286667, 'min_gain_to_split': 0.16254381571420515}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 00:28:25,216] Trial 455 finished with value: 0.8280147681614739 and parameters: {'num_leaves': 90, 'learning_rate': 0.23985622638299756, 'feature_fraction': 0.895974165223006, 'bagging_fraction': 0.7281406051918132, 'bagging_freq': 1, 'lambda_l1': 1.4788962373737985e-06, 'lambda_l2': 4.3566422810132283e-07, 'min_child_samples': 21, 'max_depth': 7, 'max_bin': 494, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.5879115020122703, 'min_gain_to_split': 0.1873466649006506}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 00:29:21,056] Trial 456 finished with value: 0.973878269108974 and parameters: {'num_leaves': 93, 'learning_rate': 0.28539213105963773, 'feature_fraction': 0.9257530068691376, 'bagging_fraction': 0.7210195094726133, 'bagging_freq': 1, 'lambda_l1': 0.23523438094007632, 'lambda_l2': 5.375550508663074e-06, 'min_child_samples': 44, 'max_depth': 6, 'max_bin': 405, 'min_data_in_leaf': 27, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.4851746014079835, 'min_gain_to_split': 0.48256787191434364}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 00:30:33,651] Trial 457 finished with value: 1.113829294017125 and parameters: {'num_leaves': 88, 'learning_rate': 0.25581818035093146, 'feature_fraction': 0.9818469121076581, 'bagging_fraction': 0.8921323599312325, 'bagging_freq': 1, 'lambda_l1': 0.12600806644056567, 'lambda_l2': 8.368602609431808e-06, 'min_child_samples': 25, 'max_depth': 7, 'max_bin': 465, 'min_data_in_leaf': 30, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6928754295619797, 'min_gain_to_split': 0.4636805913203842}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 00:31:15,924] Trial 458 finished with value: 1.2196651542508703 and parameters: {'num_leaves': 79, 'learning_rate': 0.2993189081152149, 'feature_fraction': 0.9414989066714581, 'bagging_fraction': 0.7084116115209225, 'bagging_freq': 1, 'lambda_l1': 0.030460846822733163, 'lambda_l2': 1.6557643062065912e-05, 'min_child_samples': 27, 'max_depth': 8, 'max_bin': 437, 'min_data_in_leaf': 28, 'extra_trees': True, 'early_stopping_rounds': 21, 'path_smooth': 0.5253649408739897, 'min_gain_to_split': 0.47645976859197275}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 00:32:17,133] Trial 459 finished with value: 1.3573033222391389 and parameters: {'num_leaves': 95, 'learning_rate': 0.23217368717458764, 'feature_fraction': 0.904402374061023, 'bagging_fraction': 0.7157226022558857, 'bagging_freq': 1, 'lambda_l1': 0.05009999598904924, 'lambda_l2': 1.5733574115381798e-06, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 493, 'min_data_in_leaf': 31, 'extra_trees': False, 'early_stopping_rounds': 24, 'path_smooth': 0.6212565769431936, 'min_gain_to_split': 0.4056310640590324}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 00:33:51,738] Trial 460 finished with value: 1.124868347754234 and parameters: {'num_leaves': 91, 'learning_rate': 0.26278055226956637, 'feature_fraction': 0.9148304164338977, 'bagging_fraction': 0.7333753342300655, 'bagging_freq': 2, 'lambda_l1': 0.0003874680785303479, 'lambda_l2': 3.6808692620950827e-06, 'min_child_samples': 22, 'max_depth': 10, 'max_bin': 471, 'min_data_in_leaf': 30, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.5434337031784454, 'min_gain_to_split': 0.20778436891227037}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 00:35:01,290] Trial 461 finished with value: 1.0863556298280448 and parameters: {'num_leaves': 96, 'learning_rate': 0.2063635526793982, 'feature_fraction': 0.9588721568366276, 'bagging_fraction': 0.7255167715813263, 'bagging_freq': 1, 'lambda_l1': 0.11125407605566527, 'lambda_l2': 1.0509448630390537e-05, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 500, 'min_data_in_leaf': 35, 'extra_trees': False, 'early_stopping_rounds': 29, 'path_smooth': 0.57026658808046, 'min_gain_to_split': 0.46185315073774896}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 00:36:16,489] Trial 462 finished with value: 1.1717960895101398 and parameters: {'num_leaves': 93, 'learning_rate': 0.27121533240738666, 'feature_fraction': 0.9358354378053202, 'bagging_fraction': 0.8573854630850484, 'bagging_freq': 1, 'lambda_l1': 0.017836441739112387, 'lambda_l2': 7.019192200861732e-07, 'min_child_samples': 29, 'max_depth': 7, 'max_bin': 426, 'min_data_in_leaf': 69, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6425887764103709, 'min_gain_to_split': 0.17114138596115555}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 00:37:23,126] Trial 463 finished with value: 1.2175865481750023 and parameters: {'num_leaves': 87, 'learning_rate': 0.24681910721393246, 'feature_fraction': 0.946838489480496, 'bagging_fraction': 0.7128264419729637, 'bagging_freq': 2, 'lambda_l1': 0.19696532120569205, 'lambda_l2': 5.741212692546383e-06, 'min_child_samples': 30, 'max_depth': 7, 'max_bin': 447, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.60117518926239, 'min_gain_to_split': 0.48217417502774373}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 00:38:30,601] Trial 464 finished with value: 1.3186447323212938 and parameters: {'num_leaves': 94, 'learning_rate': 0.1680405266434774, 'feature_fraction': 0.9275675711822291, 'bagging_fraction': 0.8672018018194317, 'bagging_freq': 1, 'lambda_l1': 0.3052740384464628, 'lambda_l2': 2.395809602912577e-06, 'min_child_samples': 23, 'max_depth': 6, 'max_bin': 481, 'min_data_in_leaf': 33, 'extra_trees': False, 'early_stopping_rounds': 23, 'path_smooth': 0.5595315533553094, 'min_gain_to_split': 0.46728332959082713}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 00:39:39,531] Trial 465 finished with value: 0.6089060437238969 and parameters: {'num_leaves': 91, 'learning_rate': 0.2785711166823212, 'feature_fraction': 0.9547989292928744, 'bagging_fraction': 0.8734203222063965, 'bagging_freq': 1, 'lambda_l1': 0.06342238888290878, 'lambda_l2': 0.0011784536132059202, 'min_child_samples': 13, 'max_depth': 7, 'max_bin': 458, 'min_data_in_leaf': 26, 'extra_trees': False, 'early_stopping_rounds': 29, 'path_smooth': 0.5048408656216725, 'min_gain_to_split': 0.45536489323809115}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 00:41:13,575] Trial 466 finished with value: 1.6417399758811395 and parameters: {'num_leaves': 89, 'learning_rate': 0.10119050682419409, 'feature_fraction': 0.9689741018137645, 'bagging_fraction': 0.8727237500970351, 'bagging_freq': 1, 'lambda_l1': 0.07902450491197532, 'lambda_l2': 0.005078097725916327, 'min_child_samples': 43, 'max_depth': 7, 'max_bin': 464, 'min_data_in_leaf': 26, 'extra_trees': False, 'early_stopping_rounds': 29, 'path_smooth': 0.5024302635992549, 'min_gain_to_split': 0.45144644073471674}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 00:42:24,433] Trial 467 finished with value: 0.6853034770619569 and parameters: {'num_leaves': 91, 'learning_rate': 0.23124173111749965, 'feature_fraction': 0.9554516624767841, 'bagging_fraction': 0.8754507865687935, 'bagging_freq': 1, 'lambda_l1': 0.003587163954261587, 'lambda_l2': 0.0022925951360235567, 'min_child_samples': 16, 'max_depth': 7, 'max_bin': 458, 'min_data_in_leaf': 26, 'extra_trees': False, 'early_stopping_rounds': 29, 'path_smooth': 0.4726657230640616, 'min_gain_to_split': 0.4403042653385603}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 00:43:41,977] Trial 468 finished with value: 1.1157787195384645 and parameters: {'num_leaves': 90, 'learning_rate': 0.2160447625541765, 'feature_fraction': 0.957500388863816, 'bagging_fraction': 0.8798811332921969, 'bagging_freq': 2, 'lambda_l1': 0.006093814206350636, 'lambda_l2': 0.010260806562800814, 'min_child_samples': 13, 'max_depth': 7, 'max_bin': 453, 'min_data_in_leaf': 24, 'extra_trees': False, 'early_stopping_rounds': 30, 'path_smooth': 0.4824049703467729, 'min_gain_to_split': 0.4284880757340421}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 00:44:50,448] Trial 469 finished with value: 1.4166588689593724 and parameters: {'num_leaves': 87, 'learning_rate': 0.20130564167571227, 'feature_fraction': 0.9645246170877315, 'bagging_fraction': 0.8752973817918109, 'bagging_freq': 1, 'lambda_l1': 0.12089281816796144, 'lambda_l2': 0.0022882702490413863, 'min_child_samples': 14, 'max_depth': 7, 'max_bin': 462, 'min_data_in_leaf': 72, 'extra_trees': False, 'early_stopping_rounds': 31, 'path_smooth': 0.49327198014437196, 'min_gain_to_split': 0.43930106021621323}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 00:46:03,928] Trial 470 finished with value: 1.2316946391103802 and parameters: {'num_leaves': 91, 'learning_rate': 0.2270211982823782, 'feature_fraction': 0.9755549404224567, 'bagging_fraction': 0.8848231885626638, 'bagging_freq': 1, 'lambda_l1': 0.0709188153482225, 'lambda_l2': 0.003175113284970949, 'min_child_samples': 27, 'max_depth': 7, 'max_bin': 458, 'min_data_in_leaf': 26, 'extra_trees': False, 'early_stopping_rounds': 31, 'path_smooth': 0.45489205903626095, 'min_gain_to_split': 0.44869338613171716}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 00:47:21,939] Trial 471 finished with value: 0.7857909079300043 and parameters: {'num_leaves': 30, 'learning_rate': 0.23816128980290827, 'feature_fraction': 0.9555101227195913, 'bagging_fraction': 0.8606592467680944, 'bagging_freq': 1, 'lambda_l1': 0.005022962849655592, 'lambda_l2': 0.0027738523355041664, 'min_child_samples': 14, 'max_depth': 7, 'max_bin': 470, 'min_data_in_leaf': 26, 'extra_trees': False, 'early_stopping_rounds': 29, 'path_smooth': 0.43954147562077617, 'min_gain_to_split': 0.4154040835925141}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 00:48:35,505] Trial 472 finished with value: 1.136520053452581 and parameters: {'num_leaves': 89, 'learning_rate': 0.1896387027300666, 'feature_fraction': 0.9492613172193793, 'bagging_fraction': 0.8692256265042727, 'bagging_freq': 1, 'lambda_l1': 0.18424240646292112, 'lambda_l2': 0.0013873195246701428, 'min_child_samples': 12, 'max_depth': 7, 'max_bin': 456, 'min_data_in_leaf': 20, 'extra_trees': False, 'early_stopping_rounds': 29, 'path_smooth': 0.46755497539262963, 'min_gain_to_split': 0.4574183297789503}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 00:49:56,354] Trial 473 finished with value: 1.4976118301681234 and parameters: {'num_leaves': 85, 'learning_rate': 0.21907196438501464, 'feature_fraction': 0.9637768916150198, 'bagging_fraction': 0.8785616670206946, 'bagging_freq': 2, 'lambda_l1': 0.0013386599675475504, 'lambda_l2': 0.0017093673340294524, 'min_child_samples': 46, 'max_depth': 9, 'max_bin': 463, 'min_data_in_leaf': 23, 'extra_trees': False, 'early_stopping_rounds': 28, 'path_smooth': 0.5109907409603764, 'min_gain_to_split': 0.4369321102939425}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 00:51:26,165] Trial 474 finished with value: 1.4400338448586127 and parameters: {'num_leaves': 91, 'learning_rate': 0.04910715739092179, 'feature_fraction': 0.9522737320012254, 'bagging_fraction': 0.8851188211987633, 'bagging_freq': 1, 'lambda_l1': 0.0006038289042443081, 'lambda_l2': 0.00574784622983237, 'min_child_samples': 16, 'max_depth': 7, 'max_bin': 450, 'min_data_in_leaf': 26, 'extra_trees': False, 'early_stopping_rounds': 28, 'path_smooth': 0.47224720640111867, 'min_gain_to_split': 0.45587275323766935}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 00:52:39,271] Trial 475 finished with value: 0.7888028250719301 and parameters: {'num_leaves': 88, 'learning_rate': 0.2502457011026525, 'feature_fraction': 0.9469429425925756, 'bagging_fraction': 0.8754949517588653, 'bagging_freq': 1, 'lambda_l1': 0.5193727022111037, 'lambda_l2': 0.0038963422783216254, 'min_child_samples': 17, 'max_depth': 8, 'max_bin': 475, 'min_data_in_leaf': 25, 'extra_trees': False, 'early_stopping_rounds': 29, 'path_smooth': 0.4964656556564541, 'min_gain_to_split': 0.47095575535231393}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 00:53:26,038] Trial 476 finished with value: 1.1796339116989016 and parameters: {'num_leaves': 90, 'learning_rate': 0.23383612736798065, 'feature_fraction': 0.9564184686724055, 'bagging_fraction': 0.8708544426789607, 'bagging_freq': 1, 'lambda_l1': 0.029035730771944362, 'lambda_l2': 3.3448554556945296e-06, 'min_child_samples': 13, 'max_depth': 7, 'max_bin': 446, 'min_data_in_leaf': 22, 'extra_trees': True, 'early_stopping_rounds': 30, 'path_smooth': 0.7039058891622172, 'min_gain_to_split': 0.4216704002691566}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 00:54:20,757] Trial 477 finished with value: 1.460640098107771 and parameters: {'num_leaves': 92, 'learning_rate': 0.25013165451155844, 'feature_fraction': 0.9706556222489794, 'bagging_fraction': 0.8915232944811627, 'bagging_freq': 1, 'lambda_l1': 0.0008334216436134426, 'lambda_l2': 0.0011981844649557368, 'min_child_samples': 15, 'max_depth': 4, 'max_bin': 466, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 30, 'path_smooth': 0.525870424362605, 'min_gain_to_split': 0.44393362525578123}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 00:55:32,364] Trial 478 finished with value: 1.1455532631366618 and parameters: {'num_leaves': 86, 'learning_rate': 0.22633577445281575, 'feature_fraction': 0.9423547372732017, 'bagging_fraction': 0.8657674107844269, 'bagging_freq': 4, 'lambda_l1': 0.0023073585515288337, 'lambda_l2': 0.0019612531106471646, 'min_child_samples': 11, 'max_depth': 7, 'max_bin': 455, 'min_data_in_leaf': 24, 'extra_trees': False, 'early_stopping_rounds': 28, 'path_smooth': 0.6717398823957188, 'min_gain_to_split': 0.4776591819141283}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 00:56:36,075] Trial 479 finished with value: 1.1642587589238897 and parameters: {'num_leaves': 91, 'learning_rate': 0.2577932820516131, 'feature_fraction': 0.9551074720096443, 'bagging_fraction': 0.8841862674393258, 'bagging_freq': 2, 'lambda_l1': 0.003121039826568462, 'lambda_l2': 0.001013502451579986, 'min_child_samples': 16, 'max_depth': 6, 'max_bin': 482, 'min_data_in_leaf': 27, 'extra_trees': False, 'early_stopping_rounds': 28, 'path_smooth': 0.4913354511542597, 'min_gain_to_split': 0.4609369750966653}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 00:57:53,576] Trial 480 finished with value: 1.1448700668390708 and parameters: {'num_leaves': 89, 'learning_rate': 0.2669381612204217, 'feature_fraction': 0.9377354714289334, 'bagging_fraction': 0.8796491363560778, 'bagging_freq': 1, 'lambda_l1': 0.285985186302698, 'lambda_l2': 1.1998108855979673e-06, 'min_child_samples': 10, 'max_depth': 7, 'max_bin': 441, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.5036922157359486, 'min_gain_to_split': 0.2220097363861121}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 00:59:04,785] Trial 481 finished with value: 1.4739987298724997 and parameters: {'num_leaves': 100, 'learning_rate': 0.20516999003856715, 'feature_fraction': 0.9634332611483002, 'bagging_fraction': 0.8737391335876079, 'bagging_freq': 3, 'lambda_l1': 0.13580406967877864, 'lambda_l2': 0.0008613027708654502, 'min_child_samples': 25, 'max_depth': 7, 'max_bin': 474, 'min_data_in_leaf': 75, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.529094391225533, 'min_gain_to_split': 0.4523481096870384}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 01:00:18,875] Trial 482 finished with value: 1.1599878755137139 and parameters: {'num_leaves': 93, 'learning_rate': 0.2366474745442475, 'feature_fraction': 0.9477679863970793, 'bagging_fraction': 0.8454607834342646, 'bagging_freq': 1, 'lambda_l1': 0.06437069441094206, 'lambda_l2': 1.8040981456319649e-06, 'min_child_samples': 11, 'max_depth': 7, 'max_bin': 488, 'min_data_in_leaf': 60, 'extra_trees': False, 'early_stopping_rounds': 19, 'path_smooth': 0.43018120286578493, 'min_gain_to_split': 0.4414697022962377}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 01:01:53,226] Trial 483 finished with value: 1.6840986510605915 and parameters: {'num_leaves': 68, 'learning_rate': 0.0211319231783866, 'feature_fraction': 0.9792101706570073, 'bagging_fraction': 0.8604387468798982, 'bagging_freq': 2, 'lambda_l1': 0.10177982756312884, 'lambda_l2': 0.0023539064671898855, 'min_child_samples': 13, 'max_depth': 7, 'max_bin': 373, 'min_data_in_leaf': 27, 'extra_trees': False, 'early_stopping_rounds': 29, 'path_smooth': 0.46826759965425024, 'min_gain_to_split': 0.46676992759305197}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 01:03:09,786] Trial 484 finished with value: 0.9012053659468782 and parameters: {'num_leaves': 91, 'learning_rate': 0.27113277930569823, 'feature_fraction': 0.9410798419506802, 'bagging_fraction': 0.8656956861185743, 'bagging_freq': 1, 'lambda_l1': 0.041416913094707214, 'lambda_l2': 4.964042759260703e-06, 'min_child_samples': 12, 'max_depth': 7, 'max_bin': 460, 'min_data_in_leaf': 24, 'extra_trees': False, 'early_stopping_rounds': 31, 'path_smooth': 0.5323561251179276, 'min_gain_to_split': 0.43197265197285367}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 01:04:18,302] Trial 485 finished with value: 1.2826927254349347 and parameters: {'num_leaves': 88, 'learning_rate': 0.24491610473208641, 'feature_fraction': 0.9512050710578449, 'bagging_fraction': 0.8880084522119212, 'bagging_freq': 1, 'lambda_l1': 0.48021524057094706, 'lambda_l2': 3.127614948555268e-07, 'min_child_samples': 15, 'max_depth': 7, 'max_bin': 449, 'min_data_in_leaf': 30, 'extra_trees': False, 'early_stopping_rounds': 28, 'path_smooth': 0.5187268027013174, 'min_gain_to_split': 0.48973134060873247}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 01:05:19,734] Trial 486 finished with value: 1.3425625402250956 and parameters: {'num_leaves': 83, 'learning_rate': 0.2580676866680049, 'feature_fraction': 0.9596052177358405, 'bagging_fraction': 0.8798946499661943, 'bagging_freq': 1, 'lambda_l1': 0.19971513710416963, 'lambda_l2': 1.1175169680751476, 'min_child_samples': 17, 'max_depth': 7, 'max_bin': 492, 'min_data_in_leaf': 21, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.5735538806891017, 'min_gain_to_split': 0.4754776245117502}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 01:06:41,271] Trial 487 finished with value: 1.076622749847345 and parameters: {'num_leaves': 93, 'learning_rate': 0.2123121335485335, 'feature_fraction': 0.9344793680795344, 'bagging_fraction': 0.7056267089974508, 'bagging_freq': 5, 'lambda_l1': 0.08022920372868918, 'lambda_l2': 7.75199924669633e-06, 'min_child_samples': 31, 'max_depth': 7, 'max_bin': 467, 'min_data_in_leaf': 26, 'extra_trees': False, 'early_stopping_rounds': 32, 'path_smooth': 0.5452763399082781, 'min_gain_to_split': 0.4559382773159042}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 01:08:10,174] Trial 488 finished with value: 0.8346587190157587 and parameters: {'num_leaves': 96, 'learning_rate': 0.2843823612463773, 'feature_fraction': 0.947181694487047, 'bagging_fraction': 0.7216047040570672, 'bagging_freq': 2, 'lambda_l1': 0.040942033712252614, 'lambda_l2': 2.786693561076206e-06, 'min_child_samples': 28, 'max_depth': 8, 'max_bin': 440, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.407526377192409, 'min_gain_to_split': 0.20136806670970314}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 01:09:15,063] Trial 489 finished with value: 1.4194655159043732 and parameters: {'num_leaves': 92, 'learning_rate': 0.2989474000045108, 'feature_fraction': 0.934342329695699, 'bagging_fraction': 0.736510893997976, 'bagging_freq': 10, 'lambda_l1': 0.14615041717233312, 'lambda_l2': 4.735269874885308e-06, 'min_child_samples': 29, 'max_depth': 7, 'max_bin': 477, 'min_data_in_leaf': 28, 'extra_trees': False, 'early_stopping_rounds': 29, 'path_smooth': 0.6550799873254664, 'min_gain_to_split': 0.3145465155152021}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 01:10:30,555] Trial 490 finished with value: 1.4175795204514496 and parameters: {'num_leaves': 94, 'learning_rate': 0.060805576487208704, 'feature_fraction': 0.9435467235241921, 'bagging_fraction': 0.7047345159972835, 'bagging_freq': 1, 'lambda_l1': 0.36902888690354957, 'lambda_l2': 0.003468824339925353, 'min_child_samples': 26, 'max_depth': 6, 'max_bin': 485, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 12, 'path_smooth': 0.7236911814693383, 'min_gain_to_split': 0.48981684539672476}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 01:11:48,500] Trial 491 finished with value: 1.6370581471607035 and parameters: {'num_leaves': 97, 'learning_rate': 0.22468152381062412, 'feature_fraction': 0.9668670591747581, 'bagging_fraction': 0.8732544825096772, 'bagging_freq': 1, 'lambda_l1': 0.025075076937745355, 'lambda_l2': 1.5911508970903678e-06, 'min_child_samples': 27, 'max_depth': 7, 'max_bin': 500, 'min_data_in_leaf': 23, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.625550538882841, 'min_gain_to_split': 0.46612200342114585}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 01:12:57,308] Trial 492 finished with value: 1.2212063146621817 and parameters: {'num_leaves': 90, 'learning_rate': 0.2466619667112381, 'feature_fraction': 0.9554625601562243, 'bagging_fraction': 0.8519294860718426, 'bagging_freq': 1, 'lambda_l1': 0.05779950436885003, 'lambda_l2': 1.1383759852392528e-05, 'min_child_samples': 32, 'max_depth': 7, 'max_bin': 451, 'min_data_in_leaf': 25, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.6828116271045953, 'min_gain_to_split': 0.4474126292824141}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 01:14:11,277] Trial 493 finished with value: 1.053945393087299 and parameters: {'num_leaves': 87, 'learning_rate': 0.26913251535533966, 'feature_fraction': 0.9327686693179285, 'bagging_fraction': 0.8956310607226023, 'bagging_freq': 1, 'lambda_l1': 0.10335200833891119, 'lambda_l2': 0.007809389752686125, 'min_child_samples': 25, 'max_depth': 7, 'max_bin': 458, 'min_data_in_leaf': 27, 'extra_trees': False, 'early_stopping_rounds': 41, 'path_smooth': 0.5577754818938807, 'min_gain_to_split': 0.47939232921738956}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 01:15:15,472] Trial 494 finished with value: 1.1273067556587508 and parameters: {'num_leaves': 99, 'learning_rate': 0.2357017434028294, 'feature_fraction': 0.941333834646076, 'bagging_fraction': 0.709931133128211, 'bagging_freq': 2, 'lambda_l1': 0.009420731715950656, 'lambda_l2': 9.204529718827171e-07, 'min_child_samples': 15, 'max_depth': 7, 'max_bin': 288, 'min_data_in_leaf': 31, 'extra_trees': False, 'early_stopping_rounds': 28, 'path_smooth': 0.591704923551401, 'min_gain_to_split': 0.43074578454576423}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 01:16:05,286] Trial 495 finished with value: 1.428412448356078 and parameters: {'num_leaves': 81, 'learning_rate': 0.26680951362259486, 'feature_fraction': 0.9213304399942553, 'bagging_fraction': 0.7304274032708233, 'bagging_freq': 1, 'lambda_l1': 0.0035086900301722567, 'lambda_l2': 3.1719990349089773e-06, 'min_child_samples': 29, 'max_depth': 6, 'max_bin': 471, 'min_data_in_leaf': 30, 'extra_trees': True, 'early_stopping_rounds': 37, 'path_smooth': 0.4798749540799097, 'min_gain_to_split': 0.18377669965918822}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 01:17:11,968] Trial 496 finished with value: 1.332752741761729 and parameters: {'num_leaves': 92, 'learning_rate': 0.2517205428588172, 'feature_fraction': 0.9264728610831733, 'bagging_fraction': 0.8652388096401288, 'bagging_freq': 1, 'lambda_l1': 0.24784640012432563, 'lambda_l2': 7.165457359440936e-06, 'min_child_samples': 24, 'max_depth': 7, 'max_bin': 436, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5099239098342003, 'min_gain_to_split': 0.4610453144706312}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 01:18:21,360] Trial 497 finished with value: 0.752513769321707 and parameters: {'num_leaves': 95, 'learning_rate': 0.2827249533189995, 'feature_fraction': 0.9512344227292789, 'bagging_fraction': 0.8846242528125702, 'bagging_freq': 1, 'lambda_l1': 0.03547240533337957, 'lambda_l2': 4.079000005252234e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 478, 'min_data_in_leaf': 27, 'extra_trees': False, 'early_stopping_rounds': 29, 'path_smooth': 0.4527938204711597, 'min_gain_to_split': 0.4715142434932861}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 01:19:17,094] Trial 498 finished with value: 1.7046743400883329 and parameters: {'num_leaves': 89, 'learning_rate': 0.23093919378991035, 'feature_fraction': 0.9405772409166904, 'bagging_fraction': 0.7406243321821486, 'bagging_freq': 8, 'lambda_l1': 0.05848211890476821, 'lambda_l2': 2.0423239885275915e-06, 'min_child_samples': 32, 'max_depth': 7, 'max_bin': 444, 'min_data_in_leaf': 90, 'extra_trees': False, 'early_stopping_rounds': 27, 'path_smooth': 0.5769721944603494, 'min_gain_to_split': 0.4442101024577681}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}

[I 2025-07-12 01:20:23,497] Trial 499 finished with value: 1.3229839660368021 and parameters: {'num_leaves': 94, 'learning_rate': 0.2822009988003494, 'feature_fraction': 0.9581726523808091, 'bagging_fraction': 0.7001683139361526, 'bagging_freq': 1, 'lambda_l1': 0.16740304238940457, 'lambda_l2': 0.0011456191685838778, 'min_child_samples': 26, 'max_depth': 7, 'max_bin': 491, 'min_data_in_leaf': 32, 'extra_trees': False, 'early_stopping_rounds': 25, 'path_smooth': 0.5518284914797872, 'min_gain_to_split': 0.49986344145552913}. Best is trial 191 with value: 0.4882488232313609.

Mejor trial hasta ahora: RMSE=0.488249, Parámetros={'num_leaves': 93, 'learning_rate': 0.22634931577422102, 'feature_fraction': 0.9429427285714367, 'bagging_fraction': 0.7185873268490852, 'bagging_freq': 1, 'lambda_l1': 0.03529965164069097, 'lambda_l2': 1.7241089660595204e-06, 'min_child_samples': 28, 'max_depth': 7, 'max_bin': 433, 'min_data_in_leaf': 29, 'extra_trees': False, 'early_stopping_rounds': 26, 'path_smooth': 0.5629907432202811, 'min_gain_to_split': 0.45181315423785}
Estudio guardado en: sqlite:///optuna_studies_v21.db

Mejores hiperparámetros encontrados:
num_leaves: 93
learning_rate: 0.22634931577422102
feature_fraction: 0.9429427285714367
bagging_fraction: 0.7185873268490852
bagging_freq: 1
lambda_l1: 0.03529965164069097
lambda_l2: 1.7241089660595204e-06
min_child_samples: 28
max_depth: 7
max_bin: 433
min_data_in_leaf: 29
extra_trees: False
early_stopping_rounds: 26
path_smooth: 0.5629907432202811
min_gain_to_split: 0.45181315423785

(<optuna.study.study.Study at 0x1b021e5ecd0>,
 {'num_leaves': 93,
  'learning_rate': 0.22634931577422102,
  'feature_fraction': 0.9429427285714367,
  'bagging_fraction': 0.7185873268490852,
  'bagging_freq': 1,
  'lambda_l1': 0.03529965164069097,
  'lambda_l2': 1.7241089660595204e-06,
  'min_child_samples': 28,
  'max_depth': 7,
  'max_bin': 433,
  'min_data_in_leaf': 29,
  'extra_trees': False,
  'early_stopping_rounds': 26,
  'path_smooth': 0.5629907432202811,
  'min_gain_to_split': 0.45181315423785,
  'objective': 'regression',
  'metric': 'rmse',
  'boosting_type': 'gbdt',
  'verbosity': -1})

Prediccion

In [23]:
df_future = model_lgb.semillerio_en_prediccion_con_pesos(train, test, version="v21")

In [24]:
df_future

       periodo  product_id  target      pred
30476   201912       20001     0.0  0.983107
30477   201912       20002     0.0  1.174595
30478   201912       20003     0.0  0.429366
30479   201912       20004     0.0  0.579315
30480   201912       20005     0.0  0.679257
...        ...         ...     ...       ...
31357   201912       21265     0.0  0.802648
31358   201912       21266     0.0  0.451392
31359   201912       21267     0.0  0.029572
31360   201912       21271     0.0  0.308942
31361   201912       21276     0.0  0.744200

[886 rows x 4 columns]

Filtramos los 180 productos

In [25]:
productos_ok = pd.read_csv("https://storage.googleapis.com/open-courses/austral2025-af91/labo3v/product_id_apredecir201912.txt", sep="\t")
df_future = df_future[df_future['periodo'] == 201912]
df_future = df_future[df_future['product_id'].isin(productos_ok['product_id'].unique())]

In [26]:
df_future

       periodo  product_id  target      pred
30476   201912       20001     0.0  0.983107
30477   201912       20002     0.0  1.174595
30478   201912       20003     0.0  0.429366
30479   201912       20004     0.0  0.579315
30480   201912       20005     0.0  0.679257
...        ...         ...     ...       ...
31355   201912       21263     0.0  0.314934
31357   201912       21265     0.0  0.802648
31358   201912       21266     0.0  0.451392
31359   201912       21267     0.0  0.029572
31361   201912       21276     0.0  0.744200

[780 rows x 4 columns]

In [27]:
df_future_copy = df_future.copy()

In [28]:
import os
ruta_archivo = f'./datasets/tn_stats_201912.csv'
    
df_stats = pd.DataFrame()

if os.path.exists(ruta_archivo) and ruta_archivo.endswith('.csv'):
    df_stats = pd.read_csv(ruta_archivo, sep=',')

df_stats

      product_id      tn_mean      tn_std
0          20001  1398.344322  293.975388
1          20002  1009.368178  299.585187
2          20003   889.004243  287.951952
3          20004   671.615383  221.310769
4          20005   644.200514  215.220300
...          ...          ...         ...
1159       21271     0.024268    0.019484
1160       21273     0.057242    0.124272
1161       21274     0.067028    0.096980
1162       21276     0.045447    0.041380
1163       21281     0.021060    0.031414

[1164 rows x 3 columns]

In [29]:
df_future_copy = df_future_copy.merge(df_stats, on=['product_id'], how='left')
df_future_copy

     periodo  product_id  target      pred      tn_mean      tn_std
0     201912       20001     0.0  0.983107  1398.344322  293.975388
1     201912       20002     0.0  1.174595  1009.368178  299.585187
2     201912       20003     0.0  0.429366   889.004243  287.951952
3     201912       20004     0.0  0.579315   671.615383  221.310769
4     201912       20005     0.0  0.679257   644.200514  215.220300
..       ...         ...     ...       ...          ...         ...
775   201912       21263     0.0  0.314934     0.089233    0.148180
776   201912       21265     0.0  0.802648     0.089541    0.103219
777   201912       21266     0.0  0.451392     0.094659    0.100530
778   201912       21267     0.0  0.029572     0.092835    0.075836
779   201912       21276     0.0  0.744200     0.045447    0.041380

[780 rows x 6 columns]

In [30]:

df_future_copy['tn'] = df_future_copy['pred'] * df_future_copy['tn_std'] + df_future_copy['tn_mean']
df_future_copy

,periodo,product_id,target,pred,tn_mean,tn_std,tn
0,201912,20001,0.0,0.983107,1398.344322,293.975388,1687.353551
1,201912,20002,0.0,1.174595,1009.368178,299.585187,1361.259501
2,201912,20003,0.0,0.429366,889.004243,287.951952,1012.641029
3,201912,20004,0.0,0.579315,671.615383,221.310769,799.823966
4,201912,20005,0.0,0.679257,644.200514,215.220300,790.390495
...,...,...,...,...,...,...,...
775,201912,21263,0.0,0.314934,0.089233,0.148180,0.135900
776,201912,21265,0.0,0.802648,0.089541,0.103219,0.172390
777,201912,21266,0.0,0.451392,0.094659,0.100530,0.140038
778,201912,21267,0.0,0.029572,0.092835,0.075836,0.095078
779,201912,21276,0.0,0.744200,0.045447,0.041380,0.076242

Vemos cuantos negativos hay

In [31]:
df_future_copy[df_future_copy['tn'] < 0]

Empty DataFrame
Columns: [periodo, product_id, target, pred, tn_mean, tn_std, tn]
Index: []

Reemplazamos los negativos por el promedio de ultimos 12 meses

In [ ]:
# promedio780 = model_lgb.promedio_12_meses_780p()
# df_future = df_future.merge(promedio780, on='product_id', how='left')
# df_future.drop(columns=['target','periodo'], inplace=True)
# df_future.loc[df_future['pred'] < 0, 'pred'] = df_future['tn']
# df_future

     product_id         pred           tn
0         20001  1397.305481  1454.732720
1         20002  1086.538942  1175.437142
2         20003   747.163659   784.976407
3         20004   565.799872   627.215328
4         20005   638.965713   668.270104
..          ...          ...          ...
775       21263     0.029993     0.029993
776       21265     0.791975     0.089541
777       21266     0.094659     0.094659
778       21267     0.092835     0.092835
779       21276     0.045447     0.045447

[780 rows x 3 columns]

Guardamos el archivo

In [32]:
# df_future_copy.drop(columns=['tn'], inplace=True)
# df_future_copy.rename(columns={'pred': 'tn'}, inplace=True)
df_future_copy[['product_id', 'tn']].to_csv("./outputs/predicciones_exp_07_lgb_v9.csv", index=False, sep=',')

Ensemble

In [31]:
df_lgb = df_future_copy[['product_id', 'tn']].rename(columns={'tn': 'tn_lgb'})
df_rl = pd.read_csv("./outputs/predicciones_regresion_lineal_v1.csv", sep=',', encoding='utf-8').rename(columns={'tn': 'tn_rl'})
df_ensemble = df_lgb.merge(df_rl, on='product_id', how='left')
df_ensemble['tn'] = (df_ensemble['tn_lgb'] + df_ensemble['tn_rl']) / 2
df_ensemble[['product_id', 'tn']].to_csv("./outputs/predicciones_exp_07_lgb_v6_ensemble.csv", index=False, sep=',')

In [32]:
df_lgb = df_future_copy[['product_id', 'tn']].rename(columns={'tn': 'tn_lgb'})
df_rl = pd.read_csv("./outputs/predicciones_regresion_lineal_v1.csv", sep=',', encoding='utf-8').rename(columns={'tn': 'tn_rl'})
df_ag = pd.read_csv("./outputs/prediccion_autogluon_2ventanas.csv", sep=',', encoding='utf-8').rename(columns={'tn': 'tn_ag'})
df_ensemble = df_lgb.merge(df_rl, on='product_id', how='left')
df_ensemble = df_ensemble.merge(df_ag, on='product_id', how='left')
df_ensemble['tn'] = (df_ensemble['tn_lgb'] + df_ensemble['tn_rl'] + df_ensemble['tn_ag']) / 3
df_ensemble[['product_id', 'tn']].to_csv("./outputs/predicciones_exp_07_lgb_v6_ensemble_3models.csv", index=False, sep=',')